#!/usr/bin/env python3
"""Batch 33 - technology, digital life, social media, AI, modern dilemmas."""
import json

ADDITIONS33 = {
    "infancia": [
        ("¿Qué tecnología de tu infancia te parecía mágica y hoy es ridícula?", 1),
        ("¿Cuál fue el primer videojuego o dispositivo tecnológico que te marcó?", 1),
        ("¿Cuál era tu programa de televisión favorito y qué te quedó de él?", 1),
        ("¿Tenías reglas en casa sobre cuánto tiempo podías ver televisión o usar la computadora?", 1),
        ("¿Cuál fue la primera vez que accediste a internet y qué hiciste?", 1),
        ("¿Qué música escuchabas de chico y cómo la conseguías?", 1),
        ("¿Había alguna tecnología que tus padres no te dejaban usar y que usabas igual?", 1),
        ("¿Qué cambiaría de tu infancia si hubieras tenido acceso a internet y redes sociales?", 1),
        ("¿Cuál fue el primer celular que tuviste y cómo lo usabas?", 1),
        ("¿Qué extrañás de la manera en que te comunicabas cuando eras chico, antes del celular?", 1),
        ("¿La tecnología de tu infancia te conectaba más o menos con las personas que querías?", 1),
        ("¿Hubo alguna película o serie de ciencia ficción que moldeo cómo imaginabas el futuro?", 1),
        ("¿De qué manera la falta de internet en tu infancia fue una ventaja?", 1),
        ("¿Qué cosa de la infancia digital de los chicos de hoy envidias o te alegra no haber tenido?", 1),
        ("¿Cuál fue el primer aparato tecnológico que fue tuyo y solo tuyo?", 1),
        ("¿Qué te enseñó la tecnología de tu infancia sobre la paciencia?", 2),
        ("¿De qué manera la tecnología que consumías de chico formó tu manera de pensar hoy?", 2),
        ("¿Qué diferencia en tu desarrollo hubiera tenido tener redes sociales desde los 10 años?", 2),
        ("¿Cómo era tu imaginación de chico sin algoritmos que te digan qué consumir?", 2),
        ("¿Qué te perdiste por no tener internet en tu infancia y qué ganaste?", 2),
        ("¿Qué rol jugaba la tecnología en la dinámica de tu familia cuando eras chico?", 2),
        ("¿La infancia sin redes sociales te hizo más o menos capaz de manejar el rechazo?", 3),
        ("¿Qué impacto hubiera tenido en tu identidad crecer con el acceso a información que tienen los chicos hoy?", 3),
        ("¿Qué parte de vos se formó gracias a tener que aburrirte sin pantallas?", 3),
        ("¿Si pudieras darle acceso a internet a tu yo de 8 años, lo harías? ¿Por qué?", 3),
        ("¿Qué cosa de tu infancia analógica no cambiarías por nada de lo que ofrece la infancia digital?", 3),
        ("¿Cómo te hubiera formado diferente crecer con validación social constante de redes sociales?", 3),
        ("¿Qué parte de tu carácter existe porque no tenías pantallas que te distraijeran de vos mismo?", 3),
    ],

    "futuro": [
        ("¿Cuál es la tecnología que más cambiará tu vida en los próximos 10 años?", 1),
        ("¿Te imaginas usando inteligencia artificial en tu vida cotidiana futura de manera habitual?", 1),
        ("¿Qué tecnología actual te parece que va a desaparecer pronto?", 1),
        ("¿Cuánto tiempo de pantalla imaginás en tu vida ideal del futuro?", 1),
        ("¿Te imaginás trabajando con o junto a inteligencia artificial en el futuro?", 1),
        ("¿Qué tecnología futura te genera más expectativa?", 1),
        ("¿Te preocupa lo que la inteligencia artificial va a cambiar en tu profesión o área?", 1),
        ("¿Imaginás un futuro donde te desconectás digitalmente de manera intencional?", 1),
        ("¿Qué relación querés tener con la tecnología en el futuro: más integrada o más distante?", 1),
        ("¿Qué cosa de tu vida digital actual querés haber cambiado en 5 años?", 1),
        ("¿Cómo te imaginás la educación cuando seas mayor o cuando tus hijos crezcan?", 1),
        ("¿Qué tecnología te parece que va a resolver algo importante de tu vida?", 1),
        ("¿Cómo querés manejar la privacidad digital en el futuro?", 1),
        ("¿Te gustaría conectar tu mente a una computadora si fuera posible y seguro?", 1),
        ("¿Qué límite tecnológico querés establecerte antes de que sea demasiado tarde?", 1),
        ("¿Cuánto de tu futuro está determinado por algoritmos y cuánto por vos?", 2),
        ("¿Cómo la inteligencia artificial va a cambiar lo que valorás de vos mismo profesionalmente?", 2),
        ("¿Qué habilidades humanas querés desarrollar justamente porque ninguna IA puede reemplazarlas?", 2),
        ("¿Cómo querés que sea tu relación con la tecnología cuando seas viejo?", 2),
        ("¿Qué futuro tecnológico te genera angustia y cómo te preparás para él?", 2),
        ("¿Hay algún futuro tecnológico que te resulta emocionalmente perturbador?", 2),
        ("¿Qué parte de tu humanidad querés proteger activamente del avance tecnológico?", 3),
        ("¿Cómo te imaginás encontrando significado en un mundo donde las máquinas hacen casi todo mejor?", 3),
        ("¿Qué cosa completamente humana querés que siga siendo solo humana en el futuro?", 3),
        ("¿Si la IA pudiera hacer tu trabajo mejor que vos, qué harías con tu tiempo?", 3),
        ("¿Cómo el avance tecnológico cambia lo que significa ser humano para vos?", 3),
        ("¿Qué le querés transmitir a las generaciones futuras sobre cómo relacionarse con la tecnología?", 3),
        ("¿En qué punto la tecnología deja de ser herramienta y se convierte en algo que te define?", 3),
    ],

    "amor": [
        ("¿Cómo cambia el amor cuando la principal comunicación es digital?", 1),
        ("¿Tuviste alguna historia de amor que empezó en redes sociales o por app?", 1),
        ("¿Qué cosas de una pareja no podés juzgar bien a través de una pantalla?", 1),
        ("¿Cuánto tiempo de pantalla en pareja es demasiado para vos?", 1),
        ("¿Las redes sociales te ayudaron o complicaron en el amor?", 1),
        ("¿Qué dice de una relación la manera en que la pareja gestiona las redes sociales?", 1),
        ("¿Qué límites con la tecnología son importantes para vos en una pareja?", 1),
        ("¿Alguna vez un mensaje de texto o algo en redes causó un conflicto de pareja?", 1),
        ("¿Cómo el celular cambia la dinámica de estar con alguien que amás?", 1),
        ("¿Qué parte del romance tradicional extrañás o valoras en la era digital?", 1),
        ("¿Cómo querés que sea la relación de tu pareja con las redes sociales?", 1),
        ("¿El amor a distancia por videollamada funciona para vos?", 1),
        ("¿Qué cosa de las apps de citas te parece que daña la manera de conectar?", 1),
        ("¿Cómo sabés que alguien te interesa de verdad y no es performance digital?", 1),
        ("¿Cuál es la señal digital que más te dice que alguien está presente en la relación?", 1),
        ("¿Cómo las redes sociales cambian los celos, la confianza, y la privacidad en el amor?", 2),
        ("¿Qué cosas sobre una persona no podés conocer si solo la ves en redes?", 2),
        ("¿De qué manera la sobreexposición digital cambia la profundidad de una relación?", 2),
        ("¿Cómo el amor sobrevive a la cultura de la inmediatez digital?", 2),
        ("¿Qué dice de vos cómo usás el celular cuando estás con alguien que amás?", 2),
        ("¿Cuándo fue la última vez que dejaste el celular completamente para estar presente con alguien?", 2),
        ("¿Cómo la tecnología cambió lo que significa estar ausente o presente en el amor?", 3),
        ("¿Qué parte del amor se pierde cuando todo se comunica por texto?", 3),
        ("¿Cómo el acceso constante a miles de opciones en apps cambia la capacidad de comprometerse?", 3),
        ("¿Qué necesitás de una relación que ningún algoritmo puede darte?", 3),
        ("¿Cómo la mirada de las redes sociales cambia la manera en que vivís y mostrás tu vida amorosa?", 3),
        ("¿Qué cosa de tu manera de amar existía antes de los smartphones y querés recuperar?", 3),
        ("¿Cómo el amor resiste en un mundo donde todo lo que sentís puede ser consumido como contenido?", 3),
    ],

    "familia": [
        ("¿Cómo usan las pantallas en tu familia y qué conflictos genera eso?", 1),
        ("¿Cuál fue el primer dispositivo tecnológico que entró en tu familia y cómo cambió la dinámica?", 1),
        ("¿Hay reglas en tu familia sobre el uso del celular en las comidas o reuniones?", 1),
        ("¿Cómo mantener el contacto con familia lejana cambió con la tecnología?", 1),
        ("¿Qué dice del estado de una familia cómo usa (o no usa) el celular junta?", 1),
        ("¿Hay algún familiar tuyo que rechaza la tecnología y cómo lo manejás?", 1),
        ("¿Cómo la tecnología cambió el rol de abuelos y abuelas en la vida familiar?", 1),
        ("¿Qué momento familiar perdió calidad por culpa de las pantallas?", 1),
        ("¿Cómo te gustaría que tu familia futura manejara la tecnología?", 1),
        ("¿Alguna vez la tecnología conectó a tu familia en un momento difícil?", 1),
        ("¿Qué ritual o tradición familiar querés que sobreviva a la era digital?", 1),
        ("¿Cuánto de la historia familiar guardás digitalmente y cuánto en objetos físicos?", 1),
        ("¿Cómo compartís con tu familia contenido digital (fotos, memes, música) y qué dice eso de su vínculo?", 1),
        ("¿Alguna vez un conflicto familiar se trasladó o amplificó por un grupo de WhatsApp?", 1),
        ("¿Cómo querés que tus hijos o sobrinos se relacionen con la tecnología?", 1),
        ("¿Cómo la tecnología cambió el poder dentro de tu familia — quién sabe más, quién conecta, quién excluye?", 2),
        ("¿Qué conversaciones familiares importantes nunca tendrían que haberse dado por texto o WhatsApp?", 2),
        ("¿De qué manera el acceso de tus hijos o familiares más jóvenes a internet cambia la dinámica con ellos?", 2),
        ("¿Cómo las redes sociales afectan la imagen que tu familia construye hacia afuera y cómo te sentís con eso?", 2),
        ("¿Qué pierden las familias cuando las pantallas reemplazan el aburrimiento compartido?", 2),
        ("¿Cómo la tecnología te ayudó a mantener (o dañó) relaciones familiares difíciles?", 2),
        ("¿Qué conversación familiar importante postergás porque es más fácil no tenerla en persona?", 3),
        ("¿Cómo el acceso constante a pantallas cambia la manera en que los chicos de tu familia desarrollan vínculos?", 3),
        ("¿Qué parte de la identidad familiar se pierde cuando todo se documenta para redes?", 3),
        ("¿Si tu familia del futuro pudiera elegir un nivel de uso tecnológico, qué elegirías vos?", 3),
        ("¿Cómo la tecnología amplificó tanto lo mejor como lo peor de tu dinámica familiar?", 3),
        ("¿Qué necesitás del espacio familiar que las pantallas no pueden darte?", 3),
        ("¿Qué parte de la vida familiar querés que sea completamente analógica, sin registro digital?", 3),
    ],

    "amistades": [
        ("¿Cómo cambió tu círculo de amigos con las redes sociales?", 1),
        ("¿Tenés amigos que solo existen digitalmente y que nunca viste en persona?", 1),
        ("¿Qué significa para vos que alguien te siga o te deje de seguir en redes?", 1),
        ("¿Cuánto del mantenimiento de tus amistades es digital vs. presencial?", 1),
        ("¿Las redes sociales te acercaron o alejaron de tus amigos?", 1),
        ("¿Cómo sabes que una amistad digital es real?", 1),
        ("¿Hay alguna amistad que sobrevive principalmente por WhatsApp o redes?", 1),
        ("¿Qué cosas de un amigo no podés conocer si solo interactuás digitalmente?", 1),
        ("¿Cuál fue el primer amigo que hiciste por internet?", 1),
        ("¿Cómo las redes sociales cambiaron los celos y las comparaciones entre amigos?", 1),
        ("¿Qué significa para vos que un amigo no tenga redes sociales?", 1),
        ("¿Alguna vez una amistad se complicó o terminó por algo que pasó en redes o WhatsApp?", 1),
        ("¿Qué parte de una amistad requiere presencia física que no puede reemplazarse digitalmente?", 1),
        ("¿Cuántos contactos tenés en el celular con quienes realmente tendrías una conversación real?", 1),
        ("¿Cómo querés que sean tus amistades en un mundo cada vez más digital?", 1),
        ("¿Cómo la cultura de la inmediatez digital cambió la paciencia que tenés con tus amigos?", 2),
        ("¿Qué dice de una amistad la manera en que dos personas se comunican digitalmente?", 2),
        ("¿Alguna vez las redes sociales te mostraron algo de un amigo que cambió tu percepción de él/ella?", 2),
        ("¿De qué manera la sobreexposición a la vida de tus amigos en redes afecta cómo los ves?", 2),
        ("¿Qué amistades perdiste porque la distancia digital las fue diluyendo?", 2),
        ("¿Cómo querés equilibrar la conexión digital y la presencia real con tus amigos?", 2),
        ("¿Cuántas amistades tenés que sobrevivirían si mañana desaparecieran todas las redes?", 3),
        ("¿Qué parte de vos que mostrás en redes es auténtica y qué parte es performance para tus amigos?", 3),
        ("¿Cómo la posibilidad de conectar con miles de personas a la vez cambia la profundidad de cada amistad?", 3),
        ("¿Qué necesitás de una amistad que ninguna plataforma digital puede replicar?", 3),
        ("¿Cómo la comparación constante habilitada por redes afecta la calidad de tus amistades?", 3),
        ("¿Qué amistades construiste digitalmente que terminaron siendo más reales que algunas presenciales?", 3),
        ("¿Cómo querés que sea el espacio de tus amistades más importantes en un mundo hiper-conectado?", 3),
    ],

    "exs": [
        ("¿Seguís a algún ex en redes sociales? ¿Por qué sí o por qué no?", 1),
        ("¿Alguna vez stalkeaste a un ex en redes y qué encontraste?", 1),
        ("¿Cómo las redes sociales complicaron o facilitaron procesar una ruptura?", 1),
        ("¿Qué hace a las rupturas más difíciles en la era de las redes sociales?", 1),
        ("¿Alguna vez bloqueaste a alguien en redes después de una ruptura? ¿Cómo fue?", 1),
        ("¿Qué significa para vos ver que un ex está bien (o mal) en redes?", 1),
        ("¿Alguna vez publicaste algo en redes después de una ruptura pensando en que lo iba a ver?", 1),
        ("¿Cómo cambió tu relación con las redes después de una ruptura importante?", 1),
        ("¿Qué fotos o recuerdos digitales guardás de relaciones pasadas?", 1),
        ("¿Alguna vez un ex te contactó por redes después de mucho tiempo y cómo manejaste eso?", 1),
        ("¿Qué hace más difícil cerrar un ciclo cuando el ex sigue visible en tus redes?", 1),
        ("¿Cuánto tiempo tardás en dejar de revisar las redes de alguien después de una ruptura?", 1),
        ("¿Qué dice de una ruptura la manera en que los dos la manejan en redes?", 1),
        ("¿Preferís borrar completamente las fotos de una relación pasada o guardarlas?", 1),
        ("¿Cómo las apps de citas cambiaron la experiencia de volver a empezar después de una ruptura?", 1),
        ("¿De qué manera la exposición digital a la vida de un ex después de una ruptura complica el proceso de sanación?", 2),
        ("¿Qué significa para vos que un ex te borre de redes sociales?", 2),
        ("¿Cómo el registro digital de una relación (fotos, chats, redes) cambia la manera de procesarla?", 2),
        ("¿Alguna vez las redes te mostraron algo de un ex que cambió tu versión de la historia?", 2),
        ("¿Cómo querés manejar la presencia digital de relaciones pasadas en el futuro?", 2),
        ("¿Qué aprendiste sobre vos mismo en cómo manejás las redes después de una ruptura?", 2),
        ("¿Qué harías si pudieras borrar todo registro digital de una relación pasada?", 3),
        ("¿Cómo la visibilidad constante de la vida de un ex en redes cambia el duelo de una ruptura?", 3),
        ("¿Qué dice de una relación que termine principalmente en chats y no en persona?", 3),
        ("¿Cómo la tecnología cambió lo que significa desaparecer de la vida de alguien?", 3),
        ("¿Qué conversación de cierre con alguien del pasado nunca debería haber pasado por texto?", 3),
        ("¿De qué manera ver a un ex feliz en redes te revela algo sobre vos mismo?", 3),
        ("¿Qué parte de una relación pasada existe ahora solo como dato digital y qué sentís con eso?", 3),
    ],

    "personalidad": [
        ("¿Cómo es tu relación con las redes sociales: las disfrutás, te estresan, o las tolerás?", 1),
        ("¿Qué versión de vos mostrás en redes y cuánto se parece a quien sos en persona?", 1),
        ("¿Cómo te afecta el silencio digital — no recibir likes, comentarios, respuestas?", 1),
        ("¿Sos más de producir contenido o de consumirlo?", 1),
        ("¿Qué plataforma digital dice más de tu personalidad y por qué?", 1),
        ("¿Cómo el uso del celular cambia según tu estado emocional?", 1),
        ("¿Alguna vez hiciste un detox digital? ¿Cómo fue?", 1),
        ("¿Qué relación tenés con la notificación: la ignorás, la atendés inmediatamente, o te genera ansiedad?", 1),
        ("¿Cuánto te importa la imagen que proyectás online?", 1),
        ("¿Cómo sabés cuándo estás usando demasiado el celular?", 1),
        ("¿Cuál es la app que más dice de quién sos y qué dice?", 1),
        ("¿Qué cosa hacés en redes de la que no estás del todo orgulloso?", 1),
        ("¿Cómo la tecnología afecta tu concentración y tu capacidad de estar presente?", 1),
        ("¿Qué parte de vos existe solo en el espacio digital?", 1),
        ("¿Cómo sería tu personalidad si mañana desaparecieran todas las redes?", 1),
        ("¿Qué dice de vos la manera en que te presentás online vs. en persona?", 2),
        ("¿Cómo la validación digital (likes, comentarios, seguidores) afecta tu autoestima?", 2),
        ("¿Qué patrón de uso digital refleja algo de tu personalidad que preferirías cambiar?", 2),
        ("¿Cómo la tecnología cambió tu capacidad de tolerar el aburrimiento y la soledad?", 2),
        ("¿Qué parte de tu identidad construís principalmente en el espacio digital?", 2),
        ("¿Cómo querés relacionarte con la tecnología para ser más la versión de vos que querés ser?", 2),
        ("¿Qué parte de tu vida interior se ve más afectada por el uso constante de pantallas?", 3),
        ("¿Cómo el algoritmo que consume te fue moldeando en quién sos hoy sin que te des cuenta?", 3),
        ("¿Qué decisiones importantes de tu vida fueron influenciadas por algo que viste o consumiste digitalmente?", 3),
        ("¿Cómo querés que sea tu relación con la tecnología para proteger lo que más valorás de vos?", 3),
        ("¿Qué parte de vos solo existe cuando estás desconectado?", 3),
        ("¿Cómo la sobreexposición a la vida de los demás en redes cambió tu relación con la tuya propia?", 3),
        ("¿Si pudieras elegir cómo la tecnología te moldea en el futuro, qué elegirías?", 3),
    ],

    "miedos": [
        ("¿Qué te genera más ansiedad en el mundo digital: las redes, el trabajo, la privacidad?", 1),
        ("¿Le tenés miedo a quedarte sin batería o sin internet en un momento crítico?", 1),
        ("¿Qué tecnología te genera desconfianza o miedo?", 1),
        ("¿Te preocupa lo que las empresas tecnológicas saben de vos?", 1),
        ("¿Alguna vez sentiste que perdiste el control de algo por culpa de la tecnología?", 1),
        ("¿Qué miedo relacionado con la inteligencia artificial es el que más te pesa?", 1),
        ("¿Le tenés miedo a la adicción tecnológica: tuya o de alguien que querés?", 1),
        ("¿Qué miedo digital tenés que no le confesarías fácilmente a alguien?", 1),
        ("¿Le tenés miedo a que algo privado tuyo se filtre digitalmente?", 1),
        ("¿Qué es lo que más te asustaría que pasara con tu huella digital después de tu muerte?", 1),
        ("¿El miedo a perderte algo (FOMO) en redes sociales cómo te afecta?", 1),
        ("¿Qué escenario tecnológico del futuro te genera más angustia?", 1),
        ("¿Le tenés miedo a depender demasiado de la tecnología?", 1),
        ("¿Qué te genera más miedo: un mundo sin privacidad o un mundo sin conectividad?", 1),
        ("¿Cómo manejás el miedo a quedar desactualizado tecnológicamente?", 1),
        ("¿De qué manera la exposición constante a noticias y redes amplifica tus miedos?", 2),
        ("¿Qué cosa de tu vida digital te genera una ansiedad que no terminás de controlar?", 2),
        ("¿Cómo el miedo a la obsolescencia tecnológica se conecta con miedos más profundos sobre tu futuro?", 2),
        ("¿Qué miedo sobre la privacidad digital te hace actuar diferente online?", 2),
        ("¿Cómo el consumo de contenido negativo o alarmista digital afecta tus miedos cotidianos?", 2),
        ("¿Qué miedo sobre la inteligencia artificial te resulta más difícil de racionalizar?", 2),
        ("¿Qué miedo profundo sobre el futuro tecnológico de la humanidad llevás y casi nunca expresás?", 3),
        ("¿Cómo la tecnología amplificó miedos que antes podías ignorar más fácilmente?", 3),
        ("¿Qué dice de vos la manera en que reaccionás cuando la tecnología falla o te traiciona?", 3),
        ("¿En qué punto el miedo a la IA o a la tecnología es en realidad miedo a tu propia obsolescencia?", 3),
        ("¿Qué parte de tu futuro te da más miedo en un mundo donde la tecnología avanza más rápido que tu capacidad de adaptarte?", 3),
        ("¿Cómo querés enfrentar los miedos sobre el futuro tecnológico para no dejar que te paralicen?", 3),
        ("¿Qué tecnología te aterra y sin embargo usás todos los días sin cuestionarte?", 3),
    ],

    "logros": [
        ("¿Hay algún logro tuyo que fue posible gracias a la tecnología o internet?", 1),
        ("¿Qué habilidad digital desarrollaste de la que estés orgulloso?", 1),
        ("¿Alguna vez aprendiste algo importante completamente por tu cuenta gracias a internet?", 1),
        ("¿Cómo la tecnología amplificó algún logro tuyo que de otra manera hubiera sido más difícil?", 1),
        ("¿Hay algún proyecto digital del que estés orgulloso?", 1),
        ("¿Qué logro profesional o personal fue posible gracias a una conexión que hiciste online?", 1),
        ("¿Cómo la tecnología cambió la escala de lo que podés lograr?", 1),
        ("¿Usás alguna herramienta digital que amplificó tu productividad de manera significativa?", 1),
        ("¿Alguna vez la tecnología te ayudó a aprender algo que cambió el rumbo de tu vida?", 1),
        ("¿Qué cosa lograste primero online antes de poder hacerlo en el mundo físico?", 1),
        ("¿La tecnología te abrió una oportunidad que de otra manera nunca hubiera llegado?", 1),
        ("¿Hay algún logro tuyo que nadie hubiera podido imaginar antes de que existiera internet?", 1),
        ("¿Cómo la democratización del conocimiento digital cambió lo que podés lograr?", 1),
        ("¿Qué meta del futuro es posible gracias a herramientas tecnológicas que hoy existen?", 1),
        ("¿Cómo querés usar la tecnología de manera más intencional para lograr lo que más querés?", 1),
        ("¿Cómo la tecnología cambió la definición de logro para vos?", 2),
        ("¿Qué logro digital tuyo requirió el mismo esfuerzo o más que un logro análogo y cómo lo valoras?", 2),
        ("¿De qué manera la tecnología puede ser tanto habilitadora como obstáculo para tus logros?", 2),
        ("¿Cómo vas a usar la inteligencia artificial para lograr metas que hoy parecen inalcanzables?", 2),
        ("¿Qué logro tuyo sería imposible de replicar hoy por alguien sin acceso a la misma tecnología?", 2),
        ("¿Cómo la tecnología cambió lo que te parece un logro genuino vs. algo superficial?", 2),
        ("¿Qué potencial tuyo seguiría sin desarrollarse si no existiera la tecnología que tenés hoy?", 3),
        ("¿Cómo el acceso a internet y la tecnología cambió fundamentalmente el techo de lo que podés lograr?", 3),
        ("¿Qué querés haber creado o construido digitalmente antes de morir?", 3),
        ("¿Cómo la tecnología puede ser el vehículo para el legado que querés dejar?", 3),
        ("¿De qué manera la tecnología te obliga a redefinir constantemente qué significa el éxito?", 3),
        ("¿Qué logro tecnológico querés que sea parte de cómo te recuerdan?", 3),
        ("¿Cómo querés usar la tecnología no para escapar de la vida sino para ampliar lo que significa vivirla?", 3),
    ],

    "sinFiltro": [
        ("¿Alguna vez stalkeaste a alguien en redes de manera bastante intensa?", 1),
        ("¿Qué cosa buscás en internet que nunca confesarías en voz alta?", 1),
        ("¿Alguna vez creaste un perfil falso o anónimo online?", 1),
        ("¿Qué parte de tu vida cuidas de que no quede registro digital?", 1),
        ("¿Alguna vez le dijiste algo a alguien por mensaje que nunca le hubieras dicho en persona?", 1),
        ("¿Cuánto de lo que publicás en redes es genuino y cuánto es performance?", 1),
        ("¿Qué cosa te generaría más vergüenza que alguien viera en tu historial de búsqueda?", 1),
        ("¿Alguna vez usaste el anonimato de internet para decir o hacer algo que no harías con tu nombre?", 1),
        ("¿Cuánto tiempo real perdés en redes sociales vs. cuánto reconocés cuando te preguntan?", 1),
        ("¿Qué foto o contenido publicaste alguna vez del que te arrepentís?", 1),
        ("¿Alguna vez usaste el celular para evitar una conversación difícil en persona?", 1),
        ("¿Qué cosa de internet consumís en privado que en público negarías?", 1),
        ("¿Alguna vez enviaste un mensaje a la persona equivocada y qué pasó?", 1),
        ("¿Qué cosa hacés en redes cuando estás emocionalmente al límite que después te arrepentís?", 1),
        ("¿Cuánta de tu vida sexual o romántica existe o existió solo en el espacio digital?", 1),
        ("¿Qué te dice el historial de búsqueda de tu celular que no querés admitir sobre vos?", 2),
        ("¿Cómo la soledad o el aburrimiento cambia lo que hacés digitalmente?", 2),
        ("¿Alguna vez la tecnología te permitió hacer algo que en persona nunca te hubieras animado?", 2),
        ("¿Qué persona de tu vida digital sabe cosas de vos que nadie en tu vida real sabe?", 2),
        ("¿Cómo el anonimato digital saca una parte de vos que normalmente controlás?", 2),
        ("¿Qué cosa de tu uso de la tecnología reconocés como un problema que todavía no te animaste a cambiar?", 2),
        ("¿Qué pasaría si alguien tuviera acceso completo a tu celular sin filtros?", 3),
        ("¿Cuánto de quien sos online es una versión mejorada, empeorada, o directamente falsa de quien sos?", 3),
        ("¿Qué adicción digital tenés que en privado reconocés pero en público minimizás?", 3),
        ("¿Cómo la tecnología habilitó algo de vos que preferirías que no existiera?", 3),
        ("¿Qué cosa de tu vida digital te avergonzaría que las personas que más querés vieran?", 3),
        ("¿Si pudieras borrar una parte de tu huella digital, qué borrarías y por qué?", 3),
        ("¿Qué te revela tu relación con la tecnología sobre tu relación con vos mismo?", 3),
    ],
}


def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]


def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS33:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS33[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")


if __name__ == "__main__":
    main()
