#!/usr/bin/env python3
"""Batch 22 - communication styles, active listening, saying hard things, silence, tone."""
import json

ADDITIONS22 = {
    "infancia": [
        ("¿Cómo aprendiste a comunicarte dentro de tu familia y qué tan útil fue ese aprendizaje afuera?", 1),
        ("¿Cuándo fue la primera vez que escuchaste a alguien de verdad sin pensar en lo que ibas a responder?", 1),
        ("¿Qué cosa de la infancia nunca dijiste y qué hubiera pasado si la decías?", 1),
        ("¿Cuándo fue la primera vez que el silencio en tu familia comunicó algo más fuerte que las palabras?", 1),
        ("¿Qué aprendiste de chico sobre cómo pedir lo que necesitabas?", 1),
        ("¿Cuándo fue la primera vez que las palabras de alguien te cambiaron sin que esa persona lo supiera?", 1),
        ("¿Qué cosa de la infancia nunca te explicaron y te la tuviste que explicar solo?", 1),
        ("¿Cuándo fue la primera vez que escuchar fue más difícil que hablar?", 1),
        ("¿Qué aprendiste de chico sobre cómo se dice algo difícil?", 1),
        ("¿Cuándo fue la primera vez que el tono de alguien fue más importante que sus palabras?", 1),
        ("¿Qué cosa de la infancia que nadie te dijo con palabras entendiste igual?", 1),
        ("¿Cuándo fue la primera vez que el silencio fue más elocuente que cualquier explicación?", 1),
        ("¿Qué cosa aprendiste de la comunicación de chico que hoy te parece un obstáculo?", 1),
        ("¿Cuándo fue la primera vez que alguien te escuchó de verdad y qué cambió eso?", 1),
        ("¿Qué cosa de la infancia te costó decir que de adulto ya podés decir con más facilidad?", 1),
        ("¿Cuándo fue la primera vez que entendiste que la forma de decir algo era tan importante como lo que decías?", 1),
        ("¿Qué patrón comunicativo de tu infancia todavía repetís sin darte cuenta?", 1),
        ("¿Cuándo fue la primera vez que las palabras no alcanzaron para decir lo que sentías?", 1),
        ("¿Qué cosa de la infancia que no se hablaba en tu familia aprendiste a hablar después?", 1),
        ("¿Cuándo fue la primera vez que alguien en tu familia dijo algo difícil de una manera que te ayudó?", 1),
        ("¿Qué cosa de cómo te comunicaban afecto en la infancia todavía buscás hoy?", 1),
        ("¿Cuándo fue la primera vez que algo que no se dijo pesó más que lo que se dijo?", 1),
        ("¿Qué aprendiste de chico sobre cuándo callar que de adulto todavía aplicás?", 1),
        ("¿Cuándo fue la primera vez que alguien entendió lo que querías decir sin que lo dijeras?", 1),
        ("¿Qué cosa de la infancia que se decía en casa de cierta manera hoy te parece que se podría haber dicho mejor?", 1),
        ("¿Cuándo fue la primera vez que las palabras de alguien te hicieron sentir que eras comprendido?", 1),
        ("¿Qué cosa de la comunicación de tu infancia te gustaría haber tenido diferente?", 1),
        ("¿Cuándo fue la primera vez que algo que no se dijo en la infancia afectó algo de tu vida adulta?", 1),
        ("¿Qué cosa de la infancia que se callaba te hubiera cambiado saber?", 1),
        ("¿Cuándo fue la primera vez que el silencio de alguien fue la respuesta más honesta?", 1),
        ("¿Qué patrón de comunicación de la infancia te costó más trabajo reaprender de adulto?", 2),
        ("¿Cuándo fue la primera vez que algo que no se dijo en tu familia generó un daño que duró?", 2),
        ("¿Qué cosa que nunca dijiste en la infancia todavía la llevás como peso?", 2),
        ("¿Cuándo fue la primera vez que entendiste que escuchar era una habilidad que había que aprender?", 2),
        ("¿Qué cosa de la comunicación de tu infancia reprodujiste en relaciones adultas antes de darte cuenta?", 2),
        ("¿Cuándo fue la primera vez que decir algo difícil fue exactamente lo más amoroso?", 2),
        ("¿Qué aprendiste de la infancia sobre el silencio que todavía no terminás de cuestionarte?", 2),
        ("¿Cuándo fue la primera vez que algo que no se dijo en la infancia lo tuviste que descubrir solo y fue duro?", 2),
        ("¿Qué forma de comunicarte que tenés hoy viene directamente de algo que aprendiste en la infancia?", 2),
        ("¿Cuándo fue la primera vez que escuchar activamente cambió una conversación que iba mal?", 2),
        ("¿Qué cosa de la infancia que se callaba ahora entendés por qué se callaba?", 2),
        ("¿Cuándo fue la primera vez que tus palabras dañaron a alguien que querías y cómo lo procesaste?", 2),
        ("¿Qué forma de comunicar que heredaste de la infancia todavía te genera conflicto?", 2),
        ("¿Qué cosa que nunca se dijo en tu familia de la infancia todavía resuena en cómo te comunicás hoy?", 3),
        ("¿Cuándo fue la primera vez que el silencio de la infancia fue más dañino que cualquier palabra?", 3),
        ("¿Qué cosa que se dijo en la infancia todavía la escuchás aunque haya pasado mucho tiempo?", 3),
        ("¿Cuándo fue la primera vez que algo de la comunicación de tu infancia te mostró exactamente lo que no querías repetir?", 3),
        ("¿Qué patrón de silencio de la infancia todavía no terminás de romper aunque quieras?", 3),
        ("¿Cuándo fue la primera vez que las palabras de alguien de la infancia te formaron de una manera que no elegiste?", 3),
        ("¿Qué cosa que se dijo o no se dijo en tu infancia todavía tiene más poder sobre vos de lo que querías?", 3),
        ("¿Cuándo fue la primera vez que algo que no se dijo en la infancia hizo más daño que cualquier cosa dicha?", 3),
    ],

    "futuro": [
        ("¿Qué conversación del futuro te da más miedo y más ganas de tener al mismo tiempo?", 1),
        ("¿Cómo imaginás que vas a comunicarte en el futuro con las personas que más querés?", 1),
        ("¿Qué cosa que todavía no dijiste necesitás decir antes de que sea tarde?", 1),
        ("¿Cuándo fue la última vez que pensaste en qué le querrías decir a alguien que ya no va a estar?", 1),
        ("¿Qué versión futura de vos se comunica mejor que la actual y qué necesitaría cambiar para llegar?", 1),
        ("¿Qué conversación pendiente del futuro te genera más ansiedad?", 1),
        ("¿Cómo querés que sea tu comunicación con tus hijos o con quienes vengan después de vos?", 1),
        ("¿Qué cosa que todavía no decís a las personas que querés deberías empezar a decir?", 1),
        ("¿Cuándo fue la última vez que pensaste en qué querrías que dijeran de vos cuando ya no estés?", 1),
        ("¿Qué versión de vos comunicador querés ser que todavía no sos?", 1),
        ("¿Qué conversación difícil del futuro estás postergando y qué necesitás para tenerla?", 1),
        ("¿Cómo imaginás que van a ser tus conversaciones difíciles en el futuro?", 1),
        ("¿Qué cosa que no decís hoy querés empezar a decir?", 1),
        ("¿Cuándo fue la última vez que imaginaste cómo sería escuchar mejor de lo que escuchás?", 1),
        ("¿Qué forma de comunicarte querés que sea distinta en el futuro?", 1),
        ("¿Qué conversación del futuro te gustaría no tener que tener pero sabés que es inevitable?", 1),
        ("¿Cómo querés que te recuerden comunicándote con las personas que amás?", 1),
        ("¿Qué cosa que todavía no dijiste será más difícil decirla cuanto más tiempo pase?", 1),
        ("¿Cuándo fue la última vez que pensaste en qué te gustaría escuchar de alguien antes de que ya no sea posible?", 1),
        ("¿Qué aprendizaje sobre la comunicación querés llevar al futuro?", 1),
        ("¿Qué conversación pendiente te genera más urgencia?", 1),
        ("¿Cómo imaginás que vas a manejar los silencios en tus relaciones del futuro?", 1),
        ("¿Qué cosa que expresás mal hoy querés aprender a decir mejor?", 1),
        ("¿Cuándo fue la última vez que imaginaste cómo sería decir algo difícil sin miedo?", 1),
        ("¿Qué mensaje querés que quede claro para las personas que más importan en tu vida?", 1),
        ("¿Qué conversación del futuro esperás con más ganas?", 1),
        ("¿Cómo querés que te recuerden cuando ya no estés en términos de cómo te comunicabas?", 1),
        ("¿Qué cosa que no expresás todavía empezaría a cambiar todo si la dijeras?", 1),
        ("¿Cuándo fue la última vez que imaginaste cómo sería una conversación honesta con alguien importante?", 1),
        ("¿Qué legado de comunicación querés dejar?", 1),
        ("¿Qué conversación difícil del futuro estás postergando que ya debería haber pasado?", 2),
        ("¿Cuándo fue la última vez que el silencio fue una elección del futuro que después lamentaste?", 2),
        ("¿Qué cosa que no decís hoy va a ser más difícil decir después y aun así no la decís?", 2),
        ("¿Cuándo fue la última vez que imaginaste qué pasaría si tuvieras la conversación más difícil que postergás?", 2),
        ("¿Qué forma de comunicarte querés cambiar pero todavía no encontraste cómo?", 2),
        ("¿Cuándo fue la última vez que pensaste en qué querrías decirle a alguien importante si supieran que no iban a volver a verse?", 2),
        ("¿Qué conversación pendiente ya tiene un peso que se acumula?", 2),
        ("¿Cuándo fue la última vez que imaginaste cómo sería escuchar de verdad a alguien que todavía no escuchaste bien?", 2),
        ("¿Qué cosa que no decís te está costando algo que no querés perder?", 2),
        ("¿Cuándo fue la última vez que el miedo a cómo reaccionaría alguien te hizo callar algo importante?", 2),
        ("¿Qué conversación del futuro más te aterra tener y más necesitás tener?", 2),
        ("¿Cuándo fue la última vez que pensaste en qué querrías haber dicho en el pasado y no dijiste?", 2),
        ("¿Qué forma de comunicar que tenés hoy querés que sea distinta en el futuro aunque todavía no sepas cómo cambiarla?", 2),
        ("¿Qué conversación del futuro que estás postergando ya afecta algo sin que la hayas tenido?", 3),
        ("¿Cuándo fue la última vez que el silencio fue una forma de cuidar algo pero también de dejarlo morir?", 3),
        ("¿Qué cosa que no dijiste nunca va a poder decirse igual si esperas más?", 3),
        ("¿Cuándo fue la última vez que imaginaste cómo sería quedar sin tiempo para decir lo que más importa?", 3),
        ("¿Qué conversación difícil del futuro cambiaría todo si la tuvieras hoy?", 3),
        ("¿Cuándo fue la última vez que pensaste en qué diría de vos alguien que ya no está si pudiera hablar?", 3),
        ("¿Qué cosa que no decís hoy va a ser tu mayor arrepentimiento si nunca la decís?", 3),
        ("¿Cuándo fue la última vez que el miedo a una conversación fue más grande que el costo de no tenerla?", 3),
    ],

    "amor": [
        ("¿Cómo le decís a alguien que lo amás sin usar esas palabras?", 1),
        ("¿Cuándo fue la última vez que escuchaste a tu pareja o a alguien que amás sin preparar tu respuesta?", 1),
        ("¿Qué cosa difícil le dijiste a alguien que amabas que fue exactamente lo correcto aunque costara?", 1),
        ("¿Cuándo fue la última vez que el silencio con alguien que amás fue cómodo y no tenso?", 1),
        ("¿Qué tono usás con la persona que amás que no usarías con nadie más?", 1),
        ("¿Cuándo fue la última vez que expresaste algo que sentías sin filtrar nada?", 1),
        ("¿Qué cosa que necesitás en el amor todavía no aprendiste a pedir con claridad?", 1),
        ("¿Cuándo fue la última vez que alguien que amabas te entendió sin que lo dijeras?", 1),
        ("¿Qué cosa en el amor te cuesta más escuchar que decir?", 1),
        ("¿Cuándo fue la última vez que el tono de una conversación cambió todo?", 1),
        ("¿Qué cosa que decís en el amor dice más de vos que de la otra persona?", 1),
        ("¿Cuándo fue la última vez que le dijiste a alguien lo que sentías aunque fuera incómodo?", 1),
        ("¿Qué forma de comunicar el amor aprendiste que no sabías antes?", 1),
        ("¿Cuándo fue la última vez que en una conversación de pareja te detuviste a escuchar en lugar de defender?", 1),
        ("¿Qué cosa que no decís en el amor empieza a pesar más de lo que querés?", 1),
        ("¿Cuándo fue la última vez que el silencio en una conversación de amor fue exactamente lo que necesitaban?", 1),
        ("¿Qué le decís a alguien que amás cuando no sabés qué decirle?", 1),
        ("¿Cuándo fue la última vez que expresaste algo en el amor y fue recibido de una manera distinta a como lo querías?", 1),
        ("¿Qué cosa del amor que sentís todavía no expresás bien?", 1),
        ("¿Cuándo fue la última vez que una conversación honesta mejoró algo que estaba dañado?", 1),
        ("¿Qué forma de decir las cosas aprendiste que mejoró tus relaciones amorosas?", 1),
        ("¿Cuándo fue la última vez que el tono fue más importante que el contenido en una conversación amorosa?", 1),
        ("¿Qué cosa que sentís en el amor le cuesta más trabajo decirle a alguien?", 1),
        ("¿Cuándo fue la última vez que en el amor callar fue más honesto que hablar?", 1),
        ("¿Qué cosa del amor que sentís cuando lo decís suena diferente de lo que sentís?", 1),
        ("¿Cuándo fue la última vez que escuchar de verdad cambió lo que pensabas de una situación?", 1),
        ("¿Qué te cuesta más decir en el amor: lo que necesitás o lo que sentís?", 1),
        ("¿Cuándo fue la última vez que una conversación en el amor fue exactamente lo que ambos necesitaban?", 1),
        ("¿Qué forma de comunicarte en el amor querés mejorar?", 1),
        ("¿Cuándo fue la última vez que algo que no dijiste en el amor fue más elocuente que cualquier palabra?", 1),
        ("¿Qué cosa que no decís en el amor empieza a crear distancia sin que lo notes del todo?", 2),
        ("¿Cuándo fue la última vez que dijiste algo difícil en el amor y valió la pena aunque fuera incómodo?", 2),
        ("¿Qué patrón de comunicación en el amor repetís que sabés que no funciona pero todavía no cambiaste?", 2),
        ("¿Cuándo fue la última vez que el silencio en el amor fue una elección que después lamentaste?", 2),
        ("¿Qué cosa del amor que sentís le cuesta decirle a la persona que amás porque no sabés cómo va a reaccionar?", 2),
        ("¿Cuándo fue la última vez que escuchar en el amor fue más difícil que cualquier cosa que tenías que decir?", 2),
        ("¿Qué forma de comunicar que tenés en el amor viene de algo que aprendiste en la infancia y ya deberías haber cambiado?", 2),
        ("¿Cuándo fue la última vez que algo que no dijiste en el amor dañó algo que importaba?", 2),
        ("¿Qué cosa difícil todavía no le dijiste a alguien que amás que debería saber?", 2),
        ("¿Cuándo fue la última vez que una conversación en el amor cambió algo que parecía inamovible?", 2),
        ("¿Qué cosa que decís en el amor tiene un impacto que no terminás de entender?", 2),
        ("¿Cuándo fue la última vez que el miedo a una conversación en el amor fue más grande que el amor mismo?", 2),
        ("¿Qué cosa que no decís en el amor es la que más pesa?", 2),
        ("¿Qué conversación que nunca tuviste en el amor podría cambiar todo y seguís sin tenerla?", 3),
        ("¿Cuándo fue la última vez que algo que no dijiste en el amor fue exactamente lo que hizo que algo se rompiera?", 3),
        ("¿Qué cosa del amor que sentís es tan difícil de decir que a veces preferís no sentirla?", 3),
        ("¿Cuándo fue la última vez que el silencio en el amor fue una forma de mentir?", 3),
        ("¿Qué cosa que no decís en el amor va a ser tu mayor arrepentimiento si el tiempo se acaba?", 3),
        ("¿Cuándo fue la última vez que una conversación honesta en el amor te mostró algo de vos mismo que no querías ver?", 3),
        ("¿Qué cosa difícil que necesitás decir en el amor estás esperando el momento perfecto que nunca llega?", 3),
        ("¿Cuándo fue la última vez que el amor fue tan grande que las palabras fueron insuficientes y eso estuvo bien?", 3),
    ],

    "familia": [
        ("¿Cómo se comunica tu familia las cosas difíciles y qué tan bien funciona eso?", 1),
        ("¿Cuándo fue la última vez que escuchaste a alguien de tu familia sin querer tener razón?", 1),
        ("¿Qué cosa difícil le dijiste a alguien de tu familia que fue lo correcto aunque costara?", 1),
        ("¿Cuándo fue la última vez que el silencio en tu familia fue más elocuente que cualquier conversación?", 1),
        ("¿Qué tono usás con tu familia que no usarías con nadie más?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te entendió sin que lo dijeras?", 1),
        ("¿Qué cosa que necesitás decirle a alguien de tu familia todavía no encontraste cómo decirla?", 1),
        ("¿Cuándo fue la última vez que una conversación familiar fue exactamente lo que todos necesitaban?", 1),
        ("¿Qué cosa en tu familia cuesta más escuchar que decir?", 1),
        ("¿Cuándo fue la última vez que el tono de una conversación familiar cambió todo?", 1),
        ("¿Qué cosa que se dice en tu familia dice más sobre la familia que sobre el tema?", 1),
        ("¿Cuándo fue la última vez que expresaste algo difícil en tu familia sin filtrar nada?", 1),
        ("¿Qué forma de comunicarse aprendiste de tu familia que hoy querés cambiar?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te escuchó de verdad?", 1),
        ("¿Qué cosa que no decís en tu familia empieza a pesar?", 1),
        ("¿Cuándo fue la última vez que el silencio familiar fue cómodo y no tenso?", 1),
        ("¿Qué le decís a alguien de tu familia cuando no sabés qué decirle?", 1),
        ("¿Cuándo fue la última vez que una conversación honesta en tu familia mejoró algo?", 1),
        ("¿Qué cosa del amor familiar todavía no expresás bien?", 1),
        ("¿Cuándo fue la última vez que en tu familia alguien dijo algo difícil de una manera que ayudó?", 1),
        ("¿Qué forma de decir las cosas aprendiste en tu familia que resultó ser un obstáculo?", 1),
        ("¿Cuándo fue la última vez que el tono en tu familia fue más importante que el contenido?", 1),
        ("¿Qué cosa que sentís por alguien de tu familia le cuesta más trabajo decirle?", 1),
        ("¿Cuándo fue la última vez que en tu familia callar fue más honesto que hablar?", 1),
        ("¿Qué patrón de comunicación familiar querés no repetir en las relaciones que creás?", 1),
        ("¿Cuándo fue la última vez que escuchar de verdad a alguien de tu familia cambió lo que pensabas?", 1),
        ("¿Qué te cuesta más expresar en tu familia: lo que necesitás o lo que sentís?", 1),
        ("¿Cuándo fue la última vez que algo que no dijiste en tu familia fue más elocuente que cualquier palabra?", 1),
        ("¿Qué forma de comunicarte en tu familia querés mejorar?", 1),
        ("¿Cuándo fue la última vez que una conversación familiar fue tan honesta que cambió algo para siempre?", 1),
        ("¿Qué cosa que no se dice en tu familia empieza a crear distancia?", 2),
        ("¿Cuándo fue la última vez que dijiste algo difícil en tu familia que fue exactamente necesario?", 2),
        ("¿Qué patrón de comunicación familiar repetís que sabés que no ayuda pero todavía no cambiaste?", 2),
        ("¿Cuándo fue la última vez que el silencio en tu familia fue una elección que después lamentaste?", 2),
        ("¿Qué cosa que sentís por alguien de tu familia le cuesta decirle porque no sabés cómo va a reaccionar?", 2),
        ("¿Cuándo fue la última vez que escuchar en tu familia fue más difícil que cualquier otra cosa?", 2),
        ("¿Qué forma de comunicar que tenés en tu familia viene de algo que aprendiste de chico y ya deberías cambiar?", 2),
        ("¿Cuándo fue la última vez que algo que no dijiste en tu familia dañó algo que importaba?", 2),
        ("¿Qué cosa difícil todavía no le dijiste a alguien de tu familia que debería saber?", 2),
        ("¿Cuándo fue la última vez que una conversación familiar cambió algo que parecía inamovible?", 2),
        ("¿Qué cosa que decís en tu familia tiene un impacto que no terminás de entender?", 2),
        ("¿Cuándo fue la última vez que el miedo a una conversación familiar fue más grande que el amor?", 2),
        ("¿Qué cosa que no decís en tu familia es la que más pesa y más deberías decir?", 2),
        ("¿Qué conversación que nunca tuviste en tu familia podría cambiar algo importante?", 3),
        ("¿Cuándo fue la última vez que algo que no dijiste en tu familia fue lo que hizo que algo se rompiera?", 3),
        ("¿Qué cosa que sentís por alguien de tu familia es tan difícil de decir que a veces preferís no sentirla?", 3),
        ("¿Cuándo fue la última vez que el silencio en tu familia fue una forma de mentira colectiva?", 3),
        ("¿Qué cosa que no decís en tu familia va a ser tu mayor arrepentimiento si el tiempo se acaba?", 3),
        ("¿Cuándo fue la última vez que una conversación honesta en tu familia te mostró algo de vos que no querías ver?", 3),
        ("¿Qué cosa difícil necesitás decir en tu familia y seguís esperando el momento que nunca llega?", 3),
        ("¿Cuándo fue la última vez que algo que no se dijo en tu familia tuvo más peso que todo lo que sí se dijo?", 3),
    ],

    "amistades": [
        ("¿Cómo le decís a un amigo que algo que hace te molesta?", 1),
        ("¿Cuándo fue la última vez que escuchaste a un amigo sin querer resolver su problema?", 1),
        ("¿Qué cosa difícil le dijiste a un amigo que fue exactamente lo que necesitaba escuchar?", 1),
        ("¿Cuándo fue la última vez que el silencio con un amigo fue completamente cómodo?", 1),
        ("¿Qué tono usás con tus amigos que no usarías con nadie más?", 1),
        ("¿Cuándo fue la última vez que un amigo te entendió sin que lo dijeras?", 1),
        ("¿Qué cosa que necesitás decirle a un amigo todavía no encontraste cómo decirla?", 1),
        ("¿Cuándo fue la última vez que una conversación con un amigo fue exactamente lo que necesitabas?", 1),
        ("¿Qué cosa en la amistad te cuesta más escuchar que decir?", 1),
        ("¿Cuándo fue la última vez que el tono de una conversación con un amigo lo cambió todo?", 1),
        ("¿Qué cosa que decís a tus amigos dice más sobre vos que sobre ellos?", 1),
        ("¿Cuándo fue la última vez que le expresaste a un amigo cuánto significaba para vos?", 1),
        ("¿Qué forma de comunicarte con tus amigos querés mejorar?", 1),
        ("¿Cuándo fue la última vez que un amigo te escuchó de verdad y eso cambió algo?", 1),
        ("¿Qué cosa que no decís a tus amigos empieza a pesar?", 1),
        ("¿Cuándo fue la última vez que el silencio con un amigo fue más elocuente que cualquier conversación?", 1),
        ("¿Qué le decís a un amigo cuando no sabés qué decirle?", 1),
        ("¿Cuándo fue la última vez que una conversación honesta con un amigo mejoró la amistad?", 1),
        ("¿Qué cosa de la amistad que sentís todavía no expresás bien?", 1),
        ("¿Cuándo fue la última vez que un amigo te dijo algo difícil de una manera que te ayudó?", 1),
        ("¿Qué forma de escuchar aprendiste en la amistad que llevás a otras relaciones?", 1),
        ("¿Cuándo fue la última vez que el tono con un amigo fue más importante que lo que decías?", 1),
        ("¿Qué cosa que sentís por un amigo le cuesta más trabajo decirle?", 1),
        ("¿Cuándo fue la última vez que en la amistad callar fue más honesto que hablar?", 1),
        ("¿Qué patrón de comunicación que tenés con tus amigos querés cambiar?", 1),
        ("¿Cuándo fue la última vez que escuchar de verdad a un amigo cambió lo que pensabas?", 1),
        ("¿Qué te cuesta más expresar en la amistad: lo que necesitás o lo que sentís?", 1),
        ("¿Cuándo fue la última vez que algo que no dijiste a un amigo fue más elocuente que cualquier palabra?", 1),
        ("¿Qué forma de comunicarte en la amistad que tenés querés mejorar?", 1),
        ("¿Cuándo fue la última vez que una conversación con un amigo fue tan honesta que cambió algo entre ustedes?", 1),
        ("¿Qué cosa que no decís a tus amigos empieza a crear distancia?", 2),
        ("¿Cuándo fue la última vez que dijiste algo difícil a un amigo y fue exactamente lo que necesitaba?", 2),
        ("¿Qué patrón de comunicación en la amistad repetís que sabés que no funciona?", 2),
        ("¿Cuándo fue la última vez que el silencio con un amigo fue una elección que después lamentaste?", 2),
        ("¿Qué cosa que sentís por un amigo le cuesta decirle porque no sabés cómo va a reaccionar?", 2),
        ("¿Cuándo fue la última vez que escuchar a un amigo fue más difícil que cualquier otra cosa?", 2),
        ("¿Qué forma de comunicar que tenés con tus amigos viene de algo que aprendiste y ya deberías cambiar?", 2),
        ("¿Cuándo fue la última vez que algo que no dijiste a un amigo dañó algo que importaba?", 2),
        ("¿Qué cosa difícil todavía no le dijiste a un amigo que debería saber?", 2),
        ("¿Cuándo fue la última vez que una conversación con un amigo cambió algo que parecía inamovible?", 2),
        ("¿Qué cosa que le decís a un amigo tiene un impacto que no terminás de entender?", 2),
        ("¿Cuándo fue la última vez que el miedo a una conversación con un amigo fue más grande que la amistad?", 2),
        ("¿Qué cosa que no decís a tus amigos es la que más pesa?", 2),
        ("¿Qué conversación que nunca tuviste con un amigo podría cambiar algo importante?", 3),
        ("¿Cuándo fue la última vez que algo que no dijiste a un amigo fue lo que hizo que algo se rompiera?", 3),
        ("¿Qué cosa que sentís por un amigo es tan difícil de decir que a veces preferís no sentirla?", 3),
        ("¿Cuándo fue la última vez que el silencio en una amistad fue una forma de dejar morir algo?", 3),
        ("¿Qué cosa que no decís a un amigo va a ser tu mayor arrepentimiento si el tiempo se acaba?", 3),
        ("¿Cuándo fue la última vez que una conversación honesta con un amigo te mostró algo de vos que no querías ver?", 3),
        ("¿Qué cosa difícil necesitás decirle a un amigo y seguís esperando el momento que nunca llega?", 3),
        ("¿Cuándo fue la última vez que el silencio en una amistad fue más dañino que cualquier conversación difícil?", 3),
    ],

    "exs": [
        ("¿Qué cosa que no dijiste en una relación pasada todavía te pesa?", 1),
        ("¿Cuándo fue la última vez que una conversación con un ex fue mejor de lo que esperabas?", 1),
        ("¿Qué cosa difícil dijiste en una relación pasada que fue exactamente lo correcto aunque doliera?", 1),
        ("¿Cuándo fue la última vez que el silencio en una relación pasada dijo más que cualquier pelea?", 1),
        ("¿Qué forma de comunicarte en el pasado amoroso querés no repetir?", 1),
        ("¿Cuándo fue la última vez que alguien de una relación pasada te entendió sin que lo dijeras?", 1),
        ("¿Qué cosa que necesitabas decir en una relación pasada nunca dijiste?", 1),
        ("¿Cuándo fue la última vez que una conversación honesta en una relación pasada mejoró algo?", 1),
        ("¿Qué cosa en las relaciones pasadas te costaba más escuchar que decir?", 1),
        ("¿Cuándo fue la última vez que el tono en una relación pasada fue más importante que el contenido?", 1),
        ("¿Qué cosa que decías en relaciones pasadas decía más sobre vos que sobre la otra persona?", 1),
        ("¿Cuándo fue la última vez que le expresaste a alguien de una relación pasada exactamente lo que sentías?", 1),
        ("¿Qué forma de comunicarte aprendiste de una relación pasada que llevás a las actuales?", 1),
        ("¿Cuándo fue la última vez que alguien de una relación pasada te escuchó de verdad?", 1),
        ("¿Qué cosa que no decías en relaciones pasadas empezó a crear problemas sin que lo notaras?", 1),
        ("¿Cuándo fue la última vez que el silencio en una relación pasada fue más elocuente que cualquier conversación?", 1),
        ("¿Qué le decías a alguien que amabas cuando no sabías qué decirle?", 1),
        ("¿Cuándo fue la última vez que una conversación honesta en una relación pasada cambió algo?", 1),
        ("¿Qué cosa del amor que sentías en el pasado no expresabas bien?", 1),
        ("¿Cuándo fue la última vez que alguien de una relación pasada te dijo algo difícil de una manera que te ayudó?", 1),
        ("¿Qué forma de escuchar que aprendiste en una relación pasada cambiaste después?", 1),
        ("¿Cuándo fue la última vez que en una relación pasada callar fue más honesto que hablar?", 1),
        ("¿Qué cosa que sentías por un ex te costaba más trabajo decirle?", 1),
        ("¿Cuándo fue la última vez que algo que no dijiste en una relación pasada dijo más que todo lo que sí dijiste?", 1),
        ("¿Qué patrón de comunicación de relaciones pasadas todavía no terminaste de cambiar?", 1),
        ("¿Cuándo fue la última vez que escuchar de verdad en una relación pasada cambió lo que pensabas?", 1),
        ("¿Qué te costaba más expresar en las relaciones pasadas: lo que necesitabas o lo que sentías?", 1),
        ("¿Cuándo fue la última vez que algo que no dijiste en una relación pasada fue exactamente lo que mató algo?", 1),
        ("¿Qué forma de comunicarte en relaciones pasadas querés definitivamente no repetir?", 1),
        ("¿Cuándo fue la última vez que una conversación en una relación pasada fue tan honesta que cambió algo para siempre?", 1),
        ("¿Qué cosa que no dijiste en una relación pasada todavía afecta cómo te comunicás hoy?", 2),
        ("¿Cuándo fue la última vez que algo que dijiste en una relación pasada dañó algo irreparablemente?", 2),
        ("¿Qué patrón de comunicación de relaciones pasadas repetiste hasta que te diste cuenta que no funcionaba?", 2),
        ("¿Cuándo fue la última vez que el silencio en una relación pasada fue una elección que lamentaste?", 2),
        ("¿Qué cosa que sentías por un ex nunca le dijiste y cómo llevas eso?", 2),
        ("¿Cuándo fue la última vez que escuchar en una relación pasada fue más difícil que cualquier conversación?", 2),
        ("¿Qué forma de comunicar que tenías en el pasado amoroso venía de algo que aprendiste en la infancia?", 2),
        ("¿Cuándo fue la última vez que algo que no dijiste en una relación pasada dañó algo que podría haber sobrevivido?", 2),
        ("¿Qué cosa difícil nunca le dijiste a un ex que quizás hubiera cambiado algo?", 2),
        ("¿Cuándo fue la última vez que una conversación honesta en una relación pasada cambió algo que parecía inamovible?", 2),
        ("¿Qué cosa que decías en una relación pasada tenía un impacto que no entendías en ese momento?", 2),
        ("¿Cuándo fue la última vez que el miedo a una conversación en el amor pasado fue más grande que el amor?", 2),
        ("¿Qué cosa que no dijiste en una relación pasada es la que más pesa?", 2),
        ("¿Qué conversación que nunca tuviste en una relación pasada todavía te preguntás qué hubiera pasado?", 3),
        ("¿Cuándo fue la última vez que algo que no dijiste en una relación pasada fue exactamente lo que la terminó?", 3),
        ("¿Qué cosa que sentías en una relación pasada era tan difícil de decir que elegiste no sentirla?", 3),
        ("¿Cuándo fue la última vez que el silencio en una relación pasada fue la forma más elegante de mentir?", 3),
        ("¿Qué cosa que no dijiste en una relación pasada fue tu mayor arrepentimiento de esa relación?", 3),
        ("¿Cuándo fue la última vez que una conversación honesta en el amor pasado te mostró algo de vos que preferirías no haber visto?", 3),
        ("¿Qué cosa difícil que nunca dijiste en una relación pasada hubiera cambiado todo si la hubieras dicho?", 3),
        ("¿Cuándo fue la última vez que el silencio en el amor pasado fue más dañino que cualquier pelea?", 3),
    ],

    "personalidad": [
        ("¿Cómo te comunicás diferente con distintas personas y qué dice eso de vos?", 1),
        ("¿Cuándo fue la última vez que escuchaste activamente a alguien en lugar de esperar tu turno?", 1),
        ("¿Qué forma de comunicarte es tan tuya que no podrías cambiarla aunque quisieras?", 1),
        ("¿Cuándo fue la última vez que el silencio fue tu respuesta más honesta?", 1),
        ("¿Qué tono usás cuando estás nervioso que no querés usar pero aparece igual?", 1),
        ("¿Cuándo fue la última vez que expresaste exactamente lo que pensabas sin suavizarlo?", 1),
        ("¿Qué cosa que necesitás decir te cuesta más trabajo poner en palabras?", 1),
        ("¿Cuándo fue la última vez que alguien te entendió sin que lo dijeras?", 1),
        ("¿Qué cosa te cuesta más escuchar que decir?", 1),
        ("¿Cuándo fue la última vez que el tono con el que dijiste algo fue más importante que las palabras?", 1),
        ("¿Qué cosa que decís habitualmente dice más sobre vos que sobre el tema?", 1),
        ("¿Cuándo fue la última vez que expresaste algo difícil y lo recibieron mejor de lo que esperabas?", 1),
        ("¿Qué forma de comunicarte querés mejorar?", 1),
        ("¿Cuándo fue la última vez que alguien te escuchó de verdad y qué cambió eso?", 1),
        ("¿Qué cosa que no decís empieza a pesar más de lo que querés?", 1),
        ("¿Cuándo fue la última vez que el silencio fue más cómodo que cualquier conversación?", 1),
        ("¿Qué le decís a alguien cuando no sabés qué decirle?", 1),
        ("¿Cuándo fue la última vez que una conversación honesta mejoró algo que estaba dañado?", 1),
        ("¿Qué cosa de lo que sentís todavía no expresás bien?", 1),
        ("¿Cuándo fue la última vez que alguien te dijo algo difícil de una manera que te ayudó?", 1),
        ("¿Qué forma de escuchar que tenés llevás a todas tus relaciones?", 1),
        ("¿Cuándo fue la última vez que el tono fue más importante que el contenido en una conversación?", 1),
        ("¿Qué cosa que sentís te cuesta más trabajo decirle a alguien?", 1),
        ("¿Cuándo fue la última vez que callar fue más honesto que hablar?", 1),
        ("¿Qué patrón de comunicación tuyo querés cambiar?", 1),
        ("¿Cuándo fue la última vez que escuchar de verdad cambió lo que pensabas?", 1),
        ("¿Qué te cuesta más expresar: lo que necesitás o lo que sentís?", 1),
        ("¿Cuándo fue la última vez que algo que no dijiste fue más elocuente que cualquier palabra?", 1),
        ("¿Qué forma de comunicarte que tenés es tu mayor fortaleza y cuál tu mayor obstáculo?", 1),
        ("¿Cuándo fue la última vez que una conversación honesta cambió algo que parecía imposible de cambiar?", 1),
        ("¿Qué cosa que no decís empieza a crear distancia con las personas que más importan?", 2),
        ("¿Cuándo fue la última vez que dijiste algo difícil que fue exactamente lo que alguien necesitaba?", 2),
        ("¿Qué patrón de comunicación repetís que sabés que no funciona pero todavía no cambiaste?", 2),
        ("¿Cuándo fue la última vez que el silencio fue una elección que después lamentaste?", 2),
        ("¿Qué cosa que sentís le cuesta decirle a alguien porque no sabés cómo va a reaccionar?", 2),
        ("¿Cuándo fue la última vez que escuchar fue más difícil que cualquier otra cosa que tenías que hacer?", 2),
        ("¿Qué forma de comunicar que tenés viene de algo que aprendiste y ya deberías cambiar?", 2),
        ("¿Cuándo fue la última vez que algo que no dijiste dañó algo que importaba?", 2),
        ("¿Qué cosa difícil todavía no le dijiste a alguien que debería saber?", 2),
        ("¿Cuándo fue la última vez que una conversación honesta cambió algo que parecía inamovible?", 2),
        ("¿Qué cosa que decís tiene un impacto que no terminás de entender?", 2),
        ("¿Cuándo fue la última vez que el miedo a una conversación fue más grande que lo que tenías que decir?", 2),
        ("¿Qué cosa que no decís es la que más pesa?", 2),
        ("¿Qué conversación que nunca tuviste podría cambiar algo importante en tu vida?", 3),
        ("¿Cuándo fue la última vez que algo que no dijiste fue lo que hizo que algo se rompiera?", 3),
        ("¿Qué cosa que sentís es tan difícil de decir que a veces preferís no sentirla?", 3),
        ("¿Cuándo fue la última vez que el silencio fue una forma de mentir?", 3),
        ("¿Qué cosa que no decís va a ser tu mayor arrepentimiento si el tiempo se acaba?", 3),
        ("¿Cuándo fue la última vez que una conversación honesta te mostró algo de vos que no querías ver?", 3),
        ("¿Qué cosa difícil necesitás decir y seguís esperando el momento que nunca llega?", 3),
        ("¿Cuándo fue la última vez que el silencio fue más dañino que cualquier conversación difícil?", 3),
    ],

    "miedos": [
        ("¿Qué miedo te cuesta más poner en palabras?", 1),
        ("¿Cuándo fue la última vez que hablar de un miedo lo hizo más pequeño?", 1),
        ("¿Qué miedo tuyo todavía no dijiste en voz alta porque si lo hacés se vuelve real?", 1),
        ("¿Cuándo fue la última vez que el silencio sobre un miedo fue más pesado que el miedo mismo?", 1),
        ("¿Qué miedo tuyo que nunca contaste alguien igual lo intuye?", 1),
        ("¿Cuándo fue la última vez que contar un miedo te acercó a alguien?", 1),
        ("¿Qué tono usás cuando estás asustado que no querés usar pero aparece igual?", 1),
        ("¿Cuándo fue la última vez que escuchar el miedo de alguien más te ayudó a entender el tuyo?", 1),
        ("¿Qué miedo que no decís empieza a afectar algo más de lo que querés?", 1),
        ("¿Cuándo fue la última vez que poner un miedo en palabras lo cambió?", 1),
        ("¿Qué cosa del miedo te cuesta más escuchar de otros?", 1),
        ("¿Cuándo fue la última vez que alguien te entendió sin que dijeras de qué tenías miedo?", 1),
        ("¿Qué miedo que tenés se lo contarías a alguien y cuál jamás?", 1),
        ("¿Cuándo fue la última vez que hablar de un miedo fue más fácil de lo que esperabas?", 1),
        ("¿Qué miedo tuyo que escondés ya es bastante visible para alguien que te conoce bien?", 1),
        ("¿Cuándo fue la última vez que el silencio sobre un miedo fue exactamente lo que lo alimentó?", 1),
        ("¿Qué miedo te cuesta más admitir en voz alta?", 1),
        ("¿Cuándo fue la última vez que decir que tenías miedo fue exactamente lo más valiente?", 1),
        ("¿Qué miedo que cargás solo sería más liviano si alguien más lo supiera?", 1),
        ("¿Cuándo fue la última vez que hablar de un miedo fue exactamente lo que necesitabas?", 1),
        ("¿Qué miedo tuyo que no nombrás sigue teniendo poder sobre vos?", 1),
        ("¿Cuándo fue la última vez que el tono con el que alguien habló de su miedo te enseñó algo?", 1),
        ("¿Qué miedo que tenés le cuesta más trabajo decirle a alguien que más te importa?", 1),
        ("¿Cuándo fue la última vez que escuchar el miedo de alguien cambió cómo lo veías?", 1),
        ("¿Qué miedo que no decís empieza a pesar más de lo que esperabas?", 1),
        ("¿Cuándo fue la última vez que nombrar un miedo fue el primer paso para superarlo?", 1),
        ("¿Qué miedo tuyo que nunca dijiste ya sería tiempo de decir?", 1),
        ("¿Cuándo fue la última vez que algo que no dijiste sobre un miedo fue más elocuente que todo lo que sí dijiste?", 1),
        ("¿Qué forma de hablar del miedo aprendiste que querés mejorar?", 1),
        ("¿Cuándo fue la última vez que una conversación honesta sobre un miedo cambió algo?", 1),
        ("¿Qué miedo tuyo que no decís empieza a afectar algo concreto?", 2),
        ("¿Cuándo fue la última vez que el silencio sobre un miedo fue más dañino que hablar de él?", 2),
        ("¿Qué miedo que nunca contaste todavía tiene el poder que tiene porque nadie lo sabe?", 2),
        ("¿Cuándo fue la última vez que hablar de un miedo requirió más valentía que enfrentarlo?", 2),
        ("¿Qué miedo tuyo que no decís es el que más limita algo?", 2),
        ("¿Cuándo fue la última vez que escuchar el miedo de alguien fue más difícil que el tuyo propio?", 2),
        ("¿Qué miedo que cargás en silencio ya debería estar compartido?", 2),
        ("¿Cuándo fue la última vez que algo del miedo que no dijiste dañó algo que importaba?", 2),
        ("¿Qué miedo que no nombrás sería más manejable si lo dijeras?", 2),
        ("¿Cuándo fue la última vez que el miedo a hablar de un miedo fue más grande que el miedo mismo?", 2),
        ("¿Qué miedo que escondés ya sabés que debería decirse?", 2),
        ("¿Cuándo fue la última vez que el silencio sobre un miedo fue exactamente lo que lo hizo crecer?", 2),
        ("¿Qué miedo que no decís es el que más pesa?", 2),
        ("¿Qué miedo que nunca dijiste en voz alta podría cambiar algo si lo dijeras?", 3),
        ("¿Cuándo fue la última vez que el silencio sobre un miedo fue exactamente lo que te mantuvo atrapado?", 3),
        ("¿Qué miedo que cargás es tan íntimo que nombrarlo sería desnudarte demasiado?", 3),
        ("¿Cuándo fue la última vez que no decir un miedo fue exactamente lo que hizo que algo se rompiera?", 3),
        ("¿Qué miedo tuyo va a ser tu mayor arrepentimiento si nunca lo decís?", 3),
        ("¿Cuándo fue la última vez que nombrar un miedo cambió algo de manera que no esperabas?", 3),
        ("¿Qué miedo que no decís revela algo de vos que preferirías que nadie vea?", 3),
        ("¿Cuándo fue la última vez que el silencio sobre un miedo fue más costoso que cualquier conversación difícil?", 3),
    ],

    "logros": [
        ("¿Cómo le contás a alguien un logro sin que parezca que te estás jactando?", 1),
        ("¿Cuándo fue la última vez que celebraste un logro en voz alta sin minimizarlo?", 1),
        ("¿Qué logro tuyo todavía no dijiste a nadie?", 1),
        ("¿Cuándo fue la última vez que el silencio sobre un logro fue más honesto que compartirlo?", 1),
        ("¿Qué forma de comunicar los logros aprendiste que querés cambiar?", 1),
        ("¿Cuándo fue la última vez que alguien celebró un logro tuyo de una manera que te sorprendió?", 1),
        ("¿Qué logro tuyo que nunca contaste alguien igual lo intuye?", 1),
        ("¿Cuándo fue la última vez que contar un logro te acercó a alguien?", 1),
        ("¿Qué tono usás cuando hablás de tus logros que no querés usar pero aparece igual?", 1),
        ("¿Cuándo fue la última vez que escuchar el logro de alguien más te ayudó a entender el tuyo?", 1),
        ("¿Qué logro que no contás empieza a pesar más de lo que querés?", 1),
        ("¿Cuándo fue la última vez que poner un logro en palabras lo cambió?", 1),
        ("¿Qué cosa de los logros ajenos te cuesta más escuchar?", 1),
        ("¿Cuándo fue la última vez que alguien te felicitó de una manera que realmente llegó?", 1),
        ("¿Qué logro que tenés se lo contarías a alguien y cuál te cuesta más compartir?", 1),
        ("¿Cuándo fue la última vez que hablar de un logro fue más fácil de lo que esperabas?", 1),
        ("¿Qué logro tuyo que escondés ya es bastante visible para alguien que te conoce bien?", 1),
        ("¿Cuándo fue la última vez que el silencio sobre un logro fue lo más elocuente?", 1),
        ("¿Qué logro te cuesta más admitir que conseguiste?", 1),
        ("¿Cuándo fue la última vez que compartir un logro fue exactamente lo que el momento necesitaba?", 1),
        ("¿Qué logro que cargás solo sería más valioso si alguien más lo supiera?", 1),
        ("¿Cuándo fue la última vez que hablar de un logro fue exactamente lo que necesitabas?", 1),
        ("¿Qué logro tuyo que no nombrás todavía no celebraste del todo?", 1),
        ("¿Cuándo fue la última vez que el tono con el que alguien habló de su logro te enseñó algo?", 1),
        ("¿Qué logro que tenés le cuesta más trabajo compartir con quien más te importa?", 1),
        ("¿Cuándo fue la última vez que escuchar el logro de alguien cambió cómo lo veías?", 1),
        ("¿Qué logro que no decís empieza a pesar más de lo que querés?", 1),
        ("¿Cuándo fue la última vez que nombrar un logro fue el primer paso para celebrarlo?", 1),
        ("¿Qué logro tuyo que nunca dijiste ya sería tiempo de decir?", 1),
        ("¿Cuándo fue la última vez que algo de un logro que no dijiste fue más elocuente que todo lo que sí dijiste?", 1),
        ("¿Qué logro tuyo que no decís empieza a afectar algo concreto en cómo te ves?", 2),
        ("¿Cuándo fue la última vez que el silencio sobre un logro fue más dañino que celebrarlo?", 2),
        ("¿Qué logro que nunca contaste todavía no termina de hacerse real porque nadie lo sabe?", 2),
        ("¿Cuándo fue la última vez que hablar de un logro requirió más valentía que conseguirlo?", 2),
        ("¿Qué logro tuyo que no decís es el que más te cuesta reconocer?", 2),
        ("¿Cuándo fue la última vez que escuchar el logro de alguien fue más difícil de lo que esperabas?", 2),
        ("¿Qué logro que cargás en silencio ya debería estar compartido?", 2),
        ("¿Cuándo fue la última vez que algo del logro que no dijiste dañó cómo te ves?", 2),
        ("¿Qué logro que no nombrás sería más valioso si lo dijeras?", 2),
        ("¿Cuándo fue la última vez que el miedo a sonar jactancioso fue más grande que el logro mismo?", 2),
        ("¿Qué logro que escondés ya sabés que merecería decirse?", 2),
        ("¿Cuándo fue la última vez que el silencio sobre un logro fue exactamente lo que lo hizo crecer?", 2),
        ("¿Qué logro que no decís es el que más pesa no haber celebrado?", 2),
        ("¿Qué logro que nunca dijiste en voz alta podría cambiar algo si lo dijeras?", 3),
        ("¿Cuándo fue la última vez que el silencio sobre un logro fue exactamente lo que te mantuvo sin celebrarlo?", 3),
        ("¿Qué logro que cargás es tan íntimo que compartirlo sería desnudarte demasiado?", 3),
        ("¿Cuándo fue la última vez que no decir un logro fue exactamente lo que hizo que algo quedara sin cerrar?", 3),
        ("¿Qué logro tuyo va a ser tu mayor arrepentimiento no haber celebrado si el tiempo se acaba?", 3),
        ("¿Cuándo fue la última vez que nombrar un logro cambió algo de manera que no esperabas?", 3),
        ("¿Qué logro que no decís revela algo de vos que todavía no estás listo para reconocer?", 3),
        ("¿Cuándo fue la última vez que el silencio sobre un logro fue más costoso que cualquier conversación difícil?", 3),
    ],

    "sinFiltro": [
        ("¿Qué cosa que pensás nunca decís porque no sabés cómo va a caer?", 1),
        ("¿Cuándo fue la última vez que dijiste algo sin filtrar y fue exactamente lo correcto?", 1),
        ("¿Qué cosa que callás sería liberador decir aunque fuera incómodo?", 1),
        ("¿Cuándo fue la última vez que el silencio fue más honesto que cualquier cosa que podrías haber dicho?", 1),
        ("¿Qué tono usás cuando no te importa lo que piensen que no usarías en otro contexto?", 1),
        ("¿Cuándo fue la última vez que alguien te dijo algo sin filtrar y fue exactamente lo que necesitabas escuchar?", 1),
        ("¿Qué cosa que pensás sobre vos mismo nunca dijiste en voz alta?", 1),
        ("¿Cuándo fue la última vez que expresaste algo incómodo y fue recibido mejor de lo que esperabas?", 1),
        ("¿Qué cosa que callás empieza a pesar más de lo que querés?", 1),
        ("¿Cuándo fue la última vez que el tono sin filtros de alguien fue exactamente lo que necesitabas?", 1),
        ("¿Qué cosa que decís en privado no dirías en público aunque sea verdad?", 1),
        ("¿Cuándo fue la última vez que la honestidad sin filtros fue exactamente lo más valiente?", 1),
        ("¿Qué cosa que pensás sobre alguien nunca dijiste aunque te la preguntaran?", 1),
        ("¿Cuándo fue la última vez que decir algo sin filtrar cambió algo para mejor?", 1),
        ("¿Qué cosa que callás ya es bastante visible para alguien que te conoce bien?", 1),
        ("¿Cuándo fue la última vez que el silencio sin filtros fue más elocuente que cualquier palabra?", 1),
        ("¿Qué cosa que pensás te cuesta más admitir que es verdad?", 1),
        ("¿Cuándo fue la última vez que ser completamente directo fue exactamente lo más amable?", 1),
        ("¿Qué cosa que cargás solo sería más liviana si alguien más la supiera aunque fuera incómodo decirla?", 1),
        ("¿Cuándo fue la última vez que hablar sin filtrar fue exactamente lo que el momento necesitaba?", 1),
        ("¿Qué cosa que pensás sobre la vida nunca decís en voz alta?", 1),
        ("¿Cuándo fue la última vez que el tono con el que alguien dijo algo sin filtrar te enseñó algo?", 1),
        ("¿Qué cosa que callás le cuesta más trabajo decirle a alguien que más te importa?", 1),
        ("¿Cuándo fue la última vez que escuchar algo sin filtrar de alguien cambió cómo lo veías?", 1),
        ("¿Qué cosa que no decís empieza a pesar más de lo que querés admitir?", 1),
        ("¿Cuándo fue la última vez que nombrar algo sin filtrar fue el primer paso para manejarlo?", 1),
        ("¿Qué cosa tuya sin filtrar que nunca dijiste ya sería tiempo de decir?", 1),
        ("¿Cuándo fue la última vez que algo que no dijiste sin filtrar fue más elocuente que todo lo que sí dijiste?", 1),
        ("¿Qué forma de comunicarte sin filtrar que tenés querés mejorar?", 1),
        ("¿Cuándo fue la última vez que una conversación sin filtros cambió algo que parecía imposible de cambiar?", 1),
        ("¿Qué cosa que no decís sin filtrar empieza a crear distancia con las personas que más importan?", 2),
        ("¿Cuándo fue la última vez que dijiste algo sin filtrar que fue exactamente lo que alguien necesitaba aunque le doliera?", 2),
        ("¿Qué cosa que callás sin filtrar y sabés que no funciona todavía no cambiaste?", 2),
        ("¿Cuándo fue la última vez que el silencio sin filtros fue una elección que después lamentaste?", 2),
        ("¿Qué cosa que pensás no decís porque no sabés cómo va a reaccionar quien lo recibe?", 2),
        ("¿Cuándo fue la última vez que decir algo sin filtrar fue más difícil que cualquier otra cosa?", 2),
        ("¿Qué forma de callarte que tenés viene de algo que aprendiste y ya deberías cambiar?", 2),
        ("¿Cuándo fue la última vez que algo que no dijiste sin filtrar dañó algo que importaba?", 2),
        ("¿Qué cosa difícil sin filtrar todavía no le dijiste a alguien que debería saber?", 2),
        ("¿Cuándo fue la última vez que una conversación honesta sin filtros cambió algo que parecía inamovible?", 2),
        ("¿Qué cosa que decís o no decís tiene un impacto que no terminás de entender?", 2),
        ("¿Cuándo fue la última vez que el miedo a una conversación sin filtros fue más grande que lo que tenías que decir?", 2),
        ("¿Qué cosa que no decís sin filtros es la que más pesa?", 2),
        ("¿Qué conversación sin filtros que nunca tuviste podría cambiar algo importante en tu vida?", 3),
        ("¿Cuándo fue la última vez que algo que no dijiste sin filtrar fue lo que hizo que algo se rompiera?", 3),
        ("¿Qué cosa que pensás es tan difícil de decir sin filtrar que a veces preferís no pensarla?", 3),
        ("¿Cuándo fue la última vez que el silencio fue una forma de mentir que elegiste conscientemente?", 3),
        ("¿Qué cosa que no decís sin filtrar va a ser tu mayor arrepentimiento si el tiempo se acaba?", 3),
        ("¿Cuándo fue la última vez que una conversación sin filtros te mostró algo de vos que no querías ver?", 3),
        ("¿Qué cosa que necesitás decir sin filtrar seguís esperando el momento que nunca llega?", 3),
        ("¿Cuándo fue la última vez que el silencio sin filtros fue más dañino que cualquier conversación incómoda?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS22:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS22[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
