#!/usr/bin/env python3
"""Second batch of question expansion."""
import json

ADDITIONS2 = {
    "infancia": [
        # Level 1
        ("¿Cuál era tu postre favorito de chico?", 1),
        ("¿Tenías miedo a los truenos o relámpagos de niño?", 1),
        ("¿Cómo se llamaba tu maestra o maestro favorito?", 1),
        ("¿Qué música escuchaban en tu casa cuando eras chico?", 1),
        ("¿Cuál fue la primera película que viste en el cine?", 1),
        ("¿Jugabas más en la calle o en casa?", 1),
        ("¿Tenías bicicleta? ¿Cómo era?", 1),
        ("¿Cuál era el dulce o golosina que más pedías?", 1),
        ("¿Qué rol tenías en el grupo de amigos del colegio?", 1),
        ("¿Cuántos idiomas intentaste aprender de chico?", 1),
        ("¿Cómo te enterabas de las noticias del mundo cuando eras chico?", 1),
        ("¿Tuviste algún club o pandilla de amigos con nombre propio?", 1),
        ("¿Cuál fue la primera vez que cocinaste algo solo?", 1),
        ("¿Qué libro te leían de noche antes de dormir?", 1),
        ("¿Cuál era la actividad extracurricular que más te gustaba?", 1),
        ("¿Tenías algún ídolo o persona famosa que adorabas?", 1),
        ("¿Cómo fue tu primer día de escuela?", 1),
        ("¿Cuál fue la primera travesura que te costó un castigo?", 1),
        ("¿Preferías los juguetes tecnológicos o los juegos de imaginación?", 1),
        ("¿Qué era lo más emocionante del fin de semana de chico?", 1),
        ("¿Cuál fue el primer trabajo que quisiste tener cuando fueras grande?", 1),
        ("¿Dónde estaba tu escondite favorito para jugar?", 1),
        ("¿Cuántos primos tenías y con cuál te llevabas mejor?", 1),
        ("¿Ibas de campamento o a colonias de vacaciones?", 1),
        ("¿Cuál fue el primer video juego que recuerdas haber jugado?", 1),
        ("¿Te gustaba dibujar o pintar de chico?", 1),
        ("¿Cuál fue el cuento que más veces pediste que te contaran?", 1),
        ("¿A qué edad empezaste a usar celular?", 1),
        ("¿Cuál fue el primer deporte que practicaste?", 1),
        ("¿Cómo celebrabas el día de tu cumpleaños cuando eras niño?", 1),
        # Level 2
        ("¿Cuándo fue la primera vez que sentiste que debías proteger a alguien de tu familia?", 2),
        ("¿Alguna vez te metiste en una pelea física? ¿Cómo fue?", 2),
        ("¿Hubo algún momento en que te sentiste diferente al resto de tu clase?", 2),
        ("¿Cómo era la situación económica de tu familia cuando eras chico?", 2),
        ("¿Alguna vez viste a tus padres pelear? ¿Cómo te afectó?", 2),
        ("¿Cuál fue el primer secreto que te confiaron y que guardaste?", 2),
        ("¿Alguna vez mentiste sobre tu familia para encajar o impresionar?", 2),
        ("¿Cuál fue la primera vez que sentiste que algo era injusto?", 2),
        ("¿Cuándo fue la primera vez que sentiste presión por los estudios?", 2),
        ("¿Había algo que hacías diferente a los demás que te hacía sentir solo?", 2),
        ("¿Cuál fue el consejo más importante que te dio alguien en la escuela?", 2),
        ("¿Alguna vez viste algo que no debías ver de chico?", 2),
        ("¿Cómo te afectó cuando te diste cuenta de que los adultos no siempre tienen razón?", 2),
        ("¿Cuál fue la primera vez que tuviste que tomar una decisión difícil solo?", 2),
        ("¿Hubo algo en tu infancia que te hacía sentir especial?", 2),
        # Level 3
        ("¿Qué parte de tu infancia te cuesta más mirar de frente?", 3),
        ("¿Hay algún recuerdo que durante años pensaste que era uno y luego descubriste otro?", 3),
        ("¿Cuál fue la primera vez que sentiste vergüenza de vos mismo?", 3),
        ("¿Qué cosa de tu infancia más influyó en tus miedos adultos?", 3),
        ("¿Si pudieras cambiar algo de tu infancia, qué sería y por qué?", 3),
    ],

    "futuro": [
        # Level 1
        ("¿Cuál es la app o tecnología que más usarías si existiera?", 1),
        ("¿Te imaginás teniendo hijos o ya los tenés? ¿Cuántos?", 1),
        ("¿Cuál es el país que definitivamente querés conocer antes de morir?", 1),
        ("¿Qué tipo de casa soñás tener: campo, ciudad, playa o montaña?", 1),
        ("¿Preferís un retiro temprano activo o seguir trabajando con propósito?", 1),
        ("¿Cuál es el vehículo soñado que querés tener algún día?", 1),
        ("¿Tenés planes de hacer algún voluntariado o proyecto social?", 1),
        ("¿Qué tipo de mascotas querés tener en el futuro?", 1),
        ("¿Cuál es la carrera o formación que considerás estudiar a futuro?", 1),
        ("¿Preferís una vida más simple o más exitosa si hubiera que elegir?", 1),
        ("¿Cuál es el negocio o emprendimiento que te gustaría arrancar?", 1),
        ("¿Te imaginas viviendo fuera de tu país natal?", 1),
        ("¿Qué deporte extremo o actividad te gustaría probar?", 1),
        ("¿Cuál es el concierto o artista que no te querés perder?", 1),
        ("¿Qué hábito de salud querés incorporar este año?", 1),
        ("¿Cuántos años más te ves en el trabajo que tenés actualmente?", 1),
        ("¿Cuál es el festival o evento que querés vivir al menos una vez?", 1),
        ("¿Te gustaría aprender a cocinar algo específico?", 1),
        ("¿Cómo te imaginas que será el mundo en 50 años?", 1),
        ("¿Cuál es la startup o empresa que te gustaría fundar?", 1),
        ("¿Querés escribir un libro algún día?", 1),
        ("¿Qué hobby querés retomar que dejaste por falta de tiempo?", 1),
        ("¿Cuál es el viaje de tu vida que todavía no hiciste?", 1),
        ("¿Cómo te ves en una relación en 5 años?", 1),
        ("¿Cuál es la contribución que querés hacer a tu comunidad?", 1),
        # Level 2
        ("¿Cuál es el sueño que más miedo te da perseguir?", 2),
        ("¿Qué parte de tu vida actual sabés que no va a funcionar en el largo plazo?", 2),
        ("¿Cuándo fue la última vez que hiciste algo concreto hacia tu meta más importante?", 2),
        ("¿Hay algo que deberías haber empezado hace tiempo y que seguís postergando?", 2),
        ("¿Cuánto peso le das a la seguridad vs. el riesgo en tus decisiones de futuro?", 2),
        ("¿Qué habilidad te da vergüenza no tener todavía?", 2),
        ("¿Cuál es la conversación sobre el futuro que más evitás tener?", 2),
        ("¿Cómo pensás que va a cambiar tu relación con el dinero en los próximos años?", 2),
        ("¿Cuánto importa lo que los demás esperan de vos en tus planes futuros?", 2),
        ("¿Hay algo que querés lograr que te daría vergüenza si fracasás?", 2),
        ("¿Cuándo fue la última vez que realmente te sentaste a pensar en tu futuro?", 2),
        ("¿Cuál es la relación que más querés fortalecer en los próximos años?", 2),
        ("¿Qué tan preparado te sentís para los desafíos que vienen?", 2),
        ("¿Hay un sueño que abandonaste y que en el fondo sabés que era el correcto?", 2),
        ("¿Cuánto de tu futuro está en tus manos y cuánto lo dejás al azar?", 2),
        # Level 3
        ("¿Cuándo fue la última vez que hiciste algo que el 'vos' del futuro agradecerá?", 3),
        ("¿Qué tan seguido sentís que estás viviendo la vida de otra persona?", 3),
        ("¿Cuál es la cosa que más te da miedo no haber hecho cuando seas viejo?", 3),
        ("¿Cuánto de tu futuro ideal depende de que alguien más cambie?", 3),
        ("¿Hay algo que sabés que tenés que soltar para poder avanzar?", 3),
    ],

    "amor": [
        # Level 1
        ("¿Cuál es la canción que pondrías en una playlist romántica?", 1),
        ("¿Sos más de sorpresas o de planes previsibles en pareja?", 1),
        ("¿Cuál fue tu primera foto con alguien que te gustaba?", 1),
        ("¿Cuánto tiempo tardás en saber si alguien te gusta de verdad?", 1),
        ("¿Cuál es el regalo más original que le diste a una pareja?", 1),
        ("¿Sos de los que dice 'te quiero' fácil o lo reservás para cuando es verdad?", 1),
        ("¿Cuál es la cosa que hacés cuando te enamoras que no hacés normalmente?", 1),
        ("¿Qué es lo que más te llama la atención en una persona al principio?", 1),
        ("¿Cuál es tu lenguaje del amor principal?", 1),
        ("¿Fuiste más veces el que enamoró o el enamorado?", 1),
        ("¿Sos del tipo que se imagina el futuro en las primeras citas?", 1),
        ("¿Cuál es la actividad que siempre querés hacer con tu pareja?", 1),
        ("¿Qué detalle romántico nunca pasó de moda para vos?", 1),
        ("¿Cuánto tiempo sin ver a tu pareja antes de empezar a extrañar?", 1),
        ("¿Tenés algún ritual de pareja que repetís con cada relación?", 1),
        ("¿Cuál es el tipo de persona que definitivamente no es para vos?", 1),
        ("¿Qué es lo que más te divierte de empezar a conocer a alguien?", 1),
        ("¿Cuándo fue la primera vez que sentiste mariposas de verdad?", 1),
        ("¿Sos de leer las señales bien o te confundís seguido?", 1),
        ("¿Cuál fue el mal entendido más gracioso que tuviste con alguien que te gustaba?", 1),
        ("¿Cuántas citas hacen falta para que empieces a confiar?", 1),
        ("¿Preferís el contacto físico o las palabras para expresar amor?", 1),
        ("¿Cuál es el lugar más romántico en el que estuviste?", 1),
        ("¿Le contás a tus amigos todo sobre tus relaciones o guardás para vos?", 1),
        ("¿Cuál fue el primer beso que realmente recordás?", 1),
        # Level 2
        ("¿Alguna vez te dijeron que eras difícil para amar?", 2),
        ("¿Cómo manejás cuando una relación empieza a enfriarse?", 2),
        ("¿Cuánto de vos mismo cambiás cuando estás en pareja?", 2),
        ("¿Alguna vez te pusiste en pareja con alguien que sabías que no era para vos?", 2),
        ("¿Cuándo fue la última vez que pediste disculpas en una relación?", 2),
        ("¿Hay algo que nunca le dirías a tu pareja por miedo a su reacción?", 2),
        ("¿Cómo afecta tu autoestima estar o no estar en pareja?", 2),
        ("¿Cuánto de tus relaciones está moldeado por la relación de tus padres?", 2),
        ("¿Cuál fue la relación que más te enseñó sobre tus propios límites?", 2),
        ("¿Alguna vez usaste una relación para escapar de otra cosa?", 2),
        ("¿Cómo definirías la diferencia entre una pareja sana y una que no lo es?", 2),
        ("¿Cuánto tiempo necesitás después de una ruptura antes de empezar algo nuevo?", 2),
        ("¿Hay algo de cómo amás que querés cambiar?", 2),
        ("¿Qué es lo que más te asusta de una relación profunda?", 2),
        ("¿Alguna vez te quedaste en una relación por comodidad?", 2),
        # Level 3
        ("¿Cuándo fue la última vez que amaste sin esperar nada a cambio?", 3),
        ("¿Qué parte de vos mismo escondés en una relación íntima?", 3),
        ("¿Cuál es el apego que más te cuesta soltar en el amor?", 3),
        ("¿Cuánto de lo que buscás en una pareja es lo que te falta a vos?", 3),
        ("¿Hay alguien a quien amaste tan mal que todavía lo sentís?", 3),
    ],

    "familia": [
        # Level 1
        ("¿Cuántas generaciones de tu familia conociste en persona?", 1),
        ("¿Hay algún familiar que sea el contador de historias de la familia?", 1),
        ("¿Cuál es el recuerdo más vívido de una reunión familiar?", 1),
        ("¿Tu familia tiene algún dicho o frase que se repite?", 1),
        ("¿Cuántas veces por año ven a su familia extendida?", 1),
        ("¿Cuál es el plato típico de las fiestas en tu familia?", 1),
        ("¿A quién de tu familia llamarías primero en una emergencia?", 1),
        ("¿Cuál es el talento artístico o creativo que hay en tu familia?", 1),
        ("¿Hay alguna historia de los orígenes de tu familia que te encante contar?", 1),
        ("¿Cuál es la profesión más repetida en tu árbol familiar?", 1),
        ("¿Tenés familia en otros países? ¿Cuánto contacto tienen?", 1),
        ("¿Cuál es el álbum de fotos familiar más antiguo que tenés?", 1),
        ("¿Hay alguna tradición navideña que sea exclusiva de tu familia?", 1),
        ("¿Tu familia tiene algún ritual de buena suerte?", 1),
        ("¿Cuál fue el mejor viaje familiar que recuerdas?", 1),
        ("¿Cuántos idiomas hablan entre todos en tu familia?", 1),
        ("¿Cuál es la historia de cómo se conocieron tus padres?", 1),
        ("¿Cómo maneja tu familia los desacuerdos políticos?", 1),
        ("¿Cuál es la canción que identifica a tu familia?", 1),
        ("¿Quién es el más estricto de tu familia?", 1),
        # Level 2
        ("¿Cuál fue el año más difícil de tu familia y cómo lo superaron?", 2),
        ("¿Hay algo de tu familia de origen que reproducís en tu vida sin querer?", 2),
        ("¿Cómo impactó la economía en las decisiones de tu familia a lo largo del tiempo?", 2),
        ("¿Hay alguna expectativa familiar que sentiste que no podías cumplir?", 2),
        ("¿Cuándo fue la última vez que tuviste un conflicto serio con un familiar?", 2),
        ("¿Cómo reaccionaría tu familia si tomás una decisión que va en contra de sus valores?", 2),
        ("¿Cuánto de quién sos es un resultado directo de cómo te criaron?", 2),
        ("¿Hay algún tema del que nunca hablan en tu familia pero que todos saben?", 2),
        ("¿Cómo se maneja el dinero en tu familia?", 2),
        ("¿Hay alguna dinámica familiar que reconocés que no es sana pero que cuesta cambiar?", 2),
        ("¿Cuándo fue la última vez que dijiste 'te quiero' a un familiar?", 2),
        ("¿Qué cosa de tu crianza agradecés genuinamente?", 2),
        ("¿Cuán diferente sos en familia de cómo sos con tus amigos?", 2),
        ("¿Hay algún familiar que sientas que no te conoce de verdad?", 2),
        ("¿Cómo afectó la ausencia de algún familiar tu desarrollo?", 2),
        # Level 3
        ("¿Cuál es el patrón familiar que más querés no repetir?", 3),
        ("¿Hay algo de tu familia que nunca pudiste perdonar del todo?", 3),
        ("¿Cuándo fue la última vez que tu familia te falló cuando más la necesitabas?", 3),
        ("¿Cuán libre te sentís de ser quien sos dentro de tu familia?", 3),
        ("¿Hay algo que tu familia nunca supo de vos y que cambiaría todo si lo supiera?", 3),
    ],

    "amistades": [
        # Level 1
        ("¿Cuántos amigos considerás que tenés de verdad?", 1),
        ("¿Cuál es el plan de último momento que más disfrutaste con amigos?", 1),
        ("¿Cómo conociste al amigo más raro que tenés?", 1),
        ("¿Cuál es la cosa que hacés solo con tus amigos que nunca harías en otro contexto?", 1),
        ("¿Tenés algún amigo que conociste en internet?", 1),
        ("¿Cuándo fue la última vez que conociste a alguien nuevo que pasó a ser amigo?", 1),
        ("¿Cuál es la habilidad que más admirás en un amigo?", 1),
        ("¿Sos el amigo que consuela, el que da consejos o el que distrae?", 1),
        ("¿Cuál es la discusión más ridícula que tuviste con un amigo?", 1),
        ("¿Cuánto duró la amistad más larga que tenés actualmente?", 1),
        ("¿Hay algún amigo que nunca conociste en persona?", 1),
        ("¿Cuál es la sorpresa más grande que te dieron tus amigos?", 1),
        ("¿Qué te diferencia de tus amigos en términos de personalidad?", 1),
        ("¿Cuál es la cosa que te hace volver a ver a tus amigos sin importar la distancia?", 1),
        ("¿Sos de los que llama o prefiere chatear?", 1),
        ("¿Cuándo fue la última vez que te fuiste de viaje con amigos?", 1),
        ("¿Cuál es el consejo de un amigo que marcó tu vida?", 1),
        ("¿Hay algún amigo que llegaste a odiar y luego te volviste a reconciliar?", 1),
        ("¿Cuánto tiempo pasan juntos en persona vs. por mensajes?", 1),
        ("¿Cuál es el plan de amigos que se convirtió en un desastre divertido?", 1),
        # Level 2
        ("¿Cuándo fue la última vez que un amigo te pidió algo que no querías dar?", 2),
        ("¿Hay alguna amistad que mantiene viva más por costumbre que por genuino afecto?", 2),
        ("¿Cuándo fue la última vez que cortaste una amistad? ¿Por qué?", 2),
        ("¿Alguna vez fuiste desleal con un amigo sin que se enterara?", 2),
        ("¿Cómo manejás cuando un amigo toma decisiones que pueden hacerle daño?", 2),
        ("¿Hay algún secreto de un amigo que supiste y que todavía guardás?", 2),
        ("¿Cuándo fue la última vez que un amigo te sorprendió con su generosidad?", 2),
        ("¿Alguna vez te sacrificaste por un amigo y no te lo reconoció?", 2),
        ("¿Cómo afectan las parejas de tus amigos sus amistades contigo?", 2),
        ("¿Cuándo fue la última vez que pusiste un límite con un amigo?", 2),
        ("¿Cuánto pesa la distancia geográfica en tus amistades?", 2),
        ("¿Hay alguna amistad que sientes que se fue apagando sin drama?", 2),
        ("¿Alguna vez te alejaste de alguien por protegerte a vos mismo?", 2),
        ("¿Cuál es la cosa más difícil que le tuviste que decir a un amigo?", 2),
        ("¿Cómo te sentís cuando un amigo tiene éxito donde vos todavía estás luchando?", 2),
        # Level 3
        ("¿Hay alguna amistad que terminó y de la que todavía no te recuperaste del todo?", 3),
        ("¿Cuándo fue la última vez que sentiste que un amigo te conocía mejor que vos mismo?", 3),
        ("¿Qué le pedirías a tus amigos que hicieran diferente en su trato hacia vos?", 3),
        ("¿Cuánto miedo te da quedarte sin tu red de amigos?", 3),
        ("¿Hay algo que nunca mostrás con tus amigos por miedo a que te juzguen?", 3),
    ],

    "exs": [
        # Level 1
        ("¿Cuál fue la ruptura más civilizada que tuviste?", 1),
        ("¿Alguna vez terminaste una relación por mensaje de texto?", 1),
        ("¿Cuánto tiempo te llevó subir fotos nuevas después de una ruptura?", 1),
        ("¿Cuál fue la primera señal de que algo no estaba bien en una relación pasada?", 1),
        ("¿Alguna vez te escribió un ex después de mucho tiempo sin contacto?", 1),
        ("¿Cuándo fue la última vez que pensaste en un ex sin quererlo?", 1),
        ("¿Cuál fue el lugar favorito que tenías con un ex?", 1),
        ("¿Alguna vez bloqueaste a alguien después de terminar? ¿Lo desbloqueste después?", 1),
        ("¿Cuál fue la cosa más sentimental que devolviste (o que te devolvieron) al terminar?", 1),
        ("¿Hay alguna película o lugar que evitás por recuerdos de un ex?", 1),
        ("¿Cuánto duró la relación más corta que tuviste?", 1),
        ("¿Cuál fue el motivo de ruptura más insólito que experimentaste?", 1),
        ("¿Hay algún ex cuyo número todavía tenés guardado con un apodo?", 1),
        ("¿Cuándo fue la última vez que soñaste con un ex?", 1),
        ("¿Cuál es la cosa que aprendiste sobre vos mismo en tu relación más larga?", 1),
        ("¿Alguna vez te compararon con un ex?", 1),
        ("¿Cuántas veces revisaste el perfil de un ex en redes sin interactuar?", 1),
        ("¿Cuál fue el momento más incómodo post-ruptura?", 1),
        ("¿Alguna vez te arrepentiste de terminar una relación?", 1),
        ("¿Cuál es la lección más valiosa que te dejó una relación pasada?", 1),
        # Level 2
        ("¿Alguna vez terminaste una relación de la que dependías emocionalmente? ¿Cómo fue?", 2),
        ("¿Cuándo entendiste que lo que sentías ya no era amor?", 2),
        ("¿Alguna vez volviste con un ex sabiendo que no iba a funcionar?", 2),
        ("¿Qué necesitabas de esa relación que no podías pedir directamente?", 2),
        ("¿Cuánto tiempo duró el duelo de tu ruptura más fuerte?", 2),
        ("¿Hay algo de un ex que genuinamente admirabas?", 2),
        ("¿Cuándo fue la primera vez que dijiste 'ya superé esto' y era verdad?", 2),
        ("¿Cómo cambió una relación tu visión del amor?", 2),
        ("¿Alguna vez tuviste que callar lo que sentías al terminar una relación?", 2),
        ("¿Cuánto peso tienen las experiencias pasadas en cómo te relacionás hoy?", 2),
        ("¿Alguna vez elegiste a alguien que no era para vos para no estar solo?", 2),
        ("¿Cuál fue el momento en que finalmente aceptaste que una relación había terminado?", 2),
        ("¿Hay algo que un ex te dijo que cambió la percepción que tenías de vos mismo?", 2),
        ("¿Cómo manejás el hecho de que tu ex esté con alguien nuevo?", 2),
        ("¿Cuándo fue la última vez que le deseaste bien a un ex de corazón?", 2),
        # Level 3
        ("¿Cuál es la herida de una relación pasada que todavía afecta tu manera de amar?", 3),
        ("¿Hay alguien a quien dejaste ir y que en el fondo no querías dejar ir?", 3),
        ("¿Cuánto de quien sos hoy fue moldeado por el dolor de una ruptura?", 3),
        ("¿Cuál es la cosa que más te cuesta aceptar de cómo terminaron tus relaciones?", 3),
        ("¿Si pudieras hablar cinco minutos con un ex del pasado, qué le dirías?", 3),
    ],

    "personalidad": [
        # Level 1
        ("¿Cuánto tiempo podés estar sin internet antes de inquietarte?", 1),
        ("¿Qué tipo de persona querías ser de grande y en qué medida lo lograste?", 1),
        ("¿Cuál es tu forma favorita de conocer gente nueva?", 1),
        ("¿Cuál fue el consejo que mejor te funcionó en la vida?", 1),
        ("¿Qué es lo que más te motiva a levantarte por la mañana?", 1),
        ("¿Cuántas alarmas ponés para despertar?", 1),
        ("¿Sos de los que llega temprano o siempre llega tarde?", 1),
        ("¿Cuál es la serie que más veces viste?", 1),
        ("¿Qué frase o mantra repetís cuando las cosas se ponen difíciles?", 1),
        ("¿Cómo describís tu sentido del humor?", 1),
        ("¿Qué tipo de persona te saca de quicio más fácilmente?", 1),
        ("¿Sos de guardar la ropa del año anterior o tirás todo?", 1),
        ("¿Qué es lo que más te distrae cuando intentás concentrarte?", 1),
        ("¿Cuánto tiempo podés pasar sin hablar con nadie?", 1),
        ("¿Qué tipo de contenido consumís más: videos, podcasts, libros o redes?", 1),
        ("¿Cómo sos en situaciones de estrés: te bloqueás o te activás?", 1),
        ("¿Cuántas veces por día revisás el celular?", 1),
        ("¿Qué es lo primero que hacés cuando no sabés qué hacer?", 1),
        ("¿Sos de los que dice sí cuando quiere decir no?", 1),
        ("¿Cuánto de tu tiempo libre es de calidad real?", 1),
        ("¿Cuál fue el hábito que más costó trabajo cambiar?", 1),
        ("¿Preferís el ruido de fondo o el silencio para trabajar?", 1),
        ("¿Cuánto influye tu estado de ánimo en el de los que te rodean?", 1),
        ("¿Qué tipo de situación te hace sentir más vivo?", 1),
        ("¿Cuál es tu opinión más polémica sobre algo del día a día?", 1),
        # Level 2
        ("¿Cuándo fue la última vez que actuaste en contra de lo que creés?", 2),
        ("¿Qué versión de vos mismo le mostrás al mundo vs. la que guardás?", 2),
        ("¿Hay alguna parte de tu carácter que reconocés que le hace daño a los demás?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que estabas equivocado y lo admitiste?", 2),
        ("¿Qué es lo que más te cuesta pedir?", 2),
        ("¿Cuánto peso tiene la crítica ajena en cómo te ves?", 2),
        ("¿Cuál es el patrón de comportamiento que más repetís en situaciones de conflicto?", 2),
        ("¿Cuándo fue la última vez que hiciste algo por pura rebeldía?", 2),
        ("¿Qué tan fácil es para vos pedir disculpas de corazón?", 2),
        ("¿Hay algo que reconocés que hacés por inseguridad aunque lo justificás diferente?", 2),
        ("¿Cuándo fue la última vez que cambiaste de opinión sobre algo importante?", 2),
        ("¿Cuánto de tu comportamiento está condicionado por el miedo al juicio?", 2),
        ("¿Cuál es el límite que sabés que deberías poner pero que no terminás de poner?", 2),
        ("¿Qué cosa de vos mismo te cuesta más aceptar?", 2),
        ("¿Cuándo fue la última vez que dejaste que alguien te ayudara sin sentirte mal?", 2),
        # Level 3
        ("¿Cuál es la sombra de tu personalidad que más te cuesta reconocer?", 3),
        ("¿Cuánto de quien sos es genuino y cuánto es adaptación al entorno?", 3),
        ("¿Hay algo de tu carácter que sabés que viene de un dolor que no sanaste?", 3),
        ("¿Cuándo fue la última vez que te sentiste completamente en paz con quien sos?", 3),
        ("¿Qué parte de vos mismo rechazás que en el fondo es la que más te define?", 3),
    ],

    "miedos": [
        # Level 1
        ("¿Cuál es el tipo de película que definitivamente no podés ver solo?", 1),
        ("¿Le tenés miedo a algo que en teoría debería ser inofensivo?", 1),
        ("¿Cuándo fue la última vez que algo te dio un susto de verdad?", 1),
        ("¿Qué lugar o ambiente te genera incomodidad sin razón clara?", 1),
        ("¿Le tenés miedo a las tormentas?", 1),
        ("¿Cuántas veces verificás que cerraste la puerta antes de salir?", 1),
        ("¿Cuál es la fobia más extraña que conocés de alguien?", 1),
        ("¿Qué sonido te despierta de un sueño profundo?", 1),
        ("¿Cuál es la pesadilla que más se repite en tu vida?", 1),
        ("¿Le tenés miedo al agua profunda o a las alturas más?", 1),
        ("¿Qué haría falta para que entrases a una casa abandonada de noche?", 1),
        ("¿Cuál fue el momento más escalofriante que viviste en la vida real?", 1),
        ("¿Le tenés miedo a las agujas o a los procedimientos médicos?", 1),
        ("¿Hay alguna textura, olor o sabor que te genera un rechazo físico?", 1),
        ("¿Cuándo fue la última vez que dormiste con la luz prendida?", 1),
        ("¿Cuál es el animal que más evitás en la vida cotidiana?", 1),
        ("¿Qué actividad de aventura nunca jamás harías por más dinero?", 1),
        ("¿Le tenés miedo a los payasos o a alguna figura infantil específica?", 1),
        ("¿Cuándo fue la última vez que pediste que alguien revisara algo de la casa por vos?", 1),
        ("¿Cuál es la superstición que seguís aunque no lo quieras admitir?", 1),
        # Level 2
        ("¿Qué tan seguido el miedo al ridículo te frena?", 2),
        ("¿Cuándo fue la última vez que el miedo te impidió ser honesto?", 2),
        ("¿Hay algo que sabés que deberías enfrentar y que seguís evitando?", 2),
        ("¿Cuánto miedo le tenés a la enfermedad propia o de alguien querido?", 2),
        ("¿Cuál fue el momento en que el miedo tomó una decisión por vos?", 2),
        ("¿Cuánto peso tiene el miedo al fracaso vs. el miedo al éxito en tus decisiones?", 2),
        ("¿Hay algo que te genera ansiedad anticipatoria constante?", 2),
        ("¿Cuándo fue la última vez que enfrentaste algo que te daba miedo y salió bien?", 2),
        ("¿Cuánto de tu control sobre el entorno está motivado por el miedo?", 2),
        ("¿Hay algo que le tenés miedo de decirle a alguien cercano?", 2),
        ("¿Cuándo fue la última vez que el miedo te protegió de algo real?", 2),
        ("¿Cuánto miedo te da perder la salud mental o emocional?", 2),
        ("¿Hay algún miedo que transferiste sin querer a alguien que amás?", 2),
        ("¿Cuándo fue la última vez que actuaste a pesar del miedo?", 2),
        ("¿Qué tan seguido el miedo al abandono afecta tus relaciones?", 2),
        # Level 3
        ("¿Cuál es el miedo que más define quién sos y que más querés soltar?", 3),
        ("¿Hay algo que te da terror de conocer si mirás muy adentro tuyo?", 3),
        ("¿Cuánto de tu vida cotidiana está organizada para evitar algo que te aterra?", 3),
        ("¿Cuál es el miedo que más vergüenza te da tener?", 3),
        ("¿Si pudieras vivir sin tu miedo más profundo, quién serías?", 3),
    ],

    "logros": [
        # Level 1
        ("¿Cuál fue el momento en que te sentiste más orgulloso en el trabajo o estudio?", 1),
        ("¿Hay alguna habilidad que desarrollaste de cero y que te sorprende a vos mismo?", 1),
        ("¿Cuándo fue la última vez que alguien te felicitó por algo que hiciste?", 1),
        ("¿Cuál fue el desafío físico más grande que superaste?", 1),
        ("¿Qué proyecto personal completaste que se sentía imposible al principio?", 1),
        ("¿Cuál fue la primera vez que ganaste dinero por algo que te apasionaba?", 1),
        ("¿Cuándo fue la última vez que te pusiste una meta difícil y la cumpliste?", 1),
        ("¿Cuál es la cosa más perseverante que hiciste en tu vida?", 1),
        ("¿Tenés alguna certificación, título o reconocimiento del que estés orgulloso?", 1),
        ("¿Cuándo fue la última vez que aprendiste algo nuevo desde cero?", 1),
        ("¿Cuál fue el logro de un amigo o familiar del que te sentiste tan orgulloso como si fuera tuyo?", 1),
        ("¿Hay algo que lograste de lo que no hablás mucho pero que significa mucho para vos?", 1),
        ("¿Cuál fue el momento en que te diste cuenta de que podías más de lo que creías?", 1),
        ("¿Cuántas veces te negaron algo y lo lograste de todas formas?", 1),
        ("¿Cuál es el récord personal que más querés superar?", 1),
        ("¿Cuándo fue la primera vez que sentiste que eras bueno en algo?", 1),
        ("¿Cuál fue la vez que más improvisaste y salió bien?", 1),
        ("¿Hay alguna dificultad que superaste sola/o y que nadie sabe?", 1),
        ("¿Cuándo fue la última vez que hiciste algo que te salió a la primera?", 1),
        ("¿Cuál fue la primera vez que alguien confió en vos para algo importante?", 1),
        # Level 2
        ("¿Cuándo fue la última vez que celebraste un logro propio de verdad?", 2),
        ("¿Hay algo que lograste y luego dejaste ir más fácil de lo que esperabas?", 2),
        ("¿Cuánto de lo que lograste fue gracias a ayuda externa y cuánto fue solo tuyo?", 2),
        ("¿Cuándo fue la última vez que sentiste que alcanzar algo no fue suficiente?", 2),
        ("¿Hay algo que lograste que al principio no querías y terminó siendo fundamental?", 2),
        ("¿Cuánto de tu identidad depende de lo que lograste?", 2),
        ("¿Cuándo fue la última vez que renunciaste a algo a tiempo?", 2),
        ("¿Cómo manejás cuando algo que lograste con esfuerzo se desmorona?", 2),
        ("¿Hay un logro que minimizás por miedo a parecer arrogante?", 2),
        ("¿Qué es lo que más te costó trabajo aceptar que no podías lograr?", 2),
        ("¿Cuándo fue la última vez que rompiste tu propio techo de expectativas?", 2),
        ("¿Hay algo que lograste y que en el fondo no te hace feliz?", 2),
        ("¿Cuánto de tu esfuerzo cotidiano tiene sentido para vos más allá del resultado?", 2),
        ("¿Cuál fue la vez que más dudaste de vos mismo antes de lograr algo importante?", 2),
        ("¿Cuándo sentiste por primera vez que ya no necesitabas la aprobación ajena para sentirte capaz?", 2),
        # Level 3
        ("¿Cuál es el logro del que nunca hablás porque no creés que los demás puedan entenderlo?", 3),
        ("¿Cuándo fue la última vez que hiciste algo que el mundo nunca sabrá y que te importó igual?", 3),
        ("¿Qué tan seguido el miedo a fallar te impide intentar cosas que podrían ser enormes?", 3),
        ("¿Cuál es la cosa que todavía no lograste y que más duele reconocer?", 3),
        ("¿Qué significaría para vos vivir plenamente de lo que te apasiona?", 3),
    ],

    "sinFiltro": [
        # Level 1
        ("¿Cuántas veces al día revisás el estado de tus contactos para ver cuándo fue la última vez activos?", 1),
        ("¿Cuál es la canción que ponés a máximo volumen cuando estás solo?", 1),
        ("¿Alguna vez comiste algo caído al piso? ¿Cuántos segundos duró en el piso?", 1),
        ("¿Cuántas veces al mes llenas el carrito de compras online y no comprás nada?", 1),
        ("¿Cuál es la cosa más ridícula que buscaste en YouTube a las 3 AM?", 1),
        ("¿Alguna vez leíste el final de un libro primero?", 1),
        ("¿Cuántas contraseñas tenés y cuántas son variaciones de la misma?", 1),
        ("¿Cuál es la frase que usás para salir de conversaciones que no querés tener?", 1),
        ("¿Cuántas notificaciones sin leer tenés en este momento?", 1),
        ("¿Alguna vez fingiste estar ocupado para no ayudar?", 1),
        ("¿Cuál es el meme que más te hizo reír en el último mes?", 1),
        ("¿Cuántas veces al semana comés de pie sobre la mesada?", 1),
        ("¿Cuál es el pensamiento más absurdo que tuviste esta semana?", 1),
        ("¿Alguna vez lloraste en el baño para que nadie te viera?", 1),
        ("¿Cuántos grupos de WhatsApp tenés silenciados permanentemente?", 1),
        ("¿Cuál es el compra impulsiva más cara que hiciste?", 1),
        ("¿Alguna vez mandaste el mismo meme a dos personas del mismo grupo?", 1),
        ("¿Cuánto tiempo podés pasar viendo videos de gatitos sin darte cuenta?", 1),
        ("¿Cuál es tu teoría más ridícula sobre algo mundano?", 1),
        ("¿Cuántas veces cambiaste de Netflix en una tarde sin ver nada?", 1),
        # Level 2
        ("¿Alguna vez le dijiste algo feo a alguien y te sentiste mejor después?", 2),
        ("¿Cuándo fue la última vez que actuaste desde la envidia?", 2),
        ("¿Cuál fue la mentira más descarada que contaste en un contexto laboral?", 2),
        ("¿Alguna vez te fuiste de un evento sin avisar a nadie?", 2),
        ("¿Cuántas veces usaste 'me quedé sin batería' para evitar responder?", 2),
        ("¿Cuándo fue la última vez que dijiste 'ya lo hago' y no lo hiciste?", 2),
        ("¿Alguna vez viste algo que no debías en el teléfono o computadora de alguien?", 2),
        ("¿Cuántas cosas tenés en 'favoritos' que en realidad nunca vas a comprar?", 2),
        ("¿Alguna vez fingiste que no recibiste un mensaje?", 2),
        ("¿Cuándo fue la última vez que actuaste con petulancia o soberbia?", 2),
        ("¿Hay algo que hacés cuando nadie te ve que jamás admitirías en público?", 2),
        ("¿Cuántas veces dijiste 'sí' a algo y después cancelaste?", 2),
        ("¿Cuándo fue la última vez que actuaste por puro orgullo y te arrepentiste?", 2),
        ("¿Alguna vez manipulaste una situación para salir vos favorecido?", 2),
        ("¿Cuántas veces al mes pensás en alguien que no deberías estar pensando?", 2),
        # Level 3
        ("¿Cuál es el secreto que jamás le contarías a alguien de este grupo aunque confiaras en ellos?", 3),
        ("¿Cuándo fue la última vez que hiciste algo absolutamente deshonesto y te quedó rondando?", 3),
        ("¿Cuál es tu mayor hipocresía personal: algo que pregonás pero no practicás?", 3),
        ("¿Cuánto de tus logros públicos tapan algo que en privado te produce vergüenza?", 3),
        ("¿Cuál es la fantasía más loca que tenés y que nunca actuarías porque no hay forma?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS2:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS2[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
