#!/usr/bin/env python3
"""Batch 8 - themes: gratitude, regrets, identity, humor, embarrassment, nostalgia, community, generosity, boundaries, self-care."""
import json

ADDITIONS8 = {
    "infancia": [
        ("¿Cuál fue el momento de tu infancia por el que más agradecido estás hoy?", 1),
        ("¿Qué cosa de tu infancia extrañás más cuando estás estresado?", 1),
        ("¿Cuál fue la primera vez que sentiste vergüenza delante de alguien que te importaba?", 1),
        ("¿Cuál es la escena de tu infancia que más te hace reír cuando la recordás?", 1),
        ("¿Cuándo fue la primera vez que perteneciste a una comunidad fuera de la familia?", 1),
        ("¿Cuál fue el acto de generosidad más grande que viste de chico?", 1),
        ("¿Cuándo fue la primera vez que pusiste un límite a alguien?", 1),
        ("¿Cuándo fue la primera vez que te cuidaste solo cuando algo te dolía?", 1),
        ("¿Cuál fue la cosa que más te daba vergüenza de chico y que hoy te parece adorable?", 1),
        ("¿Cuándo fue la primera vez que extrañaste algo que ya no existía?", 1),
        ("¿Cuál fue el gesto más generoso de alguien de tu infancia hacia vos?", 1),
        ("¿Cuándo fue la primera vez que defendiste a alguien más débil?", 1),
        ("¿Cuándo fue la primera vez que alguien te dijo 'gracias' y te cambió el día?", 1),
        ("¿Cuál fue la primera vez que dijiste algo que te arrepentiste inmediatamente?", 1),
        ("¿Cuándo fue la primera vez que te sentiste parte de algo más grande que vos?", 1),
        ("¿Cuándo fue la primera vez que la generosidad de otro cambió cómo veías el mundo?", 1),
        ("¿Cuándo fue la primera vez que pusiste un límite y alguien lo respetó?", 1),
        ("¿Cuándo fue la primera vez que te cuidaste en lugar de cuidar a todos los demás?", 1),
        ("¿Cuándo fue la primera vez que la nostalgia de algo todavía presente te hizo darte cuenta de que lo ibas a extrañar?", 1),
        ("¿Cuál fue el grupo o club al que perteneciste que más formó parte de quien sos?", 1),
        ("¿Cuándo fue la primera vez que algo de tu identidad que te avergonzaba se convirtió en algo de lo que te enorgullecías?", 2),
        ("¿Hay alguna persona de tu infancia a quien no le agradeciste lo suficiente?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que pertenecías más a un lugar que a otro?", 2),
        ("¿Hay algo de tu infancia que haría diferente y que todavía te pesa?", 2),
        ("¿Cuándo empezaste a construir los límites que hoy tenés?", 2),
        ("¿Cuándo fue la primera vez que cuidarte a vos mismo entró en conflicto con cuidar a otros?", 2),
        ("¿Cuándo fue la primera vez que un acto de generosidad hacia vos cambió cómo te veías?", 2),
        ("¿Cuándo fue la primera vez que la vergüenza de pertenecer a algo te hizo querer pertenecer a otra cosa?", 2),
        ("¿Cuándo fue la primera vez que el humor fue tu manera de manejar algo que te dolía?", 2),
        ("¿Cuándo fue la primera vez que pusiste límites a alguien que amabas y te costó más que la situación misma?", 2),
        ("¿Cuándo fue la primera vez que la vergüenza te impidió ser quien realmente eras?", 3),
        ("¿Qué parte de tu identidad de la infancia protegiste a toda costa aunque te costó mucho?", 3),
        ("¿Cuándo fue la primera vez que te arrepentiste de algo lo suficientemente profundo como para cambiar?", 3),
        ("¿Cuánto de la gratitud que tenés hoy viene de haber pasado por cosas que entonces parecían solo dolor?", 3),
        ("¿Qué comunidad o grupo de tu infancia te moldeó más de lo que entonces entendías?", 3),
        ("¿Cuándo fue la primera vez que pusiste tus propias necesidades antes que las de otros y te sentiste mal por ello?", 3),
        ("¿Hay algo de tu infancia que todavía te genera arrepentimiento y que no lograste cerrar del todo?", 3),
        ("¿Cuándo fue la primera vez que entendiste que el cuidado propio no era egoísmo?", 3),
        ("¿Cuándo fue la primera vez que la identidad que los demás te asignaron entró en colisión con la que vos sentías?", 3),
        ("¿Cuándo fue la primera vez que el humor fue el único idioma que te dejaron usar para decir algo serio?", 3),
        ("¿Cuándo fue la primera vez que la nostalgia de algo que perdiste te hizo entender cuánto lo valorabas?", 3),
        ("¿Cuándo fue la primera vez que ser generoso con alguien te costó algo real?", 3),
        ("¿Cuándo fue la primera vez que poner un límite fue más difícil que aguantar lo que el límite buscaba frenar?", 3),
        ("¿Cuándo fue la primera vez que la vergüenza te enseñó algo que la comodidad no hubiera podido?", 3),
        ("¿Cuándo fue la primera vez que pertenecer a algo requirió que abandonaras otra parte de vos?", 3),
        ("¿Cuándo fue la primera vez que el arrepentimiento fue más maestro que cualquier éxito?", 3),
        ("¿Cuándo fue la primera vez que cuidarte te hizo sentir que le fallabas a alguien que querías?", 3),
        ("¿Cuándo fue la primera vez que la nostalgia de un lugar o tiempo te hizo entender que la identidad es también historia?", 3),
        ("¿Cuándo fue la primera vez que la generosidad de alguien te hizo querer ser mejor de lo que eras?", 3),
        ("¿Cuándo fue la primera vez que la gratitud te cambió la percepción de algo que creías solo negativo?", 3),
    ],

    "futuro": [
        ("¿Por qué cosas de tu vida actual estás más agradecido de cara al futuro?", 1),
        ("¿Hay algo que hoy hacés y que en el futuro te vas a arrepentir de no haberlo valorado más?", 1),
        ("¿Cómo querés que sea tu identidad en 10 años?", 1),
        ("¿Qué cosa querés poder reírte de vos mismo en el futuro?", 1),
        ("¿Cómo querés que sea tu relación con la vergüenza cuando seas mayor?", 1),
        ("¿Qué lugar o comunidad del pasado extrañarías si te fueras?", 1),
        ("¿Qué tipo de comunidad querés construir o integrar en el futuro?", 1),
        ("¿Cuál es el acto de generosidad que querés haber hecho antes de que sea tarde?", 1),
        ("¿Cuáles son los límites que querés tener más claros en el futuro?", 1),
        ("¿Cómo querés cuidarte en el futuro de maneras que hoy no te permitís?", 1),
        ("¿Qué arrepentimiento de hoy podés evitar tomando una decisión esta semana?", 1),
        ("¿Qué parte de tu identidad querés que sea más visible en el futuro?", 1),
        ("¿Cuándo fue la última vez que te imaginaste agradeciéndole algo a alguien del presente en el futuro?", 1),
        ("¿Qué tipo de humor querés que te caracterice cuando seas mayor?", 1),
        ("¿Qué tipo de nostalgia querés sentir cuando mires este período de tu vida?", 1),
        ("¿Qué parte de tu comunidad actual querés que siga en tu vida en 10 años?", 1),
        ("¿Cuánto de la gratitud que querés sentir en el futuro depende de cosas que podés hacer hoy?", 1),
        ("¿Cuánto de los límites que querés tener en el futuro estás entrenando hoy?", 1),
        ("¿Qué versión de vos mismo querés que sea la que más te dé vergüenza dentro de 10 años porque así creciste?", 1),
        ("¿Cuánto de quien querés ser en el futuro ya sos en los momentos que nadie mira?", 1),
        ("¿Cuánto de vos mismo estás dispuesto a soltar para convertirte en quien querés ser?", 2),
        ("¿Cuándo fue la última vez que pensaste en lo que te vas a arrepentir en el lecho de muerte?", 2),
        ("¿Cuánto de tu identidad futura está en construcción y cuánto ya está fija?", 2),
        ("¿Cuándo fue la última vez que redefiniste dónde y con quién querés pertenecer?", 2),
        ("¿Cuánto de la generosidad que querés tener en el futuro te cuesta practicarla hoy?", 2),
        ("¿Cuándo fue la última vez que pusiste un límite que te acercó más al futuro que querés?", 2),
        ("¿Cuánto del cuidado propio que necesitás en el futuro estás postergando hoy?", 2),
        ("¿Cuándo fue la última vez que imaginaste el futuro como un lugar donde ya aprendiste a cuidarte mejor?", 2),
        ("¿Cuándo fue la última vez que la nostalgia del futuro que querías cuando eras joven te ayudó a redirigir el presente?", 2),
        ("¿Cuándo fue la última vez que pensaste qué comunidades querés haber construido cuando mires hacia atrás?", 2),
        ("¿Cuándo fue la última vez que te preguntaste qué versión de vos mismo te va a generar gratitud cuando seas viejo?", 2),
        ("¿Cuándo fue la última vez que imaginaste el mejor y peor escenario de una decisión importante y lo usaste bien?", 2),
        ("¿Cuándo fue la última vez que le dijiste a alguien cómo querés que sea tu vida y no te dio vergüenza decirlo?", 2),
        ("¿Cuándo fue la última vez que te preguntaste si estás viviendo una vida que en el futuro te va a dar vergüenza?", 3),
        ("¿Cuál es el arrepentimiento que más te guiaría si lo usaras como brújula para el futuro?", 3),
        ("¿Cuándo fue la última vez que imaginaste el futuro con gratitud en lugar de con ansiedad?", 3),
        ("¿Cuánto de tu identidad futura depende de que te perdones algo del presente?", 3),
        ("¿Cuál es la comunidad que necesitás construir o encontrar para que el futuro que querés sea posible?", 3),
        ("¿Cuándo fue la última vez que preguntaste qué necesitabas realmente en lugar de qué debías tener?", 3),
        ("¿Cuánto del autocuidado que te negás hoy lo estás pagando con interés en el futuro?", 3),
        ("¿Cuándo fue la última vez que imaginaste el final de tu vida y lo usaste para decidir algo hoy?", 3),
        ("¿Cuándo fue la última vez que la nostalgia de quién eras te confrontó con quién estás eligiendo ser?", 3),
        ("¿Cuándo fue la última vez que la vergüenza de quién sos hoy fue un motor para quien querés ser mañana?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento fue la brújula más honesta que usaste?", 3),
        ("¿Cuánto de la identidad que querés en el futuro requiere que abandones algo de quien sos hoy?", 3),
        ("¿Cuándo fue la última vez que imaginaste ser completamente generoso en el futuro y te diste cuenta de que podrías serlo hoy?", 3),
        ("¿Cuándo fue la última vez que pusiste un límite que te alineó con quien querés ser en el futuro?", 3),
        ("¿Cuándo fue la última vez que el cuidado de vos mismo fue la decisión más valiente que tomaste?", 3),
        ("¿Cuánto de la gratitud que querés sentir en el futuro depende de no arrepentirte de los límites que no pusiste hoy?", 3),
        ("¿Cuándo fue la última vez que imaginaste que la comunidad en la que querés vivir ya existe y solo tenés que elegirla?", 3),
    ],

    "amor": [
        ("¿Cuándo fue la última vez que le agradeciste a alguien que amás simplemente por estar?", 1),
        ("¿Hay algo de una relación que terminó por lo que hoy le tenés gratitud?", 1),
        ("¿Cuál fue la situación más vergonzosa que viviste en pareja?", 1),
        ("¿Cuándo fue la última vez que te reíste tanto en pareja que te dolió la cara?", 1),
        ("¿Cuándo fue la última vez que extrañaste una versión pasada del amor que tuviste?", 1),
        ("¿Cuándo fue la última vez que hiciste algo generoso por una pareja sin esperar nada?", 1),
        ("¿Cuándo fue la última vez que pusiste un límite en una relación por amor propio?", 1),
        ("¿Cuándo fue la última vez que te cuidaste emocionalmente dentro de una relación?", 1),
        ("¿Hay algo de cómo amaste en el pasado de lo que te arrepentís?", 1),
        ("¿Cuándo fue la última vez que un recuerdo de amor te acompañó en un momento difícil?", 1),
        ("¿Cuándo fue la última vez que tu sentido del humor salvó una situación tensa en pareja?", 1),
        ("¿Cuál es la nostalgia más tierna que tenés de alguna relación pasada?", 1),
        ("¿Cuándo fue la última vez que pudiste reírte de vos mismo frente a quien amabas?", 1),
        ("¿Hay algo de una relación que terminó y de lo que todavía te arrepentís?", 1),
        ("¿Cuándo fue la última vez que el amor te hizo más generoso con alguien que no era tu pareja?", 1),
        ("¿Cuándo fue la última vez que el humor compartido fue el pegamento de una relación que andaba mal?", 1),
        ("¿Cuándo fue la última vez que agradeciste a alguien que amabas no por lo que hacía sino por quién era?", 1),
        ("¿Cuándo fue la última vez que la nostalgia de una relación te hizo más cuidadoso con la actual?", 1),
        ("¿Cuándo fue la última vez que pusiste un límite en el amor y la relación mejoró?", 1),
        ("¿Cuándo fue la última vez que cuidarte en una relación fue un acto de amor también hacia el otro?", 1),
        ("¿Cuándo fue la última vez que pusiste límites en el amor y te sentiste más libre?", 2),
        ("¿Cuánto de la gratitud que tenés hacia parejas pasadas tardaste en poder sentirla?", 2),
        ("¿Cuándo fue la última vez que tu identidad cambió dentro de una relación?", 2),
        ("¿Cuándo fue la última vez que la vergüenza en el amor te impidió ser auténtico?", 2),
        ("¿Cuánto del autocuidado que practicás hoy aprendiste de relaciones que te lastimaron?", 2),
        ("¿Cuándo fue la última vez que tu arrepentimiento en el amor te llevó a ser diferente con alguien nuevo?", 2),
        ("¿Cuándo fue la última vez que el amor te empujó fuera de tu comunidad de confort?", 2),
        ("¿Cuándo fue la última vez que el humor fue el escudo detrás del que escondiste algo que dolía?", 2),
        ("¿Cuándo fue la última vez que la generosidad en el amor fue posible porque primero te cuidaste?", 2),
        ("¿Cuándo fue la última vez que la vergüenza fue la razón por la que no dijiste lo que sentías?", 2),
        ("¿Cuándo fue la última vez que la nostalgia de cómo amabas antes te hizo querer volver a ese lugar?", 2),
        ("¿Cuándo fue la última vez que el arrepentimiento en el amor te hizo elegir diferente con alguien que estaba frente a vos?", 2),
        ("¿Cuándo fue la última vez que la comunidad que tenías a tu alrededor cambió la manera en que pudiste amar?", 2),
        ("¿Cuándo fue la última vez que le agradeciste a alguien que te amó por haberte dejado ir?", 3),
        ("¿Cuál es el límite en el amor que te costó más poner y que más te liberó?", 3),
        ("¿Cuándo fue la última vez que el amor te obligó a redefinir quién eras?", 3),
        ("¿Cuánto del autocuidado que te negás en el amor viene de creer que no merecés más?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento en el amor te hizo más compasivo con vos mismo?", 3),
        ("¿Cuál es la vergüenza más profunda que cargás en tu historia amorosa?", 3),
        ("¿Cuándo fue la última vez que elegiste ser generoso en el amor aunque te hubieran lastimado?", 3),
        ("¿Cuál es la identidad en el amor que abandonaste para ser quien creías que tenías que ser?", 3),
        ("¿Cuándo fue la última vez que la gratitud por alguien que ya no está te hizo valorar más a quien sí está?", 3),
        ("¿Cuándo fue la última vez que el humor fue lo único que te quedó para sobrevivir algo difícil en el amor?", 3),
        ("¿Cuándo fue la última vez que la nostalgia del amor fue más honesta que cualquier cosa que digas sobre él?", 3),
        ("¿Cuándo fue la última vez que la comunidad de gente que te rodea cambió lo que creías merecer en el amor?", 3),
        ("¿Cuándo fue la última vez que cuidarte en el amor requirió que también cuidaras al otro de algo que te pedía?", 3),
        ("¿Cuándo fue la última vez que la generosidad en el amor fue una elección y no una obligación?", 3),
        ("¿Cuándo fue la última vez que la vergüenza en el amor te enseñó algo que no podrías haber aprendido de otra manera?", 3),
        ("¿Cuándo fue la última vez que un límite en el amor fue también un acto de amor hacia la otra persona?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento en el amor fue también la primera vez que te cuidaste de verdad?", 3),
    ],

    "familia": [
        ("¿Cuándo fue la última vez que le agradeciste a un familiar por algo que nunca antes mencionaste?", 1),
        ("¿Hay algo de tu familia que hoy extrañás y que entonces no valorabas?", 1),
        ("¿Cuándo fue la última vez que te reíste hasta llorar con alguien de tu familia?", 1),
        ("¿Cuál fue la situación más vergonzosa que viviste por culpa de un familiar?", 1),
        ("¿Cuándo fue la primera vez que te sentiste parte de una comunidad más allá de tu familia?", 1),
        ("¿Cuándo fue la última vez que un familiar hizo algo muy generoso que te sorprendió?", 1),
        ("¿Cuándo fue la primera vez que pusiste un límite a un familiar?", 1),
        ("¿Cuándo fue la última vez que te cuidaste en una situación familiar difícil?", 1),
        ("¿Hay algo que hiciste con tu familia de lo que te arrepentís?", 1),
        ("¿Cuál es la nostalgia más potente que tenés de tu familia cuando eras chico?", 1),
        ("¿Cuándo fue la última vez que el humor de tu familia te sacó de un momento tenso?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te sorprendió con su generosidad?", 1),
        ("¿Cuándo fue la última vez que la identidad familiar te ayudó a entender la tuya propia?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que algo de tu familia que te daba vergüenza te hace único?", 1),
        ("¿Cuándo fue la última vez que le mostraste gratitud a tu familia de una manera que los sorprendió?", 1),
        ("¿Cuándo fue la última vez que la nostalgia familiar te hizo llamar a alguien que no llamabas hace tiempo?", 1),
        ("¿Cuándo fue la última vez que el humor familiar fue el idioma en el que mejor se entendieron?", 1),
        ("¿Cuándo fue la última vez que pusiste un límite en tu familia y mejoró la relación?", 1),
        ("¿Cuándo fue la última vez que cuidaste tu salud emocional en una situación familiar?", 1),
        ("¿Cuándo fue la última vez que la generosidad de alguien de tu familia te cambió algo?", 1),
        ("¿Cuándo fue la última vez que el humor familiar cruzó una línea y alguien salió lastimado?", 2),
        ("¿Cuánto te cuesta poner límites en la familia sin sentirte culpable?", 2),
        ("¿Hay algo de tu identidad que tu familia todavía no terminó de aceptar?", 2),
        ("¿Cuándo fue la última vez que te cuidaste en una relación familiar sin pedir permiso?", 2),
        ("¿Cuánto de la gratitud que tenés por tu familia fue creciendo con los años?", 2),
        ("¿Cuándo fue la última vez que la nostalgia familiar te hizo ver el presente de manera diferente?", 2),
        ("¿Cuándo fue la última vez que el arrepentimiento de algo con tu familia te hizo cambiar cómo te relacionás?", 2),
        ("¿Cuándo fue la última vez que la vergüenza familiar fue algo que vos tuviste que cargar aunque no era tuya?", 2),
        ("¿Cuándo fue la última vez que la comunidad familiar te protegió de algo aunque no lo eligiste?", 2),
        ("¿Cuándo fue la última vez que ser generoso con tu familia te costó algo que en retrospectiva valió la pena?", 2),
        ("¿Cuándo fue la última vez que perdonaste a un familiar sin necesitar que cambiara?", 3),
        ("¿Cuál es el límite que más te costó poner en tu familia y que más te liberó?", 3),
        ("¿Cuánto de tu identidad es una reacción a quién tu familia necesitaba que fueras?", 3),
        ("¿Cuándo fue la última vez que te arrepentiste de algo con un familiar y lo dijiste en voz alta?", 3),
        ("¿Cuánto del autocuidado que practicás hoy tuviste que aprender en soledad porque tu familia no te lo enseñó?", 3),
        ("¿Cuándo fue la última vez que la vergüenza familiar fue la razón por la que no mostraste quién sos?", 3),
        ("¿Cuándo fue la última vez que la nostalgia familiar te confrontó con lo que elegís repetir y lo que elegís romper?", 3),
        ("¿Cuándo fue la última vez que la gratitud por tu familia coexistió con el dolor de lo que no pudo darte?", 3),
        ("¿Cuándo fue la última vez que ser generoso con tu familia requirió que primero lo fueras con vos mismo?", 3),
        ("¿Cuándo fue la última vez que la comunidad de tu familia amplió lo que creías posible en lugar de limitarlo?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento de haber dejado pasar algo con un familiar fue más pesado que cualquier conflicto?", 3),
        ("¿Cuándo fue la última vez que poner límites en tu familia requirió que soportaras que te vieran como el problema?", 3),
        ("¿Cuándo fue la última vez que cuidarte en tu familia fue también cuidar la relación?", 3),
        ("¿Cuándo fue la última vez que la identidad que tu familia te dio fue tanto una jaula como una raíz?", 3),
        ("¿Cuándo fue la última vez que la generosidad de tu familia fue también una forma de control?", 3),
        ("¿Cuándo fue la última vez que la vergüenza de algo de tu familia te hizo sentir que tenías que compensarlo?", 3),
        ("¿Cuándo fue la última vez que la nostalgia de algo que ya no podés recuperar de tu familia te hizo más presente con lo que sí tenés?", 3),
        ("¿Cuándo fue la última vez que la gratitud por tu familia fue difícil de sentir y la sentiste igual?", 3),
        ("¿Cuándo fue la última vez que los límites que pusiste en tu familia definieron qué tipo de persona sos?", 3),
        ("¿Cuándo fue la última vez que el autocuidado dentro de tu familia fue también el regalo más honesto que pudiste dar?", 3),
    ],

    "amistades": [
        ("¿Cuándo fue la última vez que le agradeciste a un amigo por algo muy específico?", 1),
        ("¿Hay alguna amistad pasada que extrañás con nostalgia genuina?", 1),
        ("¿Cuándo fue la última vez que te reíste con un amigo hasta que no podías más?", 1),
        ("¿Cuál fue la situación más vergonzosa que viviste con amigos?", 1),
        ("¿Cómo describís la comunidad de amigos que tenés actualmente?", 1),
        ("¿Cuándo fue la última vez que un amigo hizo algo muy generoso por vos?", 1),
        ("¿Cuándo fue la última vez que pusiste un límite con un amigo?", 1),
        ("¿Cuándo fue la última vez que te cuidaste emocionalmente dentro de una amistad?", 1),
        ("¿Hay alguna amistad de la que te arrepentís de cómo terminó?", 1),
        ("¿Cuándo fue la última vez que la nostalgia de una amistad pasada te agarró por sorpresa?", 1),
        ("¿Cuándo fue la última vez que el humor de tus amigos te sanó algo que palabras no hubieran podido?", 1),
        ("¿Cuándo fue la última vez que ser generoso con un amigo te costó pero lo hiciste igual?", 1),
        ("¿Cuándo fue la última vez que agradeciste una amistad por lo que te desafía y no solo por lo que te da?", 1),
        ("¿Cuándo fue la última vez que la vergüenza compartida con un amigo se convirtió en un recuerdo que los une?", 1),
        ("¿Cuándo fue la última vez que te imaginaste extrañando la etapa de amistades en la que estás ahora?", 1),
        ("¿Cuándo fue la última vez que le pusiste un límite a un amigo y la amistad sobrevivió mejor?", 1),
        ("¿Cuándo fue la última vez que la identidad de tu grupo de amigos te dio algo que no podías encontrar solo?", 1),
        ("¿Cuándo fue la última vez que cuidarte fue posible porque un amigo te lo recordó?", 1),
        ("¿Cuándo fue la última vez que el arrepentimiento de algo con un amigo te hizo ser más presente?", 1),
        ("¿Cuándo fue la última vez que la comunidad de amigos que tenés te hizo sentir que pertenecés?", 1),
        ("¿Cuándo fue la última vez que el humor en una amistad cruzó un límite y lo tuviste que señalar?", 2),
        ("¿Cuánto de tu identidad cambió gracias a las amistades que elegiste?", 2),
        ("¿Cuándo fue la última vez que pusiste un límite en una amistad y la amistad sobrevivió?", 2),
        ("¿Cuánto de tu autocuidado estás dispuesto a sacrificar por mantener una amistad?", 2),
        ("¿Cuándo fue la última vez que sentiste vergüenza dentro de una amistad y lo nombraste?", 2),
        ("¿Cuánto de la comunidad que tenés es la que elegiste y cuánto es la que simplemente acumulaste?", 2),
        ("¿Cuándo fue la última vez que la nostalgia de una amistad que se fue te hizo valorar más las que tenés?", 2),
        ("¿Cuándo fue la última vez que la gratitud por un amigo fue tan grande que no supiste cómo expresarla?", 2),
        ("¿Cuándo fue la última vez que ser generoso con un amigo requirió que antes lo fueras con vos mismo?", 2),
        ("¿Cuándo fue la última vez que el arrepentimiento de cómo trataste a un amigo te hizo cambiar algo tuyo?", 2),
        ("¿Cuándo fue la última vez que te arrepentiste de cómo trataste a un amigo y lo reconociste en voz alta?", 3),
        ("¿Cuándo fue la última vez que tu identidad entró en conflicto con lo que tu grupo de amigos esperaba de vos?", 3),
        ("¿Cuándo fue la última vez que elegiste tu bienestar sobre mantener una amistad que ya no te hacía bien?", 3),
        ("¿Cuándo fue la última vez que la gratitud por una amistad fue también gratitud por quien te hizo ser?", 3),
        ("¿Cuándo fue la última vez que la vergüenza de algo que hiciste con un amigo te hizo cambiar algo de fondo?", 3),
        ("¿Cuándo fue la última vez que la nostalgia de una amistad perdida te enseñó algo sobre cómo cuidar las que tenés?", 3),
        ("¿Cuándo fue la última vez que la comunidad de amigos fue el espejo más honesto que tuviste?", 3),
        ("¿Cuándo fue la última vez que la generosidad de un amigo te hizo querer ser mejor persona?", 3),
        ("¿Cuándo fue la última vez que los límites en una amistad definieron quién sos más que cualquier cosa que hayas logrado?", 3),
        ("¿Cuándo fue la última vez que el autocuidado en una amistad fue también el acto más generoso que pudiste hacer?", 3),
        ("¿Cuándo fue la última vez que la identidad que construiste con tus amigos entró en conflicto con quien querés ser?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento de no haber estado para un amigo en el momento justo cambió cómo priorizás?", 3),
        ("¿Cuándo fue la última vez que el humor fue la manera más honesta de decirle a un amigo algo que no podías decir de otra forma?", 3),
        ("¿Cuándo fue la última vez que la comunidad que elegiste te exigió más de lo que esperabas de vos mismo?", 3),
        ("¿Cuándo fue la última vez que pusiste un límite en una amistad que te hizo ganar respeto propio aunque perdiste algo de la relación?", 3),
        ("¿Cuándo fue la última vez que la gratitud por una amistad llegó tarde y te costó expresarla aunque era real?", 3),
        ("¿Cuándo fue la última vez que cuidarte dentro de una amistad fue también lo que salvó la amistad?", 3),
        ("¿Cuándo fue la última vez que la generosidad en una amistad fue la que más te costó porque no estabas en tu mejor momento?", 3),
        ("¿Cuándo fue la última vez que el humor con un amigo fue el lenguaje en el que se dijeron todo lo que no podían decir de frente?", 3),
        ("¿Cuándo fue la última vez que la vergüenza compartida con un amigo fue el comienzo de una confianza que no existía antes?", 3),
    ],

    "exs": [
        ("¿Hay algo de una relación pasada por lo que hoy le tenés gratitud genuina?", 1),
        ("¿Cuál es la nostalgia más pura que tenés de alguna relación que terminó?", 1),
        ("¿Cuándo fue la situación más vergonzosa que viviste en o después de una ruptura?", 1),
        ("¿Cuándo fue la última vez que recordaste algo gracioso de una relación pasada y te reíste solo?", 1),
        ("¿Cuándo fue la última vez que hiciste algo generoso por una ex pareja?", 1),
        ("¿Cuándo fue la primera vez que pusiste un límite claro en cómo querías ser tratado en una relación?", 1),
        ("¿Cuándo fue la primera vez que te cuidaste a vos mismo después de una ruptura?", 1),
        ("¿Hay algo de cómo terminó una relación de lo que te arrepentís?", 1),
        ("¿Cuándo fue la última vez que la nostalgia de una relación pasada te llegó en el peor momento?", 1),
        ("¿Cuándo fue la última vez que te reíste de algo que en su momento fue muy doloroso en el amor?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que podías ser generoso con alguien que te había lastimado?", 1),
        ("¿Cuándo fue la primera vez que la identidad que construiste en una relación te sobrevivió?", 1),
        ("¿Cuándo fue la primera vez que la vergüenza de cómo terminaste algo te hizo crecer?", 1),
        ("¿Cuándo fue la primera vez que cuidarte después de una ruptura fue también cuidar lo que vendría?", 1),
        ("¿Cuándo fue la última vez que la gratitud por algo que viviste en pareja llegó mucho después de que terminó?", 1),
        ("¿Cuándo fue la primera vez que el humor fue la única manera de procesar una ruptura?", 1),
        ("¿Cuándo fue la primera vez que pusiste un límite en una relación y no lo levantaste aunque te lo pidieran?", 1),
        ("¿Cuándo fue la primera vez que la comunidad de gente que te rodeaba después de una ruptura fue lo que te sostuvo?", 1),
        ("¿Cuándo fue la primera vez que la nostalgia de una relación fue más honesta que cualquier cosa que dijiste sobre ella?", 1),
        ("¿Cuándo fue la primera vez que el arrepentimiento de algo en el amor fue el punto de partida de algo mejor?", 1),
        ("¿Cuánto de tu identidad definiste en oposición a alguien que amaste?", 2),
        ("¿Cuándo fue la última vez que pusiste un límite en cómo hablás de tus ex?", 2),
        ("¿Cuánto de la gratitud que tenés por relaciones pasadas tardaste años en poder sentir?", 2),
        ("¿Cuándo fue la última vez que el arrepentimiento en el amor te hizo cambiar algo de vos mismo?", 2),
        ("¿Cuándo fue la última vez que la vergüenza de cómo actuaste en una relación te llevó a ser diferente?", 2),
        ("¿Cuándo fue la última vez que elegiste protegerte emocionalmente antes de intentar revivir algo?", 2),
        ("¿Cuándo fue la última vez que la nostalgia de una relación pasada fue también nostalgia de quién eras entonces?", 2),
        ("¿Cuándo fue la última vez que el humor fue la primera señal de que habías sanado algo?", 2),
        ("¿Cuándo fue la última vez que la comunidad que tenías después de una ruptura te mostró quiénes eran tus verdaderos afectos?", 2),
        ("¿Cuándo fue la última vez que ser generoso con un ex fue también un acto de generosidad con vos mismo?", 2),
        ("¿Cuándo fue la última vez que la identidad que dejaste en una relación pasada fue también la que menos te servía?", 2),
        ("¿Cuándo fue la última vez que pusiste un límite con alguien del pasado que te liberó de seguir cargando algo que no era tuyo?", 2),
        ("¿Cuándo fue la última vez que el autocuidado después de una ruptura fue también la manera de aprender qué necesitabas?", 2),
        ("¿Cuál es la gratitud más difícil que tuviste que construir hacia alguien que te lastimó profundamente?", 3),
        ("¿Cuándo fue la última vez que te arrepentiste de algo en el amor que todavía no lograste perdonarte?", 3),
        ("¿Cuándo fue la última vez que elegiste tu bienestar sobre revivir algo del pasado?", 3),
        ("¿Cuándo fue la última vez que la vergüenza de cómo te comportaste en el amor fue también el catalizador del cambio más profundo?", 3),
        ("¿Cuándo fue la última vez que la nostalgia de una relación fue más útil que honesta?", 3),
        ("¿Cuándo fue la última vez que el humor fue la manera más honesta de admitir que algo del pasado todavía duele?", 3),
        ("¿Cuándo fue la última vez que la comunidad que construiste después de una ruptura fue mejor que la que tenías antes?", 3),
        ("¿Cuándo fue la última vez que ser generoso con alguien del pasado fue posible porque primero te cuidaste?", 3),
        ("¿Cuándo fue la última vez que la identidad que dejaste en una relación fue también la que te impidió ser quien querías?", 3),
        ("¿Cuándo fue la última vez que el límite que pusiste con alguien del pasado fue también el límite que te abrió al futuro?", 3),
        ("¿Cuándo fue la última vez que el autocuidado después de una ruptura fue el acto más valiente y solitario que hiciste?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento en el amor fue la brújula más honesta que tuviste?", 3),
        ("¿Cuándo fue la última vez que la gratitud por algo doloroso en el amor llegó tan tarde que ya no podías compartirla con quien debías?", 3),
        ("¿Cuándo fue la última vez que la vergüenza de cómo terminaste algo fue el último obstáculo para cerrar esa historia?", 3),
        ("¿Cuándo fue la última vez que la nostalgia de una relación pasada te enseñó algo que ninguna terapia pudo?", 3),
        ("¿Cuándo fue la última vez que el humor frente a una historia pasada fue también el perdón que no podías decir de otra forma?", 3),
        ("¿Cuándo fue la última vez que el límite más importante que pusiste en el amor fue el que te costó más defender?", 3),
    ],

    "personalidad": [
        ("¿Por qué parte de quién sos estás más agradecido hoy?", 1),
        ("¿Cuándo fue la última vez que sentiste nostalgia de una versión anterior de vos mismo?", 1),
        ("¿Cuándo fue la última vez que te reíste de vos mismo con genuina ternura?", 1),
        ("¿Cuándo fue la última vez que sentiste vergüenza de algo tuyo y lo nombraste igual?", 1),
        ("¿A qué comunidades sentís que genuinamente pertenecés?", 1),
        ("¿Cuándo fue la última vez que fuiste generoso con alguien que no te lo esperaba?", 1),
        ("¿Cuándo fue la última vez que pusiste un límite que definió quién sos?", 1),
        ("¿Cuándo fue la última vez que te cuidaste de una manera que antes no habrías permitido?", 1),
        ("¿Cuál es la parte de tu identidad de la que más te arrepentís?", 1),
        ("¿Cuándo fue la última vez que la nostalgia de quién eras te dio información útil sobre quién querés ser?", 1),
        ("¿Cuándo fue la última vez que tu humor te reveló algo sobre vos mismo?", 1),
        ("¿Cuándo fue la última vez que alguien fue generoso con vos de una manera que te cambió?", 1),
        ("¿Cuándo fue la última vez que le agradeciste a alguien por lo que te hizo crecer aunque duela?", 1),
        ("¿Cuándo fue la última vez que la vergüenza de algo tuyo te llevó a cambiarlo?", 1),
        ("¿Cuándo fue la última vez que la nostalgia de quién fuiste te hizo ver con más claridad quién sos?", 1),
        ("¿Cuándo fue la última vez que la comunidad en la que estás reflejó algo de vos que vos mismo no veías?", 1),
        ("¿Cuándo fue la última vez que la generosidad que tenés con otros la usaste también con vos mismo?", 1),
        ("¿Cuándo fue la última vez que un límite que pusiste definió mejor quién sos que cualquier logro?", 1),
        ("¿Cuándo fue la última vez que cuidarte fue el acto más honesto que pudiste hacer?", 1),
        ("¿Cuándo fue la última vez que el arrepentimiento por algo tuyo fue también la semilla de algo mejor?", 1),
        ("¿Cuándo fue la última vez que el humor fue un escudo para no mostrar algo real?", 2),
        ("¿Cuánto de tu identidad actual construiste conscientemente y cuánto te pasó sin darte cuenta?", 2),
        ("¿Cuándo fue la última vez que pusiste un límite y sentiste que te traicionabas vs. que te cuidabas?", 2),
        ("¿Cuánto de la comunidad en la que vivís y trabajás refleja quién sos realmente?", 2),
        ("¿Cuándo fue la última vez que el arrepentimiento cambió algo profundo en vos?", 2),
        ("¿Cuándo fue la última vez que elegiste cuidarte aunque otros lo leyeron como abandono?", 2),
        ("¿Cuándo fue la última vez que la gratitud por quien sos te llegó de afuera antes de que la pudieras sentir desde adentro?", 2),
        ("¿Cuándo fue la última vez que la vergüenza de algo tuyo fue también una señal de que algo importaba?", 2),
        ("¿Cuándo fue la última vez que la nostalgia de una versión anterior de vos mismo fue un recurso y no una trampa?", 2),
        ("¿Cuándo fue la última vez que la generosidad con vos mismo fue tan difícil como la que tenés con otros?", 2),
        ("¿Cuándo fue la última vez que fuiste completamente honesto sobre quién sos con alguien que podría no aceptarlo?", 3),
        ("¿Cuál es la vergüenza más vieja que cargás sobre vos mismo y que todavía no pudiste soltar?", 3),
        ("¿Cuándo fue la última vez que tu identidad entró en crisis y saliste más auténtico?", 3),
        ("¿Cuánto de los límites que tenés te protegen y cuánto te aíslan de cosas que realmente querés?", 3),
        ("¿Cuándo fue la última vez que el autocuidado requirió que decepcionaras a alguien que querías?", 3),
        ("¿Cuándo fue la última vez que te perdonaste algo que creías imperdonable?", 3),
        ("¿Cuánto de quién sos es una armadura y cuánto es realmente vos?", 3),
        ("¿Cuándo fue la última vez que elegiste pertenecer a algo aunque implicara cambiar parte de vos mismo?", 3),
        ("¿Cuál es el arrepentimiento que más información te da sobre quién querés ser de acá en adelante?", 3),
        ("¿Cuándo fue la última vez que tu mayor acto de generosidad fue contigo mismo?", 3),
        ("¿Cuándo fue la última vez que la gratitud por quien sos coexistió con el arrepentimiento de quien fuiste?", 3),
        ("¿Cuándo fue la última vez que el humor fue la manera más honesta de mostrar quién sos sin exponerte demasiado?", 3),
        ("¿Cuándo fue la última vez que la nostalgia de quién eras te hizo elegir diferente?", 3),
        ("¿Cuándo fue la última vez que pertenecer a algo requirió que fueras honesto sobre quién no sos?", 3),
        ("¿Cuándo fue la última vez que la vergüenza fue la puerta de entrada a un cambio que no hubieras hecho de otra manera?", 3),
        ("¿Cuándo fue la última vez que la comunidad que elegiste te hizo más vos mismo en lugar de diluirte?", 3),
        ("¿Cuándo fue la última vez que la generosidad con vos mismo fue también la que más te costó defender frente a otros?", 3),
        ("¿Cuándo fue la última vez que poner un límite fue la manera más fiel de ser vos mismo?", 3),
        ("¿Cuándo fue la última vez que cuidarte fue el acto más difícil y al mismo tiempo el más necesario?", 3),
        ("¿Cuándo fue la última vez que la gratitud por lo que pasaste fue mayor que cualquier amargura por cómo pasó?", 3),
    ],

    "miedos": [
        ("¿Le tenés miedo a no tener nada de lo que ser agradecido algún día?", 1),
        ("¿Cuándo fue la última vez que el miedo a arrepentirte te paralizó?", 1),
        ("¿Le tenés miedo a perder partes de tu identidad que hoy considerás esenciales?", 1),
        ("¿Le tenés miedo a que te tomen el pelo o a hacer el ridículo?", 1),
        ("¿Cuándo fue la última vez que el miedo a la vergüenza te impidió hacer algo?", 1),
        ("¿Le tenés miedo a quedarte sin comunidad o sentirte completamente solo?", 1),
        ("¿Le tenés miedo a ser visto como alguien egoísta si priorizás tus propias necesidades?", 1),
        ("¿Cuándo fue la última vez que el miedo a lastimar a alguien te llevó a descuidarte?", 1),
        ("¿Le tenés miedo a que la nostalgia te impida disfrutar el presente?", 1),
        ("¿Le tenés miedo a ser demasiado generoso y que te usen?", 1),
        ("¿Le tenés miedo a que alguien te conozca de verdad y no le gustes?", 1),
        ("¿Le tenés miedo a no pertenecer a ningún lugar que te importe?", 1),
        ("¿Le tenés miedo a los límites que los otros te ponen?", 1),
        ("¿Le tenés miedo a que el autocuidado te vuelva egoísta?", 1),
        ("¿Le tenés miedo al arrepentimiento por cosas que todavía no hiciste?", 1),
        ("¿Le tenés miedo al humor de los demás cuando es a tu costa?", 1),
        ("¿Le tenés miedo a perder la identidad que te costó construir?", 1),
        ("¿Le tenés miedo a que la gratitud que sentís por tu vida actual dure poco?", 1),
        ("¿Le tenés miedo a la nostalgia de un tiempo que en realidad no era tan bueno como lo recordás?", 1),
        ("¿Le tenés miedo a poner límites y que los demás te abandonen?", 1),
        ("¿Cuándo fue la última vez que el miedo a la vergüenza fue más fuerte que el deseo de ser honesto?", 2),
        ("¿Cuándo fue la última vez que el miedo a perder tu comunidad te hizo comportarte diferente?", 2),
        ("¿Cuánto del miedo a la vergüenza viene de creencias que internalizaste de otros?", 2),
        ("¿Cuándo fue la última vez que el miedo al arrepentimiento te hizo tomar una decisión que no querías tomar?", 2),
        ("¿Cuánto miedo te genera la idea de cambiar partes de tu identidad que ya no te sirven?", 2),
        ("¿Cuándo fue la última vez que el miedo a no tener límites claros te hizo daño?", 2),
        ("¿Cuánto del miedo que tenés al autocuidado viene de creer que no merecés esa atención?", 2),
        ("¿Cuándo fue la última vez que el miedo a arrepentirte en el futuro te impidió vivir el presente?", 2),
        ("¿Cuándo fue la última vez que el miedo a perder tu identidad te hizo aferrarte a algo que te hacía daño?", 2),
        ("¿Cuándo fue la última vez que el miedo a la nostalgia fue en realidad miedo al cambio?", 2),
        ("¿Cuándo fue la última vez que el miedo a no pertenecer te hizo ser alguien que no sos?", 2),
        ("¿Cuándo fue la última vez que el miedo a ser generoso vino del miedo a que te vean como débil?", 2),
        ("¿Cuándo fue la última vez que el miedo al humor de los otros te hizo callarte algo importante?", 2),
        ("¿Cuál es el miedo más profundo que tenés sobre quién sos en realidad?", 3),
        ("¿Cuándo fue la última vez que el miedo a la vergüenza te hizo ser menos de lo que podías ser?", 3),
        ("¿Cuál es el miedo a los límites que más te cuesta reconocer?", 3),
        ("¿Cuándo fue la última vez que el miedo a perder tu identidad te impidió crecer?", 3),
        ("¿Cuándo fue la última vez que el miedo a no pertenecer a ningún lugar fue más paralizante que cualquier otro?", 3),
        ("¿Cuándo fue la última vez que el miedo al arrepentimiento fue más destructivo que el arrepentimiento mismo?", 3),
        ("¿Cuándo fue la última vez que el miedo a cuidarte fue en realidad miedo a lo que encontrarías si te detuvieras?", 3),
        ("¿Cuándo fue la última vez que el miedo a la gratitud fue miedo a reconocer que necesitabas a alguien?", 3),
        ("¿Cuándo fue la última vez que el miedo al humor ajeno fue el miedo más profundo a ser visto?", 3),
        ("¿Cuándo fue la última vez que el miedo a la nostalgia te impidió honrar lo que fue?", 3),
        ("¿Cuándo fue la última vez que el miedo a la generosidad fue miedo a la vulnerabilidad?", 3),
        ("¿Cuándo fue la última vez que el miedo al límite que necesitabas poner fue más poderoso que el dolor de no ponerlo?", 3),
        ("¿Cuándo fue la última vez que el miedo a tu propia identidad fue lo que más te frenó?", 3),
        ("¿Cuándo fue la última vez que el miedo a la vergüenza fue la razón por la que no pediste perdón?", 3),
        ("¿Cuándo fue la última vez que el miedo al autocuidado fue miedo a reconocer que estabas sufriendo?", 3),
        ("¿Cuándo fue la última vez que el miedo a perder una comunidad fue mayor que el dolor de seguir en ella?", 3),
        ("¿Cuándo fue la última vez que el miedo más profundo que tenías estaba disfrazado de algo completamente diferente?", 3),
    ],

    "logros": [
        ("¿Cuándo fue la última vez que agradeciste un logro en lugar de simplemente ir por el siguiente?", 1),
        ("¿Hay algún logro del que te arrepentís aunque fue exitoso?", 1),
        ("¿Cuándo fue la última vez que un logro tuyo fortaleció la comunidad en la que vivís?", 1),
        ("¿Cuándo fue la última vez que lograste algo y se lo dedicaste genuinamente a alguien?", 1),
        ("¿Cuál es el logro que más define quién sos hoy?", 1),
        ("¿Cuándo fue la última vez que lograste algo siendo muy generoso con otros en el proceso?", 1),
        ("¿Cuándo fue la última vez que poner un límite fue un logro en sí mismo?", 1),
        ("¿Cuándo fue la última vez que cuidarte bien fue tu mayor logro de la semana?", 1),
        ("¿Cuándo fue la última vez que un logro te hizo reír de lo lejos que habías llegado?", 1),
        ("¿Cuándo fue la última vez que la nostalgia de un logro pasado te motivó en lugar de entristecerte?", 1),
        ("¿Hay algún logro del que te daba vergüenza hablar y que ahora podés nombrar?", 1),
        ("¿Cuándo fue la última vez que lograste algo que benefició a tu comunidad más que a vos?", 1),
        ("¿Cuándo fue la última vez que un logro tuyo fue posible porque alguien fue generoso con vos?", 1),
        ("¿Cuándo fue la última vez que el humor fue parte de cómo celebraste un logro?", 1),
        ("¿Cuándo fue la última vez que agradeciste un logro porque entendiste cuánto costó?", 1),
        ("¿Cuándo fue la última vez que lograste algo que antes te daba vergüenza querer?", 1),
        ("¿Cuándo fue la última vez que la identidad que construiste te habilitó un logro que antes era imposible?", 1),
        ("¿Cuándo fue la última vez que cuidarte fue el catalizador de un logro que no hubieras podido alcanzar de otra manera?", 1),
        ("¿Cuándo fue la última vez que un logro te hizo extrañar algo de quien eras antes de lograrlo?", 1),
        ("¿Cuándo fue la última vez que lograste algo que te dio vergüenza celebrar aunque lo merecías?", 1),
        ("¿Cuándo fue la última vez que el arrepentimiento de un logro que no perseguiste fue más útil que el orgullo de uno que sí?", 2),
        ("¿Cuánto de tus logros son expresiones de tu identidad real y cuántos son máscaras?", 2),
        ("¿Cuándo fue la última vez que un logro tuyo vino de cruzar un límite propio que creías inamovible?", 2),
        ("¿Cuándo fue la última vez que lograste algo y lo primero que sentiste fue gratitud en lugar de alivio?", 2),
        ("¿Cuánto de tus logros los lograste a costa de tu propio bienestar?", 2),
        ("¿Cuándo fue la última vez que generosidad genuina fue parte central de un logro tuyo?", 2),
        ("¿Cuándo fue la última vez que la comunidad que tenías fue el logro más importante que podías tener?", 2),
        ("¿Cuándo fue la última vez que un límite que pusiste fue también el logro más silencioso del año?", 2),
        ("¿Cuándo fue la última vez que el humor fue la manera en que procesaste un logro que te costó demasiado?", 2),
        ("¿Cuándo fue la última vez que la nostalgia de un logro pasado te mostró cuánto cambiaste?", 2),
        ("¿Cuándo fue la última vez que un logro te reveló algo de tu identidad que no querías ver?", 3),
        ("¿Cuál es el logro que más te costó celebrar porque implicaba dejar atrás algo que amabas?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento de un camino no tomado fue más honesto que la satisfacción del que sí tomaste?", 3),
        ("¿Cuándo fue la última vez que el logro más importante fue el que no viste venir porque no lo estabas buscando?", 3),
        ("¿Cuándo fue la última vez que la gratitud por un logro llegó tan tarde que casi no podías sentirla?", 3),
        ("¿Cuándo fue la última vez que la vergüenza de no haber logrado algo fue el motor de un cambio profundo?", 3),
        ("¿Cuándo fue la última vez que la nostalgia de un logro pasado te confrontó con cuánto dejaste de perseguir?", 3),
        ("¿Cuándo fue la última vez que la comunidad que construiste fue en sí mismo el logro más difícil de sostener?", 3),
        ("¿Cuándo fue la última vez que ser generoso en el proceso de un logro fue más valioso que el logro mismo?", 3),
        ("¿Cuándo fue la última vez que el límite que pusiste fue también el punto de partida de tu logro más importante?", 3),
        ("¿Cuándo fue la última vez que cuidarte fue el logro más difícil de defender frente a otros?", 3),
        ("¿Cuándo fue la última vez que la identidad que construiste a través de tus logros entró en colisión con quién sos realmente?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento de algo que lograste fue también la señal de que habías crecido?", 3),
        ("¿Cuándo fue la última vez que el humor en torno a un fracaso fue también el primer paso del siguiente logro?", 3),
        ("¿Cuándo fue la última vez que la gratitud por un logro fue posible porque alguien antes fue generoso con vos?", 3),
        ("¿Cuándo fue la última vez que lograste algo que te costó tanto que tardaste en poder sentirte orgulloso?", 3),
        ("¿Cuándo fue la última vez que la vergüenza de un logro no celebrado fue más pesada que el logro mismo?", 3),
        ("¿Cuándo fue la última vez que poner un límite fue el logro que más te definió?", 3),
        ("¿Cuándo fue la última vez que cuidarte fue el primer logro después del peor momento de tu vida?", 3),
        ("¿Cuándo fue la última vez que la comunidad que elegiste fue el logro más importante aunque nadie lo vea así?", 3),
    ],

    "sinFiltro": [
        ("¿Cuántas veces al mes le agradecés algo a alguien en tu cabeza pero nunca se lo decís?", 1),
        ("¿Cuándo fue la última vez que la nostalgia te hizo hacer algo cringe?", 1),
        ("¿Cuándo fue la situación más vergonzosa que viviste en público y que todavía te da calor la cara?", 1),
        ("¿Cuándo fue la última vez que te reíste de algo que era demasiado oscuro como para admitirlo?", 1),
        ("¿Cuántas veces por semana hacés algo que se supone que es autocuidado pero es solo procrastinar con estilo?", 1),
        ("¿Cuándo fue la última vez que pusiste un límite pero lo explicaste tanto que se convirtió en una disculpa?", 1),
        ("¿Cuánto de tu generosidad es generosidad real y cuánto es querer que te quieran?", 1),
        ("¿Cuándo fue la última vez que el arrepentimiento te agarró en la ducha a las 2 AM?", 1),
        ("¿Cuántas comunidades o grupos te quedaste mucho tiempo más de lo que debías?", 1),
        ("¿Cuándo fue la última vez que hiciste algo por nostalgia que fue un error obvio de principio a fin?", 1),
        ("¿Cuándo fue la última vez que te reíste en una situación completamente inapropiada?", 1),
        ("¿Cuántas veces al mes te cuidás de maneras que nadie sabría que son cuidado?", 1),
        ("¿Cuántas veces en la última semana agradeciste algo mentalmente sin decirlo?", 1),
        ("¿Cuántas veces pusiste un límite que en realidad era un ultimátum disfrazado?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que pertenecés a un grupo más por inercia que por elección?", 1),
        ("¿Cuándo fue la última vez que la generosidad fue tu estrategia para que alguien no te pudiera rechazar?", 1),
        ("¿Cuándo fue la última vez que te reíste de alguien y después te diste cuenta de que eras vos el chiste?", 1),
        ("¿Cuántas veces prometiste que ibas a empezar a cuidarte 'la semana que viene'?", 1),
        ("¿Cuándo fue la última vez que la nostalgia te hizo idealizar algo que en realidad no era tan bueno?", 1),
        ("¿Cuándo fue la última vez que te arrepentiste de algo pero no lo dijiste porque te daba vergüenza arrepentirte?", 1),
        ("¿Cuándo fue la última vez que usaste el humor para esquivar una conversación que necesitabas tener?", 2),
        ("¿Cuándo fue la última vez que tu autocuidado le generó culpa a alguien más y lo disfrutaste?", 2),
        ("¿Alguna vez pusiste un límite que era más para castigar que para protegerte?", 2),
        ("¿Cuándo fue la última vez que fuiste 'generoso' esperando algo a cambio aunque decías que no?", 2),
        ("¿Cuándo fue la última vez que la vergüenza te hizo actuar peor de lo que hubiera sido simplemente reconocerla?", 2),
        ("¿Cuándo fue la última vez que te quedaste en una comunidad o grupo por inercia sabiendo que te hacía daño?", 2),
        ("¿Cuándo fue la última vez que la nostalgia fue la excusa perfecta para no tomar una decisión que necesitabas tomar?", 2),
        ("¿Cuándo fue la última vez que agradeciste algo solo para cerrar una conversación incómoda?", 2),
        ("¿Cuándo fue la última vez que el arrepentimiento fue tan incómodo que lo convertiste en humor?", 2),
        ("¿Cuándo fue la última vez que tu identidad fue tan rígida que te impidió ser generoso con alguien diferente?", 2),
        ("¿Cuándo fue la última vez que algo te generó un arrepentimiento tan profundo que cambiaste algo importante?", 3),
        ("¿Cuándo fue la última vez que hiciste algo escandaloso con genuina gratitud de haberlo hecho?", 3),
        ("¿Cuándo fue la última vez que tu límite más importante fue ignorado por alguien y no hiciste nada?", 3),
        ("¿Cuál es la cosa más vergonzosa de tu identidad que nadie sabe y que en el fondo no querés cambiar?", 3),
        ("¿Cuándo fue la última vez que la generosidad que mostraste fue en realidad miedo a que te vieran como egoísta?", 3),
        ("¿Cuándo fue la última vez que la nostalgia te hizo volver a algo que ya sabías que no tenía futuro?", 3),
        ("¿Cuándo fue la última vez que agradeciste algo que en realidad todavía te duele?", 3),
        ("¿Cuándo fue la última vez que el autocuidado que practicaste fue en realidad huir de algo que tenías que enfrentar?", 3),
        ("¿Cuándo fue la última vez que te reíste de algo que te avergüenza que te haga reír?", 3),
        ("¿Cuándo fue la última vez que perteneciste a algo que sabías que no te representaba pero era mejor que estar solo?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento más profundo que sentiste fue por algo que hiciste exactamente como querías?", 3),
        ("¿Cuándo fue la última vez que la identidad que proyectás fue tan distinta de la que sentís que te dio vergüenza hasta a vos?", 3),
        ("¿Cuándo fue la última vez que la gratitud fue la última cosa que sentiste aunque era la más adecuada?", 3),
        ("¿Cuándo fue la última vez que pusiste un límite sabiendo que estabas equivocado pero no podías dar marcha atrás?", 3),
        ("¿Cuándo fue la última vez que cuidarte fue la cosa más egoísta que hiciste y lo mejor que podías hacer?", 3),
        ("¿Cuándo fue la última vez que el humor fue la manera en que evitaste asumir algo que te daba vergüenza asumir?", 3),
        ("¿Cuándo fue la última vez que la generosidad fue lo que más te costó y lo que más te definió?", 3),
        ("¿Cuándo fue la última vez que la nostalgia fue más real que el presente que estabas viviendo?", 3),
        ("¿Cuándo fue la última vez que el arrepentimiento fue tan tuyo que no necesitabas que nadie más lo supiera?", 3),
        ("¿Cuándo fue la última vez que la vergüenza de quien sos fue la única cosa que no pudiste convertir en chiste?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS8:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS8[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
