#!/usr/bin/env python3
"""Batch 14 - society, politics (light), justice, community, environment, technology."""
import json

ADDITIONS14 = {
    "infancia": [
        ("¿Cuándo fue la primera vez que entendiste que había personas que tenían mucho menos que vos?", 1),
        ("¿Cuándo fue la primera vez que viste algo injusto en la escuela y dijiste algo?", 1),
        ("¿Cuándo fue la primera vez que escuchaste a tus padres hablar de política o de lo que pasaba en el país?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que el mundo era más grande que tu barrio?", 1),
        ("¿Cuándo fue la primera vez que usaste internet y qué fue lo primero que buscaste?", 1),
        ("¿Cuándo fue la primera vez que viste que algo en la naturaleza había cambiado o desaparecido?", 1),
        ("¿Cuándo fue la primera vez que fuiste parte de algo más grande que vos —un grupo, un equipo, una comunidad?", 1),
        ("¿Cuándo fue la primera vez que defendiste a alguien que estaba siendo tratado injustamente?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que las reglas no siempre son justas?", 1),
        ("¿Cuándo fue la primera vez que viste las noticias y algo de lo que pasaba en el mundo te afectó de verdad?", 1),
        ("¿Cuándo fue la primera vez que entendiste que la gente puede tener opiniones muy diferentes a las de tu familia?", 1),
        ("¿Cuándo fue la primera vez que te importó el medioambiente?", 1),
        ("¿Cuándo fue la primera vez que tuviste acceso a tecnología y cambió algo en tu vida cotidiana?", 1),
        ("¿Cuándo fue la primera vez que viste a alguien de tu comunidad ayudando a otros sin pedir nada a cambio?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que hay personas que hacen las cosas diferente a como las hacen en tu casa y no están equivocadas?", 1),
        ("¿Cuándo fue la primera vez que participaste en algo comunitario —colecta, evento del barrio, actividad grupal?", 1),
        ("¿Cuándo fue la primera vez que una tecnología te hizo sentir que el mundo era más pequeño?", 1),
        ("¿Cuándo fue la primera vez que viste a adultos discutir sobre política y cómo te afectó?", 1),
        ("¿Cuándo fue la primera vez que te preguntaste si algo que parecía normal era en realidad injusto?", 1),
        ("¿Cuándo fue la primera vez que cuidaste algo de la naturaleza —una planta, un animal— y lo sentiste como responsabilidad?", 1),
        ("¿Cuándo fue la primera vez que el barrio o la comunidad donde creciste te dio algo que no esperabas?", 1),
        ("¿Cuándo fue la primera vez que viste que la tecnología podía hacer algo imposible posible?", 1),
        ("¿Cuándo fue la primera vez que te pusiste del lado de alguien diferente a vos en algo que importaba?", 1),
        ("¿Cuándo fue la primera vez que te preguntaste si lo que estabas haciendo le hacía bien o mal al mundo?", 1),
        ("¿Cuándo fue la primera vez que la injusticia —en el mundo, en tu entorno— te generó algo más que incomodidad?", 2),
        ("¿Cuándo fue la primera vez que la diferencia social —de clase, de barrio, de oportunidad— fue algo que sentiste en carne propia?", 2),
        ("¿Cuándo fue la primera vez que la tecnología te hizo sentir conectado a algo que antes era imposible?", 2),
        ("¿Cuándo fue la primera vez que el medioambiente fue algo que te generó preocupación real?", 2),
        ("¿Cuándo fue la primera vez que entendiste que la comunidad podía ser tanto un sostén como una presión?", 2),
        ("¿Cuándo fue la primera vez que la política —aunque sea de manera indirecta— afectó algo en tu vida de manera concreta?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que la justicia y la ley no siempre son lo mismo?", 2),
        ("¿Cuándo fue la primera vez que sentiste que pertenecías a algo más grande que tu familia?", 2),
        ("¿Cuándo fue la primera vez que el mundo de los adultos —con su política, su economía, sus conflictos— te pareció algo que también era tuyo?", 2),
        ("¿Cuándo fue la primera vez que algo de lo que pasaba en la sociedad te hizo querer cambiar algo?", 2),
        ("¿Cuándo fue la primera vez que la injusticia del mundo te tocó de una manera que todavía sentís hoy?", 3),
        ("¿Cuándo fue la primera vez que te diste cuenta de que el lugar donde naciste —el barrio, la ciudad, el país— moldeó algo fundamental de quién sos?", 3),
        ("¿Cuándo fue la primera vez que sentiste que el mundo podía ser diferente y que vos tenías algo que ver con eso?", 3),
        ("¿Cuándo fue la primera vez que la comunidad —el barrio, la escuela, el grupo— te dio algo que no podías encontrar solo?", 3),
        ("¿Cuándo fue la primera vez que te diste cuenta de que lo que pasa en el mundo también te pasa a vos?", 3),
        ("¿Cuándo fue la primera vez que la naturaleza o el ambiente donde creciste te formaron de una manera que todavía reconocés?", 3),
    ],

    "futuro": [
        ("¿Cuándo fue la última vez que te imaginaste cómo va a ser el mundo en 30 años?", 1),
        ("¿Cuándo fue la última vez que pensaste en qué papel querés jugar en la sociedad?", 1),
        ("¿Cuándo fue la última vez que te imaginaste usando una tecnología que todavía no existe?", 1),
        ("¿Cuándo fue la última vez que te imaginaste viviendo en un mundo más justo y pensaste en cómo llegar ahí?", 1),
        ("¿Cuándo fue la última vez que pensaste en qué le querés dejar al planeta?", 1),
        ("¿Cuándo fue la última vez que te imaginaste contribuyendo a tu comunidad de una manera significativa?", 1),
        ("¿Cuándo fue la última vez que te imaginaste cómo va a cambiar la tecnología tu trabajo o tu vida cotidiana?", 1),
        ("¿Cuándo fue la última vez que pensaste en qué sociedad querés que habiten quienes vengan después de vos?", 1),
        ("¿Cuándo fue la última vez que te imaginaste siendo parte de un cambio colectivo?", 1),
        ("¿Cuándo fue la última vez que pensaste en el impacto ambiental de tus decisiones cotidianas?", 1),
        ("¿Cuándo fue la última vez que te imaginaste viviendo en un lugar más conectado con la naturaleza en el futuro?", 1),
        ("¿Cuándo fue la última vez que pensaste en qué tipo de comunidad querés construir?", 1),
        ("¿Cuándo fue la última vez que te imaginaste en una sociedad donde la justicia funcionara de manera diferente?", 1),
        ("¿Cuándo fue la última vez que la tecnología te hizo replantearte algo sobre el futuro que querés?", 1),
        ("¿Cuándo fue la última vez que pensaste en el legado colectivo que querés dejar?", 1),
        ("¿Cuándo fue la última vez que te imaginaste con más tiempo para hacer algo que le aportara al mundo?", 1),
        ("¿Cuándo fue la última vez que pensaste en cómo el cambio climático va a cambiar algo en tu vida en los próximos años?", 1),
        ("¿Cuándo fue la última vez que te imaginaste siendo parte de algo más grande que vos mismo en el futuro?", 1),
        ("¿Cuándo fue la última vez que pensaste en cómo querés que sea la comunidad que te rodea?", 1),
        ("¿Cuándo fue la última vez que la tecnología te hizo optimista o pesimista sobre el futuro?", 1),
        ("¿Cuándo fue la última vez que te imaginaste en un mundo donde las cosas que hoy te parecen injustas ya no existen?", 1),
        ("¿Cuándo fue la última vez que pensaste en qué podés hacer vos —concreto y pequeño— para aportar al futuro que querés?", 1),
        ("¿Cuándo fue la última vez que te imaginaste conectando con tu comunidad de una manera que ahora no encontrás?", 1),
        ("¿Cuándo fue la última vez que el futuro del planeta te generó algo más que ansiedad —quizás determinación?", 1),
        ("¿Cuándo fue la última vez que te preguntaste cuánto de lo que querés para el futuro es individual y cuánto es colectivo?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que el mundo que querés construir requiere que vos también cambies?", 2),
        ("¿Cuándo fue la última vez que la tecnología te hizo repensar algo fundamental sobre cómo querés vivir?", 2),
        ("¿Cuándo fue la última vez que el impacto ambiental de tus decisiones te generó una incomodidad que te llevó a actuar?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que el futuro que querés depende de cosas que están fuera de tu control individual?", 2),
        ("¿Cuándo fue la última vez que pensaste en qué significa la justicia para vos y si ese concepto cambió?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la comunidad puede ser tanto un recurso como una responsabilidad?", 2),
        ("¿Cuándo fue la última vez que la situación política te hizo replantearte algo sobre el futuro que querés?", 2),
        ("¿Cuándo fue la última vez que te preguntaste si la tecnología nos acerca o nos aleja del tipo de vida que realmente querés?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que el futuro que querés requiere también que te impliques en algo más allá de tu propia vida?", 2),
        ("¿Cuándo fue la última vez que te preguntaste qué clase de persona querés ser en relación con el mundo, no solo en tu vida privada?", 3),
        ("¿Cuándo fue la última vez que el estado del planeta te afectó de una manera que fue más allá de la preocupación abstracta?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que el futuro que querés para vos no puede existir si el mundo que te rodea no cambia también?", 3),
        ("¿Cuándo fue la última vez que te preguntaste qué estás dispuesto a sacrificar para que el futuro sea mejor —no solo para vos?", 3),
        ("¿Cuándo fue la última vez que la tecnología te hizo ver algo del futuro que te generó tanto esperanza como miedo al mismo tiempo?", 3),
        ("¿Cuándo fue la última vez que pensaste en el legado colectivo que querés dejar y te preguntaste si estás viviendo en coherencia con eso?", 3),
    ],

    "amor": [
        ("¿Cuándo fue la última vez que la diferencia política o de valores sociales fue un tema con alguien que te gustaba?", 1),
        ("¿Cuándo fue la última vez que te atrajo alguien por su compromiso social o su manera de ver el mundo?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue parte de cómo empezaste algo con alguien?", 1),
        ("¿Cuándo fue la última vez que el cuidado del medioambiente fue un valor que compartiste —o no— con alguien?", 1),
        ("¿Cuándo fue la última vez que las diferencias políticas o sociales con alguien fueron más un obstáculo de lo que esperabas?", 1),
        ("¿Cuándo fue la última vez que algo que pasaba en el mundo —noticias, política, crisis— fue el contexto de un momento importante con alguien?", 1),
        ("¿Cuándo fue la última vez que la tecnología mediá una conversación importante en una relación tuya?", 1),
        ("¿Cuándo fue la última vez que compartir valores sobre justicia o sociedad fue parte de lo que te conectó con alguien?", 1),
        ("¿Cuándo fue la última vez que la tecnología —redes, apps, mensajes— complicó algo en una relación tuya?", 1),
        ("¿Cuándo fue la última vez que la diferencia en cómo ven el mundo vos y alguien que amás fue enriquecedora en lugar de conflictiva?", 1),
        ("¿Cuándo fue la última vez que algo de lo que pasa en la sociedad cambió algo en cómo viviste una relación?", 1),
        ("¿Cuándo fue la última vez que la comunidad —amigos, barrio, entorno— influyó en cómo iba una relación tuya?", 1),
        ("¿Cuándo fue la última vez que te importó que alguien con quien estuviste tuviera conciencia ambiental?", 1),
        ("¿Cuándo fue la última vez que la tecnología hizo más fácil o más difícil mantener algo con alguien?", 1),
        ("¿Cuándo fue la última vez que alguien con quien estuviste te abrió los ojos a algo social o político que no veías?", 1),
        ("¿Cuándo fue la última vez que una diferencia de valores sobre la sociedad fue el inicio —o el fin— de algo con alguien?", 1),
        ("¿Cuándo fue la última vez que el mundo exterior —política, crisis, cambios— entró en una relación y la sacudió?", 1),
        ("¿Cuándo fue la última vez que te enamoraste de la forma en que alguien se relaciona con el mundo que lo rodea?", 1),
        ("¿Cuándo fue la última vez que compartir preocupaciones sobre el futuro del planeta fue algo que los unió con alguien?", 1),
        ("¿Cuándo fue la última vez que la forma en que alguien usa la tecnología te dijo algo sobre cómo es?", 1),
        ("¿Cuándo fue la última vez que un evento social o político fue el escenario de un momento importante en una relación?", 1),
        ("¿Cuándo fue la última vez que la brecha generacional —diferente relación con la tecnología, la política, el mundo— fue algo que tuviste que navegar en una relación?", 1),
        ("¿Cuándo fue la última vez que la forma en que alguien veía la sociedad te hizo verlo de una manera completamente diferente?", 1),
        ("¿Cuándo fue la última vez que algo que pasaba en el mundo te hizo querer estar cerca de alguien en particular?", 1),
        ("¿Cuándo fue la última vez que una diferencia fundamental en cómo ven el mundo vos y alguien que amás fue más importante que el amor que se tenían?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue el espacio donde una relación mostró algo que en la realidad no podía?", 2),
        ("¿Cuándo fue la última vez que el compromiso de alguien con el mundo —la comunidad, el planeta, la justicia— te hizo amarlo más o cuestionarlo?", 2),
        ("¿Cuándo fue la última vez que lo que pasaba en la sociedad fue la razón de un conflicto dentro de una relación tuya?", 2),
        ("¿Cuándo fue la última vez que amar a alguien te hizo ver el mundo de una manera diferente?", 2),
        ("¿Cuándo fue la última vez que la diferencia política fue algo que los dos eligieron sostener porque la relación valía más?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue la razón por la que una relación sobrevivió o no sobrevivió?", 2),
        ("¿Cuándo fue la última vez que el mundo exterior —la crisis, la pandemia, la situación política— puso a prueba una relación y salió algo?", 2),
        ("¿Cuándo fue la última vez que la visión del mundo de alguien fue incompatible con la tuya de una manera que no se podía ignorar?", 2),
        ("¿Cuándo fue la última vez que la forma en que alguien se relaciona con la tecnología te dijo algo profundo sobre cómo se relaciona con los demás?", 2),
        ("¿Cuándo fue la última vez que amar a alguien te obligó a ampliar tu manera de ver el mundo?", 3),
        ("¿Cuándo fue la última vez que la diferencia en cómo ven el mundo vos y alguien que amás fue también la razón por la que el amor fue más rico?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que alguien se relaciona con la justicia, la sociedad o el planeta dice algo sobre cómo va a amar?", 3),
        ("¿Cuándo fue la última vez que el mundo fue demasiado grande y lo único que quería era reducirlo a una persona?", 3),
        ("¿Cuándo fue la última vez que la tecnología fue el medio a través del cual experimentaste algo de una relación que en la vida física no hubiera sido posible?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que amar a alguien también significa preocuparte por el mundo en el que ese alguien va a vivir?", 3),
    ],

    "familia": [
        ("¿Cuándo fue la última vez que hablaron de política en tu familia sin que terminara mal?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te hizo ver el mundo de una manera diferente?", 1),
        ("¿Cuándo fue la última vez que la tecnología cambió algo en cómo se comunica tu familia?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia hizo algo por la comunidad que te sorprendió?", 1),
        ("¿Cuándo fue la última vez que tu familia debatió algo de la actualidad y fue una conversación interesante?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te transmitió un valor sobre la justicia o la sociedad?", 1),
        ("¿Cuándo fue la última vez que la diferencia generacional dentro de tu familia fue obvia en una conversación política o social?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te sorprendió con una postura social o política que no esperabas?", 1),
        ("¿Cuándo fue la última vez que el medioambiente fue un tema dentro de tu familia?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue causa de conflicto o de conexión dentro de tu familia?", 1),
        ("¿Cuándo fue la última vez que tu familia participó en algo comunitario juntos?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te enseñó algo sobre vivir en comunidad?", 1),
        ("¿Cuándo fue la última vez que la situación política o económica del país afectó a tu familia de manera concreta?", 1),
        ("¿Cuándo fue la última vez que debatiste algo social o político con alguien de tu familia y los dos cambiaron algo?", 1),
        ("¿Cuándo fue la última vez que la historia del país o de la ciudad donde vivís fue parte de la conversación familiar?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te mostró cómo se puede contribuir al mundo desde lo pequeño?", 1),
        ("¿Cuándo fue la última vez que la diferencia de valores sociales o políticos con alguien de tu familia fue el tema que más evitaron?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue la causa de una discusión generacional dentro de tu familia?", 1),
        ("¿Cuándo fue la última vez que algo que pasaba en el país fue también algo que pasaba dentro de tu familia?", 1),
        ("¿Cuándo fue la última vez que tu familia te transmitió algo sobre la responsabilidad hacia la comunidad o el planeta?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te hizo ver una injusticia que antes no veías?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue el puente que mantuvo a tu familia conectada a través de la distancia?", 1),
        ("¿Cuándo fue la última vez que algo social o político fue el origen de una grieta dentro de tu familia?", 1),
        ("¿Cuándo fue la última vez que la historia de tu familia y la historia de tu país o comunidad estuvieron entrelazadas de manera que podías ver?", 1),
        ("¿Cuándo fue la última vez que la diferencia de valores políticos o sociales con alguien de tu familia fue algo que eligieron no resolver porque la relación valía más?", 2),
        ("¿Cuándo fue la última vez que la tecnología cambió algo fundamental en cómo tu familia se relaciona?", 2),
        ("¿Cuándo fue la última vez que la historia política o social del país —o del mundo— fue parte de una conversación honesta en tu familia?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que los valores sociales que tiene tu familia los heredaste sin que nadie te los dijera explícitamente?", 2),
        ("¿Cuándo fue la última vez que la situación del planeta fue algo que tu familia procesó de maneras muy diferentes?", 2),
        ("¿Cuándo fue la última vez que la diferencia de postura política con alguien de tu familia fue más dolorosa que cualquier otro desacuerdo?", 2),
        ("¿Cuándo fue la última vez que la historia de tu familia fue también la historia de algo más grande —una migración, una crisis, un cambio social?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue el espacio donde tu familia pudo conectar de maneras que en persona le costaban?", 2),
        ("¿Cuándo fue la última vez que algo de lo que pasa en el mundo te hizo ver a tu familia con más compasión?", 2),
        ("¿Cuándo fue la última vez que la diferencia generacional en los valores sociales dentro de tu familia fue tanto un conflicto como una fuente de aprendizaje?", 2),
        ("¿Cuándo fue la última vez que la historia política y social del lugar donde creciste fue parte de lo que te formó de maneras que todavía estás procesando?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que tu familia se relaciona con la sociedad —activamente o desde el margen— moldeó tu propia manera de estar en el mundo?", 3),
        ("¿Cuándo fue la última vez que la diferencia de valores entre generaciones de tu familia te hizo entender mejor dónde venís y hacia dónde vas?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que la comunidad que vos construís es también una respuesta —consciente o no— a lo que tu familia era o no era?", 3),
        ("¿Cuándo fue la última vez que la tecnología fue el espejo que reveló algo de tu familia que antes podía quedar escondido?", 3),
        ("¿Cuándo fue la última vez que la historia de tu familia te hizo ver tu lugar en el mundo de una manera diferente?", 3),
    ],

    "amistades": [
        ("¿Cuándo fue la última vez que tuviste una conversación sobre política con amigos que fue buena en lugar de tensa?", 1),
        ("¿Cuándo fue la última vez que la tecnología hizo posible una amistad que de otro modo no hubiera existido?", 1),
        ("¿Cuándo fue la última vez que hiciste algo por tu comunidad junto a amigos?", 1),
        ("¿Cuándo fue la última vez que la diferencia política o de valores con un amigo fue algo que pudieron atravesar igual?", 1),
        ("¿Cuándo fue la última vez que un amigo te hizo ver el mundo de una manera que nunca habías considerado?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue la razón por la que seguiste en contacto con alguien que de otro modo habrías perdido?", 1),
        ("¿Cuándo fue la última vez que el medioambiente o el planeta fue un tema que unió a tu grupo de amigos?", 1),
        ("¿Cuándo fue la última vez que vos y tus amigos hicieron algo que aportó a la comunidad?", 1),
        ("¿Cuándo fue la última vez que las diferencias de postura política entre amigos fueron más interesantes que conflictivas?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue el espacio donde construiste o mantuviste algo importante con amigos?", 1),
        ("¿Cuándo fue la última vez que tu grupo de amigos se movilizó por algo que consideraban injusto?", 1),
        ("¿Cuándo fue la última vez que la diferencia de cómo ven el mundo vos y un amigo fue la razón de una conversación que valió la pena?", 1),
        ("¿Cuándo fue la última vez que el contexto social —una crisis, un cambio, algo que pasaba en el país— fue el tema central de un encuentro con amigos?", 1),
        ("¿Cuándo fue la última vez que vos y tus amigos tuvieron visiones muy distintas sobre algo social y lo sostuvieron sin romperse?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue el centro de un conflicto dentro de tu grupo de amigos?", 1),
        ("¿Cuándo fue la última vez que sentiste que tu grupo de amigos era también una comunidad?", 1),
        ("¿Cuándo fue la última vez que alguien de tu grupo te hizo ver algo del mundo de una manera más justa?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue la razón por la que algo en un grupo de amigos mejoró o empeoró?", 1),
        ("¿Cuándo fue la última vez que un amigo te desafió a pensar diferente sobre algo social o político de una manera que valió la pena?", 1),
        ("¿Cuándo fue la última vez que la preocupación ambiental fue algo que compartiste con amigos de manera concreta?", 1),
        ("¿Cuándo fue la última vez que algo que pasaba en el mundo fue el contexto de uno de tus mejores momentos con amigos?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue el puente que mantuvo unido algo de un grupo cuando la distancia lo hubiera separado?", 1),
        ("¿Cuándo fue la última vez que el activismo —grande o pequeño— fue algo que compartiste con amigos?", 1),
        ("¿Cuándo fue la última vez que la diferencia de cómo ven el mundo vos y tus amigos fue también lo que hacía más interesante el grupo?", 1),
        ("¿Cuándo fue la última vez que la diferencia de valores políticos o sociales fue el límite de una amistad?", 2),
        ("¿Cuándo fue la última vez que la tecnología reveló algo de la dinámica de un grupo de amigos que antes no era visible?", 2),
        ("¿Cuándo fue la última vez que sentiste que tu grupo de amigos podía hacer algo que impactara más allá de su propio círculo?", 2),
        ("¿Cuándo fue la última vez que una conversación política con un amigo te cambió realmente algo en cómo pensás?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue el espacio donde viste algo de tus amigos que en persona no hubieran mostrado?", 2),
        ("¿Cuándo fue la última vez que la preocupación por el planeta fue algo que transformó algo concreto en cómo vivís con tu grupo?", 2),
        ("¿Cuándo fue la última vez que la diferencia de postura social entre amigos reveló algo importante sobre quiénes eran cada uno?", 2),
        ("¿Cuándo fue la última vez que sentiste que las amistades que tenés también dicen algo de quién sos en el mundo?", 2),
        ("¿Cuándo fue la última vez que un amigo te retó —con respeto— a ser más coherente con los valores que decís tener?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue tanto una herramienta de conexión como de desconexión dentro de un grupo?", 2),
        ("¿Cuándo fue la última vez que sentiste que la comunidad de amigos que tenés también es una forma de estar en el mundo?", 3),
        ("¿Cuándo fue la última vez que la diferencia de valores políticos o sociales fue el final de algo que querías mantener?", 3),
        ("¿Cuándo fue la última vez que la tecnología fue el espejo donde viste algo de tus amistades que no podías ver en la vida física?", 3),
        ("¿Cuándo fue la última vez que sentiste que tus amigos y vos podían contribuir a algo más allá de ustedes mismos?", 3),
        ("¿Cuándo fue la última vez que una conversación honesta con amigos sobre el mundo te hizo sentir que no estabas solo en lo que pensás?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que los amigos que elegís también dicen algo de tu relación con el mundo?", 3),
    ],

    "exs": [
        ("¿Cuándo fue la última vez que la diferencia política con alguien fue un tema en una relación pasada?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue parte de cómo empezó o terminó algo con alguien?", 1),
        ("¿Cuándo fue la última vez que pensaste en cómo alguien del pasado veía el mundo y lo viste de manera diferente ahora?", 1),
        ("¿Cuándo fue la última vez que la visión social o política de alguien con quien estuviste fue algo que al principio te atrajo?", 1),
        ("¿Cuándo fue la última vez que la tecnología complicó algo en una relación pasada?", 1),
        ("¿Cuándo fue la última vez que alguien con quien estuviste te abrió los ojos a algo del mundo que no podías ver antes?", 1),
        ("¿Cuándo fue la última vez que la diferencia en cómo veían el mundo vos y alguien del pasado fue más grande de lo que esperabas?", 1),
        ("¿Cuándo fue la última vez que las redes sociales fueron el espacio donde algo de una relación pasada se complicó?", 1),
        ("¿Cuándo fue la última vez que el compromiso social de alguien con quien saliste fue algo que admiraste —o no?", 1),
        ("¿Cuándo fue la última vez que algo que pasaba en el mundo fue el contexto de un momento importante con alguien del pasado?", 1),
        ("¿Cuándo fue la última vez que la diferencia de valores sociales fue algo que al principio parecía menor y después resultó central?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue el medio a través del cual terminó algo con alguien?", 1),
        ("¿Cuándo fue la última vez que alguien del pasado te enseñó algo sobre cómo estar en el mundo?", 1),
        ("¿Cuándo fue la última vez que la postura política de alguien del pasado fue algo que te hizo ver la tuya propia de otra manera?", 1),
        ("¿Cuándo fue la última vez que algo de lo que pasaba en el mundo cambió algo en cómo viviste una relación pasada?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue parte de cómo te relacionabas con alguien de una manera que en retrospectiva no te gusta?", 1),
        ("¿Cuándo fue la última vez que la diferencia en cómo veían el planeta —o su cuidado— fue parte de lo que no funcionó?", 1),
        ("¿Cuándo fue la última vez que la comunidad alrededor de alguien con quien saliste influyó en la relación?", 1),
        ("¿Cuándo fue la última vez que la diferencia de visión del mundo fue la razón de fondo de algo que terminó?", 1),
        ("¿Cuándo fue la última vez que alguien del pasado te hizo más curioso sobre el mundo o menos?", 1),
        ("¿Cuándo fue la última vez que el mundo exterior —noticias, crisis, situación política— entró en una relación y la sacudió?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue el lugar donde viste algo de alguien del pasado que en persona no hubiera mostrado?", 1),
        ("¿Cuándo fue la última vez que la visión del mundo de alguien que amaste fue también parte de lo que aprendiste en esa relación?", 1),
        ("¿Cuándo fue la última vez que la diferencia política o social fue algo que intentaron resolver y no pudieron?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que la visión del mundo de alguien con quien estuviste era incompatible con la tuya de una manera que no podías ignorar?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue el espejo donde viste algo de una relación pasada que en la vida física nunca hubiera sido tan claro?", 2),
        ("¿Cuándo fue la última vez que lo que alguien del pasado te enseñó sobre el mundo cambió cómo te relacionás con él ahora?", 2),
        ("¿Cuándo fue la última vez que la diferencia política fue el síntoma de algo más profundo que la relación no podía sostener?", 2),
        ("¿Cuándo fue la última vez que la forma en que alguien del pasado usaba la tecnología te dijo algo sobre cómo era en realidad?", 2),
        ("¿Cuándo fue la última vez que algo de lo que pasaba en el mundo fue la razón por la que una relación tuya se tensó de maneras que antes no tenía?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que el mundo en el que vivía alguien del pasado era diferente al tuyo aunque estuvieran en el mismo lugar?", 2),
        ("¿Cuándo fue la última vez que la diferencia de valores sociales fue algo que elegiste poner por encima del amor —o debajo?", 2),
        ("¿Cuándo fue la última vez que la visión del mundo de alguien que amaste fue parte de lo que más extrañaste?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la manera en que alguien se relaciona con el mundo dice más de quién es que cualquier cosa que pueda decirte?", 2),
        ("¿Cuándo fue la última vez que la diferencia de cómo veían el mundo vos y alguien que amaste fue también lo más enriquecedor de esa relación?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que alguien del pasado te enseñó algo sobre el mundo que todavía forma parte de quién sos?", 3),
        ("¿Cuándo fue la última vez que la tecnología fue el espacio donde algo de una relación pasada sobrevivió de maneras que no esperabas?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que alguien del pasado veía el mundo fue tanto un regalo como un límite?", 3),
        ("¿Cuándo fue la última vez que amar a alguien con una visión del mundo diferente te amplió —o te encogió?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que más te alejó de alguien fue también lo que más te enseñó sobre cómo querés estar en el mundo?", 3),
    ],

    "personalidad": [
        ("¿Cuándo fue la última vez que algo de lo que pasaba en el mundo te hizo reaccionar de una manera que te sorprendió?", 1),
        ("¿Cuándo fue la última vez que una conversación política o social te hizo ver algo de vos mismo?", 1),
        ("¿Cuándo fue la última vez que la tecnología reveló algo de tu carácter que en otro contexto no salía?", 1),
        ("¿Cuándo fue la última vez que el medioambiente fue un tema donde viste la diferencia entre lo que pensás y lo que hacés?", 1),
        ("¿Cuándo fue la última vez que tu postura política o social te generó incomodidad con alguien que te importa?", 1),
        ("¿Cuándo fue la última vez que la tecnología cambió algo en cómo te relacionás con los demás?", 1),
        ("¿Cuándo fue la última vez que la injusticia del mundo te hizo actuar en lugar de solo quejarte?", 1),
        ("¿Cuándo fue la última vez que tu manera de ver el mundo fue desafiada de una manera que resultó útil?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue el espejo donde viste algo de vos mismo que no te gustó?", 1),
        ("¿Cuándo fue la última vez que sentiste que ser parte de una comunidad te cambió algo?", 1),
        ("¿Cuándo fue la última vez que la forma en que usás la tecnología reflejó algo de cómo te relacionás con el mundo?", 1),
        ("¿Cuándo fue la última vez que algo de lo que pasa en el mundo te hizo más o menos optimista sobre la humanidad?", 1),
        ("¿Cuándo fue la última vez que tu postura social o política fue algo en lo que actuaste con coherencia?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue el lugar donde mejor pudiste ser vos mismo —o donde más te perdiste?", 1),
        ("¿Cuándo fue la última vez que la injusticia te hizo sentir algo que preferieras no sentir?", 1),
        ("¿Cuándo fue la última vez que la comunidad fue el espacio donde encontraste una versión de vos mismo que en otros contextos no existía?", 1),
        ("¿Cuándo fue la última vez que tu manera de ver la política o la sociedad fue algo que cambiaste de manera honesta?", 1),
        ("¿Cuándo fue la última vez que el medioambiente fue el tema donde más claramente viste la distancia entre tus valores y tus acciones?", 1),
        ("¿Cuándo fue la última vez que la tecnología te hizo sentir más conectado o más solo?", 1),
        ("¿Cuándo fue la última vez que ser parte de algo colectivo te hizo sentir más vos mismo?", 1),
        ("¿Cuándo fue la última vez que la injusticia te hizo actuar de manera que después te enorgulleció?", 1),
        ("¿Cuándo fue la última vez que tu relación con la tecnología reflejó algo de cómo te relacionás con los límites?", 1),
        ("¿Cuándo fue la última vez que sentiste que tus valores sociales y tus acciones cotidianas estaban alineados?", 1),
        ("¿Cuándo fue la última vez que algo de lo que pasa en el mundo te hizo replantearte qué clase de persona querés ser?", 1),
        ("¿Cuándo fue la última vez que la distancia entre lo que creés sobre el mundo y cómo vivís fue algo que no pudiste ignorar?", 2),
        ("¿Cuándo fue la última vez que la tecnología reveló algo de vos mismo que hubieras preferido no ver?", 2),
        ("¿Cuándo fue la última vez que la injusticia te confrontó con algo de tu propio privilegio o limitación?", 2),
        ("¿Cuándo fue la última vez que la forma en que te relacionás con la comunidad te dijo algo de tu carácter?", 2),
        ("¿Cuándo fue la última vez que tu postura política o social fue puesta a prueba y viste qué tan firme era realmente?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue el espacio donde más claramente podías ver tu sombra?", 2),
        ("¿Cuándo fue la última vez que el medioambiente fue un tema donde tuviste que reconocer una hipocresía tuya?", 2),
        ("¿Cuándo fue la última vez que sentiste que pertenecías a algo más grande que vos mismo y eso te cambió algo?", 2),
        ("¿Cuándo fue la última vez que la forma en que tratás el mundo —el planeta, la comunidad, la tecnología— fue el reflejo más honesto de tus valores?", 2),
        ("¿Cuándo fue la última vez que algo de lo que pasa en el mundo te obligó a mirar algo de vos mismo que preferías no ver?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue tanto el mejor como el peor espejo que tuviste?", 3),
        ("¿Cuándo fue la última vez que la injusticia del mundo te hizo confrontar algo de vos mismo que te resultó difícil sostener?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que te relacionás con el mundo —la sociedad, el planeta, la tecnología— dice algo muy honesto de quién sos?", 3),
        ("¿Cuándo fue la última vez que sentiste que ser parte de algo colectivo te permitió ser más plenamente vos mismo?", 3),
        ("¿Cuándo fue la última vez que la distancia entre lo que decís creer sobre el mundo y cómo vivís fue tan grande que no pudiste ignorarla?", 3),
        ("¿Cuándo fue la última vez que algo de lo que pasa en el mundo te hizo ver con más claridad qué clase de persona querés ser —y si lo estás siendo?", 3),
    ],

    "miedos": [
        ("¿Cuándo fue la última vez que algo de lo que pasaba en el mundo —noticias, política, crisis— te generó miedo real?", 1),
        ("¿Cuándo fue la última vez que el miedo al cambio climático fue algo más que una preocupación abstracta?", 1),
        ("¿Cuándo fue la última vez que la tecnología te generó un miedo que antes no tenías?", 1),
        ("¿Cuándo fue la última vez que el miedo a lo que puede pasar en el país —política, economía— afectó algo en tu vida?", 1),
        ("¿Cuándo fue la última vez que el miedo a la injusticia —propia o del mundo— te paralizó?", 1),
        ("¿Cuándo fue la última vez que algo que leíste o viste sobre el estado del mundo te quitó el sueño?", 1),
        ("¿Cuándo fue la última vez que la tecnología te generó miedo por algo que implica para el futuro?", 1),
        ("¿Cuándo fue la última vez que el miedo a lo colectivo —una pandemia, una crisis social— fue más paralizante que cualquier miedo individual?", 1),
        ("¿Cuándo fue la última vez que el miedo al futuro del planeta fue algo que te hizo actuar?", 1),
        ("¿Cuándo fue la última vez que el miedo a perder la privacidad —por la tecnología— fue algo que te afectó?", 1),
        ("¿Cuándo fue la última vez que el miedo a lo que puede hacer la tecnología fue más grande que la fascinación?", 1),
        ("¿Cuándo fue la última vez que el miedo a la injusticia fue también el miedo a que te pasara a vos?", 1),
        ("¿Cuándo fue la última vez que el miedo al futuro del mundo fue más poderoso que la esperanza?", 1),
        ("¿Cuándo fue la última vez que el miedo a la inestabilidad social o política fue algo que cambió una decisión tuya?", 1),
        ("¿Cuándo fue la última vez que algo de la realidad política o social del mundo te hizo sentir que el suelo se movía?", 1),
        ("¿Cuándo fue la última vez que el miedo a las consecuencias ambientales de algo que hacés fue suficiente para cambiarlo?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue la razón de un miedo que no sabías cómo nombrar?", 1),
        ("¿Cuándo fue la última vez que el miedo a que el mundo cambie de maneras que no podés controlar fue más grande que la adaptación?", 1),
        ("¿Cuándo fue la última vez que el miedo colectivo —de tu comunidad, de tu país— lo sentiste también como tuyo?", 1),
        ("¿Cuándo fue la última vez que el miedo a la injusticia fue también el motor de algo que hiciste?", 1),
        ("¿Cuándo fue la última vez que la realidad del mundo fue más aterradora que cualquier ficción?", 1),
        ("¿Cuándo fue la última vez que el miedo a lo que viene tecnológicamente fue más real que la emoción?", 1),
        ("¿Cuándo fue la última vez que el miedo al futuro colectivo fue más difícil de manejar que el miedo al futuro individual?", 1),
        ("¿Cuándo fue la última vez que algo de lo que pasa en el mundo te hizo sentir que tus miedos eran compartidos por muchos?", 1),
        ("¿Cuándo fue la última vez que el miedo al estado del mundo reveló algo de lo que más valorás?", 2),
        ("¿Cuándo fue la última vez que el miedo a la tecnología fue también el miedo a algo de vos mismo que ella podría revelar?", 2),
        ("¿Cuándo fue la última vez que el miedo al cambio climático fue suficientemente concreto para cambiar algo en cómo vivís?", 2),
        ("¿Cuándo fue la última vez que el miedo colectivo te conectó con algo de tu propio miedo individual?", 2),
        ("¿Cuándo fue la última vez que la injusticia del mundo te generó un miedo que también fue vergüenza por no hacer más?", 2),
        ("¿Cuándo fue la última vez que el miedo a la inestabilidad política fue también el miedo a perder algo que creías fijo?", 2),
        ("¿Cuándo fue la última vez que el miedo al futuro del planeta fue también el miedo a lo que le vas a dejar a quienes vengan?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue el espejo donde viste algo de tus miedos que en otra parte no podías ver?", 2),
        ("¿Cuándo fue la última vez que el miedo al mundo te hizo querer construir algo propio que fuera más sólido que todo lo que parece frágil?", 2),
        ("¿Cuándo fue la última vez que el miedo al futuro colectivo fue también el motor de algo tuyo?", 2),
        ("¿Cuándo fue la última vez que el miedo al estado del mundo te hizo ver algo de vos mismo que preferías no ver?", 3),
        ("¿Cuándo fue la última vez que el miedo colectivo fue también el espejo de tu miedo más profundo?", 3),
        ("¿Cuándo fue la última vez que la tecnología te mostró algo que te aterrorizó sobre el futuro y no pudiste mirar para otro lado?", 3),
        ("¿Cuándo fue la última vez que el miedo al mundo fue también el miedo a que nada de lo que hacés sea suficiente?", 3),
        ("¿Cuándo fue la última vez que el miedo a la injusticia fue también el miedo a tu propia complicidad?", 3),
        ("¿Cuándo fue la última vez que el miedo al futuro del planeta fue lo suficientemente real para cambiar algo profundo en cómo querés vivir?", 3),
    ],

    "logros": [
        ("¿Cuándo fue la última vez que contribuiste a algo más grande que vos mismo?", 1),
        ("¿Cuándo fue la última vez que algo que hiciste tuvo un impacto en tu comunidad?", 1),
        ("¿Cuándo fue la última vez que usaste la tecnología para lograr algo que antes parecía imposible?", 1),
        ("¿Cuándo fue la última vez que lograste algo relacionado con el medioambiente —aunque fuera pequeño?", 1),
        ("¿Cuándo fue la última vez que participaste en algo colectivo que salió bien?", 1),
        ("¿Cuándo fue la última vez que lograste cambiar algo en tu entorno que antes parecía imposible de cambiar?", 1),
        ("¿Cuándo fue la última vez que tu voz fue parte de algo que logró un cambio?", 1),
        ("¿Cuándo fue la última vez que la tecnología te permitió lograr algo que de otro modo no hubiera sido posible?", 1),
        ("¿Cuándo fue la última vez que contribuiste a algo que le va a servir a gente que todavía no conocés?", 1),
        ("¿Cuándo fue la última vez que lograste convencer a alguien de ver algo social o político de una manera diferente?", 1),
        ("¿Cuándo fue la última vez que algo que hiciste fue también una forma de construir comunidad?", 1),
        ("¿Cuándo fue la última vez que lograste algo que te hizo sentir parte de algo más grande?", 1),
        ("¿Cuándo fue la última vez que tu contribución a algo colectivo fue reconocida de una manera que no esperabas?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue la herramienta que te permitió lograr algo con impacto?", 1),
        ("¿Cuándo fue la última vez que un logro tuyo fue también un logro para tu comunidad?", 1),
        ("¿Cuándo fue la última vez que algo que creaste o construiste tuvo un impacto en el mundo que te rodeaba?", 1),
        ("¿Cuándo fue la última vez que lograste algo que parecía imposible porque lo hiciste junto a otros?", 1),
        ("¿Cuándo fue la última vez que tu preocupación ambiental se tradujo en una acción concreta que valió la pena?", 1),
        ("¿Cuándo fue la última vez que la tecnología fue parte de un logro que le sirvió a alguien más allá de vos?", 1),
        ("¿Cuándo fue la última vez que sentiste que lo que lograste tenía un valor social además de personal?", 1),
        ("¿Cuándo fue la última vez que lograste algo que pensabas que requería más poder o más recursos de los que tenías?", 1),
        ("¿Cuándo fue la última vez que tu manera de relacionarte con la tecnología fue en sí misma un logro?", 1),
        ("¿Cuándo fue la última vez que lograste algo que le mostró a alguien cercano que el cambio es posible?", 1),
        ("¿Cuándo fue la última vez que algo pequeño que hiciste tuvo un efecto dominó que no esperabas?", 1),
        ("¿Cuándo fue la última vez que un logro colectivo te enseñó algo que ningún logro individual podría haberte dado?", 2),
        ("¿Cuándo fue la última vez que lo que lograste fue también una forma de responder a algo que veías injusto?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue tanto el obstáculo como la herramienta para lograr algo importante?", 2),
        ("¿Cuándo fue la última vez que lograste algo que tuvo un impacto más allá de lo que esperabas?", 2),
        ("¿Cuándo fue la última vez que un logro tuyo cambió algo en cómo te relacionás con la comunidad?", 2),
        ("¿Cuándo fue la última vez que lograste algo que requirió que pongas tus valores sociales en práctica, no solo en palabras?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue el vehículo de un logro que también fue un acto de comunidad?", 2),
        ("¿Cuándo fue la última vez que lograste algo que también cambió algo en cómo ves el mundo?", 2),
        ("¿Cuándo fue la última vez que contribuir a algo más grande que vos fue también uno de los logros más importantes de tu vida?", 2),
        ("¿Cuándo fue la última vez que un logro colectivo te mostró que solo no lo hubieras podido —y que eso estuvo bien?", 2),
        ("¿Cuándo fue la última vez que lograste algo que cambió para siempre cómo te relacionás con tu comunidad o con el mundo?", 3),
        ("¿Cuándo fue la última vez que un logro tuyo fue también un acto de justicia —aunque pequeño?", 3),
        ("¿Cuándo fue la última vez que la tecnología fue el medio a través del cual lograste algo que no hubiera sido posible en ninguna otra época?", 3),
        ("¿Cuándo fue la última vez que lo que lograste fue también una manera de dejar algo en el mundo que valdrá después de que no estés?", 3),
        ("¿Cuándo fue la última vez que sentiste que un logro tuyo fue también una contribución al tipo de mundo que querés habitar?", 3),
        ("¿Cuándo fue la última vez que lograste algo que cambió algo de la comunidad que te rodea —aunque sea algo pequeño— y eso valió más que cualquier reconocimiento?", 3),
    ],

    "sinFiltro": [
        ("¿Cuándo fue la última vez que scrolleaste redes sociales y te sentiste peor que antes de empezar?", 1),
        ("¿Cuándo fue la última vez que te quejaste del medioambiente sin hacer nada diferente al respecto?", 1),
        ("¿Cuándo fue la última vez que dijiste algo político o social para quedar bien sin creértelo del todo?", 1),
        ("¿Cuándo fue la última vez que te quedaste mirando el teléfono durante una conversación y no lo pudiste evitar?", 1),
        ("¿Cuándo fue la última vez que stalkeaste a alguien en redes sin ninguna razón real?", 1),
        ("¿Cuándo fue la última vez que posteaste algo que en privado no creías del todo?", 1),
        ("¿Cuándo fue la última vez que te quejaste de la política pero no fuiste a votar o no leíste nada sobre el tema?", 1),
        ("¿Cuándo fue la última vez que la tecnología hizo algo que debería haber hecho vos?", 1),
        ("¿Cuándo fue la última vez que enviaste un audio de 5 minutos cuando un mensaje corto era más que suficiente?", 1),
        ("¿Cuándo fue la última vez que leíste solo el titular de una nota y opinaste con seguridad?", 1),
        ("¿Cuándo fue la última vez que te metiste en una discusión política online que no llevó a ningún lado?", 1),
        ("¿Cuándo fue la última vez que te comparaste con alguien en redes y lo convirtiste en un problema tuyo?", 1),
        ("¿Cuándo fue la última vez que actuaste como si fuera importante cuidar el ambiente pero lo primero que hacés cuando llegás a casa es encender el aire acondicionado al máximo?", 1),
        ("¿Cuándo fue la última vez que usaste la tecnología para evitar una conversación que debías tener en persona?", 1),
        ("¿Cuándo fue la última vez que te indignaste públicamente por algo y en privado lo hacías igual?", 1),
        ("¿Cuándo fue la última vez que compraste algo que no necesitabas con un clic porque era fácil?", 1),
        ("¿Cuándo fue la última vez que bloqueaste a alguien en lugar de tener la conversación?", 1),
        ("¿Cuándo fue la última vez que te acordaste de un cumpleaños solo porque la app te lo dijo?", 1),
        ("¿Cuándo fue la última vez que preguntaste la opinión de la IA antes que la de un amigo?", 1),
        ("¿Cuándo fue la última vez que hiciste ghosting a alguien porque la tecnología hacía que fuera demasiado fácil?", 1),
        ("¿Cuándo fue la última vez que tu uso de redes sociales fue más una performance que una conexión real?", 1),
        ("¿Cuándo fue la última vez que te quedaste en el loop de las noticias malas sin poder salir y sin poder hacer nada?", 1),
        ("¿Cuándo fue la última vez que mandaste un mensaje importanteísimo por chat cuando la situación pedía una llamada?", 1),
        ("¿Cuándo fue la última vez que usaste la inteligencia artificial para hacer algo que debías haber hecho vos?", 1),
        ("¿Cuándo fue la última vez que tu postura pública en redes era radicalmente distinta a lo que pensás en privado?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue el lugar donde fuiste más deshonesto con vos mismo?", 2),
        ("¿Cuándo fue la última vez que la comodidad tecnológica te hizo ser peor ciudadano, vecino o miembro de tu comunidad?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que tu preocupación ambiental era más una identidad que un hábito?", 2),
        ("¿Cuándo fue la última vez que las redes sociales te mostraron algo de vos mismo que en persona nunca hubiera salido?", 2),
        ("¿Cuándo fue la última vez que usaste la tecnología para evitar estar presente en algo que importaba?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que tu consumo tecnológico contradecía algo que decías valorar?", 2),
        ("¿Cuándo fue la última vez que la comodidad de la tecnología te hizo ser menos empático de lo que hubiera sido en persona?", 2),
        ("¿Cuándo fue la última vez que tu postura política o social fue más sobre cómo querés ser visto que sobre lo que realmente creés?", 2),
        ("¿Cuándo fue la última vez que la tecnología fue el escudo detrás del cual te escondiste de algo que no querías enfrentar?", 2),
        ("¿Cuándo fue la última vez que la tecnología reveló algo de vos mismo que preferirías que nadie supiera —incluyéndote a vos?", 3),
        ("¿Cuándo fue la última vez que tu relación con la tecnología fue tan honesta sobre quién sos que te resultó incómoda?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que publicás en redes dice algo de lo que más te falta en la vida real?", 3),
        ("¿Cuándo fue la última vez que la tecnología fue el lugar donde fuiste más vos mismo —sin filtros, sin audiencia?", 3),
        ("¿Cuándo fue la última vez que la comodidad tecnológica fue también una forma de escapar de algo que merecía tu presencia?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que usás la tecnología dice algo profundo de cómo te relacionás con el mundo?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS14:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS14[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
