#!/usr/bin/env python3
"""Batch 30 - self-sabotage, procrastination, comfort zone, discipline, motivation, habits."""
import json

ADDITIONS30 = {
    "infancia": [
        ("¿Cuándo fue la primera vez que postergaste algo porque te generaba miedo y qué pasó?", 1),
        ("¿Qué hábito de tu infancia que era malo te costó más romper?", 1),
        ("¿Eras un chico disciplinado o más bien evitabas lo que te costaba?", 1),
        ("¿Qué cosa que te costaba mucho de chico sin embargo seguías intentando?", 1),
        ("¿Cuándo fue la primera vez que te saboteaste a vos mismo en algo importante?", 1),
        ("¿Qué rutina o hábito de tu infancia que era bueno perdiste al crecer?", 1),
        ("¿Qué zona de confort tenías de chico que te costó salir?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que te estabas poniendo límites innecesarios?", 1),
        ("¿Qué cosa que hacías de chico por pura disciplina hoy te da orgullo?", 1),
        ("¿Cómo te motivabas de chico para hacer las cosas que no querías hacer?", 1),
        ("¿Qué hábito de tu infancia que era positivo querés recuperar?", 1),
        ("¿Cuándo fue la primera vez que hiciste algo difícil y te sorprendiste a vos mismo?", 1),
        ("¿Qué cosa de chico que postponías constantemente finalmente hacías igual?", 1),
        ("¿Tenías rituales o hábitos de chico que te ayudaban a concentrarte o estudiar?", 1),
        ("¿Qué cosa de chico que evitabas resultó ser mucho mejor de lo que imaginabas?", 1),
        ("¿Cuándo fue la primera vez que la pereza te costó algo que querías?", 1),
        ("¿Qué parte de tu personalidad de chico que era autodisciplinada todavía está en vos?", 1),
        ("¿Qué modelo de disciplina o hábito de tu infancia que viste en algún adulto adoptaste?", 1),
        ("¿Cuándo fue la primera vez que te pusiste un objetivo difícil y lo cumpliste?", 1),
        ("¿Qué hábito de tu infancia que era malo seguís teniendo de adulto?", 1),
        ("¿Qué patrón de evitación que aprendiste de chico todavía aparece en tu vida adulta?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que te estabas saboteando a vos mismo?", 2),
        ("¿Qué cosa de tu infancia que te costaba mucho hoy entendés que fue el entrenamiento para algo más grande?", 2),
        ("¿Cómo la disciplina o su ausencia en tu infancia moldeó cómo te relacionás con el esfuerzo hoy?", 2),
        ("¿Qué zona de confort de tu infancia que rompiste fue el punto de partida de un cambio importante?", 2),
        ("¿Cuándo fue la primera vez que entendiste que postergarlo no lo hacía desaparecer?", 2),
        ("¿Qué hábito que construiste de chico que te parecía pequeño resultó ser fundamental de adulto?", 2),
        ("¿Qué patrón de sabotaje propio que viene de tu infancia todavía te cuesta más reconocer?", 3),
        ("¿Cuándo fue la primera vez que la comodidad te costó algo que realmente querías?", 3),
        ("¿Qué cosa de tu infancia que evitabas resultó ser exactamente lo que más necesitabas?", 3),
        ("¿Qué hábito de tu infancia que era aparentemente pequeño cambió quién sos de manera que no esperabas?", 3),
        ("¿Cuánto del auto-sabotaje que tenés hoy tiene raíces directas en algo que aprendiste de chico?", 3),
        ("¿Qué zona de confort de tu infancia que nunca rompiste todavía te define de maneras que no ves?", 3),
        ("¿Qué versión de vos de chico que era más disciplinada o más libre que la actual querés recuperar?", 3),
    ],

    "futuro": [
        ("¿Qué hábito querés instalar en tu vida en el próximo año?", 1),
        ("¿Hay algo que seguís postergando que sabés que tenés que hacer?", 1),
        ("¿Qué zona de confort querés salir en el futuro cercano?", 1),
        ("¿Qué hábito que tenés hoy querés eliminar?", 1),
        ("¿Cuándo fue la última vez que hiciste algo que te costó y te alegró haberlo hecho?", 1),
        ("¿Qué cosa que postergás indefinidamente querés comprometerte a hacer?", 1),
        ("¿Cómo querés que sea tu rutina diaria en cinco años?", 1),
        ("¿Qué hábito de alguien que admirás querés incorporar?", 1),
        ("¿Qué cosa que evitás hacer por miedo a no hacerla bien querés intentar igualmente?", 1),
        ("¿Cuánto tiempo le dedicás a cosas que te importan versus cosas urgentes pero no importantes?", 1),
        ("¿Qué cambio de hábito que sabés que necesitás hacer te genera más resistencia?", 1),
        ("¿Cómo querés manejar la procrastinación en el futuro de manera diferente a ahora?", 1),
        ("¿Qué cosa que estás evitando tiene la capacidad de cambiar algo importante si la hacés?", 1),
        ("¿Qué proyecto que postergaste durante mucho tiempo querés empezar de una vez?", 1),
        ("¿Cuánto de tu futuro depende de hábitos que todavía no instalaste?", 1),
        ("¿Qué cosa que hacés que te sabotea querés dejar de hacer?", 1),
        ("¿Cómo te gustaría que sea tu relación con la disciplina en el futuro?", 1),
        ("¿Qué compromiso con vos mismo que incumpliste una y otra vez querés honrar de verdad?", 1),
        ("¿Qué versión futura de vos mismo requiere hábitos que hoy no tenés?", 1),
        ("¿Qué cosa que hacés por inercia querés cambiar porque ya no te sirve?", 1),
        ("¿Cuánto de lo que postergás para el futuro es en realidad evitación disfrazada de planificación?", 2),
        ("¿Qué patrón de auto-sabotaje tuyo tiene el mayor potencial de arruinarte algo importante en el futuro?", 2),
        ("¿Qué hábito futuro que sabés que necesitás instalar te genera más resistencia y por qué?", 2),
        ("¿Cuánto de tu futuro está esperando que rompas un hábito que llevas años sin poder cambiar?", 2),
        ("¿Qué zona de confort que querés salir en el futuro ya sabés que va a costar más de lo que te imaginás?", 2),
        ("¿Cómo querés que sea diferente tu relación con el esfuerzo y la disciplina en el futuro?", 2),
        ("¿Qué decisión futura que sabés que tenés que tomar seguís postergando y qué es exactamente lo que la frena?", 2),
        ("¿Qué futuro tuyo está bloqueado por algo que evitás hacer y que sabés que tenés que hacer?", 3),
        ("¿Cuánto de lo que querés para el futuro ya podría estar en marcha si no fuera por la procrastinación o el miedo?", 3),
        ("¿Qué versión de vos mismo del futuro que más querés ser requiere que hagas algo hoy que te genera el mayor rechazo?", 3),
        ("¿Cuánto de tu auto-sabotaje actual te está alejando de un futuro que en el fondo ya sabés que querés?", 3),
        ("¿Qué hábito que instalás y abandonás una y otra vez si lo sostuvieras esta vez cambiaría algo fundamental?", 3),
        ("¿Qué conversación con vos mismo sobre el futuro que evitás tener tiene las respuestas que más necesitás?", 3),
        ("¿Qué estarías dispuesto a sacrificar hoy por un futuro que genuinamente querés y no solo imaginás?", 3),
    ],

    "amor": [
        ("¿Cómo te saboteás en el amor cuando algo empieza a ir bien?", 1),
        ("¿Qué hábito que tenés en pareja querés cambiar?", 1),
        ("¿Cuándo fue la última vez que saliste de tu zona de confort en una relación?", 1),
        ("¿Qué cosa que postergás en el amor tenés que hacer?", 1),
        ("¿Cuándo fue la última vez que la comodidad en una relación te impidió crecer?", 1),
        ("¿Qué hábito de pareja que tenés que sabés que daña la relación todavía no cambiaste?", 1),
        ("¿Cómo te motivás para cuidar una relación cuando estás cansado o distraído?", 1),
        ("¿Qué rutina de pareja que tenés querés sostener o mejorar?", 1),
        ("¿Cuándo fue la última vez que hiciste algo para sorprender a tu pareja que requirió esfuerzo?", 1),
        ("¿Qué cosa en el amor que evitás hacer por miedo sabés que mejoraría la relación?", 1),
        ("¿Qué hábito de comunicación de pareja que tenés querés cambiar?", 1),
        ("¿Cuándo fue la última vez que priorizaste la relación sobre la comodidad?", 1),
        ("¿Qué cosa en el amor que postergás abordar sabés que va a ser más difícil cuanto más esperes?", 1),
        ("¿Cómo la pereza emocional afecta tus relaciones?", 1),
        ("¿Qué hábito positivo de pareja que tenías y que perdiste querés recuperar?", 1),
        ("¿Cuándo fue la última vez que hiciste algo incómodo para mejorar una relación?", 1),
        ("¿Qué cosa en el amor que haces por inercia ya no te sirve y querés cambiar?", 1),
        ("¿Cómo el miedo a la vulnerabilidad te hace procrastinar en el amor?", 1),
        ("¿Qué patrón en el amor que se repite una y otra vez querés romper?", 1),
        ("¿Qué disciplina en el amor que querés tener todavía no lograste instalar?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que te estabas saboteando en el amor?", 2),
        ("¿Qué patrón de auto-sabotaje en tus relaciones tiene más historia y más peso?", 2),
        ("¿Cuánto de la comodidad que buscás en el amor te impide la profundidad que también querés?", 2),
        ("¿Qué cosa en el amor que postergás abordar ya sabés que va a tener un costo mayor si seguís esperando?", 2),
        ("¿Cómo el miedo al abandono o al rechazo te hace sabotear relaciones que van bien?", 2),
        ("¿Qué hábito que tenés en el amor que te hace daño y que sabés que te hace daño seguís igual?", 2),
        ("¿Cuándo fue la primera vez que reconociste que estabas arruinando algo bueno por miedo a que fuera bueno?", 2),
        ("¿Cuánto de tu auto-sabotaje en el amor es miedo consciente y cuánto es automático?", 3),
        ("¿Qué versión tuya en el amor que querés ser requiere romper hábitos que te protegen pero también te limitan?", 3),
        ("¿Cuánto de lo que postergás en el amor está esperando condiciones que nunca van a ser perfectas?", 3),
        ("¿Qué patrón tuyo en el amor que viene de lejos si lo rompieras esta vez cambiaría algo fundamental?", 3),
        ("¿Cuánto del amor que querés está esperando que hagas algo que evitás hacer porque cambia la dinámica?", 3),
        ("¿Qué te está costando más en el amor: el miedo a perderte algo o el miedo a comprometerte con algo?", 3),
        ("¿Qué versión del amor que querés tener ya podría existir si dejás de sabotearte de la manera en que lo hacés?", 3),
    ],

    "familia": [
        ("¿Qué hábito familiar que querés cambiar todavía no cambiaste?", 1),
        ("¿Qué cosa que postergás hacer por tu familia sabés que tenés que hacer?", 1),
        ("¿Cómo la procrastinación afecta tus vínculos familiares?", 1),
        ("¿Qué zona de confort en tu dinámica familiar querés salir?", 1),
        ("¿Cuándo fue la última vez que hiciste algo incómodo por alguien de tu familia?", 1),
        ("¿Qué hábito positivo querés instalar en tu familia?", 1),
        ("¿Cuándo fue la última vez que priorizaste tiempo de calidad con tu familia sobre la comodidad?", 1),
        ("¿Qué cosa que evitás hacer con tu familia sabés que mejoraría el vínculo?", 1),
        ("¿Qué rutina familiar que tenías y perdiste querés recuperar?", 1),
        ("¿Cómo te saboteás en los vínculos familiares cuando algo empieza a estar mejor?", 1),
        ("¿Qué conversación familiar que postergás tener tiene más costo cuanto más la postergás?", 1),
        ("¿Cuándo fue la última vez que hiciste algo para mejorar una dinámica familiar que te generaba resistencia?", 1),
        ("¿Qué patrón familiar que se repite una y otra vez querés ser el que lo rompa?", 1),
        ("¿Qué hábito que tenés en familia que sabés que no sirve seguís igual?", 1),
        ("¿Cómo el confort de la dinámica familiar conocida te frena de cambiar algo que querés cambiar?", 1),
        ("¿Qué cosa que querés hacer por alguien de tu familia seguís postergando?", 1),
        ("¿Cuándo fue la última vez que rompiste un patrón familiar que se repetía y cómo resultó?", 1),
        ("¿Qué cosa que te cuesta en los vínculos familiares si la trabajás mejoraría algo importante?", 1),
        ("¿Cómo la inercia familiar te hace seguir en dinámicas que ya no te sirven?", 1),
        ("¿Qué cosa que haces en familia por hábito ya no suma y querés cambiar?", 1),
        ("¿Qué patrón familiar que se repite generacionalmente tenés más poder del que creés para cambiar?", 2),
        ("¿Cuánto de lo que no cambiás en tu familia es porque genuinamente no podés versus porque es más cómodo no hacerlo?", 2),
        ("¿Qué zona de confort familiar que romper te generaría más resistencia en el corto plazo pero más ganancia en el largo?", 2),
        ("¿Cómo la pereza emocional en los vínculos familiares afecta algo que querés que sea diferente?", 2),
        ("¿Qué cosa que postergás con alguien de tu familia si la hacés hoy cambia algo que mañana podría ser tarde?", 2),
        ("¿Cuándo fue la última vez que hiciste algo que requirió esfuerzo real por alguien de tu familia y valió la pena?", 2),
        ("¿Qué patrón de evitación familiar que tenés es en realidad una forma de auto-sabotaje disfrazada?", 2),
        ("¿Qué cambio en la dinámica familiar que querés ya podría estar en marcha si no fuera por la inercia?", 3),
        ("¿Cuánto del confort familiar que priorizás te está costando la profundidad que también querés?", 3),
        ("¿Qué conversación o acción familiar que postergás tiene el mayor potencial de cambiar algo importante?", 3),
        ("¿Cuánto de los hábitos que tenés en familia son elecciones genuinas y cuánto son inercia que ya no cuestionás?", 3),
        ("¿Qué patrón familiar que venís repitiendo sin darte cuenta si lo vieras claramente te daría más urgencia de cambiarlo?", 3),
        ("¿Qué necesitaría pasar para que te comprometieras de verdad a cambiar algo en tu dinámica familiar?", 3),
        ("¿Cuánto del bienestar de tu familia futura depende de hábitos y cambios que podés empezar hoy?", 3),
    ],

    "amistades": [
        ("¿Qué amistades que querés cultivar postergás constantemente?", 1),
        ("¿Cuándo fue la última vez que hiciste algo incómodo para mantener una amistad?", 1),
        ("¿Qué hábito de amistad que querés tener todavía no instalaste?", 1),
        ("¿Cómo la comodidad te impide a veces hacer el esfuerzo que las amistades requieren?", 1),
        ("¿Qué amistad que querés recuperar seguís postergando retomar?", 1),
        ("¿Cuándo fue la última vez que pusiste energía real en una amistad?", 1),
        ("¿Qué zona de confort social querés salir?", 1),
        ("¿Qué tipo de personas evitás conocer aunque creas que te podrían aportar?", 1),
        ("¿Cuándo fue la última vez que hiciste algo nuevo con amigos?", 1),
        ("¿Qué hábito de amistad que tenés que sabés que daña el vínculo seguís teniendo?", 1),
        ("¿Cómo te saboteás en las amistades cuando empiezan a profundizarse?", 1),
        ("¿Qué cosa en las amistades que evitás hacer sabés que las mejoraría?", 1),
        ("¿Cuándo fue la última vez que buscaste activamente hacer nuevos amigos?", 1),
        ("¿Qué patrón en tus amistades que se repite querés cambiar?", 1),
        ("¿Cómo la pereza social te afecta en la calidad de tus amistades?", 1),
        ("¿Qué cosa que querés hacer por un amigo seguís postergando?", 1),
        ("¿Cuándo fue la última vez que saliste de tu círculo habitual de amigos?", 1),
        ("¿Qué hábito positivo de amistad que querés tener no terminás de instalar?", 1),
        ("¿Cómo la inercia afecta las amistades que tenés?", 1),
        ("¿Qué amistad que está en piloto automático merece más energía de la que le estás dando?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que te estabas aislando y lo decidiste cambiar?", 2),
        ("¿Qué patrón de auto-sabotaje en tus amistades tiene más historia?", 2),
        ("¿Cuánto de la distancia que ponés en algunas amistades es elección genuina y cuánto es evitación?", 2),
        ("¿Qué cosa en tus amistades que postergás abordar ya sabés que tiene un costo mayor cuanto más esperas?", 2),
        ("¿Cómo el miedo a la vulnerabilidad te hace evitar la profundidad en las amistades?", 2),
        ("¿Cuándo fue la última vez que hiciste algo fuera de tu zona de confort social y resultó bien?", 2),
        ("¿Qué hábito social que tenés y que sabés que te aísla seguís igual?", 2),
        ("¿Qué amistad que está en riesgo de perderse ya podría estar recuperada si no fuera por la procrastinación?", 3),
        ("¿Cuánto del tiempo que le dedicás a tus amistades refleja genuinamente cuánto te importan?", 3),
        ("¿Qué versión tuya en las amistades que querés ser requiere salir de hábitos que te protegen pero te aíslan?", 3),
        ("¿Cuánto de lo que querés en tus amistades ya podría existir si hicieras el esfuerzo que postergás?", 3),
        ("¿Qué patrón de aislamiento o distancia social tuyo si lo vieras claramente te daría más urgencia de cambiarlo?", 3),
        ("¿Cuándo fue la última vez que una amistad que te requirió un esfuerzo real valió cada segundo de ese esfuerzo?", 3),
        ("¿Qué necesitaría pasar para que le des a tus amistades la energía que dicen que les querés dar?", 3),
    ],

    "exs": [
        ("¿Cómo te saboteabas en relaciones pasadas cuando todo iba bien?", 1),
        ("¿Qué hábito que tenías en una relación pasada que reconocés como auto-destructivo todavía aparece?", 1),
        ("¿Cuándo fue la última vez que la comodidad en una relación te impidió hacer algo que necesitabas hacer?", 1),
        ("¿Qué patrón que se repitió en varias relaciones tuyas reconocés como auto-sabotaje?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que estabas arruinando algo que funcionaba?", 1),
        ("¿Qué cosa que postergabas en relaciones pasadas costó más cuanto más la postergaste?", 1),
        ("¿Cómo la procrastinación emocional afectó alguna relación pasada tuya?", 1),
        ("¿Qué hábito de pareja que tenías que sabías que dañaba la relación no cambiaste a tiempo?", 1),
        ("¿Cuándo fue la primera vez que reconociste que te estabas saboteando en el amor pero no pudiste parar?", 1),
        ("¿Qué zona de confort que no rompiste en una relación pasada te costó esa relación o parte de ella?", 1),
        ("¿Cómo el miedo al compromiso o a la profundidad te hizo boicotear algo que podría haber sido bueno?", 1),
        ("¿Qué cosa que hacías en relaciones pasadas por inercia sabías que no sumaba pero seguías haciendo?", 1),
        ("¿Cuándo fue la primera vez que elegiste la comodidad sobre el crecimiento en el amor?", 1),
        ("¿Qué patrón de evitación que tenías en relaciones pasadas todavía te persigue?", 1),
        ("¿Qué hábito que tenías en el amor que era auto-sabotaje puro entendiste recién después?", 1),
        ("¿Cuándo fue la primera vez que reconociste que eras vos el problema en una relación?", 1),
        ("¿Qué cosa que postergaste en una relación pasada que si lo hubieras hecho hubiera cambiado el resultado?", 1),
        ("¿Cómo la comodidad de quedarte en lo conocido te impidió crecer en alguna relación?", 1),
        ("¿Qué patrón que se repetía en relaciones pasadas tuyas entendiste como auto-sabotaje solo con el tiempo?", 1),
        ("¿Qué disciplina en el amor que nunca pudiste instalar en relaciones pasadas querés tener ahora?", 1),
        ("¿Qué patrón de auto-sabotaje en el amor que se repitió en varias relaciones tuyas todavía no terminaste de entender del todo?", 2),
        ("¿Cuánto de lo que hoy llamás 'mala suerte' en el amor fue en realidad auto-sabotaje que hoy ves con más claridad?", 2),
        ("¿Qué hábito que tenías en relaciones pasadas que sabías que era malo y que no cambiaste cuánto te costó?", 2),
        ("¿Cuándo fue la primera vez que entendiste que el problema en una relación pasada era un patrón tuyo y no del otro?", 2),
        ("¿Qué zona de confort en el amor que no rompiste en el pasado querés comprometerte a romper ahora?", 2),
        ("¿Cómo el miedo a la intimidad disfrazado de otra cosa te hizo alejar a personas que valías en relaciones pasadas?", 2),
        ("¿Cuándo fue la primera vez que reconociste que te auto-saboteabas en el amor de manera sistemática?", 2),
        ("¿Qué versión tuya en el amor que era auto-destructiva todavía tiene algo de presencia aunque intentes cambiarla?", 3),
        ("¿Cuánto del auto-sabotaje en el amor que tuviste en el pasado es la versión adulta de algo que aprendiste de chico?", 3),
        ("¿Qué patrón tuyo en el amor que viene de muy atrás si lograras romperlo esta vez cambiaría la historia?", 3),
        ("¿Cuánto de lo que no funcionó en relaciones pasadas fue genuinamente circunstancial y cuánto fue vos saboteándote?", 3),
        ("¿Qué parte de vos que boicotea el amor bueno todavía está activa aunque ya sepas que existe?", 3),
        ("¿Cuándo fue la primera vez que elegiste conscientemente no repetir un patrón de relaciones pasadas y lo lograste?", 3),
        ("¿Qué cambio en tu relación con vos mismo necesitás hacer para que el auto-sabotaje en el amor pierda fuerza?", 3),
    ],

    "personalidad": [
        ("¿Cuándo procrastinás más: cuando algo es difícil o cuando algo te importa mucho?", 1),
        ("¿Qué hábito de auto-sabotaje reconocés como más tuyo?", 1),
        ("¿Cómo te motivás cuando no tenés ganas de hacer algo que tenés que hacer?", 1),
        ("¿Qué zona de confort tuya querés salir pero seguís evitando?", 1),
        ("¿Cuándo fue la última vez que fuiste más disciplinado de lo que creías posible?", 1),
        ("¿Qué hábito que tiene alguien que admirás querés incorporar?", 1),
        ("¿Cómo sabés cuando estás procrastinando versus cuando genuinamente necesitás esperar?", 1),
        ("¿Qué cosa que hacés que te sabotea ya reconocés pero todavía no cambiás?", 1),
        ("¿Cuándo fue la última vez que rompiste un hábito malo?", 1),
        ("¿Qué tipo de esfuerzo te resulta más fácil sostener en el tiempo?", 1),
        ("¿Cómo manejás las rachas donde nada funciona y querés tirar todo?", 1),
        ("¿Qué excusa para no hacer algo usás más frecuentemente?", 1),
        ("¿Cuándo fue la última vez que empezaste algo y lo terminaste aunque fue difícil?", 1),
        ("¿Qué cosa de vos que reconocés como auto-sabotaje te resulta más difícil de cambiar?", 1),
        ("¿Cómo diferenciás entre descansar y evitar?", 1),
        ("¿Qué hábito positivo que instalaste y que costó mucho te da más orgullo?", 1),
        ("¿Cuándo fue la última vez que te sorprendiste a vos mismo por tu nivel de disciplina?", 1),
        ("¿Qué tipo de entorno te ayuda más a ser más disciplinado?", 1),
        ("¿Cómo reaccionás cuando algo que empezás no sale como esperabas?", 1),
        ("¿Qué cosa que postergás que no es urgente es sin embargo importante?", 1),
        ("¿Cuánto de tu procrastinación es miedo a fallar y cuánto es miedo a tener éxito?", 2),
        ("¿Qué patrón de auto-sabotaje tuyo tiene más historia y más peso en tu vida?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que te estabas saboteando a vos mismo de manera sistemática?", 2),
        ("¿Qué zona de confort tuya que rompiste fue el punto de partida de un cambio más importante del que esperabas?", 2),
        ("¿Cómo diferenciás entre el miedo sano que te protege y el miedo que te limita disfrazado de prudencia?", 2),
        ("¿Cuándo fue la primera vez que reconociste que un hábito tuyo era auto-destructivo y decidiste cambiarlo?", 2),
        ("¿Qué parte de vos que te sabotea seguís en alguna medida eligiendo porque también te da algo?", 2),
        ("¿Qué patrón de auto-sabotaje tuyo si lo eliminaras cambiaría más cosas de las que creés?", 3),
        ("¿Cuánto de lo que procrastinás está en realidad esperando que las condiciones sean perfectas aunque sepas que no lo van a ser?", 3),
        ("¿Qué versión tuya sin auto-sabotaje se vería diferente a la actual y qué te genera eso?", 3),
        ("¿Cuánto de quién sos está definido por los límites que vos mismo te pusiste?", 3),
        ("¿Qué necesitaría cambiar en vos para que el auto-sabotaje pierda el poder que tiene?", 3),
        ("¿Cuándo fue la última vez que hiciste algo completamente fuera de tu zona de confort y la experiencia cambió algo permanentemente?", 3),
        ("¿Qué versión de vos mismo que querés ser ya podría existir si no fuera por los hábitos que elegís mantener aunque no te sirvan?", 3),
    ],

    "miedos": [
        ("¿Le tenés miedo al fracaso o al éxito? ¿Cuál frena más?", 1),
        ("¿Qué cosa que postergás por miedo a hacerla mal merece ser intentada igual?", 1),
        ("¿Cuándo fue la última vez que el miedo te impidió hacer algo que querías?", 1),
        ("¿Qué miedo tuyo disfrazado de procrastinación reconocés?", 1),
        ("¿Le tenés miedo a comprometerte con algo y fallar?", 1),
        ("¿Cuándo fue la última vez que un miedo que tenías resultó ser mucho más manejable de lo que imaginabas?", 1),
        ("¿Qué cosa que evitás por miedo al juicio ajeno querés hacer igual?", 1),
        ("¿Cuándo fue la primera vez que el miedo al fracaso te costó algo que querías?", 1),
        ("¿Qué miedo a cambiar algo conocido te impide mejorar?", 1),
        ("¿Cómo manejás el miedo cuando estás a punto de salir de tu zona de confort?", 1),
        ("¿Qué miedo que tenés y que sabés que es irracional igual frena algo?", 1),
        ("¿Le tenés miedo a que si lo intentás y funciona ya no tenés excusas?", 1),
        ("¿Cuándo fue la última vez que el miedo a lo desconocido te paralizó más que cualquier obstáculo real?", 1),
        ("¿Qué miedo a cambiar de hábitos o de zona de confort tiene más fuerza de lo que debería?", 1),
        ("¿Cuándo fue la primera vez que reconociste que estabas procrastinando por miedo y no por falta de tiempo?", 1),
        ("¿Qué miedo a ser visto o juzgado te frena de hacer algo que querés?", 1),
        ("¿Cómo diferenciás entre el miedo que te informa y el que te paraliza?", 1),
        ("¿Qué miedo tuyo a quedarte sin excusas si algo funciona reconocés honestamente?", 1),
        ("¿Cuándo fue la última vez que hiciste algo a pesar del miedo y te alegró haberlo hecho?", 1),
        ("¿Qué miedo que postergás enfrentar tiene más costo cuanto más lo evitás?", 1),
        ("¿Cuánto del auto-sabotaje que tenés está gobernado por miedos que no terminás de reconocer como tales?", 2),
        ("¿Qué miedo a romper tu zona de confort tiene más consecuencias invisibles en tu vida?", 2),
        ("¿Cuándo fue la primera vez que entendiste que tu procrastinación era en realidad un miedo disfrazado?", 2),
        ("¿Qué miedo a lo que podrías ser si te comprometieras de verdad es en realidad el que más te frena?", 2),
        ("¿Cómo el miedo al cambio se disfraza en tu vida de prudencia, timing, o esperar el momento justo?", 2),
        ("¿Qué miedo tuyo que frenó algo importante en el pasado todavía tiene influencia aunque haya cambiado de forma?", 2),
        ("¿Cuánto de los hábitos que no cambiás son en realidad una manera de no tener que enfrentar lo que viene si cambian?", 2),
        ("¿Qué miedo profundo tuyo está detrás del patrón de auto-sabotaje que más te cuesta romper?", 3),
        ("¿Cuánto del miedo que tenés a cambiar es en realidad miedo a descubrir quién sos sin los hábitos que te definen?", 3),
        ("¿Qué miedo a fracasar en algo que te importa mucho es el que más te hace procrastinar exactamente en eso?", 3),
        ("¿Cuándo fue la última vez que un miedo que enfrentaste de verdad resultó en algo que no esperabas pero que necesitabas?", 3),
        ("¿Qué miedo tuyo más honesto si lo nombraras claramente dejaría de tener tanto poder?", 3),
        ("¿Cuánto de lo que llamas disciplina o falta de ella está en realidad gobernado por miedos que nunca nombraste?", 3),
        ("¿Qué necesitaría pasar para que pudieras hacer esa cosa que postergás con miedo y que sabés que necesitás hacer?", 3),
    ],

    "logros": [
        ("¿Cuándo fue la última vez que lograste algo que requirió mantener un hábito difícil en el tiempo?", 1),
        ("¿Qué logro tuyo fue principalmente el resultado de disciplina sostenida?", 1),
        ("¿Cuándo fue la primera vez que la disciplina te llevó a un logro que sin ella no hubiera sido posible?", 1),
        ("¿Qué hábito que instalaste que te costó mucho fue el punto de partida de un logro importante?", 1),
        ("¿Cuándo fue la última vez que rompiste tu zona de confort y de ahí salió algo valioso?", 1),
        ("¿Qué logro tuyo fue posible porque superaste el auto-sabotaje que te tenía frenado?", 1),
        ("¿Cuándo fue la primera vez que terminaste algo aunque tuviste muchas ganas de abandonarlo?", 1),
        ("¿Qué logro que postergaste mucho tiempo resultó ser más accesible de lo que creías?", 1),
        ("¿Cuándo fue la última vez que la perseverancia te llevó a algo que ya habías dado por perdido?", 1),
        ("¿Qué logro que conseguiste te enseñó algo sobre tu capacidad de ser disciplinado que no sabías?", 1),
        ("¿Cuándo fue la primera vez que reconociste que el esfuerzo sostenido en el tiempo era más poderoso que el talento?", 1),
        ("¿Qué logro tuyo que requirió salir de la zona de confort cambió permanentemente tu límite de lo que creés posible?", 1),
        ("¿Cuándo fue la última vez que un pequeño hábito que instalaste resultó tener un impacto mayor del que esperabas?", 1),
        ("¿Qué logro que conseguiste fue en realidad la suma de cosas pequeñas sostenidas en el tiempo?", 1),
        ("¿Cuándo fue la primera vez que lograste algo a pesar de haber querido abandonar muchas veces?", 1),
        ("¿Qué cosa que lograste te costó más en términos de disciplina y menos en términos de talento?", 1),
        ("¿Cuándo fue la última vez que una racha mala no pudo con la disciplina que habías instalado?", 1),
        ("¿Qué logro tuyo fue el resultado de romper un patrón de procrastinación que venías teniendo?", 1),
        ("¿Cuándo fue la primera vez que entendiste que los pequeños hábitos diarios importaban más que los esfuerzos esporádicos?", 1),
        ("¿Qué logro que tenés planeado ya podría estar en marcha si no fuera por la procrastinación?", 1),
        ("¿Cuánto de lo que lograste fue resultado de disciplina genuina y cuánto de presión externa?", 2),
        ("¿Qué logro que todavía no conseguiste ya podría existir si no te sabotearas de la manera en que lo hacés?", 2),
        ("¿Cuándo fue la primera vez que reconociste que tu auto-sabotaje te había costado un logro que podrías haber tenido?", 2),
        ("¿Qué patrón de procrastinación tuyo tiene el mayor potencial de costarte un logro futuro importante?", 2),
        ("¿Cuándo fue la primera vez que la constancia te demostró algo sobre vos mismo que el esfuerzo esporádico nunca pudo?", 2),
        ("¿Qué logro que querés alcanzar ya sabés que requiere romper un hábito que todavía no rompiste?", 2),
        ("¿Cuándo fue la última vez que algo que lograste requirió que te enfrentaras directamente con tu propio auto-sabotaje?", 2),
        ("¿Qué logro futuro tuyo está esperando que hagas exactamente lo que más evitás hacer?", 3),
        ("¿Cuánto de lo que querés lograr ya podría estar pasando si empezaras hoy con los hábitos que postergás instalar?", 3),
        ("¿Qué logro que ya casi alcanzaste y abandonaste merece un intento más honesto?", 3),
        ("¿Cuándo fue la última vez que el auto-sabotaje te costó algo que genuinamente querías y qué cambió después?", 3),
        ("¿Qué versión tuya como logrador que querés ser requiere exactamente qué cambio de hábitos que todavía no hiciste?", 3),
        ("¿Cuánto del talento que tenés está siendo desperdiciado por hábitos que sabés que no te sirven?", 3),
        ("¿Qué logro que parece lejano ya podría estar en camino si te comprometieras con un hábito pequeño y lo sostuvieras?", 3),
    ],

    "sinFiltro": [
        ("¿A qué le tenés más miedo: a intentarlo y fracasar o a no intentarlo y preguntarte siempre?", 1),
        ("¿Qué cosa que sabés que te hace bien seguís sin hacer porque preferís estar cómodo?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente impulsivo que resultó bien?", 1),
        ("¿Qué hábito que tenés que sería obvio eliminarlo seguís igual porque es cómodo?", 1),
        ("¿Cuándo fue la última vez que te mandaste algo sin pensar demasiado y te salió mejor que si lo planificabas?", 1),
        ("¿Qué cosa que hacés para auto-sabotearte que sabés perfectamente que lo estás haciendo seguís igual?", 1),
        ("¿Cuándo fue la última vez que rompiste tu rutina de manera radical y cómo te fue?", 1),
        ("¿Qué cosa que te da placer a corto plazo te cuesta a largo plazo y seguís eligiéndola igual?", 1),
        ("¿Cuándo fue la última vez que dijiste que sí a algo que te daba miedo y resultó ser lo mejor que hiciste?", 1),
        ("¿Qué excusa que usás más para no hacer algo sabés que es mentira pero la creés igual?", 1),
        ("¿Cuándo fue la última vez que hiciste algo sin pensarlo demasiado que cambió algo?", 1),
        ("¿Qué cosa que te auto-sabotea reconocés completamente pero elegís no cambiar porque algo te da?", 1),
        ("¿Cuándo fue la última vez que hiciste algo sin red de seguridad y valió la pena?", 1),
        ("¿Qué cosa que sabés que tenés que hacer seguís sin hacer aunque sepas que cada día que pasa tiene un costo?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente fuera de tu perfil y te sorprendiste?", 1),
        ("¿Qué hábito que tenés que es una pérdida de tiempo seguís eligiendo porque te hace sentir que hacés algo?", 1),
        ("¿Cuándo fue la última vez que te permitiste ser completamente imperfecto y avanzaste igual?", 1),
        ("¿Qué cosa que postergas hace tiempo si la haces hoy cambia algo que mañana podría ser tarde para cambiar?", 1),
        ("¿Cuándo fue la última vez que el miedo al ridículo te frenó y te arrepentiste de haberle dado tanto poder?", 1),
        ("¿Qué cosa que te genera adrenalina hacer seguís evitando porque la comodidad gana siempre?", 1),
        ("¿Cuánto del auto-sabotaje que tenés es en realidad miedo a ser responsable del resultado?", 2),
        ("¿Qué parte de vos que procrastina seguís eligiendo aunque sepa perfectamente lo que te está costando?", 2),
        ("¿Cuándo fue la última vez que te auto-saboteaste en algo que realmente te importaba y qué pasó después?", 2),
        ("¿Qué cosa que evitás hacer porque requiere esfuerzo real te gustaría poder decir que hiciste?", 2),
        ("¿Cuánto de lo que llamás cansancio o falta de tiempo es en realidad evitación disfrazada?", 2),
        ("¿Qué hábito que tenés que es claramente auto-destructivo seguís eligiendo porque también te protege de algo?", 2),
        ("¿Cuándo fue la última vez que hiciste algo completamente sin red y te salió mejor de lo que esperabas?", 2),
        ("¿Si supieras que nadie te va a juzgar por fallar qué intentarías que hoy no te animás a intentar?", 3),
        ("¿Cuánto de lo que no hacés es porque genuinamente no podés y cuánto es porque elegís la comodidad?", 3),
        ("¿Qué necesitaría pasar para que hagas esa cosa que postergás hace tiempo y que sabés que necesitás hacer?", 3),
        ("¿Cuándo fue la última vez que te comprometiste de verdad con algo y lo sostuviste aunque fue difícil?", 3),
        ("¿Qué versión de vos sin auto-sabotaje se vería diferente a la actual y qué te genera imaginarla?", 3),
        ("¿Cuánto de lo que querés genuinamente ya podría estar en tu vida si no fuera por los hábitos que elegís mantener?", 3),
        ("¿Qué excusa que usás para no hacer algo que querés si la quitas deja expuesto qué miedo real?", 3),
    ],
}


def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]


def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS30:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS30[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")


if __name__ == "__main__":
    main()
