#!/usr/bin/env python3
"""Batch 28 - childhood dreams vs. adult reality, nostalgia, regret, wonder, what changed."""
import json

ADDITIONS28 = {
    "infancia": [
        ("¿Qué querías ser de grande cuando eras chico y qué pasó con ese sueño?", 1),
        ("¿Cuál era tu juguete favorito y qué te enseñó sobre lo que te importa?", 1),
        ("¿Qué programa de televisión o película de tu infancia te marcó más?", 1),
        ("¿Qué comida de tu infancia te genera más nostalgia hoy?", 1),
        ("¿Recuerdo algún verano de tu infancia que fue perfecto?", 1),
        ("¿Qué habilidad aprendiste de chico que hoy casi no usás?", 1),
        ("¿Cuál era la ilusión más grande que tenías sobre la vida adulta que resultó completamente falsa?", 1),
        ("¿Qué cosa de la infancia de otros chicos te generaba envidia?", 1),
        ("¿Qué tradición familiar de tu infancia desapareció con el tiempo?", 1),
        ("¿Cuál fue el primer libro que te atrapó de verdad?", 1),
        ("¿Qué deporte o actividad abandonaste de chico que a veces deseás haber seguido?", 1),
        ("¿Qué objeto de tu infancia guardarías si pudieras tenerlo hoy?", 1),
        ("¿Qué canción de tu infancia todavía te emociona al escucharla?", 1),
        ("¿Cuál era tu lugar secreto preferido siendo chico?", 1),
        ("¿Qué cosa creías de chico sobre los adultos que resultó totalmente equivocada?", 1),
        ("¿Qué apodo tenías de chico y qué te parecía en ese momento?", 1),
        ("¿Cuál fue la primera vez que sentiste que el mundo adulto era injusto?", 1),
        ("¿Qué cosa de tu infancia te genera nostalgia pero que honestamente fue bastante difícil también?", 1),
        ("¿Qué clase de héroe o personaje querías ser de chico?", 1),
        ("¿Cuál era el mayor miedo que tenías de chico que hoy te parece simpático?", 1),
        ("¿Qué momento de asombro puro de tu infancia todavía podés evocar con claridad?", 1),
        ("¿Qué parte de vos de chico sentís que perdiste al crecer y cuánto te importa recuperarla?", 2),
        ("¿Cuál fue el momento exacto en que sentiste que la infancia había terminado?", 2),
        ("¿Qué expectativa de la vida adulta que tenías de chico cumpliste y cuál te parece ridícula hoy?", 2),
        ("¿Hay algún sueño de infancia que silenciosamente seguís persiguiendo aunque no lo admitas abiertamente?", 2),
        ("¿Qué parte de tu carácter actual viene directamente de algo que viviste antes de los diez años?", 2),
        ("¿Qué cosa de tu infancia preferirías que no hubiera pasado y qué cosa no cambiarías por nada?", 2),
        ("¿Hay alguna herida de infancia que entendiste recién de adulto y que cambió cómo te ves a vos mismo?", 2),
        ("¿Qué versión de vos de chico te daría más orgullo y cuál te daría más vergüenza ver?", 2),
        ("¿Qué sueño de infancia traicionaste con más culpa al convertirte en adulto?", 3),
        ("¿Qué parte del asombro que tenías de chico lograste preservar y cuánto te costó?", 3),
        ("¿Qué herida de infancia todavía aparece disfrazada en tus vínculos adultos?", 3),
        ("¿Si pudieras hablarle al vos de diez años, qué le dirías que no ibas a poder protegerlo de?", 3),
        ("¿Qué cosa de la vida adulta que más temías de chico terminó siendo exactamente tan difícil como imaginabas?", 3),
        ("¿Qué versión de adulto esperabas ser que no llegaste a ser y todavía duele un poco?", 3),
        ("¿Qué asombro de la infancia tuya querés recuperar antes de que sea tarde?", 3),
    ],

    "futuro": [
        ("¿Qué sueño de infancia todavía tiene algo de vigencia en el futuro que te imaginás?", 1),
        ("¿Qué cosa que perdiste al crecer querés recuperar en el futuro?", 1),
        ("¿En qué momento de tu vida futura te gustaría recuperar la sensación de asombro de la infancia?", 1),
        ("¿Qué ilusiones sobre el futuro que tenías de chico resultaron exactas?", 1),
        ("¿Cómo te imaginás siendo abuelo o figura mayor en la vida de niños?", 1),
        ("¿Qué cosas del presente que hoy das por sentadas probablemente vayas a extrañar en el futuro?", 1),
        ("¿Qué versión de adulto mayor querés ser que no se parece a ningún adulto que hayas conocido?", 1),
        ("¿Hay algo que de chico jurabas que nunca ibas a hacer de grande y que ya estás haciendo?", 1),
        ("¿Qué cosa de la vida adulta que imaginabas de chico todavía no llegó y no perdiste la esperanza?", 1),
        ("¿Qué legado querés dejar que el vos de diez años aprobaría sin dudarlo?", 1),
        ("¿Cuánto del futuro que construís hoy tiene que ver con cumplirle algo al vos del pasado?", 1),
        ("¿Qué momento de tu futuro te genera la misma ilusión que los sueños que tenías de chico?", 1),
        ("¿Qué parte de tu vida futura ideal es en realidad una versión adulta de algo que soñabas de chico?", 1),
        ("¿Qué versión de vos mismo del futuro sería la que al chico de antes le daría más envidia?", 1),
        ("¿Cómo te gustaría sorprenderte a vos mismo en el futuro de la misma manera que te sorprendías de chico?", 1),
        ("¿Qué cosas que hoy postergás sabés que el vos del futuro te va a agradecer o reprochar?", 1),
        ("¿Qué arrepentimiento querés evitar en el futuro que ya podés ver venir?", 1),
        ("¿Cuánto del futuro que planeás es lo que realmente querés versus lo que aprendiste que se supone que querés?", 1),
        ("¿En qué querés ser mejor que tus padres o figuras adultas de referencia?", 1),
        ("¿Qué sueño que dejaste ir de chico merece una segunda oportunidad en tu vida adulta?", 1),
        ("¿Cuánto de lo que hacés hoy está construido sobre lo que genuinamente querías de chico versus lo que la vida fue pidiendo?", 2),
        ("¿Qué versión de tu futuro estarías construyendo si el vos de diez años fuera el que tomara todas las decisiones?", 2),
        ("¿Qué patrón que arrastrás del pasado tiene más poder sobre tu futuro del que te gustaría admitir?", 2),
        ("¿Cuál es la diferencia más importante entre el adulto que imaginabas ser y el que sos hoy?", 2),
        ("¿Qué cosa que de chico esperabas con ansiedad de la vida adulta resultó ser exactamente igual que la imaginabas pero de maneras que no esperabas?", 2),
        ("¿Qué expectativa del vos del pasado todavía está ejerciendo presión sobre tu futuro?", 2),
        ("¿Qué regret del pasado tiene más peso en cómo construís tu futuro hoy?", 2),
        ("¿Qué futuro te gustaría construir que sea una reivindicación de todo lo que el vos de chico no pudo tener?", 3),
        ("¿Cuánto del futuro que querés es tuyo genuinamente y cuánto es una respuesta a heridas del pasado?", 3),
        ("¿Si supieras que el vos del futuro va a mirar atrás al presente, qué querés que vea?", 3),
        ("¿Qué versión de vos mismo del futuro te da más miedo: la que se convirtió en lo que temías o la que nunca llegó a ser lo que soñabas?", 3),
        ("¿Qué sueño de infancia que abandonaste merece una última oportunidad honesta?", 3),
        ("¿Cómo reconciliás lo que soñabas ser con lo que sos de manera que no sea una derrota?", 3),
        ("¿Qué parte del futuro que construís hoy es para reparar algo que el pasado rompió?", 3),
    ],

    "amor": [
        ("¿Cómo era el amor que imaginabas de chico y en qué se parece o diferencia al que viviste?", 1),
        ("¿Cuál fue tu primer crush de infancia y qué te enseñó sobre lo que te atrae?", 1),
        ("¿Qué idea del amor romántico de las películas o cuentos de tu infancia todavía influye en vos?", 1),
        ("¿Qué cosa del amor que viviste te genera nostalgia aunque la relación no haya durado?", 1),
        ("¿Hay algún momento romántico del pasado que idealizás más de lo que fue en realidad?", 1),
        ("¿Qué parte del amor que experimentaste siendo joven que no repetirías y cuál que sí?", 1),
        ("¿Qué cosa de las relaciones actuales extrañás de la manera en que amabas cuando eras más joven?", 1),
        ("¿Qué expectativa del amor que tenías a los quince años todavía llevás sin darte cuenta?", 1),
        ("¿Qué versión del amor que soñabas de chico todavía te parece válida?", 1),
        ("¿Cuándo fue la primera vez que sentiste que el amor era complicado?", 1),
        ("¿Qué aprendiste sobre el amor en las relaciones de tu infancia que todavía define cómo amás?", 1),
        ("¿Qué cosa de la manera en que te enamoraste por primera vez todavía te asombra?", 1),
        ("¿Qué error amoroso del pasado lamentás con más claridad?", 1),
        ("¿Qué cosa del amor que tenías antes perdiste y te gustaría recuperar?", 1),
        ("¿Cuánto del amor que buscás hoy tiene que ver con algo que te faltó de chico?", 1),
        ("¿Qué historia de amor que viste en tu familia de chico todavía te sirve como referencia?", 1),
        ("¿Qué versión de pareja que soñabas de chico resultó ser más o menos exacta?", 1),
        ("¿Hay algún amor del pasado que idealizaste tanto que ya no podés verlo con claridad?", 1),
        ("¿Qué cosa del amor de antes querés recuperar en el amor del futuro?", 1),
        ("¿Qué parte de la ternura que tenías al amar cuando eras joven querés que siga estando?", 1),
        ("¿Cuánto de cómo amás hoy es una respuesta a algo que no funcionó en el pasado?", 2),
        ("¿Qué imagen del amor que te enseñaron de chico tuvo que ser desarmada para poder amar de verdad?", 2),
        ("¿Hay alguna historia de amor de tu infancia o adolescencia que nunca terminaste de procesar?", 2),
        ("¿Qué regret amoroso del pasado todavía aparece en tus relaciones actuales sin que lo invites?", 2),
        ("¿Qué parte del amor que creías que tenías de chico resultó ser otra cosa cuando lo revisás de adulto?", 2),
        ("¿Cuánto de la persona que sos en el amor es una versión corregida de algo que salió mal antes?", 2),
        ("¿Qué cosa del amor que viviste de joven que en su momento no valoraste y ahora sí?", 2),
        ("¿Qué amor del pasado te dejó una marca que todavía define qué buscás o qué evitás?", 3),
        ("¿Qué versión del amor que esperabas de chico todavía no encontraste y qué hacés con eso?", 3),
        ("¿Cuánto del amor que das hoy está construido sobre lo que necesitabas y no tuviste?", 3),
        ("¿Qué aprendiste sobre el amor que ojalá hubieras sabido antes y que cambia cómo lo ves hoy?", 3),
        ("¿Qué imagen de amor romántico que tenías de chico resultó ser la más dañina para tus relaciones adultas?", 3),
        ("¿Cuánto del amor que buscás es para reparar algo del pasado y cuánto es genuinamente tuyo?", 3),
        ("¿Qué historia de amor del pasado tuyo merece ser revisitada con ojos más compasivos?", 3),
    ],

    "familia": [
        ("¿Qué imagen de familia que tenías de chico resultó ser más complicada al crecer?", 1),
        ("¿Qué tradición familiar de tu infancia desapareció y la extrañás?", 1),
        ("¿Qué cosa de tu familia que odiabas de chico hoy valorás o entendés diferente?", 1),
        ("¿Qué sueño que tenías sobre tu propia familia adulta ya cumpliste y cuál sigue pendiente?", 1),
        ("¿Cuál fue el momento en que dejaste de ver a tus padres como héroes o figuras perfectas?", 1),
        ("¿Qué cosa de tu infancia familiar que dabas por sentada resultó ser un privilegio?", 1),
        ("¿Qué cosa de la familia que tenías de chico querés replicar y qué querés cambiar completamente?", 1),
        ("¿Qué apodo familiar de infancia todavía te define aunque no te lo digan?", 1),
        ("¿Cuándo fue la primera vez que sentiste que tu familia era diferente a las de los demás?", 1),
        ("¿Qué cosa de tu infancia familiar te genera nostalgia aunque también fue difícil?", 1),
        ("¿Qué momento familiar de tu infancia revisitás mentalmente con más frecuencia?", 1),
        ("¿Qué cosa que hacía tu familia de chico adoptaste sin darte cuenta?", 1),
        ("¿Qué imagen de familia ideal que tenías de chico resultó ser completamente irreal?", 1),
        ("¿Cuánto de quién sos hoy es una respuesta directa a algo de tu familia de infancia?", 1),
        ("¿Qué herramienta emocional que aprendiste en tu familia de chico todavía te sirve?", 1),
        ("¿Qué cosa de la vida familiar que imaginabas de adulto se parece más a lo que tenés?", 1),
        ("¿Qué personaje de tu familia de infancia extrañás con más intensidad?", 1),
        ("¿Qué cosa de tu infancia familiar que en su momento no parecía especial hoy sabés que era única?", 1),
        ("¿Qué error de tus padres entendiste de adulto y cómo cambia eso la historia?", 1),
        ("¿Qué parte del vínculo familiar que tenías de chico querés que esté presente en la familia que construís o construiste?", 1),
        ("¿Qué herida familiar de tu infancia todavía aparece en cómo te relacionás con los que amás?", 2),
        ("¿Qué cosa de tu familia de chico que rechazabas con más fuerza hoy ves en vos mismo?", 2),
        ("¿Cuánto de cómo construís tu familia actual es una respuesta a algo que faltó en la familia de infancia?", 2),
        ("¿Qué cosa de tu familia de chico que creías normal descubriste más tarde que no lo era?", 2),
        ("¿Qué conversación con alguien de tu familia de infancia que ya no está podés imaginar con claridad?", 2),
        ("¿Qué dinámica familiar de tu infancia todavía se repite en tu vida adulta aunque no quieras?", 2),
        ("¿Cuándo fue el momento en que empezaste a ver a tus padres como personas y no solo como roles?", 2),
        ("¿Qué cosa de tu familia de infancia que más te marcó es la que más te cuesta hablar?", 3),
        ("¿Cuánto de la familia que construís o querés construir es para reparar algo de la familia en que creciste?", 3),
        ("¿Qué patrón familiar que se repitió en generaciones previas tuyas querés ser el que lo rompa?", 3),
        ("¿Qué aprendiste sobre tu familia al convertirte en adulto que cambió completamente cómo la ves?", 3),
        ("¿Qué parte de tu historia familiar todavía no terminaste de procesar y cómo aparece en tu vida?", 3),
        ("¿Qué familia soñabas de chico que hoy entendés que era una respuesta a lo que te faltaba?", 3),
        ("¿Si pudieras cambiar algo de tu familia de infancia, qué cambiarías y qué no cambiarías aunque pudiera?", 3),
    ],

    "amistades": [
        ("¿Cuál fue tu mejor amigo de infancia y qué pasó con esa amistad?", 1),
        ("¿Qué amistad de la infancia o adolescencia extrañás con más intensidad?", 1),
        ("¿Qué cosa de las amistades de infancia que ya no tenés te gustaría recuperar?", 1),
        ("¿Cuál fue la primera traición de un amigo que te marcó?", 1),
        ("¿Cómo era la amistad de chico diferente a la amistad adulta en términos de profundidad?", 1),
        ("¿Qué amigo de infancia dejaste ir y todavía te preguntás qué fue de él o ella?", 1),
        ("¿Qué pandilla o grupo de amigos de chico fue el más importante de tu vida?", 1),
        ("¿Cuál fue el momento de amistad de tu infancia que más te marcó positivamente?", 1),
        ("¿Qué cosa hacías con tus amigos de infancia que ya no hacés y extrañás?", 1),
        ("¿Cómo elegías a tus amigos de chico versus cómo los elegís ahora?", 1),
        ("¿Qué amistad de infancia que duró te dice algo sobre lo que más valorás en los vínculos?", 1),
        ("¿Cuál fue el primer momento en que una amistad te decepcionó?", 1),
        ("¿Qué tipo de amigo eras de chico y en qué se diferencia del que sos hoy?", 1),
        ("¿Qué amistad de la infancia te gustaría haber cuidado más?", 1),
        ("¿Cuándo fue la primera vez que una amistad se terminó y lo sufriste?", 1),
        ("¿Qué cosa de las amistades de tu infancia te genera más nostalgia?", 1),
        ("¿Qué amistad de chico te cambió de alguna manera fundamental?", 1),
        ("¿Qué regla no escrita de amistad de chico todavía seguís?", 1),
        ("¿Cómo era diferente el sentido de pertenencia a un grupo de amigos de chico al de ahora?", 1),
        ("¿Qué cosa de las amistades de tu infancia que dabas por sentada resultó ser especial?", 1),
        ("¿Cuánto de cómo buscás amigos hoy está influenciado por lo que tuviste o no tuviste de chico?", 2),
        ("¿Qué amistad del pasado que perdiste todavía ocupa espacio en tu vida de maneras que no esperabas?", 2),
        ("¿Qué patrón en tus amistades de infancia se repite en tus amistades adultas aunque no quieras?", 2),
        ("¿Qué amigo de chico fue el primero en ver algo en vos que vos no veías?", 2),
        ("¿Qué herida de una amistad de infancia todavía afecta cómo te vinculás hoy?", 2),
        ("¿Qué cosa aprendiste sobre la lealtad en tus amistades de chico que todavía llevás?", 2),
        ("¿Hay alguna amistad de infancia que terminó mal y que nunca llegaste a cerrar?", 2),
        ("¿Qué amistad de infancia te arrepentís de haber dejado ir y qué harías diferente?", 3),
        ("¿Cuánto de cómo te relacionás con amigos hoy es una respuesta a algo que pasó en la infancia?", 3),
        ("¿Qué versión tuya como amigo de chico querés recuperar y qué versión preferís dejar atrás?", 3),
        ("¿Qué le dirías hoy a algún amigo de infancia que se fue sin que le hayas dicho algo importante?", 3),
        ("¿Qué amistad del pasado que idealizás al revisarla fue menos perfecta de lo que recordás?", 3),
        ("¿Cuándo fue el momento en que entendiste que mantener amistades de adulto requería un esfuerzo diferente?", 3),
        ("¿Qué cosa de la inocencia de las amistades de infancia querés proteger en tus vínculos actuales?", 3),
    ],

    "exs": [
        ("¿Cuál fue la primera relación que en su momento creíste que duraría para siempre?", 1),
        ("¿Qué cosa de una relación pasada extrañás con más honestidad, sin romanticizarla?", 1),
        ("¿Hay alguna ex relación que en el momento fue dolorosa pero que hoy ves como necesaria?", 1),
        ("¿Qué versión de vos mismo en una relación pasada ya no reconocés del todo?", 1),
        ("¿Cuál fue la primera ruptura que te cambió de manera permanente?", 1),
        ("¿Qué cosa de una relación pasada dabas por sentada y que hoy extrañás?", 1),
        ("¿Cuándo fue la primera vez que el fin de una relación te enseñó algo sobre vos que no sabías?", 1),
        ("¿Hay alguna relación del pasado que idealizás más de lo que fue realmente?", 1),
        ("¿Qué cosa hiciste en una relación pasada que ahora entendés mejor?", 1),
        ("¿Qué relación pasada que parecía un fracaso resultó ser en retrospectiva un aprendizaje enorme?", 1),
        ("¿Qué versión de vos mismo que existió en una relación pasada lamentás haber perdido?", 1),
        ("¿Qué cosa de una relación del pasado que odiabas en el momento hoy en cierta manera extrañás?", 1),
        ("¿Cuál fue la relación más larga que tuviste y qué parte de ella llevás con vos?", 1),
        ("¿Qué relación del pasado terminó de la manera más inesperada?", 1),
        ("¿Qué patrón que se repitió en varias relaciones pasadas tuyas ya reconocés con claridad?", 1),
        ("¿Cuándo fue el primer momento en que entendiste que una relación ya no tenía vuelta atrás?", 1),
        ("¿Qué cosa de alguna relación pasada que no valoraste en el momento ahora sí valorás?", 1),
        ("¿Qué relación del pasado que terminó mal cerró eventualmente de buena manera?", 1),
        ("¿Qué imagen del amor romántico que tenías antes de tu primera relación seria cambió después de vivirla?", 1),
        ("¿Qué relación del pasado que en su momento parecía todo hoy te parece diferente?", 1),
        ("¿Cuánto de lo que buscás en el amor hoy es una respuesta a algo que no funcionó en relaciones anteriores?", 2),
        ("¿Qué versión tuya en una relación pasada que te avergüenza ahora entendés con más compasión?", 2),
        ("¿Cuál es el aprendizaje más caro que pagaste en una relación pasada?", 2),
        ("¿Qué relación del pasado que parecía un error absoluto cambió algo en vos para mejor?", 2),
        ("¿Qué cosa de vos mismo descubriste en una relación que terminó y que no hubieras descubierto de otra manera?", 2),
        ("¿Hay alguna ex pareja a quien le debés algo que nunca le diste: una disculpa, una explicación, un cierre?", 2),
        ("¿Cuánto del amor que sos capaz de dar hoy fue moldeado por el amor que recibiste o no recibiste en el pasado?", 2),
        ("¿Qué relación del pasado te cambió tan profundamente que dividís tu vida entre antes y después de ella?", 3),
        ("¿Cuánto de quién sos en el amor hoy es una versión corregida de quien fuiste en una relación que salió mal?", 3),
        ("¿Qué aprendiste sobre vos mismo en la relación más difícil que tuviste que no puedas aprender de otra manera?", 3),
        ("¿Qué relación del pasado idealizás tanto que te impide ver lo que tenés o podés tener hoy?", 3),
        ("¿Cuánto de lo que no pudiste dar o recibir en relaciones pasadas todavía te pesa en las actuales?", 3),
        ("¿Qué versión del amor del pasado tuyo que en el momento fue real querés honrar sin repetir?", 3),
        ("¿Si pudieras revisar la historia de alguna relación pasada con los ojos de hoy, qué verías diferente?", 3),
    ],

    "personalidad": [
        ("¿En qué aspecto de tu personalidad notás más diferencia entre el vos de chico y el de ahora?", 1),
        ("¿Qué rasgo de carácter que tenías de chico perdiste y a veces extrañás?", 1),
        ("¿Qué cosa de vos de chico que odiabas ahora entendés que era una fortaleza?", 1),
        ("¿Cuándo fue el primer momento en que te diste cuenta de que eras diferente a los demás?", 1),
        ("¿Qué sueño que tenías de chico sobre quién ibas a ser dejó más huella en quien sos?", 1),
        ("¿Qué parte de tu personalidad que te parecía normal de chico resultó ser bastante particular?", 1),
        ("¿Qué cosa de vos que cambió al crecer fue un alivio y cuál fue una pérdida?", 1),
        ("¿Cuál fue la primera vez que alguien te describió de una manera que no reconocías pero resultó ser verdad?", 1),
        ("¿Qué aspecto de tu carácter que todavía tenés hoy viene directamente de tu infancia?", 1),
        ("¿Qué rasgo tuyo de chico que fue criticado hoy valorás en vos mismo?", 1),
        ("¿Cuándo fue la primera vez que te sorprendiste a vos mismo haciendo algo que no creías capaz?", 1),
        ("¿Qué versión de vos mismo extrañás más: la de los quince, los veinte, los veinticinco?", 1),
        ("¿Qué cosa de tu personalidad de chico que fue un escudo hoy ya no necesitás pero todavía usás?", 1),
        ("¿Cuánto de vos es el resultado de elegir conscientemente versus repetir lo que aprendiste?", 1),
        ("¿Qué cosa de vos mismo que creías permanente cambió más de lo que esperabas?", 1),
        ("¿Qué característica tuya que nunca pensaste que fuera especial resultó ser de las más valiosas?", 1),
        ("¿En qué momento de tu vida sentiste más claramente quién eras?", 1),
        ("¿Qué aspecto de tu carácter que tenías de chico te costó más trabajo mantener de adulto?", 1),
        ("¿Qué cosa de vos mismo que cambiaste conscientemente te da más orgullo?", 1),
        ("¿Qué parte de vos que dabas por sentada de chico tuvo que ser construida de adulto?", 1),
        ("¿Qué versión de vos mismo del pasado que rechazabas hoy mirás con más compasión?", 2),
        ("¿Cuánto de quien sos hoy es el resultado de reaccionar a algo que pasó en el pasado?", 2),
        ("¿Qué cosa de vos mismo de chico que cambió fue una pérdida real y qué fue una ganancia real?", 2),
        ("¿Qué patrón de comportamiento tuyo que viene de lejos todavía te cuesta cambiar aunque quieras?", 2),
        ("¿Cuándo fue la primera vez que entendiste que algo de vos que creías un defecto era en realidad parte de lo que te hace vos?", 2),
        ("¿Qué parte de tu identidad que construiste con esfuerzo te resulta hoy más frágil de lo que esperabas?", 2),
        ("¿Qué cosa de vos mismo que nunca te gustó de chico terminó siendo lo que más te define de manera positiva?", 2),
        ("¿Qué parte de vos mismo que perdiste al crecer querés recuperar y qué estarías dispuesto a hacer para recuperarla?", 3),
        ("¿Cuánto de quien sos hoy es una respuesta a algo del pasado versus una elección genuina del presente?", 3),
        ("¿Qué versión de vos mismo que todavía no sos pero que querés ser requiere dejar ir qué parte de quien sos hoy?", 3),
        ("¿Qué cosa de tu personalidad que creías fija de chico resultó ser mucho más moldeable de lo que pensabas?", 3),
        ("¿Cuánto del asombro que tenías de chico sobre el mundo todavía podés acceder y qué lo bloquea?", 3),
        ("¿Qué versión de vos mismo del pasado que ya no sos te ayudó a ser quien sos hoy sin que lo supieras en el momento?", 3),
        ("¿Qué parte de tu carácter que te costó mucho cambiar cambiaste y todavía no terminás de creer que cambió?", 3),
    ],

    "miedos": [
        ("¿Qué miedo de infancia que tenías que creías que desaparecería al crecer todavía está?", 1),
        ("¿Cuál fue el primer miedo de adulto que te tomó por sorpresa?", 1),
        ("¿Qué cosa que de chico creías que iba a asustarte menos de grande en realidad te asusta más?", 1),
        ("¿Qué miedo que tenías de chico desapareció y no extrañás en absoluto?", 1),
        ("¿Cuándo fue la primera vez que sentiste un miedo que venía de entender algo real sobre el mundo?", 1),
        ("¿Qué miedo de adulto que tenés te parece que el vos de chico no hubiera entendido?", 1),
        ("¿Qué miedo de infancia que en su momento parecía irracional tenía algo de verdadero?", 1),
        ("¿Cómo cambiaron tus miedos desde la infancia hasta hoy?", 1),
        ("¿Qué miedo nuevo que apareció en tu vida adulta no esperabas?", 1),
        ("¿Cuál fue la primera vez que te diste cuenta de que los adultos también tenían miedo?", 1),
        ("¿Qué cosa que de chico creías que de grande ya no ibas a temer todavía te preocupa?", 1),
        ("¿Qué miedo de tu infancia que se fue lo dejaste ir o simplemente cambió de forma?", 1),
        ("¿Qué miedo de chico que era ridículo te enseñó algo real sobre vos?", 1),
        ("¿Cuándo fue la primera vez que un miedo tuyo resultó ser completamente justificado?", 1),
        ("¿Qué miedo tenés hoy que tiene raíces directas en algo que viviste de chico?", 1),
        ("¿Qué miedo de chico que superaste fue el que más te costó?", 1),
        ("¿Cuánto de cómo manejás el miedo hoy lo aprendiste de tu familia de infancia?", 1),
        ("¿Qué miedo de adulto que tenés te parece más difícil de admitir que tus miedos de chico?", 1),
        ("¿Qué cosa que temías de chico resultó ser exactamente tan mala como imaginabas?", 1),
        ("¿Cuál fue el miedo de infancia que más te costó admitir frente a otros?", 1),
        ("¿Qué miedo del pasado que superaste fue en realidad una preparación para algo más difícil?", 2),
        ("¿Cuánto de los miedos que tenés hoy son versiones adultas de miedos que tenías de chico?", 2),
        ("¿Qué miedo que tenés ahora viene de algo que te enseñaron a temer que en realidad no merecía tanto?", 2),
        ("¿Qué miedo de infancia que cargaste mucho tiempo resultó ser más sobre el contexto que sobre vos?", 2),
        ("¿Qué miedo que todavía tenés querés superar y qué te lo impide?", 2),
        ("¿Cuánto de lo que hoy evitás tiene raíces en un miedo de infancia que nunca nombraste?", 2),
        ("¿Qué miedo tuyo que era un secreto de chico resultó ser compartido por más personas de lo que creías?", 2),
        ("¿Qué miedo de chico que nunca superaste define de maneras silenciosas cómo vivís hoy?", 3),
        ("¿Cuánto de las decisiones que tomás hoy están gobernadas por miedos del pasado disfrazados de prudencia?", 3),
        ("¿Qué miedo de infancia que cargaste muchos años merece ser examinado de nuevo con ojos adultos?", 3),
        ("¿Cuánto de lo que protegés hoy es en realidad el niño de antes protegiéndose de algo que ya pasó?", 3),
        ("¿Qué miedo tuyo más honesto todavía tiene la forma exacta que tenía cuando eras chico?", 3),
        ("¿Qué miedo que de chico creías que desaparecería simplemente con crecer todavía está esperando que lo veas?", 3),
        ("¿Qué necesitaría pasar para que puedas dejar ir el miedo que más peso tiene de tu historia?", 3),
    ],

    "logros": [
        ("¿Cuál fue el primer logro que recordás de tu infancia del que te sentiste genuinamente orgulloso?", 1),
        ("¿Qué habilidad que desarrollaste de chico fue el punto de partida de un logro adulto?", 1),
        ("¿Cuándo fue la primera vez que lograste algo que alguien te dijo que no podías hacer?", 1),
        ("¿Qué logro que soñabas de chico que ibas a tener de grande ya cumpliste?", 1),
        ("¿Qué logro de tu adolescencia que en el momento no parecía importante resultó ser clave?", 1),
        ("¿Cuál fue el primer logro adulto que te hizo pensar que el vos de chico se sentiría orgulloso?", 1),
        ("¿Qué cosa que empezaste de chico y abandonaste después te arrepentís más de no haber seguido?", 1),
        ("¿Qué logro del pasado que ya no recordás tanto fue el que más te costó en su momento?", 1),
        ("¿Cuál fue el primer momento en que alguien reconoció algo en vos que vos todavía no reconocías?", 1),
        ("¿Qué logro de tu infancia que era pequeño hoy entendés como grande?", 1),
        ("¿Cuándo fue la primera vez que sentiste que podías lograr algo que parecía fuera de tu alcance?", 1),
        ("¿Qué logro de tu pasado fue el resultado de algo que de chico parecía una debilidad?", 1),
        ("¿Cuál fue el logro que más tiempo tardaste en reconocer como tal?", 1),
        ("¿Qué cosa que lograste de joven que era un sueño perdió el brillo con el tiempo?", 1),
        ("¿Qué logro del pasado que parecía enorme hoy lo ves con más perspectiva y te alegra igual?", 1),
        ("¿Cuál fue el primer fracaso que se convirtió en la base de un logro posterior?", 1),
        ("¿Qué logro que tenías planeado de chico todavía está pendiente y qué pasa con eso?", 1),
        ("¿Qué cosa que lograste de adulto tiene raíces directas en algo que empezaste de chico?", 1),
        ("¿Cuándo fue la primera vez que un logro tuyo fue reconocido públicamente y cómo lo viviste?", 1),
        ("¿Qué logro de tu infancia o adolescencia te da más orgullo cuando lo mirás en perspectiva?", 1),
        ("¿Cuánto de lo que lograste hasta ahora era lo que soñabas de chico y cuánto cambió el camino?", 2),
        ("¿Qué logro del pasado que costó mucho todavía te da la confianza de que podés con lo difícil?", 2),
        ("¿Qué cosa que lograste que parecía imposible cambió permanentemente lo que creés capaz de hacer?", 2),
        ("¿Qué logro de tu historia que estaba relacionado con superar algo difícil del pasado todavía te define?", 2),
        ("¿Cuánto de lo que lograste fue resultado de perseverancia y cuánto fue resultado de circunstancias?", 2),
        ("¿Qué logro que tenías planeado de chico dejaste ir y qué te dice eso sobre quien sos hoy?", 2),
        ("¿Qué logro del pasado que en el momento sentiste como una obligación hoy podés ver como tuyo?", 2),
        ("¿Qué logro del pasado fue el que más alejó al adulto que sos del niño que eras?", 3),
        ("¿Cuánto de lo que lograste hasta ahora fue para cumplirle algo al vos de chico y cuánto fue para vos hoy?", 3),
        ("¿Qué logro pendiente del pasado tuyo si lo alcanzaras cambiaría la historia que te contás sobre vos?", 3),
        ("¿Qué significa para vos lograr algo versus soñar algo y cómo cambió esa ecuación desde la infancia?", 3),
        ("¿Qué logro que tenés planeado es genuinamente tuyo y cuál es una respuesta a algo de tu historia?", 3),
        ("¿Cuándo fue la primera vez que un logro tuyo no te dio lo que esperabas y qué aprendiste de eso?", 3),
        ("¿Qué logro del pasado que costó mucho querés que el vos de chico hubiera podido ver?", 3),
    ],

    "sinFiltro": [
        ("¿Cuál fue la primera vez que hiciste algo prohibido de chico y te salió bien?", 1),
        ("¿Qué cosa de chico te mandaste que hoy admitís que estuvo bien aunque no debería?", 1),
        ("¿Cuándo fue la primera vez que mentiste de adulto de la misma manera que lo hacías de chico?", 1),
        ("¿Qué travesura de infancia que nunca te descubrieron recordás con más orgullo secreto?", 1),
        ("¿Cuál fue la primera vez que actuaste por puro impulso de adulto y no te arrepentís?", 1),
        ("¿Qué cosa que hacías de chico sin filtro dejaste de hacer de adulto y a veces extrañás?", 1),
        ("¿Cuándo fue la primera vez que dijiste algo completamente honesto que incomodó a todos pero era necesario?", 1),
        ("¿Qué versión sin filtros de vos de chico te gustaría recuperar por un día?", 1),
        ("¿Qué travesura que te descubrieron de chico en retrospectiva fue completamente necesaria?", 1),
        ("¿Cuándo fue la primera vez que rompiste una regla de adulto que no merecía existir?", 1),
        ("¿Qué cosa que hacías de chico con toda naturalidad ahora te parece increíble que te animaras?", 1),
        ("¿Cuál fue el primer momento en que dijiste lo que pensabas sin calcular las consecuencias y resultó bien?", 1),
        ("¿Qué cosa de tu infancia que se supone que debería avergonzarte en realidad no te avergüenza nada?", 1),
        ("¿Qué hiciste de chico que de adulto no harías y qué dice eso de lo que perdiste?", 1),
        ("¿Cuándo fue la primera vez que hiciste algo completamente espontáneo de adulto y te sorprendió la libertad que sentiste?", 1),
        ("¿Cuál fue el primer arrepentimiento real de tu vida adulta que el vos de chico no hubiera entendido?", 1),
        ("¿Qué cosa de la vida adulta que de chico esperabas con ilusión resultó ser mucho más complicada de lo que imaginabas?", 1),
        ("¿Qué impulso de chico que reprimiste porque te enseñaron que era malo hoy reconocés que era completamente válido?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que los adultos de tu infancia también actuaban por impulso?", 1),
        ("¿Qué cosa que te mandaste de joven que fue un desastre absoluto ahora te genera más cariño que vergüenza?", 1),
        ("¿Cuánto del niño que fuiste todavía actúa desde adentro tuyo en los momentos más inesperados?", 2),
        ("¿Qué cosa que de chico hacías sin culpa hoy hacés con culpa aunque no deberías?", 2),
        ("¿Qué versión de vos de chico sin filtros aparece cuando estás verdaderamente relajado?", 2),
        ("¿Qué deseo de chico que reprimiste se convirtió en un motor silencioso de decisiones adultas?", 2),
        ("¿Cuánto del adulto que sos hoy sigue siendo el nene o la nena que solo quería que lo vieran y lo aprobaran?", 2),
        ("¿Qué cosa que hacías de chico sin vergüenza hoy hacés con vergüenza aunque en el fondo no cambia nada?", 2),
        ("¿Qué límite que te pusieron de chico que respetaste todavía lo respetás aunque ya no hay nadie que te lo imponga?", 2),
        ("¿Qué cosa que el niño que fuiste quería con más desesperación el adulto que sos todavía no terminó de conseguir o de soltar?", 3),
        ("¿Cuánto de lo que hacés de adulto es el chico de antes todavía buscando aprobación?", 3),
        ("¿Qué parte de vos sin filtros de la infancia intentás suprimir más que todo lo demás y qué pasaría si la dejaras salir?", 3),
        ("¿Cuándo fue la última vez que actuaste con la misma libertad que tenías de chico y qué se sintió?", 3),
        ("¿Qué cosa que el vos de diez años haría sin dudar el adulto que sos todavía no se animó a hacer?", 3),
        ("¿Cuánto de la nostalgia que sentís por la infancia es en realidad nostalgia por una versión de vos mismo que dejaste de ser?", 3),
        ("¿Qué necesitaría pasar para que el adulto que sos recupere algo de la libertad sin culpa que tenías de chico?", 3),
    ],
}


def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]


def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS28:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS28[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")


if __name__ == "__main__":
    main()
