#!/usr/bin/env python3
"""Batch 32 - play, joy, laughter, spontaneity, lightness, celebration, fun."""
import json

ADDITIONS32 = {
    "infancia": [
        ("¿Cuál fue el juego de tu infancia que más te hacía reír?", 1),
        ("¿Qué cosa de chico hacías que te generaba alegría pura sin ninguna mezcla?", 1),
        ("¿Cuál era la broma más repetida en tu casa de chico?", 1),
        ("¿Qué momento de juego de tu infancia todavía recordás con una sonrisa automática?", 1),
        ("¿Quién te hacía reír más cuando eras chico?", 1),
        ("¿Cuál fue tu cumpleaños de infancia favorito?", 1),
        ("¿Qué cosa ridícula hacías de chico que hoy te genera ternura?", 1),
        ("¿Cuál era la canción más tonta que cantabas de chico?", 1),
        ("¿Qué juego de chico que jugabas con amigos fue el más divertido?", 1),
        ("¿Cuándo fue la primera vez que reíste tanto que te dolió la panza?", 1),
        ("¿Qué cosa de chico te llenaba de energía pura?", 1),
        ("¿Cuál era la actividad más libre y desestructurada que tenías de chico?", 1),
        ("¿Qué personaje cómico o gracioso de chico imitabas o admirabas?", 1),
        ("¿Qué tradición festiva de tu infancia te generaba más anticipación?", 1),
        ("¿Cuál era tu juego favorito bajo la lluvia?", 1),
        ("¿Qué cosa espontánea de tu infancia que salió sin planear fue la más divertida?", 1),
        ("¿Cuándo fue la última vez que jugaste como jugabas de chico?", 1),
        ("¿Qué cosa que hacías de chico sin pensar en las consecuencias era la más liberadora?", 1),
        ("¿Cuál era tu fiesta o festejo favorito de la infancia?", 1),
        ("¿Qué cosa de chico que era aparentemente inútil era la que más disfrutabas?", 1),
        ("¿Qué tipo de alegría de tu infancia que ya no tenés con la misma frecuencia te gustaría recuperar?", 2),
        ("¿Cómo el juego de tu infancia moldeó algo de tu personalidad que todavía está?", 2),
        ("¿Cuándo fue la última vez que te reíste con alguien con la misma libertad que reías de chico?", 2),
        ("¿Qué cosa de la ligereza de tu infancia que perdiste al crecer fue la que más costó perder?", 2),
        ("¿Cómo la alegría espontánea que tenías de chico cambió de forma al hacerse adulta?", 2),
        ("¿Qué parte del juego de tu infancia que todavía tenés en alguna forma es la más valiosa?", 2),
        ("¿Qué cosa de la manera en que te divertías de chico dice algo profundo de quién sos?", 2),
        ("¿Qué momento de risa pura de tu infancia que todavía podés evocar te devuelve algo que no tiene precio?", 3),
        ("¿Qué parte del niño o la niña que fuiste que se expresaba en el juego y la alegría querés honrar de adulto?", 3),
        ("¿Cuándo fue la primera vez que sentiste que la alegría tenía que ser merecida o justificada y qué perdiste con eso?", 3),
        ("¿Qué versión de vos de chico que era completamente libre en el juego querés recuperar en algo de cómo vivís hoy?", 3),
        ("¿Qué cosa de la ligereza de tu infancia que hoy casi no tenés si la recuperaras cambiaría algo en tu vida adulta?", 3),
        ("¿Qué juego de chico que nunca abandonaste del todo es uno de tus activos más secretos?", 3),
        ("¿Cuándo fue la última vez que hiciste algo completamente inútil por el puro placer de hacerlo como hacías de chico?", 3),
    ],

    "futuro": [
        ("¿Cómo querés que sea la alegría en tu vida futura?", 1),
        ("¿Qué cosa que te da mucha alegría querés que sea parte de tu vida futura?", 1),
        ("¿Cómo querés celebrar los momentos importantes de tu vida en el futuro?", 1),
        ("¿Qué tipo de juego o diversión querés seguir teniendo cuando seas mayor?", 1),
        ("¿Cómo querés que sea la ligereza y la espontaneidad en tu vida en diez años?", 1),
        ("¿Qué cosa que hoy no te permitís disfrutar querés empezar a disfrutar en el futuro?", 1),
        ("¿Qué plan que solo tiene como objetivo pasarla bien querés que ocurra pronto?", 1),
        ("¿Cómo querés que sea el equilibrio entre seriedad y ligereza en tu vida futura?", 1),
        ("¿Qué tipo de celebración querés que sea parte de tu vida futura?", 1),
        ("¿Qué actividad lúdica o creativa querés desarrollar en el futuro?", 1),
        ("¿Cómo querés que sea la relación de las personas que amás con la alegría en el futuro?", 1),
        ("¿Qué cosa que te genera alegría genuina querés cultivar más en el futuro?", 1),
        ("¿Cómo querés que sea la risa en tu vida cotidiana futura?", 1),
        ("¿Qué tipo de juego o ligereza querés que sea parte de tu vejez?", 1),
        ("¿Qué cosa que solo hacés cuando vas de vacaciones o en ocasiones especiales querés que sea más frecuente?", 1),
        ("¿Cuánto de la vida que querés en el futuro tiene que ver con alegría versus logros?", 1),
        ("¿Qué cosa que hoy postergás disfrutar querés comprometerte a disfrutar antes de que sea tarde?", 1),
        ("¿Cómo querés que sea la espontaneidad en tus relaciones futuras?", 1),
        ("¿Qué cosa divertida que hacías y dejaste de hacer querés retomar?", 1),
        ("¿Cómo querés que sea la celebración en tu vida futura en términos de frecuencia y tipo?", 1),
        ("¿Cuánto de la vida futura que construís tiene espacio para el juego y la ligereza versus cuánto es solo obligaciones?", 2),
        ("¿Qué cosa que te da alegría que postergás para cuando tengas más tiempo merece empezar ahora?", 2),
        ("¿Cómo querés que sea diferente la proporción de levedad y seriedad en tu vida futura?", 2),
        ("¿Qué tipo de alegría que en el futuro te va a importar estás descuidando hoy?", 2),
        ("¿Cuánto del futuro que construís está diseñado para disfrutarse y cuánto solo para llegar a algo?", 2),
        ("¿Qué cosa divertida y sin propósito que hacías y dejaste ir merece ser recuperada en el futuro cercano?", 2),
        ("¿Cómo querés que sea tu relación con el juego y la ligereza en la vejez que querés tener?", 2),
        ("¿Qué parte de la vida futura tuya que querés estar vivo es la que tiene más alegría y cuánto estás haciendo para que exista?", 3),
        ("¿Cuánto de lo que llamás responsabilidad te está costando la alegría que también necesitás?", 3),
        ("¿Qué le querés transmitir a quienes vienen después sobre el valor de la alegría y el juego?", 3),
        ("¿Qué cosa que trae alegría genuina en tu vida si la eliminás qué perdés y cuánto le das el lugar que merece?", 3),
        ("¿Cuándo fue la última vez que planificaste algo solo para pasarla bien sin otro propósito?", 3),
        ("¿Qué versión tuya del futuro que querés ser tiene más espacio para la risa y la ligereza?", 3),
        ("¿Cuánto de la alegría que querés tener en el futuro ya podría existir si no postergás el disfrute para después?", 3),
    ],

    "amor": [
        ("¿Cuándo fue la última vez que te reíste a carcajadas con tu pareja o alguien que amás?", 1),
        ("¿Qué cosa tonta o ridícula es un chiste interno entre vos y alguien que amás?", 1),
        ("¿Qué plan que solo sirve para pasarla bien querés hacer con alguien que amás?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente espontáneo con alguien que amás?", 1),
        ("¿Qué cosa divertida que hacías al principio de una relación perdiste con el tiempo?", 1),
        ("¿Cómo es la alegría en tu relación más importante?", 1),
        ("¿Qué tipo de celebración o festejo es el que más disfrutás con alguien que amás?", 1),
        ("¿Cuándo fue la última vez que jugaron como chicos vos y alguien que amás?", 1),
        ("¿Qué broma interna entre vos y alguien que amás tiene tanta historia que ya solo con una palabra hace gracia?", 1),
        ("¿Qué cosa espontánea e inesperada que hiciste con alguien que amás resultó ser lo mejor del día?", 1),
        ("¿Cuánto de ligereza y juego tiene la relación más importante de tu vida?", 1),
        ("¿Qué cosa ridícula pero llena de ternura hacés o hiciste con alguien que amás?", 1),
        ("¿Cuándo fue la última vez que sorprendiste a alguien que amás con algo inesperado y alegre?", 1),
        ("¿Qué tipo de juego o diversión compartís con las personas que más amás?", 1),
        ("¿Cómo la risa y la ligereza funcionan en tu relación más importante?", 1),
        ("¿Cuándo fue la última vez que la alegría en una relación fue más importante que cualquier otra cosa?", 1),
        ("¿Qué plan completamente inútil pero que genera alegría pura querés hacer pronto con alguien que amás?", 1),
        ("¿Cómo celebrás los momentos buenos con las personas que amás?", 1),
        ("¿Cuándo fue la última vez que te enamoraste un poco más de alguien porque te hizo reír de verdad?", 1),
        ("¿Qué tipo de espontaneidad en una relación amorosa te genera más alegría?", 1),
        ("¿Cuánto de la alegría y el juego en una relación es tan importante como la profundidad y la intimidad?", 2),
        ("¿Qué cosa de la ligereza en una relación pasada que tenías y perdiste con el tiempo querés recuperar en el amor futuro?", 2),
        ("¿Cuándo fue la primera vez que la risa con alguien te dijo algo sobre esa persona que ninguna conversación seria podía?", 2),
        ("¿Qué cosa divertida y espontánea que hacías en una relación que ya no está extrañás con más honestidad?", 2),
        ("¿Cómo la capacidad de reírse juntos de algo afecta la profundidad de un vínculo amoroso?", 2),
        ("¿Cuándo fue la primera vez que entendiste que la alegría compartida era tan importante como el amor serio?", 2),
        ("¿Qué tipo de juego o ligereza en el amor que querés tener todavía no encontraste o no construiste?", 2),
        ("¿Qué momento de risa pura con alguien que amás tiene el mismo peso en tu corazón que los momentos más profundos?", 3),
        ("¿Cuánto del amor que das y recibís tiene espacio para la ligereza y el juego y qué dice eso de cómo amás?", 3),
        ("¿Qué cosa tonta pero llena de amor que hacés o hacías con alguien que amás tiene un valor que ninguna otra cosa puede reemplazar?", 3),
        ("¿Cuándo fue la última vez que la alegría y el juego en el amor te recordaron por qué todo el esfuerzo vale la pena?", 3),
        ("¿Cuánto de la seriedad con que tomás el amor te está costando la ligereza que también lo nutre?", 3),
        ("¿Qué tipo de alegría compartida con alguien que amás querés que sea una constante y no una excepción?", 3),
        ("¿Cuándo fue la última vez que la risa con alguien que amás fue en sí misma suficiente para todo?", 3),
    ],

    "familia": [
        ("¿Cuál es el chiste o la broma familiar que siempre hace gracia aunque ya lo escuchaste mil veces?", 1),
        ("¿Qué tradición festiva familiar es la que más disfrutás?", 1),
        ("¿Cuándo fue la última vez que tu familia se rió junta de algo con verdadera alegría?", 1),
        ("¿Qué juego o actividad divertida hacías con tu familia de chico que extrañás?", 1),
        ("¿Quién es el miembro más gracioso de tu familia?", 1),
        ("¿Cuál es la historia familiar más ridícula que todos conocen y que siempre genera risa?", 1),
        ("¿Cuándo fue la última vez que celebraste algo con tu familia de manera espontánea?", 1),
        ("¿Qué cosa completamente tonta que hace alguien de tu familia te genera ternura y risa?", 1),
        ("¿Cuál es el festejo familiar que más anticipás?", 1),
        ("¿Qué juego o actividad lúdica querés recuperar o crear en tu familia?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente espontáneo con tu familia?", 1),
        ("¿Qué cosa que en tu familia genera risa nadie que no sea de la familia entendería?", 1),
        ("¿Cuándo fue la última vez que una reunión familiar fue pura alegría sin ninguna tensión?", 1),
        ("¿Qué tipo de celebración o festejo querés crear en tu familia que todavía no existe?", 1),
        ("¿Cómo la risa y la ligereza funcionan en tu familia?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te sorprendió con algo completamente inesperado y alegre?", 1),
        ("¿Qué momento de alegría pura con tu familia querés que se repita más seguido?", 1),
        ("¿Cuándo fue la última vez que la familia se rió tanto que alguien casi llora?", 1),
        ("¿Qué tipo de juego o actividad lúdica querés que sea parte de la vida de tu familia?", 1),
        ("¿Cuándo fue la última vez que hiciste algo ridículo con alguien de tu familia solo para reírse?", 1),
        ("¿Cuánto de ligereza y juego tiene la dinámica de tu familia actualmente y cuánto querés que tenga?", 2),
        ("¿Qué tipo de alegría familiar que tenías de chico perdiste con el tiempo y querés recuperar?", 2),
        ("¿Cuándo fue la primera vez que entendiste que la risa entre familia tenía el poder de sanar algo que las palabras no podían?", 2),
        ("¿Cómo la alegría y el juego en tu familia cambiaron desde tu infancia hasta hoy?", 2),
        ("¿Qué tipo de celebración familiar que no existe todavía querés crear y qué necesitarías para hacerlo?", 2),
        ("¿Cuándo fue la última vez que algo totalmente espontáneo con tu familia fue lo mejor de la semana?", 2),
        ("¿Cuánto del tiempo que pasás con tu familia es genuinamente alegre versus obligatorio pero vacío?", 2),
        ("¿Qué momento de risa familiar que se repite una y otra vez es uno de los tesoros más secretos de tu historia?", 3),
        ("¿Cuánto de la alegría que querés transmitirle a tu familia ya está presente en lo que hacés juntos?", 3),
        ("¿Qué le querés transmitir a los que vienen después de vos sobre el valor de celebrar y reír juntos?", 3),
        ("¿Cuándo fue la última vez que la ligereza con tu familia fue más nutritiva que cualquier conversación seria?", 3),
        ("¿Qué tipo de alegría familiar que querés construir está esperando que des el primer paso?", 3),
        ("¿Cuánto de la seriedad con que tomás los vínculos familiares te está costando la ligereza que también los nutre?", 3),
        ("¿Qué necesitaría pasar para que la alegría y el juego sean una constante en tu familia y no una excepción?", 3),
    ],

    "amistades": [
        ("¿Cuándo fue la última vez que te reíste con un amigo hasta no poder más?", 1),
        ("¿Cuál es el chiste o la referencia interna que solo entienden en tu grupo de amigos?", 1),
        ("¿Qué plan completamente inútil pero que genera alegría querés hacer pronto con amigos?", 1),
        ("¿Quién es el amigo más gracioso que tenés?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente espontáneo con amigos?", 1),
        ("¿Qué cosa ridícula pero memorable hiciste con amigos que ahora es parte de la historia del grupo?", 1),
        ("¿Cuál es la anécdota más divertida que tenés con algún amigo?", 1),
        ("¿Qué actividad lúdica o divertida querés hacer con amigos que todavía no hiciste?", 1),
        ("¿Cuándo fue la última vez que una salida con amigos fue pura alegría y ligereza?", 1),
        ("¿Qué tipo de diversión con amigos que tenías antes y que perdiste querés recuperar?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente tonto con amigos y fue lo mejor del día?", 1),
        ("¿Qué cosa que solo hacés cuando estás con ciertos amigos te saca la mejor versión de vos?", 1),
        ("¿Cuál es la celebración de amistad que más disfrutás?", 1),
        ("¿Cuándo fue la última vez que sorprendiste a un amigo con algo inesperado y alegre?", 1),
        ("¿Qué tipo de juego o actividad divertida querés retomar con amigos?", 1),
        ("¿Cuándo fue la última vez que la risa con amigos fue más nutritiva que cualquier conversación seria?", 1),
        ("¿Qué cosa totalmente espontánea que pasó con amigos fue el mejor recuerdo reciente?", 1),
        ("¿Qué amistad que tenés que siempre te hace reír es uno de tus mayores tesoros?", 1),
        ("¿Cuándo fue la última vez que jugaste como un chico con amigos adultos?", 1),
        ("¿Qué tipo de alegría con amigos que querés tener más seguido estás postergando?", 1),
        ("¿Cuánto de las amistades que más valorás tiene que ver con la capacidad de reírse juntos?", 2),
        ("¿Qué tipo de ligereza en las amistades que querés tener estás descuidando?", 2),
        ("¿Cuándo fue la primera vez que entendiste que la risa genuina con un amigo era una de las formas más profundas de conexión?", 2),
        ("¿Qué amigo tuyo que siempre te hace ver el lado ridículo de las cosas tiene un valor que no siempre reconocés?", 2),
        ("¿Cuándo fue la última vez que algo completamente espontáneo con amigos resultó en un recuerdo que vale más que lo planificado?", 2),
        ("¿Cuánto del tiempo que pasás con amigos es genuinamente alegre y cuánto es más obligación o inercia?", 2),
        ("¿Qué tipo de celebración de amistad que no tenés todavía querés crear?", 2),
        ("¿Qué momento de risa con amigos que podés evocar te devuelve algo que ningún otro tipo de alegría puede?", 3),
        ("¿Cuánto de la alegría genuina que tenés en tu vida viene de la risa y el juego con amigos?", 3),
        ("¿Qué le querés dejar a tus amigos en términos de alegría y celebración compartida?", 3),
        ("¿Cuándo fue la última vez que la ligereza con amigos fue tan profunda como cualquier conversación existencial?", 3),
        ("¿Qué tipo de alegría de amistad que querés construir está esperando que le des el espacio que merece?", 3),
        ("¿Cuánto de la seriedad con que tomás las amistades te está costando la ligereza que también las nutre?", 3),
        ("¿Qué necesitaría pasar para que la alegría y el juego sean una constante en tus amistades y no una excepción?", 3),
    ],

    "exs": [
        ("¿Cuál fue el momento más ridículo y divertido que tuviste con un ex?", 1),
        ("¿Qué cosa tonta e inesperada que pasó con un ex fue uno de los mejores momentos de esa relación?", 1),
        ("¿Hubo alguna relación pasada que te haya hecho reír más que ninguna otra?", 1),
        ("¿Cuándo fue la última vez que pensaste en un ex con una sonrisa genuina por algo gracioso?", 1),
        ("¿Qué chiste interno que tenías con un ex todavía recordás con ternura?", 1),
        ("¿Cuál fue el plan más espontáneo e inesperado que tuviste con un ex?", 1),
        ("¿Qué cosa ridícula que hacías con un ex que en el momento te parecía normal hoy te genera risa?", 1),
        ("¿Cuándo fue la última vez que una relación pasada te hizo ser más espontáneo de lo que eras?", 1),
        ("¿Qué tipo de alegría o diversión que tenías en alguna relación pasada no encontraste igual después?", 1),
        ("¿Cuándo fue la primera vez que reíste sin parar con alguien que después se convirtió en importante para vos?", 1),
        ("¿Qué plan que era completamente inútil pero que hacías con un ex fue uno de los mejores?", 1),
        ("¿Cuál fue la sorpresa más alegre que le hiciste o que te hicieron en una relación pasada?", 1),
        ("¿Qué cosa espontánea que pasó con un ex cambió algo en esa relación para mejor?", 1),
        ("¿Cuándo fue la primera vez que la risa con alguien te dijo que había algo real ahí?", 1),
        ("¿Qué recuerdo de alegría pura con alguien del pasado todavía te devuelve algo valioso?", 1),
        ("¿Cuándo fue la última vez que un recuerdo alegre de una relación pasada te hizo sentir gratitud en vez de nostalgia?", 1),
        ("¿Qué cosa de la ligereza que tenías en alguna relación pasada querés recuperar en relaciones futuras?", 1),
        ("¿Cuándo fue la primera vez que la capacidad de alguien de hacerte reír fue lo que más te enamoró?", 1),
        ("¿Qué tipo de juego o espontaneidad en el amor que tuviste en el pasado querés que sea parte del futuro?", 1),
        ("¿Cuándo fue la primera vez que entendiste que la ligereza y la alegría en el amor eran tan importantes como la profundidad?", 1),
        ("¿Cuánto de lo que extrañás de relaciones pasadas tiene que ver con la alegría y la ligereza que había?", 2),
        ("¿Qué tipo de diversión en el amor que perdiste en alguna relación pasada te gustaría recuperar?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que extrañabas más la risa que cualquier otra cosa de una relación?", 2),
        ("¿Qué cosa de la espontaneidad que tenías con alguien del pasado te gustaría poder tener en el amor presente?", 2),
        ("¿Cuándo fue la primera vez que la alegría en una relación fue en sí misma razón suficiente para estar ahí?", 2),
        ("¿Qué tipo de celebración o ligereza que tenías en una relación pasada que ya no tenés extrañás con más honestidad?", 2),
        ("¿Cuánto de la ligereza y el juego que tenías con alguien del pasado cambió tu estándar de lo que querés en el amor?", 2),
        ("¿Qué recuerdo de alegría pura con alguien del pasado cuando lo evocás te devuelve algo que nada más puede?", 3),
        ("¿Cuánto de lo que buscás en el amor hoy tiene que ver con encontrar esa alegría y ligereza que algunas relaciones del pasado tenían?", 3),
        ("¿Qué tipo de juego y espontaneidad en el amor que existió en el pasado querés que sea no la excepción sino la norma?", 3),
        ("¿Cuándo fue la última vez que un recuerdo de risa con alguien del pasado te recordó que el amor también puede ser liviano?", 3),
        ("¿Qué le querías agradecer a alguien del pasado por la alegría que trajo a tu vida aunque ya no esté?", 3),
        ("¿Cuánto de la seriedad con que mirás el amor te está costando la ligereza que también necesitás?", 3),
        ("¿Qué versión de vos mismo en el amor que era más espontáneo y alegre querés recuperar?", 3),
    ],

    "personalidad": [
        ("¿Qué es lo que más te hace reír?", 1),
        ("¿Cómo es tu sentido del humor?", 1),
        ("¿Sos más de risa contagiosa o de humor sutil?", 1),
        ("¿Cuándo fue la última vez que te reíste sin parar?", 1),
        ("¿Qué tipo de humor que no te hace gracia a vos le hace gracia a todos?", 1),
        ("¿Qué cosa completamente tonta te genera una alegría desproporcionada?", 1),
        ("¿Cómo usás el humor en situaciones difíciles?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente espontáneo y sin planear?", 1),
        ("¿Qué tipo de juego o diversión te saca la mejor versión de vos?", 1),
        ("¿Cómo celebrás las cosas buenas?", 1),
        ("¿Qué tipo de alegría que tenés que es completamente tuya y difícil de explicar?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente inútil por el puro placer de hacerlo?", 1),
        ("¿Qué cosa que te hace reír que a otros no les hace gracia?", 1),
        ("¿Cómo es tu relación con la espontaneidad?", 1),
        ("¿Qué tipo de sorpresas te gustan?", 1),
        ("¿Cuándo fue la última vez que te sorprendiste a vos mismo por lo mucho que disfrutaste algo?", 1),
        ("¿Qué tipo de ligereza y alegría querés que sea más parte de tu vida cotidiana?", 1),
        ("¿Cómo diferenciás entre alegría genuina y entretenimiento?", 1),
        ("¿Cuándo fue la última vez que hiciste algo ridículo y te divirtió sin vergüenza?", 1),
        ("¿Qué cosa de vos mismo que es completamente ridícula te genera ternura?", 1),
        ("¿Cuánto de ligereza y alegría tiene tu vida cotidiana versus cuánto querés que tenga?", 2),
        ("¿Qué parte de tu personalidad que es más juguetona o espontánea no siempre le permitís salir?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que la alegría también podía ser una elección?", 2),
        ("¿Qué tipo de humor o alegría tuya que en ciertos contextos inhibís querés dejar salir más?", 2),
        ("¿Cómo la capacidad de reírte de vos mismo cambió algo en vos con el tiempo?", 2),
        ("¿Cuándo fue la última vez que la espontaneidad te llevó a algo mucho mejor que cualquier plan?", 2),
        ("¿Cuánto de tu carácter que es más serio o controlado te está costando la alegría que también forma parte de vos?", 2),
        ("¿Qué parte de vos que solo sale cuando sos completamente espontáneo es la que más te gusta?", 3),
        ("¿Cuánto de la alegría que querés tener en tu vida está esperando que te des permiso de no justificarla?", 3),
        ("¿Qué versión de vos mismo que es más liviana y juguetona el mundo necesita ver más?", 3),
        ("¿Cuándo fue la última vez que la risa te recordó algo de vos mismo que la seriedad había hecho olvidar?", 3),
        ("¿Cuánto de lo que llamás madurez te está costando algo de ligereza y juego que también sos?", 3),
        ("¿Qué cosa de vos mismo que es completamente ridícula y que escondés es en realidad parte de lo mejor de vos?", 3),
        ("¿Qué necesitaría pasar para que la alegría y el juego sean una parte más central de cómo vivís?", 3),
    ],

    "miedos": [
        ("¿Le tenés miedo a hacer el ridículo?", 1),
        ("¿Cuándo fue la última vez que el miedo al ridículo te impidió disfrutar algo?", 1),
        ("¿Le tenés miedo a ser demasiado espontáneo en contextos donde no se espera?", 1),
        ("¿Qué tipo de celebración o alegría te genera incomodidad aunque te guste?", 1),
        ("¿Le tenés miedo a reírte de vos mismo?", 1),
        ("¿Cuándo fue la última vez que el miedo a la opinión ajena te frenó de disfrutar algo?", 1),
        ("¿Qué tipo de juego o espontaneidad que te genera alegría te cuesta mostrarte en público?", 1),
        ("¿Le tenés miedo a que te vean siendo completamente liviano o ridículo?", 1),
        ("¿Cuándo fue la última vez que el miedo a no estar a la altura de una situación te impidió disfrutarla?", 1),
        ("¿Qué cosa que te genera alegría te cuesta disfrutar cuando otros te miran?", 1),
        ("¿Le tenés miedo a que si sos demasiado alegre o espontáneo no te van a tomar en serio?", 1),
        ("¿Cuándo fue la última vez que el miedo a disfrutar demasiado algo te hizo contenerte?", 1),
        ("¿Qué tipo de alegría que tenés en privado te cuesta mostrar en público?", 1),
        ("¿Le tenés miedo a la sorpresa?", 1),
        ("¿Cuándo fue la última vez que el miedo a perder el control de una situación te impidió dejarte llevar por la alegría?", 1),
        ("¿Qué tipo de risa o juego te genera vergüenza aunque no haya razón para que la genere?", 1),
        ("¿Le tenés miedo a que te vean con la guardia baja en términos de alegría y espontaneidad?", 1),
        ("¿Cuándo fue la última vez que te permitiste ser completamente ridículo sin preocuparte por lo que pensaban?", 1),
        ("¿Qué tipo de celebración o festejo que genuinamente disfrutás te cuesta admitir que disfrutás?", 1),
        ("¿Le tenés miedo a que la alegría sea demasiado buena y que algo la interrumpa?", 1),
        ("¿Cuánto del miedo al ridículo o a la opinión ajena te está costando alegría genuina?", 2),
        ("¿Qué miedo a perder el control o la imagen te impide ser más espontáneo en la vida?", 2),
        ("¿Cuándo fue la primera vez que entendiste que el miedo a no ser tomado en serio te costaba alegría real?", 2),
        ("¿Qué miedo a que la alegría tenga un costo oculto te hace contenerte de disfrutarla completamente?", 2),
        ("¿Cuándo fue la última vez que hiciste algo completamente espontáneo a pesar del miedo y resultó en la alegría más genuina?", 2),
        ("¿Qué miedo a la levedad o a la ligereza tenés que se disfraza de responsabilidad?", 2),
        ("¿Cuánto del miedo a disfrutar demasiado viene de haber aprendido que la alegría puede ser seguida por algo difícil?", 2),
        ("¿Qué miedo tuyo a ser visto en tu versión más espontánea y ridícula es en realidad miedo a qué exactamente?", 3),
        ("¿Cuánto del miedo al ridículo que tenés está guardando una versión de vos mismo que genuinamente querés que el mundo vea?", 3),
        ("¿Qué necesitaría pasar para que el miedo al juicio no pueda más que la alegría que querés vivir?", 3),
        ("¿Cuándo fue la última vez que la alegría genuina fue más fuerte que cualquier miedo y qué se sintió?", 3),
        ("¿Qué versión de vos mismo que es completamente espontánea y alegre estás guardando por miedo y qué te está costando?", 3),
        ("¿Cuánto de lo que llamás madurez o seriedad es en realidad miedo al ridículo disfrazado?", 3),
        ("¿Qué miedo a la alegría o a dejarte llevar es en realidad miedo a algo más profundo que la alegría en sí?", 3),
    ],

    "logros": [
        ("¿Cuándo fue la última vez que celebraste un logro tuyo de verdad?", 1),
        ("¿Qué logro tuyo que festejaste de la manera más simple resultó ser el que más disfrutaste?", 1),
        ("¿Cuándo fue la última vez que algo que lograste te generó una alegría que no pudiste contener?", 1),
        ("¿Qué tipo de celebración de un logro que tuviste fue la más memorable?", 1),
        ("¿Cuándo fue la última vez que celebraste algo con espontaneidad pura y sin planificación?", 1),
        ("¿Qué logro que conseguiste que podría parecer pequeño celebraste con más alegría que uno grande?", 1),
        ("¿Cuándo fue la última vez que te diste un premio o un regalo por algo que lograste?", 1),
        ("¿Qué logro tuyo que le generó alegría a alguien más fue el que más te llenó?", 1),
        ("¿Cuándo fue la última vez que algo que lograste te hizo reír de alegría?", 1),
        ("¿Qué tipo de festejo de logros que no tenés querés incorporar en tu vida?", 1),
        ("¿Cuándo fue la última vez que celebraste algo junto a otros con alegría genuina?", 1),
        ("¿Qué logro tuyo que le generó alegría a alguien que amás fue el más valioso?", 1),
        ("¿Cómo celebrás las victorias pequeñas cotidianas?", 1),
        ("¿Cuándo fue la última vez que hiciste algo ridículo de alegría por haber logrado algo?", 1),
        ("¿Qué tipo de festejo de un logro que tuviste que fue completamente espontáneo fue el mejor?", 1),
        ("¿Cuándo fue la última vez que alguien celebró algo tuyo con más alegría que vos mismo?", 1),
        ("¿Qué logro que tenés planeado ya sabés cómo lo vas a celebrar?", 1),
        ("¿Cuándo fue la última vez que te sorprendiste a vos mismo con cuánta alegría genuina te generó algo que lograste?", 1),
        ("¿Qué tipo de celebración que le ponés a los logros de otros querés también ponerte a vos?", 1),
        ("¿Cuándo fue la última vez que el proceso de lograr algo fue más divertido que el resultado?", 1),
        ("¿Cuánto de lo que lograste festejaste genuinamente y cuánto pasó desapercibido?", 2),
        ("¿Qué logro tuyo que no celebraste suficientemente merece ser reconocido aunque sea tarde?", 2),
        ("¿Cuándo fue la primera vez que entendiste que celebrar los logros era tan importante como conseguirlos?", 2),
        ("¿Qué cosa de cómo celebrás tus logros querés cambiar para que sea más genuina y alegre?", 2),
        ("¿Cuándo fue la última vez que la alegría de un logro fue más importante que el logro en sí?", 2),
        ("¿Qué logro que querés alcanzar ya tenés pensado cómo celebrar y qué dice eso?", 2),
        ("¿Cuánto de la seriedad con que tomás tus logros te está costando la alegría que merecen?", 2),
        ("¿Qué logro tuyo cuando lo mirás con ojos de alegría pura te devuelve algo que la seriedad no puede?", 3),
        ("¿Cuánto de lo que lograste en tu vida si lo celebraras con la alegría que merece cambiaría algo en cómo te relacionás con lo que viene?", 3),
        ("¿Qué le querés transmitir a quienes vienen después sobre el valor de celebrar lo que se logra sin esperar el logro perfecto?", 3),
        ("¿Cuándo fue la última vez que la alegría de lograr algo junto a otros fue más valiosa que el logro individual?", 3),
        ("¿Qué versión de vos mismo que celebra con más alegría y menos seriedad querés cultivar?", 3),
        ("¿Cuánto de la capacidad de disfrutar lo que lograste que tenés determina si vale la pena el esfuerzo de lograrlo?", 3),
        ("¿Qué necesitaría pasar para que la alegría de celebrar lo que conseguís sea una parte más central de quién sos?", 3),
    ],

    "sinFiltro": [
        ("¿Cuándo fue la última vez que hiciste algo completamente ridículo y te divirtió sin ningún filtro?", 1),
        ("¿Qué cosa que te genera alegría en privado te daría vergüenza admitir?", 1),
        ("¿Cuándo fue la última vez que bailaste como si nadie te viera aunque alguien te estuviera viendo?", 1),
        ("¿Qué broma que hiciste que fue inapropiada pero graciosa no te arrepentís de haber hecho?", 1),
        ("¿Cuándo fue la última vez que te reíste de algo que no tenías que reírte pero no pudiste evitarlo?", 1),
        ("¿Qué cosa completamente ridícula hacés cuando estás solo que nunca admitirías?", 1),
        ("¿Cuándo fue la última vez que alguien te hizo reír en el peor momento posible?", 1),
        ("¿Qué cosa que le hace gracia a poca gente te hace reír sin poder parar?", 1),
        ("¿Cuándo fue la última vez que la risa llegó en el momento más inoportuno y fue lo mejor del día?", 1),
        ("¿Qué cosa espontánea que hiciste sin pensar resultó ser lo más divertido del año?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente infantil siendo adulto y te encantó?", 1),
        ("¿Qué tipo de humor que tenés que es demasiado tonto o ridículo para admitirlo en público?", 1),
        ("¿Cuándo fue la última vez que te dejaste llevar completamente por la alegría sin pensar en las consecuencias?", 1),
        ("¿Qué cosa que hacés solo cuando estás con personas muy de confianza que sería impensable en otros contextos?", 1),
        ("¿Cuándo fue la última vez que algo te generó tanta alegría que no pudiste disimularlo aunque quisieras?", 1),
        ("¿Qué cosa ridícula o infantil que todavía disfrutás que no le contás a nadie?", 1),
        ("¿Cuándo fue la última vez que te reíste de algo completamente inapropiado y no te podías parar?", 1),
        ("¿Qué broma interna que tenés con alguien que si la escuchara un extraño no entendería absolutamente nada?", 1),
        ("¿Cuándo fue la última vez que hiciste una pavada enorme y fue lo mejor de la semana?", 1),
        ("¿Qué cosa que hacés cuando nadie te ve que es completamente ridícula es también completamente necesaria?", 1),
        ("¿Cuánto de la alegría más genuina que tenés pasa en momentos que nadie ve y que nunca contás?", 2),
        ("¿Qué tipo de humor o ligereza tuya que escondés en ciertos contextos querés dejar de esconder?", 2),
        ("¿Cuándo fue la última vez que te permitiste ser completamente ridiculo y fue exactamente lo que necesitabas?", 2),
        ("¿Qué parte de vos más espontánea y alegre que inhibís para encajar querés soltar más seguido?", 2),
        ("¿Cuándo fue la primera vez que entendiste que la alegría que no se justifica es a veces la más real?", 2),
        ("¿Cuánto del vos sin filtros es en realidad más alegre y espontáneo que el vos que mostrás?", 2),
        ("¿Qué tipo de diversión que tenés que no podés mostrar en ciertos contextos es de las más valiosas?", 2),
        ("¿Si pudieras ser completamente sin filtros en términos de alegría y espontaneidad qué harías diferente en tu vida?", 3),
        ("¿Qué versión de vos mismo más alegre y ridícula el mundo necesita ver más y qué te frena de mostrarlo?", 3),
        ("¿Cuánto de la alegría que vivís en privado merece más espacio en tu vida pública y qué te lo impide?", 3),
        ("¿Qué necesitaría pasar para que la versión más espontánea y alegre de vos sea la que lleva el timón más seguido?", 3),
        ("¿Cuándo fue la última vez que la alegría pura fue más poderosa que cualquier otra cosa que estuvieras sintiendo?", 3),
        ("¿Qué le dirías al vos del futuro sobre el valor de reírse más y controlarse menos?", 3),
        ("¿Qué cosa de la vida que podría ser completamente ridícula y sin propósito pero llena de alegría todavía no te animás a hacer?", 3),
    ],
}


def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]


def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS32:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS32[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")


if __name__ == "__main__":
    main()
