#!/usr/bin/env python3
"""Batch 29 - communication styles, difficult conversations, silence, tone, what's unsaid."""
import json

ADDITIONS29 = {
    "infancia": [
        ("¿Cómo comunicabas lo que te molestaba cuando eras chico?", 1),
        ("¿Había temas de los que nunca se hablaba en tu casa de infancia?", 1),
        ("¿Cómo se manejaban los conflictos en tu familia cuando eras chico?", 1),
        ("¿Cuándo fue la primera vez que dijiste algo importante y no te escucharon?", 1),
        ("¿Qué aprendiste sobre el silencio en tu infancia?", 1),
        ("¿Había alguien en tu familia que hablaba demasiado y alguien que hablaba muy poco?", 1),
        ("¿Cómo se expresaba el amor en tu casa de infancia: con palabras, acciones, o no se expresaba?", 1),
        ("¿Qué tema de tu infancia que nadie nombraba vos sí sentías que estaba siempre en el aire?", 1),
        ("¿Cómo aprendiste a pedir lo que necesitabas de chico?", 1),
        ("¿Había conversaciones que solo podías tener con ciertas personas en tu familia?", 1),
        ("¿Qué cosa importante de tu infancia nunca pudiste decirle a alguien que hubieras querido?", 1),
        ("¿Cómo reaccionaba tu familia cuando alguien decía algo incómodo?", 1),
        ("¿Qué aprendiste sobre el tono de voz y su poder de chico?", 1),
        ("¿Se podía llorar abiertamente en tu casa de infancia?", 1),
        ("¿Qué conversación de tu infancia que nunca se tuvo cambiaría algo si hubiera pasado?", 1),
        ("¿Cómo comunicaban enojo en tu familia de chico: gritando, con silencio, con ironía?", 1),
        ("¿Qué aprendiste sobre interrumpir o esperar en las conversaciones de tu infancia?", 1),
        ("¿Había alguien en tu familia que era el intérprete o mediador de los conflictos?", 1),
        ("¿Qué cosa que querías decir de chico te tragaste y todavía recordás?", 1),
        ("¿Cómo aprendiste a decir que no de chico?", 1),
        ("¿Qué regla no escrita de comunicación de tu infancia todavía seguís sin darte cuenta?", 2),
        ("¿Cómo el estilo comunicativo de tu familia de chico moldeó cómo te comunicás hoy?", 2),
        ("¿Hay alguna conversación que nunca tuviste con alguien de tu infancia y que sigue pendiente?", 2),
        ("¿Qué aprendiste en tu familia de infancia sobre lo que no se dice y cómo te afecta eso hoy?", 2),
        ("¿Cómo el silencio era usado en tu familia de chico y qué aprendiste de eso?", 2),
        ("¿Qué cosa que nunca se dijo en tu infancia pero era evidente para todos siguió afectando a la familia?", 2),
        ("¿Cómo la manera en que se comunicaba tu familia de chico influyó en cómo pedís o recibís afecto hoy?", 2),
        ("¿Qué conversación de infancia que se tuvo una sola vez y de manera imperfecta fue sin embargo la más importante?", 3),
        ("¿Qué cosa de la comunicación de tu familia de infancia rompiste conscientemente y qué te costó?", 3),
        ("¿Qué silencio de tu infancia todavía habla más fuerte que cualquier cosa que se haya dicho?", 3),
        ("¿Qué conversación que nunca se tuvo en tu infancia cambia la historia de tu familia si imaginás que hubiera pasado?", 3),
        ("¿Qué aprendiste sobre lo que no se dice de tu infancia que todavía te gobierna?", 3),
        ("¿Cómo el idioma emocional de tu familia de infancia te ayudó o te limitó para comunicarte de adulto?", 3),
        ("¿Qué palabra que nunca te dijeron de chico que necesitabas oír todavía te falta?", 3),
    ],

    "futuro": [
        ("¿Cómo querés que sea la comunicación en los vínculos más importantes de tu futuro?", 1),
        ("¿Qué conversación que postergás tener necesitás tener antes de que sea tarde?", 1),
        ("¿Cómo te imaginás manejando las conversaciones difíciles en el futuro?", 1),
        ("¿Qué hábito de comunicación querés desarrollar en el futuro?", 1),
        ("¿Hay algo que querés decir en el futuro que hoy no encontrás cómo?", 1),
        ("¿Qué tipo de comunicación buscás en el entorno laboral de tu futuro?", 1),
        ("¿Cómo querés que sea tu comunicación con las personas que amás en diez años?", 1),
        ("¿Qué conversación pendiente querés tener antes de que termine el año?", 1),
        ("¿Cómo te gustaría mejorar tu capacidad de escuchar en el futuro?", 1),
        ("¿Qué cosa querés decir más seguido que hoy no decís suficiente?", 1),
        ("¿Qué cosa querés aprender a decir que todavía no sabés cómo?", 1),
        ("¿Cómo querés que sea el silencio en tus vínculos futuros?", 1),
        ("¿Qué tipo de conversaciones querés que sean normales en tu vida futura que hoy no lo son?", 1),
        ("¿Cómo querés manejar el conflicto en tus relaciones del futuro?", 1),
        ("¿Qué cosa que no decís hoy querés empezar a decir?", 1),
        ("¿Cómo querés que sea tu comunicación con vos mismo en el futuro?", 1),
        ("¿Qué parte de cómo te comunicás hoy querés dejar atrás?", 1),
        ("¿Qué conversación difícil del futuro ya sabés que viene y cómo te estás preparando?", 1),
        ("¿Cómo querés que recuerden la manera en que te comunicabas?", 1),
        ("¿Qué cosa que decís que no querés decir más querés cambiar?", 1),
        ("¿Cuánto de lo que postergás decir tiene que ver con el miedo y cuánto con el momento?", 2),
        ("¿Qué conversación que sabés que tenés que tener en el futuro te genera más resistencia y por qué?", 2),
        ("¿Cómo querés que sea diferente tu comunicación con las personas difíciles de tu vida en el futuro?", 2),
        ("¿Qué cosa que no decís hoy porque creés que no va a cambiar nada merece ser dicha igual?", 2),
        ("¿Cuánto del silencio en tus vínculos es elección genuina y cuánto es evitación?", 2),
        ("¿Qué conversación futura que necesitás tener te genera más miedo y por qué exactamente?", 2),
        ("¿Cómo querés construir espacios de comunicación genuina en tu vida futura que hoy no existen?", 2),
        ("¿Qué cosa que no podés decir hoy pero que querés poder decir en el futuro requeriría cambiar qué de vos?", 3),
        ("¿Cuánto de lo que no decís hoy va a importar o pesar en el futuro?", 3),
        ("¿Qué conversación que estás evitando tiene el potencial de cambiar algo importante si la tenés?", 3),
        ("¿Cómo querés que sea diferente la manera en que te comunicás en el futuro de manera que requiera trabajo real?", 3),
        ("¿Qué voz tuya que hoy silenciás querés que en el futuro sea la que más se oiga?", 3),
        ("¿Qué conversación futura que inevitablemente viene querés tener de la mejor manera posible y qué necesitarías para eso?", 3),
        ("¿Qué cosa que no decís que te corroe por dentro merece ser dicha aunque cambie todo?", 3),
    ],

    "amor": [
        ("¿Cómo preferís comunicar lo que te molesta en una relación?", 1),
        ("¿Qué cosa en el amor nunca sabés cómo decir bien?", 1),
        ("¿Preferís resolver los conflictos de pareja en el momento o después de calmarte?", 1),
        ("¿Qué cosa que tu pareja hace que te molesta todavía no le dijiste?", 1),
        ("¿Cómo reaccionás cuando alguien que amás te dice algo que no querés escuchar?", 1),
        ("¿Qué cosa en el amor te resulta más difícil de pedir?", 1),
        ("¿Cómo preferís que te digan las cosas difíciles en una relación?", 1),
        ("¿Qué cosa que no dijiste en una relación pasada todavía lamentás no haber dicho?", 1),
        ("¿Cómo usás el silencio en una relación: como escudo, como descanso, como forma de castigar?", 1),
        ("¿Qué cosa en el amor te cuesta más escuchar que decir?", 1),
        ("¿Cuándo fue la última vez que dijiste algo difícil en una relación y salió bien?", 1),
        ("¿Qué conversación de pareja que postergás tener es la más necesaria?", 1),
        ("¿Cómo sabés cuándo tu pareja está diciéndote algo importante aunque no lo diga explícitamente?", 1),
        ("¿Qué cosa en el amor que sentís no sabés cómo expresar con palabras?", 1),
        ("¿Cuándo el silencio en una relación te generó más ansiedad?", 1),
        ("¿Qué tono de voz en tu pareja te pone automáticamente a la defensiva?", 1),
        ("¿Cómo pedís perdón en una relación y qué tan fácil te resulta?", 1),
        ("¿Qué cosa que querés en el amor nunca terminás de pedir claramente?", 1),
        ("¿Cómo diferenciás entre escuchar y esperar tu turno para hablar en una conversación de pareja?", 1),
        ("¿Qué parte de cómo te comunicás en el amor querés cambiar?", 1),
        ("¿Qué conversación difícil de pareja que tuviste resultó ser la más importante aunque fuera la más incómoda?", 2),
        ("¿Cuánto de lo que no decís en una relación es para proteger al otro y cuánto es para protegerte vos?", 2),
        ("¿Qué cosa que no dijiste en una relación importante cambió el curso de esa relación?", 2),
        ("¿Cómo el silencio en tus relaciones amorosas pasadas fue un lenguaje propio?", 2),
        ("¿Qué cosa que te dijeron en una relación que dolió mucho en el momento fue también la más verdadera?", 2),
        ("¿Cuándo fue la primera vez que entendiste que en el amor a veces lo que no se dice importa más que lo que se dice?", 2),
        ("¿Qué estilo de comunicación de una pareja pasada que en el momento odiabas ahora entendés mejor?", 2),
        ("¿Qué conversación que nunca tuviste con alguien que amaste todavía pesa?", 3),
        ("¿Cuánto de lo que no decís en el amor es miedo y cuánto es genuinamente innecesario decirlo?", 3),
        ("¿Qué cosa que tu cuerpo le dice al otro que tu boca no dice en el amor?", 3),
        ("¿Qué conversación que tuviste en una relación que en el momento no entendiste cambia de sentido hoy?", 3),
        ("¿Cuánto del amor que das se pierde en la traducción entre lo que sentís y lo que podés expresar?", 3),
        ("¿Qué cosa que sabés que necesitás decir en el amor y no podés decir te cuesta más: el qué o el cómo?", 3),
        ("¿Qué silencio en una relación que viviste fue más elocuente que cualquier conversación?", 3),
    ],

    "familia": [
        ("¿Qué tema sigue siendo tabú en tu familia y cómo lo manejás?", 1),
        ("¿Cómo se manejaban los conflictos en tu familia y cómo eso te afecta hoy?", 1),
        ("¿Hay algo que nunca le dijiste a alguien de tu familia y que todavía querés decir?", 1),
        ("¿Cómo es la comunicación en tu familia hoy comparada con cuando eras chico?", 1),
        ("¿Qué tema que en tu familia nadie nombra vos sí lo ves claramente?", 1),
        ("¿Cómo preferís tener conversaciones difíciles con tu familia?", 1),
        ("¿Hay alguien en tu familia con quien la comunicación es especialmente difícil?", 1),
        ("¿Cómo expresan amor los miembros de tu familia entre sí?", 1),
        ("¿Qué cosa que siempre quisiste preguntarle a alguien de tu familia todavía no preguntaste?", 1),
        ("¿Cómo reacciona tu familia cuando alguien dice algo que incomoda?", 1),
        ("¿Hay algún malentendido familiar que nunca se aclaró del todo?", 1),
        ("¿Qué cosa que sentís sobre tu familia nunca pudiste decir abiertamente?", 1),
        ("¿Cuál es la conversación familiar más difícil que tuviste y cómo quedó?", 1),
        ("¿Cómo cambió la comunicación en tu familia con el tiempo?", 1),
        ("¿Hay algo que se dice en tu familia de manera indirecta que todos entienden pero nadie nombra?", 1),
        ("¿Qué papel jugás en la comunicación de tu familia: mediador, directo, evitador?", 1),
        ("¿Cómo preferís que tu familia te comunique las cosas difíciles?", 1),
        ("¿Qué conversación familiar pendiente sabés que tarde o temprano va a tener que ocurrir?", 1),
        ("¿Cómo afectan las reuniones familiares tu capacidad de comunicarte genuinamente?", 1),
        ("¿Qué cosa que querés decirle a alguien de tu familia nunca encontró el momento?", 1),
        ("¿Qué patrón de comunicación familiar que te afecta negativamente todavía no pudiste cambiar?", 2),
        ("¿Cuánto de lo que no se dice en tu familia tiene más peso que lo que sí se dice?", 2),
        ("¿Qué conversación familiar que postergás tener tiene más costo cuanto más la postergás?", 2),
        ("¿Cómo el estilo comunicativo de tu familia te ayuda o te dificulta en otros vínculos?", 2),
        ("¿Qué cosa que nunca se habló en tu familia y que todos saben que existe te genera más incomodidad?", 2),
        ("¿Cómo distinguís en tu familia entre lo que se dice para proteger y lo que se silencia para evitar?", 2),
        ("¿Qué conversación familiar que sería incómoda pero necesaria postergás más?", 2),
        ("¿Qué no-conversación de tu familia tiene más poder sobre la dinámica del grupo que cualquier cosa que se haya dicho?", 3),
        ("¿Qué cosa que nunca le dijiste a alguien de tu familia que todavía está querés decirle antes de que no puedas?", 3),
        ("¿Cuánto del silencio en tu familia es protección y cuánto es el costo de no poder ser honestos?", 3),
        ("¿Qué conversación familiar que cambiaría algo importante si se tuviera seguís esperando el momento perfecto?", 3),
        ("¿Qué cosa no dicha en tu familia define más quiénes son que todo lo que sí dijeron?", 3),
        ("¿Cuándo fue la última vez que una conversación familiar cambió algo real y qué la hizo posible?", 3),
        ("¿Qué conversación familiar que necesitás tener te da más miedo y qué te frena exactamente?", 3),
    ],

    "amistades": [
        ("¿Cómo le decís a un amigo que algo que hizo te molestó?", 1),
        ("¿Qué tipo de conversaciones preferís tener con amigos: profundas, livianas, o una mezcla?", 1),
        ("¿Hay algo que le querés decir a un amigo y no sabés cómo?", 1),
        ("¿Cuándo fue la última vez que tuviste una conversación de verdad con un amigo?", 1),
        ("¿Qué cosa que un amigo hace que te molesta todavía no le dijiste?", 1),
        ("¿Cómo reaccionás cuando un amigo te dice algo difícil de escuchar?", 1),
        ("¿Qué tipo de escucha preferís de tus amigos: que te aconsejen, que te validen, que solo escuchen?", 1),
        ("¿Hay alguna amistad en la que la comunicación se volvió más difícil con el tiempo?", 1),
        ("¿Qué conversación con un amigo tuviste que fue incómoda pero necesaria?", 1),
        ("¿Cómo sabés que una amistad tiene la confianza suficiente para decirse las cosas difíciles?", 1),
        ("¿Qué cosa que nunca le dijiste a un amigo pero deberías le dirías hoy?", 1),
        ("¿Cuándo fue la última vez que le pediste algo a un amigo y fue fácil hacerlo?", 1),
        ("¿Cómo preferís que tus amigos te digan que algo que vos hiciste estuvo mal?", 1),
        ("¿Qué cosa en una amistad es más difícil de decir que en una relación romántica?", 1),
        ("¿Cómo manejás el silencio o la distancia en una amistad?", 1),
        ("¿Qué conversación de amistad que postergás tener es la que más necesitás?", 1),
        ("¿Hay algo que le decís solo a ciertos amigos que nunca le dirías a otros?", 1),
        ("¿Cómo sabés cuándo callarte y cuándo hablar en una conversación con un amigo?", 1),
        ("¿Qué tipo de amigo te resulta más difícil de comunicarte: el que evita el conflicto o el que lo busca?", 1),
        ("¿Qué le dirías hoy a un amigo que se fue de tu vida y con quien no pudiste cerrar bien?", 1),
        ("¿Cuánto de lo que no le decís a tus amigos se acumula y cómo afecta la amistad?", 2),
        ("¿Qué cosa que le dijiste a un amigo que en el momento te pareció difícil resultó fortalecer la amistad?", 2),
        ("¿Cómo la calidad de las conversaciones con tus amigos cambió con el tiempo y qué lo explica?", 2),
        ("¿Qué amistad perdiste parcialmente porque algo quedó sin decirse y cómo lo manejás?", 2),
        ("¿Cuándo una conversación honesta con un amigo cambió la dinámica de la amistad para mejor?", 2),
        ("¿Qué cosa que te resulta fácil decirle a un extraño sos incapaz de decirle a un amigo cercano?", 2),
        ("¿Cuánto de cómo te comunicás con tus amigos es un reflejo de cómo aprendiste a comunicarte en la infancia?", 2),
        ("¿Qué conversación que nunca tuviste con un amigo importante te hubiera cambiado algo si la hubieras tenido?", 3),
        ("¿Cuánto del silencio en tus amistades es respeto y cuánto es evitación de algo difícil?", 3),
        ("¿Qué cosa que no le decís a tus amigos te define más de lo que imaginás?", 3),
        ("¿Cuándo fue la última vez que una conversación de amistad cambió algo real en tu vida?", 3),
        ("¿Qué amistad que perdiste podría haberse salvado si alguien hubiera dicho lo que ninguno dijo?", 3),
        ("¿Qué cosa que un amigo cercano nunca te dijo y que necesitabas oír igual lo entendiste?", 3),
        ("¿Cuánto de lo más honesto de vos mismo solo puede salir en ciertas conversaciones con ciertas personas?", 3),
    ],

    "exs": [
        ("¿Qué cosa que nunca le dijiste a un ex todavía pensás en decirle?", 1),
        ("¿Cómo era la comunicación en tu relación pasada más larga?", 1),
        ("¿Qué conversación difícil con un ex que tuviste resultó ser la más honesta?", 1),
        ("¿Hay algo que un ex te dijo que tardaste tiempo en entender pero que resultó verdad?", 1),
        ("¿Cómo comunicabas lo que te molestaba en tus relaciones pasadas?", 1),
        ("¿Qué cosa que no dijiste en una relación pasada pesó más que lo que sí dijiste?", 1),
        ("¿Cómo fue la última conversación que tuviste con un ex y cómo la recordás?", 1),
        ("¿Qué cosa en una relación pasada que nunca se habló tenía todos conscientes de que existía?", 1),
        ("¿Cómo reaccionabas cuando un ex te decía algo que no querías escuchar?", 1),
        ("¿Qué estilo de comunicación de un ex que en el momento odias ahora entendés?", 1),
        ("¿Cuándo fue la última vez que le dijiste algo honesto a un ex aunque sabías que no era lo que quería escuchar?", 1),
        ("¿Qué malentendido de una relación pasada que podría haberse evitado con una conversación todavía te pesa?", 1),
        ("¿Cómo el silencio funcionaba en alguna relación pasada tuya?", 1),
        ("¿Qué cosa que un ex necesitaba que le dijeras no pudiste decirle?", 1),
        ("¿Cómo el tono de las conversaciones difíciles en una relación pasada definió el fin de esa relación?", 1),
        ("¿Qué conversación que tuviste al final de una relación que en el momento fue un desastre hoy entendés diferente?", 1),
        ("¿Hay algo que un ex te dijo que cambió permanentemente cómo te ves a vos mismo?", 1),
        ("¿Cómo manejabas el conflicto en tus relaciones pasadas versus cómo lo manejás ahora?", 1),
        ("¿Qué cosa que le pediste a un ex y te costó pedir valió la pena haberla pedido?", 1),
        ("¿Qué conversación con un ex que no se tuvo cambiaría algo si se hubiera tenido?", 1),
        ("¿Cuánto de cómo te comunicás en el amor hoy es una respuesta a cómo te comunicabas en relaciones pasadas?", 2),
        ("¿Qué cosa que nunca pudiste decirle a un ex que todavía importa imaginas que pasaría si lo dijeras?", 2),
        ("¿Qué patrón de comunicación que se repetía en una relación pasada todavía aparece en vínculos actuales?", 2),
        ("¿Qué conversación de una relación pasada que en el momento fue la más dolorosa resultó ser la más necesaria?", 2),
        ("¿Cómo el silencio en alguna relación pasada fue más dañino que cualquier pelea?", 2),
        ("¿Qué cosa que un ex te dijo que rechazaste en el momento hoy revisás con más apertura?", 2),
        ("¿Cuánto de lo que no dijiste en una relación pasada contribuyó a su fin?", 2),
        ("¿Qué conversación que nunca tuviste con alguien del pasado todavía ocupa espacio en tu cabeza?", 3),
        ("¿Cuánto del silencio que mantuviste en una relación pasada era protección y cuánto era cobardía?", 3),
        ("¿Qué cosa que te dijeron en una relación pasada y que dolió muchísimo fue sin embargo la más verdadera?", 3),
        ("¿Cuánto de lo que no dijiste en relaciones pasadas repercute en cómo te comunicás en las actuales?", 3),
        ("¿Qué conversación de cierre que nunca tuviste con alguien del pasado te impide cerrar algo completamente?", 3),
        ("¿Qué le dirías hoy a alguien del pasado si supieras que no habría consecuencias?", 3),
        ("¿Qué cosa que un ex intentó decirte de maneras que no entendiste entonces hoy ves claramente?", 3),
    ],

    "personalidad": [
        ("¿Cómo preferís comunicarte: hablando, escribiendo, o con acciones?", 1),
        ("¿Qué tipo de conversaciones te sacan lo mejor de vos?", 1),
        ("¿Cuándo te resulta más difícil decir lo que pensás?", 1),
        ("¿Sos más de decir las cosas directo o de ir rodeando el tema?", 1),
        ("¿Cómo reaccionás cuando alguien te habla de manera agresiva?", 1),
        ("¿Qué tipo de silencio te resulta cómodo y cuál te genera ansiedad?", 1),
        ("¿Cuándo fue la última vez que dijiste algo difícil que necesitabas decir?", 1),
        ("¿Qué cosa en las conversaciones te cuesta más: empezarlas, sostenerlas, o cerrarlas?", 1),
        ("¿Cómo sabés cuándo algo que estás diciendo está llegando al otro?", 1),
        ("¿Sos mejor escuchando o hablando?", 1),
        ("¿Qué tipo de conversación te agota más?", 1),
        ("¿Cómo usás el humor en conversaciones difíciles?", 1),
        ("¿Qué decís cuando no sabés qué decir?", 1),
        ("¿Cómo comunicás el afecto sin palabras?", 1),
        ("¿Qué cosa que no decís comunica igual?", 1),
        ("¿Cuándo preferís el silencio al diálogo?", 1),
        ("¿Qué tipo de interlocutor te saca lo mejor de vos?", 1),
        ("¿Cómo sabés que una conversación llegó a su punto más honesto?", 1),
        ("¿Qué cosa en tu manera de comunicarte reconocés como una limitación?", 1),
        ("¿Qué cosa en tu manera de comunicarte te parece una fortaleza?", 1),
        ("¿Cuánto de lo que comunicás es intencional y cuánto sale sin que lo planees?", 2),
        ("¿Qué cosa que no decís habla más de vos que lo que sí decís?", 2),
        ("¿Cómo tu estilo de comunicación cambia dependiendo de con quién hablás?", 2),
        ("¿Qué patrón de comunicación tuyo que reconocés como problemático todavía no pudiste cambiar?", 2),
        ("¿Cuándo fue la última vez que escuchaste de verdad sin planear tu respuesta?", 2),
        ("¿Qué cosas que no podés decir con palabras encontrás otros canales para expresar?", 2),
        ("¿Cuánto de lo que callás es estratégico y cuánto es que genuinamente no sabés cómo decirlo?", 2),
        ("¿Qué voz tuya que silenciás más en las conversaciones querés que tenga más espacio?", 3),
        ("¿Cuánto de tu comunicación real ocurre en los silencios y en lo que no decís?", 3),
        ("¿Qué cosa que querés comunicar sobre vos mismo nunca encontró las palabras adecuadas?", 3),
        ("¿Cuándo fue la última vez que dijiste algo y sentiste que te escuchaste a vos mismo de verdad?", 3),
        ("¿Qué conversación con vos mismo que evitás tener es la más necesaria?", 3),
        ("¿Cuánto de cómo te comunicás con otros es en realidad el diálogo que todavía no terminas de tener con vos mismo?", 3),
        ("¿Qué cosa que callás todo el tiempo si la dijeras una vez cambiaría algo fundamental?", 3),
    ],

    "miedos": [
        ("¿Qué tipo de conversación te genera más miedo?", 1),
        ("¿Le tenés miedo a decir lo que pensás en ciertos contextos?", 1),
        ("¿Cuándo fue la última vez que el miedo te impidió decir algo que querías decir?", 1),
        ("¿Qué miedo tenés a cómo te van a recibir cuando decís algo difícil?", 1),
        ("¿Le tenés miedo al silencio en una conversación?", 1),
        ("¿Qué tipo de respuesta del otro te genera más miedo cuando hablás?", 1),
        ("¿Qué cosa que querés decir más nunca decís por miedo?", 1),
        ("¿Le tenés miedo a que te digan que no cuando pedís algo?", 1),
        ("¿Cuándo fue la última vez que el miedo a decir algo cambió el curso de algo importante?", 1),
        ("¿Qué cosa que no podés decir te genera más ansiedad?", 1),
        ("¿Le tenés miedo a las conversaciones donde el otro llora?", 1),
        ("¿Qué tipo de conversación evitás más aunque sepas que la necesitás?", 1),
        ("¿El miedo a herir a alguien cuántas veces te impidió decir algo verdadero?", 1),
        ("¿Le tenés miedo a que te malentiendan?", 1),
        ("¿Cuándo el miedo a una conversación difícil fue peor que la conversación misma?", 1),
        ("¿Qué consecuencia de decir algo verdadero te genera más miedo?", 1),
        ("¿Le tenés miedo a las conversaciones donde el otro se enoja?", 1),
        ("¿Qué cosa no dicha en alguna relación tuya se convirtió en un fantasma?", 1),
        ("¿Cuándo fue la primera vez que el miedo a hablar te costó algo importante?", 1),
        ("¿Qué miedo a la comunicación honesta tenés que sea más irracional que real?", 1),
        ("¿Cuánto de lo que no decís está gobernado por miedos más profundos que el miedo a la conversación misma?", 2),
        ("¿Qué miedo a cómo te van a ver si decís lo que realmente pensás te limita más?", 2),
        ("¿Cuándo el miedo a una conversación difícil que evitaste terminó costándote más que si la hubieras tenido?", 2),
        ("¿Qué miedo de ser malentendido o rechazado gobierna cuánto te abrís en las conversaciones?", 2),
        ("¿Cómo el miedo al conflicto moldea lo que decís y lo que callás en tus vínculos?", 2),
        ("¿Qué miedo a las palabras del otro es en realidad un miedo a lo que podrían confirmar?", 2),
        ("¿Cuánto de lo que callás en las conversaciones está protegiendo tu imagen de una verdad que ya sabés?", 2),
        ("¿Qué cosa que no decís por miedo en el fondo ya saben todos aunque no lo nombres?", 3),
        ("¿Cuánto de lo que evitás decir está en realidad guardando algo que ya no podés guardar?", 3),
        ("¿Qué conversación que evitás tener por miedo es la que más te define evitar?", 3),
        ("¿Cuánto de tu silencio en ciertos temas es miedo genuino y cuánto es comodidad?", 3),
        ("¿Qué miedo a decir algo verdadero sobre vos mismo es en realidad miedo a que sea verdad?", 3),
        ("¿Qué conversación que te generó terror tener y que sin embargo tuviste resultó ser diferente a lo que temías?", 3),
        ("¿Cuándo fue la última vez que el coraje de decir algo difícil cambió algo importante para mejor?", 3),
    ],

    "logros": [
        ("¿Cuándo fue la primera vez que pediste ayuda abiertamente y resultó bien?", 1),
        ("¿Qué logro tuyo fue posible porque alguien te dijo algo difícil que necesitabas escuchar?", 1),
        ("¿Cuándo fue la última vez que dar una retroalimentación honesta te costó y valió la pena?", 1),
        ("¿Qué cosa que te dijeron que era una crítica resultó ser el punto de partida de un logro?", 1),
        ("¿Cómo comunicás tus logros a los demás: con orgullo, con modestia, con indiferencia?", 1),
        ("¿Qué habilidad de comunicación fue clave en algún logro importante tuyo?", 1),
        ("¿Cuándo fue la primera vez que decir lo que querías claramente te llevó a conseguirlo?", 1),
        ("¿Qué conversación difícil que tuviste en el ámbito laboral o profesional resultó ser un punto de inflexión?", 1),
        ("¿Cómo aprender a pedir claramente lo que querías cambió algo en tu vida?", 1),
        ("¿Qué cosa que dijiste que te costó decir abrió una puerta que no esperabas?", 1),
        ("¿Cuándo fue la última vez que una conversación honesta cambió el rumbo de algo importante?", 1),
        ("¿Qué logro tuyo empezó con una conversación difícil que evitabas tener?", 1),
        ("¿Cómo cambió tu carrera o vida cuando empezaste a comunicar lo que realmente querías?", 1),
        ("¿Qué cosa que nunca te animabas a pedir pediste una vez y resultó mucho mejor de lo que esperabas?", 1),
        ("¿Cuándo fue la primera vez que decir la verdad aunque no fuera lo que el otro quería escuchar te llevó a algo mejor?", 1),
        ("¿Qué logro de comunicación personal te da más orgullo: aprender a escuchar, a pedir, a decir que no?", 1),
        ("¿Cómo tu manera de comunicarte evolucionó en función de los logros que querías alcanzar?", 1),
        ("¿Qué conversación que tuviste y que requirió mucho coraje resultó ser la que más avanzó algo?", 1),
        ("¿Cuándo fue la primera vez que expresar una opinión impopular resultó ser la decisión correcta?", 1),
        ("¿Qué logro que conseguiste fue directamente el resultado de haber podido decir algo que antes no podías?", 1),
        ("¿Cuánto de lo que lograste fue posible porque aprendiste a comunicarte de manera más efectiva?", 2),
        ("¿Qué conversación difícil en el ámbito laboral que postergabas tener y que finalmente tuviste cambió algo?", 2),
        ("¿Cuándo fue la primera vez que el coraje de decir lo que pensabas en público te llevó a algo que no esperabas?", 2),
        ("¿Qué cosa que aprendiste a decir o no decir en el ámbito profesional fue el cambio más importante?", 2),
        ("¿Cuánto de tus logros dependen de poder comunicarte de manera que el otro reciba lo que realmente querés transmitir?", 2),
        ("¿Qué feedback que recibiste que fue difícil de escuchar resultó ser el más valioso para un logro?", 2),
        ("¿Cuándo aprender a decir que no claramente fue en realidad el punto de partida de algo mejor?", 2),
        ("¿Qué conversación que nunca tuviste y que postergaste por miedo terminó costándote un logro que podrías haber tenido?", 3),
        ("¿Cuánto de lo que lograste requirió aprender a hablar de vos mismo de maneras que antes no podías?", 3),
        ("¿Qué voz tuya que antes callabas que empezaste a usar cambió el tipo de logros que alcanzás?", 3),
        ("¿Cuándo fue la primera vez que la honestidad brutal en una conversación profesional te costó algo a corto plazo pero te ganó algo más importante?", 3),
        ("¿Qué logro futuro tuyo depende de tener una conversación que todavía estás postergando?", 3),
        ("¿Cuánto de lo que querés lograr está esperando que puedas decir algo que todavía no podés decir?", 3),
        ("¿Qué cosa que aprendiste a comunicar sobre vos mismo cambió el tipo de oportunidades que aparecen?", 3),
    ],

    "sinFiltro": [
        ("¿Cuándo fue la última vez que dijiste exactamente lo que pensabas sin filtrar nada?", 1),
        ("¿Qué cosa que siempre callás necesitás decir en voz alta aunque sea una vez?", 1),
        ("¿Hay alguien a quien querés decirle algo hace tiempo y no te animás?", 1),
        ("¿Qué cosa que pensás sobre alguien cercano nunca dijiste y nunca vas a decir?", 1),
        ("¿Cuándo fue la última vez que le dijiste a alguien lo que realmente pensás de él o ella sin suavizarlo?", 1),
        ("¿Qué cosa que le dirías a tu jefe si no hubiera consecuencias?", 1),
        ("¿Cuándo fue la última vez que te dijeron algo tan directo que al principio dolió pero después fue un regalo?", 1),
        ("¿Qué cosa que la gente nunca te dice sobre vos mismo crees que piensan?", 1),
        ("¿Cuándo fue la última vez que callaste algo que querías decir y luego te arrepentiste de haberlo callado?", 1),
        ("¿Qué cosa que normalmente endulzás o suavizás necesitás decir tal cual?", 1),
        ("¿Cuándo fue la última vez que alguien fue completamente honesto con vos y cómo lo recibiste?", 1),
        ("¿Qué opinión tuya que es impopular en tu círculo más cercano sostenés en silencio?", 1),
        ("¿Hay algo que le dirías a alguien que ya murió que nunca pudiste decirle?", 1),
        ("¿Qué cosa que te dijeron que te dolió mucho fue sin embargo completamente verdad?", 1),
        ("¿Cuándo fue la última vez que le dijiste a alguien que lo o la amás de manera completamente directa?", 1),
        ("¿Qué cosa que nunca decís abiertamente sobre vos mismo en el fondo querés que todos sepan?", 1),
        ("¿Cuándo fue la última vez que recibiste una crítica honesta y pudiste escucharla sin defenderte?", 1),
        ("¿Qué tema que todos piensan pero nadie dice en tu entorno más cercano?", 1),
        ("¿Cuándo fue la última vez que dijiste algo verdadero que incomodó a todos pero era necesario?", 1),
        ("¿Qué cosa que les callás a las personas que amás por no lastimarlas ya saben igual?", 1),
        ("¿Qué conversación sin filtros que necesitás tener con vos mismo seguís evitando?", 2),
        ("¿Cuánto de lo que no decís es para proteger al otro y cuánto es para protegerte vos de las consecuencias?", 2),
        ("¿Qué cosa verdadera sobre vos mismo que nadie te dice porque les da miedo necesitás escuchar?", 2),
        ("¿Cuándo fue la última vez que la honestidad brutal tuya o de alguien cambió algo real?", 2),
        ("¿Qué cosa que decís con rodeos querés poder decir alguna vez de manera directa?", 2),
        ("¿Cuánto de lo que callás es sabiduría y cuánto es cobardía honesta?", 2),
        ("¿Qué cosa que le callás a alguien por amor te está costando a vos mismo?", 2),
        ("¿Qué necesitaría pasar para que pudieras decir lo más honesto que tenés de vos mismo en voz alta?", 3),
        ("¿Cuándo fue la última vez que dijiste algo completamente sin filtros y el resultado fue mejor de lo que esperabas?", 3),
        ("¿Qué cosa que todos ven pero nadie dice de tu situación actual necesita ser nombrada?", 3),
        ("¿Cuánto de lo que silenciás sobre vos mismo te está costando más de lo que imaginás?", 3),
        ("¿Qué conversación completamente honesta con alguien que amás si la tuvieras cambiaría algo fundamental?", 3),
        ("¿Qué verdad sobre vos mismo que callás hace mucho tiempo si la dijeras en voz alta a alguien de confianza cambiaría algo?", 3),
        ("¿Qué frase que nunca te animaste a decir necesita ser dicha aunque sea una vez antes de que pase demasiado tiempo?", 3),
    ],
}


def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]


def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS29:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS29[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")


if __name__ == "__main__":
    main()
