#!/usr/bin/env python3
"""Batch 34 - creativity, art, expression, making things, imagination, aesthetic sensibilities."""
import json

ADDITIONS34 = {
    "infancia": [
        ("¿Qué cosa creabas de chico que te generaba más orgullo?", 1),
        ("¿Dibujabas, pintabas o hacías manualidades cuando eras chico?", 1),
        ("¿Hubo algún maestro o adulto que alimentó tu lado creativo?", 1),
        ("¿Qué historias inventabas o te contabas a vos mismo cuando eras chico?", 1),
        ("¿Tenías algún mundo imaginario propio cuando eras chico?", 1),
        ("¿Tocabas algún instrumento o querías aprender alguno de chico?", 1),
        ("¿Qué hacías cuando te aburrías de chico y nadie te decía qué hacer?", 1),
        ("¿Coleccionabas algo de chico? ¿Qué decía eso de vos?", 1),
        ("¿Cuál fue la primera obra de arte, película o libro que te impactó de chico?", 1),
        ("¿Qué inventabas o construías con lo que tenías a mano?", 1),
        ("¿Cantabas o bailabas cuando eras chico sin que nadie te mirara?", 1),
        ("¿Había algo en lo que eras especialmente creativo de chico que dejaste de hacer?", 1),
        ("¿Qué soñabas de noche o de día que te parecía tuyo y único?", 1),
        ("¿Cuál fue la primera cosa que hiciste con tus manos de la que estuviste orgulloso?", 1),
        ("¿Qué juego inventabas con las reglas propias?", 1),
        ("¿Qué hacías en el espacio entre las actividades que nadie organizaba para vos?", 1),
        ("¿Alguien en tu infancia te dijo que eras creativo o que no lo eras y cómo te afectó?", 1),
        ("¿Cuál fue la primera vez que sentiste que hiciste algo que era tuyo, que vino de vos?", 1),
        ("¿Qué color, forma o imagen te parecía especialmente tuya de chico?", 1),
        ("¿Escribías cosas de chico — diario, cuentos, cartas — que guardabas en secreto?", 1),
        ("¿Hubo algo que te enseñaron a hacer de manera creativa que todavía llevás con vos?", 1),
        ("¿Qué actividad creativa te quitaron o limitaron de chico y qué sentiste?", 1),
        ("¿Qué parte de tu imaginación de chico sobrevive en vos hoy?", 1),
        ("¿Cuándo sentiste por primera vez que tenías un gusto propio, diferente al de todos?", 1),
        ("¿Qué cosas hacías de chico que, en retrospectiva, eran expresiones de quién ibas a ser?", 1),
        ("¿Cómo la creatividad de tu infancia sobrevivió o no al sistema educativo?", 2),
        ("¿Qué mundo imaginario de tu infancia te hubiera gustado poder mostrarle a alguien?", 2),
        ("¿Qué talento creativo de chico dejaste ir y qué te costó reconocerlo?", 2),
        ("¿Cómo la manera en que tus padres valoraban (o no) la creatividad te formó?", 2),
        ("¿Qué cosa creabas de chico que hoy entendés que era tu forma de procesar el mundo?", 2),
        ("¿Si pudieras recuperar un pedazo de tu imaginación de chico, cuál sería?", 2),
        ("¿Qué historia inventabas de chico que dice algo sobre tus miedos o deseos más profundos?", 2),
        ("¿Qué te pasaría si le mostraras a tu yo adulto la cosa más honesta que creaste de chico?", 2),
        ("¿De qué manera la vergüenza en la infancia frenó algo creativo en vos?", 2),
        ("¿Qué parte de tu identidad creativa actual tiene raíces directas en algo que hacías de chico?", 2),
        ("¿Qué versión creativa de vos mismo murió en algún momento de la infancia y cuándo?", 3),
        ("¿Qué hiciste de chico que nunca le mostraste a nadie y qué significó ese secreto?", 3),
        ("¿Qué le hubiera pasado a tu creatividad si alguien importante la hubiera validado en lugar de ignorarla?", 3),
        ("¿Cuánto de lo que creabas de chico era una forma de pedir que te vieran?", 3),
        ("¿Qué hubiera cambiado en vos si en tu infancia te hubieran enseñado que crear era tan importante como aprender?", 3),
    ],

    "futuro": [
        ("¿Qué cosa te gustaría crear o hacer antes de morir que todavía no empezaste?", 1),
        ("¿Te imaginás en el futuro dedicando más tiempo a alguna expresión creativa?", 1),
        ("¿Qué arte o habilidad creativa querés aprender en el futuro?", 1),
        ("¿Cómo imaginás que va a evolucionar tu gusto estético en los próximos años?", 1),
        ("¿Te imaginás viviendo en un espacio que refleje más tu estética propia?", 1),
        ("¿Qué cosa querés haber creado cuando llegues a viejo?", 1),
        ("¿Cómo querés que sea tu relación con el arte y la cultura en el futuro?", 1),
        ("¿Hay algún proyecto creativo que postergás y que en el futuro querés haber hecho?", 1),
        ("¿Qué cosa creativa querés enseñarle a alguien que querés?", 1),
        ("¿Cómo imaginás que la inteligencia artificial va a cambiar tu relación con la creatividad?", 1),
        ("¿Qué espacio físico o mental querés crear en tu vida para tener más expresión creativa?", 1),
        ("¿Cómo querés que el arte y la belleza sean parte de tu vida cotidiana futura?", 1),
        ("¿Qué forma de expresión artística te gustaría explorar que nunca probaste?", 1),
        ("¿Cómo querés que sea el ambiente estético del hogar donde vivás en 10 años?", 1),
        ("¿Qué legado creativo querés dejar, aunque sea pequeño?", 1),
        ("¿Cómo querés que la creatividad forme parte de tu trabajo o vida profesional en el futuro?", 1),
        ("¿Qué cosa creativa querés hacer que hoy te parece demasiado ambiciosa o ridícula?", 1),
        ("¿Qué libro, canción, película o pieza de arte querés haber creado antes de que sea tarde?", 1),
        ("¿Cómo querés que la creatividad te ayude a envejecer de la manera que querés?", 1),
        ("¿Qué versión creativa de vos mismo querés haber desarrollado en 20 años?", 1),
        ("¿Cómo imaginás que va a cambiar lo que te parece bello o estético a medida que envejecés?", 1),
        ("¿Qué cosa hacés hoy de manera creativa que querés que sea una constante en tu futuro?", 1),
        ("¿Cómo la creatividad puede ser para vos una forma de procesar el paso del tiempo?", 1),
        ("¿Qué parte de tu mundo interior querés externalizar alguna vez a través del arte o la expresión?", 1),
        ("¿Qué futuro imaginás para las personas que se dedican al arte en un mundo con inteligencia artificial?", 1),
        ("¿Cómo querés usar la creatividad para construir algo que valga la pena cuando ya no estés?", 2),
        ("¿Qué parte de vos que no expresás hoy querés animarte a mostrar en el futuro?", 2),
        ("¿Cómo el miedo al juicio ajeno frena tu expresión creativa y cómo querés resolverlo?", 2),
        ("¿Qué proyecto creativo postergado dice más de tus miedos que de tu falta de tiempo?", 2),
        ("¿Cómo querés que la creatividad te ayude a encontrar sentido cuando todo lo demás se vuelva incierto?", 2),
        ("¿Qué talento creativo no desarrollaste que en el futuro querés haber honrado aunque sea un poco?", 2),
        ("¿Cómo la creatividad puede ser un acto de resistencia frente a un mundo que te define por lo que producís?", 3),
        ("¿Qué cosa querés crear que sea completamente tuya, sin audiencia, sin validación?", 3),
        ("¿Si supieras que nadie va a ver lo que creás, qué crearías?", 3),
        ("¿Cómo el hecho de que la IA pueda crear arte cambia el significado de que vos lo hagas?", 3),
        ("¿Qué cosa querés haber hecho creativamente que pruebe que estuviste acá, que exististe?", 3),
        ("¿Cómo el acto de crear te conecta con algo más grande que vos mismo?", 3),
        ("¿Qué cosa creativa no hiciste todavía por miedo a que no sea lo suficientemente buena?", 3),
        ("¿Qué le querés dejar a alguien que amás que sea completamente tuyo, hecho con tus manos o tu mente?", 3),
        ("¿Si en el futuro solo pudieras hacer una cosa creativa, cuál elegirías y qué te dice eso de vos?", 3),
    ],

    "amor": [
        ("¿Qué cosa creaste o hiciste con tus manos para alguien que amabas?", 1),
        ("¿Qué música te recuerda a una persona que amaste?", 1),
        ("¿Cómo sabés que alguien tiene buen gusto y si eso te importa en una pareja?", 1),
        ("¿Qué dice de una persona la música que escucha o el arte que consume?", 1),
        ("¿Alguna vez alguien te dedicó algo creativo — una canción, una carta, algo hecho a mano?", 1),
        ("¿Qué película, canción o libro asociás con una relación amorosa importante?", 1),
        ("¿Cómo el gusto estético compartido (o no) afecta una relación para vos?", 1),
        ("¿Qué cosa hiciste creativamente para seducir o enamorar a alguien?", 1),
        ("¿Qué cosa creativa de alguien te enamoró o te atrajo?", 1),
        ("¿Cuánto te importa que tu pareja tenga sus propios intereses creativos?", 1),
        ("¿Qué espacio en tu hogar dice más de quién sos y cómo querés que lo reciba alguien que te visita?", 1),
        ("¿Alguna vez escribiste algo — carta, poema, mensaje — para alguien que amabas?", 1),
        ("¿Qué cosa estética o artística compartida fue parte importante de una relación?", 1),
        ("¿Cómo expresás el amor de maneras creativas o simbólicas?", 1),
        ("¿Qué cosa hecha a mano o creada por vos le darías a alguien que amás?", 1),
        ("¿Qué dice del amor que alguien haga algo con sus manos para vos?", 1),
        ("¿Qué artista, libro o película conociste gracias a alguien que amaste?", 1),
        ("¿Cómo la creatividad o la imaginación de alguien te atrae o te enamora?", 1),
        ("¿Qué cosa creativa compartís o compartiste con alguien importante en tu vida?", 1),
        ("¿Cuánto te importa que alguien aprecie lo que hacés creativamente?", 1),
        ("¿Qué objeto o creación guardás que te conecta con alguien que amaste?", 1),
        ("¿Cómo el gusto de alguien por el arte, la música o la literatura te dice algo sobre su mundo interior?", 1),
        ("¿Qué playlist o canción le harías hoy a alguien que querés?", 1),
        ("¿Qué cosa creativa hiciste en una relación que hoy te parece increíble que hiciste?", 1),
        ("¿Qué forma de expresión artística querés compartir con tu pareja o con alguien que amás?", 1),
        ("¿Qué dice de un amor cuando la estética y la sensibilidad de dos personas se encuentran?", 2),
        ("¿Cómo la creatividad de alguien puede revelar cosas de su personalidad que no se ven de otra manera?", 2),
        ("¿Qué cosa creaste o escribiste en un momento de dolor amoroso que te sorprendió?", 2),
        ("¿Cómo la sensibilidad artística de alguien puede conectar o separar de una manera que va más allá de lo racional?", 2),
        ("¿Qué hubiera pasado con una relación si hubieras tenido más espacio para expresarte creativamente en ella?", 2),
        ("¿Qué dice de una relación cuando la creatividad propia tiene que frenarse para que el otro se sienta bien?", 2),
        ("¿Qué cosa creativa hiciste en nombre del amor que nadie sabe que fue por eso?", 3),
        ("¿Cómo la capacidad de crear o imaginar de alguien puede ser la cosa más seductora de su persona?", 3),
        ("¿Qué parte de tu expresión creativa usaste alguna vez para decir algo que no podías decir de otra manera?", 3),
        ("¿Qué le crearías a alguien que querés si no te importara si lo entiende o lo aprecia?", 3),
        ("¿Cómo el arte o la expresión creativa puede ser más honesto que las palabras en el amor?", 3),
        ("¿Qué objeto, carta o creación tuya querés que alguien que amás tenga después de que no estés?", 3),
        ("¿Cuánto de lo que creaste en tu vida fue en realidad una forma de amar a alguien o de procesar ese amor?", 3),
        ("¿Qué cosa creativa que le prometiste a alguien todavía no hiciste?", 3),
        ("¿Si pudieras crear una sola cosa para la persona que más amás, qué sería?", 3),
    ],

    "familia": [
        ("¿Había algún talento creativo en tu familia que se transmitía de generación en generación?", 1),
        ("¿Algún familiar tuyo es o fue artista, músico o alguien que creaba cosas?", 1),
        ("¿Cómo se valoraba (o no) la creatividad en tu familia?", 1),
        ("¿Hay algún objeto hecho a mano en tu familia que tiene un significado especial?", 1),
        ("¿Qué cosa creativa hacías con tu familia cuando eras chico?", 1),
        ("¿Alguien de tu familia te enseñó a hacer algo con las manos que todavía hacés o valorás?", 1),
        ("¿Qué músicas, libros o películas eran parte del mundo estético de tu familia?", 1),
        ("¿Cómo el gusto de tus padres o familia formó o chocó con el tuyo?", 1),
        ("¿Hay alguna tradición creativa o artística en tu familia que querés mantener viva?", 1),
        ("¿Qué dice del mundo interior de tu familia lo que decoraba o no decoraba su casa?", 1),
        ("¿Algún familiar tuyo tenía un talento que nunca pudo desarrollar y cómo te afectó eso?", 1),
        ("¿Qué cosa creativa de alguien de tu familia te parece increíble y no le dijiste lo suficiente?", 1),
        ("¿Cómo la música era o no parte del ambiente de tu familia?", 1),
        ("¿Qué objeto creado o hecho a mano en tu familia querés guardar o ya guardás?", 1),
        ("¿Cuál fue la primera vez que tu familia te vio hacer algo creativo y cómo reaccionaron?", 1),
        ("¿Hay algún arte o habilidad creativa que querés transmitirle a las generaciones que vienen?", 1),
        ("¿Cómo la creatividad de alguien de tu familia te inspiró aunque no lo hayas reconocido antes?", 1),
        ("¿Qué espacio en la casa de tu infancia era el más propio, el más tuyo estéticamente?", 1),
        ("¿Cómo la falta de espacio para la expresión creativa en tu familia te afectó?", 1),
        ("¿Qué talento creativo de alguien de tu familia desearías haber heredado?", 1),
        ("¿Qué le crearías o harías con tus manos para alguien de tu familia que más lo necesita?", 1),
        ("¿Cómo el gusto artístico o estético de tu familia define o no tu propia sensibilidad?", 1),
        ("¿Qué historia o mito familiar fue el que más estimuló tu imaginación de chico?", 1),
        ("¿Qué cosa hacía alguien de tu familia con las manos que te llenaba de admiración?", 1),
        ("¿Cuánto del gusto estético que tenés hoy viene de tu familia y cuánto es tuyo?", 1),
        ("¿Cómo la represión o la apertura creativa en tu familia moldeó tu relación con la expresión artística?", 2),
        ("¿Qué talento creativo familiar fue ignorado o aplastado y qué efecto tuvo eso en la familia?", 2),
        ("¿Cómo la estética del hogar donde creciste formó tu sensibilidad de maneras que recién ahora entendés?", 2),
        ("¿Qué cosa creativa haría alguien de tu familia que cambiaría cómo los ves?", 2),
        ("¿De qué manera la creatividad puede ser una forma de sanar o procesar la historia familiar?", 2),
        ("¿Qué parte de la historia de tu familia querés preservar o expresar de una manera creativa?", 2),
        ("¿Qué dice de vos lo que creás cuando pensás en alguien de tu familia que ya no está?", 3),
        ("¿Qué le crearías o le dejarías a alguien de tu familia para que te recuerde?", 3),
        ("¿De qué manera el arte o la expresión creativa puede decir lo que en tu familia nunca se dijo en palabras?", 3),
        ("¿Qué cosa de la historia de tu familia querés que no se pierda y cómo la vas a preservar?", 3),
        ("¿Qué herida familiar podría cerrarse a través de algo creado o expresado?", 3),
        ("¿Cuánto de lo que creás es en realidad una conversación con alguien de tu familia?", 3),
        ("¿Qué tradición creativa querés inventar en tu familia que no existía antes?", 3),
        ("¿Qué objeto creado por alguien que ya no está es para vos el objeto más precioso que tenés?", 3),
        ("¿Si pudieras crear algo que capturara la esencia de tu familia, cómo sería?", 3),
    ],

    "amistades": [
        ("¿Tus amigos más cercanos son creativos? ¿Eso te importa?", 1),
        ("¿Algún amigo te presentó a un artista, músico o libro que cambió algo en vos?", 1),
        ("¿Tenés amigos con quienes compartís algo creativo — música, arte, escritura?", 1),
        ("¿Alguna vez hiciste algo creativo junto con un amigo?", 1),
        ("¿Qué dice de una amistad compartir el mismo gusto musical o estético?", 1),
        ("¿Hay algún amigo tuyo con un talento creativo que te genera admiración?", 1),
        ("¿Alguna vez un amigo creó algo para vos o vos para él/ella?", 1),
        ("¿Qué tipo de gusto o sensibilidad estética buscás en las personas con quienes te juntás?", 1),
        ("¿Cómo el gusto artístico compartido (o no) afecta una amistad?", 1),
        ("¿Alguna vez un amigo te dio una crítica de algo que creaste y cómo la recibiste?", 1),
        ("¿Hay amistades que te inspiran creativamente sin que te des cuenta?", 1),
        ("¿Qué harías creativamente con tu mejor amigo si tuvieran un fin de semana sin planes?", 1),
        ("¿Hay algún amigo con quien compartas ese tipo de silencio creativo — escuchar música, ver arte — sin necesidad de hablar?", 1),
        ("¿Qué banda, película o libro se convirtió en parte de una amistad importante?", 1),
        ("¿Cómo la creatividad de un amigo puede revelar cosas que de otra manera no sabrías de él/ella?", 1),
        ("¿Qué dice de vos el tipo de personas creativas que te rodean o querés que te rodeen?", 1),
        ("¿Tenés alguna amistad donde la creatividad sea el lenguaje principal?", 1),
        ("¿Qué cosa creativa compartís solo con un círculo muy pequeño de personas?", 1),
        ("¿Hay algún amigo con quien tengas un lenguaje creativo propio, que sea solo de ustedes?", 1),
        ("¿Qué le crearías o le darías a un amigo para que sepa cuánto lo valorás?", 1),
        ("¿Cómo las amistades que tenés ahora alimentan o frenan tu lado creativo?", 1),
        ("¿Qué artista o creador conociste gracias a un amigo que cambió algo en vos?", 1),
        ("¿Cómo buscás amigos que te desafíen a ver el mundo de manera diferente?", 1),
        ("¿Qué tipo de conversación sobre arte, música o creatividad te resulta la más nutritiva?", 1),
        ("¿Cuánto de tu gusto propio fue moldeado por las personas con quienes te juntaste?", 1),
        ("¿Cómo la creatividad puede ser la base de una amistad más profunda que la historia compartida?", 2),
        ("¿Qué amistad importante perdiste y qué quedó de ella en tu gusto o sensibilidad?", 2),
        ("¿De qué manera estar rodeado de personas creativas cambia lo que vos mismo te animás a crear?", 2),
        ("¿Qué le mostraste a un amigo que lo transformó y él/ella nunca supo que fue algo tuyo?", 2),
        ("¿Cómo el miedo al juicio de tus amigos frena tu expresión creativa?", 2),
        ("¿Qué amistad nació de compartir algo creativo y qué te enseñó eso?", 2),
        ("¿Qué cosa creativa de un amigo te genera envidia y qué dice esa envidia de vos?", 3),
        ("¿Cómo la creatividad compartida puede ser más íntima que muchas conversaciones?", 3),
        ("¿Qué amigo conoce tu lado más creativo y qué significa que lo conozca?", 3),
        ("¿Qué hubiera pasado si en tu círculo de amigos la creatividad hubiera sido más valorada?", 3),
        ("¿Cuánto de lo que creás lleva la huella de alguien que fue importante para vos aunque ya no esté?", 3),
        ("¿Qué cosa creaste o vas a crear alguna vez que sea un homenaje a alguien que querés?", 3),
        ("¿Qué amistades alimentan tu imaginación y cuáles la secan sin que te des mucha cuenta?", 3),
        ("¿Qué cosa creativa haría tu mejor amigo que te dejaría sin palabras?", 3),
        ("¿Cómo la creatividad puede ser la manera más honesta de conocer a alguien de verdad?", 3),
    ],

    "exs": [
        ("¿Qué música o artista te recuerda a alguien con quien estuviste?", 1),
        ("¿Alguna vez creaste algo — una canción, un texto, algo — sobre o por alguien del pasado?", 1),
        ("¿Cómo el gusto artístico compartido con un ex fue parte importante de esa relación?", 1),
        ("¿Hay alguna película, libro o canción que ya no podés disfrutar de la misma manera por alguien del pasado?", 1),
        ("¿Algún ex o ex amigo/a te presentó a algo creativo que se quedó con vos para siempre?", 1),
        ("¿Qué cosa creativa conservás o tiraste que tenía que ver con alguien del pasado?", 1),
        ("¿Alguna vez usaste el arte o la escritura para procesar el final de una relación?", 1),
        ("¿Qué cosa creaste durante o después de una relación que te sorprendió que pudiste hacer?", 1),
        ("¿Hay alguna canción o playlist que fue de una relación y ahora es solo tuya?", 1),
        ("¿Qué lugar, canción o obra de arte está marcado por alguien que ya no está en tu vida?", 1),
        ("¿Cómo la creatividad de un ex fue algo que te atrajo y qué pasó cuando eso cambió?", 1),
        ("¿Qué objeto o creación hecha a mano guarda demasiada memoria de alguien?", 1),
        ("¿Alguna vez encontraste algo creado por alguien del pasado y qué sentiste?", 1),
        ("¿Qué cosa creativa te quedó de alguien que te gustó mucho aunque la relación no funcionara?", 1),
        ("¿Cómo cambia una obra de arte o una canción cuando la asociás a alguien del pasado?", 1),
        ("¿Qué dice de vos lo que creaste durante las etapas más dolorosas de relaciones pasadas?", 2),
        ("¿Cómo el duelo por alguien que querías se transformó alguna vez en algo creativo tuyo?", 2),
        ("¿Qué parte de tu sensibilidad estética fue moldeada por alguien con quien estuviste?", 2),
        ("¿Qué canción o artista que amabas perdiste de alguna manera porque la otra persona lo reclamó como propio?", 2),
        ("¿Cómo la creatividad propia puede ser un camino para recuperarte de algo que dolió?", 2),
        ("¿Qué cosa hubiera sido diferente en una relación si hubieran compartido más espacio creativo?", 2),
        ("¿Qué cosa creaste pensando en alguien del pasado que nunca le mostraste?", 3),
        ("¿Cómo el arte o la expresión creativa puede ser más honesto que las palabras para cerrar algo?", 3),
        ("¿Qué parte de vos se expresó más libremente durante o después de una ruptura y por qué?", 3),
        ("¿Cuánto de lo que creás todavía tiene conversaciones no resueltas con alguien del pasado?", 3),
        ("¿Qué le crearías a alguien que alguna vez te importó mucho si pudieras sin ninguna consecuencia?", 3),
        ("¿Qué canción o obra de arte le pertenece a una versión de vos que ya no existe?", 3),
        ("¿Qué cosa creativa hiciste en el fondo para alguien aunque nunca lo reconocieras?", 3),
        ("¿Cómo el arte te ayudó o no te ayudó a entender por qué algo no funcionó?", 3),
        ("¿Qué le dirías a alguien del pasado a través de algo creado que no podés decirle de otra manera?", 3),
        ("¿Qué artista o canción empezaste a escuchar después de que alguien se fue y qué buscabas en eso?", 1),
        ("¿Cómo tu gusto estético cambió después de una relación importante?", 1),
        ("¿Qué cosa del mundo creativo de alguien del pasado todavía te resulta difícil de apropiarte como tuya?", 1),
        ("¿Hay alguna obra de arte o canción que no podés escuchar sin volver a alguien del pasado?", 1),
        ("¿Qué hubiera sido diferente en una relación si la creatividad hubiera tenido más espacio?", 2),
        ("¿Cómo el gusto artístico de alguien con quien estuviste todavía influye en lo que consumís hoy?", 2),
        ("¿Qué cosa creativa descubriste gracias a alguien del pasado que ahora es completamente tuya?", 2),
        ("¿Qué dice de una relación perdida el hecho de que su música o su arte todavía te alcance?", 3),
        ("¿Qué creación tuya tiene una deuda no reconocida con alguien con quien estuviste?", 3),
        ("¿Cómo una relación pasada te abrió o te cerró a ciertas formas de expresión que hoy te definen?", 3),
    ],

    "personalidad": [
        ("¿Te considerás una persona creativa? ¿Por qué sí o por qué no?", 1),
        ("¿Cuál es tu forma favorita de expresarte creativamente?", 1),
        ("¿Qué tipo de arte o expresión te genera la emoción más genuina?", 1),
        ("¿Cómo describís tu gusto estético en pocas palabras?", 1),
        ("¿Sos más de crear o de consumir arte y por qué?", 1),
        ("¿Qué hacés con tus manos que te da satisfacción?", 1),
        ("¿Cuándo fue la última vez que algo te pareció verdaderamente bello?", 1),
        ("¿Cómo la música afecta tu estado de ánimo y qué dice eso de vos?", 1),
        ("¿Qué artista, músico o escritor sentís que habla directamente de tu mundo interior?", 1),
        ("¿Cuándo sentís que sos más creativo: solo o con otros?", 1),
        ("¿Qué dice de vos la estética del espacio donde vivís o trabajás?", 1),
        ("¿Sos de los que terminan lo que empiezan creativamente o lo dejás ir?", 1),
        ("¿Qué forma de expresión creativa te gustaría desarrollar más?", 1),
        ("¿Qué cosa creativa hacés que nadie sabe?", 1),
        ("¿Cuánto necesitás de belleza o estética en tu vida cotidiana para estar bien?", 1),
        ("¿Qué dice de tu personalidad lo que encontrás bello que a otros les parece ordinario?", 1),
        ("¿Cómo describís tu relación con el orden, el caos y la estética en los espacios donde vivís?", 1),
        ("¿Qué tipo de música escuchás cuando querés estar completamente en vos mismo?", 1),
        ("¿Qué obra de arte, canción o libro te parece que te describe mejor que cualquier cosa que puedas decir de vos?", 1),
        ("¿Qué forma de expresión creativa abandonaste y qué te costó?", 1),
        ("¿Cómo la creatividad te ayuda a procesar lo que no podés procesar de otra manera?", 1),
        ("¿Cuándo sentís que estás en estado de flujo creativo y qué lo genera?", 1),
        ("¿Qué hace que algo te parezca bello o artísticamente poderoso?", 1),
        ("¿Qué cosa creativa hacés que, aunque no seas experto, te genera satisfacción genuina?", 1),
        ("¿Qué parte de tu sensibilidad estética viene de vos y cuál aprendiste de otros?", 1),
        ("¿Qué dice de vos la diferencia entre lo que creás para vos mismo y lo que mostrás a otros?", 2),
        ("¿Cómo la crítica a algo que creaste te afecta diferente a la crítica a otras cosas?", 2),
        ("¿Qué parte de tu expresión creativa es la más honesta sobre quién sos?", 2),
        ("¿Cómo la creatividad refleja o contradice otras partes de tu personalidad?", 2),
        ("¿Qué cosa creativa no hacés por miedo a no ser suficientemente bueno?", 2),
        ("¿Cómo tu relación con la creatividad cambió desde que eras chico?", 2),
        ("¿Qué dice de vos profundamente la cosa más oscura o extraña que creaste o que te gusta?", 3),
        ("¿Qué parte de vos solo aparece cuando estás en medio de algo creativo?", 3),
        ("¿Cuánto de lo que creás es en realidad la persona que querés ser y no la que sos?", 3),
        ("¿Qué te revelaría sobre vos mismo si analizaras todo lo que creaste en los últimos 10 años?", 3),
        ("¿Qué cosa querés crear que te da miedo porque dice demasiado de vos?", 3),
        ("¿Cómo la creatividad puede ser al mismo tiempo tu parte más libre y tu mayor vulnerabilidad?", 3),
        ("¿Qué cosa creativa te define más que cualquier palabra que usarías para describirte?", 3),
        ("¿Si tu vida entera fuera una obra de arte, de qué género sería y por qué?", 3),
        ("¿Qué cosa creaste que cambió cómo te ves a vos mismo aunque nadie más lo haya visto?", 3),
    ],

    "miedos": [
        ("¿Te da miedo mostrar algo que creaste o expresaste? ¿Por qué?", 1),
        ("¿Qué te genera más miedo: no tener ideas o tener ideas que no podés ejecutar?", 1),
        ("¿Le tenés miedo al juicio de los demás cuando expresás algo propio?", 1),
        ("¿Alguna vez el miedo al ridículo frenó algo creativo que querías hacer?", 1),
        ("¿Qué parte de tu creatividad censurás antes de que nadie más pueda opinar?", 1),
        ("¿Le tenés miedo a que tu gusto o sensibilidad sea juzgado por ser demasiado o poco sofisticado?", 1),
        ("¿Qué miedo relacionado con la creación o el arte te limita más?", 1),
        ("¿Le tenés miedo a quedarte sin ideas o a que tu creatividad se agote?", 1),
        ("¿Qué cosa creativa nunca mostraste por miedo a que no sea suficientemente buena?", 1),
        ("¿Le tenés miedo a que te copien o a que tu expresión no sea original?", 1),
        ("¿Qué pasa en vos cuando alguien critica algo que hiciste o creaste?", 1),
        ("¿El miedo al fracaso creativo te paraliza más que el miedo al fracaso en otras áreas?", 1),
        ("¿Qué miedo relacionado con tu imaginación o tu mundo interior llevas sin expresar?", 1),
        ("¿Le tenés miedo a que lo que creás no esté a la altura de lo que imaginaste que sería?", 1),
        ("¿Qué cosa creativa empezaste y abandonaste por miedo y no por falta de tiempo?", 1),
        ("¿Cómo el miedo al juicio estético de alguien específico limita tu expresión?", 2),
        ("¿Qué dice de vos el tipo de cosas que censurás creativamente antes de empezar?", 2),
        ("¿De qué manera el perfeccionismo es en realidad un miedo disfrazado en tu vida creativa?", 2),
        ("¿Cómo el miedo a no ser original te frena más de lo que te impulsa?", 2),
        ("¿Qué pasaría si mostraras la parte más rara o oscura de tu imaginación sin filtro?", 2),
        ("¿Cómo el miedo a la vulnerabilidad se convierte en autocensura creativa?", 2),
        ("¿Qué cosa querés crear que te da terror porque una vez que existe ya no podés controlar lo que significa?", 3),
        ("¿Cuánto del miedo a crear viene de miedo a descubrir quién sos realmente cuando no hay filtro?", 3),
        ("¿Qué cosa de tu imaginación te asusta y nunca le contaste a nadie?", 3),
        ("¿Cómo el miedo a que algo tuyo no sea lo suficientemente bueno es en realidad miedo a no ser lo suficientemente bueno vos?", 3),
        ("¿Qué creación tuya, si existiera, cambiaría cómo te ven los que más te importan?", 3),
        ("¿Qué dice de vos lo que imaginás en los peores momentos de oscuridad creativa?", 3),
        ("¿Cómo el miedo a la belleza propia — a reconocerte como alguien con algo valioso para expresar — te limita?", 3),
        ("¿Qué cosa no creás porque en el fondo tenés miedo de que sí sea buena?", 3),
        ("¿Qué miedo creativo querés haber enfrentado antes de que sea demasiado tarde?", 3),
        ("¿Cuánto miedo te genera hacer algo que nadie pidió y que puede no gustarle a nadie?", 1),
        ("¿Le tenés más miedo a empezar algo creativo o a terminarlo?", 1),
        ("¿Qué miedo creativo disfrazás de falta de tiempo o de recursos?", 1),
        ("¿Cómo el miedo a mostrar algo incompleto te frena de crear?", 1),
        ("¿Cómo el miedo a sonar pretencioso o snob limita lo que decís sobre el arte que te gusta?", 2),
        ("¿Qué dice de vos el tipo de arte que consumís en privado versus el que reconocés en público?", 2),
        ("¿Cómo el miedo al fracaso creativo se disfraza de perfeccionismo en tu vida?", 2),
        ("¿Qué cosa de tu mundo creativo te aterra compartir porque revelaría algo que no estás listo para mostrar?", 3),
        ("¿Qué le pasaría a tu imagen de vos mismo si lo más raro que imaginás saliera a la luz?", 3),
        ("¿Cómo el miedo a la creatividad propia puede ser en realidad miedo a la propia libertad?", 3),
    ],

    "logros": [
        ("¿Cuál es la cosa más creativa que hiciste de la que estés orgulloso?", 1),
        ("¿Alguna vez creaste algo que superó tus propias expectativas?", 1),
        ("¿Aprendiste alguna habilidad creativa completamente solo y qué te enseñó eso?", 1),
        ("¿Qué proyecto creativo terminaste que en algún momento pensaste que no ibas a poder?", 1),
        ("¿Cuándo fue la primera vez que alguien reconoció un talento creativo tuyo?", 1),
        ("¿Hay algo que hiciste con tus manos de lo que te sentís especialmente orgulloso?", 1),
        ("¿Qué cosa creativa compartiste y generó una reacción que no esperabas?", 1),
        ("¿Alguna vez una obra de arte, canción o escrito tuyo ayudó o movió a alguien de manera genuina?", 1),
        ("¿Cómo el desarrollo de un talento creativo cambió cómo te ves a vos mismo?", 1),
        ("¿Qué habilidad artística o creativa desarrollaste que antes creías imposible para vos?", 1),
        ("¿Cuál fue el momento en que te diste cuenta de que podías crear algo de valor?", 1),
        ("¿Qué logro creativo tuyo pasó casi desapercibido para otros pero para vos fue enorme?", 1),
        ("¿Hay algún proyecto creativo que terminaste que te costó más que cualquier otro logro?", 1),
        ("¿Cómo el proceso de crear algo difícil te cambió, independientemente del resultado?", 1),
        ("¿Qué talento creativo reconociste en vos mismo que te tomó demasiado tiempo aceptar?", 1),
        ("¿Qué logro creativo tuyo no valoraste suficiente en el momento y ahora reconocés que fue grande?", 1),
        ("¿Cómo el hecho de terminar algo creativo — aunque no sea perfecto — es un logro en sí mismo?", 1),
        ("¿Qué cosa aprendiste a hacer creativamente que cambió algo importante de cómo vivís?", 1),
        ("¿Hay algún logro creativo tuyo que le regalaste a alguien y qué significó ese regalo?", 1),
        ("¿Qué proyecto creativo empezaste sin saber si ibas a poder y qué pasó?", 1),
        ("¿Cómo el acto de crear algo te enseñó sobre vos mismo más que cualquier otra cosa?", 1),
        ("¿Qué logro creativo tuyo tiene raíces en algo que antes veías como una limitación?", 1),
        ("¿Cuál fue la vez que algo que hiciste se convirtió en parte de la vida de alguien más?", 1),
        ("¿Qué cosa creaste que todavía te sorprende que hayas podido hacer?", 1),
        ("¿Qué logro creativo querés haber alcanzado antes de morir?", 1),
        ("¿Qué dice de vos el tipo de logros creativos que más valorás en comparación con otros logros?", 2),
        ("¿Cómo un logro creativo cambió tu identidad de maneras que otros logros no pudieron?", 2),
        ("¿Qué cosa creativa lograste que requirió más valentía que habilidad?", 2),
        ("¿Cómo la creatividad puede ser el camino más largo y más difícil hacia un logro y también el más valioso?", 2),
        ("¿Qué logro creativo tuyo tiene más valor para vos que cualquier premio o reconocimiento externo?", 2),
        ("¿De qué manera un fracaso creativo fue en realidad el mayor logro de tu proceso?", 2),
        ("¿Qué cosa creaste que fue un acto de coraje disfrazado de expresión artística?", 3),
        ("¿Cómo el hecho de crear algo que nadie pidió ni esperaba fue tu logro más genuino?", 3),
        ("¿Qué cosa querés haber creado que pruebe que exististe y que valió la pena?", 3),
        ("¿Cómo un logro creativo puede ser el más frágil y al mismo tiempo el más indestructible?", 3),
        ("¿Qué le hubiera pasado a tu vida si hubiera seguido el camino creativo que dejaste?", 3),
        ("¿Qué logro creativo define quién sos de una manera que ningún otro logro puede igualar?", 3),
        ("¿Cuánto de lo que creaste fue en realidad una lucha por demostrar algo y cuánto fue genuinamente libre?", 3),
        ("¿Qué cosa querés crear antes de morir solo para saber que pudiste?", 3),
        ("¿Cómo el acto de crear puede ser en sí mismo un logro independientemente de si alguien lo ve o lo valora?", 3),
    ],

    "sinFiltro": [
        ("¿Qué cosa creaste que nadie vio nunca y que no querés que nadie vea?", 1),
        ("¿Qué tipo de arte o expresión consumís en privado que en público negarías o minimizarías?", 1),
        ("¿Hay alguna fantasía creativa o imaginaria que tenés y que te parece demasiado extraña para contarla?", 1),
        ("¿Qué cosa hiciste con las manos que en secreto te parece más valioso que todo lo que mostrás?", 1),
        ("¿Qué canción, libro o película considerás una culpa placer artística que no confesarías fácilmente?", 1),
        ("¿Alguna vez creaste algo que te avergonzó o sorprendió por lo que reveló de vos?", 1),
        ("¿Qué cosa imaginás o fantaseas que si la contaras cambiaría cómo te ven?", 1),
        ("¿Qué forma de expresión creativa practicás o practicaste que te parece demasiado vulnerable para mostrar?", 1),
        ("¿Qué dice de vos lo que encontrás bello que otros encontrarían raro o perturbador?", 1),
        ("¿Hubo alguna vez en que algo que creaste reveló algo de vos que no sabías que estaba ahí?", 1),
        ("¿Qué cosa escribiste, dibujaste o hiciste en un momento de angustia que después destruiste?", 1),
        ("¿Qué imaginás de noche que de día no te animás a pensar?", 1),
        ("¿Qué parte de tu imaginación es la más oscura y de dónde creés que viene?", 1),
        ("¿Hay algún mundo imaginario que tenés que no le contaste a nadie porque te parece demasiado tuyo?", 1),
        ("¿Qué cosa del arte o la ficción que consumís en privado dice más de tus deseos que cualquier cosa que declarás?", 1),
        ("¿Qué cosa creaste para alguien sin decirle que era para él/ella?", 2),
        ("¿Cómo la creatividad puede ser una manera de confesar cosas que no podés decir de otra manera?", 2),
        ("¿Qué parte de tu imaginación más extraña encontró salida alguna vez en algo que creaste?", 2),
        ("¿Qué dice de vos lo más oscuro que encontrás bello o poéticamente verdadero?", 2),
        ("¿Qué cosa creativa guardás como secreto que en realidad es la más honesta sobre quién sos?", 2),
        ("¿Qué pasaría si alguien con quien convivís leyera o viera todo lo que creaste en privado?", 2),
        ("¿Qué cosa creaste o imaginaste en un momento de rabia, dolor o deseo que te sorprendió de vos mismo?", 3),
        ("¿Qué parte de tu imaginación te resulta más difícil de integrar con quien decís que sos?", 3),
        ("¿Qué dice de vos lo que creás cuando nadie mira y no hay ninguna consecuencia?", 3),
        ("¿Si pudieras mostrar solo una cosa que creaste sin filtro a alguien que te conoce bien, qué mostrarías y qué sentirías?", 3),
        ("¿Qué cosa de tu mundo imaginario es la que más miedo te da reconocer?", 3),
        ("¿Cuánto de lo que creás en secreto es más real que lo que mostrás?", 3),
        ("¿Qué cosa creaste o imaginaste que si saliera a la luz cambiaría cómo te ves a vos mismo?", 3),
        ("¿Qué cosa hacés creativamente en los peores momentos que nunca le contarías a nadie?", 3),
        ("¿Qué parte de tu creatividad es un espacio de libertad absoluta y qué pasa ahí adentro que no sale?", 3),
        ("¿Qué cosa de tu gusto estético escondés porque sabés que no encaja con lo que se espera de vos?", 1),
        ("¿Alguna vez creaste algo erótico, violento o perturbador que después destruiste?", 1),
        ("¿Qué cosa de tu imaginación te generaría vergüenza si alguien te la describiera de afuera?", 1),
        ("¿Cuánto de lo que consumís artísticamente en privado nunca podría ser parte de tu identidad pública?", 1),
        ("¿Qué cosa creaste que en realidad estaba dirigida a alguien específico sin que él/ella lo supiera?", 2),
        ("¿Cómo la expresión creativa puede ser la única manera de decir algo que de otro modo nunca saldría?", 2),
        ("¿Qué cosa de tu mundo creativo secreto dice algo sobre lo que querés y no te permitís pedir?", 2),
        ("¿Qué relación hay entre lo que imaginás en privado y lo que te prohibís sentir en público?", 3),
        ("¿Si pudieras crear algo completamente libre de consecuencias y juicios, qué sería y a quién estaría dirigido?", 3),
        ("¿Qué dice de vos que lo más honesto que creaste nunca lo vio nadie?", 3),
    ],
}


def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]


def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS34:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS34[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")


if __name__ == "__main__":
    main()
