#!/usr/bin/env python3
"""Third batch - focused on new angles and themes."""
import json

ADDITIONS3 = {
    "infancia": [
        ("¿Cuántos libros leíste voluntariamente antes de los 12 años?", 1),
        ("¿Cuál fue el primer dinero que ganaste por tu cuenta?", 1),
        ("¿Tenías algún ritual para antes de los exámenes?", 1),
        ("¿Cuál era el juego al aire libre que más te gustaba?", 1),
        ("¿Cuáles eran tus caricaturas del sábado a la mañana?", 1),
        ("¿Cuánto tiempo tardabas en ir de tu casa a la escuela?", 1),
        ("¿Cómo fue la primera vez que viste a alguien llorar de verdad?", 1),
        ("¿Tenías algún personaje de ficción que te parecía aterrador?", 1),
        ("¿Cuántos compañeros de clase recordás por nombre de la primaria?", 1),
        ("¿Qué quería tu familia que estudiaras?", 1),
        ("¿Cuál era el olor que más asociás con tu hogar de infancia?", 1),
        ("¿Cuál fue la primera vez que te perdiste en un lugar público?", 1),
        ("¿Jugabas a los médicos, cocineros, o maestros con tus amigos?", 1),
        ("¿Cuál fue la primera foto tuya que recordás ver?", 1),
        ("¿Qué hobby de tu infancia retomaste de adulto?", 1),
        ("¿Cuál era el lugar de vacaciones que más emoción te generaba?", 1),
        ("¿Tuviste alguna pesadilla recurrente de chico?", 1),
        ("¿Cuál fue el primer momento que recordás sentirte mayor?", 1),
        ("¿Preferías los juguetes de chicos o chicas, o mezclabas?", 1),
        ("¿Cómo era el vecindario donde creciste?", 1),
        ("¿Cuál fue la primera injusticia escolar que recordás?", 2),
        ("¿Cómo aprendiste sobre la muerte por primera vez?", 2),
        ("¿Alguna vez te metiste en una pelea para defender a alguien?", 2),
        ("¿Cuál fue la primera vez que tuviste que elegir entre dos amigos?", 2),
        ("¿Cómo manejaste la primera pérdida de un ser querido o mascota?", 2),
        ("¿Había algo que deseabas tener de chico que nunca pudiste tener?", 2),
        ("¿Cuándo fue la primera vez que sentiste presión social entre pares?", 2),
        ("¿Alguna vez te hicieron de menos en la escuela? ¿Cómo lo manejaste?", 2),
        ("¿Hay algún logro de la infancia que tus padres nunca reconocieron?", 2),
        ("¿Cuándo empezaste a dudar de las cosas que te enseñaban?", 2),
        ("¿Cuál fue el secreto más grande que guardaste en la infancia?", 3),
        ("¿Qué cosa de tu infancia te avergüenza reconocer hoy?", 3),
        ("¿Cuándo fue la primera vez que sentiste que no encajabas del todo?", 3),
        ("¿Hay alguna cosa que te pasó de chico que cambia cómo te ves hoy?", 3),
        ("¿Si pudieras hablar con tus padres de niño sobre algo específico, qué sería?", 3),
    ],

    "futuro": [
        ("¿Qué tipo de impacto querés tener en tu comunidad?", 1),
        ("¿Cuál es la startup o proyecto social que te gustaría lanzar?", 1),
        ("¿Cuántos países querés visitar antes de morir?", 1),
        ("¿Te imaginas adoptando o teniendo hijos biológicos?", 1),
        ("¿Cómo te imaginas celebrando tus 80 cumpleaños?", 1),
        ("¿Cuál es la aventura que querés vivir alguna vez?", 1),
        ("¿Hay alguna religión, filosofía o práctica espiritual que querés explorar?", 1),
        ("¿Qué legado material o artístico querés dejar?", 1),
        ("¿Cuánto querés que cambie tu cuerpo en los próximos 10 años?", 1),
        ("¿Cuál es el libro que querés escribir algún día?", 1),
        ("¿Te imaginas viviendo en una comunidad, una ciudad chica o una metrópolis?", 1),
        ("¿Qué tipo de pareja o compañero de vida imaginás a tu lado en 20 años?", 1),
        ("¿Cuál es la habilidad tecnológica que más querés dominar?", 1),
        ("¿Qué rol querés jugar en la vida de la próxima generación?", 1),
        ("¿Cuál es la causa social a la que más querés contribuir?", 1),
        ("¿Cuánto querés que cambie tu economía en los próximos 5 años?", 1),
        ("¿Te imaginas trabajando para vos mismo o en una organización?", 1),
        ("¿Cuál es la experiencia gastronómica que querés vivir?", 1),
        ("¿Qué tipo de hogar querés crear para vos?", 1),
        ("¿Hay algún aprendizaje ancestral que querés incorporar a tu vida?", 1),
        ("¿Cuándo fue la última vez que planeaste algo grande y lo ejecutaste?", 2),
        ("¿Qué parte de tu futuro dependes de que alguien más cambie?", 2),
        ("¿Cuánto peso tiene el miedo a la soledad en cómo planeas tu vida?", 2),
        ("¿Hay algo que sabés que deberías hacer hoy pero que postergás para 'después'?", 2),
        ("¿Cómo cambiará tu identidad cuando logres lo que más querés?", 2),
        ("¿Cuándo fue la última vez que revisaste si tus metas siguen siendo tuyas?", 2),
        ("¿Hay algo en lo que invertirías tiempo si tuvieras certeza de que iba a funcionar?", 2),
        ("¿Cuánto de tu imagen pública futura querés construir conscientemente?", 2),
        ("¿Qué conversación difícil es la que más cambiará tu futuro si la tenés?", 2),
        ("¿Cuánto de tu futuro está estructurado por lo que otros esperan de vos?", 2),
        ("¿Cuál es el miedo que más activamente bloqueará tu crecimiento si no lo trabajás?", 3),
        ("¿Qué tan diferente sería tu futuro si soltaras la necesidad de control?", 3),
        ("¿Qué necesitás perder para poder ganar lo que más querés?", 3),
        ("¿Cuándo fue la última vez que viviste plenamente el presente sin pensar en el futuro?", 3),
        ("¿Cuál es la versión de vos mismo que más te asusta convertirte y cómo evitarlo?", 3),
    ],

    "amor": [
        ("¿Cuándo fue la primera vez que alguien te rompió el corazón?", 1),
        ("¿Sos celoso/a o te resulta fácil confiar?", 1),
        ("¿Cuál fue la primera vez que alguien te persiguió románticamente?", 1),
        ("¿Qué es lo que más te gusta de estar de novio/a o en pareja?", 1),
        ("¿Cuál es la cosa más ridícula que hiciste cuando te gustaba alguien?", 1),
        ("¿Cuánto tiempo pasó entre tu primera cita con alguien y el primer beso?", 1),
        ("¿Prefieres salir de noche o hacer planes de día para citas?", 1),
        ("¿Cuál fue la confesión de amor más inesperada que recibiste?", 1),
        ("¿Sos de los que deja en visto o respondés rápido?", 1),
        ("¿Cuál es el tipo de humor que te seduce en una persona?", 1),
        ("¿Qué es lo que más te cuesta tolerar en una pareja?", 1),
        ("¿Cuándo fue la última vez que cortejaste a alguien activamente?", 1),
        ("¿Cuál fue la cita más extraña que tuviste?", 1),
        ("¿Sos de los que escribe poesía, canciones o cartas en enamoramiento?", 1),
        ("¿Cuántas veces actuaste para impresionar a alguien que te gustaba?", 1),
        ("¿Cuál es el detalle que más rápido te conquista?", 1),
        ("¿Qué tanto tiempo tardás en 'bajar la guardia' con alguien nuevo?", 1),
        ("¿Cuál fue la persona que más te cambió la perspectiva sobre el amor?", 1),
        ("¿Prefieres relaciones donde el otro te busca o donde buscás vos?", 1),
        ("¿Cuándo fue la última vez que te enamoraste en serio?", 1),
        ("¿Hay algo que repetís en cada relación porque no aprendiste todavía?", 2),
        ("¿Cuánto de lo que buscás en una pareja es lo que te falta a vos mismo?", 2),
        ("¿Alguna vez dejaste a alguien antes de que te dejaran por miedo?", 2),
        ("¿Cuándo fue la última vez que una relación reveló algo que no sabías de vos?", 2),
        ("¿Cuánto tiempo podés estar cómodo/a siendo soltero/a?", 2),
        ("¿Hay algo que hacés diferente cuando te gusta alguien mucho?", 2),
        ("¿Cuándo fue la última vez que amaste sin guardarte nada?", 2),
        ("¿Cómo afecta tu autoestima la forma en que te tratan tus parejas?", 2),
        ("¿Hay alguien que estuvo en tu vida que representó la versión más pura del amor para vos?", 2),
        ("¿Cuánto de cómo amás viene de cómo te amaron cuando eras chico?", 2),
        ("¿Cuándo fue la última vez que amaste a alguien más de lo que te amabas a vos mismo?", 3),
        ("¿Hay algo sobre el amor que ya no creés como antes?", 3),
        ("¿Cuál es la promesa sobre el amor que te resultó más difícil de mantener?", 3),
        ("¿Cuánto miedo te da la posibilidad de estar solo para siempre?", 3),
        ("¿Cuál es la cosa más valiente que hiciste en nombre del amor?", 3),
    ],

    "familia": [
        ("¿Cómo era la relación entre tus padres cuando eras chico?", 1),
        ("¿Cuál es el pariente más excéntrico que tenés?", 1),
        ("¿Cuántas generaciones de tu familia vivieron en el mismo lugar?", 1),
        ("¿Hay alguna historia de inmigración en tu familia?", 1),
        ("¿Cuál fue la reunión familiar más memorable?", 1),
        ("¿Tenés algún pariente que sea un modelo a seguir?", 1),
        ("¿Cuál es la cosa que tu madre hacía que jamás podrías replicar?", 1),
        ("¿Cuál es la cosa que tu padre hacía que aprendiste sin darte cuenta?", 1),
        ("¿Cuánto tiempo pasabas con tus abuelos?", 1),
        ("¿Cuál fue la enseñanza más valiosa que te dejó tu familia?", 1),
        ("¿Hay alguna figura familiar que fue como un segundo padre o madre?", 1),
        ("¿Cuántas mudanzas hizo tu familia mientras crecías?", 1),
        ("¿Cuál es el legado más importante que querés mantener de tu familia?", 1),
        ("¿Cómo se tomaban las decisiones importantes en tu familia?", 1),
        ("¿Cuál es el platillo que podría definir a tu familia?", 1),
        ("¿Hay algún ritual religioso o espiritual en tu familia que seguís o dejaste?", 1),
        ("¿Cuál es la diferencia más grande entre vos y alguno de tus padres?", 1),
        ("¿Cómo manejaron el duelo en tu familia cuando alguien falleció?", 1),
        ("¿Cuál fue la primera vez que defendiste a un familiar frente a otros?", 1),
        ("¿Cómo celebran los éxitos en tu familia?", 1),
        ("¿Cuándo sentiste por primera vez que tus padres estaban equivocados en algo?", 2),
        ("¿Cuánto peso tienen las opiniones familiares en cómo te ves a vos mismo?", 2),
        ("¿Cuál fue el mayor sacrificio que alguien de tu familia hizo por vos?", 2),
        ("¿Hay algo que hacés hoy para no repetir errores de tu familia?", 2),
        ("¿Cuál fue la crisis familiar que más los unió?", 2),
        ("¿Cuánto de la relación con tus padres tuviste que renegociar de adulto?", 2),
        ("¿Hay alguna dinámica familiar que recién entendiste cuando creciste?", 2),
        ("¿Cuánto de tus miedos adultos vienen de lo que viste en tu familia?", 2),
        ("¿Hay algo que le diste a tu familia que nadie más les pudo dar?", 2),
        ("¿Cómo afectó económicamente tu familia a tus oportunidades en la vida?", 2),
        ("¿Cuál es el patrón de tu familia que más querés romper conscientemente?", 3),
        ("¿Hay algo de lo que creciste creyendo sobre la familia que hoy rechazás?", 3),
        ("¿Cuándo fue la última vez que te sentiste completamente libre dentro de tu familia?", 3),
        ("¿Hay alguien en tu familia a quien nunca pudiste perdonar del todo?", 3),
        ("¿Cuál es la cosa que más temés repetir de tus padres cuando seas padre/madre?", 3),
    ],

    "amistades": [
        ("¿Cuál es la actividad que organizarías para juntarte con tus amigos esta semana?", 1),
        ("¿Tenés algún amigo con quien te comuniques de una manera completamente particular?", 1),
        ("¿Cuándo fue la última vez que hiciste nuevos amigos fuera de tu círculo habitual?", 1),
        ("¿Cuál fue la última aventura espontánea que tuviste con amigos?", 1),
        ("¿Tenés amigos de diferentes etapas de tu vida que no se conocen entre sí?", 1),
        ("¿Cuál fue la primera vez que viste llorar a un amigo?", 1),
        ("¿Sos de los que siempre tiene un plan o improvisás?", 1),
        ("¿Cuál es la cosa de la que más te reís con tus amigos más cercanos?", 1),
        ("¿Cuándo fue la última vez que sorprendiste a un amigo con algo que sabías que necesitaba?", 1),
        ("¿Cuál es el rol no oficial que tenés en tu grupo de amigos?", 1),
        ("¿Hay algún amigo que sea tu opuesto total y con quien igual te llevás bien?", 1),
        ("¿Cuál fue la primera vez que un amigo te pidió dinero?", 1),
        ("¿Hay algún momento que marcó la amistad más importante que tenés?", 1),
        ("¿Cuándo fue la última vez que le preguntaste a un amigo cómo estaba de verdad?", 1),
        ("¿Cuál es el plan de amigos más absurdo que alguna vez se volvió realidad?", 1),
        ("¿Cómo reaccionás cuando un amigo está en crisis?", 1),
        ("¿Cuántas veces por año ves a tu amigo más cercano?", 1),
        ("¿Hay algún amigo que sea tu confidente y por qué lo elegiste a él o ella?", 1),
        ("¿Cuál fue el momento que más te orgulleció de un amigo?", 1),
        ("¿Cómo sería para vos el amigo perfecto?", 1),
        ("¿Alguna vez sentiste que un amigo te envidiaba?", 2),
        ("¿Cómo manejás cuando un amigo te pide algo que no podés o no querés dar?", 2),
        ("¿Hay alguna amistad que mantenés viva por inercia?", 2),
        ("¿Cuándo fue la última vez que un amigo te sorprendió negativamente?", 2),
        ("¿Cuánto de vos mismo ocultás frente a tus amigos?", 2),
        ("¿Hay algún amigo que sientes que te quita más energía de la que te da?", 2),
        ("¿Cuándo fue la última vez que pusiste a un amigo por encima de vos mismo?", 2),
        ("¿Alguna vez le dijiste a un amigo algo que sabías que no quería escuchar?", 2),
        ("¿Hay algo que le debes a un amigo y que todavía no resolviste?", 2),
        ("¿Cuándo fue la última vez que un amigo te cambió de perspectiva sobre algo?", 2),
        ("¿Cuál es la cosa que más le agradecés a tu mejor amigo en este momento?", 3),
        ("¿Cuándo fue la última vez que una amistad te hizo crecer como persona?", 3),
        ("¿Hay alguna amistad que no sobrevivió algo y que aún te pesa?", 3),
        ("¿Cuánto miedo te da mostrarte vulnerable frente a tus amigos?", 3),
        ("¿Cuál es la amistad que más te costó y que más te dio?", 3),
    ],

    "exs": [
        ("¿Cuánto tardaste en cambiar tu estado en redes después de una ruptura?", 1),
        ("¿Cuándo fue la última vez que escuchaste una canción que te recordó a un ex?", 1),
        ("¿Hubo algún ex que te presentó a personas que hoy son importantes en tu vida?", 1),
        ("¿Cuánto tardaste en conocer a la familia de tu pareja más seria?", 1),
        ("¿Cuál fue la aventura más memorable que tuviste con un ex?", 1),
        ("¿Hay algún ex al que todavía googlearías?", 1),
        ("¿Cuál fue el regalo más extraño que recibiste de un ex?", 1),
        ("¿Cuántas rupturas viviste que fueron 'de mutuo acuerdo' y cuántas realmente lo fueron?", 1),
        ("¿Cuánto tiempo permaneciste en una relación que ya no funcionaba?", 1),
        ("¿Hay algún ex que no recuerdas bien por qué terminaron?", 1),
        ("¿Alguna vez terminaste una relación que en el fondo no querías terminar?", 1),
        ("¿Cuál fue la relación que más te costó empezar?", 1),
        ("¿Cuándo fue la última vez que tuviste nostalgia de un ex?", 1),
        ("¿Cómo te enteraste de cuando un ex se casó o tuvo hijos?", 1),
        ("¿Hay algún objeto o lugar que ya no podés ver de la misma manera después de una relación?", 1),
        ("¿Cuándo sentiste por primera vez que eras libre después de una ruptura?", 1),
        ("¿Cuál fue la parte más difícil de adaptarte a estar solo después de una relación larga?", 1),
        ("¿Cuándo fue la primera vez que pudiste hablar bien de un ex después de terminar?", 1),
        ("¿Alguna vez te fuiste de vacaciones con un ex y resultó un desastre?", 1),
        ("¿Cuál fue el momento más incómodo que viviste con un ex estando solteros?", 1),
        ("¿Cuándo te diste cuenta de que no estabas enamorado de alguien?", 2),
        ("¿Cuál fue la relación que más te costó reconocer como tóxica?", 2),
        ("¿Hay algo que repetís en cada relación que sabés que viene de una herida?", 2),
        ("¿Cuándo fue la primera vez que te sentiste verdaderamente libre después de una ruptura?", 2),
        ("¿Alguna vez tu relación más importante te hizo cuestionar quién eras?", 2),
        ("¿Qué necesitabas que ningún ex pudo darte realmente?", 2),
        ("¿Cuándo fue la última vez que perdonaste a alguien de tu pasado amoroso?", 2),
        ("¿Hay algo de una relación pasada que todavía extrañás y que te cuesta admitir?", 2),
        ("¿Cuánto de cómo amás ahora cambió a partir de una relación difícil?", 2),
        ("¿Cuándo fue la primera vez que elegiste estar solo en lugar de estar en una relación que no era sana?", 2),
        ("¿Cuál fue la relación que más te enseñó sobre tus propios límites?", 3),
        ("¿Hay alguien de tu pasado a quien le debes algo y no pudiste pagarlo?", 3),
        ("¿Cuánto de quien sos hoy fue construido sobre las ruinas de relaciones pasadas?", 3),
        ("¿Qué necesitás resolver en vos mismo para no repetir ciertos patrones amorosos?", 3),
        ("¿Cuándo fue la última vez que amaste de manera verdaderamente libre?", 3),
    ],

    "personalidad": [
        ("¿Cuántas horas del día hacés cosas que te apasionan realmente?", 1),
        ("¿Cuál es la cosa que más fácilmente te saca de tu zona de confort?", 1),
        ("¿Qué palabra usarían tus amigos para describirte y cuál usarías vos?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente nuevo?", 1),
        ("¿Cuál es la cosa que más postergás en la vida cotidiana?", 1),
        ("¿Cómo reaccionás cuando alguien te contradice en público?", 1),
        ("¿Cuánto importa para vos la coherencia entre lo que decís y lo que hacés?", 1),
        ("¿Cuál es el tipo de humor que más disfrutás?", 1),
        ("¿Sos de los que se adaptan o de los que prefieren que los demás se adapten?", 1),
        ("¿Cuándo fue la última vez que actuaste desde la intuición pura?", 1),
        ("¿Cuál es tu peor hábito de comunicación?", 1),
        ("¿Cuánto te cuesta decir que no cuando realmente no querés hacer algo?", 1),
        ("¿Cuándo fue la última vez que alguien cambió tu punto de vista sobre algo importante?", 1),
        ("¿Cuál es la cosa que más te define que no sea evidente a primera vista?", 1),
        ("¿Cómo manejás la incertidumbre en el trabajo o en relaciones?", 1),
        ("¿Cuánto de lo que hacés todos los días te gusta realmente?", 1),
        ("¿Cuál es la decisión de la que estás más orgulloso que hayas tomado?", 1),
        ("¿Qué es lo que hacés cuando te sentís perdido?", 1),
        ("¿Cuánto tiempo te lleva recuperarte después de un conflicto?", 1),
        ("¿Cuál es la cosa que más enorgullece a la gente que te conoce de vos?", 1),
        ("¿Cuándo fue la última vez que te mentiste a vos mismo y te diste cuenta tarde?", 2),
        ("¿Cuánto peso tiene la culpa en tus decisiones cotidianas?", 2),
        ("¿Cuál es la narrativa sobre vos mismo que más te limita?", 2),
        ("¿Hay algún aspecto de tu carácter que te cuesta mostrar?", 2),
        ("¿Cuándo fue la última vez que te perdonaste a vos mismo por algo?", 2),
        ("¿Cuánto de vos mismo le mostrás a la gente que recién conocés?", 2),
        ("¿Hay algo que hacés por costumbre que ya no te define pero que no cambiaste?", 2),
        ("¿Cuándo fue la última vez que actuaste en contra de tu carácter y te sorprendiste?", 2),
        ("¿Cuál es la diferencia entre quien sos y quien querés ser?", 2),
        ("¿Cuándo fue la última vez que realmente te diste el tiempo de conocerte mejor?", 2),
        ("¿Cuál es la parte de tu identidad que más te costó construir?", 3),
        ("¿Cuándo fue la última vez que te animaste a mostrar tu lado más vulnerable?", 3),
        ("¿Hay algo que creés sobre vos mismo que nadie más confirmó ni negó?", 3),
        ("¿Cuánto de quien sos fue elegido por vos y cuánto fue moldeado por el entorno?", 3),
        ("¿Cuál es la cosa que más te asusta descubrir si mirás muy adentro tuyo?", 3),
    ],

    "miedos": [
        ("¿Cuál es la situación social que más evitás?", 1),
        ("¿Le tenés miedo al dentista?", 1),
        ("¿Cuál es el tipo de lugar o espacio que más te genera claustrofobia?", 1),
        ("¿Cuándo fue la última vez que dormiste con miedo?", 1),
        ("¿Hay alguna noticia que te afecta de manera desproporcionada?", 1),
        ("¿Cuál fue la primera vez que sentiste un miedo físico intenso?", 1),
        ("¿Le tenés miedo al fracaso público?", 1),
        ("¿Cuál es el miedo que tenés y que logicamente no tiene sentido?", 1),
        ("¿Cuántas veces al mes pensás en algo que te genera ansiedad?", 1),
        ("¿Qué tipo de película de suspenso o terror preferís?", 1),
        ("¿Le tenés miedo a los accidentes de tránsito?", 1),
        ("¿Cuándo fue la última vez que tuviste un ataque de ansiedad?", 1),
        ("¿Hay algún miedo que te pasa solo cuando estás cansado o estresado?", 1),
        ("¿Le tenés miedo a ciertos tipos de clima extremo?", 1),
        ("¿Cuándo fue la última vez que evitaste algo por miedo?", 1),
        ("¿Cuál fue el miedo de infancia que lograste superar?", 1),
        ("¿Tenés miedo a las multitudes o a los espacios muy abiertos?", 1),
        ("¿Le tenés miedo a los ruidos fuertes inesperados?", 1),
        ("¿Cuándo fue la última vez que el miedo te hizo actuar de manera que te sorprendió?", 1),
        ("¿Cuál es la actividad de riesgo bajo que igual evitás?", 1),
        ("¿Cuándo fue la última vez que el miedo al rechazo te impidió hacer algo?", 2),
        ("¿Cuánto peso tiene el miedo a la soledad en tus relaciones?", 2),
        ("¿Hay algo que le tenés miedo y que necesitarías trabajar con alguien?", 2),
        ("¿Cuándo fue la última vez que enfrentaste algo que te daba miedo y no salió bien?", 2),
        ("¿Cuánto miedo te da perder el control sobre tu vida?", 2),
        ("¿Hay algún miedo que empeoró con los años en lugar de mejorar?", 2),
        ("¿Cuándo fue la última vez que hablaste de tus miedos con alguien de confianza?", 2),
        ("¿Cuánto miedo te genera la posibilidad de estar equivocado en algo fundamental?", 2),
        ("¿Hay algún aspecto de tu futuro que te genera un miedo irracional?", 2),
        ("¿Cuándo fue la última vez que el miedo te hizo más pequeño de lo que sos?", 2),
        ("¿Cuál es el miedo que más vergüenza te da admitir frente a alguien que te conoce?", 3),
        ("¿Cuándo fue la última vez que te permitiste sentir miedo sin juzgarte?", 3),
        ("¿Hay algo que creés que siempre vas a temer sin importar cuánto lo trabajes?", 3),
        ("¿Cuál es el miedo que más define tus relaciones y que menos hablás?", 3),
        ("¿Si pudieras vivir sin tu miedo más limitante, qué cambiaría primero?", 3),
    ],

    "logros": [
        ("¿Cuál fue la primera vez que alguien dependió de vos para lograr algo?", 1),
        ("¿Cuándo fue la última vez que tu trabajo o esfuerzo marcó a alguien?", 1),
        ("¿Cuál fue el momento en que te diste cuenta de que una meta era real?", 1),
        ("¿Hay algo que aprendiste a hacer que creías imposible?", 1),
        ("¿Cuándo fue la primera vez que sentiste que eras bueno en algo?", 1),
        ("¿Cuál fue el proyecto más ambicioso que terminaste?", 1),
        ("¿Hay algún logro que conseguiste sin que nadie te lo haya pedido?", 1),
        ("¿Cuándo fue la última vez que superaste una expectativa que tenías sobre vos mismo?", 1),
        ("¿Cuál fue el momento de mayor claridad sobre lo que querías lograr?", 1),
        ("¿Hay algo que lograste de lo que todavía vivís?", 1),
        ("¿Cuándo fue la última vez que alguien fue testigo de un logro tuyo?", 1),
        ("¿Cuál fue el logro que más le costó a tu familia entender?", 1),
        ("¿Hay algún logro que te haya cambiado fundamentalmente como persona?", 1),
        ("¿Cuándo fue la última vez que celebraste algo con genuina alegría?", 1),
        ("¿Cuál fue la primera vez que ganaste algo competitivamente?", 1),
        ("¿Hay alguna cosa que hiciste que podría considerarse arte en algún sentido?", 1),
        ("¿Cuándo fue la última vez que alguien te copió algo que hiciste?", 1),
        ("¿Cuál fue el consejo que más contribuyó a uno de tus logros?", 1),
        ("¿Hay algo que lograste hace poco que hace 5 años hubiera parecido imposible?", 1),
        ("¿Cuándo fue la última vez que te diste crédito sin minimizarlo?", 1),
        ("¿Cuándo fue la última vez que lograste algo importante y nadie lo notó?", 2),
        ("¿Cuál fue el fracaso que más te costó procesar y cómo lo superaste?", 2),
        ("¿Cuánto de tus logros están alineados con lo que querés de verdad?", 2),
        ("¿Cuándo fue la última vez que hiciste algo sin la seguridad de que iba a funcionar?", 2),
        ("¿Hay algo que lograste por obligación y no por elección?", 2),
        ("¿Cuándo fue la última vez que pediste ayuda para lograr algo?", 2),
        ("¿Hay algún logro que conseguiste que en el fondo no te llenó?", 2),
        ("¿Cuándo fue la última vez que apostaste por vos mismo contra todas las probabilidades?", 2),
        ("¿Cuánto de lo que lograste fue gracias a suerte y cuánto a trabajo?", 2),
        ("¿Cuándo fue la última vez que renunciaste a algo a tiempo para evitar un fracaso mayor?", 2),
        ("¿Cuál es el logro que más define quién sos y que menos hablás?", 3),
        ("¿Cuándo fue la última vez que hiciste algo importante sin importarte si alguien lo vería?", 3),
        ("¿Cuál es la diferencia entre el éxito que soñabas y el que tenés?", 3),
        ("¿Cuánto de tus logros son para callar voces del pasado?", 3),
        ("¿Cuál sería tu vida si no necesitaras demostrarle nada a nadie?", 3),
    ],

    "sinFiltro": [
        ("¿Cuántos chats tenés en leído que nunca respondiste?", 1),
        ("¿Cuál fue la mentira más exitosa que contaste?", 1),
        ("¿Alguna vez finges estar de acuerdo con algo para no pelear?", 1),
        ("¿Cuánto dinero hay en tu billetera ahora mismo?", 1),
        ("¿Cuál fue la situación más vergonzosa que viviste en público?", 1),
        ("¿Alguna vez hiciste trampa en un juego de mesa?", 1),
        ("¿Cuántas veces miraste el Instagram de alguien antes de hablarle?", 1),
        ("¿Cuál es la mentira que más repetís sin darte cuenta?", 1),
        ("¿Cuánto dinero pensás que deberías ganar y cuánto ganás realmente?", 1),
        ("¿Alguna vez le contaste algo de alguien que debías guardar?", 1),
        ("¿Cuántos contactos en tu celular jamás volverías a llamar?", 1),
        ("¿Cuántas contraseñas anotaste en papel porque no las recordás?", 1),
        ("¿Cuál fue la cosa más ridícula que compraste y luego te arrepentiste?", 1),
        ("¿Cuántas aplicaciones de delivery tenés y cuántas usas realmente?", 1),
        ("¿Cuál es la cosa que nunca te vas a tatuar aunque te lo pidieran?", 1),
        ("¿Alguna vez fingiste que te gustó algo que te regalaron?", 1),
        ("¿Cuánto te tardaste en regresar la llamada de alguien que no querías llamar?", 1),
        ("¿Cuál es la cosa más cara que perdiste por accidente?", 1),
        ("¿Cuántas veces al día mirás tu celular cuando deberías estar haciendo otra cosa?", 1),
        ("¿Cuál es el comentario más honesto que le dirías a alguien de este grupo?", 1),
        ("¿Cuándo fue la última vez que dijiste algo solo para quedar bien?", 2),
        ("¿Alguna vez te aprovechaste de la confianza de alguien?", 2),
        ("¿Cuándo fue la última vez que estuviste celoso de alguien de tu círculo?", 2),
        ("¿Hay algo que hacés que si lo supieran tus padres cambiaría todo?", 2),
        ("¿Cuántas veces al mes gastás más de lo que deberías?", 2),
        ("¿Cuándo fue la última vez que actuaste desde el egoísmo puro?", 2),
        ("¿Alguna vez te hiciste el enfermo para evitar una responsabilidad?", 2),
        ("¿Cuántas personas conocés que hablan mal de vos y de quienes hablas mal también?", 2),
        ("¿Cuándo fue la última vez que actuaste por pura conveniencia?", 2),
        ("¿Cuál es la cosa más escandalosa que pasó en tu vida que pocos saben?", 2),
        ("¿Cuál es la cosa que más te da vergüenza admitir que te pone?", 3),
        ("¿Cuándo fue la última vez que hiciste algo de lo que no estás orgulloso y no se lo dijiste a nadie?", 3),
        ("¿Cuál es tu mayor hipocresía que nadie nota?", 3),
        ("¿Hay algo que disfrutaste que socialmente está mal visto y que lo disfrutaste igual?", 3),
        ("¿Cuál es el secreto que te llevarías a la tumba si pudieras?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS3:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS3[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
