#!/usr/bin/env python3
"""Fourth batch - sensory memories, hypotheticals, body language, creativity, humor, spirituality, technology, light politics, environment, childhood dreams."""
import json

ADDITIONS4 = {
    "infancia": [
        # Level 1 - ~24 questions
        ("¿Cuál es el sonido que más asociás con los veranos de tu infancia?", 1),
        ("¿Qué textura o sensación física recordás con más cariño de cuando eras chico?", 1),
        ("¿Cuál fue el olor que te hacía saber que estabas en la casa de tus abuelos?", 1),
        ("¿Tenías algún sueño recurrente bonito, no pesadilla, de chico?", 1),
        ("¿Cuál fue la primera vez que viste el mar, la montaña o un paisaje que te voló la cabeza?", 1),
        ("¿Qué canción escuchás hoy y te transporta directamente a la infancia?", 1),
        ("¿Cuál era el sabor que pedías cada vez que ibas al kiosco?", 1),
        ("¿Cómo era la voz de la persona que más te calmaba cuando eras chico?", 1),
        ("¿Tenías algún personaje inventado o mundo imaginario propio?", 1),
        ("¿Cuál fue el primer chiste que aprendiste de memoria?", 1),
        ("¿Qué programa de televisión jamás te perdías de chico?", 1),
        ("¿Cuántas veces intentaste aprender algo y lo dejaste a mitad porque te aburriste?", 1),
        ("¿Cuál fue la primera vez que te enamoraste de un personaje de ficción?", 1),
        ("¿Qué juego inventabas cuando no tenías nada para hacer?", 1),
        ("¿Cuál era el sueño de carrera que tenías a los 10 años que hoy te da ternura?", 1),
        ("¿Tenías algún ritual para cuando llovía?", 1),
        ("¿Cuál fue la primera vez que saliste solo a hacer algo sin adultos?", 1),
        ("¿Cuánto tiempo pasabas en la bañera o pileta jugando antes de que te sacaran?", 1),
        ("¿Qué cosa de grande descubriste y pensaste 'ojalá hubiera sabido esto de chico'?", 1),
        ("¿Cuál fue el primer deporte que viste en vivo y te emocionó?", 1),
        ("¿Tenías alguna palabra inventada que solo tu familia usaba?", 1),
        ("¿Qué dibujo animado sentías que nadie más veía pero vos amabas?", 1),
        ("¿Cuándo fue la primera vez que cocinaste algo y resultó comestible?", 1),
        ("¿Cuál fue la primera vez que hiciste reír a un adulto con algo que dijiste?", 1),
        # Level 2 - ~10 questions
        ("¿Hay algún sueño de infancia que todavía no abandonaste del todo?", 2),
        ("¿Cuándo fue la primera vez que sentiste que el mundo era más grande y más complicado de lo que pensabas?", 2),
        ("¿Hay alguna amistad de infancia que terminó sin que entendieras bien por qué?", 2),
        ("¿Cuándo empezaste a notar que tus padres tenían una vida propia que no girabas alrededor tuyo?", 2),
        ("¿Qué cosa creíste de chico que resultó ser completamente falsa cuando creciste?", 2),
        ("¿Cuál fue la primera vez que sentiste presión para ser de una manera determinada?", 2),
        ("¿Hay algo que querías ser de grande que tu entorno descartó como 'imposible'?", 2),
        ("¿Cuándo fue la primera vez que experimentaste algo que los adultos no querían que supieras?", 2),
        ("¿Cuál fue la primera vez que cuestionaste una creencia que tu familia te enseñó?", 2),
        ("¿Qué parte de la infancia tuya no concuerda con cómo te recordás siendo?", 2),
        # Level 3 - ~6 questions
        ("¿Hay algo de tu infancia que reencuadraste completamente al entender más de adulto?", 3),
        ("¿Cuál fue la primera vez que la realidad fue muy distinta de lo que esperabas y eso te cambió?", 3),
        ("¿Qué necesidad emocional de tu infancia seguís intentando satisfacer de adulto?", 3),
        ("¿Cuándo fue la primera vez que sentiste que no podías ser completamente vos mismo?", 3),
        ("¿Hay algún momento de tu infancia del que te enteraste de adulto y que cambió cómo ves tu historia?", 3),
        ("¿Qué parte del niño o niña que fuiste todavía necesita algo que nunca recibió?", 3),
    ],

    "futuro": [
        # Level 1 - ~24 questions
        ("¿Cuál es la tecnología que más te entusiasma para el futuro?", 1),
        ("¿Si pudieras vivir en cualquier época de la historia futura, cuál elegirías?", 1),
        ("¿Cuál es la cosa del mundo natural que más querés que siga existiendo en 50 años?", 1),
        ("¿Cuál es la app, herramienta o gadget que todavía no existe y te encantaría tener?", 1),
        ("¿Te imaginas usando inteligencia artificial en tu trabajo o vida diaria de forma significativa?", 1),
        ("¿Cuál es la causa medioambiental que más te importa para el futuro del planeta?", 1),
        ("¿Cómo te imaginas que va a cambiar la educación en los próximos 20 años?", 1),
        ("¿Si pudieras resolver un solo problema global, cuál elegirías?", 1),
        ("¿Cuál es la habilidad creativa que querés desarrollar en los próximos años?", 1),
        ("¿Te gustaría probar vivir de manera más sustentable o off-grid en algún momento?", 1),
        ("¿Cuál es el proyecto creativo que postergás porque 'no es el momento'?", 1),
        ("¿Cuánto te importa dejar huella en el mundo versus vivir una vida privada y plena?", 1),
        ("¿Si pudieras teleportarte a cualquier lugar del mundo cada fin de semana, a dónde irías?", 1),
        ("¿Cuál es la forma de ganarte la vida que más te llamaría la atención si empezaras de cero?", 1),
        ("¿Cómo te imaginás que va a cambiar tu relación con la tecnología en 10 años?", 1),
        ("¿Qué tipo de comunidad o barrio te imaginas habitando en el futuro?", 1),
        ("¿Si supieras que el mundo va a cambiar radicalmente en 5 años, qué harías distinto hoy?", 1),
        ("¿Cuál es el ritual o práctica espiritual o de bienestar que querés incorporar?", 1),
        ("¿Cuánto espacio le das en tu futuro a la espontaneidad versus la planificación?", 1),
        ("¿Cuál es la cosa del mundo actual que más querés que cambie para cuando seas viejo?", 1),
        ("¿Si pudieras dominar un instrumento musical en un año, cuál sería?", 1),
        ("¿Cuál es el tipo de impacto que querés tener con el trabajo que hacés?", 1),
        ("¿Cuánto pesa la idea de sustentabilidad y medio ambiente en tus decisiones de vida?", 1),
        ("¿Si pudieras cambiar una sola ley o política pública, cuál cambiarías?", 1),
        # Level 2 - ~10 questions
        ("¿Cuándo fue la última vez que tomaste una decisión que priorizó el largo plazo sobre el corto plazo?", 2),
        ("¿Hay algo en lo que creés políticamente que cambió radicalmente en los últimos años?", 2),
        ("¿Cuánto de tu futuro está condicionado por el peso de las deudas o compromisos actuales?", 2),
        ("¿Hay algo que el vos de hoy le diría al vos de dentro de 10 años?", 2),
        ("¿Cuándo fue la última vez que actuaste en línea con tus valores y no con tus miedos?", 2),
        ("¿Qué tan preparado te sentís para los desafíos climáticos o sociales que se vienen?", 2),
        ("¿Hay una conversación sobre el futuro que evitás tener con alguien cercano?", 2),
        ("¿Cuánto de tu identidad futura depende de lo que otros esperan de vos?", 2),
        ("¿Cuándo fue la última vez que imaginaste activamente cómo querés que sea tu vida en 20 años?", 2),
        ("¿Qué cosa del presente sabés que vas a extrañar cuando ya no esté?", 2),
        # Level 3 - ~6 questions
        ("¿Cuál es la versión de vos mismo que más te aterra ser en 20 años?", 3),
        ("¿Hay algo que el miedo al futuro te impide construir hoy?", 3),
        ("¿Cuánto de lo que querés para el futuro es genuinamente tuyo y cuánto es una expectativa ajena internalizada?", 3),
        ("¿Qué deberías soltar del pasado para poder diseñar el futuro que realmente querés?", 3),
        ("¿Cuándo fue la última vez que viviste plenamente sin escaparte ni al pasado ni al futuro?", 3),
        ("¿Cuál es la cosa más valiente que podrías hacer esta semana por tu futuro?", 3),
    ],

    "amor": [
        # Level 1 - ~24 questions
        ("¿Cuál es el gesto no verbal que más te dice que alguien está enamorado de vos?", 1),
        ("¿Qué olor o perfume asociás con alguien que amaste?", 1),
        ("¿Cuál es la escena de película romántica que en secreto te gustaría vivir?", 1),
        ("¿Sos de los que se vuelve más gracioso o más serio cuando le gusta alguien?", 1),
        ("¿Cuánto te importa la inteligencia emocional en una pareja versus la intelectual?", 1),
        ("¿Cuál es la canción que más daría vergüenza admitir que pone en modo romántico?", 1),
        ("¿Cuál es el gesto pequeño que más valoras en la cotidianidad de una relación?", 1),
        ("¿Sos de los que necesita espacio o de los que disfruta la intensidad del todo el tiempo juntos?", 1),
        ("¿Cuál es la pregunta que nunca le preguntaste a una pareja pero que más querías saber?", 1),
        ("¿Cuánto te importa que una pareja tenga sentido del humor similar al tuyo?", 1),
        ("¿Cuál es la cosa más creativa que hiciste para demostrar que te gustaba alguien?", 1),
        ("¿Cuál es la señal de lenguaje corporal que más rápido te dice si alguien está interesado?", 1),
        ("¿Qué tipo de conversación es la que más disfrutás tener con alguien que te gusta?", 1),
        ("¿Cuánto peso le das a la compatibilidad espiritual o de valores profundos?", 1),
        ("¿Cuál es la cosa que una persona puede hacer en una primera cita que ya te cierra la puerta?", 1),
        ("¿Qué tan importante es para vos que tu pareja tenga proyectos propios más allá de la relación?", 1),
        ("¿Cuál es el momento más absurdamente romántico que viviste sin querer?", 1),
        ("¿Cuánto tiempo podés estar en pareja antes de empezar a necesitar tiempo solo?", 1),
        ("¿Cuál es la diferencia más grande entre cómo amás en teoría y cómo amás en la práctica?", 1),
        ("¿Cuándo fue la última vez que alguien te sorprendió completamente en el amor?", 1),
        ("¿Cuál es el mito del amor romántico que desearías que fuera verdad?", 1),
        ("¿Qué significa para vos sentirte amado en el día a día?", 1),
        ("¿Cuánto peso tienen los gustos estéticos compartidos en tu atracción hacia alguien?", 1),
        ("¿Cuál es el tipo de humor que más te conecta con una pareja?", 1),
        # Level 2 - ~10 questions
        ("¿Cuándo fue la última vez que el amor te hizo actuar en contra de tu propio juicio?", 2),
        ("¿Hay algo que aprendiste sobre el amor de una persona inesperada, no pareja?", 2),
        ("¿Cuánto de cómo te expresás en el amor viene de lo que viste en tu familia?", 2),
        ("¿Cuándo fue la última vez que priorizaste las necesidades de tu pareja por encima de las tuyas de manera genuina?", 2),
        ("¿Hay algo sobre el amor que te cuesta creer que sea posible para vos?", 2),
        ("¿Cuándo fue la última vez que te animaste a ser completamente vulnerable con alguien?", 2),
        ("¿Qué tan diferente es el amor que das del amor que creés merecer?", 2),
        ("¿Cuándo fue la última vez que alguien te hizo sentir visto de verdad en una relación?", 2),
        ("¿Cuánto espacio le das a la negociación y el compromiso en el amor versus tus principios irrenunciables?", 2),
        ("¿Hay algo del amor que querés aprender a hacer mejor en la próxima relación?", 2),
        # Level 3 - ~6 questions
        ("¿Cuál es la creencia sobre el amor que más te limita y que más te cuesta soltar?", 3),
        ("¿Cuándo fue la última vez que amaste sin miedo a salir lastimado?", 3),
        ("¿Qué necesitarías cambiar de vos mismo para poder amar de la manera que soñás?", 3),
        ("¿Hay algo sobre tu propia capacidad de amar que todavía te genera dudas?", 3),
        ("¿Cuándo fue la última vez que el amor te hizo ser la mejor versión de vos mismo?", 3),
        ("¿Cuál es la cosa que más deseás que alguien te diga alguna vez en el amor?", 3),
    ],

    "familia": [
        # Level 1 - ~24 questions
        ("¿Cuál es el olor que más asociás con la casa de tu infancia?", 1),
        ("¿Cuál fue la canción que más sonaba en tu casa cuando eras chico?", 1),
        ("¿Hay algún objeto de tu hogar de infancia que aún tenés o que te gustaría recuperar?", 1),
        ("¿Cuál es la receta de tu familia que nunca pudiste replicar igual?", 1),
        ("¿Cómo era la luz y la temperatura de la casa donde creciste?", 1),
        ("¿Cuántas generaciones de tu familia vivieron en el mismo país?", 1),
        ("¿Hay algún pariente con una historia de vida increíble que pocas personas conocen?", 1),
        ("¿Cuál es la frase que más escuchaste de tu familia y que hoy usás sin darte cuenta?", 1),
        ("¿Cuál era la rutina matutina en tu familia cuando eras chico?", 1),
        ("¿Cuándo fue la última vez que toda tu familia estuvo reunida y qué se habló?", 1),
        ("¿Qué creencia o valor familiar es el que más te define hoy?", 1),
        ("¿Hay algún familiar con quien sentís que tenés una comunicación casi telepática?", 1),
        ("¿Cuál es la forma en que tu familia demuestra afecto que es única de ustedes?", 1),
        ("¿Cuántos de tus hobbies actuales vienen directamente de influencias familiares?", 1),
        ("¿Hay alguna historia de tu árbol genealógico que te parece increíble o inspiradora?", 1),
        ("¿Cuál es la mayor diferencia generacional que notás con tu familia?", 1),
        ("¿Cómo manejaban el humor en tu familia? ¿Era parte de la cultura familiar?", 1),
        ("¿Cuál fue la última vez que un familiar te sorprendió con algo que no sabías de ellos?", 1),
        ("¿Hay alguna profesión o vocación que se repite en tu familia sin que nadie lo haya planeado?", 1),
        ("¿Cuál es el viaje o plan que más querés hacer con tu familia antes de que sea tarde?", 1),
        ("¿Cuánto de tu sentido del humor viene de cómo era el humor en tu familia?", 1),
        ("¿Cuál es la diferencia más grande entre la familia que tuviste y la familia que querés crear?", 1),
        ("¿Hay algún familiar de generaciones anteriores con quien sientas una conexión especial?", 1),
        ("¿Cuál es el valor que tu familia te enseñó que nadie más te podría haber dado?", 1),
        # Level 2 - ~10 questions
        ("¿Cuándo fue la última vez que tuviste una conversación honesta y profunda con un familiar?", 2),
        ("¿Hay algo que tu familia cree sobre vos que ya no es cierto pero que no corregiste?", 2),
        ("¿Cuánto de tu relación con el dinero viene de lo que viste en tu familia?", 2),
        ("¿Cuándo fue la última vez que perdonaste a un familiar por algo que te dolió?", 2),
        ("¿Hay algo que tu familia nunca habló abiertamente y que sería liberador que se hablara?", 2),
        ("¿Cuánto peso tienen las expectativas familiares en las decisiones que tomás hoy?", 2),
        ("¿Cuándo fue la última vez que demostraste que amás a tu familia de manera activa?", 2),
        ("¿Qué tan parecido o diferente sos de tus padres en la manera de manejar el estrés?", 2),
        ("¿Hay algo que tu familia te dio que no te diste cuenta del valor que tenía hasta tarde?", 2),
        ("¿Cuándo fue la última vez que necesitaste a tu familia y la tuviste realmente presente?", 2),
        # Level 3 - ~6 questions
        ("¿Cuál es la dinámica familiar que más daño te hizo y que más trabajo te costó reconocer?", 3),
        ("¿Cuándo fue la primera vez que viste a tus padres como personas con sus propias heridas?", 3),
        ("¿Hay algo de tu historia familiar que cambiaría completamente quién sos si lo supieras?", 3),
        ("¿Cuánto de lo que más amás y lo que más temés viene del mismo lugar de tu historia familiar?", 3),
        ("¿Cuál es la conversación que más necesitás tener con algún familiar antes de que ya no sea posible?", 3),
        ("¿Qué tan libre te sentís de ser completamente vos dentro del contexto de tu familia?", 3),
    ],

    "amistades": [
        # Level 1 - ~24 questions
        ("¿Cuál es el ritual no oficial que tenés con tu grupo de amigos más cercano?", 1),
        ("¿Hay algún amigo que siempre logra hacerte reír sin importar cómo estés?", 1),
        ("¿Cuál es la cosa más ridícula que hicieron en grupo y de la que todavía se ríen?", 1),
        ("¿Cuándo fue la última vez que un amigo te dijo algo que te cambió la perspectiva?", 1),
        ("¿Cuál es el tipo de conversación que más disfrutás tener con tus amigos?", 1),
        ("¿Hay algún amigo que admires en algo específico que vos no tenés?", 1),
        ("¿Cuándo fue la última vez que hiciste algo completamente ridículo con un amigo y fue genial?", 1),
        ("¿Cuál es la regla no escrita de tu grupo de amigos que todo el mundo respeta?", 1),
        ("¿Qué tan seguido te juntás con amigos para hablar de cosas serias versus cosas livianas?", 1),
        ("¿Hay algún amigo que sea el mejor contador de historias que conocés?", 1),
        ("¿Cuál es la ciudad o lugar que visitarías exclusivamente para ver a un amigo?", 1),
        ("¿Qué te hace saber que alguien tiene potencial para ser tu amigo de verdad?", 1),
        ("¿Cuándo fue la última vez que llamaste a un amigo solo para ver cómo estaba?", 1),
        ("¿Hay algún amigo con quien tenés un código de humor que nadie más entiende?", 1),
        ("¿Cuál es la actividad que siempre planeás con tus amigos y nunca termina pasando?", 1),
        ("¿Cuál fue el momento en que te diste cuenta de que alguien era tu amigo de verdad?", 1),
        ("¿Qué cosa de vos mismo mostrás primero cuando recién estás conociendo a alguien?", 1),
        ("¿Cuándo fue la última vez que un amigo te defendió frente a alguien?", 1),
        ("¿Hay algún amigo con quien el tiempo y la distancia no cambian nada?", 1),
        ("¿Cuál es la cosa que más disfrutás del tipo de amistad que tenés?", 1),
        ("¿Cuánto te importa tener amigos con distintas visiones del mundo a la tuya?", 1),
        ("¿Cuál fue la amistad más inesperada que desarrollaste con alguien muy diferente a vos?", 1),
        ("¿Qué cualidad en un amigo considerás indispensable?", 1),
        ("¿Cuándo fue la última vez que una amistad te hizo ser mejor persona?", 1),
        # Level 2 - ~10 questions
        ("¿Cuándo fue la última vez que sentiste que le fallaste a un amigo?", 2),
        ("¿Hay alguna amistad que descuidaste por estar muy enfocado en otra parte de tu vida?", 2),
        ("¿Cuánto te cuesta mostrarte vulnerable con tus amigos más cercanos?", 2),
        ("¿Cuándo fue la última vez que un amigo te sorprendió con algo que no sabías de él?", 2),
        ("¿Hay alguna conversación pendiente con un amigo que sabés que deberías tener?", 2),
        ("¿Cuándo fue la última vez que priorizaste una amistad por encima de algo más conveniente?", 2),
        ("¿Cuánto de tu bienestar emocional depende de la calidad de tus amistades?", 2),
        ("¿Hay algo que tus amigos saben de vos que vos mismo tardaste en aceptar?", 2),
        ("¿Cuándo fue la última vez que un amigo te dio un consejo que no querías escuchar pero que necesitabas?", 2),
        ("¿Hay algo que te cuesta perdonarle a un amigo aunque el vínculo siga en pie?", 2),
        # Level 3 - ~6 questions
        ("¿Cuándo fue la última vez que una amistad te mostró algo de vos mismo que no querías ver?", 3),
        ("¿Hay algún amigo a quien le debés una disculpa que todavía no le diste?", 3),
        ("¿Cuánto miedo te da perder a tus amigos más cercanos a medida que la vida cambia?", 3),
        ("¿Hay algo que le pedirías a tus amigos que cambiaran de cómo te tratan?", 3),
        ("¿Cuándo fue la última vez que sentiste que tus amigos realmente te conocen?", 3),
        ("¿Cuál es la cosa más importante que tus amistades te enseñaron sobre vos mismo?", 3),
    ],

    "exs": [
        # Level 1 - ~24 questions
        ("¿Cuál es el olor o canción que más instantáneamente te recuerda a una relación pasada?", 1),
        ("¿Cuántas rupturas viviste donde la iniciativa fue tuya?", 1),
        ("¿Cuál fue el momento más gracioso que viviste con un ex en retrospectiva?", 1),
        ("¿Cuándo fue la última vez que hablaste de un ex con genuina gratitud?", 1),
        ("¿Hay algún lugar que sigue teniendo la 'marca' de una relación pasada?", 1),
        ("¿Cuánto tiempo tardaste en crear nuevos rituales propios después de una ruptura?", 1),
        ("¿Cuál fue la cosa que más extrañaste de la rutina de una relación pasada?", 1),
        ("¿Qué tipo de película o serie te ponías a ver cuando terminabas una relación?", 1),
        ("¿Cuándo fue la última vez que alguien te preguntó por un ex y te sorprendió tu propia respuesta?", 1),
        ("¿Cuál fue la primera vez que pudiste hablar de una relación pasada sin que te afectara?", 1),
        ("¿Hay algún hábito que adoptaste de una relación pasada que aún mantenés?", 1),
        ("¿Cuándo fue la última vez que viste a un ex y te sorprendió que no te afectara?", 1),
        ("¿Cuál fue la cosa más linda que te escribió o le escribiste a alguien en una relación?", 1),
        ("¿Cuánto tardás en eliminar fotos o recuerdos físicos después de terminar?", 1),
        ("¿Cuál fue la primera cosa que hiciste para vos mismo después de terminar una relación importante?", 1),
        ("¿Hay algún ex del que aprendiste algo importante sobre vos que todavía valorás?", 1),
        ("¿Cuándo fue la última vez que alguien de tu pasado amoroso te escribió de manera inesperada?", 1),
        ("¿Cuántas veces te enamoraste de alguien que en el fondo sabías que no era para vos?", 1),
        ("¿Cuál es la señal de alerta más obvia que ignoraste en una relación y que hoy ves clarísima?", 1),
        ("¿Hay algún ex al que genuinamente le desearías lo mejor si lo cruzaras mañana?", 1),
        ("¿Cuándo fue la primera vez que terminaste una relación sin necesitar la aprobación del otro?", 1),
        ("¿Cuál fue la relación donde sentiste que realmente podías ser vos mismo?", 1),
        ("¿Cuánto de lo que buscás en una pareja hoy es lo opuesto de lo que buscabas antes?", 1),
        ("¿Cuál fue la relación que más te hizo reír en el buen sentido?", 1),
        # Level 2 - ~10 questions
        ("¿Cuándo fue la última vez que una relación terminada te hizo replantear algo sobre vos mismo?", 2),
        ("¿Hay algo que perdonaste en una relación pasada que hoy no tolerarías?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que ya sanaste algo de una relación pasada?", 2),
        ("¿Cuánto de la forma en que terminaron tus relaciones dice algo sobre cómo eras en ese momento?", 2),
        ("¿Hay algo que te gustaría que un ex supiera sobre vos ahora?", 2),
        ("¿Cuándo fue la última vez que actuaste desde el dolor de una relación pasada sin darte cuenta?", 2),
        ("¿Cuánto de quién sos en el amor hoy fue formado por alguien específico de tu pasado?", 2),
        ("¿Hay algo de cómo terminó una relación de lo que te responsabilizás más hoy de lo que lo hacías antes?", 2),
        ("¿Cuándo fue la primera vez que te permitiste extrañar a alguien sin sentirte mal por eso?", 2),
        ("¿Qué cosas sabés ahora sobre el amor que te hubieran cambiado una relación pasada?", 2),
        # Level 3 - ~6 questions
        ("¿Cuál es la herida de amor más antigua que todavía afecta cómo te relacionás?", 3),
        ("¿Cuándo fue la última vez que amaste a alguien más de lo que te amabas a vos mismo y qué pasó?", 3),
        ("¿Qué patrón amoroso venís repitiendo que sabés que necesitás romper?", 3),
        ("¿Hay algo de una relación pasada que perdonaste pero que en el fondo no terminaste de soltar?", 3),
        ("¿Cuándo fue la última vez que elegiste quedarte solo antes que volver a algo conocido que no te hacía bien?", 3),
        ("¿Cuál es la cosa que más te costó reconocer de vos mismo a través de tus relaciones?", 3),
    ],

    "personalidad": [
        # Level 1 - ~24 questions
        ("¿Cuál es tu reacción cuando algo te parece genuinamente gracioso?", 1),
        ("¿Qué tipo de humor preferís: absurdo, irónico, observacional o de slapstick?", 1),
        ("¿Cuál es la cosa cotidiana que te genera una alegría desproporcionada?", 1),
        ("¿Qué decís o hacés cuando estás nervioso que los demás quizás notan antes que vos?", 1),
        ("¿Cuál es el lenguaje corporal o gesto que más te delata cuando estás mintiendo o incómodo?", 1),
        ("¿Sos de los que procesa las emociones hablando o necesitás tiempo solo primero?", 1),
        ("¿Cuánto tiempo tardás en confiar en alguien lo suficiente como para mostrar tu lado más raro?", 1),
        ("¿Cuál es la cosa más absurda que encontrás genuinamente interesante?", 1),
        ("¿Qué es lo que más disfrutan los que te conocen de tu personalidad?", 1),
        ("¿Cuánto influye tu estado físico en tu estado emocional?", 1),
        ("¿Cuál es la cosa que hacés cuando querés evitar pensar en algo?", 1),
        ("¿Sos de los que necesita entender el 'por qué' de las cosas o podés aceptar sin explicación?", 1),
        ("¿Cuál es el tipo de persona que más te inspira a ser mejor?", 1),
        ("¿Cuánto de vos mismo mostrás en las redes sociales versus en persona?", 1),
        ("¿Cuál es la cosa de la que más orgulloso te ponés cuando alguien la nota?", 1),
        ("¿Qué tipo de ambiente físico necesitás para estar en tu mejor estado?", 1),
        ("¿Cuál es la cosa que más veces empezaste sin terminar?", 1),
        ("¿Cómo manejás cuando alguien tiene una opinión completamente opuesta a la tuya?", 1),
        ("¿Cuál es la cosa que hacés cuando querés procesar algo difícil?", 1),
        ("¿Sos más de actuar y preguntar después, o pensar mucho antes de actuar?", 1),
        ("¿Qué cosa tuya le resultaría completamente sorpresiva a alguien que recién te conoce?", 1),
        ("¿Cuánto espacio necesitás entre lo que sentís y lo que expresás?", 1),
        ("¿Cuál es la cosa que nunca hacés pero que en secreto siempre quisiste intentar?", 1),
        ("¿Cuánto cambia tu personalidad según con quién estás?", 1),
        # Level 2 - ~10 questions
        ("¿Cuándo fue la última vez que tu intuición te dijo algo que tu cabeza tardó en procesar?", 2),
        ("¿Cuánto de cómo te ves a vos mismo coincide con cómo te ven los demás?", 2),
        ("¿Cuándo fue la última vez que te sorprendiste actuando de manera que no esperabas?", 2),
        ("¿Hay algo de tu carácter que sabés que es tuyo pero que te resulta difícil de explicar?", 2),
        ("¿Cuándo fue la última vez que actuaste desde tus valores aunque te costara algo?", 2),
        ("¿Hay algo sobre tu identidad que cambió radicalmente en los últimos años?", 2),
        ("¿Cuándo fue la última vez que te permitiste hacer algo sin saber si iba a salir bien?", 2),
        ("¿Cuánto de tu manera de relacionarte viene de mecanismos de defensa que alguna vez fueron útiles?", 2),
        ("¿Hay algo de vos mismo que te cuesta recibir como elogio?", 2),
        ("¿Cuándo fue la última vez que cambiaste de opinión en público y te sintió bien?", 2),
        # Level 3 - ~6 questions
        ("¿Cuál es la parte de vos mismo que más protegés y que menos dejás ver?", 3),
        ("¿Cuándo fue la última vez que te animaste a hacer algo que exponía tu lado más vulnerable?", 3),
        ("¿Hay algo que sabés sobre vos mismo que cambiaria cómo te ven los demás si lo supieran?", 3),
        ("¿Cuánto de quién sos es realmente elegido y cuánto es una respuesta adaptativa a tu historia?", 3),
        ("¿Cuál es la cosa que más te acerca a sentirte completamente vos mismo?", 3),
        ("¿Qué necesitarías que cambiara en vos para sentirte en paz con quién sos?", 3),
    ],

    "miedos": [
        # Level 1 - ~24 questions
        ("¿Cuál es el tipo de contenido en redes que más ansiedad te genera?", 1),
        ("¿Le tenés miedo a las situaciones de vergüenza pública?", 1),
        ("¿Cuál es el escenario hipotético que más te asusta pensar aunque sería improbable?", 1),
        ("¿Qué tan seguido sentís miedo de hacer el ridículo?", 1),
        ("¿Cuál es el sonido que más te sobresalta cuando no te lo esperás?", 1),
        ("¿Le tenés miedo a los espacios bajo el agua o a las profundidades?", 1),
        ("¿Cuál es el tipo de situación laboral que más te genera ansiedad?", 1),
        ("¿Cuándo fue la última vez que tuviste miedo de decepcionar a alguien?", 1),
        ("¿Cuál es la fobia urbana más común que entendés aunque no la tenés?", 1),
        ("¿Le tenés miedo a los eclipses, fenómenos astronómicos o catástrofes naturales?", 1),
        ("¿Cuándo fue la última vez que el miedo te hizo pedir ayuda?", 1),
        ("¿Cuál es la actividad tecnológica o digital que más te genera desconfianza o miedo?", 1),
        ("¿Le tenés miedo a perder la memoria o la claridad mental?", 1),
        ("¿Cuándo fue la última vez que el miedo te hizo ser más cauteloso de lo necesario?", 1),
        ("¿Le tenés miedo a las enfermedades virales o pandemias?", 1),
        ("¿Cuál es la situación con extraños que más evitás?", 1),
        ("¿Cuándo fue la última vez que el miedo te generó una respuesta física concreta?", 1),
        ("¿Le tenés miedo a tener que depender de alguien en el futuro?", 1),
        ("¿Cuál es la pesadilla más recurrente que tuviste de adulto?", 1),
        ("¿Qué actividad social te genera más ansiedad anticipatoria?", 1),
        ("¿Le tenés miedo a los cambios de humor propios o de personas cercanas?", 1),
        ("¿Cuándo fue la última vez que el miedo te hizo más pequeño de lo que eras?", 1),
        ("¿Cuál es el lugar o situación que inmediatamente te activa el modo alerta?", 1),
        ("¿Le tenés miedo a la irrelevancia o a ser olvidado?", 1),
        # Level 2 - ~10 questions
        ("¿Cuándo fue la última vez que enfrentaste un miedo y te cambió algo?", 2),
        ("¿Hay algún miedo que antes controlabas y que ahora sientes que creció?", 2),
        ("¿Cuánto de tus decisiones de vida están organizadas alrededor de evitar algo específico?", 2),
        ("¿Cuándo fue la última vez que hablaste abiertamente de un miedo con alguien?", 2),
        ("¿Hay algo que tu miedo te impide hacer y que sabés que te haría bien?", 2),
        ("¿Cuándo fue la última vez que el miedo al qué dirán te costó algo importante?", 2),
        ("¿Cuánto de tu miedo más grande viene de algo que viste o viviste de chico?", 2),
        ("¿Hay algo que le tenés miedo de pedirle a alguien cercano?", 2),
        ("¿Cuándo fue la última vez que el miedo te resultó útil en lugar de limitante?", 2),
        ("¿Cuánto espacio ocupa el miedo a la incertidumbre en tu vida cotidiana?", 2),
        # Level 3 - ~6 questions
        ("¿Cuál es el miedo que más vergüenza te da y que más trabajo te costó nombrar?", 3),
        ("¿Cuándo fue la última vez que te permitiste sentir miedo sin hacer nada para controlarlo?", 3),
        ("¿Hay algo que sabés que siempre vas a temer pero que aprendiste a convivir con ello?", 3),
        ("¿Cuál es el miedo que más define la persona que sos y que más relación tiene con el amor que no recibiste?", 3),
        ("¿Si pudieras vivir sin tu miedo más central, qué serías capaz de hacer que hoy no hacés?", 3),
        ("¿Cuándo fue la última vez que el miedo te protegió de algo real versus cuando solo te frenó?", 3),
    ],

    "logros": [
        # Level 1 - ~24 questions
        ("¿Cuál fue la primera vez que alguien te pidió consejo en algo porque eras el más experto?", 1),
        ("¿Cuándo fue la última vez que algo que hiciste tuvo un impacto que no esperabas?", 1),
        ("¿Cuál es la cosa más creativa que lograste sin seguir ningún manual?", 1),
        ("¿Cuándo fue la última vez que te pusiste un límite de tiempo y lo cumpliste?", 1),
        ("¿Hay algún logro que conseguiste casi por accidente que resultó ser de los más importantes?", 1),
        ("¿Cuándo fue la última vez que fallaste rápido y aprendiste más que si hubieras tardado en fallar?", 1),
        ("¿Cuál es la cosa que lograste colaborativamente que nunca hubiera salido solo?", 1),
        ("¿Cuándo fue la última vez que tu disciplina te salvó de algo?", 1),
        ("¿Cuál es el hábito que instalaste que más impacto tuvo en lo que lograste después?", 1),
        ("¿Hay algún logro técnico o de aprendizaje que nadie en tu círculo cercano sabe que tenés?", 1),
        ("¿Cuándo fue la última vez que terminaste algo con el que sabías que iba a quedar bien?", 1),
        ("¿Cuál fue la primera vez que alguien confió en vos para liderar algo?", 1),
        ("¿Cuándo fue la última vez que hiciste algo por puro placer y resultó ser extraordinario?", 1),
        ("¿Cuál es el logro más silencioso que tenés, uno que no está en ningún CV ni red social?", 1),
        ("¿Cuándo fue la última vez que superaste una expectativa de alguien que creía en vos?", 1),
        ("¿Cuál fue la primera vez que vos mismo reconociste que habías mejorado en algo?", 1),
        ("¿Cuándo fue la última vez que algo que considerabas pequeño resultó ser enorme para alguien más?", 1),
        ("¿Cuál es la cosa que más veces fracasaste antes de lograr?", 1),
        ("¿Cuándo fue la última vez que disfrutaste el proceso de algo más que el resultado?", 1),
        ("¿Cuál es el logro de alguien cercano que te llenó de orgullo como si fuera tuyo?", 1),
        ("¿Cuándo fue la última vez que te permitiste descansar sin sentirte culpable?", 1),
        ("¿Cuál fue la primera vez que creaste algo desde cero y pensaste 'esto es mío'?", 1),
        ("¿Cuándo fue la última vez que te comprometiste con algo difícil sin saber si lo ibas a lograr?", 1),
        ("¿Cuál es el logro que más le costó creer a la gente cuando se lo contaste?", 1),
        # Level 2 - ~10 questions
        ("¿Cuándo fue la última vez que un fracaso te abrió una puerta que no esperabas?", 2),
        ("¿Hay algo que lograste que en el fondo te da más miedo perder que cualquier otra cosa?", 2),
        ("¿Cuándo fue la última vez que reconociste el aporte de alguien más en algo que vos te atribuís?", 2),
        ("¿Cuánto de lo que lograste fue posible gracias a privilegios que no elegiste?", 2),
        ("¿Hay algo que dejaste de intentar después de fallar que hoy te arrepentís de no haber retomado?", 2),
        ("¿Cuándo fue la última vez que pusiste toda tu energía en algo que valió cada gramo?", 2),
        ("¿Cuánto miedo te da que los logros que tenés no sean suficientes para lo que querés?", 2),
        ("¿Hay algo que lograste que cambió la percepción que tenías sobre tus propios límites?", 2),
        ("¿Cuándo fue la última vez que hiciste algo importante sin importarte si alguien lo iba a ver?", 2),
        ("¿Cuánto de lo que definís como logro está alineado con lo que verdaderamente valorás?", 2),
        # Level 3 - ~6 questions
        ("¿Cuál es el logro más profundo que nadie puede quitarte aunque perdieras todo lo demás?", 3),
        ("¿Cuándo fue la última vez que lograste algo y en lugar de festejarlo te preguntaste si era suficiente?", 3),
        ("¿Cuál es la diferencia entre el éxito que soñabas y el que hoy perseguís, y qué cambió?", 3),
        ("¿Cuánto de tus logros son realmente tuyos y cuánto son una respuesta a las expectativas de otros?", 3),
        ("¿Cuándo fue la última vez que te permitiste celebrar algo sin minimizarlo?", 3),
        ("¿Qué significaría para vos saber que ya hiciste suficiente?", 3),
    ],

    "sinFiltro": [
        # Level 1 - ~24 questions
        ("¿Cuántas veces al día abrís el refri sin saber bien por qué?", 1),
        ("¿Cuál es el pensamiento más raro que tuviste esta semana que no le contaste a nadie?", 1),
        ("¿Alguna vez te quedaste dormido en algo que se supone no debías?", 1),
        ("¿Cuántos likes le diste esta semana a cosas de personas que no te caen bien?", 1),
        ("¿Cuál es la cosa más barata que comprás de manera impulsiva y que no necesitás?", 1),
        ("¿Alguna vez te creaste una cuenta falsa en alguna red solo para mirar algo?", 1),
        ("¿Cuántas veces fingiste entender algo en una conversación cuando no entendiste nada?", 1),
        ("¿Cuál es el tema sobre el que nunca hablás pero que seguís en silencio en redes?", 1),
        ("¿Alguna vez leyó un mensaje de alguien importante y lo ignoraste deliberadamente?", 1),
        ("¿Cuántos episodios de algo mirás de corrido antes de sentirte culpable?", 1),
        ("¿Cuál es la canción que pondrías si nadie te viera pero que jamás admitirías en público?", 1),
        ("¿Alguna vez le mandaste una captura de pantalla de alguien a otra persona sin permiso?", 1),
        ("¿Cuántas veces esta semana dijiste que estabas bien cuando no estabas?", 1),
        ("¿Cuál es la cosa más ridícula que googled después de las 12 de la noche?", 1),
        ("¿Alguna vez te probaste algo en un local sin intención de comprarlo?", 1),
        ("¿Cuántos planes cancelaste este mes con la misma excusa?", 1),
        ("¿Cuál es el hábito más asqueroso que tenés y que solo hacés cuando estás solo?", 1),
        ("¿Alguna vez miraste el historial de búsqueda de alguien que dejó su computadora abierta?", 1),
        ("¿Cuántas veces al día te distraés con el teléfono en medio de algo que deberías estar haciendo?", 1),
        ("¿Cuál es la cosa más irracional que hiciste por la comodidad?", 1),
        ("¿Alguna vez le mentiste a un médico sobre tus hábitos?", 1),
        ("¿Cuántas horas de contenido al día consumís que no te aporta absolutamente nada?", 1),
        ("¿Cuál es el pensamiento más perturbador que tuviste sobre alguien que amás?", 1),
        ("¿Cuántos chats tenés con gente que en algún momento quisiste pero que hoy abrirías con ansiedad?", 1),
        # Level 2 - ~10 questions
        ("¿Cuándo fue la última vez que hiciste algo por pura imagen y no te importó nada más?", 2),
        ("¿Hay algo que normalmente juzgás en otros y que vos hacés más de lo que admitís?", 2),
        ("¿Cuándo fue la última vez que te aprovechaste de la buena fe de alguien aunque fuera de manera chica?", 2),
        ("¿Cuántas veces pensaste mal de alguien sin tener suficiente información y resultó ser prejuicio puro?", 2),
        ("¿Hay algo que comprás o consumís que va en contra de tus propios valores y lo hacés igual?", 2),
        ("¿Cuándo fue la última vez que te quedaste callado ante algo injusto por conveniencia?", 2),
        ("¿Cuánto de lo que mostrás en redes es una versión editada de algo que en realidad te genera vergüenza?", 2),
        ("¿Cuándo fue la última vez que actuaste desde los celos sin que nadie lo notara?", 2),
        ("¿Hay algo que repetís con conocimiento de que no está bien y que aún así justificás?", 2),
        ("¿Cuándo fue la última vez que algo te importó solo porque le importaba a otros?", 2),
        # Level 3 - ~6 questions
        ("¿Cuál es el deseo o fantasía que más te cuesta admitir que tenés, incluso ante vos mismo?", 3),
        ("¿Hay algo de lo que hiciste en el pasado que te genera vergüenza pero que en el fondo no te arrepentís?", 3),
        ("¿Cuándo fue la última vez que actuaste de manera que sabías que no tenía vuelta atrás?", 3),
        ("¿Cuál es la mayor contradicción entre quién decís ser y quién sos en los momentos más privados?", 3),
        ("¿Qué cosa de vos mismo que nadie sabe cambiaría completamente cómo te ven si saliera a la luz?", 3),
        ("¿Cuándo fue la última vez que hiciste algo que solo podías justificar ante vos mismo y con nada más?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS4:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS4[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
