#!/usr/bin/env python3
"""Batch 31 - spirituality, meaning, purpose, mortality, legacy, wisdom, transcendence."""
import json

ADDITIONS31 = {
    "infancia": [
        ("¿Tenías alguna creencia espiritual o religiosa de chico y cómo la vivías?", 1),
        ("¿Cuándo fue la primera vez que te preguntaste de dónde venimos y a dónde vamos?", 1),
        ("¿Qué rituales o prácticas de tu familia de infancia tenían algo de sagrado para vos?", 1),
        ("¿Cuándo fue la primera vez que la muerte llegó a tu vida y cómo lo procesaste?", 1),
        ("¿Qué te enseñaron sobre el sentido de la vida de chico?", 1),
        ("¿Tenías alguna práctica de chico que te daba paz o conexión con algo más grande?", 1),
        ("¿Cuándo fue la primera vez que te hiciste preguntas existenciales?", 1),
        ("¿Qué lugar de tu infancia te generaba algo parecido a lo sagrado o lo trascendente?", 1),
        ("¿Había algún adulto en tu infancia que encarnaba una sabiduría que vos admirabas?", 1),
        ("¿Cuándo fue la primera vez que algo de la vida te resultó inexplicable y fascinante?", 1),
        ("¿Qué te enseñaron sobre Dios, lo divino, o lo espiritual de chico?", 1),
        ("¿Cuándo fue la primera vez que tuviste conciencia de tu propia mortalidad?", 1),
        ("¿Qué momentos de tu infancia tenían algo de mágico o inexplicable?", 1),
        ("¿Qué valores de tu infancia que eran casi sagrados para tu familia seguís teniendo?", 1),
        ("¿Cuándo fue la primera vez que sentiste que había algo más allá de lo visible?", 1),
        ("¿Qué personaje de libro, película o historia de tu infancia encarnaba algo que te parecía trascendente?", 1),
        ("¿Cuándo fue la primera vez que rezaste, meditaste, o hiciste algo con intención espiritual?", 1),
        ("¿Qué pregunta sobre el sentido de la vida que tenías de chico todavía no tiene respuesta?", 1),
        ("¿Qué cosa que de chico era obvia en términos de sentido hoy te resulta más compleja?", 1),
        ("¿Qué valor de tu infancia que se suponía que era absoluto fuiste cuestionando al crecer?", 1),
        ("¿Cuándo fue la primera vez que la espiritualidad de tu infancia resultó insuficiente para procesar algo real?", 2),
        ("¿Qué idea sobre el sentido de la vida que te enseñaron de chico tuvo que ser revisada de adulto?", 2),
        ("¿Cómo la primera experiencia con la muerte en tu infancia moldeó tu relación con la mortalidad hoy?", 2),
        ("¿Qué pregunta existencial de tu infancia que nadie te respondió bien todavía te hace ruido?", 2),
        ("¿Cómo la espiritualidad o religiosidad de tu familia de infancia influyó en tu búsqueda de sentido de adulto?", 2),
        ("¿Qué sabiduría de alguien de tu infancia que en el momento no entendiste hoy significa mucho?", 2),
        ("¿Cuándo fue la primera vez que encontraste sentido en algo que no podías explicar racionalmente?", 2),
        ("¿Qué creencia espiritual de tu infancia que abandonaste todavía te acompaña en alguna forma?", 3),
        ("¿Cuándo fue la primera vez que sentiste que había algo en vos que era más grande que vos mismo?", 3),
        ("¿Qué idea sobre la muerte o el más allá que tenías de chico cambió completamente y cómo te afectó ese cambio?", 3),
        ("¿Qué pregunta del sentido de la vida de tu infancia que nunca fue respondida fue sin embargo la más formativa?", 3),
        ("¿Cuándo fue la primera vez que la experiencia directa con la vida o la muerte te cambió la concepción del mundo?", 3),
        ("¿Qué cosa de la espiritualidad de tu infancia que rechazaste querés recuperar aunque sea en otra forma?", 3),
        ("¿Qué momento de tu infancia que parecía ordinario entendés hoy como uno de los más trascendentes de tu historia?", 3),
    ],

    "futuro": [
        ("¿Qué querés que digan de vos cuando ya no estés?", 1),
        ("¿Qué legado querés dejar en el mundo?", 1),
        ("¿Cómo querés que sea tu relación con la espiritualidad en el futuro?", 1),
        ("¿Qué sentido querés que tenga tu vida en términos que todavía no tiene del todo?", 1),
        ("¿Cómo te imaginás tu vejez en términos espirituales y existenciales?", 1),
        ("¿Qué cosa querés haber hecho antes de morir que todavía no hiciste?", 1),
        ("¿Cómo querés que te recuerden las personas que te importan?", 1),
        ("¿Qué práctica espiritual o de meditación querés incorporar en el futuro?", 1),
        ("¿Qué sabiduría querés haber desarrollado para cuando seas mayor?", 1),
        ("¿Cómo querés relacionarte con la idea de tu propia mortalidad en el futuro?", 1),
        ("¿Qué le querés dejar a quienes vienen después de vos?", 1),
        ("¿Qué cosa que hacés hoy que no tiene propósito querés reemplazar por algo con sentido?", 1),
        ("¿Cómo querés que sea la vejez tuya en términos de paz interior?", 1),
        ("¿Qué proyecto o acción que querés tomar tiene el mayor potencial de sentido?", 1),
        ("¿Qué le querés enseñar a alguien más joven sobre el sentido de la vida?", 1),
        ("¿Cuándo fue la última vez que hiciste algo con sentido que trascendiera lo cotidiano?", 1),
        ("¿Cómo querés envejecer de una manera que le dé sentido a todo lo vivido?", 1),
        ("¿Qué cosa que querés haber experimentado antes de morir no tiene que ver con logros sino con ser?", 1),
        ("¿Qué tipo de persona querés ser que hoy todavía no sos del todo?", 1),
        ("¿Qué contribución al mundo que querés hacer todavía está esperando?", 1),
        ("¿Cuánto de lo que hacés hoy tiene algo de sentido trascendente versus cuánto es solo funcional?", 2),
        ("¿Qué legado personal querés dejar que no tenga que ver con logros ni éxito sino con lo que fuiste?", 2),
        ("¿Cómo querés que sea tu relación con la mortalidad a medida que envejecés?", 2),
        ("¿Qué tipo de sabiduría querés haber desarrollado para cuando seas viejo que hoy todavía no tenés?", 2),
        ("¿Cuánto de lo que hacés hoy es para el futuro y cuánto para el presente y cómo querés equilibrar eso?", 2),
        ("¿Qué pregunta existencial que todavía no tenés respuesta querés haber encontrado paz con ella para cuando seas mayor?", 2),
        ("¿Cómo querés haber vivido para que cuando llegue el final la historia de tu vida tenga sentido?", 2),
        ("¿Qué versión futura de vos mismo que querés ser está más relacionada con quién sos que con qué lograste?", 3),
        ("¿Cuándo pensás en el final de tu vida qué es lo que más querés que haya sido verdad de cómo la viviste?", 3),
        ("¿Qué cosa que todavía no hiciste si no la hacés antes de morir sería tu mayor pesar?", 3),
        ("¿Cuánto del legado que querés dejar tiene que ver con lo que les das a otros versus con lo que encontraste en vos mismo?", 3),
        ("¿Cómo querés relacionarte con la idea de que todo es temporal de manera que te libere en vez de paralizarte?", 3),
        ("¿Qué sentido querés que tenga tu vida que hoy todavía le falta y qué está esperando para que aparezca?", 3),
        ("¿Cuándo pensás en la muerte qué es lo primero que surge y qué dice eso de cómo estás viviendo?", 3),
    ],

    "amor": [
        ("¿Creés que el amor verdadero trasciende la muerte?", 1),
        ("¿Qué dimensión del amor que viviste te pareció más trascendente?", 1),
        ("¿Creés que hay algo de destino en las personas con quienes te encontrás?", 1),
        ("¿Qué te enseñó el amor sobre el sentido de la vida?", 1),
        ("¿Hubo alguna relación en tu vida que sentiste que tenía algo de sagrado?", 1),
        ("¿Creés que el amor puede ser una práctica espiritual?", 1),
        ("¿Qué le pedirías a una relación en términos de propósito compartido?", 1),
        ("¿Cómo querés que el amor esté presente en los últimos años de tu vida?", 1),
        ("¿Hubo algún momento en el amor que sentiste que estabas más allá de vos mismo?", 1),
        ("¿Qué sabiduría sobre el amor que hoy tenés te hubiera cambiado algo en relaciones pasadas?", 1),
        ("¿Cómo el amor que viviste cambió tu relación con el sentido de la vida?", 1),
        ("¿Qué tipo de amor que querés tener tiene algo de sagrado o trascendente para vos?", 1),
        ("¿Qué le querés dejar a alguien que amás que no sea material?", 1),
        ("¿Hubo alguna pérdida en el amor que te enseñó algo sobre lo que más importa?", 1),
        ("¿Cómo el amor te conecta con algo más grande que vos mismo?", 1),
        ("¿Qué cosa del amor que te da más miedo perder no es algo concreto sino algo intangible?", 1),
        ("¿Cuándo fue la última vez que el amor te hizo sentir que la vida tiene sentido de maneras que no podés explicar?", 1),
        ("¿Qué imagen del amor que tenés que trascendiría incluso si todo lo demás cambiara?", 1),
        ("¿Hubo alguna relación en tu vida que cambió tu concepción de lo que es posible en el amor?", 1),
        ("¿Cuándo fue la última vez que el amor te conectó con algo que sentiste como más grande que vos mismo?", 1),
        ("¿Cuánto del amor que buscás tiene que ver con encontrar sentido en la existencia?", 2),
        ("¿Qué cosa del amor que viviste que en el momento fue ordinaria hoy entendés como sagrada?", 2),
        ("¿Cómo el amor que tuviste y perdiste cambió tu relación con lo que es temporal y lo que dura?", 2),
        ("¿Qué tipo de amor que querés construir tiene una dimensión de propósito que va más allá de la pareja?", 2),
        ("¿Cuándo fue la primera vez que entendiste que amar a alguien te conectaba con algo mayor que vos mismo?", 2),
        ("¿Qué pérdida en el amor que viviste te enseñó algo sobre el sentido de la vida que ninguna alegría podía enseñarte?", 2),
        ("¿Cómo el amor que tenés o que querés tener tiene algo de vocación o llamado más que solo de elección?", 2),
        ("¿Qué conversación sobre el sentido de la vida y la muerte que querés tener con alguien que amás seguís postergando?", 3),
        ("¿Cuánto del amor que amás genuinamente te conecta con algo que trasciende tu propia existencia?", 3),
        ("¿Qué amor de tu vida si lo mirás desde la perspectiva de toda tu historia tiene el mayor peso trascendente?", 3),
        ("¿Cómo el amor te ayudó a hacer las paces con la mortalidad o te la hizo más difícil?", 3),
        ("¿Qué le querés decir a alguien que amás sobre el sentido que tiene en tu vida antes de que sea tarde?", 3),
        ("¿Cuánto de lo que buscás en el amor es en realidad una búsqueda de sentido que el amor a veces puede dar?", 3),
        ("¿Qué cosa del amor que todavía querés vivir tiene algo de sagrado para vos que no podés explicar del todo?", 3),
    ],

    "familia": [
        ("¿Qué legado espiritual o de valores recibiste de tu familia?", 1),
        ("¿Cómo tu familia abordaba los temas de la muerte y el más allá?", 1),
        ("¿Qué ritual familiar que tenía algo de sagrado recordás con más emoción?", 1),
        ("¿Qué sabiduría de alguien de tu familia que ya no está seguís llevando?", 1),
        ("¿Cuándo fue la primera vez que la muerte de alguien de tu familia cambió algo en vos?", 1),
        ("¿Qué legado que recibiste de tu familia querés transmitir y cuál querés que se detenga en vos?", 1),
        ("¿Cómo tu familia de origen moldeó tu relación con la espiritualidad o la fe?", 1),
        ("¿Qué valor que es central en tu familia tiene algo de sagrado para vos?", 1),
        ("¿Cuándo fue la última vez que una conversación con alguien de tu familia te conectó con algo más grande?", 1),
        ("¿Qué parte de la historia de tu familia que trasciende lo cotidiano querés que no se olvide?", 1),
        ("¿Qué cosa de tu familia que ya no está te genera el mayor sentido de pérdida y también de gratitud?", 1),
        ("¿Cómo querés que tu familia recuerde quién fuiste?", 1),
        ("¿Qué tipo de familia que querés construir o mantener tiene algo de sagrado o de propósito compartido?", 1),
        ("¿Qué momento familiar que fue ordinario hoy entendés como uno de los más trascendentes?", 1),
        ("¿Cuándo fue la última vez que algo de tu historia familiar te llenó de un sentido de propósito?", 1),
        ("¿Qué cosa de tu familia que perdiste con el tiempo te hace tomar más consciencia de lo efímero?", 1),
        ("¿Qué legado que querés dejar a tu familia tiene menos que ver con bienes y más con quién fuiste?", 1),
        ("¿Cuándo fue la primera vez que un familiar mayor te compartió algo de sabiduría que en el momento no entendiste?", 1),
        ("¿Qué cosa de tu familia que tomabas por sentada hoy entendés como un regalo?", 1),
        ("¿Cómo querés que sea la conversación sobre la muerte en tu familia?", 1),
        ("¿Cuánto del sentido de pertenencia que te da tu familia tiene algo de trascendente que va más allá de los vínculos individuales?", 2),
        ("¿Qué cosa de tu historia familiar que involucra pérdida y duelo te enseñó algo sobre el sentido de la vida?", 2),
        ("¿Cómo la muerte de alguien de tu familia que fue importante moldeó tu relación con lo que importa de verdad?", 2),
        ("¿Qué legado espiritual o de valores que recibiste de tu familia que en el momento rechazaste hoy entendés diferente?", 2),
        ("¿Qué conversación sobre la muerte o el sentido de la vida que nunca tuviste con alguien de tu familia querés tener?", 2),
        ("¿Cuándo fue la primera vez que entendiste que la historia de tu familia era más grande que la historia de cada uno?", 2),
        ("¿Qué cosa de tu familia que trasciende lo cotidiano querés que esté presente en quienes vengan después?", 2),
        ("¿Qué momento familiar que involucró la muerte o la pérdida te cambió de manera permanente?", 3),
        ("¿Cuánto del sentido de tu vida está ligado a algo que trasciende tu existencia individual y se conecta con tu familia?", 3),
        ("¿Qué le querés dejar a tu familia que no sea material y que sin embargo sea lo más valioso?", 3),
        ("¿Cuándo fue la última vez que pensaste en tu lugar en la cadena de generaciones de tu familia y qué te generó?", 3),
        ("¿Qué cosa de la historia de tu familia que no fue suficientemente honrada querés honrar antes de que se olvide?", 3),
        ("¿Cuánto de lo que sos como persona tiene que ver con un propósito que trasciende tu vida individual y se conecta con algo mayor?", 3),
        ("¿Qué conversación sobre el sentido de todo y sobre lo efímero que querés tener con alguien de tu familia todavía no tuviste?", 3),
    ],

    "amistades": [
        ("¿Hay algún amigo con quien puedas hablar de los temas más profundos de la existencia?", 1),
        ("¿Cuándo fue la última vez que una conversación con un amigo te tocó algo del orden del sentido?", 1),
        ("¿Qué amigo tuyo encarna una sabiduría de vida que admirás?", 1),
        ("¿Hubo alguna amistad que te ayudó a atravesar algo de orden existencial?", 1),
        ("¿Qué conversación con un amigo sobre la muerte o el sentido de la vida te quedó?", 1),
        ("¿Cuándo fue la última vez que una amistad te conectó con algo más grande que vos mismo?", 1),
        ("¿Qué amigo tuyo tiene una relación con la espiritualidad o la trascendencia que te genera curiosidad o envidia?", 1),
        ("¿Cuándo fue la última vez que compartiste algo de tu espiritualidad o búsqueda de sentido con un amigo?", 1),
        ("¿Qué amigo que perdiste cuya ausencia tiene algo de trascendente en tu historia?", 1),
        ("¿Hubo alguna amistad que cambió tu manera de ver la vida de manera fundamental?", 1),
        ("¿Qué cosa que le querés decir a un amigo sobre lo que significa para vos todavía no dijiste?", 1),
        ("¿Cuándo fue la última vez que la muerte o la enfermedad de alguien cercano en el círculo de amigos cambió algo en vos?", 1),
        ("¿Qué amigo tuyo sería el más indicado para tener una conversación profunda sobre el sentido de la vida?", 1),
        ("¿Cómo una amistad importante en tu vida te ayudó a encontrar o sostener sentido en momentos difíciles?", 1),
        ("¿Cuándo fue la última vez que un amigo te compartió algo de su visión del mundo que te cambió algo?", 1),
        ("¿Qué amigo tuyo que ya no está tiene un lugar en tu historia que trasciende lo cotidiano?", 1),
        ("¿Qué cosa que le querés dejar a un amigo que no sea material?", 1),
        ("¿Cuándo fue la última vez que una amistad te hizo sentir que formás parte de algo más grande?", 1),
        ("¿Qué conversación existencial pendiente con algún amigo querés tener antes de que sea tarde?", 1),
        ("¿Cuándo fue la última vez que la presencia de un amigo fue en sí misma suficiente para darle sentido a algo?", 1),
        ("¿Cuánto del sentido de tu vida viene de los vínculos de amistad y qué te dice eso?", 2),
        ("¿Qué amigo tuyo que ya no está dejó una huella en vos que tiene algo de sagrado?", 2),
        ("¿Cómo las amistades más profundas que tuviste cambiaron tu manera de entender lo que importa?", 2),
        ("¿Qué conversación de amistad que tuviste sobre la muerte o el sentido de la vida fue la más transformadora?", 2),
        ("¿Cuándo fue la primera vez que una amistad te ayudó a atravesar algo existencial que solo no hubieras podido?", 2),
        ("¿Qué amigo tuyo que encarna algo que admirás profundamente te hace plantearte cosas sobre tu propia vida?", 2),
        ("¿Cuánto de lo que creés sobre el sentido de la vida fue moldeado por conversaciones con amigos que importaron mucho?", 2),
        ("¿Qué amigo tuyo cuando pensás en toda tu historia tiene un lugar que trasciende la categoría de amistad?", 3),
        ("¿Cuánto del sentido más profundo de tu vida viene de los vínculos que tenés con otros y qué pasa si eso cambia?", 3),
        ("¿Qué conversación con un amigo sobre lo que más importa que todavía no tuviste merece ser tenida?", 3),
        ("¿Cómo las amistades que perdiste con el tiempo cambiaron tu relación con lo que es efímero y lo que dura?", 3),
        ("¿Qué le querías decir a alguien que fue un amigo fundamental y que ya no podés decirle?", 3),
        ("¿Cuándo fue la última vez que una amistad te recordó que estás vivo de una manera que ninguna otra cosa podía?", 3),
        ("¿Qué amigo tuyo si te preguntara en qué creés de verdad te costaría responder con honestidad?", 3),
    ],

    "exs": [
        ("¿Hubo alguna relación pasada que tuvo algo de sagrado o trascendente para vos?", 1),
        ("¿Qué te enseñó una relación pasada sobre el sentido de la vida?", 1),
        ("¿Hubo alguna ruptura que te obligó a reformular qué importa?", 1),
        ("¿Qué legado intangible dejó en vos la relación más importante que tuviste?", 1),
        ("¿Cuándo fue la primera vez que una pérdida en el amor te conectó con algo existencial?", 1),
        ("¿Qué sabiduría sobre la vida que hoy tenés viene directamente de haber amado y perdido?", 1),
        ("¿Hay algún ex con quien sentís que tuviste algo que iba más allá de lo cotidiano?", 1),
        ("¿Qué te enseñó sobre vos mismo la relación más difícil que tuviste?", 1),
        ("¿Cuándo fue la primera vez que el final de una relación te hizo plantearte cosas fundamentales?", 1),
        ("¿Qué cosa de una relación pasada que fue ordinaria hoy entendés como trascendente?", 1),
        ("¿Hubo alguna relación pasada que te cambió la relación con lo que creés que importa?", 1),
        ("¿Qué relación del pasado te hizo más sabio sobre la vida aunque también te costó?", 1),
        ("¿Cuándo fue la primera vez que el amor te conectó con algo que no podías explicar racionalmente?", 1),
        ("¿Qué cosa de una relación pasada que perdiste te recuerda que todo es temporal?", 1),
        ("¿Hubo algún momento con alguien del pasado que sentiste que tocaba algo de lo sagrado?", 1),
        ("¿Qué aprendiste sobre el amor y la vida de la relación que más te costó superar?", 1),
        ("¿Cuándo fue la última vez que pensaste en alguien del pasado con algo que no era nostalgia sino gratitud por lo que fue?", 1),
        ("¿Qué parte de vos que existe gracias a una relación pasada es la parte más valiosa?", 1),
        ("¿Cuándo fue la primera vez que entendiste que una pérdida en el amor podía tener algo de significado a pesar del dolor?", 1),
        ("¿Qué relación del pasado tuyo cambió permanentemente lo que sos capaz de ver en el amor?", 1),
        ("¿Cuánto de la sabiduría que tenés hoy sobre la vida viene de haber amado y perdido?", 2),
        ("¿Qué pérdida en el amor del pasado que en el momento fue devastadora hoy entendés como parte de algo más grande?", 2),
        ("¿Cómo la experiencia de perder algo o a alguien en el amor cambió tu relación con lo efímero?", 2),
        ("¿Qué relación del pasado que tuvo algo de trascendente todavía te define de maneras que no siempre ves?", 2),
        ("¿Cuándo fue la primera vez que el dolor de una relación terminada te enseñó algo sobre el sentido de la vida?", 2),
        ("¿Qué cosa que aprendiste sobre vos mismo en la relación más difícil tiene el mayor peso en quién sos hoy?", 2),
        ("¿Cuánto de lo que creés sobre el amor viene de haber tenido y perdido algo que importó mucho?", 2),
        ("¿Qué relación del pasado que en el momento fue un fracaso fue en realidad una de las más formativas de tu historia?", 3),
        ("¿Cuánto del sentido que tiene tu vida hoy fue moldeado por relaciones pasadas que ya no están?", 3),
        ("¿Qué le querías decir a alguien del pasado que amaste y que ya no podés decirle y cómo llevás eso?", 3),
        ("¿Cuándo fue la primera vez que entendiste que perder a alguien que amabas te hacía más consciente de estar vivo?", 3),
        ("¿Qué cosa de una relación pasada que fue sagrada para vos querés honrar aunque ya no exista?", 3),
        ("¿Cuánto de lo que amás del amor hoy viene de haber aprendido qué es lo que vale de haber perdido algo?", 3),
        ("¿Qué sabiduría sobre el amor que hoy tenés y que viene de una pérdida te hubiera dolido saber que ibas a necesitar aprenderla así?", 3),
    ],

    "personalidad": [
        ("¿Cómo es tu relación con la espiritualidad o la fe?", 1),
        ("¿Qué te da sentido de manera más profunda en tu vida?", 1),
        ("¿Cómo te relacionás con la idea de tu propia mortalidad?", 1),
        ("¿Qué es lo que más te importa que trasciende lo cotidiano?", 1),
        ("¿Qué práctica tuya tiene algo de ritual o de sagrado?", 1),
        ("¿Cómo encontrás sentido en los momentos difíciles?", 1),
        ("¿Qué creés sobre lo que pasa después de la muerte?", 1),
        ("¿Qué te genera más asombro de la existencia?", 1),
        ("¿Cuándo fue la última vez que sentiste algo que podría llamarse trascendencia?", 1),
        ("¿Qué pregunta existencial te hace más ruido?", 1),
        ("¿Qué es lo que más te asusta de la finitud?", 1),
        ("¿Qué cosa de la vida que no podés explicar racionalmente igual aceptás?", 1),
        ("¿Cómo te relacionás con la idea de que todo es temporal?", 1),
        ("¿Qué cosa de vos mismo que creés que trasciende lo material?", 1),
        ("¿Cuándo fue la última vez que algo ordinario se volvió extraordinario de maneras que no podías anticipar?", 1),
        ("¿Qué es lo que más le daría sentido a tu vida si pudiera existir?", 1),
        ("¿Cómo te conectás con algo más grande que vos mismo?", 1),
        ("¿Qué idea sobre el propósito de la vida que sostenés no podés probar pero creés igual?", 1),
        ("¿Qué es lo que más querés que sea verdad sobre la vida cuando la mirás en perspectiva?", 1),
        ("¿Cuándo fue la última vez que te hiciste preguntas sobre el sentido de todo y cómo las procesaste?", 1),
        ("¿Cómo tu relación con la espiritualidad o el sentido de la vida cambió desde la infancia hasta hoy?", 2),
        ("¿Qué es lo que te da más sentido que no tiene nada que ver con logros ni éxito?", 2),
        ("¿Cómo te relacionás con la idea de que todo lo que construís es temporal?", 2),
        ("¿Qué cosa de la existencia que no podés controlar aprendiste a aceptar y qué te enseñó eso?", 2),
        ("¿Cuándo fue la primera vez que un momento de trascendencia genuina cambió algo en cómo te relacionás con la vida?", 2),
        ("¿Qué parte de tu espiritualidad o búsqueda de sentido es genuinamente tuya versus heredada?", 2),
        ("¿Cómo te preparás existencialmente para perder cosas o personas que importan?", 2),
        ("¿Cuándo fue la última vez que pensaste en tu propia muerte de manera honesta y qué surgió?", 3),
        ("¿Qué necesitaría ser verdad sobre tu vida para que cuando llegue el final puedas decir que valió la pena?", 3),
        ("¿Cuánto de lo que hacés hoy tiene algo de sentido que trasciende lo funcional y lo cotidiano?", 3),
        ("¿Qué cosa de la existencia que no podés explicar te genera más paz que angustia y por qué?", 3),
        ("¿Cuándo fue la última vez que algo te recordó que estás vivo de una manera que ninguna rutina puede?", 3),
        ("¿Qué dejarías de hacer si supieras que solo te queda un año de vida y qué dice eso de cómo estás viviendo?", 3),
        ("¿Qué es lo que más querés que sea cierto sobre vos cuando tu historia sea contada por alguien que te amó?", 3),
    ],

    "miedos": [
        ("¿Le tenés miedo a la muerte?", 1),
        ("¿Qué cosa del fin de la vida que imaginás te genera más angustia?", 1),
        ("¿Le tenés miedo a que la vida no tenga sentido?", 1),
        ("¿Cuándo fue la primera vez que el miedo a la muerte fue real y no abstracto?", 1),
        ("¿Qué miedo existencial tenés que raramente nombrás?", 1),
        ("¿Le tenés miedo al sufrimiento o a la muerte en sí?", 1),
        ("¿Cuándo fue la primera vez que la finitud de alguien que amás cambió algo en vos?", 1),
        ("¿Le tenés miedo a no haber vivido bien cuando llegue el final?", 1),
        ("¿Qué miedo tuyo a lo desconocido se conecta con lo existencial?", 1),
        ("¿Le tenés miedo a morir solo?", 1),
        ("¿Cuándo fue la última vez que pensaste en tu propia muerte y cómo lo manejaste?", 1),
        ("¿Qué miedo tuyo sobre el sentido de la vida te genera más angustia?", 1),
        ("¿Le tenés miedo a no haber sido lo que querías ser cuando llegue el final?", 1),
        ("¿Cuándo fue la última vez que el miedo a perder a alguien te hizo valorar lo que tenés?", 1),
        ("¿Qué miedo existencial que tenés raramente compartís con alguien?", 1),
        ("¿Le tenés miedo a que lo que creés sobre la vida después de la muerte sea equivocado?", 1),
        ("¿Cuándo fue la primera vez que la mortalidad propia o de alguien cercano te generó un cambio real?", 1),
        ("¿Qué miedo al olvido o a no dejar huella tenés?", 1),
        ("¿Le tenés miedo a envejecer más que a morir?", 1),
        ("¿Cuándo fue la última vez que el miedo a la muerte te hizo más consciente de estar vivo?", 1),
        ("¿Cuánto del miedo a la muerte es en realidad miedo a no haber vivido suficiente?", 2),
        ("¿Qué miedo existencial tuyo tiene el mayor peso en cómo tomás decisiones sin que lo veas claramente?", 2),
        ("¿Cómo el miedo a la finitud moldea tus elecciones de manera que no siempre reconocés?", 2),
        ("¿Cuándo fue la primera vez que un miedo existencial te llevó a un cambio real en cómo vivís?", 2),
        ("¿Qué miedo a morir sin sentido tiene más influencia sobre lo que hacés día a día?", 2),
        ("¿Cuándo fue la primera vez que el miedo a perder algo permanentemente te enseñó a valorizarlo mientras estaba?", 2),
        ("¿Qué miedo existencial que tenés si lo nombraras claramente perdería algo de poder?", 2),
        ("¿Cuándo fue la última vez que un miedo profundo sobre la vida o la muerte cambió algo genuinamente en vos?", 3),
        ("¿Cuánto del miedo a la muerte que tenés está en realidad diciéndote algo sobre cómo querés vivir?", 3),
        ("¿Qué miedo existencial tuyo si lo mirás de frente qué encontrás que no esperabas?", 3),
        ("¿Cuándo fue la primera vez que la muerte de alguien cercano te obligó a hacerte preguntas que no habías podido evitar más?", 3),
        ("¿Qué miedo a la finitud que tenés podría en realidad ser una brújula sobre lo que más importa?", 3),
        ("¿Cuánto de lo que hacés y de lo que no hacés está gobernado por el miedo a la muerte aunque nunca lo nombres así?", 3),
        ("¿Qué cambiaría en tu manera de vivir si pudieras relacionarte con la finitud desde un lugar diferente al miedo?", 3),
    ],

    "logros": [
        ("¿Qué logro tuyo tiene el mayor peso en términos de propósito?", 1),
        ("¿Qué querés que recuerden de vos que no tiene que ver con éxito ni con logros?", 1),
        ("¿Cuándo fue la última vez que lograste algo que tuvo sentido más allá de vos mismo?", 1),
        ("¿Qué legado querés dejar que sea más valioso que cualquier logro material?", 1),
        ("¿Cuándo fue la primera vez que un logro tuyo le importó a alguien más que a vos?", 1),
        ("¿Qué cosa que lograste que cambió la vida de alguien más es tu logro más importante?", 1),
        ("¿Cuándo fue la última vez que lograste algo y sentiste que tenía algo de sagrado?", 1),
        ("¿Qué logro tuyo que costó mucho tuvo un sentido que trascendía el resultado?", 1),
        ("¿Cuándo fue la primera vez que lograste algo que al verte mayor vas a querer que sea parte de tu historia?", 1),
        ("¿Qué logro que querés alcanzar tiene algo de vocación más que de ambición?", 1),
        ("¿Cuándo fue la última vez que lograste algo que te hizo sentir que formabas parte de algo más grande?", 1),
        ("¿Qué cosa que hiciste que tuvo impacto en alguien más es el logro del que más te enorgullecés?", 1),
        ("¿Cuándo fue la primera vez que entendiste que no todos los logros importantes son visibles o reconocidos?", 1),
        ("¿Qué logro que querés alcanzar tiene que ver con dejar algo que dure más que vos?", 1),
        ("¿Cuándo fue la última vez que algo que lograste te generó una sensación de que valió la vida?", 1),
        ("¿Qué contribución al mundo que querés hacer es el que tiene más sentido para vos?", 1),
        ("¿Cuándo fue la primera vez que un logro tuyo tuvo consecuencias que no esperabas y que te conectaron con algo mayor?", 1),
        ("¿Qué logro tuyo que parece pequeño en términos de reconocimiento externo es en realidad el más significativo?", 1),
        ("¿Cuándo fue la última vez que trabajaste en algo que sentías que tenía propósito más allá del resultado?", 1),
        ("¿Qué logro tuyo que querés alcanzar el vos de mayor va a valorar más que cualquier otro?", 1),
        ("¿Cuánto de lo que lograste tiene sentido más allá de lo que vos ganaste con ello?", 2),
        ("¿Qué logro futuro tuyo tiene el mayor potencial de trascender tu propia existencia?", 2),
        ("¿Cuándo fue la primera vez que entendiste que algunos de los logros más importantes son los que no aparecen en ningún CV?", 2),
        ("¿Qué legado que querés dejar requiere un tipo de logro diferente al que perseguías antes?", 2),
        ("¿Cuánto de lo que querés lograr está impulsado por el propósito y cuánto por el ego?", 2),
        ("¿Qué logro que podría parecer pequeño para otros tiene para vos el mayor peso en términos de sentido?", 2),
        ("¿Cuándo fue la primera vez que lograste algo que te hizo sentir que habías cumplido algo más grande que un objetivo?", 2),
        ("¿Qué logro futuro tuyo cuando lo mirás desde el final de la vida tendrá el mayor peso?", 3),
        ("¿Cuánto de lo que llaman logro tiene sentido verdadero para vos y cuánto es simplemente lo que se supone que querés?", 3),
        ("¿Qué contribución que querés hacer al mundo es la que más claramente conecta con tu propósito más profundo?", 3),
        ("¿Cuándo fue la última vez que algo que lograste te recordó por qué valía la pena el esfuerzo de vivir?", 3),
        ("¿Qué logro que no reconocés suficientemente como tuyo tiene el mayor peso en la historia que va a quedar de vos?", 3),
        ("¿Cuánto de lo que querés lograr es para vos y cuánto es para dejar algo que valga para otros?", 3),
        ("¿Qué sería suficiente para vos en términos de lo que lograste cuando llegue el momento de hacer el balance?", 3),
    ],

    "sinFiltro": [
        ("¿Creés genuinamente en algo después de la muerte o te resulta imposible creerlo?", 1),
        ("¿Le tenés más miedo a la muerte o a haber vivido mal?", 1),
        ("¿Qué cosa de la vida que creés que tiene sentido la mayor parte de las veces te resulta absurda en algunos momentos?", 1),
        ("¿Cuándo fue la última vez que pensaste en tu propia muerte sin angustia?", 1),
        ("¿Qué cosa de la vida que la mayoría da por sentada te parece profundamente inexplicable?", 1),
        ("¿En qué creés que no podés probar pero que sostiene algo de tu manera de vivir?", 1),
        ("¿Cuándo fue la última vez que algo ordinario te generó una sensación de que estar vivo era algo inexplicablemente valioso?", 1),
        ("¿Qué tenés miedo de que sea verdad sobre lo que hay después de la muerte?", 1),
        ("¿Cuándo fue la última vez que algo inexplicable te pasó y lo dejaste ser inexplicable en vez de explicarlo?", 1),
        ("¿Qué cosa de la espiritualidad organizada que rechazaste tiene algo que todavía te atrae aunque no lo admitas?", 1),
        ("¿Cuándo fue la última vez que hiciste algo con sentido que sabías que nadie iba a reconocer?", 1),
        ("¿Qué pregunta sobre el sentido de la vida que nunca te animás a hacer en voz alta te hace ruido?", 1),
        ("¿Cuándo fue la última vez que la muerte de alguien te recordó algo sobre cómo querés vivir que se te había olvidado?", 1),
        ("¿Qué cosa de la vida que te genera angustia existencial preferís no pensar pero que sigue estando?", 1),
        ("¿Cuándo fue la última vez que actuaste desde un lugar de propósito genuino y cómo lo reconociste?", 1),
        ("¿Qué cosa sobre vos mismo cuando pensás en toda tu vida querés que sea verdad?", 1),
        ("¿Cuándo fue la última vez que algo te recordó que todo es temporal y cómo lo viviste?", 1),
        ("¿Qué cosa que hacés que tiene sentido para vos sería completamente incomprensible para otros?", 1),
        ("¿Cuándo fue la última vez que la presencia de alguien que amás te recordó por qué vale la pena todo?", 1),
        ("¿Qué cosa de la vida que querés que sea verdad sabés que no podés probar pero la necesitás igual?", 1),
        ("¿Cuánto de la vida que vivís tiene sentido para vos cuando la mirás desde afuera sin el filtro de lo cotidiano?", 2),
        ("¿Qué cosa de la existencia que no podés explicar y que tampoco podés ignorar cómo la llevás?", 2),
        ("¿Cuándo fue la primera vez que entendiste que el sentido de la vida no era algo que se encontraba sino algo que se construía?", 2),
        ("¿Qué pregunta existencial que tenés si se la hacés a alguien que amás cambiaría la conversación?", 2),
        ("¿Cuánto de lo que hacés día a día tiene sentido cuando lo mirás desde el final y qué te dice eso?", 2),
        ("¿Qué cosa que creés sobre el sentido de la vida que nunca dijiste en voz alta necesita ser dicha?", 2),
        ("¿Cuándo fue la última vez que algo te hizo sentir que estabas vivo de una manera que ninguna rutina puede?", 2),
        ("¿Si supieras la fecha exacta de tu muerte qué harías diferente hoy y qué dice eso de cómo estás viviendo?", 3),
        ("¿Qué cosa de la vida que tomás por sentada si la perdieras cambiaría todo y por qué no la priorizás más?", 3),
        ("¿Cuándo fue la última vez que viviste un momento que en sí mismo fue suficiente justificación de todo?", 3),
        ("¿Qué necesitaría ser verdad sobre tu vida para que cuando llegue el final no te arrepientas de cómo la viviste?", 3),
        ("¿Qué le dirías a alguien que amás sobre el sentido que tiene en tu vida que todavía no dijiste?", 3),
        ("¿Cuánto de lo que postergás tiene el potencial de ser lo que más vas a extrañar no haber hecho?", 3),
        ("¿Qué pregunta sobre vos mismo que no te animás a hacer en voz alta tiene la respuesta que más necesitás?", 3),
    ],
}


def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]


def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS31:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS31[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")


if __name__ == "__main__":
    main()
