#!/usr/bin/env python3
"""Batch 35 - body, health, physical self, energy, aging, movement, food, sleep, physicality."""
import json

ADDITIONS35 = {
    "infancia": [
        ("¿Qué relación tenías con tu cuerpo cuando eras chico?", 1),
        ("¿Cómo describís tu energía física de chico en pocas palabras?", 1),
        ("¿Qué deporte o actividad física hacías de chico y qué te dejó?", 1),
        ("¿Hubo alguna enfermedad o problema físico de chico que te marcó?", 1),
        ("¿Qué comida de tu infancia te genera el recuerdo más vívido?", 1),
        ("¿Cómo dormías de chico y qué decía eso de cómo te sentías en casa?", 1),
        ("¿Tenías alguna conciencia de tu cuerpo de chico o era algo que no pensabas?", 1),
        ("¿Qué cosa física te daba más placer de chico — correr, nadar, trepar, bailar?", 1),
        ("¿Cómo tu familia hablaba (o no hablaba) del cuerpo, la salud o la comida?", 1),
        ("¿Cuál fue la primera vez que te sentiste incómodo con tu cuerpo?", 1),
        ("¿Había algún alimento que amabas de chico y que hoy ya no comés o que extrañás?", 1),
        ("¿Qué lesión o accidente físico importante tuviste de chico?", 1),
        ("¿Cómo era tu relación con el sueño de chico: dormías bien, mal, poco?", 1),
        ("¿Qué cosa hacías físicamente de chico que hoy te parece increíble que podías hacer?", 1),
        ("¿Cómo la alimentación en tu casa formó tus hábitos actuales con la comida?", 1),
        ("¿Cuánto tiempo pasabas en movimiento de chico comparado con cómo sos ahora?", 1),
        ("¿Cómo sabías de chico si te sentías bien o mal físicamente?", 1),
        ("¿Tus padres te enseñaron a escuchar tu cuerpo o te lo enseñó la vida?", 1),
        ("¿Qué relación tenías con el dolor físico de chico?", 1),
        ("¿Cómo se manejaba la enfermedad en tu familia y qué aprendiste de eso?", 1),
        ("¿Qué cosa hacías de chico para gastar energía que hoy te parece inalcanzable?", 1),
        ("¿Cuándo fue la primera vez que fuiste consciente de que tu cuerpo tenía límites?", 1),
        ("¿Había algo que comías de chico que hoy no tolerás o que te generaba problemas?", 1),
        ("¿Qué relación tenía tu cuerpo de chico con el frío, el calor, la lluvia?", 1),
        ("¿Qué recuerdos físicos de la infancia guardás con más claridad?", 1),
        ("¿Cómo los mensajes sobre el cuerpo que recibiste de chico todavía te afectan?", 2),
        ("¿Qué hábito físico o alimenticio de tu infancia resultó ser dañino y cuándo te diste cuenta?", 2),
        ("¿Cómo la relación de tus padres con su propio cuerpo moldeó la tuya?", 2),
        ("¿Qué dice de tu infancia la manera en que tratás tu cuerpo hoy?", 2),
        ("¿Cómo el cuerpo de chico te dio información sobre tu estado emocional que no sabías procesar?", 2),
        ("¿Qué hábito físico aprendiste de chico que tardaste en cuestionar porque era lo normal en tu casa?", 2),
        ("¿Qué hubiera cambiado en tu relación con tu cuerpo si de chico te hubieran enseñado a cuidarlo diferente?", 3),
        ("¿Cómo la vergüenza corporal que viviste de chico todavía aparece en tu vida de adulto?", 3),
        ("¿Qué mensaje sobre tu cuerpo recibiste de chico que tardaste en desaprender?", 3),
        ("¿De qué manera el cuerpo guardó lo que de chico no podías procesar emocionalmente?", 3),
        ("¿Qué relación tenías con el hambre de chico — física, emocional, de atención?", 3),
        ("¿Qué dice de vos la manera en que tu cuerpo registró las tensiones de tu familia cuando eras chico?", 3),
        ("¿Qué cosa de tu cuerpo de chico querías que fuera diferente y qué efecto tuvo ese deseo?", 3),
        ("¿Cómo el cuidado o descuido del cuerpo en tu infancia definió cómo te relacionás con el tuyo hoy?", 3),
        ("¿Qué parte de vos que hoy no podés escuchar empezó callándose en la infancia?", 3),
    ],

    "futuro": [
        ("¿Cómo te imaginás físicamente en 20 años?", 1),
        ("¿Qué hábito de salud querés haber establecido para cuando seas mayor?", 1),
        ("¿Cómo querés envejecer físicamente?", 1),
        ("¿Qué cosa querés poder seguir haciendo físicamente cuando tengas 70 años?", 1),
        ("¿Qué relación querés tener con la comida en el futuro?", 1),
        ("¿Cómo imaginás tu energía física en los próximos 10 años?", 1),
        ("¿Qué te da más miedo del envejecimiento físico?", 1),
        ("¿Hay algún hábito físico que querés cambiar antes de que sea demasiado tarde?", 1),
        ("¿Cómo querés que sea tu sueño en el futuro comparado con cómo es hoy?", 1),
        ("¿Qué forma de movimiento querés mantener toda la vida?", 1),
        ("¿Cómo la tecnología médica del futuro cambia lo que esperás de tu salud?", 1),
        ("¿Qué querés que diga tu cuerpo de cómo viviste cuando llegues a viejo?", 1),
        ("¿Cómo querés relacionarte con tu cuerpo a medida que cambia con la edad?", 1),
        ("¿Qué hábito físico de hoy querés que sea una constante en tu vida futura?", 1),
        ("¿Cómo imaginás tu relación con la salud cuando seas mayor?", 1),
        ("¿Qué tipo de movimiento o actividad física querés descubrir todavía?", 1),
        ("¿Cómo querés cuidar tu energía física en el futuro de manera diferente a como lo hacés ahora?", 1),
        ("¿Qué tipo de alimentación querés tener en el futuro que hoy no tenés?", 1),
        ("¿Cómo imaginás que el envejecimiento va a cambiar lo que valorás de tu cuerpo?", 1),
        ("¿Qué le querés enseñar a alguien más joven sobre cómo cuidar el cuerpo?", 1),
        ("¿Qué decisión de salud que postergás querés haber tomado antes de los próximos 5 años?", 1),
        ("¿Cómo la longevidad creciente cambia la manera en que pensás en tu cuerpo y tu salud?", 1),
        ("¿Qué parte de tu cuerpo querés cuidar más en el futuro?", 1),
        ("¿Cómo querés que sea tu relación con el dolor físico a medida que envejecés?", 1),
        ("¿Qué querés seguir siendo capaz de hacer físicamente que hoy das por hecho?", 1),
        ("¿Qué dice de cómo querés vivir la manera en que querés envejecer físicamente?", 2),
        ("¿Cómo la aceptación del cambio físico puede ser un trabajo de toda la vida?", 2),
        ("¿Qué le querés deber a tu cuerpo cuando llegues al final de tu vida?", 2),
        ("¿De qué manera el miedo al deterioro físico cambia cómo vivís hoy?", 2),
        ("¿Cómo querés equilibrar el cuidado del cuerpo sin que se convierta en una obsesión?", 2),
        ("¿Qué le pasa a tu identidad cuando tu cuerpo ya no puede hacer lo que hacía antes?", 2),
        ("¿Cómo querés relacionarte con la muerte de manera que incluya una reconciliación con tu cuerpo?", 3),
        ("¿Qué le dirías a tu cuerpo futuro — el que envejece y se deteriora?", 3),
        ("¿Qué parte del envejecimiento físico te genera más angustia existencial y por qué?", 3),
        ("¿Cómo querés vivir en tu cuerpo de manera que cuando llegues al final no tengas arrepentimientos físicos?", 3),
        ("¿Qué hubiera cambiado en tu vida si hubieras empezado a cuidar tu cuerpo 10 años antes?", 3),
        ("¿Cómo el cuerpo puede ser el lugar donde se resuelven o no se resuelven las cosas más importantes?", 3),
        ("¿Qué le querés dejar a las personas que vienen después sobre cómo relacionarse con su cuerpo?", 3),
        ("¿Qué parte de tu cuerpo querés haber honrado cuando ya no puedas?", 3),
        ("¿Cómo la finitud del cuerpo cambia el sentido de todo lo demás?", 3),
    ],

    "amor": [
        ("¿Qué lugar tiene el contacto físico en lo que necesitás de una relación?", 1),
        ("¿Cómo la atracción física se combina con la conexión emocional para vos?", 1),
        ("¿Qué dice de una relación la manera en que dos cuerpos se mueven juntos en el espacio?", 1),
        ("¿Cómo dormís con alguien que amás y qué dice eso de vos?", 1),
        ("¿Qué forma de contacto físico es la más importante para sentirte amado?", 1),
        ("¿Cómo la energía física de alguien afecta tu atracción hacia esa persona?", 1),
        ("¿Cómo manejás la diferencia de niveles de energía física con tu pareja?", 1),
        ("¿Qué relación tiene la alimentación compartida con el amor para vos?", 1),
        ("¿Cómo una enfermedad o limitación física propia o de la pareja cambia una relación?", 1),
        ("¿Qué dice del amor la manera en que dos personas cuidan o no cuidan su cuerpo juntas?", 1),
        ("¿Qué tipo de movimiento o actividad física compartida te parece especialmente íntima?", 1),
        ("¿Cómo la presencia física de alguien — su olor, su tacto, su temperatura — te conecta con el amor?", 1),
        ("¿Qué relación tiene la salud con el amor a largo plazo?", 1),
        ("¿Cómo el estrés físico de alguien afecta la relación amorosa?", 1),
        ("¿Qué cosa del cuerpo de alguien te genera la sensación más intensa de conexión o amor?", 1),
        ("¿Cómo los hábitos físicos compartidos — comer, dormir, moverse — forman el tejido de una relación?", 1),
        ("¿Cuánto peso le das a la atracción física sostenida en una relación larga?", 1),
        ("¿Cómo la distancia física cambia el amor para vos?", 1),
        ("¿Qué dice de una relación que dos personas puedan estar cómodas en el silencio físico?", 1),
        ("¿Cómo el envejecimiento físico compartido de una pareja te parece: aterrador, hermoso, inevitable?", 1),
        ("¿Qué relación tiene el sueño compartido con la intimidad para vos?", 1),
        ("¿Qué cosa física compartida te parece la más íntima en una relación?", 1),
        ("¿Cómo la salud física de alguien que amás afecta tu propio cuerpo y energía?", 1),
        ("¿Qué cosa del cuerpo de alguien recordás con más claridad de una relación pasada?", 1),
        ("¿Cuánto de lo que sentís en el cuerpo cuando estás con alguien te dice si el amor es real?", 1),
        ("¿Qué dice de la profundidad de un amor la manera en que acompañás a alguien en una enfermedad?", 2),
        ("¿Cómo el cuerpo sabe antes que la cabeza si algo amoroso funciona o no?", 2),
        ("¿Qué pasa con el amor cuando el cuerpo ya no puede lo que podía antes?", 2),
        ("¿Cómo la vulnerabilidad física — mostrarse enfermo, cansado, deteriorado — cambia lo que esperás del amor?", 2),
        ("¿Qué parte del amor está en el cuerpo de una manera que las palabras no pueden reemplazar?", 2),
        ("¿Cómo la memoria del cuerpo de alguien que perdiste o del que te alejaste cambia con el tiempo?", 2),
        ("¿Qué cosa del cuerpo de alguien te queda cuando todo lo demás de una relación se termina?", 3),
        ("¿Cómo la atracción física se transforma en algo diferente y más profundo con el tiempo en una relación larga?", 3),
        ("¿Qué hubiera pasado con tu relación con tu propio cuerpo si el amor que recibiste hubiera sido diferente?", 3),
        ("¿Qué dice de vos lo que necesitás físicamente de alguien para sentirte amado de verdad?", 3),
        ("¿Cómo el amor puede cambiar la relación que tenés con tu propio cuerpo?", 3),
        ("¿Qué parte del amor es irreduciblemente física — una cosa que ninguna palabra puede dar?", 3),
        ("¿Qué le hubiera faltado al amor más importante de tu vida si no hubiera tenido dimensión física?", 3),
        ("¿Cómo el cuerpo guarda el amor — y el desamor — de maneras que la mente no siempre entiende?", 3),
        ("¿Qué cosa de alguien que amaste queda en tu cuerpo aunque haya pasado mucho tiempo?", 3),
    ],

    "familia": [
        ("¿Cómo tu familia hablaba o no hablaba de la salud y el cuerpo?", 1),
        ("¿Hay alguna enfermedad o condición física que sea recurrente en tu familia?", 1),
        ("¿Qué hábitos alimenticios de tu familia llevas con vos hoy?", 1),
        ("¿Cómo era la comida en tu familia — un ritual, una obligación, un placer?", 1),
        ("¿Qué dice del estado emocional de tu familia la manera en que comían juntos?", 1),
        ("¿Hay algún familiar tuyo cuya relación con su cuerpo te generó admiración o preocupación?", 1),
        ("¿Cómo la salud de alguien de tu familia cambió la dinámica familiar?", 1),
        ("¿Qué cosas físicas heredaste de tu familia — buenas y malas?", 1),
        ("¿Cómo tu familia manejaba el dolor físico: se ocultaba, se exageraba, se ignoraba?", 1),
        ("¿Qué relación tenía tu familia con el descanso y el sueño?", 1),
        ("¿Había algún alimento que era central en tu familia y que hoy extrañás o no podés comer?", 1),
        ("¿Cómo la forma en que se comía en tu familia refleja la cultura o la historia de donde vienen?", 1),
        ("¿Qué rituales físicos de tu familia — comida, descanso, movimiento — seguís hoy?", 1),
        ("¿Cómo la enfermedad de alguien importante de tu familia cambió tu relación con tu propia salud?", 1),
        ("¿Qué dicen los cuerpos de tu familia — sus posturas, sus gestos, sus hábitos — sobre quiénes son?", 1),
        ("¿Cómo se hablaba de la apariencia física en tu familia y qué efecto tuvo eso en vos?", 1),
        ("¿Qué hábito físico familiar querés que deje de existir en la próxima generación?", 1),
        ("¿Qué relación había entre el cuidado del cuerpo y el amor en tu familia?", 1),
        ("¿Hay alguna receta o comida de tu familia que sea parte de tu identidad?", 1),
        ("¿Cómo los cuerpos de las personas de tu familia cambiaron con la edad y qué te enseñó eso?", 1),
        ("¿Qué cosa física hacías con tu familia que hoy recordás con más cariño?", 1),
        ("¿Hay algún problema de salud familiar que te genera preocupación para tu propio futuro?", 1),
        ("¿Cómo la manera en que tu familia comía juntos refleja cómo se relacionaban?", 1),
        ("¿Qué hábito físico de alguien de tu familia ves en vos aunque hayas querido evitarlo?", 1),
        ("¿Qué le querés transmitir a tu familia sobre el cuidado del cuerpo que nadie te enseñó a vos?", 1),
        ("¿Cómo los mensajes sobre el cuerpo y la apariencia que recibiste en tu familia todavía te afectan?", 2),
        ("¿Qué dice de la historia de tu familia la manera en que se relacionaban con la comida y el placer físico?", 2),
        ("¿Cómo la enfermedad o el deterioro físico de alguien que amás cambia tu propia relación con tu cuerpo?", 2),
        ("¿Qué legado físico de tu familia querés romper conscientemente?", 2),
        ("¿Cómo la manera en que cuidaban o descuidaban el cuerpo en tu familia habla de lo que valoraban?", 2),
        ("¿Qué parte de la historia de tu familia está guardada en los hábitos físicos que heredaste?", 2),
        ("¿Qué hubiera cambiado en vos si tu familia hubiera tenido una relación más sana con el cuerpo?", 3),
        ("¿Cómo el cuerpo puede ser el lugar donde se transmite el trauma familiar sin que nadie lo nombre?", 3),
        ("¿Qué cosa que nadie decía en tu familia se comunicaba a través del cuerpo — la tensión, el silencio físico?", 3),
        ("¿Qué parte de tu relación con la comida es en realidad una conversación con alguien de tu familia?", 3),
        ("¿Cómo el cuerpo de alguien que perdiste vive todavía en vos?", 3),
        ("¿Qué dice de la historia de tu familia que vos cuides o no tu cuerpo de la manera en que lo hacés?", 3),
        ("¿Qué conversación sobre el cuerpo o la salud nunca tuviste con alguien de tu familia y que ya no podés tener?", 3),
        ("¿Qué cosa que viviste en tu cuerpo en la infancia familiar no entendiste hasta mucho después?", 3),
        ("¿Cómo el cuerpo es el lugar donde la familia deja su marca más duradera?", 3),
    ],

    "amistades": [
        ("¿Compartís actividad física con tus amigos o eso es algo separado?", 1),
        ("¿Qué relación tenés con la comida cuando estás con amigos?", 1),
        ("¿Hay amigos con quienes tu cuerpo se relaja de una manera diferente?", 1),
        ("¿Cómo los hábitos físicos de tus amigos influyen en los tuyos?", 1),
        ("¿Algún amigo tuyo tuvo un problema de salud que cambió la amistad?", 1),
        ("¿Cómo la energía física de tus amigos afecta tu energía cuando estás con ellos?", 1),
        ("¿Qué cosa hacés físicamente con tus amigos que no harías solo?", 1),
        ("¿Tenés amigos con quienes hablar del cuerpo, la salud o el envejecimiento es natural?", 1),
        ("¿Cómo los hábitos de alimentación o sueño de tus amigos chocan o se alinean con los tuyos?", 1),
        ("¿Hay algún amigo que te enseñó algo sobre cómo cuidar o escuchar tu cuerpo?", 1),
        ("¿Qué actividad física que hacés con amigos te genera más bienestar?", 1),
        ("¿Cómo el estado de salud de alguien que querés te afecta físicamente a vos?", 1),
        ("¿Tenés amigos con quienes puedas hablar del cuerpo sin vergüenza?", 1),
        ("¿Cómo cambia tu cuerpo — tu energía, tu tensión, tu hambre — según con quién estás?", 1),
        ("¿Qué amigo tuyo tiene la relación más sana con su cuerpo y qué aprendés de eso?", 1),
        ("¿Qué cosa hacés físicamente con tus amigos que te parece que le da cuerpo a la amistad?", 1),
        ("¿Cómo una comida compartida puede ser la base de una amistad?", 1),
        ("¿Qué hábito físico tuyo cambió porque un amigo lo hacía diferente?", 1),
        ("¿Hay algún amigo cuyo deterioro de salud te genera miedo por vos mismo?", 1),
        ("¿Qué dice de una amistad que puedan acompañarse en los momentos de vulnerabilidad física?", 1),
        ("¿Qué amigo tuyo cambió su relación con el cuerpo de una manera que te inspiró?", 1),
        ("¿Cómo la presencia física de ciertos amigos te hace sentir más vivo?", 1),
        ("¿Qué cosa de la relación con tu cuerpo solo podés hablar con ciertos amigos?", 1),
        ("¿Qué amigo tuyo tiene hábitos físicos que te generan envidia sana y por qué?", 1),
        ("¿Cuánto de tu relación con la salud y el cuerpo está influenciada por tu círculo social?", 1),
        ("¿Cómo la vulnerabilidad física — mostrarse enfermo o cansado — cambia las amistades?", 2),
        ("¿Qué dice de una amistad que el cuerpo del otro se convierta en algo familiar, reconocible?", 2),
        ("¿De qué manera los hábitos físicos de tu círculo definen el techo de tu propio cuidado?", 2),
        ("¿Cómo una enfermedad de un amigo cambió tu propia relación con tu salud?", 2),
        ("¿Qué conversaciones sobre el cuerpo o el envejecimiento tenés con amigos que antes eran impensables?", 2),
        ("¿Cómo el envejecimiento físico compartido con amigos cambia la naturaleza de esas amistades?", 2),
        ("¿Qué parte de vos que no podés mostrar físicamente en otros espacios aparece entre amigos de confianza?", 3),
        ("¿Cómo la presencia corporal — estar juntos sin pantallas, sin distracciones — define lo que es una amistad real?", 3),
        ("¿Qué dice de una amistad que dos personas puedan acompañarse en el deterioro físico sin incómodos?", 3),
        ("¿Cómo el miedo al deterioro físico propio cambia cuando lo compartís con amigos?", 3),
        ("¿Cuánto de lo que tu cuerpo siente cuando está con ciertas personas es información sobre esa relación?", 3),
        ("¿Qué amigo sabe de tu cuerpo — tus miedos, tus hábitos, tu historia física — que muy pocos saben?", 3),
        ("¿Cómo la presencia del cuerpo del otro puede ser la forma más directa de presencia en una amistad?", 3),
        ("¿Qué cosa que tu cuerpo expresa en compañía de ciertos amigos no podés expresar en ningún otro contexto?", 3),
        ("¿Cómo el tacto — un abrazo, una palmada, una presencia — puede ser el corazón de ciertas amistades?", 3),
    ],

    "exs": [
        ("¿Cómo recordás físicamente a alguien con quien estuviste — su olor, su tacto, su energía?", 1),
        ("¿Qué hábito físico o alimenticio adoptaste de alguien del pasado y todavía tenés?", 1),
        ("¿Cómo tu cuerpo respondía cuando estabas con alguien que amabas?", 1),
        ("¿Alguna vez una relación terminada dejó una marca física — tensión, insomnio, cambios en el cuerpo?", 1),
        ("¿Qué actividad física empezaste o dejaste por alguien del pasado?", 1),
        ("¿Cómo manejabas el sueño durante o después de una relación importante?", 1),
        ("¿Hay alguna comida que te recuerda a alguien con quien estuviste?", 1),
        ("¿Qué cosa de tu cuerpo cambió durante una relación de manera que notaste?", 1),
        ("¿Cómo la distancia física de alguien que amabas se sentía en el cuerpo?", 1),
        ("¿Qué lugar en tu cuerpo guardó el dolor de una ruptura?", 1),
        ("¿Cómo cambiaba tu energía física cuando estabas con alguien que amabas?", 1),
        ("¿Qué hábito de sueño o alimentación cambió notablemente después de una ruptura?", 1),
        ("¿Algún ex tuvo un impacto en tu relación con tu propio cuerpo — para bien o para mal?", 1),
        ("¿Qué cosa físicamente placentera asociás con alguien del pasado?", 1),
        ("¿Cómo la memoria del cuerpo de alguien que amaste cambia con el tiempo?", 1),
        ("¿Cómo el cuerpo procesa el fin de una relación de manera diferente a la cabeza?", 2),
        ("¿Qué dice de vos cómo tu cuerpo respondió a alguien que ya no está en tu vida?", 2),
        ("¿Cómo la intimidad física de una relación moldea tu cuerpo y tus expectativas futuras?", 2),
        ("¿Qué cosa de la presencia física de alguien que perdiste extrañás más que cualquier otra cosa?", 2),
        ("¿Cómo el cuidado o el descuido del cuerpo en una relación dice algo sobre cómo funcionaba ese vínculo?", 2),
        ("¿Qué hábito físico propio cambió para bien después de que terminó una relación?", 2),
        ("¿Cómo el cuerpo guarda relaciones pasadas de maneras que la memoria consciente no puede controlar?", 3),
        ("¿Qué parte de tu cuerpo todavía tiene la huella de alguien que amaste aunque haya pasado mucho tiempo?", 3),
        ("¿Qué dice de vos la manera en que tu cuerpo reaccionó al final de las relaciones más importantes?", 3),
        ("¿Cómo la intimidad física con alguien cambia la relación que tenés con tu propio cuerpo para siempre?", 3),
        ("¿Qué cosa te enseñó el cuerpo sobre una relación que la cabeza tardó mucho más en entender?", 3),
        ("¿Qué parte de vos se cerró físicamente después de algo que dolió y cuándo se volvió a abrir?", 3),
        ("¿Qué queda en el cuerpo de alguien que alguna vez te amó o que vos amaste?", 3),
        ("¿Cómo la memoria corporal de alguien del pasado te afecta de maneras que no podés controlar del todo?", 3),
        ("¿Qué cosa del cuerpo de alguien que ya no está extrañás de una manera que no podés explicar del todo?", 3),
        ("¿Qué comida compartida con alguien del pasado todavía te toca cuando la comés solo?", 1),
        ("¿Cómo tu cuerpo notó que algo terminaba antes de que tu cabeza lo aceptara?", 1),
        ("¿Qué actividad física que hacías en pareja ahora es un espacio completamente tuyo?", 1),
        ("¿Cómo el tacto de alguien que ya no está puede quedar en el cuerpo como algo casi físico?", 1),
        ("¿Qué cambio físico tuyo — peso, energía, salud — se puede trazar hasta una relación específica?", 2),
        ("¿Cómo el cuerpo puede resistirse a olvidar a alguien aunque la cabeza quiera?", 2),
        ("¿Qué le hubiera hecho diferente a tu cuerpo si la relación más importante de tu vida hubiera terminado antes?", 2),
        ("¿Cuánto de lo que le pedís al cuerpo de alguien nuevo es en realidad una conversación con el de alguien del pasado?", 3),
        ("¿Qué enseñanza sobre el cuerpo propio te dejó alguien que ya no está que no sabés cómo agradecer?", 3),
        ("¿Cómo la presencia o la ausencia física de alguien que amaste cambió la manera en que habitás tu propio cuerpo?", 3),
    ],

    "personalidad": [
        ("¿Cómo describís tu relación con tu cuerpo en pocas palabras?", 1),
        ("¿Sos más de escuchar lo que tu cuerpo te dice o de ignorarlo hasta que no podés más?", 1),
        ("¿Cuál es tu relación con el ejercicio o el movimiento físico?", 1),
        ("¿Cómo dormís y qué dice eso de vos?", 1),
        ("¿Qué relación tenés con la comida: placer, obligación, relación complicada?", 1),
        ("¿Cómo manejás la energía física: la guardás, la gastás, la ignorás?", 1),
        ("¿Qué parte de tu cuerpo sentís como la más tuya, la más característica?", 1),
        ("¿Cómo el cansancio físico afecta quién sos y cómo te relacionás?", 1),
        ("¿Qué señales físicas tenés cuando estás bien emocionalmente?", 1),
        ("¿Qué señales físicas tenés cuando algo no está bien aunque no lo hayas procesado?", 1),
        ("¿Cómo describís tu relación con el dolor físico: lo tolerás, lo evitás, lo ignorás?", 1),
        ("¿Qué dice de vos la manera en que cuidás o descuidás tu cuerpo?", 1),
        ("¿Cómo la alimentación afecta tu estado de ánimo y tu energía?", 1),
        ("¿Qué cosa hace tu cuerpo cuando estás estresado que te dice que algo no está bien?", 1),
        ("¿Sos de los que se enferman cuando bajan las defensas o aguantás hasta que ya no podés?", 1),
        ("¿Qué relación tenés con el placer físico — la comida, el descanso, el movimiento?", 1),
        ("¿Cómo el sueño define tu día y tu humor de maneras que todo lo demás no puede cambiar?", 1),
        ("¿Qué hábito físico tuyo te genera más conflicto interno?", 1),
        ("¿Cómo la relación con tu cuerpo cambió con la edad?", 1),
        ("¿Qué parte de tu cuerpo escuchás más y cuál ignorás sistemáticamente?", 1),
        ("¿Cómo el movimiento — caminar, correr, bailar, nadar — cambia tu estado mental?", 1),
        ("¿Qué dice de vos la manera en que respondés físicamente a diferentes entornos o personas?", 1),
        ("¿Qué relación tenés con el envejecimiento de tu propio cuerpo?", 1),
        ("¿Cómo el hambre — de comida, de descanso, de movimiento — afecta quién sos?", 1),
        ("¿Qué hábito físico querés cambiar y qué te lo impide?", 1),
        ("¿Qué dice de tu personalidad la manera en que tu cuerpo responde al estrés?", 2),
        ("¿Cómo la relación con tu cuerpo refleja la relación que tenés con vos mismo más profundamente?", 2),
        ("¿Qué parte de vos que no podés expresar de otra manera se expresa en el cuerpo?", 2),
        ("¿Cómo la manera en que tratás tu cuerpo dice algo sobre lo que creés que merecés?", 2),
        ("¿Qué te dice el cuerpo sobre vos que preferís no escuchar?", 2),
        ("¿Cómo la relación con el cuerpo cambia cuando estás en paz con vos mismo?", 2),
        ("¿Qué parte de tu historia emocional guardás en el cuerpo sin habérsela contado a nadie?", 3),
        ("¿Cómo el cuerpo puede ser más honesto que la mente sobre lo que realmente sentís?", 3),
        ("¿Qué dice de vos profundamente la manera en que te relacionás con el placer físico?", 3),
        ("¿Qué conversación pendiente con vos mismo se manifiesta como tensión o malestar físico?", 3),
        ("¿Cómo la relación con tu cuerpo revela lo que creés (aunque no lo pienses) sobre tu propio valor?", 3),
        ("¿Qué cosa de tu cuerpo que no aceptás dice algo que todavía no terminaste de procesar?", 3),
        ("¿Qué parte de quién sos solo existe en el cuerpo y no puede ponerse en palabras?", 3),
        ("¿Cómo el cuerpo puede ser el lugar donde vive lo que no dijiste y lo que no te permitiste sentir?", 3),
        ("¿Qué hubiera cambiado en vos si hubieras aprendido a habitar tu cuerpo antes?", 3),
    ],

    "miedos": [
        ("¿Qué enfermedad o condición física te genera más miedo?", 1),
        ("¿Le tenés miedo al dolor físico?", 1),
        ("¿Qué te genera más angustia: enfermarte vos o que se enferme alguien que querés?", 1),
        ("¿Le tenés miedo al deterioro físico propio con la edad?", 1),
        ("¿Qué cosa de tu cuerpo actual te genera preocupación o miedo?", 1),
        ("¿Cómo manejás el miedo a las enfermedades o al diagnóstico médico?", 1),
        ("¿Le tenés miedo a perder movilidad o independencia física?", 1),
        ("¿Qué síntoma físico tenés que preferís no investigar demasiado?", 1),
        ("¿Cómo el miedo a enfermarte afecta tus hábitos o tus decisiones?", 1),
        ("¿Le tenés miedo a depender físicamente de alguien?", 1),
        ("¿Qué miedo relacionado con el cuerpo heredaste de tu familia?", 1),
        ("¿Cómo manejás el miedo a la muerte desde el cuerpo — no como concepto sino como realidad física?", 1),
        ("¿Qué te genera más miedo: un deterioro lento o un final rápido?", 1),
        ("¿Le tenés miedo al cuerpo que vas a tener en 20 años?", 1),
        ("¿Cómo el miedo físico — la respuesta del cuerpo al peligro — se mezcla con tus miedos emocionales?", 1),
        ("¿De qué manera el miedo al deterioro físico cambia cómo vivís hoy?", 2),
        ("¿Qué miedo corporal no podés racionalizar aunque intentés hacerlo?", 2),
        ("¿Cómo el miedo a perder el cuerpo que tenés cambia la manera en que lo valorás?", 2),
        ("¿Qué dice de vos la relación entre tu miedo a enfermarte y cómo cuidás o no tu cuerpo?", 2),
        ("¿Cómo el miedo al dolor físico define o limita decisiones importantes de tu vida?", 2),
        ("¿Qué parte del miedo a la muerte es en realidad miedo al sufrimiento físico previo?", 2),
        ("¿Qué miedo físico tenés que si lo nombraras cambiaría algo en cómo lo manejás?", 3),
        ("¿Cómo el cuerpo puede generar más miedo que cualquier cosa mental cuando algo no funciona bien?", 3),
        ("¿Qué parte del miedo a envejecer es miedo a dejar de ser reconocible para vos mismo?", 3),
        ("¿Cómo el miedo a perder el control físico revela miedos más profundos sobre la identidad?", 3),
        ("¿Qué cosa de tu cuerpo te aterra y sin embargo ignorás hasta que te força a prestarle atención?", 3),
        ("¿Cómo el miedo a la vulnerabilidad física cambia la manera en que te permitís necesitar a otros?", 3),
        ("¿Qué hubiera cambiado en tu vida si no tuvieras miedo a la fragilidad del cuerpo?", 3),
        ("¿Cómo el miedo al propio cuerpo puede ser una forma de miedo a vivir completamente?", 3),
        ("¿Qué miedo físico profundo llevas que casi nunca se te permite nombrar?", 3),
        ("¿Le tenés miedo a que tu cuerpo te traicione en el peor momento posible?", 1),
        ("¿Qué miedo físico de tu infancia todavía aparece de adulto de maneras que no esperabas?", 1),
        ("¿Cómo el miedo al cuerpo ajeno — a la enfermedad de alguien que querés — afecta tu propia salud?", 1),
        ("¿Cuánto del miedo a enfermarte es miedo a ser una carga para alguien?", 1),
        ("¿Cómo el miedo al envejecimiento físico se conecta con el miedo a ser menos valioso?", 2),
        ("¿Qué miedo físico tenés que cambia cómo tomás decisiones aunque no lo reconozcas así?", 2),
        ("¿Cómo el miedo a perder el control del cuerpo cambia la manera en que te relacionás con otros?", 2),
        ("¿Qué hubiera sido diferente en vos si el miedo a enfermarte o al dolor físico hubiera sido menos?", 3),
        ("¿Cómo el miedo al cuerpo propio puede ser la forma más silenciosa de no vivir del todo?", 3),
        ("¿Qué parte de tu vida postergás por miedo a que el cuerpo no aguante o no esté a la altura?", 3),
    ],

    "logros": [
        ("¿Cuál es el logro físico del que más orgulloso te sentís?", 1),
        ("¿Alguna vez tu cuerpo te sorprendió haciendo algo que no creías que podía?", 1),
        ("¿Qué hábito de salud lograste cambiar que antes creías imposible?", 1),
        ("¿Cuál fue la prueba física más exigente que superaste?", 1),
        ("¿Qué relación querés tener con tu cuerpo y qué hiciste para llegar ahí?", 1),
        ("¿Qué cosa aprendiste sobre tu cuerpo que cambió cómo te cuidás?", 1),
        ("¿Alguna vez tu cuerpo te dio la respuesta que tu cabeza no podía?", 1),
        ("¿Qué hábito físico — de alimentación, sueño o movimiento — lograste sostener que antes no podías?", 1),
        ("¿Cuándo fue la primera vez que te sentiste orgulloso de lo que tu cuerpo podía hacer?", 1),
        ("¿Qué cosa física que parecía inalcanzable alcanzaste y qué te enseñó el proceso?", 1),
        ("¿Cómo superar un problema de salud o una limitación física cambió algo importante en vos?", 1),
        ("¿Qué logro físico tuyo no reconocés lo suficiente?", 1),
        ("¿Alguna vez el cuidado del cuerpo fue en sí mismo un logro difícil y por qué?", 1),
        ("¿Qué relación tiene para vos el logro físico con el logro en otras áreas de tu vida?", 1),
        ("¿Cómo superar algo físicamente difícil cambió tu confianza en otras áreas?", 1),
        ("¿Qué relación tiene el cuerpo con la capacidad de lograr cosas en todas las áreas de tu vida?", 1),
        ("¿Qué cosa hiciste físicamente para otro que fue un logro del que nadie sabía?", 1),
        ("¿Cómo recuperarte de una lesión o enfermedad fue en realidad uno de tus logros más grandes?", 1),
        ("¿Qué habilidad física desarrollaste de adulto que antes creías que era solo para otros?", 1),
        ("¿Cuándo fue la última vez que tu cuerpo te demostró que podía más de lo que pensabas?", 1),
        ("¿Qué dice de vos haber podido cambiar un hábito físico dañino aunque costara?", 1),
        ("¿Cómo la disciplina física te ayudó a desarrollar disciplina en otras áreas?", 1),
        ("¿Qué logro de salud tuyo cambió algo que iba a deteriorarse si no lo hubieras hecho?", 1),
        ("¿Qué cosa de cómo cuidás tu cuerpo hoy es en sí misma un logro comparado con cómo eras antes?", 1),
        ("¿Qué logro físico tenés que para otros sería ordinario pero para vos fue enorme?", 1),
        ("¿Qué dice del valor de un logro el hecho de que nadie lo vea pero el cuerpo sí lo sienta?", 2),
        ("¿Cómo superar algo físicamente difícil cambió tu relación con los límites propios?", 2),
        ("¿Qué logro físico tuyo requirió rendirse para poder lograrlo?", 2),
        ("¿Cómo la relación con tu cuerpo puede ser el logro más silencioso y más importante de tu vida?", 2),
        ("¿Qué dice de vos haber podido escuchar a tu cuerpo en momentos en que era más fácil ignorarlo?", 2),
        ("¿Cómo el cuerpo puede ser el mejor maestro sobre los límites reales y la resiliencia real?", 2),
        ("¿Qué le dirías a alguien que está en el proceso de reconectar con su cuerpo desde tu propia experiencia?", 3),
        ("¿Cómo el cuerpo puede ser el lugar donde los logros más genuinos se registran sin ruido?", 3),
        ("¿Qué cosa de tu cuerpo que antes odiabas o ignorabas aprendiste a respetar y cómo?", 3),
        ("¿Cómo el logro más importante de tu vida física no fue un maratón ni un récord sino algo más pequeño y profundo?", 3),
        ("¿Qué le debés a tu cuerpo que todavía no le diste?", 3),
        ("¿Cómo el logro de estar en paz con tu cuerpo puede ser más difícil y más valioso que cualquier logro externo?", 3),
        ("¿Qué cambiaría en tu vida si finalmente lograras hacer las paces con la relación que tenés con tu cuerpo?", 3),
        ("¿Cómo el hecho de seguir vivo y con salud puede ser el logro más subestimado de todo?", 3),
        ("¿Qué cosa de tu cuerpo que diste por hecho extrañás o extrañarás cuando ya no esté?", 3),
    ],

    "sinFiltro": [
        ("¿Cuál es tu relación honesta con el cuerpo que tenés: lo aceptás, lo tolerás, lo rechazás?", 1),
        ("¿Qué cosa de tu cuerpo te genera vergüenza o incomodidad que casi nunca decís en voz alta?", 1),
        ("¿Cuánto tiempo real descansás versus cuánto creés que deberías?", 1),
        ("¿Qué hábito físico tuyo sabés que es dañino y seguís igual?", 1),
        ("¿Qué cosa de tu cuerpo censurás o escondés que en secreto querés poder mostrar?", 1),
        ("¿Cuándo fue la última vez que comiste algo de más o de menos por razones que no tenían nada que ver con el hambre?", 1),
        ("¿Qué relación tenés con el placer físico que en público presentás diferente de lo que es en privado?", 1),
        ("¿Qué cosa de tu cuerpo nunca le mostrás a nadie y qué sentís al respecto?", 1),
        ("¿Cómo manejás la imagen de tu cuerpo en público versus cómo te sentís con él en privado?", 1),
        ("¿Qué parte de tu cuerpo querés que los demás no vean y cuánto espacio mental ocupa eso?", 1),
        ("¿Cuánto tiempo real dormís versus cuánto deberías y qué te lo impide?", 1),
        ("¿Qué relación honesta tenés con el alcohol, el azúcar, el cigarrillo, u otro hábito físico que minimizás?", 1),
        ("¿Qué cosa de tu cuerpo te molesta y nunca terminás de aceptar aunque digas que sí?", 1),
        ("¿Cómo es tu relación con el sexo y el cuerpo en términos de lo que necesitás versus lo que decís que necesitás?", 1),
        ("¿Qué señal física de tu cuerpo ignorás conscientemente porque no querés saber lo que significa?", 1),
        ("¿Qué dice de vos honestamente la diferencia entre cómo tratás tu cuerpo y cómo creés que deberías tratarlo?", 2),
        ("¿Qué relación tiene tu trato hacia tu cuerpo con cuánto creés que merecés bienestar?", 2),
        ("¿Qué cosa de tu cuerpo convertiste en algo normal que en realidad es una forma de descuidarte?", 2),
        ("¿Cómo el agotamiento físico que acumulás dice algo sobre los límites que no te ponés en otros lados?", 2),
        ("¿Qué le negás a tu cuerpo que si se lo dieras cambiaría algo importante en cómo te sentís?", 2),
        ("¿Qué conversación con tu cuerpo postergás porque implica cambios que no estás listo para hacer?", 2),
        ("¿Qué parte del descuido de tu cuerpo es en realidad una forma de castigarte por algo?", 3),
        ("¿Qué te hace más daño físicamente y qué te impide cambiar eso aunque ya lo sepas?", 3),
        ("¿Qué parte de tu relación con el cuerpo es la más difícil de reconocer en voz alta?", 3),
        ("¿Qué cosas hacés o no hacés con tu cuerpo que si alguien que querés las supiera te daría vergüenza?", 3),
        ("¿Qué dice de vos más profundamente la manera en que tratás tu cuerpo cuando nadie mira?", 3),
        ("¿Qué te da más miedo de estar completamente honesto sobre tu relación con tu salud y tu cuerpo?", 3),
        ("¿Qué parte de vos solo existe físicamente — en el cuerpo — y nunca puede ponerse en palabras limpias?", 3),
        ("¿Cuánto de cómo tratás tu cuerpo es en realidad la manera en que tratás lo que más te duele emocionalmente?", 3),
        ("¿Qué le dirías a tu cuerpo si pudieras hablarle honestamente, sin excusas?", 3),
        ("¿Qué relación tenés con tu peso o tu imagen corporal que casi nunca contás sin filtro?", 1),
        ("¿Cuánto de lo que comés o dejás de comer tiene que ver con el control y no con el hambre real?", 1),
        ("¿Qué cosa le exigís a tu cuerpo que nunca le agradecés aunque lo da igual?", 1),
        ("¿Cuándo fue la última vez que te trataste físicamente tan mal que si lo hicieras con alguien más te daría vergüenza?", 1),
        ("¿Qué dice de vos honestamente cuánto tiempo dedicás a cuidar tu cuerpo versus cuánto creés que merece?", 2),
        ("¿Qué hábito físico dañino tenés que en privado sabés que es un problema pero en público presentás como una elección?", 2),
        ("¿Cómo el descuido del cuerpo puede ser la manera más visible de que algo más profundo no está bien?", 2),
        ("¿Qué parte de vos que no podés mostrar de otra manera se expresa a través de cómo tratás tu cuerpo?", 3),
        ("¿Cuánto del maltrato que le das a tu cuerpo viene de mensajes que recibiste sobre lo que merecés?", 3),
        ("¿Qué cosa de tu relación con tu cuerpo, si la contaras sin ningún filtro, cambiaría cómo te ven quienes más te importan?", 3),
    ],
}


def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]


def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS35:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS35[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")


if __name__ == "__main__":
    main()
