#!/usr/bin/env python3
"""Batch 12 - sports, competition, body, health, food, nature, outdoors."""
import json

ADDITIONS12 = {
    "infancia": [
        ("¿Cuál fue el primer deporte que practicaste y cuánto tiempo le dedicaste?", 1),
        ("¿Cuándo fue la primera vez que ganaste algo en una competencia y cómo lo festejaste?", 1),
        ("¿Cuándo fue la primera vez que perdiste en algo y no lo pudiste aceptar?", 1),
        ("¿Cuándo fue la primera vez que te lastimaste haciendo deporte o jugando afuera?", 1),
        ("¿Cuándo fue la primera vez que fuiste a la cancha o a ver un partido en vivo?", 1),
        ("¿Cuándo fue la primera vez que corriste tanto que no podías respirar y te encantó igual?", 1),
        ("¿Cuándo fue la primera vez que un equipo te eligió primero en un partido de la escuela?", 1),
        ("¿Cuándo fue la primera vez que probaste una comida que no conocías y te encantó?", 1),
        ("¿Cuándo fue la primera vez que pasaste una noche durmiendo afuera —carpa, camping, en casa de alguien?", 1),
        ("¿Cuándo fue la primera vez que viste un amanecer o atardecer y te dejó sin palabras?", 1),
        ("¿Cuándo fue la primera vez que subiste a un árbol o a algún lugar alto donde no debías?", 1),
        ("¿Cuándo fue la primera vez que te metiste en el agua —mar, río, pileta— y no querías salir?", 1),
        ("¿Cuándo fue la primera vez que pescaste algo, aunque fuera pequeño?", 1),
        ("¿Cuándo fue la primera vez que comiste algo que hiciste vos mismo y estaba bueno?", 1),
        ("¿Cuándo fue la primera vez que te perdiste en un lugar al aire libre y cómo lo resolviste?", 1),
        ("¿Cuándo fue la primera vez que te atreviste a ir a un lugar que te parecía peligroso y salió bien?", 1),
        ("¿Cuándo fue la primera vez que coleccionaste algo de la naturaleza —piedras, hojas, bichos?", 1),
        ("¿Cuándo fue la primera vez que viste un animal salvaje de cerca y qué fue?", 1),
        ("¿Cuándo fue la primera vez que hiciste una carrera con alguien y ganaste?", 1),
        ("¿Cuándo fue la primera vez que vos y tus amigos inventaron las reglas de un juego?", 1),
        ("¿Cuándo fue la primera vez que el deporte te enseñó algo sobre trabajo en equipo?", 1),
        ("¿Cuándo fue la primera vez que un rival tuyo en algo deportivo terminó siendo tu amigo?", 1),
        ("¿Cuándo fue la primera vez que la naturaleza te hizo sentir chico en el buen sentido?", 1),
        ("¿Cuándo fue la primera vez que una comida de la infancia todavía te transporta cuando la olés?", 1),
        ("¿Cuándo fue la primera vez que tu cuerpo te demostró que podía hacer algo que vos no creías?", 2),
        ("¿Cuándo fue la primera vez que perder en algo te enseñó más que ganar?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que la competencia sana podía darte lo mejor de vos?", 2),
        ("¿Cuándo fue la primera vez que la naturaleza te cambió algo en la cabeza?", 2),
        ("¿Cuándo fue la primera vez que un momento al aire libre te hizo sentir completamente presente?", 2),
        ("¿Cuándo fue la primera vez que una comida de alguien te hizo sentir que te estaban cuidando?", 2),
        ("¿Cuándo fue la primera vez que una enfermedad de chico te hizo valorar la salud?", 2),
        ("¿Cuándo fue la primera vez que sentiste que tu cuerpo era tuyo para cuidar?", 2),
        ("¿Cuándo fue la primera vez que el esfuerzo físico fue una forma de procesar algo emocionalmente difícil?", 2),
        ("¿Cuándo fue la primera vez que la competencia te mostró algo de tu carácter que no sabías?", 2),
        ("¿Cuándo fue la primera vez que perdiste algo importante —un partido, una competencia— y esa pérdida te formó?", 3),
        ("¿Cuándo fue la primera vez que la naturaleza te enseñó algo que ninguna persona ni libro podría haberte enseñado?", 3),
        ("¿Cuándo fue la primera vez que tu cuerpo te mostró sus límites y eso te cambió algo?", 3),
        ("¿Hay algún momento de deporte o actividad física de tu infancia que sientas que formó una parte esencial de quién sos?", 3),
        ("¿Cuándo fue la primera vez que la comida fue algo más que sustento —un acto de amor, de identidad, de pertenencia?", 3),
        ("¿Cuándo fue la primera vez que estar en la naturaleza te hizo sentir que pertenecías a algo más grande?", 3),
    ],

    "futuro": [
        ("¿Cuándo fue la última vez que te imaginaste con más tiempo para hacer deporte o actividad física?", 1),
        ("¿Cuándo fue la última vez que te propusiste algo relacionado con tu salud y lo cumpliste?", 1),
        ("¿Cuándo fue la última vez que pensaste en un lugar natural al que querés ir antes de que pase mucho tiempo?", 1),
        ("¿Cuándo fue la última vez que te imaginaste comiendo mejor en el futuro?", 1),
        ("¿Cuándo fue la última vez que pensaste en un deporte o actividad física que querés empezar?", 1),
        ("¿Cuándo fue la última vez que te imaginaste con más energía física de la que tenés ahora?", 1),
        ("¿Cuándo fue la última vez que pensaste en hacer un viaje donde la naturaleza fuera la protagonista?", 1),
        ("¿Cuándo fue la última vez que te imaginaste viviendo en un lugar con más contacto con la naturaleza?", 1),
        ("¿Cuándo fue la última vez que pensaste en cómo querés estar físicamente en 10 años?", 1),
        ("¿Cuándo fue la última vez que te imaginaste cocinando mejor o con más placer?", 1),
        ("¿Cuándo fue la última vez que pensaste en un desafío físico que querés superar?", 1),
        ("¿Cuándo fue la última vez que te imaginaste descansando mejor de lo que descansás ahora?", 1),
        ("¿Cuándo fue la última vez que pensaste en cómo la alimentación podría cambiar algo en tu vida?", 1),
        ("¿Cuándo fue la última vez que te imaginaste haciendo algo al aire libre que nunca hiciste?", 1),
        ("¿Cuándo fue la última vez que te propusiste reconectar con algún deporte que amabas y dejaste?", 1),
        ("¿Cuándo fue la última vez que pensaste en cómo querés envejecer físicamente?", 1),
        ("¿Cuándo fue la última vez que te imaginaste con hábitos más saludables sin que eso sonara a sacrificio?", 1),
        ("¿Cuándo fue la última vez que pensaste en el ambiente natural que querés que rodee tu vida futura?", 1),
        ("¿Cuándo fue la última vez que te imaginaste compitiendo en algo —aunque fuera informal— en el futuro?", 1),
        ("¿Cuándo fue la última vez que pensaste en cómo el movimiento podría ser una parte central de tu vida adulta?", 1),
        ("¿Cuándo fue la última vez que te imaginaste más conectado con lo que comés y de dónde viene?", 1),
        ("¿Cuándo fue la última vez que pensaste en el legado físico que querés dejar —hábitos, salud, vitalidad?", 1),
        ("¿Cuándo fue la última vez que te imaginaste en un lugar natural específico y sintiste que pertenecías ahí?", 1),
        ("¿Cuándo fue la última vez que pensaste en una competencia —personal o con otros— que querés ganar en el futuro?", 1),
        ("¿Cuándo fue la última vez que la salud o el cuerpo te hicieron replantearte qué tipo de futuro querés construir?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que los hábitos de hoy van a determinar quién sos físicamente en el futuro?", 2),
        ("¿Cuándo fue la última vez que la naturaleza te mostró que el futuro vale la pena?", 2),
        ("¿Cuándo fue la última vez que el deporte te hizo ver algo de tu futuro que fuera del deporte no podías ver?", 2),
        ("¿Cuándo fue la última vez que te planteaste seriamente qué tipo de relación con tu cuerpo querés tener de acá en más?", 2),
        ("¿Cuándo fue la última vez que pensaste en cómo la alimentación puede ser un acto político en el futuro?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que hacés con tu cuerpo hoy es un acto de amor hacia vos del futuro?", 2),
        ("¿Cuándo fue la última vez que el contacto con la naturaleza te mostró una escala de tiempo que te acomodó las prioridades?", 2),
        ("¿Cuándo fue la última vez que te preguntaste qué ambiente físico necesitás para florecer?", 2),
        ("¿Cuándo fue la última vez que la competencia —con vos mismo o con otros— te mostró que podés más de lo que pensabas?", 2),
        ("¿Cuándo fue la última vez que tu cuerpo te dijo algo sobre el futuro que tu mente no quería escuchar?", 3),
        ("¿Cuándo fue la última vez que la naturaleza te hizo sentir que el futuro del planeta era también tu responsabilidad?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que la salud es una de las formas más concretas de apostar por un futuro?", 3),
        ("¿Cuándo fue la última vez que pensaste en envejecer y en lugar de angustiarte, lo viste como una posibilidad?", 3),
        ("¿Cuándo fue la última vez que el cuerpo fue el primer lugar donde notaste que algo en tu vida necesitaba cambiar?", 3),
        ("¿Cuándo fue la última vez que sentiste que cuidar tu cuerpo era un acto de respeto hacia todo lo que querés construir?", 3),
    ],

    "amor": [
        ("¿Cuándo fue la última vez que hiciste algo físico —deporte, caminata, actividad— con alguien y los acercó más?", 1),
        ("¿Cuándo fue la última vez que cocinaste para alguien como acto de amor?", 1),
        ("¿Cuándo fue la última vez que alguien te preparó algo de comer y lo sentiste como un gesto enorme?", 1),
        ("¿Cuándo fue la última vez que compartiste un momento al aire libre con alguien y fue más íntimo que cualquier conversación?", 1),
        ("¿Cuándo fue la última vez que te gustó alguien que tenía una relación muy diferente a la tuya con el cuerpo o la salud?", 1),
        ("¿Cuándo fue la última vez que comiste algo increíble con alguien y el momento valió tanto como la comida?", 1),
        ("¿Cuándo fue la última vez que estar en la naturaleza con alguien te hizo sentir más conectado a esa persona?", 1),
        ("¿Cuándo fue la última vez que competir con alguien que te gustaba fue más divertido que ganar?", 1),
        ("¿Cuándo fue la última vez que compartiste una comida sin teléfono y fue de los momentos más presentes del año?", 1),
        ("¿Cuándo fue la última vez que el cuerpo de alguien te pareció algo más allá de lo físico?", 1),
        ("¿Cuándo fue la última vez que un paseo o caminata con alguien fue el espacio donde dijo algo que no hubiera dicho en otro lugar?", 1),
        ("¿Cuándo fue la última vez que te sentiste bien en tu cuerpo y eso impactó positivamente en cómo te relacionaste con alguien?", 1),
        ("¿Cuándo fue la última vez que compartir una comida fue el comienzo de algo con alguien?", 1),
        ("¿Cuándo fue la última vez que le cuidaste el cuerpo a alguien —masaje, descanso, comida— como forma de amor?", 1),
        ("¿Cuándo fue la última vez que alguien te cuidó físicamente y lo recibiste sin incomodidad?", 1),
        ("¿Cuándo fue la última vez que un esfuerzo físico compartido —mudanza, deporte, viaje— te unió mucho más a alguien?", 1),
        ("¿Cuándo fue la última vez que te gustó alguien que tenía hábitos físicos muy distintos a los tuyos?", 1),
        ("¿Cuándo fue la última vez que una comida juntos fue más reveladora de quién era alguien que meses de conversación?", 1),
        ("¿Cuándo fue la última vez que la naturaleza fue el escenario de uno de tus momentos más importantes con alguien?", 1),
        ("¿Cuándo fue la última vez que le cocinaste algo a alguien y sentiste que en ese plato había algo de vos?", 1),
        ("¿Cuándo fue la última vez que el contacto físico no sexual con alguien —un abrazo, una mano— fue de las cosas más importantes de la semana?", 1),
        ("¿Cuándo fue la última vez que cuidaste la salud de alguien que amás y eso te hizo sentir útil de la mejor manera?", 1),
        ("¿Cuándo fue la última vez que el deporte o la actividad física fueron el espacio donde te abriste con alguien?", 1),
        ("¿Cuándo fue la última vez que comparar gustos de comida con alguien fue una manera de conocerlos más?", 1),
        ("¿Cuándo fue la última vez que la vulnerabilidad física —enfermedad, cansancio, dolor— te acercó más a alguien en lugar de alejarlos?", 2),
        ("¿Cuándo fue la última vez que la forma en que alguien se relaciona con su cuerpo te dijo algo importante sobre cómo se relaciona con el amor?", 2),
        ("¿Cuándo fue la última vez que el acto de comer juntos fue un espacio de honestidad que no hubieran tenido en otro lugar?", 2),
        ("¿Cuándo fue la última vez que la naturaleza fue el escenario donde pudiste mostrar una versión de vos mismo que no mostrás en la ciudad?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que alguien cuida su cuerpo dice mucho sobre cómo se cuida a sí mismo?", 2),
        ("¿Cuándo fue la última vez que preparar comida para alguien fue más íntimo que cualquier otra cosa que pudieras hacer?", 2),
        ("¿Cuándo fue la última vez que el cuerpo fue el idioma en el que mejor pudiste comunicarte con alguien?", 2),
        ("¿Cuándo fue la última vez que una actividad física compartida fue el detonante de algo importante en una relación?", 2),
        ("¿Cuándo fue la última vez que el amor te hizo cambiar algo en cómo te cuidás físicamente?", 2),
        ("¿Cuándo fue la última vez que la forma en que alguien come o se mueve en el mundo te hizo amarlo más?", 2),
        ("¿Cuándo fue la última vez que la fragilidad física de alguien que amás te mostró algo de ese amor que no habías visto?", 3),
        ("¿Cuándo fue la última vez que cuidar el cuerpo de alguien enfermo fue una de las formas más profundas en que expresaste amor?", 3),
        ("¿Cuándo fue la última vez que la naturaleza fue testigo de algo entre vos y alguien que nunca le contarías a nadie más?", 3),
        ("¿Cuándo fue la última vez que sentiste que amar a alguien también significaba amar su relación con su propio cuerpo?", 3),
        ("¿Cuándo fue la última vez que una comida compartida fue el momento más honesto e íntimo que tuviste con alguien?", 3),
        ("¿Cuándo fue la última vez que el cuerpo te mostró que estabas enamorado antes de que tu mente lo aceptara?", 3),
    ],

    "familia": [
        ("¿Cuándo fue la última vez que tu familia hizo algo físico juntos —deporte, caminata, actividad— y fue una de las mejores tardes?", 1),
        ("¿Cuándo fue la última vez que cocinaste algo para tu familia y quedó bien?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te preparó tu comida favorita?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te enseñó una receta?", 1),
        ("¿Cuándo fue la última vez que fuiste con tu familia a un lugar natural y desconectaron de todo?", 1),
        ("¿Cuándo fue la última vez que cuidaste físicamente a alguien de tu familia —una enfermedad, un accidente?", 1),
        ("¿Cuándo fue la última vez que tu familia te cuidó cuando estabas mal físicamente y lo recibiste bien?", 1),
        ("¿Cuándo fue la última vez que viste a un familiar superar algo físico difícil y te inspiró?", 1),
        ("¿Cuándo fue la última vez que la mesa familiar fue el centro de algo importante?", 1),
        ("¿Cuándo fue la última vez que aprendiste sobre la naturaleza de un familiar mayor?", 1),
        ("¿Cuándo fue la última vez que competiste amistosamente con alguien de tu familia en algo y los dos se divirtieron?", 1),
        ("¿Cuándo fue la última vez que la salud de alguien de tu familia te hizo replantear algo en tu propia vida?", 1),
        ("¿Cuándo fue la última vez que tu familia compartió una comida especial —no por la fecha sino por el momento?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te enseñó algo sobre el cuerpo o la salud que todavía usás?", 1),
        ("¿Cuándo fue la última vez que el deporte fue el idioma con el que alguien de tu familia te mostró que te quería?", 1),
        ("¿Cuándo fue la última vez que viste a un familiar envejecer y lo miraste diferente?", 1),
        ("¿Cuándo fue la última vez que la naturaleza fue el escenario de un momento familiar que no olvidás?", 1),
        ("¿Cuándo fue la última vez que un asado, una comida, o un ritual de cocina familiar te hizo sentir en casa?", 1),
        ("¿Cuándo fue la última vez que corriste, jugaste o hiciste algo físico con alguien de tu familia que no esperabas?", 1),
        ("¿Cuándo fue la última vez que cuidar la salud de tu familia fue lo más parecido que tuviste a un acto heroico cotidiano?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te sorprendió con su resistencia o fortaleza física?", 1),
        ("¿Cuándo fue la última vez que un viaje a un lugar natural con tu familia los unió de una manera inesperada?", 1),
        ("¿Cuándo fue la última vez que compartiste una comida con tu familia sin apuro y fue de lo mejor de la semana?", 1),
        ("¿Cuándo fue la última vez que la salud de alguien de tu familia te hizo darte cuenta de lo frágil que es todo?", 1),
        ("¿Cuándo fue la última vez que la salud de alguien de tu familia te hizo replantear cómo cuidas la tuya propia?", 2),
        ("¿Cuándo fue la última vez que el cuerpo de alguien de tu familia te mostró el paso del tiempo de una manera que te movió?", 2),
        ("¿Cuándo fue la última vez que cocinar juntos fue una forma de procesar algo difícil dentro de tu familia?", 2),
        ("¿Cuándo fue la última vez que la naturaleza fue el espacio donde alguien de tu familia y vos pudieron hablar de algo que no hubieran dicho en otro lado?", 2),
        ("¿Cuándo fue la última vez que cuidar físicamente a alguien de tu familia te mostró algo sobre vos mismo que no sabías?", 2),
        ("¿Cuándo fue la última vez que la salud de tus padres te hizo pensar en el tiempo que tenés con ellos?", 2),
        ("¿Cuándo fue la última vez que el deporte o la actividad física compartida fue la forma más honesta de conectar con alguien de tu familia?", 2),
        ("¿Cuándo fue la última vez que notaste que los hábitos de salud de tu familia —buenos o malos— los heredaste sin darte cuenta?", 2),
        ("¿Cuándo fue la última vez que la comida fue el idioma de amor más honesto dentro de tu familia?", 2),
        ("¿Cuándo fue la última vez que el cuerpo de alguien de tu familia te hizo ver cuánto te importaba esa persona?", 2),
        ("¿Cuándo fue la última vez que cuidar a alguien de tu familia físicamente te enseñó algo sobre el amor incondicional?", 3),
        ("¿Cuándo fue la última vez que la enfermedad o fragilidad de alguien de tu familia te mostró algo de esa persona que antes no podías ver?", 3),
        ("¿Cuándo fue la última vez que un ritual de comida o cocina familiar te hizo sentir que pertenecés a algo que trasciende lo individual?", 3),
        ("¿Cuándo fue la última vez que la naturaleza fue el escenario de uno de los momentos más honestos y conectados que tuviste con tu familia?", 3),
        ("¿Cuándo fue la última vez que pensar en la mortalidad de alguien de tu familia te hizo amar más el tiempo que tienen?", 3),
        ("¿Cuándo fue la última vez que el cuerpo fue el espejo donde viste a tu familia —y a vos mismo— con más compasión?", 3),
    ],

    "amistades": [
        ("¿Cuándo fue la última vez que hiciste deporte con amigos y fue más divertido que hacerlo solo?", 1),
        ("¿Cuándo fue la última vez que cocinaste para amigos y fue una de las mejores noches?", 1),
        ("¿Cuándo fue la última vez que alguien de tu grupo te preparó algo de comer y lo sentiste como un gesto de amistad?", 1),
        ("¿Cuándo fue la última vez que fuiste con amigos a un lugar natural y recargaron energía juntos?", 1),
        ("¿Cuándo fue la última vez que un partido o juego amistoso con amigos terminó revelando algo de la personalidad de cada uno?", 1),
        ("¿Cuándo fue la última vez que cuidaste a un amigo enfermo o que estaba mal físicamente?", 1),
        ("¿Cuándo fue la última vez que un amigo te cuidó cuando vos eras el que no estaba bien?", 1),
        ("¿Cuándo fue la última vez que competiste con un amigo de manera sana y los dos disfrutaron el proceso?", 1),
        ("¿Cuándo fue la última vez que una caminata o salida al aire libre con amigos generó conversaciones que no hubieran tenido en otro lado?", 1),
        ("¿Cuándo fue la última vez que compartiste una comida larga con amigos donde el tiempo no existía?", 1),
        ("¿Cuándo fue la última vez que alguien de tu grupo empezó a cuidar su salud y te inspiró?", 1),
        ("¿Cuándo fue la última vez que la naturaleza fue el escenario de una aventura con amigos?", 1),
        ("¿Cuándo fue la última vez que hacer algo físico con amigos —deporte, baile, actividad— fue la forma de estar sin tener que hablar?", 1),
        ("¿Cuándo fue la última vez que viste a un amigo superar algo físico difícil y te sorprendiste?", 1),
        ("¿Cuándo fue la última vez que una comida con amigos fue el contexto de una conversación que cambió algo?", 1),
        ("¿Cuándo fue la última vez que el esfuerzo físico compartido —mudanza, viaje, actividad— fortaleció una amistad?", 1),
        ("¿Cuándo fue la última vez que vos fuiste el que cocinó para los demás y lo disfrutaste?", 1),
        ("¿Cuándo fue la última vez que fuiste al campo, la sierra o la costa con amigos y fue de los momentos del año?", 1),
        ("¿Cuándo fue la última vez que una competencia amistosa con alguien de tu grupo sacó a la luz algo de quiénes eran?", 1),
        ("¿Cuándo fue la última vez que la salud de un amigo te hizo replantearte algo en la tuya?", 1),
        ("¿Cuándo fue la última vez que un picadito, paleta, o deporte de barrio con amigos fue lo mejor de la semana?", 1),
        ("¿Cuándo fue la última vez que un viaje de aventura con amigos fue más revelador que un año de conversaciones?", 1),
        ("¿Cuándo fue la última vez que cocinar juntos con amigos fue la actividad que unió a todos?", 1),
        ("¿Cuándo fue la última vez que el cuerpo —tuyo o de un amigo— fue el tema que hizo la conversación más honesta?", 1),
        ("¿Cuándo fue la última vez que la salud o el cuerpo fueron el puente para una conversación honesta con un amigo?", 2),
        ("¿Cuándo fue la última vez que acompañar a un amigo en algo físico difícil —enfermedad, recuperación— te enseñó algo sobre la amistad?", 2),
        ("¿Cuándo fue la última vez que el esfuerzo compartido en una actividad física fue la base de una amistad más sólida?", 2),
        ("¿Cuándo fue la última vez que la naturaleza fue el espacio donde encontraste a un amigo de una manera que no hubieran podido en la ciudad?", 2),
        ("¿Cuándo fue la última vez que cocinar o comer juntos fue la forma más honesta de cuidarse entre amigos?", 2),
        ("¿Cuándo fue la última vez que la competencia entre amigos reveló algo sobre cómo cada uno maneja ganar y perder?", 2),
        ("¿Cuándo fue la última vez que ver a un amigo cuidar su cuerpo te hizo replantearte cómo cuidás el tuyo?", 2),
        ("¿Cuándo fue la última vez que la salud de alguien cercano te hizo valorar más tu propio cuerpo?", 2),
        ("¿Cuándo fue la última vez que un momento al aire libre con amigos fue más transformador que cualquier conversación que hubieran tenido?", 2),
        ("¿Cuándo fue la última vez que el cuerpo de alguien de tu grupo —su energía, su cansancio, su fortaleza— te reveló algo de esa persona que las palabras no hubieran podido?", 2),
        ("¿Cuándo fue la última vez que cuidar a un amigo físicamente —cuando estaba enfermo, agotado, mal— fue uno de los actos más importantes de esa amistad?", 3),
        ("¿Cuándo fue la última vez que compartir una experiencia física extrema con amigos —aventura, esfuerzo, deporte— los unió de una manera que nada más hubiera podido?", 3),
        ("¿Cuándo fue la última vez que la naturaleza fue el espacio donde una amistad se definió de una manera que en la ciudad no hubiera sido posible?", 3),
        ("¿Cuándo fue la última vez que sentiste que la amistad también era un acto de cuidar el cuerpo y la salud del otro?", 3),
        ("¿Cuándo fue la última vez que la vulnerabilidad física de un amigo te mostró algo de esa persona que profundizó la amistad?", 3),
        ("¿Cuándo fue la última vez que sentiste que compartir una comida con un amigo era también compartir algo de quiénes eran los dos?", 3),
    ],

    "exs": [
        ("¿Cuándo fue la última vez que hiciste algo físico con alguien del pasado y fue parte de lo que funcionaba?", 1),
        ("¿Cuándo fue la última vez que pensaste en alguien del pasado al comer algo que cocinaban para vos?", 1),
        ("¿Cuándo fue la última vez que un lugar natural te recordó a alguien con quien estuviste?", 1),
        ("¿Cuándo fue la última vez que el deporte o la actividad física fue una parte central de lo que tenían con alguien?", 1),
        ("¿Cuándo fue la última vez que comiste algo que cocinaba alguien del pasado y lo extrañaste de una manera que no esperabas?", 1),
        ("¿Cuándo fue la última vez que un lugar al que ibas con alguien lo visitaste solo y fue diferente?", 1),
        ("¿Cuándo fue la última vez que alguien del pasado te influyó en tus hábitos físicos o alimenticios?", 1),
        ("¿Cuándo fue la última vez que pensaste en una aventura al aire libre que viviste con alguien del pasado?", 1),
        ("¿Cuándo fue la última vez que volviste a practicar algo —deporte, actividad— que habías dejado cuando una relación terminó?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que un hábito de salud —bueno o malo— lo adquiriste en una relación?", 1),
        ("¿Cuándo fue la última vez que la comida fue parte de lo que extrañaste de alguien?", 1),
        ("¿Cuándo fue la última vez que un deporte o actividad que practicaban juntos te resultó difícil de retomar?", 1),
        ("¿Cuándo fue la última vez que el cuerpo te habló de alguien del pasado antes de que tu mente lo hiciera?", 1),
        ("¿Cuándo fue la última vez que la naturaleza fue el escenario de un recuerdo de alguien que ya no está?", 1),
        ("¿Cuándo fue la última vez que un hábito físico que empezaste en una relación lo mantenés porque se volvió tuyo?", 1),
        ("¿Cuándo fue la última vez que competir con alguien del pasado en algo —aunque fuera informal— te mostró algo de cómo era esa relación?", 1),
        ("¿Cuándo fue la última vez que la salud fue algo en lo que una relación pasada te impactó —para bien o para mal?", 1),
        ("¿Cuándo fue la última vez que volviste a cocinar algo que cocinabas cuando estabas con alguien?", 1),
        ("¿Cuándo fue la última vez que el cuerpo te mostró que todavía estabas procesando algo de una relación pasada?", 1),
        ("¿Cuándo fue la última vez que un ritual físico —deporte, caminata, comida— que compartías con alguien lo resignificaste solo?", 1),
        ("¿Cuándo fue la última vez que el cuerpo te ayudó a procesar el fin de una relación de una manera que la mente sola no podía?", 1),
        ("¿Cuándo fue la última vez que algo físico —un lugar, un olor, una comida— te conectó con alguien del pasado sin que lo esperaras?", 1),
        ("¿Cuándo fue la última vez que retomaste un hábito de salud que habías abandonado con alguien y fue parte de recuperarte?", 1),
        ("¿Cuándo fue la última vez que la naturaleza fue el espacio donde pudiste procesar algo de una relación terminada?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que la manera en que alguien se relacionaba con su cuerpo también era parte de por qué la relación no funcionó?", 2),
        ("¿Cuándo fue la última vez que un lugar natural al que ibas con alguien lo visitaste de nuevo y fue parte de soltar?", 2),
        ("¿Cuándo fue la última vez que la forma en que te cuidaste o no después de una relación te mostró algo de vos mismo?", 2),
        ("¿Cuándo fue la última vez que el deporte o la actividad física fueron tu manera de sobrevivir una ruptura?", 2),
        ("¿Cuándo fue la última vez que cocinar algo que cocinaban juntos fue un acto de apropiarte de algo que era de los dos?", 2),
        ("¿Cuándo fue la última vez que el cuerpo fue el primero en soltar a alguien, antes que la mente?", 2),
        ("¿Cuándo fue la última vez que notaste que tus hábitos de salud mejoraron después de salir de una relación?", 2),
        ("¿Cuándo fue la última vez que un lugar natural te sirvió para despedirte de algo de una manera que las palabras no hubieran podido?", 2),
        ("¿Cuándo fue la última vez que volver a moverte —hacer deporte, salir— fue la primera señal de que estabas sanando?", 2),
        ("¿Cuándo fue la última vez que la comida fue el idioma de algo que no pudiste decirte a vos mismo sobre una relación pasada?", 2),
        ("¿Cuándo fue la última vez que el cuerpo te mostró que habías sanado de algo antes de que tu mente lo reconociera?", 3),
        ("¿Cuándo fue la última vez que la naturaleza fue el escenario de un cierre que no pudiste tener de otra manera?", 3),
        ("¿Cuándo fue la última vez que un hábito físico que desarrollaste después de una relación se convirtió en una de las cosas más tuyas que tenés?", 3),
        ("¿Cuándo fue la última vez que el cuerpo fue el lugar donde más claramente sentiste el peso de algo que necesitabas soltar?", 3),
        ("¿Cuándo fue la última vez que cuidar tu cuerpo después de una ruptura fue también una manera de recuperar algo de vos mismo?", 3),
        ("¿Cuándo fue la última vez que la relación con tu cuerpo cambió fundamentalmente después de una relación, y eso fue algo positivo?", 3),
    ],

    "personalidad": [
        ("¿Cuándo fue la última vez que el deporte o la actividad física te mostró algo de tu carácter que no veías en otro contexto?", 1),
        ("¿Cuándo fue la última vez que competir con alguien te reveló algo de vos mismo que no te esperabas?", 1),
        ("¿Cuándo fue la última vez que estar al aire libre cambió tu humor de manera radical?", 1),
        ("¿Cuándo fue la última vez que tu relación con la comida te dijo algo de vos mismo?", 1),
        ("¿Cuándo fue la última vez que el movimiento físico —deporte, baile, caminata— fue la mejor manera de aclarar tu cabeza?", 1),
        ("¿Cuándo fue la última vez que ganar o perder en algo te mostró cómo manejás la competencia?", 1),
        ("¿Cuándo fue la última vez que la naturaleza te recordó quién sos cuando estás sin ruido?", 1),
        ("¿Cuándo fue la última vez que te sorprendiste a vos mismo siendo más competitivo —o menos— de lo que creías?", 1),
        ("¿Cuándo fue la última vez que cocinar algo fue un acto meditativo que te hizo bien?", 1),
        ("¿Cuándo fue la última vez que el cuerpo fue el primer lugar donde notaste que algo estaba mal en vos?", 1),
        ("¿Cuándo fue la última vez que una actividad física te hizo sentir que eras más capaz de lo que pensabas?", 1),
        ("¿Cuándo fue la última vez que tu relación con la comida reflejó algo de cómo estabas emocionalmente?", 1),
        ("¿Cuándo fue la última vez que estar en la naturaleza te hizo sentir que tu perspectiva era demasiado chica para el mundo?", 1),
        ("¿Cuándo fue la última vez que el deporte te enseñó algo sobre cómo te relacionás con el error?", 1),
        ("¿Cuándo fue la última vez que notaste que tu cuerpo era más sabio que tu cabeza?", 1),
        ("¿Cuándo fue la última vez que la forma en que te movés en el espacio físico te dijo algo sobre cómo te movés en la vida?", 1),
        ("¿Cuándo fue la última vez que superaste algo físico y eso impactó en cómo te sentías respecto a algo completamente distinto?", 1),
        ("¿Cuándo fue la última vez que te sorprendiste siendo más resistente físicamente de lo que creías?", 1),
        ("¿Cuándo fue la última vez que el cuidado de tu cuerpo fue también una forma de cuidar tu identidad?", 1),
        ("¿Cuándo fue la última vez que un momento en la naturaleza te hizo sentir que sos más simple y más esencial de lo que creés?", 1),
        ("¿Cuándo fue la última vez que tu forma de manejar la competencia te enseñó algo que no sabías de vos?", 1),
        ("¿Cuándo fue la última vez que cocinar o comer fue la manera en que mejor te cuidaste?", 1),
        ("¿Cuándo fue la última vez que el movimiento físico fue la única manera en que podías ser honesto con vos mismo?", 1),
        ("¿Cuándo fue la última vez que la naturaleza te hizo sentir menos urgente todo lo que en la ciudad parecía urgente?", 1),
        ("¿Cuándo fue la última vez que la competencia reveló algo de tu carácter que querés trabajar?", 2),
        ("¿Cuándo fue la última vez que el cuerpo fue más honesto con vos que cualquier pensamiento que pudieras tener?", 2),
        ("¿Cuándo fue la última vez que tu relación con la comida te mostró algo que querías cambiar de vos mismo?", 2),
        ("¿Cuándo fue la última vez que un desafío físico te hizo ver de qué estás hecho?", 2),
        ("¿Cuándo fue la última vez que la naturaleza te devolvió algo de vos mismo que la vida cotidiana te había sacado?", 2),
        ("¿Cuándo fue la última vez que el esfuerzo físico te mostró que podés más de lo que tu mente te convence?", 2),
        ("¿Cuándo fue la última vez que cuidar tu cuerpo fue también una forma de respetarte?", 2),
        ("¿Cuándo fue la última vez que la forma en que te relacionás con el descanso te reveló algo sobre cómo te tratás?", 2),
        ("¿Cuándo fue la última vez que el deporte fue el espacio donde pudiste ser una versión de vos mismo que no mostrás en otro lado?", 2),
        ("¿Cuándo fue la última vez que la naturaleza te puso en perspectiva de una manera que nada más podía hacerlo?", 2),
        ("¿Cuándo fue la última vez que el cuerpo te enseñó sobre la paciencia de una manera que la mente sola no podía?", 3),
        ("¿Cuándo fue la última vez que la naturaleza te hizo confrontar algo de vos mismo que en la ciudad evitás?", 3),
        ("¿Cuándo fue la última vez que superar algo físico te cambió algo en cómo te ves a vos mismo?", 3),
        ("¿Cuándo fue la última vez que la relación con tu cuerpo fue el espejo más honesto de tu estado interior?", 3),
        ("¿Cuándo fue la última vez que el cuidado del cuerpo fue también un acto de amor propio que no podías darte de ninguna otra manera?", 3),
        ("¿Cuándo fue la última vez que la naturaleza fue el espacio donde encontraste una versión de vos mismo que no sabías que necesitabas?", 3),
    ],

    "miedos": [
        ("¿Cuándo fue la última vez que le tuviste miedo a algo físico —una lesión, una enfermedad— y lo superaste?", 1),
        ("¿Cuándo fue la última vez que le tuviste miedo a perder en algo y lo intentaste igual?", 1),
        ("¿Cuándo fue la última vez que la naturaleza te generó un miedo que también fue emocionante?", 1),
        ("¿Cuándo fue la última vez que el miedo a enfermarte cambió algo en cómo te cuidás?", 1),
        ("¿Cuándo fue la última vez que le tuviste miedo a algo al aire libre —una tormenta, una altura— y lo atravesaste?", 1),
        ("¿Cuándo fue la última vez que el miedo a perder una capacidad física te motivó a cuidarla más?", 1),
        ("¿Cuándo fue la última vez que el miedo al juicio sobre tu cuerpo te impidió hacer algo que querías?", 1),
        ("¿Cuándo fue la última vez que el deporte fue el espacio donde te enfrentaste a un miedo de manera segura?", 1),
        ("¿Cuándo fue la última vez que la comida fue algo que te generó ansiedad o miedo en lugar de placer?", 1),
        ("¿Cuándo fue la última vez que el miedo a una competencia te paralizó y qué hiciste con eso?", 1),
        ("¿Cuándo fue la última vez que el miedo a la enfermedad de alguien cercano te hizo replantearte algo?", 1),
        ("¿Cuándo fue la última vez que la oscuridad o el silencio de la naturaleza te generó una incomodidad que después disfrutaste?", 1),
        ("¿Cuándo fue la última vez que el miedo a no rendir físicamente te frenó antes de intentar algo?", 1),
        ("¿Cuándo fue la última vez que la naturaleza te hizo sentir pequeño de una manera que al principio dio miedo y después dio paz?", 1),
        ("¿Cuándo fue la última vez que el cuerpo te avisó de un miedo antes de que tu cabeza lo procesara?", 1),
        ("¿Cuándo fue la última vez que competir te puso en contacto con el miedo a fallar de una manera que te enseñó algo?", 1),
        ("¿Cuándo fue la última vez que una experiencia en la naturaleza te quitó un miedo que creías permanente?", 1),
        ("¿Cuándo fue la última vez que el miedo al dolor físico te impidió hacer algo que valía la pena?", 1),
        ("¿Cuándo fue la última vez que el cuidado del cuerpo fue también una forma de manejar la ansiedad?", 1),
        ("¿Cuándo fue la última vez que el miedo a la vulnerabilidad física —enfermarse, lesionarse— te hizo más consciente de lo que tenés?", 1),
        ("¿Cuándo fue la última vez que el miedo en la competencia te hizo dar lo mejor o lo peor de vos?", 1),
        ("¿Cuándo fue la última vez que una tormenta, una altura o la inmensidad de la naturaleza te recordó que hay cosas que no controlás?", 1),
        ("¿Cuándo fue la última vez que el miedo al envejecimiento físico fue algo que te hizo actuar en lugar de paralizarte?", 1),
        ("¿Cuándo fue la última vez que la naturaleza fue el espacio donde pudiste estar con tus miedos sin que nadie los vea?", 1),
        ("¿Cuándo fue la última vez que el miedo al deterioro físico te hizo replantearte cómo vivís?", 2),
        ("¿Cuándo fue la última vez que el miedo al cuerpo —propio o ajeno— fue algo que elegiste enfrentar en lugar de evadir?", 2),
        ("¿Cuándo fue la última vez que el miedo a perder en algo competitivo te reveló algo de cómo manejás la derrota?", 2),
        ("¿Cuándo fue la última vez que la naturaleza fue el espacio donde pudiste estar con un miedo que en la vida cotidiana siempre evitás?", 2),
        ("¿Cuándo fue la última vez que la salud —propia o de alguien cercano— te mostró algo de lo que más temés?", 2),
        ("¿Cuándo fue la última vez que el deporte fue el lugar donde aprendiste que el miedo y el coraje pueden coexistir?", 2),
        ("¿Cuándo fue la última vez que el miedo al dolor —físico o emocional que se somatizaba— fue una señal que necesitabas escuchar?", 2),
        ("¿Cuándo fue la última vez que estar en la naturaleza te conectó con un miedo existencial de una manera que en la ciudad nunca hubiera pasado?", 2),
        ("¿Cuándo fue la última vez que el miedo a la enfermedad fue también un miedo a la dependencia o a la pérdida de control?", 2),
        ("¿Cuándo fue la última vez que la competencia te enseñó que el miedo a perder puede ser más valioso que ganar?", 2),
        ("¿Cuándo fue la última vez que el cuerpo fue el mapa de tus miedos más honestos?", 3),
        ("¿Cuándo fue la última vez que la naturaleza te enfrentó con la idea de la propia mortalidad de una manera que no pudiste ignorar?", 3),
        ("¿Cuándo fue la última vez que el miedo a la pérdida física —salud, capacidad, vitalidad— te mostró lo que más valorás?", 3),
        ("¿Cuándo fue la última vez que el deporte o el esfuerzo físico fueron el espacio donde pudiste enfrentar un miedo que en la vida cotidiana siempre evadías?", 3),
        ("¿Cuándo fue la última vez que el miedo al cuerpo propio —su fragilidad, su cambio, su límite— te puso en contacto con algo muy profundo de quién sos?", 3),
        ("¿Cuándo fue la última vez que la naturaleza te hizo ver que lo que más te asusta también es lo que más te hace sentir vivo?", 3),
    ],

    "logros": [
        ("¿Cuándo fue la última vez que lograste algo físico que no creías poder hacer?", 1),
        ("¿Cuándo fue la última vez que ganar en algo —un partido, una carrera, una competencia— te dio una satisfacción que duró más de un día?", 1),
        ("¿Cuándo fue la última vez que preparaste una comida que salió mejor de lo que esperabas?", 1),
        ("¿Cuándo fue la última vez que llegaste a un lugar al aire libre que te costó mucho alcanzar?", 1),
        ("¿Cuándo fue la última vez que mantuviste un hábito de salud durante más tiempo del que esperabas?", 1),
        ("¿Cuándo fue la última vez que tu cuerpo te sorprendió con lo que podía hacer?", 1),
        ("¿Cuándo fue la última vez que completaste un desafío físico que antes te parecía imposible?", 1),
        ("¿Cuándo fue la última vez que volviste a practicar algo que habías abandonado y descubriste que todavía podías?", 1),
        ("¿Cuándo fue la última vez que cocinaste algo muy difícil y salió bien?", 1),
        ("¿Cuándo fue la última vez que un logro físico te recordó que podés más de lo que creés?", 1),
        ("¿Cuándo fue la última vez que superaste a alguien —o a una versión de vos mismo— en algo competitivo?", 1),
        ("¿Cuándo fue la última vez que alcanzaste algún lugar en la naturaleza que no creías poder llegar?", 1),
        ("¿Cuándo fue la última vez que lograste mejorar algo en tu salud que llevaba tiempo sin que lo lograras?", 1),
        ("¿Cuándo fue la última vez que te animaste a probar una comida o receta nueva y resultó siendo algo que ahora hacés seguido?", 1),
        ("¿Cuándo fue la última vez que ganaste algo en lo que competiste contra vos mismo —tu tiempo, tu resistencia, tu técnica?", 1),
        ("¿Cuándo fue la última vez que el deporte o la actividad física fue el contexto de uno de tus logros más claros?", 1),
        ("¿Cuándo fue la última vez que un logro físico te dio perspectiva sobre lo que podés lograr en otros ámbitos?", 1),
        ("¿Cuándo fue la última vez que vencer un miedo físico fue uno de tus mayores logros del año?", 1),
        ("¿Cuándo fue la última vez que recuperarte de una lesión o enfermedad fue uno de los procesos más enseñadores que tuviste?", 1),
        ("¿Cuándo fue la última vez que una experiencia en la naturaleza te dejó la sensación de haber logrado algo que no tiene trofeo?", 1),
        ("¿Cuándo fue la última vez que el deporte te mostró que el proceso importa más que el resultado?", 1),
        ("¿Cuándo fue la última vez que cocinar algo bien fue una de las satisfacciones más simples y completas de la semana?", 1),
        ("¿Cuándo fue la última vez que un logro físico te abrió la puerta a creer que podías lograr algo que te parecía inalcanzable?", 1),
        ("¿Cuándo fue la última vez que completar algo físico —una caminata, una carrera, una rutina— fue también una forma de completarte?", 1),
        ("¿Cuándo fue la última vez que un logro físico te cambió algo en cómo te ves a vos mismo?", 2),
        ("¿Cuándo fue la última vez que la persistencia en algo físico te enseñó algo sobre la persistencia en otros ámbitos de tu vida?", 2),
        ("¿Cuándo fue la última vez que superar algo físico difícil te hizo sentir que podés superar cualquier cosa?", 2),
        ("¿Cuándo fue la última vez que un logro relacionado con la salud o el cuerpo te hizo replantearte lo que definís como éxito?", 2),
        ("¿Cuándo fue la última vez que la naturaleza fue el escenario de uno de tus logros más significativos?", 2),
        ("¿Cuándo fue la última vez que el proceso de recuperar una capacidad física fue más valioso que tenerla?", 2),
        ("¿Cuándo fue la última vez que ganar en algo físico fue también ganar algo dentro de vos?", 2),
        ("¿Cuándo fue la última vez que un logro físico fue el resultado de haber superado un miedo?", 2),
        ("¿Cuándo fue la última vez que dominar una receta o técnica culinaria fue un orgullo que no esperabas sentir tan fuerte?", 2),
        ("¿Cuándo fue la última vez que la naturaleza fue testigo de un momento en que demostraste algo que no sabías que podías?", 2),
        ("¿Cuándo fue la última vez que un logro físico fue también el cierre de algo que estabas procesando?", 3),
        ("¿Cuándo fue la última vez que superar algo con tu cuerpo te enseñó algo sobre vos que ningún logro intelectual o profesional te hubiera podido enseñar?", 3),
        ("¿Cuándo fue la última vez que la naturaleza fue el contexto donde lograste algo que te demostró que sos capaz de más de lo que tu mente te limita?", 3),
        ("¿Cuándo fue la última vez que un logro físico fue una forma de honrar algo —un proceso, una pérdida, una decisión— que merecía ser honrado?", 3),
        ("¿Cuándo fue la última vez que el cuerpo fue el primer lugar donde notaste que habías logrado algo que importaba de verdad?", 3),
        ("¿Cuándo fue la última vez que superar un límite físico cambió algo en cómo te relacionás con tus límites en general?", 3),
    ],

    "sinFiltro": [
        ("¿Cuándo fue la última vez que fingiste haber hecho ejercicio cuando en realidad no hiciste nada?", 1),
        ("¿Cuándo fue la última vez que comiste algo en secreto que se supone que no debías comer?", 1),
        ("¿Cuándo fue la última vez que te hiciste el enfermo para no ir a hacer algo físico que no querías?", 1),
        ("¿Cuándo fue la última vez que dijiste que ibas al gimnasio y te fuiste a hacer algo completamente distinto?", 1),
        ("¿Cuándo fue la última vez que te comparaste físicamente con alguien de manera poco sana?", 1),
        ("¿Cuándo fue la última vez que hiciste trampa en algo competitivo aunque sea en algo pequeño?", 1),
        ("¿Cuándo fue la última vez que comiste parado frente a la heladera a las 3 de la mañana?", 1),
        ("¿Cuándo fue la última vez que dijiste que ibas a empezar una dieta o rutina de ejercicios el lunes y no lo hiciste?", 1),
        ("¿Cuándo fue la última vez que te pusiste mal porque perdiste en algo ridículo?", 1),
        ("¿Cuándo fue la última vez que exageraste algo físico tuyo para impresionar a alguien?", 1),
        ("¿Cuándo fue la última vez que googleaste los síntomas de algo y te convenciste de que tenías una enfermedad grave?", 1),
        ("¿Cuándo fue la última vez que usaste el clima como excusa para no salir o no hacer algo?", 1),
        ("¿Cuándo fue la última vez que le dijiste a alguien que eras deportista cuando hace meses que no hacés nada?", 1),
        ("¿Cuándo fue la última vez que rompiste una 'racha saludable' y lo disfrutaste más de lo que esperabas?", 1),
        ("¿Cuándo fue la última vez que competiste a muerte en algo completamente insignificante?", 1),
        ("¿Cuándo fue la última vez que te quejaste de no tener tiempo para hacer ejercicio cuando en realidad perdiste horas en el teléfono?", 1),
        ("¿Cuándo fue la última vez que usaste una app de salud para sentirte bien con vos mismo aunque los datos no coincidieran?", 1),
        ("¿Cuándo fue la última vez que pediste algo saludable en un restaurante y después robaste comida del plato de otro?", 1),
        ("¿Cuándo fue la última vez que te sacaste una foto para que pareciera que estabas en la naturaleza siendo una persona activa?", 1),
        ("¿Cuándo fue la última vez que te peleaste mentalmente con alguien que te ganó en algo y te inventaste excusas?", 1),
        ("¿Cuándo fue la última vez que compraste ropa de deporte que usaste exactamente una vez?", 1),
        ("¿Cuándo fue la última vez que te conveniste de que el estrés era razón suficiente para comerte lo que se te antojara?", 1),
        ("¿Cuándo fue la última vez que dijiste que ibas a hacer algo en la naturaleza —camping, senderismo— y te quedaste en casa?", 1),
        ("¿Cuándo fue la última vez que le exageraste a alguien cuánto ejercicio hacés o cuán saludable comés?", 1),
        ("¿Cuándo fue la última vez que te pusiste celoso de alguien por algo físico y lo convertiste en motivación aunque al principio fue envidia?", 2),
        ("¿Cuándo fue la última vez que la competencia sacó lo peor de vos y no lo pudiste reconocer en ese momento?", 2),
        ("¿Cuándo fue la última vez que usaste la salud o el ejercicio para evitar pensar en algo que no querías enfrentar?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que tu relación con la comida decía algo de vos que no querías escuchar?", 2),
        ("¿Cuándo fue la última vez que el deporte o la competencia reveló algo de tu carácter que preferirías no haber visto?", 2),
        ("¿Cuándo fue la última vez que usaste 'necesito estar saludable' como excusa para no conectar con alguien?", 2),
        ("¿Cuándo fue la última vez que la naturaleza te puso en tu lugar de una manera que no pudiste procesar en el momento?", 2),
        ("¿Cuándo fue la última vez que tu cuerpo te mostró algo de vos mismo que no querías ver?", 2),
        ("¿Cuándo fue la última vez que perdiste en algo físico de manera humillante y cómo lo manejaste internamente?", 2),
        ("¿Cuándo fue la última vez que la forma en que comés cuando nadie te ve es completamente distinta a cuando te ven?", 2),
        ("¿Cuándo fue la última vez que el cuerpo te dijo una verdad sobre vos mismo que tu ego no estaba listo para escuchar?", 3),
        ("¿Cuándo fue la última vez que la competencia reveló algo de tu carácter que te avergonzó pero te enseñó algo importante?", 3),
        ("¿Cuándo fue la última vez que la naturaleza te sacó de todas tus máscaras y lo que quedó no era exactamente lo que esperabas?", 3),
        ("¿Cuándo fue la última vez que tu relación con el cuerpo —cómo lo cuidás, cómo lo tratás, cómo lo juzgás— fue el reflejo más honesto de cómo te tratás a vos mismo?", 3),
        ("¿Cuándo fue la última vez que ganar en algo se sintió vacío porque te diste cuenta de que habías sacrificado algo importante para lograrlo?", 3),
        ("¿Cuándo fue la última vez que el cuerpo fue el espacio donde más claramente podías ver lo que te estabas haciendo a vos mismo sin darte cuenta?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS12:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS12[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
