#!/usr/bin/env python3
"""Batch 27 - nature, environment, animals, seasons, sensory world."""
import json

ADDITIONS27 = {
    "infancia": [
        ("¿Qué animal de tu infancia te marcó más, una mascota, un bicho, o uno que viste en un libro?", 1),
        ("¿Cuál era tu estación del año favorita de chico y por qué?", 1),
        ("¿Tenías algún lugar al aire libre donde te escapabas a jugar solo?", 1),
        ("¿Qué olores de la naturaleza te remiten automáticamente a tu infancia?", 1),
        ("¿Eras más de playa, montaña, campo o ciudad cuando eras chico?", 1),
        ("¿Alguna vez tuviste miedo de algún animal siendo chico?", 1),
        ("¿Qué juego al aire libre era tu favorito cuando eras chico?", 1),
        ("¿Recordás algún día de lluvia de tu infancia que haya sido especial?", 1),
        ("¿Cuál era el lugar de la naturaleza más cercano a tu casa de infancia?", 1),
        ("¿Alguna vez cuidaste a un animal siendo chico? ¿Cómo fue?", 1),
        ("¿Qué sonido de la naturaleza te transporta directamente a tu infancia?", 1),
        ("¿Había alguna planta, árbol o jardín que fuera especial para vos de chico?", 1),
        ("¿Alguna vez te perdiste o te asustaste en algún lugar abierto siendo chico?", 1),
        ("¿Cuál era el animal que más querías tener de mascota cuando eras chico?", 1),
        ("¿El clima de donde creciste cómo te afectaba en el humor?", 1),
        ("¿Qué cosa de la naturaleza te generaba fascinación de chico: insectos, estrellas, tormentas?", 1),
        ("¿Recordás algún atardecer o amanecer especial de tu infancia?", 1),
        ("¿Qué actividad al aire libre hacías con tu familia de chico?", 1),
        ("¿Había algún animal que te daba asco o miedo siendo chico y hoy no?", 1),
        ("¿El frío o el calor: ¿cuál preferías cuando eras chico?", 1),
        ("¿Qué cosa de la naturaleza de tu infancia te gustaría mostrarle a alguien que nunca la conoció?", 1),
        ("¿Alguna vez viste algo en la naturaleza siendo chico que te resultó inexplicable?", 2),
        ("¿Qué relación tenían tus papás o familia con la naturaleza y cómo te influyó eso?", 2),
        ("¿Alguna vez la naturaleza te ayudó a procesar algo difícil de chico?", 2),
        ("¿Qué aprendiste sobre la vida observando animales o plantas de chico?", 2),
        ("¿Hubo algún momento en la naturaleza de tu infancia donde sentiste algo que no podías explicar?", 2),
        ("¿La conexión con la naturaleza era algo valorado en tu familia cuando eras chico?", 2),
        ("¿Qué animal o elemento de la naturaleza de tu infancia sería tu símbolo personal?", 2),
        ("¿Hubo alguna pérdida de un animal o lugar natural de tu infancia que te dolió profundamente?", 3),
        ("¿De qué manera el entorno natural donde creciste moldeó quién sos hoy?", 3),
        ("¿Hay algún elemento de la naturaleza de tu infancia que sentís que te define de manera que no podés explicar del todo?", 3),
        ("¿Alguna vez la naturaleza te reveló algo sobre vos mismo siendo chico que todavía llevás?", 3),
        ("¿Qué lugar natural de tu infancia simboliza algo que perdiste al crecer?", 3),
        ("¿Cómo sería tu infancia ideal en términos de entorno natural?", 3),
        ("¿Qué emoción te genera hoy la naturaleza que relacionás directamente con algo de tu infancia?", 3),
    ],

    "futuro": [
        ("¿Qué tipo de entorno natural te gustaría tener cerca en tu futuro ideal?", 1),
        ("¿Te imaginas viviendo en el campo, la ciudad, la montaña o la costa en el futuro?", 1),
        ("¿Qué animal te gustaría tener en tu vida futura?", 1),
        ("¿Cómo te imaginás que el cambio climático va a afectar tu vida en el futuro?", 1),
        ("¿En tu futuro ideal tenés jardín, huerta, plantas, o nada de eso?", 1),
        ("¿Hay algún lugar natural del mundo que quieras conocer antes de morir?", 1),
        ("¿Te imaginás haciendo algo en el futuro que esté conectado con la naturaleza?", 1),
        ("¿Qué estación del año domina en el futuro que te imaginás?", 1),
        ("¿Creés que en el futuro vas a vivir en el mismo tipo de clima que ahora?", 1),
        ("¿Qué elemento de la naturaleza querés que esté presente en tu futuro cotidiano?", 1),
        ("¿Te gustaría aprender algo relacionado con la naturaleza en el futuro: bucear, escalar, cultivar?", 1),
        ("¿Cómo querés que sea tu relación con el entorno natural en el futuro?", 1),
        ("¿Qué impacto ambiental te gustaría minimizar en tu vida futura?", 1),
        ("¿Te imaginás viajes futuros a lugares naturales específicos? ¿Cuáles?", 1),
        ("¿Querés que tus hijos o las próximas generaciones tengan una relación diferente con la naturaleza?", 1),
        ("¿Cuán importante es para vos vivir cerca de la naturaleza en tu proyecto de vida?", 1),
        ("¿Qué fenómeno natural te gustaría presenciar alguna vez?", 1),
        ("¿Cómo te imaginás que va a cambiar tu relación con la naturaleza a medida que envejezcas?", 1),
        ("¿Hay algún animal que te gustaría observar en su hábitat natural antes de que desaparezca?", 1),
        ("¿Qué hábito relacionado con el cuidado del ambiente querés sostener en el futuro?", 1),
        ("¿En tu futuro ideal qué rol juega el silencio y el contacto con la naturaleza en tu rutina?", 1),
        ("¿Cuán preocupado estás por el estado del planeta para el futuro de quienes amás?", 2),
        ("¿Hay alguna causa ambiental que quieras apoyar activamente en el futuro?", 2),
        ("¿Qué renunciarías hoy para dejar un ambiente mejor para el futuro?", 2),
        ("¿La conexión con la naturaleza es algo que querés cultivar activamente en tu proyecto de vida o es secundario?", 2),
        ("¿Cómo conecta tu relación con la naturaleza con tus valores más profundos de cara al futuro?", 2),
        ("¿Qué lugar natural del mundo sería tu refugio definitivo si pudieras elegir?", 2),
        ("¿Qué legado ambiental querés dejar?", 2),
        ("¿Creés que la desconexión de la naturaleza es algo que te está costando algo hoy y que querés cambiar?", 3),
        ("¿Qué versión futura de vos mismo es la más conectada con el mundo natural y qué necesitarías para llegar ahí?", 3),
        ("¿Si el planeta te pidiera algo concreto para el futuro, qué te pediría?", 3),
        ("¿Qué relación con la naturaleza querés transmitirles a quienes vienen después?", 3),
        ("¿Hay alguna contradicción entre tus valores ambientales y cómo vivís hoy que querés resolver?", 3),
        ("¿Qué futuro te asusta más: uno sin tecnología o uno sin naturaleza?", 3),
        ("¿Qué parte de la naturaleza sentís que sos, y cómo querés honrar eso en el futuro?", 3),
    ],

    "amor": [
        ("¿Cuál es el plan con la naturaleza que más disfrutás hacer con alguien que amás?", 1),
        ("¿Preferís una cita romántica en la ciudad o al aire libre?", 1),
        ("¿Hay algún lugar natural que asocies con una historia de amor importante?", 1),
        ("¿Qué estación del año te parece más romántica?", 1),
        ("¿Alguna vez tuviste una experiencia romántica en la naturaleza que no olvidaste?", 1),
        ("¿Qué tipo de entorno natural te parece más íntimo para una conversación profunda?", 1),
        ("¿El mal tiempo te pone más romántico o más irritable?", 1),
        ("¿Cuál es el sonido de la naturaleza que más te relaja al lado de alguien?", 1),
        ("¿Qué actividad al aire libre te gustaría compartir con tu pareja ideal?", 1),
        ("¿Alguna vez el clima afectó de manera inesperada una historia de amor?", 1),
        ("¿Qué animal o elemento de la naturaleza te hace pensar en el amor?", 1),
        ("¿El tipo de vínculo que buscás en el amor se parece más a un río, un lago, el mar, o una tormenta?", 1),
        ("¿Tenés algún lugar en la naturaleza que sea especial para una relación tuya?", 1),
        ("¿Preferís un amanecer o un atardecer junto a alguien que amás?", 1),
        ("¿El entorno donde vivís ahora favorece o dificulta el tipo de vida romántica que querés?", 1),
        ("¿Alguna vez la naturaleza fue el escenario de una declaración o un momento de amor importante?", 1),
        ("¿Cuál es el plan más simple y natural que te llena de amor: sentarse a ver pasar la tarde, salir a caminar, ver el cielo?", 1),
        ("¿Qué elemento de la naturaleza usarías para describir cómo amás?", 1),
        ("¿Cuánto importa para vos que tu pareja comparta el amor por la naturaleza?", 1),
        ("¿Qué tipo de entorno natural te genera más ganas de abrirte emocionalmente?", 1),
        ("¿Alguna vez el silencio en la naturaleza junto a alguien fue más íntimo que cualquier conversación?", 2),
        ("¿Cómo influye el entorno natural en la calidad de tu vida amorosa?", 2),
        ("¿Qué relación ves entre cómo te conectás con la naturaleza y cómo te conectás con las personas que amás?", 2),
        ("¿Hay alguna manera en que la naturaleza te enseñó algo sobre el amor?", 2),
        ("¿Cómo querés que sea el entorno natural en el que envejezcas junto a alguien?", 2),
        ("¿Qué analogía con la naturaleza describe mejor la relación más importante de tu vida?", 2),
        ("¿Hay algún lugar natural al que quieras volver con alguien que ya no está en tu vida?", 2),
        ("¿Cómo sería el amor perfecto en términos de entorno, clima, y lugar?", 3),
        ("¿Qué cosa de la naturaleza expresa mejor lo que no podés decir con palabras sobre cómo amás?", 3),
        ("¿Hay alguna emoción que solo sentís en la naturaleza y que querés sentir también en el amor?", 3),
        ("¿Qué lugar natural del mundo sería el escenario de la historia de amor más honesta tuya?", 3),
        ("¿Cómo conecta tu relación con la naturaleza con tu capacidad de amar?", 3),
        ("¿Si el amor fuera un fenómeno natural, cuál sería para vos?", 3),
        ("¿Qué aprendiste sobre el amor observando la naturaleza?", 3),
        ("¿Hay algún lugar natural al que todavía querés llevar a alguien y no lo hiciste?", 3),
    ],

    "familia": [
        ("¿Qué actividad al aire libre hacías con tu familia que recordás con alegría?", 1),
        ("¿Tu familia tenía alguna tradición relacionada con la naturaleza o las estaciones?", 1),
        ("¿Había alguna mascota en tu familia que fuera especialmente importante?", 1),
        ("¿Tu familia era más de campo, playa, montaña o ciudad?", 1),
        ("¿Qué lugar natural te recuerda a tu familia más que cualquier otra cosa?", 1),
        ("¿Alguna vez tuviste un viaje familiar a la naturaleza que fue un desastre divertido?", 1),
        ("¿Qué estación del año era la favorita de tu familia y por qué?", 1),
        ("¿Había algún animal que fuera especial o simbólico en tu familia?", 1),
        ("¿Tu familia cuidaba el entorno o el ambiente como un valor?", 1),
        ("¿Qué sonido de la naturaleza te remite inmediatamente a un momento familiar?", 1),
        ("¿Hubo algún viaje familiar a un lugar natural que te haya cambiado?", 1),
        ("¿Tu familia tenía algún lugar natural específico que consideraban suyo?", 1),
        ("¿Cómo era el entorno de tu casa familiar: jardín, terraza, ciudad, campo?", 1),
        ("¿Hay algún olor de la naturaleza que te recuerde a un familiar específico?", 1),
        ("¿Qué le querés transmitir a tu familia sobre la relación con la naturaleza?", 1),
        ("¿Hay alguna tradición familiar que quieras crear o mantener relacionada con la naturaleza?", 1),
        ("¿Cuál fue el animal de la familia que más te marcó?", 1),
        ("¿Qué lugar natural familiar querés que perviva en la memoria colectiva de tu familia?", 1),
        ("¿Tu familia te transmitió respeto o miedo por algún elemento de la naturaleza?", 1),
        ("¿Cómo definirías la relación de tu familia con el entorno natural?", 1),
        ("¿Qué valores sobre la naturaleza y el ambiente te transmitió tu familia y cuáles rechazaste?", 2),
        ("¿Hay algún lugar natural que sea el corazón de la identidad de tu familia?", 2),
        ("¿Alguna vez la naturaleza fue el escenario de un momento familiar difícil que te marcó?", 2),
        ("¿Qué relación entre familia y naturaleza querés crear o mantener en tu propia vida?", 2),
        ("¿Cómo el entorno geográfico donde creció tu familia moldeó su forma de ver el mundo?", 2),
        ("¿Hay algún animal o lugar natural que sea un símbolo de tu historia familiar?", 2),
        ("¿Qué aprendiste sobre la vida observando la relación de tu familia con la naturaleza?", 2),
        ("¿Qué lugar natural sería el escenario ideal para reunir a toda tu familia?", 3),
        ("¿Cómo la relación de tu familia con la naturaleza refleja algo más profundo sobre quiénes son?", 3),
        ("¿Hay algún elemento de la naturaleza que sientas que conecta a tu familia a través del tiempo y la distancia?", 3),
        ("¿Qué lugar natural querés que sea el escenario del capítulo más importante de tu historia familiar futura?", 3),
        ("¿Cómo te gustaría que la naturaleza estuviera presente en la vida de las personas que amás?", 3),
        ("¿Qué herida o alegría familiar estás conectando cuando te encontrás con la naturaleza?", 3),
        ("¿Si tu familia fuera un ecosistema, qué tipo sería y qué rol ocuparías vos?", 3),
        ("¿Qué parte de tu historia familiar existe solo porque existió un lugar natural específico?", 3),
    ],

    "amistades": [
        ("¿Cuál es el plan al aire libre que más disfrutás hacer con amigos?", 1),
        ("¿Hay algún lugar natural que sea el escenario de tus mejores momentos con amigos?", 1),
        ("¿Cuál fue el viaje a la naturaleza más memorable que hiciste con amigos?", 1),
        ("¿Preferís planes de amistad en la ciudad o en contacto con la naturaleza?", 1),
        ("¿Qué actividad outdoor te gustaría hacer con amigos que todavía no hiciste?", 1),
        ("¿Alguna vez la naturaleza fue el contexto de un momento de quiebre o profundidad con un amigo?", 1),
        ("¿Qué tipo de entorno natural preferís para tener una charla importante con un amigo?", 1),
        ("¿Tenés algún ritual de amistad relacionado con la naturaleza: camping, playa, trekking?", 1),
        ("¿Hay algún lugar natural que sea exclusivo de una amistad específica tuya?", 1),
        ("¿Cómo el entorno natural afecta la calidad de las charlas con tus amigos?", 1),
        ("¿Qué estación del año preferís para estar con amigos?", 1),
        ("¿Alguna vez un animal o un evento de la naturaleza generó un momento memorable con amigos?", 1),
        ("¿Tus amigos más cercanos comparten tu amor o indiferencia por la naturaleza?", 1),
        ("¿Cuál fue la aventura natural más loca que tuviste con amigos?", 1),
        ("¿Qué plan simple al aire libre con amigos te llena el corazón?", 1),
        ("¿Hay algún viaje a la naturaleza que querés hacer con amigos y todavía no se dio?", 1),
        ("¿Alguna vez la naturaleza reveló algo de un amigo que no sabías?", 1),
        ("¿Cuál es el clima ideal para compartir con tus amigos?", 1),
        ("¿Qué parte de tu personalidad aparece más claramente cuando estás en la naturaleza con amigos?", 1),
        ("¿Hay algún lugar natural al que querés volver con amigos?", 1),
        ("¿Cómo la conexión con la naturaleza modifica la dinámica de una amistad?", 2),
        ("¿Alguna vez la naturaleza fue el escenario de un conflicto y también de la reconciliación con un amigo?", 2),
        ("¿Qué dice de una amistad la manera en que dos personas reaccionan al mismo entorno natural?", 2),
        ("¿Hay alguna amistad que sea imposible de imaginar sin un lugar natural específico?", 2),
        ("¿Cómo querés que la naturaleza esté presente en las amistades de tu vida futura?", 2),
        ("¿Qué aprendiste sobre un amigo en un entorno natural que no hubieras aprendido en otro lado?", 2),
        ("¿Hay algún lugar natural que sea el escenario de la mejor versión de tus amistades?", 2),
        ("¿Qué lugar natural sería el escenario ideal de una conversación completamente honesta con tu mejor amigo?", 3),
        ("¿Hay alguna amistad que fue transformada por una experiencia en la naturaleza?", 3),
        ("¿Cómo un entorno natural puede hacer visible algo de vos que ocultás en la ciudad?", 3),
        ("¿Qué dice de vos la manera en que te comportás en la naturaleza cuando estás con amigos?", 3),
        ("¿Qué amistad querés construir alrededor de la naturaleza y la aventura?", 3),
        ("¿Hay algún lugar natural que guardes para compartir solo con las personas más cercanas?", 3),
        ("¿Qué parte de tu vínculo con la naturaleza querés transmitirle a tus amigos?", 3),
        ("¿Si tu círculo de amistades fuera un ecosistema, qué sería y cuál es tu rol?", 3),
    ],

    "exs": [
        ("¿Hay algún lugar natural que te recuerde a una relación pasada?", 1),
        ("¿Tenías planes al aire libre que hacías con un ex que extrañás o que dejaste ir con alivio?", 1),
        ("¿Alguna vez tuviste una cita o momento especial en la naturaleza con un ex?", 1),
        ("¿Hay alguna estación del año que te remita a una relación pasada?", 1),
        ("¿Qué lugar natural tuvo un significado especial en alguna relación tuya pasada?", 1),
        ("¿Hay algún lugar en la naturaleza al que no volviste desde que terminó una relación?", 1),
        ("¿Algún olor, sonido o imagen de la naturaleza te recuerda a alguien con quien estuviste?", 1),
        ("¿Qué actividad al aire libre asociás con una relación pasada?", 1),
        ("¿Alguna vez usaste la naturaleza para procesar una ruptura?", 1),
        ("¿Hubo algún viaje a un lugar natural que fue el punto de quiebre de una relación?", 1),
        ("¿Qué tipo de entorno natural preferías compartir con tus ex y qué dice eso de la relación?", 1),
        ("¿Hay algún lugar natural que ahora sentís como tuyo después de haber sido de una pareja?", 1),
        ("¿Alguna vez la naturaleza fue el escenario de una pelea o una reconciliación?", 1),
        ("¿Qué elemento de la naturaleza asociás con el inicio de alguna relación pasada?", 1),
        ("¿Hay algún elemento de la naturaleza que resignificaste después de una ruptura?", 1),
        ("¿La naturaleza fue un espacio de escape o de encuentro en tus relaciones pasadas?", 1),
        ("¿Qué lugar natural sería hoy demasiado cargado de significado para volver con alguien nuevo?", 1),
        ("¿Alguna vez la naturaleza fue testigo de algo que fue un punto de no retorno en una relación?", 1),
        ("¿Qué estación del año te recuerda más a una persona con quien estuviste?", 1),
        ("¿Cómo la relación con la naturaleza de un ex influía en la dinámica que tenían?", 1),
        ("¿Cómo usaste la naturaleza para procesar el dolor de una ruptura?", 2),
        ("¿Hay algún lugar natural que todavía guardás como tuyo aunque lo compartiste con alguien que ya no está?", 2),
        ("¿Qué aprendiste sobre una relación pasada al observar cómo tu ex se relacionaba con la naturaleza?", 2),
        ("¿Alguna experiencia en la naturaleza con un ex te cambió de manera que todavía sentís hoy?", 2),
        ("¿Qué lugar natural te gustaría resignificar con alguien nuevo?", 2),
        ("¿Hay algo de la naturaleza que te haga sentir la presencia o la ausencia de alguien?", 2),
        ("¿Cómo te ayudó la naturaleza a dejar ir algo o a alguien?", 2),
        ("¿Qué lugar natural representa mejor la historia entera de una relación pasada: su comienzo, su auge, su fin?", 3),
        ("¿Hay algún lugar en la naturaleza donde todavía sentís la huella de alguien?", 3),
        ("¿Qué aprendiste sobre vos mirando cómo una relación pasada se relacionaba con la naturaleza?", 3),
        ("¿Cómo un entorno natural específico cambió lo que eras capaz de ser en una relación?", 3),
        ("¿Qué significa para vos que un lugar natural esté para siempre teñido por una persona?", 3),
        ("¿Qué conversación pendiente con alguien del pasado ubicarías en un lugar natural específico?", 3),
        ("¿Cómo la naturaleza te ayudó a ser alguien diferente en tus relaciones actuales?", 3),
        ("¿Qué ciclo natural te ayuda a entender mejor lo que viviste en alguna relación pasada?", 3),
    ],

    "personalidad": [
        ("¿Qué tipo de entorno natural refleja mejor tu personalidad: montaña, mar, bosque, desierto?", 1),
        ("¿Sos más de ciudad o de naturaleza y qué dice eso de vos?", 1),
        ("¿Qué animal te representa mejor y por qué?", 1),
        ("¿Cómo te afecta el clima en el humor cotidiano?", 1),
        ("¿Qué estación del año sos y por qué?", 1),
        ("¿La naturaleza te calma o te aburre?", 1),
        ("¿Qué actividad al aire libre saca la mejor versión de vos?", 1),
        ("¿Cuán importante es para vos tener contacto con la naturaleza en tu vida diaria?", 1),
        ("¿Qué dice de vos la manera en que reaccionás frente a los fenómenos de la naturaleza?", 1),
        ("¿Sos más de plantar, observar, caminar o solo admirar la naturaleza desde lejos?", 1),
        ("¿Qué animal que existe admiras secretamente como modelo de vida?", 1),
        ("¿Hay algún elemento de la naturaleza que sientas que te define?", 1),
        ("¿La lluvia te pone más reflexivo, melancólico, creativo o ansioso?", 1),
        ("¿Qué fenómeno natural te genera más asombro?", 1),
        ("¿Tenés algún hábito relacionado con la naturaleza que sea puramente tuyo?", 1),
        ("¿Preferís un parque urbano, una plaza, o necesitás naturaleza real para recargarte?", 1),
        ("¿Qué ecosistema natural se parece más a cómo funcionás emocionalmente?", 1),
        ("¿Qué planta serías y por qué?", 1),
        ("¿Cómo usás la naturaleza para equilibrarte cuando estás al límite?", 1),
        ("¿Qué tipo de clima es el que mejor va con tu ritmo personal?", 1),
        ("¿Qué aprendiste sobre vos mismo en alguna experiencia intensa en la naturaleza?", 2),
        ("¿Cómo tu relación con la naturaleza refleja algo profundo de quién sos?", 2),
        ("¿Hay algún elemento de la naturaleza que sea tu ancla emocional en momentos difíciles?", 2),
        ("¿Qué dice de tu carácter cómo te comportás cuando la naturaleza te supera?", 2),
        ("¿Qué parte de vos solo aparece en contacto con la naturaleza?", 2),
        ("¿Hay algún animal cuya manera de vivir admirás secretamente como modelo para tu propia vida?", 2),
        ("¿Qué tipo de entorno natural es el que más te conecta con tu intuición?", 2),
        ("¿Si fueras un fenómeno natural, cuál serías y qué dice eso de vos?", 3),
        ("¿Cómo la naturaleza te enseñó algo sobre tu manera de relacionarte con el mundo?", 3),
        ("¿Qué elemento de la naturaleza captura mejor la tensión más importante de tu personalidad?", 3),
        ("¿Qué naturaleza interna tuya querés cultivar que todavía está en semilla?", 3),
        ("¿Hay algún lugar en la naturaleza donde sentís que sos la versión más verdadera de vos?", 3),
        ("¿Qué ciclo de la naturaleza describe mejor cómo vivís emocionalmente?", 3),
        ("¿Cómo te gustaría que la naturaleza esté presente en la identidad que querés construir?", 3),
        ("¿Si la naturaleza pudiera definirte con un solo fenómeno, cuál elegiría y por qué?", 3),
    ],

    "miedos": [
        ("¿Qué fenómeno de la naturaleza te genera miedo o incomodidad?", 1),
        ("¿Tenés miedo a algún animal específico? ¿De dónde viene ese miedo?", 1),
        ("¿Le tenés miedo al mar, a las alturas, a los espacios abiertos o cerrados?", 1),
        ("¿Alguna vez la naturaleza te generó una situación de peligro real?", 1),
        ("¿El miedo a oscuras o en lugares naturales desconocidos cómo te afecta?", 1),
        ("¿Hay algún tipo de clima que te genere ansiedad o miedo?", 1),
        ("¿Alguna vez fuiste a un lugar natural y sentiste que no tenías que estar ahí?", 1),
        ("¿Qué animal te generaría más pánico encontrar de sorpresa?", 1),
        ("¿Le tenés miedo a los desastres naturales? ¿Cómo manejás esa incertidumbre?", 1),
        ("¿Hay algún lugar en la naturaleza al que no irías solo?", 1),
        ("¿Qué te genera más miedo: el silencio total en la naturaleza o el sonido de algo que no podés ver?", 1),
        ("¿Alguna vez superaste un miedo relacionado con la naturaleza?", 1),
        ("¿El instinto de preservación en la naturaleza cómo se activa en vos?", 1),
        ("¿Qué miedo relacionado con la naturaleza te parece irracional pero no podés evitar?", 1),
        ("¿Alguna vez la oscuridad en un lugar natural te generó terror?", 1),
        ("¿Le tenés miedo a quedarte solo en un lugar natural sin referencias?", 1),
        ("¿Qué te genera más miedo en la naturaleza: lo desconocido, lo salvaje, o lo incontrolable?", 1),
        ("¿Hay algún sonido de la naturaleza que te genere ansiedad?", 1),
        ("¿Cómo reaccionás cuando estás en la naturaleza y algo sale mal?", 1),
        ("¿Qué miedos relacionados con el cambio climático son los que más te pesan?", 1),
        ("¿Qué miedo sobre la naturaleza nunca le contaste a nadie porque te parece ridículo?", 2),
        ("¿Alguna vez un miedo a la naturaleza te reveló algo sobre un miedo más profundo?", 2),
        ("¿Hay algo de la naturaleza que admires y también te aterrorice al mismo tiempo?", 2),
        ("¿Cómo el miedo a la naturaleza se mezcla con el respeto que le tenés?", 2),
        ("¿Qué miedo sobre el futuro del planeta te resulta más difícil de procesar?", 2),
        ("¿Hay algún miedo relacionado con la naturaleza que te impida hacer algo que querés?", 2),
        ("¿Qué dice de vos la manera en que enfrentás los elementos de la naturaleza?", 2),
        ("¿Qué miedo profundo sobre tu propia naturaleza humana está disfrazado de miedo al mundo natural?", 3),
        ("¿Cómo la finitud de la naturaleza — el invierno, la muerte, el fin de ciclos — se conecta con tus miedos más existenciales?", 3),
        ("¿Hay algún miedo a la naturaleza que sea en realidad un miedo a algo de vos mismo?", 3),
        ("¿Qué parte de lo salvaje de la naturaleza te asusta porque lo ves también en vos?", 3),
        ("¿Cómo el miedo al cambio climático refleja otros miedos más personales sobre la pérdida y la incertidumbre?", 3),
        ("¿Qué miedo a la naturaleza te conecta con algo de tu historia que todavía no terminaste de entender?", 3),
        ("¿Si la naturaleza fuera un espejo de lo que más temés, qué te estaría mostrando?", 3),
        ("¿Qué cosa de la naturaleza te recuerda a tu propia mortalidad y cómo lo manejás?", 3),
    ],

    "logros": [
        ("¿Hay algún logro tuyo que esté relacionado con la naturaleza o el mundo outdoor?", 1),
        ("¿Alguna vez superaste un reto físico en la naturaleza del que estés orgulloso?", 1),
        ("¿Qué actividad en la naturaleza lograste hacer que antes te parecía imposible?", 1),
        ("¿Alguna vez cuidaste una planta, un jardín, o un animal y lo considerás un logro?", 1),
        ("¿Tuviste algún logro relacionado con el cuidado del ambiente o la sustentabilidad?", 1),
        ("¿Cuál fue la aventura en la naturaleza más exigente que completaste?", 1),
        ("¿Alguna vez llegaste a un lugar natural que requirió un esfuerzo grande de tu parte?", 1),
        ("¿Tuviste algún logro que haya sido posible gracias a pasar tiempo en la naturaleza?", 1),
        ("¿Qué habilidad relacionada con la naturaleza o el entorno desarrollaste y te llena de orgullo?", 1),
        ("¿Alguna vez tu relación con la naturaleza fue la base de un logro profesional o personal?", 1),
        ("¿Qué te enseñó un reto en la naturaleza que no aprendiste en ningún otro lado?", 1),
        ("¿Hay algún logro tuyo que solo fue posible porque te conectaste con algo de la naturaleza?", 1),
        ("¿Qué actividad en la naturaleza te hizo descubrir una capacidad que no sabías que tenías?", 1),
        ("¿Alguna vez completaste algo en la naturaleza que te hizo creer más en vos?", 1),
        ("¿Qué logro relacionado con la naturaleza querés alcanzar en el futuro?", 1),
        ("¿Hay algún lugar natural al que llegaste que representa un logro simbólico para vos?", 1),
        ("¿Qué habilidad de supervivencia o adaptación a la naturaleza te enorgullece?", 1),
        ("¿Cómo un entorno natural fue el contexto de alguno de tus mayores logros personales?", 1),
        ("¿Alguna vez la naturaleza te forzó a dar lo mejor de vos?", 1),
        ("¿Qué meta relacionada con la naturaleza querés cumplir antes de determinada edad?", 1),
        ("¿Cómo los retos en la naturaleza te prepararon para logros en otros ámbitos de tu vida?", 2),
        ("¿Qué logro en la naturaleza cambió tu percepción de lo que sos capaz de hacer?", 2),
        ("¿Hay algún logro relacionado con el entorno natural que te costó más de lo que imaginabas y valió la pena?", 2),
        ("¿Cómo la naturaleza te enseñó sobre la perseverancia y el esfuerzo de maneras que ningún libro podría?", 2),
        ("¿Qué logro en la naturaleza fue en realidad un logro sobre vos mismo?", 2),
        ("¿Cómo la conexión con la naturaleza te ayudó a sostener el esfuerzo en tus logros más importantes?", 2),
        ("¿Qué lugar natural es el escenario del logro que más te costó y más te transformó?", 2),
        ("¿Cuál es el reto en la naturaleza más significativo que todavía querés completar y qué representa para vos?", 3),
        ("¿Qué aprendiste sobre vos en un reto en la naturaleza que cambió cómo encarás los desafíos?", 3),
        ("¿Cómo los ciclos de la naturaleza te ayudaron a entender el proceso detrás de tus logros?", 3),
        ("¿Qué dice de tu carácter la manera en que te relacionás con lo que la naturaleza te exige?", 3),
        ("¿Hay algún logro relacionado con la naturaleza que sentís que todavía no terminaste de procesar?", 3),
        ("¿Qué parte de quien sos hoy existe porque la naturaleza te desafió en algún momento?", 3),
        ("¿Si la naturaleza fuera tu maestra, qué logro te estaría pidiendo que alcances ahora?", 3),
        ("¿Qué logro en la naturaleza querés que sea parte de la historia que los que vienen después cuenten de vos?", 3),
    ],

    "sinFiltro": [
        ("¿Alguna vez tuviste ganas de hacer algo completamente salvaje o instintivo en la naturaleza?", 1),
        ("¿Qué cosa habrías hecho en la naturaleza si no existieran las reglas sociales?", 1),
        ("¿Alguna vez te bañaste en algún lugar donde no debías?", 1),
        ("¿Qué cosa hiciste en la naturaleza de la que te arrepentís o que fue un poco imprudente?", 1),
        ("¿Alguna vez tu lado animal salió en un momento en la naturaleza?", 1),
        ("¿Qué harías si estuvieras completamente solo en la naturaleza sin que nadie lo supiera?", 1),
        ("¿Alguna vez la naturaleza te hizo actuar de manera que te sorprendió a vos mismo?", 1),
        ("¿Qué cosa de la naturaleza te genera una atracción que no podés explicar del todo?", 1),
        ("¿Alguna vez tuviste una experiencia en la naturaleza que fue límite y que volverías a hacer?", 1),
        ("¿Qué lado tuyo más primitivo o instintivo aparece en la naturaleza?", 1),
        ("¿Alguna vez la naturaleza fue el escenario de algo que preferirías que nadie sepa?", 1),
        ("¿Qué cosa de la naturaleza te hace sentir más vivo aunque también te asuste?", 1),
        ("¿Alguna vez tomaste una decisión impulsiva en la naturaleza de la que no te arrepentís?", 1),
        ("¿Qué regla social te parece más tonta cuando estás en contacto con la naturaleza?", 1),
        ("¿Qué cosa harías en la naturaleza que en la ciudad jamás harías?", 1),
        ("¿Alguna vez tuviste una experiencia en la naturaleza que no le contaste a nadie por vergüenza?", 1),
        ("¿Qué cosa de la naturaleza te conecta con algo de vos que normalmente reprimís?", 1),
        ("¿Alguna vez la naturaleza te liberó de algo que en la ciudad sentís como una carga?", 1),
        ("¿Qué harías si pudieras vivir un mes completamente en la naturaleza sin responsabilidades?", 1),
        ("¿Cuánto de tu lado salvaje o impredecible sale cuando estás en la naturaleza?", 1),
        ("¿Qué hace la naturaleza que vuelva a conectarte con la parte más honesta y sin filtros de vos?", 2),
        ("¿Hay algo de lo que la naturaleza te recuerda que preferirías ignorar sobre vos mismo?", 2),
        ("¿Qué comportamiento tuyo en la naturaleza sería muy distinto a cómo te comportás en sociedad?", 2),
        ("¿Alguna vez la naturaleza te hizo enfrentar algo de vos que normalmente escondés?", 2),
        ("¿Qué dice de vos la manera más honesta en que usás la naturaleza: para escapar, para crecer, para hacer cosas que no harías en otro lado?", 2),
        ("¿Cómo la naturaleza te recuerda que sos un animal también?", 2),
        ("¿Qué parte de vos que normalmente controlás se libera en la naturaleza?", 2),
        ("¿Qué tan seguido fantaseás con abandonar la vida estructurada e irte a vivir a la naturaleza?", 3),
        ("¿Qué parte salvaje o instintiva de vos mismo creés que reprimís demasiado?", 3),
        ("¿Si pudieras ser completamente sin filtros en la naturaleza, qué quedaría de vos que nadie conoce?", 3),
        ("¿Cuánto de lo que llamás 'civilización' creés que en realidad va en contra de tu naturaleza más profunda?", 3),
        ("¿Qué aprendiste sobre vos en un momento en que la naturaleza te obligó a ser completamente honesto?", 3),
        ("¿Si tuvieras que elegir entre una vida cómoda en la ciudad o una vida libre pero dura en la naturaleza, qué elegiría la versión más honesta de vos?", 3),
        ("¿Qué deseo o impulso que la civilización te pide reprimir sería completamente válido en la naturaleza?", 3),
        ("¿Qué te revela la naturaleza sobre la parte de vos que más te cuesta aceptar?", 3),
    ],
}


def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]


def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS27:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS27[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")


if __name__ == "__main__":
    main()
