#!/usr/bin/env python3
"""Batch 21 - childhood dreams vs. adult reality, nostalgia, regret, wonder."""
import json

ADDITIONS21 = {
    "infancia": [
        ("¿Qué querías ser de grande cuando eras chico y por qué ya no lo sos?", 1),
        ("¿Cuál era tu juego favorito de la infancia y qué dice de quien sos hoy?", 1),
        ("¿Qué cosa de la infancia extrañás tanto que a veces querés volver?", 1),
        ("¿Cuál fue el primer sueño que abandonaste y cómo te sentiste cuando lo dejaste ir?", 1),
        ("¿Qué hacías de chico que te daba una alegría pura que ya no encontrás igual?", 1),
        ("¿Cuál era tu lugar favorito de la infancia y qué pasó con él?", 1),
        ("¿Qué persona de tu infancia te marcó sin saber que lo hacía?", 1),
        ("¿Qué cosa creías de chico que resultó ser completamente distinta?", 1),
        ("¿Cuál era tu mayor miedo de la infancia y ya lo superaste?", 1),
        ("¿Qué cosa de adulto te hubiera encantado tener de chico?", 1),
        ("¿Qué recuerdo de infancia te genera nostalgia cada vez que aparece?", 1),
        ("¿Cuál fue la primera vez que entendiste que ser adulto no era lo que imaginabas?", 1),
        ("¿Qué sueño de la infancia todavía cargás aunque nunca lo hayas nombrado?", 1),
        ("¿Qué cosa de tu infancia no te gustaba en ese momento y hoy valorás?", 1),
        ("¿Cuál fue el primer momento en que sentiste que la infancia terminó?", 1),
        ("¿Qué te decían de grande los adultos que hoy sabés que era mentira?", 1),
        ("¿Qué juguete o posesión de tu infancia daría todo por recuperar?", 1),
        ("¿Qué hábito o ritual de tu infancia todavía mantenés sin admitirlo?", 1),
        ("¿Cuál fue el primer logro de tu infancia que recordás con orgullo?", 1),
        ("¿Qué le dirías al niño que fuiste si pudieras encontrártelo?", 1),
        ("¿Qué parte de la infancia sentís que nunca terminó en vos?", 1),
        ("¿Cuál fue el primer momento en que creíste que el mundo era injusto?", 1),
        ("¿Qué cosa hacías de chico con una concentración que hoy ya no tenés?", 1),
        ("¿Cuál era tu fantasía más grande de chico y qué tan lejos estás de haberla cumplido?", 1),
        ("¿Qué cosa de tu infancia fue difícil pero te hizo quien sos?", 1),
        ("¿Qué versión de vos de la infancia extrañás más?", 1),
        ("¿Cuál fue la primera decepción que recordás claramente de tu infancia?", 1),
        ("¿Qué cosa de adulto sentís que traicionó al niño que fuiste?", 1),
        ("¿Qué recuerdo de infancia compartido con alguien ya no existe porque ese alguien tampoco está?", 1),
        ("¿Qué pregunta hacías de chico que de adulto dejaste de hacer?", 1),
        ("¿Cuál era el sueño de tu infancia más absurdo que, con suerte, todavía te hace sonreír?", 2),
        ("¿Qué hiciste de adulto que el niño que fuiste jamás hubiera aprobado?", 2),
        ("¿Cuándo fue la primera vez que sentiste que la realidad era más complicada que lo que imaginabas de chico?", 2),
        ("¿Qué promesa te hiciste en la infancia que rompiste sin darte cuenta?", 2),
        ("¿Cuál fue el primer momento en que elegiste la seguridad sobre el sueño?", 2),
        ("¿Qué cosa de tu infancia te generó una herida que todavía sentís a veces?", 2),
        ("¿Qué te arrepentís de no haber aprovechado más en tu infancia?", 2),
        ("¿Cuándo fue la primera vez que sentiste vergüenza de algo que antes te llenaba de orgullo?", 2),
        ("¿Qué versión de vos mismo de la infancia te parece más genuina y por qué la perdiste?", 2),
        ("¿Cuál fue la primera vez que la magia del mundo se rompió y no pudo recomponerse igual?", 2),
        ("¿Qué soñabas de chico con una certeza que hoy ya no tenés?", 2),
        ("¿Qué aprendiste de adulto que hace que mires tu infancia con pena?", 2),
        ("¿Qué parte de tu infancia fue una mentira bien intencionada que hoy te cuesta perdonar?", 2),
        ("¿Cuándo fue la primera vez que sentiste que el tiempo era irrecuperable?", 3),
        ("¿Qué sueño de la infancia todavía duele porque nunca lo admitiste ni lo intentaste?", 3),
        ("¿Cuándo fue la primera vez que elegiste el miedo sobre la maravilla y no podés deshacerlo?", 3),
        ("¿Qué cosa de tu infancia fue tan hermosa que a veces preferís no recordarla para que no duela?", 3),
        ("¿Qué versión adulta de vos hubiera decepcionado más profundamente al niño que fuiste?", 3),
        ("¿Cuándo fue la primera vez que entendiste que algunos sueños se terminan para siempre?", 3),
        ("¿Qué cosa de la infancia perdiste y nunca vas a poder recuperar ni con todo el dinero del mundo?", 3),
    ],

    "futuro": [
        ("¿Qué parte del futuro te genera más curiosidad que miedo?", 1),
        ("¿Qué logro soñás alcanzar que todavía no contaste a nadie?", 1),
        ("¿Cómo imaginabas tu vida a esta edad cuando eras chico?", 1),
        ("¿Qué cosa del futuro te entusiasma aunque no sepas cómo va a pasar?", 1),
        ("¿Qué versión futura de vos te gustaría que te pudiera ver ahora mismo?", 1),
        ("¿Qué meta del futuro te da más miedo empezar que no lograr?", 1),
        ("¿Qué querés que la gente diga de vos cuando ya no estés?", 1),
        ("¿Qué cosa del futuro imaginabas de chico que ya descartaste?", 1),
        ("¿Qué decisión del presente va a ser clave para el futuro que querés?", 1),
        ("¿Qué lugar del mundo querés visitar antes de que sea demasiado tarde?", 1),
        ("¿Qué habilidad querés desarrollar que hoy todavía no empezaste?", 1),
        ("¿Cómo querés que sea tu vida dentro de diez años si todo saliera bien?", 1),
        ("¿Qué cosa del futuro te pone nervioso aunque sepas que va a estar bien?", 1),
        ("¿Qué tipo de persona querés ser que todavía no sos del todo?", 1),
        ("¿Qué sueño del futuro te parece tan grande que a veces preferís no pensarlo?", 1),
        ("¿Qué cosa del futuro te genera más ganas de vivir mucho tiempo?", 1),
        ("¿Qué promesa te hiciste sobre el futuro que todavía no rompiste?", 1),
        ("¿Qué parte de tu futuro depende enteramente de vos y eso te asusta o te libera?", 1),
        ("¿Qué cosa del futuro querés que tu familia recuerde cuando ya no estés?", 1),
        ("¿Cuál es el sueño de futuro más pequeño que nadie sabe que tenés?", 1),
        ("¿Qué pensabas que iba a pasar en tu vida para esta edad que todavía no pasó?", 1),
        ("¿Qué parte de tu futuro le robarías al tiempo si pudieras?", 1),
        ("¿Qué versión tuya del futuro te da más orgullo imaginar?", 1),
        ("¿Qué cosa del futuro te daría alivio saber hoy, aunque no puedas cambiarlo?", 1),
        ("¿Qué ideal de vida tenías de chico que ya no te importa y uno que todavía sí?", 1),
        ("¿Qué cosa dejaste para el futuro que ya era hora de que empezaras antes?", 1),
        ("¿Qué sueño del futuro cargás con una mezcla de esperanza y vergüenza?", 1),
        ("¿Qué parte del futuro te genera nostalgia del presente aunque no haya pasado todavía?", 1),
        ("¿Cuándo fue la primera vez que pensaste en tu propia vejez y cómo te sentiste?", 1),
        ("¿Qué le preguntarías a la versión de vos de dentro de veinte años?", 1),
        ("¿Qué cosa del futuro que imaginabas ya se cumplió y fue mejor o peor de lo esperado?", 2),
        ("¿Qué sueño del futuro te parece legítimo y cuál te parece que ya deberías haber dejado ir?", 2),
        ("¿Cuándo fue la primera vez que sentiste que el futuro no era infinito?", 2),
        ("¿Qué cosa del futuro te da más miedo admitir que querés?", 2),
        ("¿Qué versión del futuro te generaría más arrepentimiento no haber intentado?", 2),
        ("¿Cuándo fue la primera vez que cambiaste lo que querías del futuro y no por elección?", 2),
        ("¿Qué sueño de futuro renunciaste por alguien más y cómo lo llevas?", 2),
        ("¿Qué cosa del futuro que imaginabas de chico ya es imposible y cómo te reconciliaste con eso?", 2),
        ("¿Qué parte de tu futuro tiene que ver con reparar algo del pasado?", 2),
        ("¿Qué le robarías al tiempo si pudieras: más pasado o más futuro?", 2),
        ("¿Qué cosa del futuro querés tanto que te da miedo que no pase?", 2),
        ("¿Qué sueño futuro guardás tan privado que ni vos mismo lo pronunciás seguido?", 2),
        ("¿Cuándo fue la primera vez que el futuro te dio vértigo en lugar de esperanza?", 2),
        ("¿Qué parte del futuro que querés implica dejar ir algo del presente?", 3),
        ("¿Qué sueño de futuro te da más vergüenza admitir porque parece demasiado grande para vos?", 3),
        ("¿Cuándo fue la primera vez que sentiste que el futuro era tuyo y cuándo dejaste de sentir eso?", 3),
        ("¿Qué cosa del futuro imaginás que hoy se parece más a una condena que a una promesa?", 3),
        ("¿Cuándo fue la primera vez que pensaste que no había suficiente tiempo para todo lo que querías?", 3),
        ("¿Qué versión del futuro te generaría más alivio y cuál más tristeza?", 3),
        ("¿Qué cosa del futuro sabés que querés pero te aterroriza admitir porque implicaría cambiar todo?", 3),
        ("¿Cuándo fue la primera vez que el peso del futuro fue más grande que la ilusión que te generaba?", 3),
    ],

    "amor": [
        ("¿Cómo imaginabas el amor cuando eras chico y qué tan distinto es lo que viviste?", 1),
        ("¿Cuál es el gesto romántico más pequeño que recordás con más ternura?", 1),
        ("¿Qué cosa del amor te costó más aprender que no era como creías?", 1),
        ("¿Cuál fue la primera vez que el amor te sorprendió en el mejor sentido?", 1),
        ("¿Qué cosa del amor te generaba miedo de chico que ahora entendés diferente?", 1),
        ("¿Cuándo fue la primera vez que amaste sin esperar nada a cambio?", 1),
        ("¿Qué versión del amor que imaginabas ya no te interesa?", 1),
        ("¿Cuál fue el primer momento en que te diste cuenta de que alguien te amaba de verdad?", 1),
        ("¿Qué cosa del amor te parece más hermosa ahora que cuando eras más joven?", 1),
        ("¿Cuál fue la primera vez que el amor cambió algo en vos para siempre?", 1),
        ("¿Qué tipo de amor soñabas tener de chico que nunca llegó de esa forma?", 1),
        ("¿Cuándo fue la primera vez que preferiste ser honesto en el amor antes que protegerte?", 1),
        ("¿Qué cosa del amor que creías necesitar resultó no serlo?", 1),
        ("¿Cuándo fue la primera vez que el amor te costó más de lo que esperabas y valió igual?", 1),
        ("¿Qué versión de vos en el amor te genera más nostalgia?", 1),
        ("¿Qué imaginabas que iba a ser el amor para toda la vida y cómo cambió esa idea?", 1),
        ("¿Cuándo fue la primera vez que el amor te enseñó algo que ninguna otra cosa podría?", 1),
        ("¿Qué cosa del amor te parece más complicada ahora que antes?", 1),
        ("¿Cuál es el acto de amor más cotidiano que valorás profundamente?", 1),
        ("¿Qué cosa del amor que tenés o tuviste te genera más gratitud?", 1),
        ("¿Qué sueño romántico de la infancia todavía te acompaña aunque lo hayas racionalizado?", 1),
        ("¿Cuándo fue la primera vez que amaste algo de alguien que antes te molestaba?", 1),
        ("¿Qué parte del amor real te parece más hermosa que el amor de cuento?", 1),
        ("¿Cuándo fue la primera vez que el amor fue más fácil de sentir que de expresar?", 1),
        ("¿Qué cosa del amor te genera nostalgia aunque el amor todavía esté?", 1),
        ("¿Qué romanticismo de la infancia todavía guardás aunque parezca ingenuo?", 1),
        ("¿Cuándo fue la primera vez que el amor no fue suficiente y tuviste que aceptarlo?", 1),
        ("¿Qué forma de amor que no imaginabas recibiste y fue la más inesperada?", 1),
        ("¿Qué cosa del amor te generaba vergüenza admitir que necesitabas?", 1),
        ("¿Cuándo fue la primera vez que el amor fue exactamente lo que necesitabas aunque no lo pidieras?", 1),
        ("¿Qué sueño de amor nunca se cumplió y cómo lo cerras o no lo cerrás?", 2),
        ("¿Cuándo fue la primera vez que elegiste el amor sobre la comodidad?", 2),
        ("¿Qué version del amor perdiste que todavía a veces duele?", 2),
        ("¿Qué cosa del amor que imaginabas de chico resultó ser más complicada de lo que parecía?", 2),
        ("¿Cuándo fue la primera vez que el amor te cambió de una forma que no podías deshacer?", 2),
        ("¿Qué te enseñó el amor que ningún otro maestro te pudo enseñar?", 2),
        ("¿Cuándo fue la primera vez que el amor te hizo mejor y cuándo te hizo peor?", 2),
        ("¿Qué parte del amor que soñabas de chico todavía buscás aunque no lo reconozcas?", 2),
        ("¿Cuándo fue la primera vez que el amor fue más un acto de voluntad que un sentimiento?", 2),
        ("¿Qué cosa del amor que viviste te genera más arrepentimiento?", 2),
        ("¿Cuándo fue la primera vez que el amor que sentías no alcanzó para sostenerlo?", 2),
        ("¿Qué versión del amor nunca alcanzaste y cómo convivís con eso?", 2),
        ("¿Cuándo fue la primera vez que el amor te pidió que cambiaras algo de vos y lo hiciste?", 2),
        ("¿Qué parte del amor que soñabas todavía la extrañás aunque ya no querrías volver?", 3),
        ("¿Cuándo fue la primera vez que el amor te mostró lo peor de vos?", 3),
        ("¿Qué cosa del amor que nunca tuviste todavía te duele más de lo que admitís?", 3),
        ("¿Cuándo fue la primera vez que elegiste no amar por protegerte y cómo te sentiste después?", 3),
        ("¿Qué versión del amor que viviste fue la que más te costó dejar ir?", 3),
        ("¿Cuándo fue la primera vez que el amor te hizo hacer algo que nunca pensabas que ibas a hacer?", 3),
        ("¿Qué amor de tu vida cambió tan profundamente quien sos que sin él serías otra persona?", 3),
        ("¿Qué cosa del amor que nunca dijiste todavía pesa más de lo que querías?", 3),
    ],

    "familia": [
        ("¿Cómo imaginabas tu familia ideal de chico y qué tan cerca o lejos estás de eso?", 1),
        ("¿Cuál es el recuerdo de infancia con tu familia que más te genera nostalgia?", 1),
        ("¿Qué tradición familiar te gustaría recuperar o crear?", 1),
        ("¿Cuándo fue la primera vez que entendiste que tus padres también eran personas imperfectas?", 1),
        ("¿Qué cosa de tu familia de origen llevo con orgullo y cuál con más ambivalencia?", 1),
        ("¿Cuál fue la primera vez que la familia te decepcionó y cómo lo procesaste?", 1),
        ("¿Qué rasgo heredaste de tu familia que al principio te molestaba y ahora valorás?", 1),
        ("¿Cuándo fue la primera vez que protegiste a alguien de tu familia?", 1),
        ("¿Qué cosa de tu infancia familiar extrañás que ya no existe?", 1),
        ("¿Cuál fue el primer recuerdo con tu familia que fue puro y completo?", 1),
        ("¿Qué imaginabas que iba a ser tu relación con tus padres cuando fueras adulto?", 1),
        ("¿Cuándo fue la primera vez que elegiste tu familia por sobre otra cosa?", 1),
        ("¿Qué cosa aprendiste de tu familia de origen que no querés repetir?", 1),
        ("¿Cuál fue la primera vez que te sentiste parte de algo más grande que vos en tu familia?", 1),
        ("¿Qué miembro de tu familia fue el más sorprendente para vos?", 1),
        ("¿Cuándo fue la primera vez que tu familia no entendió algo tuyo y cómo lo viviste?", 1),
        ("¿Qué cosa de tu infancia familiar te parece que formó lo mejor de vos?", 1),
        ("¿Cuál fue la primera vez que le agradeciste algo a alguien de tu familia de corazón?", 1),
        ("¿Qué cosa aprendiste de observar a tu familia que nadie te enseñó explícitamente?", 1),
        ("¿Cuándo fue la primera vez que elegiste hablar en lugar de callar dentro de tu familia?", 1),
        ("¿Qué parte de tu historia familiar todavía no conocés bien y sentís curiosidad?", 1),
        ("¿Cuál era la dinámica familiar de la infancia que más te marcó?", 1),
        ("¿Qué cosa de tu familia imaginabas distinta cuando eras chico?", 1),
        ("¿Cuándo fue la primera vez que sentiste que tu familia te veía de verdad?", 1),
        ("¿Qué cosa de tu familia quisiste cambiar y eventualmente aceptaste?", 1),
        ("¿Cuál fue la primera vez que sentiste que tu familia necesitaba algo de vos que no sabías dar?", 1),
        ("¿Qué patrón familiar reconocés en vos que no querías repetir y sin embargo aparece?", 1),
        ("¿Cuándo fue la primera vez que entendiste a uno de tus padres de una manera que antes no podías?", 1),
        ("¿Qué cosa de tu familia dejaste de idealizar y cómo fue ese proceso?", 1),
        ("¿Cuál fue la primera vez que la familia fue exactamente el sostén que necesitabas?", 1),
        ("¿Qué imaginabas que iba a ser tu relación con tu familia y cómo es en realidad?", 2),
        ("¿Cuándo fue la primera vez que tuviste que elegir entre lo que tu familia quería y lo que vos querías?", 2),
        ("¿Qué herida familiar todavía cargás que no se termina de cerrar?", 2),
        ("¿Cuándo fue la primera vez que perdonaste algo de tu familia que parecía imperdonable?", 2),
        ("¿Qué cosa de tu familia que te dolió te formó de una manera que no podrías haber imaginado?", 2),
        ("¿Cuándo fue la primera vez que tu familia te pidió algo que no podías dar y cómo lo manejaste?", 2),
        ("¿Qué parte de tu historia familiar todavía te pesa más de lo que admitís?", 2),
        ("¿Cuándo fue la primera vez que viste a uno de tus padres vulnerables y cómo cambió tu relación?", 2),
        ("¿Qué cosa de tu familia que querías que fuera distinta ya aceptaste que no va a cambiar?", 2),
        ("¿Cuándo fue la primera vez que tu familia te mostró algo de vos que no sabías que estaba?", 2),
        ("¿Qué promesa no dicha hacés a tu familia aunque nunca la pronuncies?", 2),
        ("¿Cuándo fue la primera vez que la familia fue un peso en lugar de un sostén y cómo lo viviste?", 2),
        ("¿Qué cosa de tu familia de origen querés transmitir y cuál definitivamente no?", 2),
        ("¿Qué herida de tu historia familiar todavía afecta tus relaciones más de lo que querés admitir?", 3),
        ("¿Cuándo fue la primera vez que tu familia te hizo sentir que no eras suficiente y cómo lo superaste?", 3),
        ("¿Qué cosa de tu familia que idealizabas de chico fue lo que más te costó ver como era en realidad?", 3),
        ("¿Cuándo fue la primera vez que elegiste romper un patrón familiar consciente y dolorosamente?", 3),
        ("¿Qué cosa de tu relación con tu familia todavía tiene pendientes que no sabés si van a cerrarse?", 3),
        ("¿Cuándo fue la primera vez que amaste a alguien de tu familia a pesar de todo y no gracias a todo?", 3),
        ("¿Qué parte de tu historia familiar preferís no contar y por qué la guardás?", 3),
        ("¿Cuándo fue la primera vez que entendiste que tu familia hacía lo que podía y eso tuvo que ser suficiente?", 3),
    ],

    "amistades": [
        ("¿Cómo imaginabas la amistad de chico y en qué se parece o no a lo que tenés?", 1),
        ("¿Cuál fue tu primera amistad real y qué pasó con ella?", 1),
        ("¿Qué amigo de la infancia extrañás aunque hayas perdido el contacto?", 1),
        ("¿Cuándo fue la primera vez que una amistad te decepcionó y cómo lo procesaste?", 1),
        ("¿Qué tipo de amigo eras de chico y qué tan distinto sos ahora?", 1),
        ("¿Cuándo fue la primera vez que un amigo estuvo cuando más lo necesitabas?", 1),
        ("¿Qué cosa de las amistades de la infancia no podés reproducir en la adultez?", 1),
        ("¿Cuál fue la amistad que más duró sin que ninguno lo planificara?", 1),
        ("¿Qué cosa de una amistad de la infancia todavía te hace reír cuando la recordás?", 1),
        ("¿Cuándo fue la primera vez que elegiste mantener una amistad aunque costara trabajo?", 1),
        ("¿Qué amigo te enseñó algo sobre vos mismo que no habías visto?", 1),
        ("¿Cuál fue la primera vez que una amistad terminó y cómo lo llevaste?", 1),
        ("¿Qué cosa de una amistad te genera nostalgia aunque todavía sigan siendo amigos?", 1),
        ("¿Cuándo fue la primera vez que un amigo te dijo algo difícil que necesitabas escuchar?", 1),
        ("¿Qué amigo tuyo te cambió sin que lo supiera?", 1),
        ("¿Cuándo fue la primera vez que sintiste que la distancia no había cambiado una amistad?", 1),
        ("¿Qué cosa de la amistad aprendiste con el tiempo que no entendías de joven?", 1),
        ("¿Cuándo fue la primera vez que un amigo te sorprendió completamente?", 1),
        ("¿Qué amistad de la infancia marcó quién sos hoy sin que lo hayas notado?", 1),
        ("¿Cuál era la aventura favorita que compartías con tu mejor amigo de la infancia?", 1),
        ("¿Qué cosa de una amistad pasada extrañás más que la persona misma?", 1),
        ("¿Cuándo fue la primera vez que le pediste perdón a un amigo de verdad?", 1),
        ("¿Qué tipo de amigo querías ser de grande cuando eras chico?", 1),
        ("¿Cuándo fue la primera vez que una amistad te mostró que podías contar con alguien?", 1),
        ("¿Qué cosa de tus amistades actuales te genera nostalgia del futuro?", 1),
        ("¿Cuándo fue la primera vez que mantuviste una amistad a pesar de algo que los separaba?", 1),
        ("¿Qué cosa aprendiste de una amistad que no aprendiste de ninguna relación de pareja?", 1),
        ("¿Cuándo fue la primera vez que la amistad fue más importante que la razón?", 1),
        ("¿Qué amigo nunca iba a estar más y cómo extrañás esa amistad específica?", 1),
        ("¿Cuándo fue la primera vez que una amistad te hizo sentir que pertenecías?", 1),
        ("¿Qué amistad perdiste que hoy te arrepentís de no haber cuidado más?", 2),
        ("¿Cuándo fue la primera vez que una amistad te decepcionó tan profundamente que cambiaste algo en vos?", 2),
        ("¿Qué cosa de las amistades que tuviste de joven no pudiste repetir de adulto y te genera pena?", 2),
        ("¿Cuándo fue la primera vez que decidiste terminar una amistad y cómo viviste esa decisión?", 2),
        ("¿Qué cosa de una amistad que perdiste todavía te afecta más de lo que esperabas?", 2),
        ("¿Cuándo fue la primera vez que una amistad te enseñó algo doloroso sobre vos mismo?", 2),
        ("¿Qué cosa de las amistades de la infancia era más simple y eso lo hace más hermoso o más ingenuo?", 2),
        ("¿Cuándo fue la primera vez que una amistad te pidió más de lo que podías dar?", 2),
        ("¿Qué amigo te conocía tan bien que te daba miedo lo que sabía?", 2),
        ("¿Cuándo fue la primera vez que una amistad terminó sin pelea y eso fue lo más triste?", 2),
        ("¿Qué amistad marcó un antes y un después en tu vida que nadie más nota?", 2),
        ("¿Cuándo fue la primera vez que la amistad fue más difícil que el amor?", 2),
        ("¿Qué cosa de una amistad que perdiste todavía aparece en sueños o en pequeños momentos?", 2),
        ("¿Qué amistad que nunca terminaste de cerrar todavía pesa más de lo que admitís?", 3),
        ("¿Cuándo fue la primera vez que traicionaste a un amigo aunque sea de manera pequeña y cómo lo cargás?", 3),
        ("¿Qué cosa de las amistades de la infancia fue tan pura que a veces duele recordarla?", 3),
        ("¿Cuándo fue la primera vez que sentiste soledad dentro de una amistad?", 3),
        ("¿Qué amigo nunca supo cuánto significó para vos y hoy ya es imposible decírselo?", 3),
        ("¿Cuándo fue la primera vez que una amistad reveló algo de vos que preferirías no haber visto?", 3),
        ("¿Qué amistad fue tan intensa que cuando terminó fue casi como un duelo?", 3),
        ("¿Cuándo fue la primera vez que preferiste la soledad antes que una amistad que te hacía mal?", 3),
    ],

    "exs": [
        ("¿Cuándo fue la primera vez que te enamoraste de verdad y qué tan distinto fue de lo que imaginabas?", 1),
        ("¿Qué cosa de una relación pasada extrañás que no tiene que ver con la persona?", 1),
        ("¿Cuándo fue la primera vez que una relación terminó y supiste que era lo correcto?", 1),
        ("¿Qué aprendiste de tu primera relación que no sabías que ibas a necesitar?", 1),
        ("¿Cuál fue la primera vez que cortaste con alguien y te sentiste libre?", 1),
        ("¿Qué cosa de una relación del pasado todavía te genera ternura aunque ya no esté?", 1),
        ("¿Cuándo fue la primera vez que elegiste quedarte en una relación aunque no fuera perfecta?", 1),
        ("¿Qué momento de una relación pasada recordás con más cariño?", 1),
        ("¿Cuándo fue la primera vez que el final de una relación abrió algo mejor?", 1),
        ("¿Qué cosa de una relación pasada formó algo de lo que sos hoy?", 1),
        ("¿Cuándo fue la primera vez que el amor no fue suficiente para sostener una relación?", 1),
        ("¿Qué cosa imaginabas que iba a ser distinto en las relaciones y resultó igual?", 1),
        ("¿Cuándo fue la primera vez que una relación te mostró algo de vos que no habías visto?", 1),
        ("¿Qué ex recordás con el mayor agradecimiento aunque haya terminado mal?", 1),
        ("¿Cuándo fue la primera vez que el inicio de una relación fue exactamente como lo soñabas?", 1),
        ("¿Qué cosa de las relaciones pasadas te generó la mayor nostalgia?", 1),
        ("¿Cuándo fue la primera vez que elegiste no volver aunque la extrañaras?", 1),
        ("¿Qué tipo de relación imaginabas tener de grande cuando eras chico?", 1),
        ("¿Cuándo fue la primera vez que el fin de una relación fue un alivio que no esperabas?", 1),
        ("¿Qué cosa de una relación pasada te enseñó más sobre vos mismo?", 1),
        ("¿Cuándo fue la primera vez que cerrar una relación fue un acto de amor?", 1),
        ("¿Qué momento de una relación pasada cambió la dirección de tu vida sin que lo planearas?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que alguien no era lo que pensabas?", 1),
        ("¿Qué cosa de una relación del pasado que no funcionó te sigue pareciendo hermosa?", 1),
        ("¿Cuándo fue la primera vez que el amor de una relación fue real aunque no fuera suficiente?", 1),
        ("¿Qué promesa hiciste en una relación que no pudiste mantener y cómo lo cargás?", 1),
        ("¿Cuándo fue la primera vez que una relación terminó antes de que estuvieras listo?", 1),
        ("¿Qué cosa de una relación pasada todavía te parece que hiciste bien?", 1),
        ("¿Cuándo fue la primera vez que la distancia fue el fin de algo que podría haber seguido?", 1),
        ("¿Qué versión de vos en una relación del pasado extrañás aunque no quieras volver?", 1),
        ("¿Qué relación del pasado que terminó mal tardaste más en cerrar y por qué?", 2),
        ("¿Cuándo fue la primera vez que una relación te hizo perder algo de vos mismo?", 2),
        ("¿Qué cosa que hiciste en una relación pasada todavía te pesa?", 2),
        ("¿Cuándo fue la primera vez que el final de una relación fue más duro de lo que esperabas?", 2),
        ("¿Qué ex te hizo ver algo de vos que no querías ver y cómo lo procesaste?", 2),
        ("¿Cuándo fue la primera vez que una relación te dejó una herida que tardó mucho en cerrarse?", 2),
        ("¿Qué cosa de una relación pasada que idealizaste con el tiempo fue más complicada de lo que creés?", 2),
        ("¿Cuándo fue la primera vez que una relación te pidió que fueras alguien que no eras?", 2),
        ("¿Qué relación del pasado tiene pendientes que nunca se terminaron de resolver?", 2),
        ("¿Cuándo fue la primera vez que elegiste el dolor de terminar antes que el dolor de seguir?", 2),
        ("¿Qué ex tuyo/a fue el que más te hizo crecer aunque la relación haya sido difícil?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que repetías un patrón en tus relaciones?", 2),
        ("¿Qué cosa no dijiste en una relación que hoy daría todo por haber dicho?", 2),
        ("¿Qué relación del pasado te hizo dudar más de vos mismo y cómo lo superaste?", 3),
        ("¿Cuándo fue la primera vez que una relación te hizo hacer algo de lo que te arrepentís?", 3),
        ("¿Qué relación del pasado todavía tiene una pregunta sin respuesta que preferís no hacerte?", 3),
        ("¿Cuándo fue la primera vez que el amor que sentías no te alcanzó para ser quien esa persona necesitaba?", 3),
        ("¿Qué cosa de una relación pasada reveló algo de vos que no te gusta pero es verdad?", 3),
        ("¿Cuándo fue la primera vez que una relación terminó y no supiste si volverte a fiar del amor?", 3),
        ("¿Qué relación del pasado tiene una versión de vos que preferirías no recordar?", 3),
        ("¿Cuándo fue la primera vez que el peso de una relación terminada fue más pesado que la relación misma?", 3),
    ],

    "personalidad": [
        ("¿Qué rasgo tuyo de la infancia todavía está intacto aunque el mundo haya cambiado?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que eras diferente a los demás y cómo lo viviste?", 1),
        ("¿Qué cosa de tu forma de ser que antes te avergonzaba ahora celebrás?", 1),
        ("¿Cuál fue el primer momento en que sentiste que eras exactamente quien querías ser?", 1),
        ("¿Qué versión tuya de la infancia extrañás y cuál definitivamente no?", 1),
        ("¿Cuándo fue la primera vez que elegiste ser vos aunque costara?", 1),
        ("¿Qué rasgo tuyo fue incomprendido de chico y hoy es un activo?", 1),
        ("¿Cuál fue el primer momento en que alguien te vio como vos te querías ver?", 1),
        ("¿Qué sueño de cómo ibas a ser de grande se cumplió y cuál definitivamente no?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que tenías algo que nadie más tenía?", 1),
        ("¿Qué característica tuya que nadie elegiría volver elegirías vos?", 1),
        ("¿Cuándo fue la primera vez que tu carácter fue exactamente lo que salvó algo?", 1),
        ("¿Qué parte de tu personalidad formó algo de lo que sos hoy sin que lo notaras?", 1),
        ("¿Cuándo fue la primera vez que ser vos mismo fue más poderoso que actuar?", 1),
        ("¿Qué cosa de tu forma de ser que era un defecto resultó ser una fortaleza?", 1),
        ("¿Cuándo fue la primera vez que te gustaste sin necesitar que nadie te confirmara?", 1),
        ("¿Qué rasgo tuyo heredaste y al principio lo resististe?", 1),
        ("¿Cuándo fue la primera vez que tu instinto fue exactamente correcto?", 1),
        ("¿Qué parte tuya que mostrás poco es la que más te gusta?", 1),
        ("¿Cuándo fue la primera vez que tu forma de ver el mundo fue exactamente lo que alguien necesitaba?", 1),
        ("¿Qué cosa de la infancia te hizo ser quien sos que al principio parecía una desventaja?", 1),
        ("¿Cuándo fue la primera vez que elegiste no cambiar aunque te lo pidieran?", 1),
        ("¿Qué parte de tu personalidad todavía está formándose aunque seas adulto?", 1),
        ("¿Cuándo fue la primera vez que la soledad fue necesaria para que te encontraras?", 1),
        ("¿Qué versión de vos imaginabas que ibas a ser y que te alegra no haber sido?", 1),
        ("¿Cuándo fue la primera vez que te perdonaste algo que creías imperdonable?", 1),
        ("¿Qué cosa de vos que cambió con el tiempo mejoró y cuál no tanto?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que eras capaz de algo que nunca imaginabas?", 1),
        ("¿Qué parte de tu carácter fue formada por algo doloroso que hoy no cambiarías?", 1),
        ("¿Cuándo fue la primera vez que sentiste que eras exactamente quien necesitabas ser?", 1),
        ("¿Qué parte de vos que soñabas tener de chico nunca llegó y cómo te reconciliaste con eso?", 2),
        ("¿Cuándo fue la primera vez que algo de vos que ocultabas resultó ser lo más valioso que tenías?", 2),
        ("¿Qué rasgo tuyo todavía no aceptaste del todo aunque lo reconozcas?", 2),
        ("¿Cuándo fue la primera vez que cambiaste algo de vos que creías que era central en tu identidad?", 2),
        ("¿Qué cosa de tu personalidad te genera más ambivalencia?", 2),
        ("¿Cuándo fue la primera vez que alguien te conoció mejor de lo que vos te conocías?", 2),
        ("¿Qué parte de vos todavía se parece al niño que fuiste aunque hayas crecido?", 2),
        ("¿Cuándo fue la primera vez que tu personalidad fue un obstáculo que vos mismo creaste?", 2),
        ("¿Qué cosa de vos que resististe terminar cambiando fue lo más importante?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que no eras tan distinto de alguien que creías diferente?", 2),
        ("¿Qué parte de tu identidad construiste conscientemente y cuál simplemente apareció?", 2),
        ("¿Cuándo fue la primera vez que algo de vos sorprendió a alguien que te conocía bien?", 2),
        ("¿Qué rasgo tuyo revela algo de vos que no siempre querés que vean?", 2),
        ("¿Qué parte de tu personalidad todavía no terminás de entender del todo?", 3),
        ("¿Cuándo fue la primera vez que elegiste ser auténtico y eso te costó algo concreto?", 3),
        ("¿Qué cosa de vos que cambió con el tiempo todavía no sabés si fue para mejor?", 3),
        ("¿Cuándo fue la primera vez que te diste cuenta de que tu mayor fortaleza podía ser tu mayor debilidad?", 3),
        ("¿Qué parte de vos que el niño que fuiste soñaba con tener perdiste en el camino?", 3),
        ("¿Cuándo fue la primera vez que quien sos fue exactamente lo que el mundo necesitaba aunque no lo pidiera?", 3),
        ("¿Qué parte de tu identidad todavía no mostrás por completo y por qué?", 3),
        ("¿Cuándo fue la primera vez que te diste cuenta de que quién sos depende también de lo que elegís no ser?", 3),
    ],

    "miedos": [
        ("¿Cuál fue tu mayor miedo de la infancia y qué le pasó a ese miedo con el tiempo?", 1),
        ("¿Qué miedo de chico te parecía enorme que hoy te genera ternura?", 1),
        ("¿Cuándo fue la primera vez que el miedo fue exactamente la señal de que algo importaba de verdad?", 1),
        ("¿Qué miedo de la infancia todavía aparece de alguna forma en tu vida adulta?", 1),
        ("¿Cuándo fue la primera vez que enfrentaste algo que te daba miedo y salió bien?", 1),
        ("¿Qué miedo de chico heredaste de un adulto sin que nadie lo dijera?", 1),
        ("¿Cuándo fue la primera vez que el miedo fue más grande que vos pero igual te moviste?", 1),
        ("¿Qué cosa de la infancia te daba miedo que hoy ni recordás?", 1),
        ("¿Cuándo fue la primera vez que el miedo fue exactamente la razón por la que creciste?", 1),
        ("¿Qué miedo de la infancia cambió tu trayectoria de una manera que no hubieras elegido?", 1),
        ("¿Cuál fue la primera vez que le contaste a alguien un miedo que guardabas solo?", 1),
        ("¿Qué miedo de chico resultó ser completamente imaginario?", 1),
        ("¿Cuándo fue la primera vez que el miedo se convirtió en respeto?", 1),
        ("¿Qué miedo de la infancia te hizo más fuerte aunque en ese momento te pareciera lo contrario?", 1),
        ("¿Cuándo fue la primera vez que superaste algo que te parecía insuperable?", 1),
        ("¿Qué miedo de la infancia querías que alguien te dijera que era normal?", 1),
        ("¿Cuándo fue la primera vez que el miedo fue exactamente lo que te mantuvo a salvo?", 1),
        ("¿Qué miedo de chico no tenías y te apareció de adulto que no esperabas?", 1),
        ("¿Cuándo fue la primera vez que el coraje no fue la ausencia del miedo sino hacer algo a pesar de él?", 1),
        ("¿Qué miedo de la infancia todavía no superaste del todo aunque creas que sí?", 1),
        ("¿Cuándo fue la primera vez que el miedo fue exactamente el precio correcto de algo que valía la pena?", 1),
        ("¿Qué cosa de chico hacías sin miedo que hoy te genera más ansiedad?", 1),
        ("¿Cuándo fue la primera vez que el miedo te paralizó y después te arrepentiste?", 1),
        ("¿Qué miedo de la infancia fue puesto ahí por alguien más y te costó reconocerlo?", 1),
        ("¿Cuándo fue la primera vez que le pediste ayuda a alguien para algo que te daba miedo enfrentar solo?", 1),
        ("¿Qué miedo de chico creció contigo sin que lo notaras?", 1),
        ("¿Cuándo fue la primera vez que el miedo fue exactamente lo que necesitabas para tomar una decisión?", 1),
        ("¿Qué miedo te acompañó tanto tiempo que casi se convirtió en parte de tu identidad?", 1),
        ("¿Cuándo fue la primera vez que superaste un miedo y te diste cuenta de que perdiste tiempo teniéndolo?", 1),
        ("¿Qué miedo de la infancia aún no nombraste en voz alta y qué pasaría si lo hicieras?", 1),
        ("¿Qué miedo de la infancia que nunca superaste todavía limita algo de tu vida adulta?", 2),
        ("¿Cuándo fue la primera vez que el miedo te hizo tomar una decisión que no querías tomar?", 2),
        ("¿Qué miedo de chico heredaste que todavía no terminaste de cuestionar?", 2),
        ("¿Cuándo fue la primera vez que el miedo te hizo más pequeño de lo que sos?", 2),
        ("¿Qué miedo de la infancia cambió quién sos de una manera que todavía no terminás de entender?", 2),
        ("¿Cuándo fue la primera vez que el miedo ganó y cómo lo procesaste después?", 2),
        ("¿Qué miedo tuyo es tan antiguo que ya ni sabés cuándo empezó?", 2),
        ("¿Cuándo fue la primera vez que el miedo a algo imaginario tuvo consecuencias reales?", 2),
        ("¿Qué miedo de la infancia te hizo descartar algo que podrías haber amado?", 2),
        ("¿Cuándo fue la primera vez que elegiste no hablar de algo por miedo y después eso empeoró las cosas?", 2),
        ("¿Qué miedo tuyo todavía no nombraste en voz alta porque si lo hacés se vuelve real?", 2),
        ("¿Cuándo fue la primera vez que el miedo fue exactamente lo que perdiste sin querer?", 2),
        ("¿Qué miedo de la infancia todavía afecta algo de vos que no esperabas?", 2),
        ("¿Qué miedo de chico se convirtió en algo que todavía no terminaste de resolver aunque parezca superado?", 3),
        ("¿Cuándo fue la primera vez que el miedo fue exactamente lo que te impidió ser quien querías ser?", 3),
        ("¿Qué miedo que no admitís todavía dirige algunas de tus decisiones más importantes?", 3),
        ("¿Cuándo fue la primera vez que el miedo te mostró exactamente qué era lo que más querías?", 3),
        ("¿Qué miedo de la infancia fue puesto en vos por alguien y todavía no terminaste de sacártelo?", 3),
        ("¿Cuándo fue la primera vez que el miedo fue exactamente el lugar donde encontraste quién eras?", 3),
        ("¿Qué miedo tuyo revela algo sobre vos que preferirías no ver?", 3),
        ("¿Cuándo fue la primera vez que el miedo fue tan grande que cambió el rumbo de tu vida y todavía no sabés si estuvo bien?", 3),
    ],

    "logros": [
        ("¿Cuándo fue la primera vez que algo que lograste fue exactamente lo que el niño que fuiste soñaba?", 1),
        ("¿Qué logro tuyo que nadie vio fue el que más te costó?", 1),
        ("¿Cuál fue tu primer logro que te hizo sentir que eras capaz de algo más grande?", 1),
        ("¿Qué cosa lograste que de chico te hubiera parecido imposible?", 1),
        ("¿Cuándo fue la primera vez que lograste algo que te parecía demasiado grande para vos?", 1),
        ("¿Qué logro de la infancia todavía recordás con orgullo aunque parezca pequeño?", 1),
        ("¿Cuándo fue la primera vez que algo que lograste fue el resultado de años de algo silencioso?", 1),
        ("¿Qué cosa lograste que nadie esperaba que lograrás incluido vos mismo?", 1),
        ("¿Cuándo fue la primera vez que un logro fue exactamente la prueba de que valía la pena intentar?", 1),
        ("¿Qué logro de la infancia cambió cómo te veías a vos mismo?", 1),
        ("¿Cuándo fue la primera vez que lograste algo y no sabías cómo celebrarlo?", 1),
        ("¿Qué sueño de la infancia lograste más tarde de lo que esperabas y fue igualmente valioso?", 1),
        ("¿Cuándo fue la primera vez que un logro fue más importante para alguien que para vos?", 1),
        ("¿Qué cosa de la infancia practicaste tanto que resultó en un logro que nunca hubieras imaginado?", 1),
        ("¿Cuándo fue la primera vez que un fracaso fue el camino hacia el logro más importante?", 1),
        ("¿Qué logro que conseguiste de adulto fue la realización de algo que soñaste de chico?", 1),
        ("¿Cuándo fue la primera vez que lograste algo para alguien más y eso fue mejor que hacerlo para vos?", 1),
        ("¿Qué cosa de la infancia que considerabas una derrota fue en realidad un logro?", 1),
        ("¿Cuándo fue la primera vez que lograste algo en silencio sin necesitar que nadie lo supiera?", 1),
        ("¿Qué logro de la infancia que parecía pequeño tuvo un efecto enorme en tu vida?", 1),
        ("¿Cuándo fue la primera vez que un logro fue exactamente lo que no sabías que necesitabas?", 1),
        ("¿Qué cosa soñabas de chico lograr que de adulto perdiste el interés en perseguir?", 1),
        ("¿Cuándo fue la primera vez que un logro fue el resultado de alguien que creyó en vos cuando vos no creías?", 1),
        ("¿Qué logro de la infancia marcó tu carácter más que cualquier otra cosa?", 1),
        ("¿Cuándo fue la primera vez que lograste algo y el proceso fue mejor que el resultado?", 1),
        ("¿Qué logro que conseguiste olvidaste de celebrar porque ya estabas mirando el siguiente?", 1),
        ("¿Cuándo fue la primera vez que lograste algo que parecía imposible y después te preguntaste por qué tardaste tanto?", 1),
        ("¿Qué logro de la infancia compartiste con alguien que ya no está?", 1),
        ("¿Cuándo fue la primera vez que un logro fue exactamente la razón por la que todo lo anterior valió?", 1),
        ("¿Qué cosa de la infancia que intentaste y no lograste en ese momento terminaste logrando después?", 1),
        ("¿Qué logro que soñabas de chico todavía no lograste y cómo convivís con eso?", 2),
        ("¿Cuándo fue la primera vez que lograste algo que te costó algo que querías más?", 2),
        ("¿Qué logro tuyo tiene una sombra que no siempre querés ver?", 2),
        ("¿Cuándo fue la primera vez que un logro fue exactamente lo que te mostró lo que seguía faltando?", 2),
        ("¿Qué cosa de la infancia que intentaste lograr fue el fracaso que más te formó?", 2),
        ("¿Cuándo fue la primera vez que lograste algo y te preguntaste si había valido la pena lo que costó?", 2),
        ("¿Qué logro de la infancia abandonaste antes de intentarlo por algo que hoy no lo justificaba?", 2),
        ("¿Cuándo fue la primera vez que un logro cambió quién sos de una manera que no planeabas?", 2),
        ("¿Qué logro tuyo fue más importante para otros que para vos y cómo lo procesaste?", 2),
        ("¿Cuándo fue la primera vez que lograste algo y sentiste que era el comienzo de algo mayor?", 2),
        ("¿Qué logro que soñabas de chico alcanzaste y fue diferente de lo que imaginabas?", 2),
        ("¿Cuándo fue la primera vez que un logro te hizo sentir más solo de lo que esperabas?", 2),
        ("¿Qué logro de la infancia fue tan tuyo que nunca podría ser de nadie más?", 2),
        ("¿Qué logro que conseguiste todavía no reconociste del todo porque te da miedo que se acabe?", 3),
        ("¿Cuándo fue la primera vez que lograste algo que te hizo cuestionar si quería lo que creías querer?", 3),
        ("¿Qué logro de la infancia fue posible gracias a algo difícil que viviste y no elegiste?", 3),
        ("¿Cuándo fue la primera vez que un logro reveló algo de vos que no estabas listo para ver?", 3),
        ("¿Qué logro tuyo tiene un costo que nunca contaste?", 3),
        ("¿Cuándo fue la primera vez que lograste algo tan importante que el resto de tus logros parecieron pequeños?", 3),
        ("¿Qué logro que todavía no alcanzaste te da más miedo no intentar que no lograr?", 3),
        ("¿Cuándo fue la primera vez que un logro fue exactamente la prueba de que el niño que fuiste tenía razón?", 3),
    ],

    "sinFiltro": [
        ("¿Qué vergüenza de la infancia todavía te genera algo cuando la recordás?", 1),
        ("¿Cuándo fue la primera vez que hiciste algo que te pareció terrible y después resultó no serlo?", 1),
        ("¿Qué cosa de la infancia que te daba vergüenza ahora te parece completamente normal?", 1),
        ("¿Cuándo fue la primera vez que te pillaron haciendo algo que preferirías no haber hecho?", 1),
        ("¿Qué hábito de la infancia que te avergonzaba todavía mantenés en secreto?", 1),
        ("¿Cuándo fue la primera vez que dijiste algo que no debías y no podías desdecirlo?", 1),
        ("¿Qué cosa de la infancia que nadie sabe fue la que más te formó?", 1),
        ("¿Cuándo fue la primera vez que te escapaste de algo y no te atraparon?", 1),
        ("¿Qué cosa de la infancia que creías que era terrible resultó ser completamente inocente?", 1),
        ("¿Cuándo fue la primera vez que hiciste algo por impulso y fue exactamente lo correcto?", 1),
        ("¿Qué cosa de la infancia que todos sabían pero nadie decía fue la que más te afectó?", 1),
        ("¿Cuándo fue la primera vez que actuaste peor de lo que esperabas de vos y cómo lo cargaste?", 1),
        ("¿Qué cosa de la infancia que guardaste como secreto cambió algo en vos?", 1),
        ("¿Cuándo fue la primera vez que hiciste algo que te generó culpa y no había nadie que te perdonara sino vos mismo?", 1),
        ("¿Qué parte de la infancia que se supone que debería haberte traumatizado en realidad no te afectó tanto?", 1),
        ("¿Cuándo fue la primera vez que la versión menos presentable de vos fue exactamente la más auténtica?", 1),
        ("¿Qué cosa de la infancia que se supone que fue un error fue en realidad exactamente lo que necesitabas hacer?", 1),
        ("¿Cuándo fue la primera vez que hacer trampa en algo pequeño te hizo cuestionar algo grande?", 1),
        ("¿Qué cosa que de chico considerabas un secreto terrible hoy te parece completamente inofensiva?", 1),
        ("¿Cuándo fue la primera vez que la infancia te mostró que podías ser capaz de algo inesperado, para bien o para mal?", 1),
        ("¿Cuándo fue la primera vez que algo de tu infancia que creías superado volvió de una manera que no esperabas?", 1),
        ("¿Qué cosa de chico que nadie supo te generó más culpa y cómo la procesaste?", 1),
        ("¿Cuándo fue la primera vez que la versión oscura de vos apareció y qué hiciste con ella?", 1),
        ("¿Qué parte de tu infancia preferirías que nadie supiera pero que en realidad no cambia quien sos?", 1),
        ("¿Cuándo fue la primera vez que algo de la infancia que ocultaste resultó ser lo más honesto que podías haber hecho?", 1),
        ("¿Qué cosa de la infancia que fue un error fue también la base de algo valioso?", 1),
        ("¿Cuándo fue la primera vez que la versión de vos que menos te gustaba salvó algo?", 1),
        ("¿Qué secreto de la infancia ya no guardás pero todavía sentís que pesa algo?", 1),
        ("¿Cuándo fue la primera vez que algo de la infancia que parecía inocente resultó ser más complicado de lo que parecía?", 1),
        ("¿Qué cosa de la infancia que preferirías olvidar es en realidad parte de quien sos?", 1),
        ("¿Qué cosa de la infancia que cargabas como secreto todavía afecta algo de vos aunque ya no lo guardés?", 2),
        ("¿Cuándo fue la primera vez que algo de vos que escondías resultó ser lo que más conectó con alguien?", 2),
        ("¿Qué parte de tu infancia que nadie sabe fue la que más te marcó de maneras que todavía no terminás de entender?", 2),
        ("¿Cuándo fue la primera vez que la honestidad sobre algo de la infancia fue más liberadora que el secreto?", 2),
        ("¿Qué cosa de la infancia que se supone que debería haberte definido en realidad no te definió para nada?", 2),
        ("¿Cuándo fue la primera vez que algo de vos que considerabas tu peor versión fue exactamente lo que necesitabas ver?", 2),
        ("¿Qué cosa de la infancia que todavía guardás deberías haber contado hace mucho tiempo?", 2),
        ("¿Cuándo fue la primera vez que la vergüenza de algo de la infancia fue más pequeña que el alivio de contarlo?", 2),
        ("¿Qué parte de tu historia de la infancia que nadie sabe todavía te pesa más de lo que querés admitir?", 2),
        ("¿Cuándo fue la primera vez que algo que considerabas tu mayor defecto de la infancia fue exactamente lo que te salvó?", 2),
        ("¿Qué parte de la infancia que preferís no recordar aparece igual y por qué?", 2),
        ("¿Cuándo fue la primera vez que contar algo de tu infancia que habías guardado cambió algo en vos?", 2),
        ("¿Qué cosa de tu infancia sin filtros todavía no contaste y hoy te preguntás si importaría contarla?", 2),
        ("¿Qué cosa de la infancia que guardabas como vergüenza fue en realidad la semilla de tu mayor fortaleza?", 3),
        ("¿Cuándo fue la primera vez que algo de la infancia que ocultabas resultó ser lo más real de vos?", 3),
        ("¿Qué parte de tu historia de infancia que nadie sabe cambiaría cómo te ven y lo preferís así?", 3),
        ("¿Cuándo fue la primera vez que algo que creías imperdonable de la infancia terminaste perdonándote?", 3),
        ("¿Qué cosa de la infancia que nadie sabe fue la que más definió quien sos y todavía no estás listo para admitirlo?", 3),
        ("¿Cuándo fue la primera vez que la versión más oscura de vos en la infancia te mostró algo que necesitabas ver?", 3),
        ("¿Qué secreto de la infancia que guardaste tanto tiempo que ya no sabés si es verdad o si lo reconstruiste?", 3),
        ("¿Cuándo fue la primera vez que algo de la infancia que te avergonzaba resultó ser exactamente lo que te hacía más humano?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS21:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS21[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
