#!/usr/bin/env python3
"""
Expands questions.json with additional questions per category and level.
Run: python3 tools/expand_questions.py
"""
import json, sys

# New questions to add. Format: (text, level)
# IDs will be auto-generated based on existing max index.

ADDITIONS = {
    "infancia": [
        # Level 1 - Superficial
        ("¿Cuál era tu juguete favorito de chico?", 1),
        ("¿Qué comida te negabas a comer de pequeño?", 1),
        ("¿Tenías algún apodo en la infancia?", 1),
        ("¿A qué superhéroe o personaje querías parecerte?", 1),
        ("¿Cuál era tu canción favorita cuando eras chico?", 1),
        ("¿Qué deporte o actividad practicabas de niño?", 1),
        ("¿Cuál era tu lugar favorito para esconderte o jugar solo?", 1),
        ("¿Tuviste alguna mascota imaginaria o peluche especial?", 1),
        ("¿Cuál era tu película favorita de la infancia?", 1),
        ("¿Cómo se llamaba tu mejor amigo del jardín o primaria?", 1),
        ("¿Preferías los recreos o las clases? ¿Por qué?", 1),
        ("¿Qué hacías los sábados a la mañana de chico?", 1),
        ("¿Tenías algún ritual antes de dormir?", 1),
        ("¿Cuál fue el primer libro que leíste por tu cuenta?", 1),
        ("¿Qué travesura hacías en la escuela que nadie supo nunca?", 1),
        ("¿Preferías el campo, la ciudad o la playa para las vacaciones?", 1),
        ("¿Cuánto tiempo pasabas jugando afuera de tu casa?", 1),
        ("¿Qué regalo de cumpleaños recibiste que nunca olvidaste?", 1),
        ("¿Te gustaba ir a la escuela? ¿Por qué sí o no?", 1),
        ("¿Cuál fue la primera vez que te metiste en un problema serio?", 1),
        ("¿Tenías miedo a algo específico cuando eras chico?", 1),
        ("¿Cuál era tu personaje favorito de dibujos animados?", 1),
        ("¿A qué edad aprendiste a andar en bici?", 1),
        ("¿Cuál es el sabor de helado que más pedías?", 1),
        ("¿Con quién pasabas más tiempo: con tu mamá o tu papá?", 1),
        ("¿Tenías una banda o cantante favorito de chico?", 1),
        ("¿Cómo era tu cuarto cuando eras niño?", 1),
        ("¿Cuál fue el primer videojuego o juego de mesa que recuerdas?", 1),
        ("¿Solías invitar amigos a tu casa o preferías ir a la de ellos?", 1),
        ("¿Qué coleccionabas de chico, si es que coleccionabas algo?", 1),
        ("¿Cómo pasabas los veranos cuando eras pequeño?", 1),
        ("¿Tenías una frase o palabra inventada que usabas con tus amigos?", 1),
        ("¿Cuál fue el primer concierto o espectáculo al que fuiste?", 1),
        ("¿Ayudabas en casa con las tareas domésticas? ¿Cuáles?", 1),
        ("¿Qué querías ser de grande cuando tenías 6 años?", 1),
        # Level 2 - Medio
        ("¿Hubo algún momento en tu infancia en que te sentiste muy solo?", 2),
        ("¿Alguna vez te hicieron bullying o fuiste testigo de él?", 2),
        ("¿Cuál fue la mentira más grande que les dijiste a tus padres?", 2),
        ("¿Cómo era tu relación con tus hermanos cuando eran chicos?", 2),
        ("¿Alguna vez rompiste algo valioso en casa y lo ocultaste?", 2),
        ("¿Cuándo fue la primera vez que te enamoraste o te gustó alguien?", 2),
        ("¿Qué cosa querías hacer de chico que tus padres nunca te dejaron?", 2),
        ("¿Recuerdas el día que te diste cuenta que Papá Noel no existía?", 2),
        ("¿Alguna vez te escapaste de casa o lo planeaste?", 2),
        ("¿Cómo era la dinámica de tu familia en la mesa?", 2),
        ("¿Tuviste algún amigo que perdiste contacto y que extrañás?", 2),
        ("¿Cuál fue la pelea más fuerte que tuviste con un amigo de infancia?", 2),
        ("¿Recuerdas alguna vez haber sentido vergüenza de tu familia?", 2),
        ("¿Cuál fue la primera vez que sentiste que el mundo era injusto?", 2),
        ("¿Había algo en tu infancia que te hacía diferente del resto?", 2),
        ("¿En qué momento de tu infancia creciste de golpe?", 2),
        ("¿Cuál fue la peor nota que sacaste y qué pasó después?", 2),
        ("¿Tuviste algún secreto que guardaste con un amigo y nunca contaste?", 2),
        ("¿Hubo algún adulto fuera de tu familia que fue importante para vos?", 2),
        ("¿Cómo te afectó mudarte de barrio o ciudad si te tocó hacerlo?", 2),
        ("¿Cuál fue la decepción más grande que tuviste de chico?", 2),
        ("¿Hubo algo que viste o escuchaste de grande que cambió tu visión de tu infancia?", 2),
        ("¿Cuál fue el consejo que un adulto te dio de chico que más te marcó?", 2),
        ("¿Cómo celebraban las navidades o fiestas en tu familia?", 2),
        ("¿Alguna vez sentiste que tus padres tenían favoritos?", 2),
        # Level 3 - Profundo
        ("¿Qué parte de tu infancia guardás como el mayor tesoro emocional?", 3),
        ("¿Hay algo de tu infancia que aún no pudiste perdonar o soltar?", 3),
        ("¿Qué herida de la infancia todavía afecta tus decisiones de adulto?", 3),
        ("¿Cuándo fue la primera vez que sentiste que tus padres eran personas imperfectas?", 3),
        ("¿Hay algo que hubieras querido decirle a tu yo de 10 años?", 3),
        ("¿Cuál fue el momento de tu infancia en que te sentiste más abandonado?", 3),
        ("¿Qué cosa de tu infancia tuviste que superar solo, sin ayuda de nadie?", 3),
        ("¿Hubo algún trauma pequeño o grande de la infancia que moldeó quién sos hoy?", 3),
        ("¿Cómo influyó tu infancia en la manera en que te relacionás con la gente hoy?", 3),
        ("¿Qué versión de vos mismo de la infancia extrañás más?", 3),
    ],

    "futuro": [
        # Level 1
        ("¿A dónde te gustaría viajar el próximo año?", 1),
        ("¿Qué habilidad querés aprender en los próximos 5 años?", 1),
        ("¿En qué ciudad o país te imaginas viviendo en 10 años?", 1),
        ("¿Preferirías trabajar desde casa o en una oficina en el futuro?", 1),
        ("¿Qué hobby querés desarrollar que aún no arrancaste?", 1),
        ("¿Cuál es el próximo gran viaje que estás planeando?", 1),
        ("¿Qué tipo de casa o departamento querés tener?", 1),
        ("¿Te imaginás teniendo perros, gatos, u otras mascotas en el futuro?", 1),
        ("¿Qué deporte o actividad física querés empezar?", 1),
        ("¿Qué idioma te gustaría aprender?", 1),
        ("¿Qué querés lograr antes de los 40 (o tu próxima gran década)?", 1),
        ("¿Te ves jubilándote joven o trabajando toda la vida?", 1),
        ("¿Qué vehículo soñás tener algún día?", 1),
        ("¿En qué invertirías si tuvieras $1 millón mañana?", 1),
        ("¿Cuál sería tu trabajo ideal si el dinero no fuera un límite?", 1),
        ("¿Te gustaría mudarte a otra ciudad o país alguna vez?", 1),
        ("¿Qué libro, curso o carrera querés estudiar próximamente?", 1),
        ("¿Te imaginas escribiendo un libro, dando charlas o teniendo un canal algún día?", 1),
        ("¿Cuál es el restaurante o estilo de cocina que querés probar?", 1),
        ("¿Qué show o película está en tu lista de pendientes?", 1),
        ("¿Qué cambiarías de tu rutina actual si pudieras empezar de cero?", 1),
        ("¿Te gustaría tener más o menos amigos de los que tenés ahora?", 1),
        ("¿Qué proyecto personal querés arrancar este año?", 1),
        ("¿Cómo te imaginas tu vida cotidiana en 20 años?", 1),
        ("¿Qué tradición querés crear en tu vida o familia en el futuro?", 1),
        # Level 2
        ("¿Cuál es tu mayor miedo con respecto al futuro?", 2),
        ("¿Qué sacrificio estás dispuesto a hacer para alcanzar tus metas?", 2),
        ("¿Hay algo que sientas que estás posponiendo y que ya no podés seguir dejando?", 2),
        ("¿Qué relación querés que sea diferente en tu vida en el futuro?", 2),
        ("¿Cuál es el fracaso que más te preocuparía tener en los próximos años?", 2),
        ("¿Qué versión de vos mismo querés ser en 10 años?", 2),
        ("¿Hay alguna conversación importante que necesitás tener con alguien próximamente?", 2),
        ("¿Qué parte de tu vida actual sería impensable que siguiera igual en 5 años?", 2),
        ("¿Cómo sería para vos la vejez ideal?", 2),
        ("¿Qué decisión importante estás evitando tomar en este momento?", 2),
        ("¿Cómo querés que te recuerden cuando no estés?", 2),
        ("¿Qué es lo que más te frenade perseguir tus metas?", 2),
        ("¿Cuál es el cambio de hábito que sabés que más te cambiaría la vida?", 2),
        ("¿Qué relación laboral o personal querés dejar atrás?", 2),
        ("¿Estás viviendo en el presente o vivís pensando en el futuro? ¿Por qué?", 2),
        ("¿Cuánta importancia le das al dinero en tus planes futuros?", 2),
        ("¿Qué esperás de tus amigos en los próximos años?", 2),
        ("¿Qué rol querés jugar en la vida de las personas que amás?", 2),
        ("¿Hay algún sueño que abandonaste y que en el fondo querés retomar?", 2),
        ("¿Qué cosa querés aprender de vos mismo en la próxima etapa de tu vida?", 2),
        # Level 3
        ("¿Cuál es el legado que querés dejar en este mundo?", 3),
        ("¿Cuándo fue la última vez que sentiste que vivías de acuerdo a tus valores?", 3),
        ("¿Qué tan alineado está tu presente con el futuro que soñabas hace 5 años?", 3),
        ("¿Hay algo que hacés hoy que sabés que el futuro 'vos' te va a agradecer?", 3),
        ("¿Cuál es el peor escenario que imaginás para tu futuro y cómo lo enfrentarías?", 3),
        ("¿Qué tan seguido pensás en la muerte y en qué te hace reflexionar?", 3),
        ("¿Cuál es la cosa más valiente que podrías hacer hoy por tu futuro?", 3),
        ("¿Cuánto control sentís que tenés sobre el rumbo de tu vida?", 3),
        ("¿Qué estás dejando de vivir hoy por miedo a lo que podría pasar mañana?", 3),
        ("¿Si supieras que te quedan 5 años de vida, qué cambiarías primero?", 3),
    ],

    "amor": [
        # Level 1
        ("¿Cuál es tu primera experiencia romántica que recordás?", 1),
        ("¿Cómo fue tu primera cita?", 1),
        ("¿Sos de los que enamoran rápido o sos más desconfiado al principio?", 1),
        ("¿Qué es lo primero que notás de alguien que te atrae?", 1),
        ("¿Cuál es el gesto romántico que más te gusta recibir?", 1),
        ("¿Preferís las relaciones largas o disfrutás de los comienzos?", 1),
        ("¿Cuál es la mejor cita que tuviste?", 1),
        ("¿Qué canción asociás a una relación o persona especial?", 1),
        ("¿Cómo sabés que alguien te gusta de verdad?", 1),
        ("¿Preferís el amor tranquilo o el amor apasionado?", 1),
        ("¿Qué es lo que más valorás en una pareja?", 1),
        ("¿Le declaraste tu amor a alguien primero o esperaste ser declarado?", 1),
        ("¿Creés en el amor a primera vista?", 1),
        ("¿Cuál fue la primera vez que dijiste 'te quiero' y lo sentiste de verdad?", 1),
        ("¿Qué actividad te parece ideal para una cita romántica?", 1),
        ("¿Cuánto tiempo necesitás para confiar en alguien en una relación?", 1),
        ("¿Sos más de dar sorpresas o preferís recibirlas?", 1),
        ("¿Tenés algún ritual romántico que repetís con tus parejas?", 1),
        ("¿Qué es lo que más extrañás de estar en pareja cuando estás soltero?", 1),
        ("¿Cómo describirías tu estilo amoroso con una sola palabra?", 1),
        ("¿Cuál es el detalle que más te derrite en una persona?", 1),
        ("¿Preferís relaciones formales o dejar todo más libre al principio?", 1),
        ("¿Cuál es la película romántica que más te gustó?", 1),
        ("¿Alguna vez escribiste una carta o mensaje de amor?", 1),
        ("¿Qué es lo más gracioso que te pasó en una cita?", 1),
        # Level 2
        ("¿Cuántas veces sentiste que estabas verdaderamente enamorado?", 2),
        ("¿Alguna vez te enamoraste de alguien en el momento equivocado?", 2),
        ("¿Cuál fue el desamor más difícil que viviste?", 2),
        ("¿Cuál es el error que más repetiste en tus relaciones?", 2),
        ("¿Alguna vez le fuiste infiel a alguien o te fueron infiel a vos?", 2),
        ("¿Qué es lo que más cuesta trabajo en una relación para vos?", 2),
        ("¿Cómo manejás los celos en una pareja?", 2),
        ("¿Hubo alguien con quien te arrepentiste de no haber tenido algo más?", 2),
        ("¿Cuál fue la relación más tóxica que tuviste?", 2),
        ("¿Qué cosa dijiste en una relación de la que todavía te arrepentís?", 2),
        ("¿Cómo manejás una pelea fuerte con tu pareja?", 2),
        ("¿Alguna vez diste una segunda oportunidad? ¿Funcionó?", 2),
        ("¿Cuándo fue la última vez que lloraste por amor?", 2),
        ("¿Qué aprendiste de tus relaciones fallidas?", 2),
        ("¿Cuál es la diferencia entre querer y amar para vos?", 2),
        ("¿Hubo una persona que te enseñó a amar diferente?", 2),
        ("¿Cuál es el límite que no cruzarías jamás en una relación?", 2),
        ("¿Alguna vez quisiste a dos personas al mismo tiempo?", 2),
        ("¿Cuánto afectan los valores compartidos en tus relaciones?", 2),
        ("¿Qué habría necesitado ser diferente para que tu relación más importante funcionara?", 2),
        # Level 3
        ("¿Cuál es el amor de tu vida, aunque no hayan terminado juntos?", 3),
        ("¿Qué tanto miedo te da la vulnerabilidad en una relación íntima?", 3),
        ("¿Hay algo de vos que sentís que nadie en una relación ha conocido del todo?", 3),
        ("¿Cuál es la necesidad emocional que más te cuesta pedir en una pareja?", 3),
        ("¿Qué tan seguido el amor que diste fue recíproco?", 3),
        ("¿Cuál es la decisión amorosa de la que más te arrepentís?", 3),
        ("¿Qué tan diferente es quien sos en una relación de quien sos sin ella?", 3),
        ("¿Creés que sos capaz de amar incondicionalmente? ¿Con qué límites?", 3),
        ("¿Cuánto peso tuvo el miedo al abandono en tus relaciones?", 3),
        ("¿Qué cosa sobre el amor tardaste más en aprender?", 3),
    ],

    "familia": [
        # Level 1
        ("¿Qué tradición familiar te encanta y querés mantener?", 1),
        ("¿Cuál es el plato de comida que más asociás a tu familia?", 1),
        ("¿Tenés algún familiar que te inspira? ¿Quién y por qué?", 1),
        ("¿Cómo eran las reuniones familiares cuando eras chico?", 1),
        ("¿Cuál es la historia familiar que más te gusta contar?", 1),
        ("¿A qué familiar te parecés más en personalidad?", 1),
        ("¿Cuál es el chiste interno de tu familia?", 1),
        ("¿Cómo festejan los cumpleaños en tu familia?", 1),
        ("¿Cuál es el mejor regalo que recibiste de un familiar?", 1),
        ("¿Cuál es tu familiar favorito y por qué? (Si podés decirlo)", 1),
        ("¿Tus padres son parecidos o muy distintos entre sí?", 1),
        ("¿Quién cocina mejor en tu familia?", 1),
        ("¿Hay algún familiar que sea el alma de la fiesta siempre?", 1),
        ("¿Cuál es la profesión más inusual que hay en tu árbol genealógico?", 1),
        ("¿Sabés de dónde viene el apellido de tu familia?", 1),
        ("¿Cuál era el show o deporte que veían juntos en familia?", 1),
        ("¿Hay alguna foto familiar que sea especialmente significativa para vos?", 1),
        ("¿Cuántas personas hay en tu familia inmediata?", 1),
        ("¿Mantenés el contacto con tu familia extendida (primos, tíos)?", 1),
        ("¿Cuál es la costumbre de tu familia que explicarías con dificultad a un extraño?", 1),
        # Level 2
        ("¿Cómo fue tu relación con tus padres cuando eras adolescente?", 2),
        ("¿Hubo algún conflicto familiar que tardaron mucho en resolver?", 2),
        ("¿Hay algo que nunca pudiste hablar con tu familia y que quisieras poder decir?", 2),
        ("¿Cómo te afectó la separación de tus padres si la hubo?", 2),
        ("¿Hay algún familiar con quien tengas una relación complicada? ¿Por qué?", 2),
        ("¿Cuál fue el momento más difícil que atravesó tu familia?", 2),
        ("¿Qué expectativas familiares sentiste sobre vos que te pesaron?", 2),
        ("¿Hay algún secreto familiar que descubriste de grande?", 2),
        ("¿Cómo lidiasteis con la pérdida de un ser querido en tu familia?", 2),
        ("¿Hay algo que aprendiste de tus padres que hoy cuestionás?", 2),
        ("¿Cómo influyó tu familia en la forma en que vivís tus relaciones hoy?", 2),
        ("¿Sentís que tu familia te conoce de verdad o hay partes de vos que ocultás?", 2),
        ("¿Cuál fue la conversación más importante que tuviste con un padre o familiar?", 2),
        ("¿Hay algo que le diste o le das a tu familia que ningún otro podría dar?", 2),
        ("¿Cómo manejan las diferencias políticas o de valores en tu familia?", 2),
        ("¿Qué cosas de tu crianza no repetirías si tenés o tuvieras hijos?", 2),
        ("¿Cuánto peso tuvo la opinión de tu familia en las decisiones más importantes de tu vida?", 2),
        ("¿Te sentís libre de ser quien sos dentro de tu familia?", 2),
        ("¿Hay algún familiar que perdiste sin haberte reconciliado?", 2),
        ("¿Cómo cambió tu relación con tus padres cuando creciste?", 2),
        # Level 3
        ("¿Qué cosa de tu familia nunca hablarías con nadie fuera de este grupo?", 3),
        ("¿Hay algo que te duele profundamente de la familia en la que creciste?", 3),
        ("¿Qué heridas recibiste de tu familia que todavía estás sanando?", 3),
        ("¿Qué parte de la persona que sos hoy es el resultado directo del dolor familiar?", 3),
        ("¿Si pudieras decirle una sola cosa honesta a tu mamá o papá, qué sería?", 3),
        ("¿Cuál fue el momento en que tu familia te falló de la manera más profunda?", 3),
        ("¿Qué tan diferente es la familia que creás o querés crear de la que tuviste?", 3),
        ("¿Hay alguien en tu familia a quien nunca le dijiste que lo amás? ¿Por qué?", 3),
        ("¿Cuánto miedo te da repetir los errores de tus padres?", 3),
        ("¿Qué cosa de tu familia te costó más aceptar y en qué punto lo lograste?", 3),
    ],

    "amistades": [
        # Level 1
        ("¿Cómo conociste a tu mejor amigo/a actual?", 1),
        ("¿Cuál es el plan favorito que tenés con tus amigos?", 1),
        ("¿Cuánto tiempo podés estar sin ver a tus amigos más cercanos?", 1),
        ("¿Cuál es el apodo que tus amigos te pusieron?", 1),
        ("¿Qué es lo que más valorás en una amistad?", 1),
        ("¿Sos de los que tiene pocos amigos muy cercanos o muchos conocidos?", 1),
        ("¿Cuál es la anécdota más graciosa que tenés con un amigo?", 1),
        ("¿Cómo celebrás el cumpleaños de tus amigos?", 1),
        ("¿Cuál es la actividad que más disfrutás hacer con amigos?", 1),
        ("¿Tenés amigos de la infancia que todavía seguís viendo?", 1),
        ("¿Qué hace que alguien pase de conocido a amigo para vos?", 1),
        ("¿Cuál es el regalo más creativo que le hiciste a un amigo?", 1),
        ("¿Tenés amigos en otros países? ¿Cómo mantienen el contacto?", 1),
        ("¿Cuándo fue la última vez que te reíste hasta llorar con un amigo?", 1),
        ("¿Tenés un amigo con quien podás hablar de absolutamente todo?", 1),
        ("¿Cuál es la tradición que tenés con tu grupo de amigos?", 1),
        ("¿Cuántos amigos de tu grupo actual conociste en la escuela o la facultad?", 1),
        ("¿Sos del tipo que siempre organiza o esperás que otros lo hagan?", 1),
        ("¿Qué es lo que más extrañás de una amistad que ya no tenés?", 1),
        ("¿Cuál es la peor excusa que le diste a un amigo para no salir?", 1),
        # Level 2
        ("¿Alguna vez tuviste una pelea fuerte con un amigo? ¿Cómo se resolvió?", 2),
        ("¿Hay alguna amistad que terminó y todavía no entendés bien por qué?", 2),
        ("¿Cuántas veces pusiste los intereses de un amigo por encima de los tuyos?", 2),
        ("¿Alguna vez un amigo te decepcionó profundamente? ¿Qué pasó?", 2),
        ("¿Hay algo que nunca le contarías a tu mejor amigo por miedo a su reacción?", 2),
        ("¿Alguna vez perdiste una amistad por culpa de una relación amorosa?", 2),
        ("¿Cuándo fue la última vez que le dijiste a un amigo que lo valorás?", 2),
        ("¿Hay alguna amistad que sientas que sos vos quien siempre pone?", 2),
        ("¿Alguna vez le dijiste algo a un amigo que te arrepentiste después?", 2),
        ("¿Cómo reaccionás cuando un amigo toma decisiones que no compartís?", 2),
        ("¿Sentís que sos un buen amigo? ¿Qué mejorarías?", 2),
        ("¿Hay alguien que considerabas un amigo y resultó ser falso?", 2),
        ("¿Cómo manejás cuando un amigo está en un mal momento y no sabe cómo pedir ayuda?", 2),
        ("¿Hubo alguna vez que tuvieras que elegir entre dos amigos y fue muy difícil?", 2),
        ("¿Alguna vez sentiste envidia de un amigo? ¿Cómo lo manejaste?", 2),
        ("¿Cuándo fue la última vez que un amigo te sorprendió positivamente?", 2),
        ("¿Hay alguna conversación pendiente que necesitás tener con un amigo?", 2),
        ("¿Cómo afectan las diferencias económicas tus amistades?", 2),
        ("¿Alguna vez le contaste a un amigo algo que debías guardar?", 2),
        ("¿Cuál es el límite que no cruzarías en una amistad?", 2),
        # Level 3
        ("¿Cuál es la amistad que más extrañás y que sientes que nunca vas a poder recuperar?", 3),
        ("¿Hay algo que le hiciste a un amigo de lo que todavía te sentís culpable?", 3),
        ("¿Cuál es la cosa más honesta que alguien llamado tu amigo te dijo y que te dolió pero era verdad?", 3),
        ("¿Cuánto miedo te da la soledad sin tu red de amigos?", 3),
        ("¿Hay alguna amistad que terminó por tu culpa y no pudiste hacer nada para remediarlo?", 3),
        ("¿Alguna vez sentiste que tus amigos no te conocen de verdad?", 3),
        ("¿Qué parte de vos mostrás con tus amigos que con nadie más mostrás?", 3),
        ("¿Cuánto de quien sos es moldeado por la gente de la que te rodeás?", 3),
        ("¿Hay algo que cambiarías de cómo te relacionás con tus amigos más cercanos?", 3),
        ("¿Cuándo fue la última vez que una amistad te salvó de algo?", 3),
    ],

    "exs": [
        # Level 1
        ("¿Cómo conociste a tu ex más significativo/a?", 1),
        ("¿Cuánto tiempo duró tu relación más larga?", 1),
        ("¿Sos de los que mantiene amistades con sus ex o preferís cortar el contacto?", 1),
        ("¿Cuál fue la razón oficial de tu ruptura más reciente?", 1),
        ("¿Cuánto tiempo tardás en 'sanar' después de una ruptura?", 1),
        ("¿Hay alguna canción que no podés escuchar por los recuerdos que trae?", 1),
        ("¿Cuál fue la cita más memorable que tuviste con un ex?", 1),
        ("¿Cómo reaccionás cuando ves fotos antiguas de un ex en redes?", 1),
        ("¿Alguna vez fuiste a ver a un ex mucho después de terminar?", 1),
        ("¿Cómo fue el primer encuentro después de terminar con alguien?", 1),
        ("¿Tenés algún objeto que todavía conservás de una relación pasada?", 1),
        ("¿Cuántas relaciones serias tuviste en tu vida?", 1),
        ("¿Cuál fue el peor chiste que te hicieron durante una ruptura?", 1),
        ("¿Cómo te enteraste de cuando tu ex empezó a salir con alguien más?", 1),
        ("¿Sos de los que borra todo o guardás recuerdos de las relaciones pasadas?", 1),
        ("¿Cuál fue la manera más inesperada en que terminaste una relación?", 1),
        ("¿Qué extrañás (si es que algo) de algún ex?", 1),
        ("¿Alguna vez te enamoraste de alguien que tenía pareja?", 1),
        ("¿Cuál fue la señal de alerta que ignoraste en una relación pasada?", 1),
        ("¿Cuántas veces intentaste volver con un ex?", 1),
        # Level 2
        ("¿Cuál fue la ruptura más dolorosa que viviste y cómo la superaste?", 2),
        ("¿Alguna vez estuviste en una relación que sabías que no tenía futuro pero seguiste igual?", 2),
        ("¿Qué es lo que más aprendiste de tu relación más larga?", 2),
        ("¿Alguna vez dejaste ir a alguien que en el fondo no querías dejar ir?", 2),
        ("¿Cuál fue el mayor error que cometiste en una relación pasada?", 2),
        ("¿Hay algo que hiciste en una relación de lo que todavía te arrepentís?", 2),
        ("¿Cómo te cambió la persona que más amaste?", 2),
        ("¿Alguna vez retomaste una relación que ya había terminado? ¿Cómo fue?", 2),
        ("¿Cuál fue la pelea más intensa que tuviste con un ex?", 2),
        ("¿Qué necesitabas en esa relación que no podías pedir?", 2),
        ("¿Hay algo de lo que se dijo en la ruptura que aún te pesa?", 2),
        ("¿Cuánto tiempo tardaste en darte cuenta que la relación estaba terminada antes de terminarla?", 2),
        ("¿Qué harías diferente si pudieras volver atrás en esa relación?", 2),
        ("¿Alguna vez te fuiste de una relación sin dar una explicación real?", 2),
        ("¿Cómo impactaron tus ex en cómo amás hoy?", 2),
        ("¿Hubo algún ex al que le debes una disculpa?", 2),
        ("¿Qué parte de vos dejaste en esa relación y nunca recuperaste del todo?", 2),
        ("¿Hay algo que un ex te dijo sobre vos que te costó aceptar pero era verdad?", 2),
        ("¿Cómo fue la primera vez que te rompieron el corazón?", 2),
        ("¿Hay alguna relación pasada que sientas que terminó antes de tiempo?", 2),
        # Level 3
        ("¿Cuál es la persona con la que más quisiste estar y con quien no pudo ser?", 3),
        ("¿Hay alguien de tu pasado amoroso a quien nunca vas a poder olvidar del todo?", 3),
        ("¿Qué tanto miedo a repetir el dolor pasado afecta tus relaciones actuales?", 3),
        ("¿Hubo una relación que te rompió de una manera que todavía estás reconstruyendo?", 3),
        ("¿Qué necesitabas sanar antes de poder amar bien a alguien?", 3),
        ("¿Hay algo que nunca pudiste decirle a un ex y que todavía querías haber dicho?", 3),
        ("¿Cuánto de quien sos hoy tiene que ver con las heridas que dejaron tus relaciones pasadas?", 3),
        ("¿Alguna vez elegiste quedarte en una relación por miedo a la soledad?", 3),
        ("¿Cuál es la cosa más valiente que hiciste por amor?", 3),
        ("¿Hay alguna relación del pasado que, si pudieras, revisitarías solo para cerrarla bien?", 3),
    ],

    "personalidad": [
        # Level 1
        ("¿Sos más de la mañana o de la noche?", 1),
        ("¿Preferís el orden o la improvisación en tu día a día?", 1),
        ("¿Cuál es tu mayor virtud según vos mismo?", 1),
        ("¿Cómo reaccionás cuando algo no sale como esperabas?", 1),
        ("¿Sos introvertido, extrovertido o dependiendo del día?", 1),
        ("¿Cuál es tu forma preferida de relajarte?", 1),
        ("¿Qué te pone de mal humor más rápido que nada?", 1),
        ("¿Cuándo fue la última vez que probaste algo nuevo y te encantó?", 1),
        ("¿Sos de los que planifica o preferís ver qué pasa?", 1),
        ("¿Qué tipo de música escuchás cuando necesitás levantarte el ánimo?", 1),
        ("¿Cómo reaccionás ante los conflictos: los enfrentás o los esquivás?", 1),
        ("¿Cuál es la cosa más rara que hiciste en público?", 1),
        ("¿Cuál es tu guilty pleasure más inconfesable?", 1),
        ("¿Qué hobby o afición tenés que la gente suele sorprenderse al saber?", 1),
        ("¿Cuántas horas dormís por noche? ¿Te alcanza?", 1),
        ("¿Cuál es la primera cosa que hacés cuando te levantás?", 1),
        ("¿Qué es lo que más procrastinás en tu vida?", 1),
        ("¿Tenés alguna manía o superstición que todavía seguís?", 1),
        ("¿Cuál es la cosa más espontánea que hiciste?", 1),
        ("¿Qué haría que un día fuera perfecto para vos?", 1),
        ("¿Sos de los que guarda rencor o perdonás fácil?", 1),
        ("¿Qué es lo primero que notan de vos quienes te conocen?", 1),
        ("¿Cuánto tiempo pasás solo por día y cómo te sienta?", 1),
        ("¿Cuál es tu talento oculto?", 1),
        ("¿Qué hábito querés cambiar de vos mismo?", 1),
        # Level 2
        ("¿Cuál es el defecto que más te cuesta admitir?", 2),
        ("¿Qué es lo que más te da vergüenza de vos mismo?", 2),
        ("¿Cuándo fue la última vez que actuaste en contra de tus valores?", 2),
        ("¿Qué cosa de vos mismo todavía no entendés bien?", 2),
        ("¿Cómo manejás el fracaso en general?", 2),
        ("¿Cuándo fue la última vez que le pediste perdón a alguien?", 2),
        ("¿Hay algún juicio sobre vos mismo que sabés que es injusto pero que no podés deshacerte?", 2),
        ("¿Cuánto te importa lo que los demás piensan de vos?", 2),
        ("¿Cómo cambiaste en los últimos 5 años?", 2),
        ("¿Cuál es la creencia que más limita tu vida actualmente?", 2),
        ("¿Cuándo fue la última vez que hiciste algo que te asustó?", 2),
        ("¿Cuál es la emoción que más te cuesta manejar?", 2),
        ("¿Cuánto de tu comportamiento cotidiano es genuino y cuánto es performativo?", 2),
        ("¿Qué haría falta para que fueras completamente honesto con alguien?", 2),
        ("¿Cuál es la narrativa sobre vos mismo que ya no te sirve?", 2),
        ("¿Qué tipo de persona fuiste en tus peores momentos?", 2),
        ("¿Hay algo de tu personalidad que heredaste y que querías no haber heredado?", 2),
        ("¿Cuál fue la decisión que más te costó tomar por ti mismo?", 2),
        ("¿Cuándo fue la última vez que hiciste algo solo porque los demás esperaban que lo hicieras?", 2),
        ("¿Cuál es el cambio más profundo que tuviste como persona en los últimos años?", 2),
        # Level 3
        ("¿Cuál es la parte de vos mismo que más te cuesta amar?", 3),
        ("¿Qué versión de vos mismo mostrás al mundo que no es del todo auténtica?", 3),
        ("¿Hay algo que creés sobre vos mismo que nadie más sabe?", 3),
        ("¿Cuándo fue la última vez que sentiste que eras completamente vos mismo?", 3),
        ("¿Qué herida personal es la que más afecta tu manera de relacionarte?", 3),
        ("¿Cuál es la cosa de la que más te avergonzás de tu pasado?", 3),
        ("¿Qué tan cómodo te sentís con la incertidumbre y el cambio?", 3),
        ("¿Cuál es el pensamiento que no te animás a decir en voz alta?", 3),
        ("¿Hay algo que hacés de manera compulsiva cuando estás bajo presión?", 3),
        ("¿Cuánto de quien sos es quien querés ser y cuánto es quien te enseñaron a ser?", 3),
    ],

    "miedos": [
        # Level 1
        ("¿Le tenés miedo a algún animal en particular?", 1),
        ("¿Podés ver películas de terror sin problema?", 1),
        ("¿Qué situación cotidiana te genera más ansiedad?", 1),
        ("¿Cuál es la película o serie que más miedo te dio?", 1),
        ("¿Tenés alguna fobia irracional que sabes que es irracional pero persiste igual?", 1),
        ("¿Preferís dormir con la puerta abierta o cerrada? ¿Por qué?", 1),
        ("¿Cuándo fue la última vez que sentiste un susto físico real?", 1),
        ("¿Qué harías si te quedaras encerrado solo de noche en un lugar desconocido?", 1),
        ("¿Le tenés miedo a las alturas?", 1),
        ("¿Cuál es el sonido que más te pone los pelos de punta?", 1),
        ("¿Tenés miedo a volar en avión?", 1),
        ("¿Cuál es el escenario de pesadilla recurrente que tenés?", 1),
        ("¿Le tenés miedo a la oscuridad en algún contexto?", 1),
        ("¿Qué es lo que más te da asco en la vida cotidiana?", 1),
        ("¿Alguna vez te paralizaste de miedo en una situación real?", 1),
        ("¿Qué actividad de aventura (puenting, paracaídas, etc.) nunca harías?", 1),
        ("¿Le tenés miedo a los hospitales o procedimientos médicos?", 1),
        ("¿Cuál es el insecto o bicho que más te afecta?", 1),
        ("¿Cuál es el miedo más ridículo que tenés y que te da vergüenza admitir?", 1),
        ("¿Qué es lo que más te asusta del futuro cercano?", 1),
        # Level 2
        ("¿Cuál es el miedo que más limita tus decisiones?", 2),
        ("¿Alguna vez hiciste algo a pesar del miedo? ¿Cómo fue?", 2),
        ("¿Qué te da más miedo: el fracaso o el éxito?", 2),
        ("¿Cuánto miedo te da la opinión de los demás?", 2),
        ("¿Hay algo que sepas que tenés que hacer pero que el miedo te frena?", 2),
        ("¿Cuál es el miedo que superaste y del que más orgulloso estás?", 2),
        ("¿Qué es lo que más te aterra perder?", 2),
        ("¿Le tenés miedo a estar solo de manera definitiva?", 2),
        ("¿Cuándo fue la última vez que el miedo te hizo tomar una mala decisión?", 2),
        ("¿Hay algo que te dé miedo decirle a alguien cercano?", 2),
        ("¿Le tenés miedo al rechazo? ¿Cómo lo manejás?", 2),
        ("¿Qué te asusta más: que te abandonen o que se queden sin amarte?", 2),
        ("¿Cuándo fue la última vez que el miedo al fracaso te impidió intentar algo?", 2),
        ("¿Hay algún miedo que transmitiste sin querer a alguien que querés?", 2),
        ("¿Cuánto peso tiene el miedo a la muerte en tu vida cotidiana?", 2),
        ("¿Cuál es el mayor riesgo que nunca tomaste por miedo y que lamentás?", 2),
        ("¿Hay algo sobre vos mismo que te da miedo descubrir si mirás muy de cerca?", 2),
        ("¿Cuándo fue la última vez que el miedo te salvó de algo?", 2),
        ("¿Cómo manejás el miedo cuando necesitás actuar igual?", 2),
        ("¿Hay algo que sientas que te persigue sin importar cuánto lo trabajes?", 2),
        # Level 3
        ("¿Cuál es el miedo más profundo que tenés sobre quién sos?", 3),
        ("¿Hay algo que te aterroriza que pueda ser cierto sobre vos mismo?", 3),
        ("¿Cuánto de tu vida está estructurada alrededor de evitar algo que te da miedo?", 3),
        ("¿Cuál es el miedo que más trabajo te costó admitir?", 3),
        ("¿Qué tan seguido el miedo dicta quién sos y quién no podés ser?", 3),
        ("¿Cuál es el miedo que heredaste de tu familia y que querés romper?", 3),
        ("¿Alguna vez el miedo te impidió ser honesto con alguien en un momento clave?", 3),
        ("¿Qué perdiste por tener miedo y cómo lo llevás?", 3),
        ("¿Cuánto de tu identidad está construida sobre cosas que evitás por miedo?", 3),
        ("¿Cuál sería tu vida si pudieras vivir sin ese miedo central que te frena?", 3),
    ],

    "logros": [
        # Level 1
        ("¿Cuál fue tu mejor nota, premio o reconocimiento escolar?", 1),
        ("¿Qué habilidad te costó aprender pero que ahora dominás?", 1),
        ("¿Cuál es el logro del que más orgulloso estás a nivel laboral?", 1),
        ("¿Alguna vez ganaste algún concurso o competencia?", 1),
        ("¿Cuál es la cosa más difícil físicamente que hayas logrado?", 1),
        ("¿Aprendiste algo de cero en los últimos años? ¿Qué fue?", 1),
        ("¿Cuál fue el proyecto personal que terminaste y te hizo sentir más orgulloso?", 1),
        ("¿Hubo algún momento en que te superaste a vos mismo?", 1),
        ("¿Cuál fue la primera vez que te pagaron por algo que hiciste?", 1),
        ("¿Tenés algún talento que desarrollaste sin que nadie te enseñara?", 1),
        ("¿Cuál fue el viaje más complicado que planeaste y lograste?", 1),
        ("¿Hay algún libro, película o proyecto que hayas completado solo?", 1),
        ("¿Cuál es la cosa más creativa que hiciste con tus propias manos?", 1),
        ("¿Cuándo fue la última vez que lograste algo que parecía imposible?", 1),
        ("¿Hay algún idioma, instrumento o deporte que aprendiste de adulto?", 1),
        ("¿Cuál fue el momento en que alguien te felicitó y más te emocionó?", 1),
        ("¿Tuviste algún mentor o profesor que haya impactado tu desarrollo?", 1),
        ("¿Cuál fue la primera vez que viajaste solo?", 1),
        ("¿Cuándo fue la última vez que te pusiste una meta y la cumpliste?", 1),
        ("¿Cuál es el récord personal (de cualquier tipo) del que estás más orgulloso?", 1),
        # Level 2
        ("¿Cuál fue el logro que te costó más sacrificio personal?", 2),
        ("¿Hay algo que lograste que nadie de tu entorno esperaba que pudieras lograr?", 2),
        ("¿Qué meta fallaste en alcanzar y cómo procesaste esa sensación?", 2),
        ("¿Cuándo fue la última vez que te sentiste verdaderamente capaz?", 2),
        ("¿Hay algo que lograste sin apoyo externo y que por eso vale más para vos?", 2),
        ("¿Cómo reaccionás cuando reconocen tus logros públicamente?", 2),
        ("¿Hay algo que dejaste de hacer o abandonaste antes de terminarlo y que aún te pesa?", 2),
        ("¿Cuánto te costó perdonarte por los fracasos del pasado?", 2),
        ("¿Qué proyecto o meta fue rechazado y luego triunfó?", 2),
        ("¿Cómo manejás los logros de los demás cuando vos no estás en tu mejor momento?", 2),
        ("¿Hay un logro que minimizás o que no reconocés como tal pero que es importante?", 2),
        ("¿Qué tan frecuente es que te des crédito por lo que hacés bien?", 2),
        ("¿Cuál fue la vez que más duda de vos mismo tuviste antes de lograr algo?", 2),
        ("¿Hay algún logro que conseguiste y que en el fondo no te hizo tan feliz como esperabas?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que ya sos la persona que querías ser?", 2),
        ("¿Qué sacrificaste para alcanzar algo que querías?", 2),
        ("¿Cómo definís el éxito en este momento de tu vida?", 2),
        ("¿Cuál fue el fracaso que más te enseñó?", 2),
        ("¿Hay algo que hayas empezado y que sepas que nunca vas a terminar?", 2),
        ("¿Cuánto peso tienen los logros en tu autoestima?", 2),
        # Level 3
        ("¿Cuál es el logro del que menos hablás y por qué?", 3),
        ("¿Hay algo que sientas que tenés que lograr antes de morir para sentir que valió la pena?", 3),
        ("¿Cuánto de tus logros son para vos y cuánto para satisfacer a otros?", 3),
        ("¿Qué te impediría a vos mismo lograr lo que más querés?", 3),
        ("¿Cuándo fue la última vez que sentiste que hacías exactamente lo que viniste al mundo a hacer?", 3),
        ("¿Cuál es la diferencia entre lo que lograste y lo que soñabas lograr cuando eras joven?", 3),
        ("¿Hay algo que tenés que demostrar y que eso te pesa más de lo que querés admitir?", 3),
        ("¿Qué tan en paz estás con lo que hiciste y lo que dejaste de hacer?", 3),
        ("¿Cuál es el logro más importante que aún está pendiente en tu vida?", 3),
        ("¿Qué significaría para vos fallar en lo que más te importa?", 3),
    ],

    "sinFiltro": [
        # Level 1
        ("¿Cuál es la situación más incómoda en la que te encontraste en una reunión social?", 1),
        ("¿Qué opinión tenés que guardás para vos porque sabés que nadie la comparte?", 1),
        ("¿Cuál fue la mentira más elaborada que contaste?", 1),
        ("¿Cuántas veces hablaste mal de alguien en esta sala?", 1),
        ("¿Cuál es el hábito tuyo que nadie sabe que tenés?", 1),
        ("¿Qué es lo más raro que googleaste alguna vez?", 1),
        ("¿Cuál es tu opinión más polémica sobre algo completamente inofensivo?", 1),
        ("¿Alguna vez fingiste estar enfermo para no ir a algo?", 1),
        ("¿Cuál es la cosa más vergonzosa que hiciste en la universidad?", 1),
        ("¿Qué piensan los demás de vos que no es cierto?", 1),
        ("¿Cuál es tu opinión real sobre las redes sociales?", 1),
        ("¿Tenés algún placer culposo que jamás confesarías en una primera cita?", 1),
        ("¿Qué cosa comprás que te daría vergüenza que apareciera en tu extracto bancario?", 1),
        ("¿Cuántas veces miraste el teléfono de alguien sin que lo supiera?", 1),
        ("¿Cuál es el programa o artista que escuchás/ves que nadie en este grupo espera?", 1),
        ("¿Cuál fue la excusa más ridícula que usaste para cancelar algo?", 1),
        ("¿Tenés algún talento completamente inútil?", 1),
        ("¿Cuántas veces mandaste un mensaje al destinatario equivocado?", 1),
        ("¿Qué convención social te parece completamente innecesaria?", 1),
        ("¿Cuál es la aplicación del celular de la que más te avergonzarías si alguien la viera?", 1),
        # Level 2
        ("¿Cuál es la cosa más escandalosa que hiciste en un estado alterado?", 2),
        ("¿Alguna vez usaste a alguien para subir en el trabajo o socialmente?", 2),
        ("¿Cuándo fue la última vez que mentiste para evitar una conversación difícil?", 2),
        ("¿Cuál es tu opinión real sobre el matrimonio?", 2),
        ("¿Hay algo que hacés que, si lo supieran tus padres, morirías de vergüenza?", 2),
        ("¿Alguna vez stalkeaste a un ex o a alguien que te gustaba en redes sociales?", 2),
        ("¿Cuánto dinero tienes realmente en tu cuenta y cómo te hace sentir?", 2),
        ("¿Cuál fue la peor decisión que tomaste bajo presión social?", 2),
        ("¿Alguna vez copiaste en un examen importante?", 2),
        ("¿Cuándo fue la última vez que hiciste algo que va en contra de tus propios valores?", 2),
        ("¿Cuál fue el rollo de una noche más inesperado que tuviste?", 2),
        ("¿Hay algo que hayas robado aunque sea algo pequeño?", 2),
        ("¿Cuál es la mayor mentira que contaste en una entrevista de trabajo?", 2),
        ("¿Alguna vez te hiciste pasar por alguien que no eras para impresionar a alguien?", 2),
        ("¿Cuántas veces fingiste un orgasmo?", 2),
        ("¿Cuál fue tu acto más deshonesto y cómo dormís con eso?", 2),
        ("¿Hay alguien en este grupo al que hayas criticado duramente por detrás?", 2),
        ("¿Cuándo fue la última vez que actuaste con malicia hacia alguien?", 2),
        ("¿Cuál es el pensamiento que tenés sobre alguien cercano que jamás dirías en voz alta?", 2),
        ("¿Qué harías con total libertad si supieras que nadie te vería nunca?", 2),
        # Level 3
        ("¿Cuál es el secreto más oscuro que llevás y que nunca le contaste a nadie?", 3),
        ("¿Qué parte de vos mismo te cuesta aceptar que existe?", 3),
        ("¿Cuál es la cosa más egoísta que hiciste y que te convenciste de que era justificada?", 3),
        ("¿Hay algo que hayas hecho de lo que no te arrepentís pero que el mundo no lo aprobaría?", 3),
        ("¿Cuál es el pensamiento más oscuro que tuviste sobre alguien?", 3),
        ("¿Cuándo fue la última vez que actuaste completamente desde el ego y no desde el amor?", 3),
        ("¿Hay algo en lo sexual que nunca confesaste pero que te gustaría explorar?", 3),
        ("¿Cuál es la adicción o compulsión que más te avergüenza tener?", 3),
        ("¿Qué harías si supieras que no hubiera consecuencias de ningún tipo?", 3),
        ("¿Cuál fue el momento en que fuiste la peor versión de vos mismo?", 3),
    ],
}

def get_prefix(cat_id):
    prefixes = {
        "infancia": "inf",
        "futuro": "fut",
        "amor": "am",
        "familia": "fam",
        "amistades": "ami",
        "exs": "ex",
        "personalidad": "per",
        "miedos": "mie",
        "logros": "log",
        "sinFiltro": "sf",
    }
    return prefixes[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS:
            continue

        prefix = get_prefix(cat_id)
        # Find max existing index per level
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        new_qs = []
        level_counters = {1: max_idx[1], 2: max_idx[2], 3: max_idx[3]}

        for (text, level) in ADDITIONS[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        existing = len(cat["questions"]) - len(new_qs)
        print(f"{cat_id}: {existing} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
