#!/usr/bin/env python3
"""Batch 13 - work, money, ambition, success, failure, entrepreneurship."""
import json

ADDITIONS13 = {
    "infancia": [
        ("¿Cuándo fue la primera vez que viste a alguien trabajar duro y te quedó grabado?", 1),
        ("¿Cuándo fue la primera vez que te dieron plata para hacer algo y qué hiciste con ella?", 1),
        ("¿Cuándo fue la primera vez que te pusiste a pensar en qué ibas a ser cuando fueras grande?", 1),
        ("¿Cuándo fue la primera vez que viste a alguien fracasar en algo y qué sentiste?", 1),
        ("¿Cuándo fue la primera vez que viste a alguien que admirabas triunfar en algo?", 1),
        ("¿Cuándo fue la primera vez que entendiste que el dinero era algo que se podía ganar, no solo recibir?", 1),
        ("¿Cuándo fue la primera vez que te esforzaste en algo y el resultado fue mejor de lo que esperabas?", 1),
        ("¿Cuándo fue la primera vez que alguien te dijo que eras bueno para algo y lo creyeron los dos?", 1),
        ("¿Cuándo fue la primera vez que viste de cerca cómo trabajaba alguien de tu familia?", 1),
        ("¿Cuándo fue la primera vez que quisiste hacer algo mejor que los demás en la escuela o en un juego?", 1),
        ("¿Cuándo fue la primera vez que te frustraste porque no te salía algo y seguiste igual?", 1),
        ("¿Cuándo fue la primera vez que te pagaron por algo que hacías bien?", 1),
        ("¿Cuándo fue la primera vez que viste que el trabajo de alguien de tu familia los hacía felices o infelices?", 1),
        ("¿Cuándo fue la primera vez que imaginaste emprender algo propio, aunque fuera un juego?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que no todo el mundo tenía las mismas oportunidades?", 1),
        ("¿Cuándo fue la primera vez que viste que el fracaso de alguien podía ser también un punto de partida?", 1),
        ("¿Cuándo fue la primera vez que te pusiste una meta y la cumpliste sin que nadie te lo pidiera?", 1),
        ("¿Cuándo fue la primera vez que ahorraste para algo que querías y lo lograste?", 1),
        ("¿Cuándo fue la primera vez que hiciste algo solo porque querías ser el mejor?", 1),
        ("¿Cuándo fue la primera vez que algo que empezaste solo después creció con la ayuda de otros?", 1),
        ("¿Cuándo fue la primera vez que viste que el éxito de alguien dependía de algo más que el esfuerzo?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que el dinero podía generar conflicto dentro de una familia?", 1),
        ("¿Cuándo fue la primera vez que viste a alguien renunciar a algo por dinero y no entendiste por qué?", 1),
        ("¿Cuándo fue la primera vez que te diste cuenta de que lo que querías ser de grande era más complicado de lo que parecía?", 1),
        ("¿Cuándo fue la primera vez que el trabajo o el dinero de tu familia afectó algo de tu infancia de manera significativa?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que el modelo de éxito que tenías en mente no era tuyo sino de alguien más?", 2),
        ("¿Cuándo fue la primera vez que fracasaste en algo que te importaba y el fracaso te enseñó más que el éxito anterior?", 2),
        ("¿Cuándo fue la primera vez que el dinero —tenerlo o no— hizo que te sintieras diferente a los demás?", 2),
        ("¿Cuándo fue la primera vez que entendiste que el trabajo podía ser una forma de identidad, no solo de supervivencia?", 2),
        ("¿Cuándo fue la primera vez que viste que alguien a quien admirabas sacrificaba algo por su ambición?", 2),
        ("¿Cuándo fue la primera vez que te preguntaste si valía la pena lo que alguien pagaba por el éxito?", 2),
        ("¿Cuándo fue la primera vez que sentiste que había algo que querías lograr que no dependía del reconocimiento de nadie?", 2),
        ("¿Cuándo fue la primera vez que la presión de tener éxito te pesó de una manera que no esperabas?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que lo que querías de tu vida laboral era diferente a lo que querían tus padres para vos?", 2),
        ("¿Cuándo fue la primera vez que el fracaso de alguien cercano te enseñó algo que ningún éxito podría haberte dado?", 3),
        ("¿Cuándo fue la primera vez que el modelo de trabajo o dinero de tu familia te marcó de una manera que todavía sentís hoy?", 3),
        ("¿Cuándo fue la primera vez que te diste cuenta de que tenías una relación emocional compleja con el éxito o el fracaso?", 3),
        ("¿Cuándo fue la primera vez que entendiste que la ambición podía tener un costo que no estabas seguro de querer pagar?", 3),
        ("¿Cuándo fue la primera vez que sentiste que lo que querías lograr en la vida era tuyo y de nadie más?", 3),
        ("¿Cuándo fue la primera vez que la situación económica de tu familia te hizo querer construir algo diferente para vos?", 3),
    ],

    "futuro": [
        ("¿Cuándo fue la última vez que te imaginaste trabajando en algo que te apasionara?", 1),
        ("¿Cuándo fue la última vez que pensaste en cómo querés que sea tu vida económica en 10 años?", 1),
        ("¿Cuándo fue la última vez que te imaginaste emprendiendo algo propio?", 1),
        ("¿Cuándo fue la última vez que te imaginaste en una posición de liderazgo?", 1),
        ("¿Cuándo fue la última vez que pensaste en cómo querés que se vea tu éxito profesional?", 1),
        ("¿Cuándo fue la última vez que te imaginaste trabajando menos y viviendo más?", 1),
        ("¿Cuándo fue la última vez que pensaste en retirarte y qué te generó?", 1),
        ("¿Cuándo fue la última vez que te imaginaste tomando un riesgo económico grande?", 1),
        ("¿Cuándo fue la última vez que pensaste en qué harías si el dinero no fuera un problema?", 1),
        ("¿Cuándo fue la última vez que te imaginaste haciendo algo completamente diferente a lo que hacés ahora?", 1),
        ("¿Cuándo fue la última vez que pensaste en el legado profesional que querés dejar?", 1),
        ("¿Cuándo fue la última vez que te imaginaste en un trabajo que te diera libertad pero también impacto?", 1),
        ("¿Cuándo fue la última vez que te pusiste a pensar en tu relación con el dinero y cómo querés que cambie?", 1),
        ("¿Cuándo fue la última vez que te imaginaste construyendo algo junto a otras personas?", 1),
        ("¿Cuándo fue la última vez que te imaginaste fracasando y aprendiendo de eso en el futuro?", 1),
        ("¿Cuándo fue la última vez que te imaginaste siendo reconocido por algo que todavía no lograste?", 1),
        ("¿Cuándo fue la última vez que pensaste en cuánto dinero necesitás realmente para vivir bien?", 1),
        ("¿Cuándo fue la última vez que te imaginaste siendo la persona que otros miran para inspirarse?", 1),
        ("¿Cuándo fue la última vez que te imaginaste logrando algo sin saber exactamente el camino?", 1),
        ("¿Cuándo fue la última vez que te preguntaste si el éxito que estás persiguiendo es realmente el que querés?", 1),
        ("¿Cuándo fue la última vez que te imaginaste trabajando en algo que le hiciera bien al mundo?", 1),
        ("¿Cuándo fue la última vez que pensaste en dejar algo en marcha para que funcione sin vos?", 1),
        ("¿Cuándo fue la última vez que te imaginaste más libre económicamente de lo que sos hoy?", 1),
        ("¿Cuándo fue la última vez que te preguntaste qué tipo de riesgo estás dispuesto a tomar para ir a por lo que querés?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que tu definición de éxito cambió y no habías procesado ese cambio?", 2),
        ("¿Cuándo fue la última vez que pensaste en qué estarías dispuesto a sacrificar para lograr lo que querés?", 2),
        ("¿Cuándo fue la última vez que el miedo al fracaso te frenó de ir a por algo que querías de verdad?", 2),
        ("¿Cuándo fue la última vez que te preguntaste si la ambición que tenés es tuya o la aprendiste de alguien?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que el futuro económico que querés requiere decisiones que todavía no tomaste?", 2),
        ("¿Cuándo fue la última vez que pensaste en qué significaría para vos un fracaso verdadero?", 2),
        ("¿Cuándo fue la última vez que te preguntaste si el camino que seguís te va a llevar a donde realmente querés ir?", 2),
        ("¿Cuándo fue la última vez que te imaginaste mirando hacia atrás desde el futuro y evaluando si tomaste los riesgos que valían?", 2),
        ("¿Cuándo fue la última vez que te preguntaste qué pasaría si fracasaras en lo que más querés lograr, y lo respondiste honestamente?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la libertad económica y la libertad personal no siempre van de la mano?", 2),
        ("¿Cuándo fue la última vez que te confrontaste con la posibilidad de que quizás lo que más querés lograr no lo vayas a lograr, y lo sostuviste sin escapar?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que el éxito que perseguís podría no darte lo que creés que te va a dar?", 3),
        ("¿Cuándo fue la última vez que te preguntaste qué clase de persona querés ser cuando finalmente llegues a lo que buscás?", 3),
        ("¿Cuándo fue la última vez que el miedo a no ser suficiente —profesional o económicamente— fue el obstáculo más honesto que tuviste que enfrentar?", 3),
        ("¿Cuándo fue la última vez que te preguntaste si el camino que tomás te acerca o te aleja de la persona que querés ser?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que la ambición puede ser tanto un motor como una trampa?", 3),
    ],

    "amor": [
        ("¿Cuándo fue la última vez que el trabajo o el dinero generó una tensión en una relación tuya?", 1),
        ("¿Cuándo fue la última vez que alguien te atrajo por su ambición o por lo que construía?", 1),
        ("¿Cuándo fue la última vez que la diferencia económica con alguien importó más de lo que esperabas?", 1),
        ("¿Cuándo fue la última vez que el trabajo te quitó tiempo para alguien que te importaba?", 1),
        ("¿Cuándo fue la última vez que apoyaste el sueño profesional de alguien que amabas aunque te costara algo?", 1),
        ("¿Cuándo fue la última vez que alguien apoyó el tuyo y lo sentiste de verdad?", 1),
        ("¿Cuándo fue la última vez que hablaste abiertamente de dinero con alguien que te gustaba o que amabas?", 1),
        ("¿Cuándo fue la última vez que el éxito de alguien —o el fracaso— cambió algo en cómo lo veías?", 1),
        ("¿Cuándo fue la última vez que el trabajo fue la excusa perfecta para no estar presente en una relación?", 1),
        ("¿Cuándo fue la última vez que tu ambición y tu relación estuvieron en tensión?", 1),
        ("¿Cuándo fue la última vez que te gustó alguien que tenía una relación con el trabajo completamente diferente a la tuya?", 1),
        ("¿Cuándo fue la última vez que el dinero definió algo dentro de una relación aunque no quisieras que lo hiciera?", 1),
        ("¿Cuándo fue la última vez que el fracaso de alguien en el trabajo te puso en el rol de sostener esa relación?", 1),
        ("¿Cuándo fue la última vez que el éxito profesional de alguien hizo que te sintieras menos dentro de la relación?", 1),
        ("¿Cuándo fue la última vez que construir algo junto a alguien —proyecto, emprendimiento, meta compartida— los unió mucho más?", 1),
        ("¿Cuándo fue la última vez que el dinero fue la conversación más difícil que tuviste con alguien que amabas?", 1),
        ("¿Cuándo fue la última vez que alguien te inspiró a ir más lejos profesionalmente por el solo hecho de creer en vos?", 1),
        ("¿Cuándo fue la última vez que sentiste que compartir los mismos valores respecto al trabajo era más importante que la atracción?", 1),
        ("¿Cuándo fue la última vez que la ambición de alguien fue algo que te sedujo antes de que lo conocieras bien?", 1),
        ("¿Cuándo fue la última vez que el estrés laboral fue el protagonista invisible de un conflicto con alguien que amabas?", 1),
        ("¿Cuándo fue la última vez que alguien con quien estuviste no te apoyó en un proyecto tuyo y eso te dijo algo importante de esa relación?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que el trabajo o el dinero podía ser tanto un vínculo como una distancia en una relación?", 1),
        ("¿Cuándo fue la última vez que el reconocimiento profesional de alguien te hizo sentir orgulloso de una manera que te sorprendió?", 1),
        ("¿Cuándo fue la última vez que el éxito propio o ajeno fue motivo de tensión donde debería haber sido motivo de celebración?", 1),
        ("¿Cuándo fue la última vez que el dinero o el éxito revelaron algo de una relación que las buenas épocas no hubieran mostrado?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la ambición de alguien te decía algo importante sobre cómo se amaba a sí mismo?", 2),
        ("¿Cuándo fue la última vez que el fracaso fue el espacio donde una relación tuya mostró su verdad?", 2),
        ("¿Cuándo fue la última vez que el trabajo fue la manera en que alguien te mostró amor sin decírtelo directamente?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que los valores respecto al dinero y al éxito eran incompatibles con alguien que amabas?", 2),
        ("¿Cuándo fue la última vez que la diferencia de ambición entre vos y alguien que amabas fue el origen de algo más grande?", 2),
        ("¿Cuándo fue la última vez que alguien te eligió a vos sobre algo que le hubiera dado más éxito o dinero?", 2),
        ("¿Cuándo fue la última vez que vos elegiste a alguien sobre algo que te hubiera dado más éxito o dinero?", 2),
        ("¿Cuándo fue la última vez que el fracaso compartido con alguien los unió más de lo que cualquier éxito hubiera podido?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que construís profesionalmente dice algo de cómo amás?", 2),
        ("¿Cuándo fue la última vez que el dinero o el éxito fueron la pantalla detrás de la cual alguien se ocultó del amor?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que alguien maneja el fracaso te dice más de quién es que cualquier otra cosa?", 3),
        ("¿Cuándo fue la última vez que el amor te hizo cuestionar seriamente cuánta importancia le dabas al éxito?", 3),
        ("¿Cuándo fue la última vez que construir algo junto a alguien fue la forma más profunda de decirse que se amaban?", 3),
        ("¿Cuándo fue la última vez que el trabajo o el dinero te alejaron de algo que amabas y tuviste que tomar una decisión difícil?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que amar a alguien también significaba amar su manera de relacionarse con el trabajo, el fracaso y el éxito?", 3),
    ],

    "familia": [
        ("¿Cuándo fue la última vez que hablaste de trabajo o dinero abiertamente con alguien de tu familia?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te apoyó en algo profesional de manera concreta?", 1),
        ("¿Cuándo fue la última vez que viste el trabajo de alguien de tu familia y lo admiraste?", 1),
        ("¿Cuándo fue la última vez que el dinero fue un tema de tensión dentro de tu familia?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te dio un consejo sobre el trabajo o el dinero que resultó útil?", 1),
        ("¿Cuándo fue la última vez que viste a alguien de tu familia fracasar en algo y cómo lo manejaron?", 1),
        ("¿Cuándo fue la última vez que viste a alguien de tu familia lograr algo que los llenó de orgullo?", 1),
        ("¿Cuándo fue la última vez que la ambición de alguien de tu familia te generó admiración o incomodidad?", 1),
        ("¿Cuándo fue la última vez que el éxito de alguien de tu familia cambió la dinámica dentro del grupo?", 1),
        ("¿Cuándo fue la última vez que apoyaste económicamente a alguien de tu familia o ellos te apoyaron a vos?", 1),
        ("¿Cuándo fue la última vez que el trabajo fue el tema central de una reunión familiar?", 1),
        ("¿Cuándo fue la última vez que viste cómo el trabajo moldea la personalidad de alguien de tu familia?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te hizo replantearte tu relación con el dinero?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que heredaste una creencia sobre el éxito de tu familia?", 1),
        ("¿Cuándo fue la última vez que la situación económica de tu familia impactó en algo importante para vos?", 1),
        ("¿Cuándo fue la última vez que tu familia estuvo orgullosa de algo que lograste profesionalmente?", 1),
        ("¿Cuándo fue la última vez que sentiste presión de tu familia para ser más exitoso o ganar más?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te mostró que el fracaso también puede ser parte de un buen camino?", 1),
        ("¿Cuándo fue la última vez que construiste algo junto a alguien de tu familia —un negocio, un proyecto, una meta?", 1),
        ("¿Cuándo fue la última vez que el trabajo o el dinero cambiaron la relación de alguien de tu familia con el grupo?", 1),
        ("¿Cuándo fue la última vez que el sacrificio laboral de alguien de tu familia afectó tu infancia o tu vida?", 1),
        ("¿Cuándo fue la última vez que viste a alguien de tu familia defender algo que construyó a pesar de los obstáculos?", 1),
        ("¿Cuándo fue la última vez que el dinero fue el idioma indirecto del amor o del conflicto en tu familia?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te inspiró a querer más —o a querer diferente?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que la relación de tu familia con el trabajo y el dinero te formó de maneras que todavía no terminaste de procesar?", 2),
        ("¿Cuándo fue la última vez que el éxito o el fracaso de alguien de tu familia cambió la dinámica de poder dentro del grupo?", 2),
        ("¿Cuándo fue la última vez que el trabajo fue la excusa que alguien de tu familia usó para no estar presente?", 2),
        ("¿Cuándo fue la última vez que la ambición de alguien de tu familia creó una fractura que todavía sentís?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que los valores sobre el dinero y el éxito que te inculcaron no son los que querés para vos?", 2),
        ("¿Cuándo fue la última vez que el sacrificio económico de alguien de tu familia te pesó de una manera que no pudiste decir en su momento?", 2),
        ("¿Cuándo fue la última vez que el fracaso de tu familia fue lo que más los unió como grupo?", 2),
        ("¿Cuándo fue la última vez que viste en alguien de tu familia la relación con el dinero que querés evitar tener?", 2),
        ("¿Cuándo fue la última vez que el éxito propio te generó una emoción compleja respecto a alguien de tu familia que no llegó tan lejos?", 2),
        ("¿Cuándo fue la última vez que el trabajo o el dinero de tu familia definió algo de quién sos sin que nadie lo haya dicho directamente?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que tu familia manejó el dinero y el éxito sigue viva en vos de maneras que no elegiste?", 3),
        ("¿Cuándo fue la última vez que el fracaso de tu familia fue también el fracaso más honesto y formativo que experimentaste?", 3),
        ("¿Cuándo fue la última vez que te preguntaste si el éxito que perseguís es en parte una respuesta a algo que viviste en tu familia?", 3),
        ("¿Cuándo fue la última vez que el trabajo fue el idioma a través del cual alguien de tu familia te mostró amor sin poder decírtelo de otra manera?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que le debés —o no le debés— a tu familia en términos económicos y emocionales está más mezclado de lo que querés admitir?", 3),
        ("¿Cuándo fue la última vez que entendiste que la historia económica de tu familia es también parte de tu historia, aunque hayas intentado separarla?", 3),
    ],

    "amistades": [
        ("¿Cuándo fue la última vez que hablaste de dinero honestamente con un amigo?", 1),
        ("¿Cuándo fue la última vez que el éxito de un amigo te inspiró en lugar de generarte envidia?", 1),
        ("¿Cuándo fue la última vez que apoyaste a un amigo en un proyecto o emprendimiento?", 1),
        ("¿Cuándo fue la última vez que un amigo te apoyó en algo profesional de manera concreta?", 1),
        ("¿Cuándo fue la última vez que emprendiste o trabajaste en algo junto a un amigo?", 1),
        ("¿Cuándo fue la última vez que la diferencia económica con un amigo fue un tema que tuvieron que nombrar?", 1),
        ("¿Cuándo fue la última vez que el fracaso de un amigo en algo profesional te reveló quién era de verdad?", 1),
        ("¿Cuándo fue la última vez que celebraste el éxito de un amigo de corazón?", 1),
        ("¿Cuándo fue la última vez que la ambición de un amigo te contagió de manera positiva?", 1),
        ("¿Cuándo fue la última vez que el trabajo fue el tema que más ocupó una conversación con amigos?", 1),
        ("¿Cuándo fue la última vez que le pediste consejo a un amigo sobre algo laboral o económico?", 1),
        ("¿Cuándo fue la última vez que un amigo te ayudó a ver algo del trabajo o el dinero de una manera que no habías considerado?", 1),
        ("¿Cuándo fue la última vez que le diste una oportunidad laboral o económica a un amigo?", 1),
        ("¿Cuándo fue la última vez que un amigo te conectó con algo que fue clave para tu desarrollo profesional?", 1),
        ("¿Cuándo fue la última vez que el éxito de un amigo te hizo replantearte tu propio camino?", 1),
        ("¿Cuándo fue la última vez que la diferencia de ambición entre vos y un amigo generó una brecha?", 1),
        ("¿Cuándo fue la última vez que un amigo te fue honesto sobre algo de tu trabajo o tus metas que otros no te decían?", 1),
        ("¿Cuándo fue la última vez que el fracaso de un amigo te enseñó algo que aplicaste en tu propia vida?", 1),
        ("¿Cuándo fue la última vez que el éxito fue algo que celebraron juntos de manera genuina?", 1),
        ("¿Cuándo fue la última vez que trabajar con un amigo fortaleció —o tensionó— la amistad?", 1),
        ("¿Cuándo fue la última vez que el dinero fue el origen de una incomodidad no dicha dentro de un grupo de amigos?", 1),
        ("¿Cuándo fue la última vez que un amigo creyó en un proyecto tuyo más de lo que vos mismo creías?", 1),
        ("¿Cuándo fue la última vez que la conversación sobre el trabajo y las metas con amigos fue más honesta de lo habitual?", 1),
        ("¿Cuándo fue la última vez que sentiste que tus amigos y vos tenían diferentes definiciones de éxito y eso estaba bien?", 1),
        ("¿Cuándo fue la última vez que el éxito de un amigo generó algo en vos que preferiste no mostrar?", 2),
        ("¿Cuándo fue la última vez que la diferencia económica entre vos y un amigo cambió algo en la dinámica de la amistad?", 2),
        ("¿Cuándo fue la última vez que trabajar con un amigo revelό algo de esa persona que en la amistad cotidiana no veías?", 2),
        ("¿Cuándo fue la última vez que un amigo te desafió a ir más lejos en algo y fue incómodo pero necesario?", 2),
        ("¿Cuándo fue la última vez que sentiste que compartir tus metas con ciertos amigos era seguro y con otros no?", 2),
        ("¿Cuándo fue la última vez que el fracaso de un amigo te hizo replantearte tus propios riesgos?", 2),
        ("¿Cuándo fue la última vez que el dinero fue la grieta silenciosa dentro de un grupo de amigos?", 2),
        ("¿Cuándo fue la última vez que la ambición fue algo que te separó de alguien que antes era muy cercano?", 2),
        ("¿Cuándo fue la última vez que viste en un amigo la relación con el fracaso que vos querés tener?", 2),
        ("¿Cuándo fue la última vez que el éxito compartido con amigos fue más satisfactorio que cualquier logro individual?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la amistad y el dinero o el trabajo pueden ser muy difíciles de mezclar?", 3),
        ("¿Cuándo fue la última vez que la diferencia de ambición entre vos y un amigo fue el final —o el inicio— de algo importante?", 3),
        ("¿Cuándo fue la última vez que sentiste que el éxito de alguien cercano te obligó a mirarte a vos mismo de maneras que preferirías no hacer?", 3),
        ("¿Cuándo fue la última vez que un amigo te apoyó en el fracaso de una manera que te mostró el valor real de esa amistad?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que con algunos amigos podés hablar de dinero y fracaso de manera completamente honesta, y eso es un tesoro?", 3),
        ("¿Cuándo fue la última vez que sentiste que la amistad fue el motor más genuino de algo que construiste?", 3),
    ],

    "exs": [
        ("¿Cuándo fue la última vez que el trabajo o las diferencias económicas fueron un tema en una relación pasada?", 1),
        ("¿Cuándo fue la última vez que el éxito de alguien con quien saliste te generó algo complejo?", 1),
        ("¿Cuándo fue la última vez que alguien con quien estuviste te apoyó o no te apoyó en algo profesional?", 1),
        ("¿Cuándo fue la última vez que pensaste en la ambición de alguien del pasado con admiración o con alivio de que ya no estuvieran?", 1),
        ("¿Cuándo fue la última vez que el dinero fue el tema que nadie quería nombrar pero definía algo de la relación?", 1),
        ("¿Cuándo fue la última vez que el fracaso profesional de alguien con quien estuviste cambió algo en cómo los veías?", 1),
        ("¿Cuándo fue la última vez que una relación pasada te dejó algo en términos de lo que buscás laboralmente?", 1),
        ("¿Cuándo fue la última vez que sentiste que alguien del pasado te frenó o te impulsó en algo profesional?", 1),
        ("¿Cuándo fue la última vez que el éxito propio fue motivo de tensión con alguien que amabas?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que la diferencia económica con alguien del pasado definió más de lo que querías admitir?", 1),
        ("¿Cuándo fue la última vez que alguien con quien estuviste te enseñó algo sobre el trabajo o el dinero que todavía usás?", 1),
        ("¿Cuándo fue la última vez que la ambición de alguien del pasado fue algo que al principio te atrajo y después fue un problema?", 1),
        ("¿Cuándo fue la última vez que el trabajo fue la excusa que usó alguien para no estar presente en la relación?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que habías cargado con las metas económicas de alguien que amabas como si fueran tuyas?", 1),
        ("¿Cuándo fue la última vez que la diferencia en la relación con el dinero fue el síntoma de algo más profundo en una pareja?", 1),
        ("¿Cuándo fue la última vez que el éxito o fracaso de una relación pasada te hizo replantearte qué valorás en alguien?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que el modelo de éxito de alguien con quien estuviste influyó en el tuyo?", 1),
        ("¿Cuándo fue la última vez que trabajar junto a alguien que amabas fue lo mejor o lo peor de esa relación?", 1),
        ("¿Cuándo fue la última vez que el fracaso fue el momento en que una relación pasada mostró su verdad?", 1),
        ("¿Cuándo fue la última vez que el éxito fue algo que una relación no pudo sostener?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que alguien del pasado manejaba el dinero decía algo de cómo manejaba el amor?", 1),
        ("¿Cuándo fue la última vez que el trabajo fue el idioma del amor —o del abandono— en una relación?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que una relación pasada te enseñó sobre el éxito o el fracaso fue parte de tu crecimiento?", 1),
        ("¿Cuándo fue la última vez que el fin de una relación cambió algo en cómo te relacionás con el trabajo o el dinero?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que la dinámica de poder en una relación pasada estaba ligada a la diferencia económica o de éxito?", 2),
        ("¿Cuándo fue la última vez que el fracaso compartido en una relación fue también el momento más honesto de esa historia?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que habías usado el trabajo para evitar estar presente en una relación?", 2),
        ("¿Cuándo fue la última vez que el éxito de alguien del pasado te generó algo que todavía no terminaste de procesar?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que una relación pasada te costó económicamente o profesionalmente también tuvo un valor?", 2),
        ("¿Cuándo fue la última vez que el fin de una relación fue también el comienzo de algo nuevo en tu vida profesional?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que los valores sobre el dinero y el éxito eran incompatibles con alguien que amabas, y esa incompatibilidad era central?", 2),
        ("¿Cuándo fue la última vez que sentiste que una relación pasada te dio más libertad profesional de la que hubiera parecido posible?", 2),
        ("¿Cuándo fue la última vez que la ambición propia o ajena fue el catalizador del fin de algo?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que alguien que amaste te enseñó algo sobre el fracaso que todavía influye en cómo te relacionás con él?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que alguien del pasado se relacionaba con el éxito o el fracaso era incompatible con cómo querés vivir?", 3),
        ("¿Cuándo fue la última vez que el fracaso de una relación fue también la oportunidad de redefinir qué clase de éxito querías?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que el dinero o el trabajo en una relación pasada fueron los símbolos de algo que nunca pudieron decirse directamente?", 3),
        ("¿Cuándo fue la última vez que sentiste que la ambición que desarrollaste fue parcialmente una respuesta a algo que viviste en una relación?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que una relación pasada te costó —económica o profesionalmente— fue también lo que te empujó a construir algo propio?", 3),
        ("¿Cuándo fue la última vez que el fin de una relación y el comienzo de algo profesional nuevo estuvieron más entrelazados de lo que quisiste admitir?", 3),
    ],

    "personalidad": [
        ("¿Cuándo fue la última vez que el trabajo te hizo sentir que sos más capaz de lo que creés?", 1),
        ("¿Cuándo fue la última vez que el fracaso en algo te reveló algo de tu carácter que no sabías?", 1),
        ("¿Cuándo fue la última vez que el dinero te mostró algo de vos mismo que no esperabas?", 1),
        ("¿Cuándo fue la última vez que la ambición fue algo que te energizó en lugar de pesarte?", 1),
        ("¿Cuándo fue la última vez que el éxito te hizo sentir orgulloso de quien sos?", 1),
        ("¿Cuándo fue la última vez que el fracaso fue parte de lo que te define?", 1),
        ("¿Cuándo fue la última vez que tu relación con el trabajo o el dinero fue un reflejo directo de cómo te tratás?", 1),
        ("¿Cuándo fue la última vez que emprender algo —grande o pequeño— te mostró de qué estás hecho?", 1),
        ("¿Cuándo fue la última vez que el éxito ajeno te generó una reacción que dice algo de vos?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que tu relación con la ambición es más compleja de lo que querés admitir?", 1),
        ("¿Cuándo fue la última vez que el trabajo fue el espacio donde mejor podías ser vos mismo?", 1),
        ("¿Cuándo fue la última vez que el fracaso te mostró algo de tu carácter que el éxito nunca hubiera podido?", 1),
        ("¿Cuándo fue la última vez que ganarte algo por vos mismo te importó más que el reconocimiento de los demás?", 1),
        ("¿Cuándo fue la última vez que la forma en que manejaste una crisis económica te dijo algo de quién sos?", 1),
        ("¿Cuándo fue la última vez que el éxito fue más tuyo cuando lo compartiste que cuando lo guardaste?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que tu definición de éxito no coincide con la de la mayoría de la gente?", 1),
        ("¿Cuándo fue la última vez que el trabajo fue la manera en que mejor expresaste quién sos?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que le temés más al fracaso o al éxito?", 1),
        ("¿Cuándo fue la última vez que tu relación con el dinero te habló de tu relación con la seguridad?", 1),
        ("¿Cuándo fue la última vez que emprender algo te hizo sentir más libre, aunque también más expuesto?", 1),
        ("¿Cuándo fue la última vez que el trabajo fue el lugar donde te fue más difícil ser honesto con vos mismo?", 1),
        ("¿Cuándo fue la última vez que la ambición fue algo que te alejó de algo que también importaba?", 1),
        ("¿Cuándo fue la última vez que el fracaso en algo profesional te reveló algo que en el éxito estabas ignorando?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que trabajás para vivir o vivís para trabajar, y cuál de las dos te parece bien?", 1),
        ("¿Cuándo fue la última vez que la forma en que te relacionás con el éxito o el fracaso reveló algo de tu historia más profunda?", 2),
        ("¿Cuándo fue la última vez que tu ambición te alejó de algo —o de alguien— que también valorabas?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que manejás el dinero dice algo de cómo te valorás?", 2),
        ("¿Cuándo fue la última vez que el fracaso te confrontó con algo de vos mismo que el éxito te hubiera dejado evitar?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que perseguís profesionalmente no es del todo tuyo?", 2),
        ("¿Cuándo fue la última vez que el trabajo fue el espacio donde más claramente podías ver tu sombra?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la forma en que te relacionás con la autoridad en el trabajo dice algo de tu historia?", 2),
        ("¿Cuándo fue la última vez que la ambición fue algo que te mostró algo de vos mismo que no te gustó?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que tu relación con el éxito tiene que ver con cuánto creés que merecés?", 2),
        ("¿Cuándo fue la última vez que el fracaso fue el espacio más honesto donde pudiste verte tal como sos?", 2),
        ("¿Cuándo fue la última vez que tu relación con el fracaso reveló algo de tu historia que todavía no terminaste de sanar?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que más temés no es el fracaso sino lo que el fracaso diría de vos?", 3),
        ("¿Cuándo fue la última vez que el éxito no te llenó de la manera que esperabas y eso fue el inicio de algo importante?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que tu ambición es también una forma de responder a algo que no te diste a vos mismo?", 3),
        ("¿Cuándo fue la última vez que te preguntaste si el éxito que buscás te va a hacer más o menos vos mismo?", 3),
        ("¿Cuándo fue la última vez que el trabajo fue el espejo más honesto y más incómodo que tuviste?", 3),
    ],

    "miedos": [
        ("¿Cuándo fue la última vez que el miedo al fracaso te frenó de intentar algo?", 1),
        ("¿Cuándo fue la última vez que el miedo a no tener dinero cambió algo en cómo tomás decisiones?", 1),
        ("¿Cuándo fue la última vez que le tuviste miedo al éxito más que al fracaso?", 1),
        ("¿Cuándo fue la última vez que el miedo a quedar en ridículo laboralmente te paralizó?", 1),
        ("¿Cuándo fue la última vez que el miedo a perder un trabajo o una fuente de ingresos te afectó de verdad?", 1),
        ("¿Cuándo fue la última vez que el miedo a no ser suficientemente bueno te impidió mostrarte?", 1),
        ("¿Cuándo fue la última vez que el miedo al juicio de los demás sobre tu carrera o tus decisiones económicas te pesó?", 1),
        ("¿Cuándo fue la última vez que el miedo a emprender algo nuevo ganó sobre las ganas de hacerlo?", 1),
        ("¿Cuándo fue la última vez que el miedo a la inestabilidad económica te hizo elegir la seguridad sobre lo que querías?", 1),
        ("¿Cuándo fue la última vez que el miedo al fracaso fue más poderoso que cualquier otra motivación?", 1),
        ("¿Cuándo fue la última vez que el miedo a no cumplir con lo que se espera de vos laboralmente te quitó el sueño?", 1),
        ("¿Cuándo fue la última vez que el miedo a pedir más —dinero, reconocimiento, oportunidades— te frenó?", 1),
        ("¿Cuándo fue la última vez que el miedo al fracaso te hizo trabajar más duro o más ansioso de lo necesario?", 1),
        ("¿Cuándo fue la última vez que el miedo a perder lo que construiste fue más fuerte que las ganas de seguir construyendo?", 1),
        ("¿Cuándo fue la última vez que el miedo a no ser exitoso te hizo comportarte de maneras que no son tuyas?", 1),
        ("¿Cuándo fue la última vez que le tuviste miedo al éxito porque significaba más responsabilidad?", 1),
        ("¿Cuándo fue la última vez que el miedo económico te generó un nivel de ansiedad que afectó otras áreas de tu vida?", 1),
        ("¿Cuándo fue la última vez que el miedo a ser un fraude —impostor— fue algo que te afectó laboralmente?", 1),
        ("¿Cuándo fue la última vez que el miedo a que te digan que no fue suficiente para no intentarlo?", 1),
        ("¿Cuándo fue la última vez que el miedo a no poder sostener algo que habías logrado fue más difícil que lograrlo?", 1),
        ("¿Cuándo fue la última vez que el miedo al fracaso fue también la razón por la que te esforzaste tanto?", 1),
        ("¿Cuándo fue la última vez que el miedo a la pobreza —aunque fuera lejana— moldeó una decisión importante?", 1),
        ("¿Cuándo fue la última vez que el miedo te hizo elegir la seguridad económica por encima de lo que realmente querías?", 1),
        ("¿Cuándo fue la última vez que el miedo al juicio de alguien que te importa sobre tus decisiones laborales te pesó?", 1),
        ("¿Cuándo fue la última vez que el miedo al fracaso reveló algo de tu relación con el éxito que preferirías no ver?", 2),
        ("¿Cuándo fue la última vez que el miedo económico fue una señal de que había algo más profundo que estabas ignorando?", 2),
        ("¿Cuándo fue la última vez que el miedo a no ser suficiente laboralmente te hizo dar cuenta de que tu autoestima estaba ligada a tu productividad?", 2),
        ("¿Cuándo fue la última vez que el miedo a perder fue más poderoso que el deseo de ganar?", 2),
        ("¿Cuándo fue la última vez que el miedo al fracaso te hizo actuar en contradicción con tus propios valores?", 2),
        ("¿Cuándo fue la última vez que el miedo a la inestabilidad económica te mostró algo de lo que más valorás?", 2),
        ("¿Cuándo fue la última vez que el miedo a que te vean fallar fue más difícil de manejar que el fracaso mismo?", 2),
        ("¿Cuándo fue la última vez que el miedo al éxito —a lo que viene después— fue más paralizante que el miedo al fracaso?", 2),
        ("¿Cuándo fue la última vez que el miedo económico te hizo darte cuenta de que hay cosas que no podés controlar y eso te liberó algo?", 2),
        ("¿Cuándo fue la última vez que el miedo al fracaso fue el motor más honesto de algo que lograste?", 2),
        ("¿Cuándo fue la última vez que el miedo al fracaso fue el espejo de algo de vos mismo que todavía no aceptaste?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que más te asusta no es el fracaso sino lo que el fracaso implicaría sobre quién sos?", 3),
        ("¿Cuándo fue la última vez que el miedo económico te conectó con un miedo más profundo sobre el valor que creés que tenés?", 3),
        ("¿Cuándo fue la última vez que el miedo al éxito fue más revelador de tu historia que cualquier otra cosa?", 3),
        ("¿Cuándo fue la última vez que el miedo al fracaso te mostró que lo que más te importa es lo que más podés perder?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que el miedo que más te paraliza laboralmente tiene raíces que van mucho más atrás de lo que querés admitir?", 3),
    ],

    "logros": [
        ("¿Cuándo fue la última vez que lograste algo profesional que te sorprendió?", 1),
        ("¿Cuándo fue la última vez que construiste algo —un proyecto, un negocio, una idea— y le viste vida propia?", 1),
        ("¿Cuándo fue la última vez que superaste un obstáculo económico que parecía imposible?", 1),
        ("¿Cuándo fue la última vez que algo que empezaste pequeño creció más de lo que esperabas?", 1),
        ("¿Cuándo fue la última vez que te animaste a pedir algo —un aumento, una oportunidad, un reconocimiento— y te lo dieron?", 1),
        ("¿Cuándo fue la última vez que lograste algo que al principio solo vos creías posible?", 1),
        ("¿Cuándo fue la última vez que completaste algo que llevaba tiempo parado?", 1),
        ("¿Cuándo fue la última vez que el fracaso fue el paso previo a un logro importante?", 1),
        ("¿Cuándo fue la última vez que un logro profesional te abrió una puerta que no esperabas?", 1),
        ("¿Cuándo fue la última vez que alguien confió en vos para algo importante y no los defraudaste?", 1),
        ("¿Cuándo fue la última vez que hiciste algo que te generó ingresos de algo que amabas?", 1),
        ("¿Cuándo fue la última vez que tomaste un riesgo económico y valió la pena?", 1),
        ("¿Cuándo fue la última vez que algo que construiste le sirvió a otra persona?", 1),
        ("¿Cuándo fue la última vez que lograste algo que nadie de tu entorno había logrado antes?", 1),
        ("¿Cuándo fue la última vez que el trabajo te hizo sentir que estabas exactamente donde tenés que estar?", 1),
        ("¿Cuándo fue la última vez que algo que persististe en hacer a pesar de los fracasos terminó siendo lo que más te define?", 1),
        ("¿Cuándo fue la última vez que un logro tuyo ayudó a alguien a creer en los suyos?", 1),
        ("¿Cuándo fue la última vez que algo que emprendiste solo generó trabajo o valor para otras personas?", 1),
        ("¿Cuándo fue la última vez que te diste el crédito que merecías por algo que lograste?", 1),
        ("¿Cuándo fue la última vez que lograste algo en el trabajo que te recordó para qué estás acá?", 1),
        ("¿Cuándo fue la última vez que un logro económico te dio la libertad de hacer algo que nunca antes podías?", 1),
        ("¿Cuándo fue la última vez que completaste algo que habías postergado y la sensación fue mejor de lo esperado?", 1),
        ("¿Cuándo fue la última vez que lograste convencer a alguien de una idea tuya y eso cambió algo?", 1),
        ("¿Cuándo fue la última vez que sentiste que lo que construiste laboralmente era también parte de quién sos?", 1),
        ("¿Cuándo fue la última vez que un logro profesional cambió algo profundamente en cómo te ves?", 2),
        ("¿Cuándo fue la última vez que el camino al éxito te costó algo que no habías calculado?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que el logro más importante fue el proceso, no el resultado?", 2),
        ("¿Cuándo fue la última vez que algo que construiste te sobrevivió de alguna manera?", 2),
        ("¿Cuándo fue la última vez que el éxito te enseñó algo que el fracaso no podría haberte dado?", 2),
        ("¿Cuándo fue la última vez que lograste algo y lo primero que pensaste fue compartirlo en lugar de guardarlo?", 2),
        ("¿Cuándo fue la última vez que un logro tuyo redefinió lo que creías que eras capaz de hacer?", 2),
        ("¿Cuándo fue la última vez que el éxito fue también el inicio de un miedo nuevo?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que tus logros también tenían un costo que vale la pena nombrar?", 2),
        ("¿Cuándo fue la última vez que lo que lograste fue también la prueba de que la persona en la que te convertiste es diferente a la que empezó?", 2),
        ("¿Cuándo fue la última vez que un logro profesional fue también un logro personal que no podrías haber tenido de otra manera?", 3),
        ("¿Cuándo fue la última vez que lo que construiste te hizo darte cuenta de que sos capaz de más de lo que la historia que te contaban sobre vos permitía?", 3),
        ("¿Cuándo fue la última vez que lograste algo y la persona que más querías que lo supiera no estaba para verlo?", 3),
        ("¿Cuándo fue la última vez que un logro económico o profesional fue también el resultado de haber superado algo de tu historia que te limitaba?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que lo que más te enorgullece no es lo más grande que lograste sino lo más honesto?", 3),
        ("¿Cuándo fue la última vez que lo que lograste fue también la demostración de que podés construir lo que necesitás aunque no esté dado?", 3),
    ],

    "sinFiltro": [
        ("¿Cuándo fue la última vez que dijiste que estabas muy ocupado cuando en realidad no lo estabas?", 1),
        ("¿Cuándo fue la última vez que exageraste cuánto ganás o cuánto progresás para quedar bien?", 1),
        ("¿Cuándo fue la última vez que envidiaste el éxito de alguien y lo disfrazaste de crítica?", 1),
        ("¿Cuándo fue la última vez que usaste el trabajo como excusa para no hacer algo que no querías?", 1),
        ("¿Cuándo fue la última vez que te atribuiste más crédito del que te correspondía por algo?", 1),
        ("¿Cuándo fue la última vez que dijiste que ibas a emprender algo y lo postergaste indefinidamente?", 1),
        ("¿Cuándo fue la última vez que gastaste plata de más para impresionar a alguien?", 1),
        ("¿Cuándo fue la última vez que fingiste entender de finanzas o economía para no quedar mal?", 1),
        ("¿Cuándo fue la última vez que te quejaste del trabajo pero no hiciste nada para cambiarlo?", 1),
        ("¿Cuándo fue la última vez que usaste el éxito como arma para sentirte mejor frente a alguien?", 1),
        ("¿Cuándo fue la última vez que dijiste que no importaba el dinero cuando en realidad sí importaba?", 1),
        ("¿Cuándo fue la última vez que cobraste por algo que hiciste mal y te hiciste el que no se dio cuenta?", 1),
        ("¿Cuándo fue la última vez que le pediste prestado a alguien sabiendo que iba a costar que lo devuelvas?", 1),
        ("¿Cuándo fue la última vez que prometiste algo en el trabajo que sabías que no podías cumplir?", 1),
        ("¿Cuándo fue la última vez que hablaste mal de un colega o competidor para quedar mejor vos?", 1),
        ("¿Cuándo fue la última vez que te hiciste el ocupado para no tener que atender algo que no querías?", 1),
        ("¿Cuándo fue la última vez que compraste algo innecesario para sentirte que estabas progresando?", 1),
        ("¿Cuándo fue la última vez que presentaste una idea ajena como si fuera tuya?", 1),
        ("¿Cuándo fue la última vez que dijiste que no te importaba el reconocimiento cuando en realidad te importaba muchísimo?", 1),
        ("¿Cuándo fue la última vez que hiciste algo en el trabajo por miedo al jefe y lo presentaste como iniciativa propia?", 1),
        ("¿Cuándo fue la última vez que te convenciste de que merecías algo que en realidad no te habías ganado?", 1),
        ("¿Cuándo fue la última vez que tu ego laboral hizo algo que después tuviste que limpiar?", 1),
        ("¿Cuándo fue la última vez que invertiste —o gasté— en algo ridículo con la esperanza de que te hiciera parecer más exitoso?", 1),
        ("¿Cuándo fue la última vez que usaste el 'no tengo tiempo' cuando en realidad era 'no quiero'?", 1),
        ("¿Cuándo fue la última vez que la envidia al éxito de alguien te movió más que tu propia motivación?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que competías con alguien de manera no declarada y estabas perdiendo?", 2),
        ("¿Cuándo fue la última vez que el ego laboral te costó algo que valía más que la razón por la que peleabas?", 2),
        ("¿Cuándo fue la última vez que usaste el trabajo para esconderte de algo que no querías enfrentar?", 2),
        ("¿Cuándo fue la última vez que saboteaste —consciente o no— algo tuyo porque te daba miedo que saliera bien?", 2),
        ("¿Cuándo fue la última vez que el dinero reveló algo de vos mismo que preferirías no ver?", 2),
        ("¿Cuándo fue la última vez que el éxito ajeno te hizo sentir que vos estabas fallando aunque no fuera así?", 2),
        ("¿Cuándo fue la última vez que la ambición te hizo hacer algo que no era del todo tuyo?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que trabajás de más para no pensar en algo que no querés pensar?", 2),
        ("¿Cuándo fue la última vez que el fracaso fue algo que le ocultaste a los demás más de lo necesario?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que la razón por la que trabajás tanto también es una forma de huir de algo?", 3),
        ("¿Cuándo fue la última vez que la ambición te reveló algo de vos mismo que todavía no sabés si querés cambiar?", 3),
        ("¿Cuándo fue la última vez que el fracaso fue algo que internamente viviste como una confirmación de algo que ya creías de vos mismo?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que el éxito que buscás tiene más que ver con lo que te faltó que con lo que querés?", 3),
        ("¿Cuándo fue la última vez que usaste el trabajo o la ambición como una coraza para no tener que ser vulnerable?", 3),
        ("¿Cuándo fue la última vez que el dinero fue el símbolo más honesto de algo que todavía no te das a vos mismo?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS13:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS13[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
