#!/usr/bin/env python3
"""Batch 7 - themes: work/career, money/finances, creativity, travel, learning, leadership, conflict resolution, habits, goals."""
import json

ADDITIONS7 = {
    "infancia": [
        ("¿Cuál fue el primer trabajo que imaginaste tener de grande?", 1),
        ("¿Hacías alguna 'empresa' o negocio inventado de chico?", 1),
        ("¿Cuánto ahorraba o gastaba tu familia en vacaciones cuando eras chico?", 1),
        ("¿Cuál fue la primera vez que ganaste algo de dinero por tu cuenta?", 1),
        ("¿Tenías algún lugar adonde ibas cuando querías crear algo solo?", 1),
        ("¿Cuál fue el viaje más largo que hiciste de chico?", 1),
        ("¿Qué materia escolar te hizo sentir por primera vez que eras bueno en algo?", 1),
        ("¿Cuándo fue la primera vez que organizaste algo para otros de chico?", 1),
        ("¿Cuál era la pelea más común que tenías con otros chicos?", 1),
        ("¿Cuándo aprendiste por primera vez a manejar un conflicto con alguien?", 1),
        ("¿Cuál fue el hábito que más te inculcaron de chico?", 1),
        ("¿Cuándo fue la primera vez que te propusiste una meta y la lograste?", 1),
        ("¿Cuál fue la primera vez que te diste cuenta de que el dinero importaba?", 1),
        ("¿Cuál era la actividad creativa a la que le dedicabas más horas?", 1),
        ("¿Qué lugar del mundo querías conocer cuando eras chico?", 1),
        ("¿Cuándo fue la primera vez que alguien te dijo que tenías talento para algo?", 1),
        ("¿Cuánto tiempo libre tenías de chico y qué hacías con él?", 1),
        ("¿Cuándo fue la primera vez que quisiste liderar algo y los otros te siguieron?", 1),
        ("¿Cuándo fue la primera vez que te tomaste en serio algo que para otros era un juego?", 1),
        ("¿Cuál fue el viaje de estudios o excursión escolar que más recordás?", 1),
        ("¿Cuál fue el primer libro que te cambió la manera de pensar?", 1),
        ("¿Cuándo fue la primera vez que un adulto te dejó tomar una decisión real?", 1),
        ("¿Cuándo fue la primera vez que tuviste que resolver un problema que los adultos no podían?", 2),
        ("¿Cuál fue la primera meta grande que te pusiste y que tardaste más de un año en cumplir?", 2),
        ("¿Cuándo fue la primera vez que entendiste que el esfuerzo no siempre se traduce en recompensa?", 2),
        ("¿Cuándo fue la primera vez que tuviste que negociar con alguien para conseguir algo?", 2),
        ("¿Cuál fue la primera vez que te diste cuenta de que había cosas que nunca aprenderías en el colegio?", 2),
        ("¿Cuándo fue la primera vez que una crisis económica familiar cambió algo en tu vida cotidiana?", 2),
        ("¿Cuándo fue la primera vez que sentiste que tenías algo único que aportar al mundo?", 2),
        ("¿Cuándo fue la primera vez que lideraste algo que salió mal y cómo lo manejaste?", 2),
        ("¿Cuándo fue la primera vez que aprendiste algo fuera del colegio que te importó más que lo que aprendías adentro?", 2),
        ("¿Cuándo fue la primera vez que tuviste que ceder en un conflicto aunque creías tener razón?", 2),
        ("¿Cuándo fue la primera vez que te diste cuenta de que un hábito tuyo molestaba a otros?", 2),
        ("¿Qué creencia sobre el trabajo o el éxito te plantaron de chico que todavía te cuesta cuestionar?", 3),
        ("¿Hubo algún momento de escasez en tu infancia que hoy moldea cómo te relacionás con el dinero?", 3),
        ("¿Cuál fue la primera vez que tomaste una decisión difícil sin que nadie te guiara?", 3),
        ("¿Qué le enseñaría tu yo de 10 años a tu yo de hoy sobre ser creativo sin miedo?", 3),
        ("¿Cuándo de chico te diste cuenta de que seguir las reglas y tener razón podían ser cosas distintas?", 3),
        ("¿Qué ambición tenías de chico que abandonaste y de la que hoy te preguntás por qué?", 3),
        ("¿Cuándo fue la primera vez que un fracaso te cambió más que un éxito?", 3),
        ("¿Qué te enseñó tu infancia sobre el poder y quiénes lo tenían que todavía afecta cómo te relacionás con la autoridad?", 3),
        ("¿Cuándo de chico te diste cuenta de que el mundo no era tan justo como te habían dicho?", 3),
        ("¿Cuál fue la primera decisión de la que te arrepentiste que te enseñó algo que no podías haber aprendido de otra manera?", 3),
        ("¿Cuándo fue la primera vez que entendiste que los adultos también tenían miedos?", 3),
        ("¿Qué parte de tu infancia te costó más trabajo integrar en quien sos hoy?", 3),
        ("¿Cuándo fue la primera vez que elegiste algo difícil por sobre algo cómodo y valió la pena?", 3),
        ("¿Qué hábito de trabajo o esfuerzo que hoy tenés aprendiste observando a alguien de tu infancia?", 3),
        ("¿Cuándo de chico sentiste que tenías que ganarte el lugar que otros tenían por defecto?", 3),
        ("¿Cuál fue el maestro o mentor de chico que más cambió lo que creías que podías lograr?", 3),
        ("¿Cuándo fue la primera vez que la creatividad te salvó de un problema que la fuerza no hubiera resuelto?", 3),
    ],

    "futuro": [
        ("¿Cuál es el trabajo que te gustaría estar haciendo en 5 años?", 1),
        ("¿Cuánto querés que cambie tu relación con el dinero en el futuro?", 1),
        ("¿Hay algún proyecto creativo que querés haber empezado antes de cumplir el próximo año?", 1),
        ("¿Cuál es el lugar del mundo que más querés conocer antes de los 50?", 1),
        ("¿Qué habilidad querés dominar que hoy no tenés?", 1),
        ("¿Te imaginas liderando algo en el futuro? ¿Qué?", 1),
        ("¿Cuál es el hábito que más querés haber incorporado en 1 año?", 1),
        ("¿Cuál es tu meta más concreta para los próximos 90 días?", 1),
        ("¿Qué tipo de trabajo te haría sentir que vale la pena levantarse todos los días?", 1),
        ("¿Cuánto te importa la independencia financiera como meta?", 1),
        ("¿Cuál es el estilo de vida que querés que tu trabajo financie?", 1),
        ("¿Hay algún país en el que te imaginarías viviendo en el futuro?", 1),
        ("¿Cuánto querés seguir aprendiendo activamente cuando seas mayor?", 1),
        ("¿Cómo querés manejar los conflictos en tus relaciones laborales futuras?", 1),
        ("¿Cuál es la meta que no contaste a casi nadie pero que más te importa?", 1),
        ("¿Hay algún viaje que querés hacer solo algún día?", 1),
        ("¿Qué tipo de líder querés ser en el futuro?", 1),
        ("¿Cuánto tiempo le querés dedicar a aprender algo nuevo en el futuro?", 1),
        ("¿Cuál es el hábito más destructivo que querés haber abandonado en 2 años?", 1),
        ("¿Cuánto de tu futuro ideal depende de acumular dinero vs. de tener tiempo libre?", 2),
        ("¿Cuál es el cambio de carrera que más te atraería aunque sea un salto al vacío?", 2),
        ("¿Cuándo fue la última vez que redefiniste lo que significa el éxito para vos?", 2),
        ("¿Cuánto de tu meta futura nació de un miedo y cuánto de un deseo genuino?", 2),
        ("¿Qué obstáculo interno tenés que superar para llegar a la versión de vos que más querés?", 2),
        ("¿Cuánto del futuro que imaginás te lo permitís realmente creer?", 2),
        ("¿Cuánto estás dispuesto a sacrificar hoy para tener la vida que querés mañana?", 2),
        ("¿Cuándo fue la última vez que hablaste de una meta difícil y no te arrepentiste de haberlo dicho?", 2),
        ("¿Cuánto de tu liderazgo futuro depende de aprender a liderar primero tu propia vida?", 2),
        ("¿Cuándo fue la última vez que te pusiste una meta que requería aprender algo desde cero?", 2),
        ("¿Cuándo fue la última vez que un conflicto que resolviste bien te mostró el tipo de persona que querés ser?", 2),
        ("¿Cuánto de la creatividad que querés aplicar en el futuro ya la tenés y simplemente no la usás?", 2),
        ("¿Cuándo fue la última vez que definiste lo que querés con más claridad que lo que no querés?", 2),
        ("¿Cuál es la meta que si no lográs te va a pesar más que cualquier otra?", 3),
        ("¿Qué versión del éxito estás persiguiendo que en el fondo no te pertenece?", 3),
        ("¿Cuánto de lo que querés construir en el futuro está motivado por demostrarle algo a alguien?", 3),
        ("¿Cuál es el precio real que estás pagando hoy por la vida que querés mañana?", 3),
        ("¿Si supieras que el camino que elegiste no lleva adonde creés, seguirías?", 3),
        ("¿Cuándo fue la última vez que te preguntaste si tus metas te iban a hacer feliz o solo exitoso?", 3),
        ("¿Cuál es el legado que querés dejar y cuánto estás haciendo hoy para que sea posible?", 3),
        ("¿Cuándo fue la última vez que tu imagen del futuro te dio tranquilidad en lugar de ansiedad?", 3),
        ("¿Cuál sería tu vida si no tuvieras que convencer a nadie de que tiene sentido?", 3),
        ("¿Cuánto de tus metas son tuyas y cuánto son las que el mundo esperaba que tuvieras?", 3),
        ("¿Cuándo fue la última vez que aprender algo te hizo cambiar una meta que creías definitiva?", 3),
        ("¿Cuál es el conflicto interno que más te frena para ir por lo que realmente querés?", 3),
        ("¿Cuándo fue la última vez que te animaste a liderar hacia algo sin saber el final?", 3),
        ("¿Cuánto del futuro que soñás depende de que primero cambies un hábito que todavía no cambiaste?", 3),
        ("¿Cuándo fue la última vez que imaginaste el futuro con entusiasmo genuino y sin autocensura?", 3),
        ("¿Cuál es la decisión que más vas a lamentar no haber tomado si no la tomás pronto?", 3),
        ("¿Cuándo fue la última vez que le dijiste a alguien una meta tuya que los dos sabían que era posible?", 3),
        ("¿Cuánto del camino hacia tus metas implica aprender a tolerar el conflicto en lugar de evitarlo?", 3),
    ],

    "amor": [
        ("¿Cuándo fue la última vez que trabajaste en equipo con tu pareja en algo concreto?", 1),
        ("¿Cómo manejás los conflictos de dinero cuando surgen en una relación?", 1),
        ("¿Cuál es la cosa más creativa que hiciste para sorprender a alguien que amabas?", 1),
        ("¿Hay algún lugar del mundo al que querés viajar con alguien especial?", 1),
        ("¿Qué aprendiste sobre el amor que solo la experiencia te pudo enseñar?", 1),
        ("¿Cuándo fue la última vez que admiraste a una pareja por cómo encaraba su trabajo?", 1),
        ("¿Hay algún hábito tuyo que mejoró gracias a alguien que amaste?", 1),
        ("¿Cuándo fue la última vez que vos y tu pareja tuvieron una meta en común?", 1),
        ("¿Qué tan importante es la ambición de la otra persona en una pareja para vos?", 1),
        ("¿Cuándo fue la última vez que resolvieron un conflicto de pareja y quedaron más unidos?", 1),
        ("¿Hay algún hábito de pareja que te gustaría incorporar?", 1),
        ("¿Cuándo fue la última vez que aprendiste algo nuevo gracias a quien amabas?", 1),
        ("¿Cuánto influye la compatibilidad económica en una relación para vos?", 1),
        ("¿Cuándo fue la última vez que un viaje fortaleció una relación?", 1),
        ("¿Cuál es la forma más creativa en que te demostraron amor?", 1),
        ("¿Cuándo fue la primera vez que un viaje mostró una faceta nueva de quien amabas?", 1),
        ("¿Cuándo fue la última vez que aprendiste algo de alguien que amabas que te hizo mejor persona?", 1),
        ("¿Qué tipo de liderazgo emocional valorás más en una pareja?", 1),
        ("¿Cuándo fue la última vez que un hábito nuevo de tu pareja se te contagió?", 1),
        ("¿Cuándo fue la última vez que acordaron una meta financiera como pareja?", 1),
        ("¿Cuándo fue la última vez que tuvieron un conflicto y lograste escuchar antes de responder?", 2),
        ("¿Cuánto de tus metas personales estás dispuesto a adaptar por una relación?", 2),
        ("¿Cuándo fue la última vez que la diferencia de mentalidad sobre el dinero generó tensión?", 2),
        ("¿Hay algún patrón de conflicto que repetís en el amor y que todavía no lograste romper?", 2),
        ("¿Cuánto de lo que aprendiste en tus relaciones cambió quién sos fuera de ellas?", 2),
        ("¿Cuándo fue la última vez que elegiste crecer dentro de una relación en vez de salir corriendo?", 2),
        ("¿Cuánto de tu liderazgo personal se activa o se apaga cuando estás en pareja?", 2),
        ("¿Cuándo fue la última vez que elegiste aprender algo para mejorar una relación?", 2),
        ("¿Cuándo fue la última vez que un conflicto de pareja te obligó a cambiar un hábito tuyo?", 2),
        ("¿Cuánto de las metas que tenés hoy están influenciadas por alguien que amaste?", 2),
        ("¿Cuándo fue la última vez que la diferencia de mentalidades sobre el trabajo generó fricción en pareja?", 2),
        ("¿Cuándo fue la última vez que la creatividad fue el lenguaje en el que mejor se entendieron como pareja?", 2),
        ("¿Cuándo fue la última vez que fuiste completamente honesto sobre lo que necesitabas en el amor?", 3),
        ("¿Cuál es el conflicto no resuelto que más pesa en tu historia amorosa?", 3),
        ("¿Cuánto del amor que dás viene de un lugar de abundancia y cuánto de querer llenar algo?", 3),
        ("¿Cuándo fue la última vez que te animaste a ser completamente auténtico con quien amabas aunque te costara la relación?", 3),
        ("¿Cuál es la meta de vida que nunca podrías sacrificar por ninguna pareja?", 3),
        ("¿Qué necesitás aprender de vos mismo para amar de la manera que realmente querés?", 3),
        ("¿Cuándo fue la última vez que el amor te obligó a crecer de una manera que no elegiste?", 3),
        ("¿Cuál es la verdad sobre el amor que tardaste más años en aceptar?", 3),
        ("¿Cuánto de los conflictos que tenés en el amor son en realidad conflictos con vos mismo?", 3),
        ("¿Cuándo fue la última vez que resolviste un conflicto de amor siendo el primero en ceder aunque no querías?", 3),
        ("¿Cuál es la creencia sobre el amor que más te cuesta cuestionar porque te define?", 3),
        ("¿Cuándo fue la última vez que elegiste aprender a amar diferente en lugar de esperar que el otro cambiara?", 3),
        ("¿Cuánto de tu historia laboral y creativa está entrelazada con las personas que amaste?", 3),
        ("¿Cuándo fue la última vez que una relación te llevó a un lugar del mundo que no hubieras descubierto solo?", 3),
        ("¿Cuál es el hábito en el amor que sabés que te hace daño y que seguís eligiendo?", 3),
        ("¿Cuándo fue la última vez que el amor te pidió más disciplina que pasión?", 3),
        ("¿Cuánto de lo que buscás en el amor hoy está informado por los errores que más te costaron?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que el mayor liderazgo en una relación era soltar el control?", 3),
    ],

    "familia": [
        ("¿Qué aprendiste sobre el trabajo o el esfuerzo de tu familia que todavía aplicás?", 1),
        ("¿Cómo hablaba tu familia del dinero cuando eras chico?", 1),
        ("¿Hay alguien en tu familia con un talento creativo que te sorprendió?", 1),
        ("¿Cuál fue el viaje familiar más significativo que recuerdes?", 1),
        ("¿Cuándo fue la primera vez que tu familia te apoyó en aprender algo nuevo?", 1),
        ("¿Hay alguien en tu familia que considerás un líder natural?", 1),
        ("¿Cómo resolvía los conflictos tu familia cuando eras chico?", 1),
        ("¿Cuál es el hábito familiar más útil que incorporaste a tu vida?", 1),
        ("¿Hay alguna meta que tenés en común con alguien de tu familia?", 1),
        ("¿Cuándo fue la primera vez que tu familia te enseñó a negociar o pedir lo que necesitabas?", 1),
        ("¿Cuál es la historia de trabajo duro de tu familia que más te marcó?", 1),
        ("¿Cuándo fue la última vez que aprendiste algo importante de un familiar menor que vos?", 1),
        ("¿Cuándo fue la última vez que tu familia te inspiró a ir por algo que te daba miedo?", 1),
        ("¿Cuál fue el negocio o emprendimiento de algún familiar que más admiraste?", 1),
        ("¿Cuándo fue la última vez que la creatividad de alguien de tu familia te sorprendió?", 1),
        ("¿Cuándo fue la última vez que hicieron un viaje familiar que les dejó algo importante?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te desafió a crecer?", 1),
        ("¿Qué hábito de ahorro o gasto de tu familia te resultó útil en la vida adulta?", 1),
        ("¿Cuándo fue la última vez que resolviste un conflicto familiar con más madurez de la que esperabas?", 1),
        ("¿Cuándo fue la última vez que tu familia mostró creatividad para resolver algo difícil?", 1),
        ("¿Cuánto influyó tu familia en tu relación con el dinero hoy?", 2),
        ("¿Hay algo que tu familia te enseñó sobre el conflicto que tuviste que desaprender?", 2),
        ("¿Cuándo fue la última vez que tuviste un conflicto familiar y saliste más entendido?", 2),
        ("¿Cuánto de tu ambición viene de querer hacer algo que tu familia no pudo?", 2),
        ("¿Cuándo fue la última vez que tu familia te cuestionó una meta y tuviste que defenderla?", 2),
        ("¿Cuánto de la creatividad que tenés la cultivaste con o a pesar de tu familia?", 2),
        ("¿Cuándo fue la última vez que aprender algo nuevo de un familiar cambió algo en vos?", 2),
        ("¿Cuánto de cómo liderás en tu vida adulta viene de lo que viste en tu familia?", 2),
        ("¿Cuándo fue la última vez que los hábitos de tu familia te generaron más problemas que soluciones?", 2),
        ("¿Cuándo fue la última vez que el dinero generó un conflicto en tu familia y cómo lo resolvieron?", 2),
        ("¿Cuándo fue la última vez que un viaje o experiencia compartida cambió la dinámica familiar?", 2),
        ("¿Cuánto de lo que sabés del mundo lo aprendiste gracias a viajes o experiencias que tu familia te dio?", 2),
        ("¿Cuándo fue la última vez que tu familia te ayudó a clarificar una meta que vos no podías ver solo?", 2),
        ("¿Cuál es la herida familiar relacionada con el trabajo o el dinero que todavía duele?", 3),
        ("¿Cuándo fue la última vez que elegiste un camino completamente diferente al de tu familia y tuviste que sostenerlo solo?", 3),
        ("¿Qué le estarías agradeciendo a tu familia dentro de 20 años que hoy todavía no podés?", 3),
        ("¿Cuándo fue la última vez que perdonaste a tu familia por una limitación económica o laboral que te afectó?", 3),
        ("¿Qué historia de tu familia necesitás reescribir para poder construir la tuya propia?", 3),
        ("¿Cuánto de lo que lograste o dejaste de lograr se explica por el punto de partida que te dio tu familia?", 3),
        ("¿Cuándo fue la última vez que un conflicto familiar te reveló algo sobre vos que no querías ver?", 3),
        ("¿Cuánto de tu creatividad fue apoyada o suprimida por tu familia y cómo eso te afectó?", 3),
        ("¿Cuándo fue la última vez que la mentalidad de tu familia sobre el dinero entró en colisión con la tuya?", 3),
        ("¿Qué hábito familiar negativo reconocés en vos mismo aunque jurabas que nunca lo ibas a repetir?", 3),
        ("¿Cuándo fue la primera vez que sentiste que tu familia no te podía seguir a donde querías ir?", 3),
        ("¿Cuándo fue la última vez que elegiste aprender algo de un familiar que no te caía bien?", 3),
        ("¿Cuánto de tu identidad laboral y creativa está en diálogo con lo que tu familia esperaba de vos?", 3),
        ("¿Cuándo fue la última vez que la sabiduría de alguien mayor de tu familia resolvió un conflicto mejor que cualquier solución tuya?", 3),
        ("¿Cuándo fue la primera vez que tu familia te reconoció como un líder dentro del hogar?", 3),
        ("¿Cuánto del camino laboral que elegiste fue para probarle algo a tu familia y cuánto fue genuinamente tuyo?", 3),
        ("¿Cuándo fue la primera vez que superaste a alguien de tu familia en algo que ellos valoraban y cómo te sentiste?", 3),
    ],

    "amistades": [
        ("¿Hay algún amigo que admires por la manera en que encaró su carrera?", 1),
        ("¿Cuándo fue la última vez que un amigo te dio un consejo sobre el dinero que te sirvió?", 1),
        ("¿Hay algún amigo con quien hayas tenido un proyecto creativo juntos?", 1),
        ("¿Cuál fue el mejor viaje que hiciste con amigos?", 1),
        ("¿Cuándo fue la última vez que aprendiste algo importante de un amigo?", 1),
        ("¿Hay algún amigo que admires por cómo lidera grupos?", 1),
        ("¿Cuándo fue la última vez que resolviste un conflicto con un amigo y salió bien?", 1),
        ("¿Cuál es el hábito que empezaste gracias a un amigo?", 1),
        ("¿Hay alguna meta que compartís con algún amigo?", 1),
        ("¿Cuándo fue la última vez que un amigo te motivó a ir por algo que vos no te animabas?", 1),
        ("¿Cuándo fue la última vez que hablaste con un amigo sobre metas a largo plazo?", 1),
        ("¿Hay algún amigo que cambió de trabajo o carrera radicalmente y te inspiró?", 1),
        ("¿Cuándo fue la última vez que un amigo te prestó o regaló algo de valor que cambió algo en tu vida?", 1),
        ("¿Cuándo fue la última vez que viajaste con un amigo y se conocieron más que en años de verse en la ciudad?", 1),
        ("¿Cuándo fue la última vez que un amigo te corrigió algo en tu trabajo o proyecto y tenía razón?", 1),
        ("¿Hay algún amigo cuyo hábito de estudio o trabajo siempre te generó algo de envidia sana?", 1),
        ("¿Cuándo fue la última vez que un amigo te confió un problema de dinero y pudiste ayudarlo?", 1),
        ("¿Cuándo fue la última vez que un amigo y vos emprendieron algo juntos aunque fuera pequeño?", 1),
        ("¿Cuándo fue la última vez que le agradeciste a un amigo por algo que aprendiste de él?", 1),
        ("¿Cuándo fue la última vez que un amigo te propuso una meta en común y la lograron juntos?", 1),
        ("¿Cuándo fue la última vez que tuviste que mediar en un conflicto entre amigos?", 2),
        ("¿Cuánto afectan las diferencias económicas las dinámicas en tu grupo de amigos?", 2),
        ("¿Cuándo fue la última vez que un amigo te cuestionó un hábito que te hacía daño?", 2),
        ("¿Hay alguna amistad que sobrevivió un conflicto fuerte y salió más sólida?", 2),
        ("¿Cuándo fue la última vez que un amigo te ayudó a ver una meta de manera diferente?", 2),
        ("¿Cuánto te influencian los hábitos y las metas de las personas con quienes más tiempo pasás?", 2),
        ("¿Cuándo fue la última vez que la diferencia de ingresos con un amigo generó tensión aunque nadie lo dijera?", 2),
        ("¿Cuándo fue la última vez que aprender algo de un amigo cambió una creencia que tenías?", 2),
        ("¿Cuándo fue la última vez que lideraste algo en un grupo de amigos sin habértelo propuesto?", 2),
        ("¿Cuándo fue la última vez que un amigo te hizo ver que un hábito tuyo los afectaba a los dos?", 2),
        ("¿Cuándo fue la última vez que un viaje con amigos reveló algo de la dinámica del grupo que antes no veías?", 2),
        ("¿Cuándo fue la última vez que una meta compartida con amigos fortaleció más la relación que cualquier otro momento?", 2),
        ("¿Cuándo fue la última vez que tuviste que resolver un conflicto entre tu carrera y una amistad?", 2),
        ("¿Cuándo fue la última vez que una amistad te exigió lo mejor de vos?", 3),
        ("¿Cuál es el amigo que más te desafía a crecer y por qué a veces es tan incómodo?", 3),
        ("¿Cuándo fue la última vez que resolviste un conflicto con un amigo de manera que requirió cambiar algo tuyo?", 3),
        ("¿Cuándo fue la última vez que una amistad te mostró un espejo de tus hábitos que no te gustó?", 3),
        ("¿Cuánto de quién sos laboralmente se formó gracias a amigos que creyeron en vos antes que vos mismo?", 3),
        ("¿Cuándo fue la última vez que la creatividad de un amigo te sacó de un estancamiento que no podías resolver solo?", 3),
        ("¿Cuándo fue la última vez que elegiste una amistad sobre una oportunidad económica o laboral y no te arrepentiste?", 3),
        ("¿Cuándo fue la última vez que un amigo te desafió a ver el mundo diferente y lo aceptaste aunque dolió?", 3),
        ("¿Cuál es la meta que nunca hubieras perseguido si no hubieras tenido un amigo que te la recordaba?", 3),
        ("¿Cuándo fue la última vez que una amistad te salvó de un hábito que te estaba destruyendo?", 3),
        ("¿Cuánto del liderazgo que ejercés hoy lo aprendiste de amigos que confiaron en vos antes que nadie?", 3),
        ("¿Cuándo fue la última vez que una diferencia de valores entre amigos generó un conflicto que cambió la dinámica para siempre?", 3),
        ("¿Cuándo fue la última vez que un amigo te confrontó sobre tu relación con el dinero o el éxito?", 3),
        ("¿Cuándo fue la última vez que viajaste con un amigo y volvieron distintos a como eran antes de salir?", 3),
        ("¿Cuándo fue la última vez que el aprendizaje compartido con un amigo fue más valioso que cualquier curso?", 3),
        ("¿Cuándo fue la última vez que pusiste el bienestar de una amistad por sobre tu propia comodidad?", 3),
        ("¿Cuándo fue la última vez que un amigo te hizo ver que una meta tuya era más tuya de lo que creías?", 3),
    ],

    "exs": [
        ("¿Cuándo fue la primera vez que el trabajo o la carrera de una pareja afectó la relación?", 1),
        ("¿Hay alguna ex relación donde la diferencia en cómo manejaban el dinero fue un problema?", 1),
        ("¿Cuándo fue la primera vez que viajaste con una pareja y descubriste algo nuevo de vos mismo?", 1),
        ("¿Cuál fue la cosa más creativa que hicieron juntos en una relación?", 1),
        ("¿Qué aprendiste sobre el aprendizaje o el crecimiento de alguna relación pasada?", 1),
        ("¿Cuándo fue la primera vez que un ex te desafió a ser mejor en algo?", 1),
        ("¿Cuál fue el conflicto más difícil que resolvieron bien en una relación?", 1),
        ("¿Hay algún hábito que adquiriste de una ex pareja que todavía tenés?", 1),
        ("¿Cuándo fue la primera vez que compartiste una meta a largo plazo con una pareja?", 1),
        ("¿Hay algún ex que te haya cambiado la visión sobre el trabajo o la carrera?", 1),
        ("¿Cuándo fue la primera vez que hiciste un viaje largo con una pareja y cambió algo entre ustedes?", 1),
        ("¿Cuándo fue la primera vez que reconociste que una pareja pasada te había enseñado a ser más generoso?", 1),
        ("¿Hay alguna relación del pasado en la que la diferencia de metas laborales fue determinante para que terminara?", 1),
        ("¿Cuándo fue la primera vez que una pareja te presentó a una actividad o trabajo que no conocías y te cambió?", 1),
        ("¿Cuándo fue la primera vez que viajaste solo después de una ruptura?", 1),
        ("¿Cuándo fue la primera vez que resolviste un conflicto con una ex pareja mucho después de haber terminado?", 1),
        ("¿Hay alguna ex relación de la que todavía tomás decisiones económicas diferente gracias a lo que aprendiste?", 1),
        ("¿Cuándo fue la primera vez que una pareja te motivó a desarrollar un hábito creativo que todavía tenés?", 1),
        ("¿Cuándo fue la primera vez que admitiste que una ruptura tuya no fue solo culpa de la otra persona?", 1),
        ("¿Cuándo fue la primera vez que el liderazgo que mostraste en una relación fue más parte del problema que de la solución?", 1),
        ("¿Cuándo fue la última vez que el conflicto no resuelto arruinó algo bueno?", 2),
        ("¿Cuánto de cómo manejás el dinero hoy tiene raíces en una relación pasada?", 2),
        ("¿Cuándo fue la última vez que reconociste que una meta que perseguías era para impresionar a alguien del pasado?", 2),
        ("¿Cuál fue el conflicto que más te enseñó sobre cómo no querés relacionarte?", 2),
        ("¿Cuánto de lo que lograste después de una ruptura vino de querer demostrar algo?", 2),
        ("¿Cuándo fue la última vez que encontraste un hábito de una relación pasada que te hacía bien y lo recuperaste?", 2),
        ("¿Cuándo fue la última vez que reconociste que aprendiste más de una relación difícil que de una fácil?", 2),
        ("¿Cuánto de tu relación con el dinero cambió en las relaciones pasadas y cómo eso afecta las actuales?", 2),
        ("¿Cuándo fue la última vez que la creatividad fue lo primero que perdiste cuando una relación entró en crisis?", 2),
        ("¿Cuándo fue la última vez que entendiste el rol que vos jugaste en un conflicto de pareja del pasado?", 2),
        ("¿Cuándo fue la última vez que un viaje post-ruptura te enseñó algo sobre vos mismo?", 2),
        ("¿Cuándo fue la última vez que un ex te mostró una forma de liderar una vida que todavía admirás?", 2),
        ("¿Cuándo fue la última vez que un hábito que adoptaste de una relación pasada te ayudó en una situación nueva?", 2),
        ("¿Cuándo fue la última vez que una ruptura te obligó a redefinir completamente tus metas?", 3),
        ("¿Cuánto de quién sos laboralmente y creativamente fue moldeado por alguien que amaste?", 3),
        ("¿Cuál es la creencia sobre el éxito o el fracaso que te quedó de una relación pasada y que todavía afecta cómo vivís?", 3),
        ("¿Cuándo fue la última vez que te diste cuenta de que los hábitos de una relación pasada seguían determinando los tuyos sin que lo elegirías?", 3),
        ("¿Cuánto de la manera en que resolvés conflictos hoy fue moldeada por relaciones que te enseñaron a pelear mal?", 3),
        ("¿Cuándo fue la última vez que un recuerdo de una relación pasada te enseñó algo nuevo sobre vos mismo?", 3),
        ("¿Cuándo fue la última vez que reconociste que una ruptura que entonces pareció un fracaso fue en realidad el punto de partida de algo mejor?", 3),
        ("¿Cuánto de tu relación con la creatividad está ligada a alguien que alguna vez te dijo que eras bueno o que eras malo en algo?", 3),
        ("¿Cuándo fue la última vez que elegiste aprender de una relación pasada en lugar de solo juzgarla?", 3),
        ("¿Cuánto del liderazgo que hoy ejercés en tu vida fue moldeado por relaciones donde fuiste o no el que lideraba?", 3),
        ("¿Cuándo fue la última vez que el dinero en una relación pasada fue una metáfora de algo mucho más profundo?", 3),
        ("¿Cuándo fue la última vez que un viaje con una ex pareja todavía aparece en sueños o en recuerdos?", 3),
        ("¿Cuánto de lo que lograste después de una ruptura importante fue para demostrarle algo al que se fue?", 3),
        ("¿Cuándo fue la última vez que perdonaste a alguien del pasado de verdad, sin necesitar que lo supiera?", 3),
        ("¿Cuándo fue la última vez que una relación pasada te hizo ver un límite tuyo que no sabías que tenías?", 3),
        ("¿Cuándo fue la primera vez que entendiste que la resolución de conflictos en pareja era una habilidad que se aprende?", 3),
        ("¿Cuánto de quién sos en el trabajo y en la vida es una respuesta directa a quién te dijeron que eras en una relación pasada?", 3),
    ],

    "personalidad": [
        ("¿Cómo describís tu relación con el trabajo en una sola palabra?", 1),
        ("¿Cuál es tu actitud natural cuando hay un conflicto: avanzar, evitar o mediar?", 1),
        ("¿Cuándo fue la última vez que te permitiste ser creativo sin ningún objetivo?", 1),
        ("¿Qué tipo de viaje dice más de vos: mochila, todo incluido o algo intermedio?", 1),
        ("¿Cuándo fue la última vez que aprendiste algo nuevo que te entusiasmó genuinamente?", 1),
        ("¿Te sentís más cómodo siendo líder o siendo parte del equipo?", 1),
        ("¿Cuándo fue la última vez que cambiaste un hábito que te estaba frenando?", 1),
        ("¿Cuál es la meta que más te cuesta no convertir en obsesión?", 1),
        ("¿Cuándo fue la última vez que tomaste una decisión financiera de la que te sentiste orgulloso?", 1),
        ("¿Cuánto de tu identidad está ligada a lo que producís o creás?", 1),
        ("¿Cuándo fue la última vez que resolviste un conflicto sin tener que ganar?", 1),
        ("¿Cuánto te cuesta pedir ayuda para algo en lo que querés ser bueno?", 1),
        ("¿Cuándo fue la última vez que te fuiste de viaje y volviste diferente?", 1),
        ("¿Cuándo fue la última vez que fallaste en una meta y no te castigaste?", 1),
        ("¿Cuál es la cosa que más te cuesta aprender aunque querés mucho hacerlo?", 1),
        ("¿Cuándo fue la última vez que tu curiosidad te llevó a algo mejor de lo que planificabas?", 1),
        ("¿Cómo te relacionás con el dinero: lo perseguís, lo ignorás o lo administrás?", 1),
        ("¿Cuándo fue la última vez que hiciste algo creativo que no era 'tu estilo'?", 1),
        ("¿Cuándo fue la última vez que aprender algo te hizo sentir vulnerable?", 1),
        ("¿Cuándo fue la última vez que lideraste algo informal y lo disfrutaste?", 1),
        ("¿Cuándo fue la última vez que un conflicto te reveló algo de vos que no sabías?", 1),
        ("¿Cuándo fue la última vez que te comprometiste con un hábito por más de 30 días?", 1),
        ("¿Cuándo fue la última vez que una meta que lograste cambió cómo te ves a vos mismo?", 1),
        ("¿Cuándo fue la última vez que el dinero fue un termómetro de algo más profundo en tu vida?", 1),
        ("¿Cuándo fue la última vez que alguien más vio tus habilidades antes que vos?", 1),
        ("¿Cuándo fue la última vez que hiciste algo solo por el placer de crearlo sin resultado final?", 1),
        ("¿Cuándo fue la última vez que un viaje corto te recargó más que unas vacaciones largas?", 1),
        ("¿Cuándo fue la última vez que aprender algo te hizo sentir completamente vivo?", 1),
        ("¿Cuándo fue la última vez que elegiste resolver un conflicto en lugar de evitarlo?", 1),
        ("¿Cuánto de tu estilo de liderazgo viene de lo que no te gustó en líderes que tuviste?", 2),
        ("¿Cuándo fue la última vez que tu relación con el dinero te dijo algo sobre tus valores?", 2),
        ("¿Cuándo fue la última vez que resolviste un conflicto siendo el primero en ceder?", 2),
        ("¿Cuánto de lo que creás refleja quién sos realmente?", 2),
        ("¿Cuándo fue la última vez que te comprometiste con una meta sin saber el resultado?", 2),
        ("¿Cuánto de tus hábitos diarios están alineados con lo que decís que querés?", 2),
        ("¿Cuándo fue la última vez que aprender algo nuevo te cambió una creencia que tenías?", 2),
        ("¿Cuándo fue la última vez que tuviste que liderar algo sin quererlo y lo hiciste igual?", 3),
        ("¿Cuánto de tu relación con el trabajo y el dinero viene de heridas que todavía no sanaron?", 3),
        ("¿Cuándo fue la última vez que una meta que lograste te dejó un vacío inesperado?", 3),
        ("¿Cuál es el hábito que más define quién sos aunque preferirías que no fuera así?", 3),
        ("¿Cuándo fue la última vez que te animaste a crear algo sin saber si era bueno?", 3),
        ("¿Cuánto de tu potencial seguís sin explorar por miedo a no ser suficientemente bueno?", 3),
        ("¿Cuándo fue la última vez que resolviste un conflicto sin tener que tener razón?", 3),
        ("¿Cuál es el costo real de los hábitos que todavía no pudiste cambiar?", 3),
        ("¿Cuándo fue la última vez que un viaje te devolvió algo de vos mismo que habías perdido?", 3),
        ("¿Cuánto de tu identidad laboral y creativa está construida sobre lo que creés que merecés?", 3),
        ("¿Cuándo fue la última vez que aprendiste algo que destruyó una certeza que sostenías hace años?", 3),
        ("¿Cuándo fue la última vez que lideraste siendo completamente honesto aunque te exponía?", 3),
        ("¿Cuándo fue la última vez que el dinero o su ausencia te reveló lo que realmente valorás?", 3),
        ("¿Cuánto de quién sos en el conflicto es quién elegís ser y cuánto es quién no podés evitar ser?", 3),
    ],

    "miedos": [
        ("¿Le tenés miedo al fracaso laboral o al éxito que trae más responsabilidad?", 1),
        ("¿Cuándo fue la última vez que el miedo al dinero te hizo tomar una mala decisión?", 1),
        ("¿Le tenés miedo a que lo que creás no sea suficientemente bueno?", 1),
        ("¿Hay algún destino de viaje que evitás por miedo?", 1),
        ("¿Le tenés miedo a quedar expuesto como alguien que no sabe lo que hace?", 1),
        ("¿Le tenés miedo a liderar y que te vean fallar?", 1),
        ("¿Cuándo fue la última vez que el miedo al conflicto te hizo callar algo importante?", 1),
        ("¿Le tenés miedo a los hábitos que no podés cambiar?", 1),
        ("¿Cuándo fue la última vez que el miedo te impidió ir por una meta importante?", 1),
        ("¿Le tenés miedo a estancarte en lo laboral?", 1),
        ("¿Le tenés miedo a que aprender algo nuevo revele que sabías menos de lo que creías?", 1),
        ("¿Le tenés miedo a viajar solo?", 1),
        ("¿Le tenés miedo a ser creativo en público?", 1),
        ("¿Le tenés miedo a hacer una sola cosa bien en lugar de muchas cosas más o menos?", 1),
        ("¿Le tenés miedo a ganar dinero que no sabés cómo administrar?", 1),
        ("¿Le tenés miedo a dejar un trabajo seguro por algo que te apasiona?", 1),
        ("¿Le tenés miedo a aprender algo que te obligue a reconstruirte desde cero?", 1),
        ("¿Le tenés miedo a lanzar algo al mundo que te identifique y no guste?", 1),
        ("¿Le tenés miedo a la rutina que construís con tus hábitos?", 1),
        ("¿Le tenés miedo a no poder resolver los conflictos más importantes de tu vida?", 1),
        ("¿Cuándo fue la última vez que el miedo a un conflicto te hizo perder algo que querías?", 2),
        ("¿Cuánto del miedo financiero que tenés tiene base real y cuánto es heredado?", 2),
        ("¿Cuándo fue la última vez que el miedo a lo que dirían te impidió ser creativo?", 2),
        ("¿Cuánto miedo te genera la posibilidad de tener que cambiar completamente de rumbo laboral?", 2),
        ("¿Cuándo fue la última vez que el miedo a liderar te hizo retroceder?", 2),
        ("¿Cuánto del miedo que tenés a ciertas metas tiene más que ver con lo que significa si no las lográs?", 2),
        ("¿Cuándo fue la última vez que el miedo a aprender algo nuevo te frenó?", 2),
        ("¿Cuándo fue la última vez que el miedo a un viaje o experiencia nueva te hizo perder algo?", 2),
        ("¿Cuánto del miedo al conflicto viene de no confiar en que podés sobrevivir lo que salga?", 2),
        ("¿Cuándo fue la última vez que el miedo a un hábito malo te paralizó en lugar de moverte al cambio?", 2),
        ("¿Cuándo fue la última vez que el miedo a no tener suficiente dinero te hizo trabajar más de lo que debías?", 2),
        ("¿Cuándo fue la última vez que el miedo a aprender algo que cambiara todo te hizo evitarlo?", 2),
        ("¿Cuándo fue la última vez que el miedo a ser visto como un líder te hizo esconderte?", 2),
        ("¿Cuál es el miedo más profundo que tenés sobre tu carrera o tu propósito?", 3),
        ("¿Cuándo fue la última vez que el miedo a quedarte sin dinero te hizo actuar de una manera que no querés repetir?", 3),
        ("¿Cuál es el miedo a la creatividad o a mostrarte que más te ha costado en la vida?", 3),
        ("¿Cuándo fue la última vez que un miedo al conflicto te hizo traicionarte a vos mismo?", 3),
        ("¿Cuándo fue la última vez que el miedo te hizo rechazar un viaje o experiencia que en retrospectiva hubiera cambiado todo?", 3),
        ("¿Cuánto del miedo que tenés al aprendizaje está relacionado con el miedo a descubrir que podrías haber sido más?", 3),
        ("¿Cuándo fue la última vez que el miedo a un hábito que no podés cambiar te definió más de lo que querías?", 3),
        ("¿Cuándo fue la última vez que el miedo a liderar fue en realidad miedo a ser visto?", 3),
        ("¿Cuándo fue la última vez que el miedo a una meta importante te hizo saboetarla antes de empezarla?", 3),
        ("¿Cuánto del miedo financiero que sentís es en realidad miedo a tener que elegir quién sos sin el dinero como excusa?", 3),
        ("¿Cuándo fue la última vez que el miedo a aprender algo difícil fue el miedo más honesto que sentiste?", 3),
        ("¿Cuándo fue la última vez que el miedo a ser creativo fue más fuerte que el deseo de crear?", 3),
        ("¿Cuándo fue la última vez que el miedo al conflicto te costó una meta que realmente querías?", 3),
        ("¿Cuándo fue la última vez que el miedo al liderazgo te hizo elegir ser seguidor cuando eras el más indicado?", 3),
        ("¿Cuánto del miedo que tenés a cambiar tus hábitos está relacionado con el miedo a ser otra persona?", 3),
        ("¿Cuándo fue la última vez que el miedo a los viajes o a lo nuevo fue en realidad miedo a lo que podías descubrir de vos?", 3),
        ("¿Cuándo fue la última vez que un miedo que creías superado volvió con más fuerza en el contexto laboral?", 3),
    ],

    "logros": [
        ("¿Cuál fue el logro laboral que más esfuerzo te costó?", 1),
        ("¿Cuándo fue la primera vez que tomaste una buena decisión financiera?", 1),
        ("¿Cuál fue la cosa más creativa que lograste y que te sorprendió a vos mismo?", 1),
        ("¿Cuál fue el viaje que más te expandió?", 1),
        ("¿Cuándo fue la última vez que aprender algo nuevo te abrió una puerta?", 1),
        ("¿Cuándo fue la primera vez que te pusiste en un rol de liderazgo y lo disfrutaste?", 1),
        ("¿Cuándo fue la última vez que resolviste un conflicto de manera que te enorgullece?", 1),
        ("¿Cuál es el hábito que más costó incorporar y que más valor te trajo?", 1),
        ("¿Cuándo fue la primera vez que cumpliste una meta que te habías prometido a vos mismo?", 1),
        ("¿Cuándo fue la última vez que tu trabajo le dio algo real a alguien más?", 1),
        ("¿Cuál fue el logro que requirió que aprendieras a pedir ayuda?", 1),
        ("¿Cuándo fue la última vez que un logro tuyo sorprendió a alguien que no creía en vos?", 1),
        ("¿Cuándo fue la primera vez que lograste algo después de un viaje que te cambió?", 1),
        ("¿Cuándo fue la primera vez que una habilidad creativa te abrió una puerta laboral?", 1),
        ("¿Cuál fue el logro que más implicó aprender algo completamente nuevo?", 1),
        ("¿Cuándo fue la primera vez que lideraste un proceso y el resultado fue mejor de lo que esperabas?", 1),
        ("¿Cuándo fue la primera vez que tu hábito más consistente te llevó a un logro que otros no podían ver venir?", 1),
        ("¿Cuándo fue la primera vez que resolviste un conflicto y te dijeron que lo habías manejado bien?", 1),
        ("¿Cuándo fue la primera vez que una meta financiera a largo plazo se concretó?", 1),
        ("¿Cuándo fue la primera vez que usar la creatividad en un problema práctico cambió el resultado?", 1),
        ("¿Cuándo fue la última vez que tomaste una decisión financiera difícil que dio frutos?", 2),
        ("¿Cuándo fue la última vez que lideraste algo sin ningún reconocimiento y siguió valiendo la pena?", 2),
        ("¿Cuál fue el logro que requirió que superaras el mayor conflicto interno tuyo?", 2),
        ("¿Cuándo fue la última vez que cambiar un hábito fue el catalizador de un logro importante?", 2),
        ("¿Cuándo fue la última vez que aprender algo que no querías aprender te transformó?", 2),
        ("¿Cuándo fue la última vez que un logro creativo te hizo sentir más vos mismo?", 2),
        ("¿Cuándo fue la última vez que un viaje fue el catalizador de un logro personal importante?", 2),
        ("¿Cuándo fue la última vez que resolver un conflicto fue en sí mismo el logro más importante?", 2),
        ("¿Cuándo fue la última vez que un logro financiero te confirmó que ibas por el camino correcto?", 2),
        ("¿Cuándo fue la última vez que aprender de un fracaso fue más valioso que cualquier éxito anterior?", 2),
        ("¿Cuándo fue la última vez que lideraste algo que ayudó a otros a lograr más de lo que creían posible?", 2),
        ("¿Cuándo fue la última vez que el hábito más pequeño que tenés fue el que hizo posible el logro más grande?", 2),
        ("¿Cuándo fue la última vez que una meta que pusiste un año atrás la mirás y no podés creer que la lograste?", 2),
        ("¿Cuál es el logro que más le debe a alguien que te desafió cuando no querías ser desafiado?", 3),
        ("¿Cuándo fue la última vez que lograste algo que requirió que fueras completamente honesto con vos mismo sobre tus limitaciones?", 3),
        ("¿Cuál es el logro que si mirás de cerca tiene raíces en algo que alguna vez consideraste un fracaso?", 3),
        ("¿Cuándo fue la última vez que un logro creativo te hizo entender algo de vos mismo que nunca habías visto?", 3),
        ("¿Cuándo fue la última vez que el logro más importante de tu vida fue producto de un conflicto que nunca elegiste?", 3),
        ("¿Cuándo fue la última vez que un logro tuyo fue posible porque alguien creyó en vos antes de que vos creyeras?", 3),
        ("¿Cuándo fue la última vez que lograste algo que te hizo repensar completamente qué tipo de líder querés ser?", 3),
        ("¿Cuándo fue la última vez que un logro financiero no alcanzó para llenarte y entendiste que buscabas otra cosa?", 3),
        ("¿Cuándo fue la última vez que aprender algo difícil fue el camino hacia el logro que más te costó admitir que querías?", 3),
        ("¿Cuándo fue la última vez que cambiar un hábito profundo fue el logro más significativo aunque nadie lo viera?", 3),
        ("¿Cuándo fue la última vez que un viaje te llevó a un logro que no esperabas?", 3),
        ("¿Cuál es el logro que más te cambió la manera de ver el conflicto?", 3),
        ("¿Cuándo fue la última vez que el logro más difícil fue simplemente seguir cuando querías parar?", 3),
        ("¿Cuándo fue la última vez que aprender algo que te quitó certezas fue el logro más importante del año?", 3),
        ("¿Cuándo fue la última vez que lideraste hacia algo sin saber el resultado y fue el logro que más te enorgullece?", 3),
        ("¿Cuándo fue la última vez que un conflicto que resolviste bien fue el punto de inflexión de todo lo demás?", 3),
        ("¿Cuándo fue la última vez que la disciplina de un hábito pequeño fue el puente hacia el logro más grande de tu vida?", 3),
    ],

    "sinFiltro": [
        ("¿Cuántas veces al mes hacés algo que se supone que es trabajo y lo hacés en pijama?", 1),
        ("¿Cuándo fue la última vez que gastaste dinero en algo ridículo y lo volvería a hacer?", 1),
        ("¿Cuántas veces empezaste un proyecto creativo que abandonaste antes de terminar?", 1),
        ("¿Cuándo fue la última vez que hiciste un viaje y odiaste la mitad del tiempo pero igual lo recomendarías?", 1),
        ("¿Cuántas veces pagaste un curso online que nunca terminaste?", 1),
        ("¿Cuándo fue la última vez que fingiste saber más de lo que sabías frente a alguien?", 1),
        ("¿Cuántas veces evitaste un conflicto con la excusa de que 'no era el momento'?", 1),
        ("¿Cuántas veces te propusiste una meta un lunes que olvidaste el jueves?", 1),
        ("¿Cuándo fue la última vez que hiciste algo que se llama 'invertir en vos' pero en realidad era solo gastarte la plata?", 1),
        ("¿Cuántas veces prometiste cambiar un hábito el 1 de enero y lo recordaste recién en marzo?", 1),
        ("¿Cuántas apps de productividad tenés instaladas que no usás?", 1),
        ("¿Cuándo fue la última vez que evitaste resolver un conflicto esperando que el otro lo olvidara?", 1),
        ("¿Cuántas veces te vendiste como experto en algo que aprendiste esa misma semana?", 1),
        ("¿Cuándo fue la última vez que fuiste de viaje 'para desconectarte' y miraste el celular cada 10 minutos?", 1),
        ("¿Cuántas veces usaste 'soy creativo' como excusa para no terminar algo?", 1),
        ("¿Cuántas horas de cursos compraste en Udemy o similares que suman más de 200 horas sin terminar?", 1),
        ("¿Cuántas veces dijiste que ibas a arreglar ese conflicto 'cuando estés listo' y ya pasaron 6 meses?", 1),
        ("¿Cuánto dinero gastaste en el último año en cosas para un hobby que casi no practicás?", 1),
        ("¿Cuántas veces lideraste algo y cuando salió mal le echaste la culpa al contexto?", 1),
        ("¿Cuántas metas tenés escritas en algún lugar que no tocás desde hace más de un año?", 1),
        ("¿Cuándo fue la última vez que lideraste algo y mandaste todo a la mierda a la mitad?", 2),
        ("¿Alguna vez hiciste algo 'por dinero' que te avergüenza admitir aunque no era ilegal?", 2),
        ("¿Cuántas veces dijiste que eras 'creativo' para justificar el caos que te rodeaba?", 2),
        ("¿Alguna vez usaste la excusa del 'aprendizaje' para no tomar una decisión que tenías miedo de tomar?", 2),
        ("¿Cuándo fue la última vez que te convenciste de que un hábito malo era 'parte de tu personalidad'?", 2),
        ("¿Cuándo fue la última vez que pusiste el conflicto debajo de la alfombra y 6 meses después explotó?", 2),
        ("¿Alguna vez te fuiste de viaje para escapar de algo y lo encontraste esperándote cuando volviste?", 2),
        ("¿Cuántas veces te prometiste que después de ese logro ibas a descansar y el descanso nunca llegó?", 2),
        ("¿Cuántas veces lideraste a alguien diciéndole lo que quería escuchar en lugar de lo que necesitaba?", 2),
        ("¿Cuándo fue la última vez que la creatividad fue tu excusa perfecta para no hacer el trabajo aburrido que tenías que hacer?", 2),
        ("¿Cuándo fue la última vez que hiciste algo que violaba un valor tuyo por dinero o por status?", 3),
        ("¿Cuál es la meta que seguís proclamando que tenés pero que en realidad ya sabés que no vas a perseguir?", 3),
        ("¿Cuándo fue la última vez que tu mayor logro fue en realidad compensar algo que te daba vergüenza de vos mismo?", 3),
        ("¿Cuál es el hábito que sabés que te destruye lentamente y que seguís eligiendo de todos modos?", 3),
        ("¿Cuándo fue la última vez que saboteas un viaje o experiencia nueva para no tener que cambiar?", 3),
        ("¿Cuándo fue la última vez que tu manera de resolver conflictos fue en realidad ganar la pelea a cualquier costo?", 3),
        ("¿Cuándo fue la última vez que lideraste algo motivado por ego en lugar de por convicción y no lo dijiste?", 3),
        ("¿Cuándo fue la última vez que el dinero fue la razón real aunque dijiste que era otra cosa?", 3),
        ("¿Cuántas veces te vendiste una historia sobre el aprendizaje para justificar que no actuaras todavía?", 3),
        ("¿Cuándo fue la última vez que un conflicto que resolviste 'bien' fue en realidad una victoria disfrazada de paz?", 3),
        ("¿Cuándo fue la última vez que la creatividad fue el escudo perfecto para no enfrentar lo que en realidad te asusta?", 3),
        ("¿Cuándo fue la última vez que una meta que perseguiste fue más para no sentirte un fracasado que porque la querías?", 3),
        ("¿Cuándo fue la última vez que los hábitos que 'estás cambiando' son los mismos de hace 5 años?", 3),
        ("¿Cuándo fue la última vez que usaste un viaje para huir de una decisión que sabías que tenías que tomar?", 3),
        ("¿Cuándo fue la última vez que aprendiste algo nuevo para postergar hacer lo que ya sabías que tenías que hacer?", 3),
        ("¿Cuándo fue la última vez que lideraste algo y el resultado bueno fue suerte pero igual lo vendiste como habilidad?", 3),
        ("¿Cuándo fue la última vez que el dinero te hizo actuar de una manera que si te vieran hacerlo no reconocerías?", 3),
        ("¿Cuándo fue la última vez que la resolución de un conflicto fue en realidad hacer que el otro se sintiera mal?", 3),
        ("¿Cuándo fue la última vez que un hábito que decís que querés cambiar en realidad te conviene que siga como está?", 3),
        ("¿Cuándo fue la última vez que una meta que lograste fue para llenar un vacío que sigue ahí?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS7:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS7[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
