#!/usr/bin/env python3
"""Batch 11 - music, art, books, movies, culture, entertainment."""
import json

ADDITIONS11 = {
    "infancia": [
        ("¿Cuál fue la primera canción que te sabías de memoria?", 1),
        ("¿Cuándo fue la primera vez que viste una película que te dejó sin palabras?", 1),
        ("¿Cuál era tu dibujo animado favorito y por qué?", 1),
        ("¿Cuándo fue la primera vez que fuiste al cine?", 1),
        ("¿Cuándo fue la primera vez que alguien te leyó un cuento antes de dormir?", 1),
        ("¿Cuál fue el primer libro que leíste por tu cuenta y te enganchó?", 1),
        ("¿Cuándo fue la primera vez que viste a un músico en vivo y te voló la cabeza?", 1),
        ("¿Cuál era la canción que más pedías que te cantaran de chico?", 1),
        ("¿Cuándo fue la primera vez que intentaste hacer algo artístico y te sorprendiste?", 1),
        ("¿Cuál era tu personaje favorito de historieta o cómic?", 1),
        ("¿Cuándo fue la primera vez que una obra de arte —canción, libro, película— te hizo llorar?", 1),
        ("¿Cuándo fue la primera vez que dibujaste o pintaste algo que te gustó?", 1),
        ("¿Cuándo fue la primera vez que fuiste al teatro o a ver un espectáculo en vivo?", 1),
        ("¿Cuál fue la primera película que elegiste alquilar o ver vos solo?", 1),
        ("¿Cuándo fue la primera vez que te quedaste despierto leyendo hasta tarde?", 1),
        ("¿Cuál era el álbum o casete que más escuchabas de chico?", 1),
        ("¿Cuándo fue la primera vez que bailaste frente a otros?", 1),
        ("¿Cuándo fue la primera vez que escuchaste una canción y pensaste que era perfecta?", 1),
        ("¿Cuál fue la primera serie o programa que miraste de corrido?", 1),
        ("¿Cuándo fue la primera vez que intentaste tocar un instrumento?", 1),
        ("¿Cuándo fue la primera vez que un libro te cambió la forma de ver algo?", 1),
        ("¿Cuál fue el primer recital o show en vivo al que fuiste?", 1),
        ("¿Cuándo fue la primera vez que te emocionó una banda de sonido de película?", 1),
        ("¿Cuál fue la primera obra de teatro que viste y qué recordás de ella?", 1),
        ("¿Hay algún personaje de ficción de tu infancia con quien te identificabas profundamente?", 2),
        ("¿Cuándo fue la primera vez que un libro o película te hizo pensar diferente sobre el mundo?", 2),
        ("¿Hay alguna canción de tu infancia que todavía te dispara un recuerdo muy fuerte?", 2),
        ("¿Cuándo fue la primera vez que el arte te ayudó a procesar algo difícil?", 2),
        ("¿Cuál fue la primera historia —libro, película, serie— que te mostró un mundo distinto al tuyo?", 2),
        ("¿Cuándo fue la primera vez que sentiste que una canción era tuya, que te describía?", 2),
        ("¿Hay alguna película de tu infancia que ahora de grande la ves distinto?", 2),
        ("¿Cuándo fue la primera vez que el arte te hizo sentir menos solo?", 2),
        ("¿Cuándo fue la primera vez que compartiste algo artístico con alguien y los unió?", 2),
        ("¿Hay algún libro o historia de tu infancia que todavía te resuena hoy?", 2),
        ("¿Cuándo fue la primera vez que la música te ayudó a entender lo que sentías?", 3),
        ("¿Hay alguna historia —libro, película, canción— de tu infancia que sientas que te formó como persona?", 3),
        ("¿Cuándo fue la primera vez que el arte te dio un espacio seguro cuando no lo encontrabas en otra parte?", 3),
        ("¿Hay algún personaje de ficción que hayas amado tanto que su pérdida —al terminar el libro o la serie— te dolió de verdad?", 3),
        ("¿Cuándo fue la primera vez que una obra de arte te hizo enfrentar algo de vos mismo que preferías no ver?", 3),
        ("¿Hay alguna canción o película de tu infancia que sientas que guarda la esencia de quién fuiste?", 3),
    ],

    "futuro": [
        ("¿Qué tipo de música escuchás cuando querés imaginar cómo va a ser tu futuro?", 1),
        ("¿Cuándo fue la última vez que una película te hizo replantearte lo que querés para tu vida?", 1),
        ("¿Cuándo fue la última vez que un libro te dio una idea sobre hacia dónde querés ir?", 1),
        ("¿Cuándo fue la última vez que una obra de arte te inspiró a hacer algo concreto?", 1),
        ("¿Cuándo fue la última vez que la música te puso en modo 'todo es posible'?", 1),
        ("¿Cuándo fue la última vez que una historia de ficción te hizo ver tu propia historia de otro modo?", 1),
        ("¿Cuándo fue la última vez que te imaginaste viviendo en el mundo de una película o libro?", 1),
        ("¿Cuándo fue la última vez que una canción te motivó a tomar una decisión?", 1),
        ("¿Cuándo fue la última vez que una serie te hizo pensar en lo que querés hacer con tu tiempo?", 1),
        ("¿Cuándo fue la última vez que el arte te recordó que la vida puede ser más interesante de lo que parece?", 1),
        ("¿Cuándo fue la última vez que viste una película del futuro y te emocionó en lugar de asustarte?", 1),
        ("¿Cuándo fue la última vez que la música te abrió una puerta mental que no sabías que tenías cerrada?", 1),
        ("¿Cuándo fue la última vez que un libro te mostró un camino de vida que nunca habías considerado?", 1),
        ("¿Cuándo fue la última vez que el arte te hizo querer ser una mejor versión de vos mismo?", 1),
        ("¿Cuándo fue la última vez que una obra te hizo sentir que el futuro vale la pena?", 1),
        ("¿Cuándo fue la última vez que te imaginaste con más tiempo libre para crear algo?", 1),
        ("¿Cuándo fue la última vez que escuchaste una canción y pensaste 'esto va a sonar en un momento importante de mi vida'?", 1),
        ("¿Cuándo fue la última vez que una historia de ficción te ayudó a imaginar una vida distinta para vos?", 1),
        ("¿Cuándo fue la última vez que el arte te hizo confiar en el futuro?", 1),
        ("¿Cuándo fue la última vez que una obra te hizo querer aprender algo nuevo?", 1),
        ("¿Cuándo fue la última vez que la cultura que consumís —música, libros, películas— te marcó un norte?", 1),
        ("¿Cuándo fue la última vez que te imaginaste más creativo en el futuro?", 1),
        ("¿Cuándo fue la última vez que un artista te inspiró a pensar distinto sobre lo que podés hacer?", 1),
        ("¿Cuándo fue la última vez que la ficción te dio más esperanza sobre el futuro que las noticias?", 1),
        ("¿Cuándo fue la última vez que una canción o libro te ayudó a visualizar un futuro que realmente querías?", 2),
        ("¿Hay alguna historia —libro, serie, película— que te haya dado un marco mental para pensar en tu futuro?", 2),
        ("¿Cuándo fue la última vez que el arte te sacó de la ansiedad del futuro y te hizo vivir el presente?", 2),
        ("¿Cuándo fue la última vez que te preguntaste qué tipo de legado creativo, si alguno, querés dejar?", 2),
        ("¿Cuándo fue la última vez que una obra de arte te hizo plantearte si estás viviendo la vida que realmente querés?", 2),
        ("¿Cuándo fue la última vez que la música te ayudó a conectar con una versión de vos del futuro?", 2),
        ("¿Hay algún artista o creador que te inspire tanto que te hace querer cambiar algo en tu vida?", 2),
        ("¿Cuándo fue la última vez que una historia de ficción te hizo pensar qué clase de persona querés ser?", 2),
        ("¿Cuándo fue la última vez que sentiste que el arte te mostró que tu futuro puede ser más amplio de lo que creías?", 2),
        ("¿Cuándo fue la última vez que una obra te hizo querer arriesgar algo en tu vida real?", 2),
        ("¿Cuándo fue la última vez que una canción o libro te acompañó en un momento de redefinir tu camino?", 3),
        ("¿Hay alguna obra de arte —libro, película, música— que sientas que cambió para siempre hacia dónde vas?", 3),
        ("¿Cuándo fue la última vez que el arte te dio el coraje para tomar una decisión de vida que tenías pendiente?", 3),
        ("¿Cuándo fue la última vez que imaginarte creando algo —aunque sea pequeño— te llenó de esperanza sobre el futuro?", 3),
        ("¿Hay alguna historia que hayas consumido y que haya redefinido lo que significa una buena vida para vos?", 3),
        ("¿Cuándo fue la última vez que sentiste que el arte era la única cosa que de verdad te decía la verdad sobre tu futuro?", 3),
    ],

    "amor": [
        ("¿Cuándo fue la última vez que compartiste una canción con alguien y sintiste que lo decía todo?", 1),
        ("¿Cuándo fue la última vez que una película romántica te hizo creer más en el amor?", 1),
        ("¿Cuándo fue la última vez que escuchaste una canción y pensaste inmediatamente en alguien?", 1),
        ("¿Cuándo fue la última vez que le mandaste una canción a alguien como forma de decirle algo?", 1),
        ("¿Cuándo fue la última vez que una película te recordó a una relación que tuviste?", 1),
        ("¿Cuándo fue la última vez que bailaste con alguien y sintiste que el tiempo se detuvo?", 1),
        ("¿Cuándo fue la última vez que un libro o serie te hizo replantearte lo que buscás en una pareja?", 1),
        ("¿Cuándo fue la última vez que una canción te acompañó en un momento romántico?", 1),
        ("¿Cuándo fue la última vez que te gustó alguien que tenía un gusto musical muy diferente al tuyo?", 1),
        ("¿Cuándo fue la última vez que compartiste una película con alguien y la disfrutaron más juntos que solos?", 1),
        ("¿Cuándo fue la última vez que el gusto cultural de alguien —sus libros, su música, sus películas— te atrajo?", 1),
        ("¿Cuándo fue la última vez que una canción capturó algo que sentías por alguien mejor de lo que vos podías expresarlo?", 1),
        ("¿Cuándo fue la última vez que un libro te hizo entender mejor cómo amás?", 1),
        ("¿Cuándo fue la última vez que descubriste algo nuevo —música, cine, libros— gracias a una persona que te gustaba?", 1),
        ("¿Cuándo fue la última vez que una escena de película te pareció que describía perfectamente algo de tu vida amorosa?", 1),
        ("¿Cuándo fue la última vez que escuchaste una canción y pensaste que era la banda de sonido perfecta para un momento con alguien?", 1),
        ("¿Cuándo fue la última vez que viste una película con alguien y al terminar ninguno quería hablar porque todo estaba dicho?", 1),
        ("¿Cuándo fue la última vez que una canción te acompañó mientras esperabas a alguien?", 1),
        ("¿Cuándo fue la última vez que compartir algo cultural —un libro, una canción, una película— fue el primer momento de conexión real con alguien?", 1),
        ("¿Cuándo fue la última vez que le recomendaste un libro o película a alguien que te gustaba?", 1),
        ("¿Cuándo fue la última vez que una canción o película te ayudó a entender lo que sentías en una relación?", 1),
        ("¿Cuándo fue la última vez que el arte fue el idioma en el que le dijiste algo a alguien que de otro modo no podías decir?", 1),
        ("¿Cuándo fue la última vez que descubriste a través del arte que seguías enamorado —o que ya no lo estabas?", 1),
        ("¿Cuándo fue la última vez que una canción te hizo extrañar a alguien con una intensidad que no esperabas?", 1),
        ("¿Cuándo fue la última vez que el arte fue el puente para acercarte a alguien con quien las palabras no alcanzaban?", 2),
        ("¿Hay alguna canción que sienta que define una relación tuya —pasada o presente— mejor que cualquier descripción?", 2),
        ("¿Cuándo fue la última vez que compartir un libro o película con alguien profundizó lo que sentían el uno por el otro?", 2),
        ("¿Cuándo fue la última vez que el arte te hizo más valiente para amar?", 2),
        ("¿Hay alguna historia de amor —en un libro, película, serie— que te haya enseñado algo sobre cómo amás vos?", 2),
        ("¿Cuándo fue la última vez que una canción te ayudó a procesar el final de algo con alguien?", 2),
        ("¿Cuándo fue la última vez que el arte te hizo ver a alguien que amás de una manera completamente nueva?", 2),
        ("¿Cuándo fue la última vez que compartir tu mundo cultural con alguien fue un acto de vulnerabilidad?", 2),
        ("¿Cuándo fue la última vez que el arte te ayudó a perdonar a alguien o a perdonarte a vos mismo en el amor?", 2),
        ("¿Cuándo fue la última vez que una canción o película te ayudó a encontrar las palabras para decirle algo importante a alguien?", 2),
        ("¿Cuándo fue la última vez que la música o el cine te ayudó a abrir el corazón cuando lo tenías cerrado?", 3),
        ("¿Hay alguna canción que sienta que es tan tuya y de alguien que amaste que no podés escucharla sin que te mueva algo profundo?", 3),
        ("¿Cuándo fue la última vez que el arte te salvó en el amor —te dio esperanza, te acompañó en el duelo, o te mostró lo que necesitabas ver?", 3),
        ("¿Cuándo fue la última vez que sentiste que el arte decía la verdad sobre el amor mejor de lo que cualquier persona podría decírtela?", 3),
        ("¿Hay alguna obra —libro, canción, película— que hayas compartido con alguien que haya marcado para siempre esa relación?", 3),
        ("¿Cuándo fue la última vez que el arte te mostró que sos capaz de amar de una manera que no sabías que podías?", 3),
    ],

    "familia": [
        ("¿Cuándo fue la última vez que compartiste una canción con tu familia que a todos les gustó?", 1),
        ("¿Cuál es la película que tu familia vio tantas veces que todos se la saben de memoria?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te recomendó algo —libro, película, canción— que te encantó?", 1),
        ("¿Cuándo fue la última vez que viste una película con tu familia y después estuvieron hablando horas?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te descubrió algo cultural nuevo?", 1),
        ("¿Cuándo fue la última vez que en tu familia discutieron apasionadamente sobre una película o libro?", 1),
        ("¿Cuándo fue la última vez que escuchaste música que tenía tu familia en casa y la disfrutaste vos también?", 1),
        ("¿Cuándo fue la última vez que viste a alguien de tu familia emocionarse con una canción?", 1),
        ("¿Cuándo fue la última vez que una película o libro le dio tema de conversación a tu familia para toda una tarde?", 1),
        ("¿Cuándo fue la última vez que algún miembro de tu familia te recomendó algo que cambió cómo pensabas sobre algo?", 1),
        ("¿Cuándo fue la última vez que compartiste algo que te gustaba —música, película, libro— con un familiar y lo sorprendiste?", 1),
        ("¿Cuándo fue la última vez que la música fue el fondo sonoro de un momento familiar importante?", 1),
        ("¿Hay alguna canción que siempre escuchaban en casa y que todavía te hace sentir en familia cuando la oís?", 1),
        ("¿Cuándo fue la última vez que una película logró reunir a toda tu familia a verla junta?", 1),
        ("¿Cuándo fue la última vez que alguien de tu familia te sorprendió con un gusto cultural que no esperabas?", 1),
        ("¿Cuándo fue la última vez que la cultura que consumías te hizo entender algo de tu familia que antes no entendías?", 1),
        ("¿Cuándo fue la última vez que viste una obra, película o escuchaste algo y pensaste 'tengo que mostrárselo a mi familia'?", 1),
        ("¿Cuándo fue la última vez que el arte fue el idioma a través del cual te conectaste con alguien de tu familia?", 1),
        ("¿Cuándo fue la última vez que compartiste un libro con alguien de tu familia y después hablaron de él?", 1),
        ("¿Cuándo fue la última vez que la música de tu infancia familiar apareció en un momento y te llenó de nostalgia?", 1),
        ("¿Cuándo fue la última vez que ver una película con tu familia te hizo ver algo de ellos que no habías visto antes?", 1),
        ("¿Cuándo fue la última vez que el arte fue puente entre vos y algún familiar con quien era difícil conectar?", 1),
        ("¿Cuándo fue la última vez que una canción te trajo de golpe el recuerdo de un momento familiar?", 1),
        ("¿Cuándo fue la última vez que lo que escuchabas o leías te acercó más a alguien de tu familia?", 1),
        ("¿Hay alguna película o canción que sienta que representa algo esencial del alma de tu familia?", 2),
        ("¿Cuándo fue la última vez que el arte fue la manera más honesta en que alguien de tu familia te expresó algo?", 2),
        ("¿Hay algún libro o historia que hayas compartido con un familiar que los unió de una manera que las palabras solas no hubieran logrado?", 2),
        ("¿Cuándo fue la última vez que notaste que los gustos culturales de tu familia —lo que ven, lo que escuchan— te formaron sin que te dieras cuenta?", 2),
        ("¿Cuándo fue la última vez que el arte te ayudó a entender la historia de tu familia?", 2),
        ("¿Cuándo fue la última vez que una canción o película te hizo extrañar a alguien de tu familia con toda la fuerza?", 2),
        ("¿Cuándo fue la última vez que el arte fue el espacio donde vos y tu familia pudieron estar juntos sin tensiones?", 2),
        ("¿Cuándo fue la última vez que un libro, una película o una canción te ayudó a perdonar a alguien de tu familia?", 2),
        ("¿Hay alguna obra que hayas consumido y que te haya dado un nuevo lente para ver a tus padres o hermanos?", 2),
        ("¿Cuándo fue la última vez que sentiste que la cultura que compartís con tu familia es parte de quién sos?", 2),
        ("¿Cuándo fue la última vez que el arte te ayudó a procesar algo difícil de tu historia familiar?", 3),
        ("¿Hay alguna canción o película que sientas que guarda la esencia de lo que significó tu familia para vos?", 3),
        ("¿Cuándo fue la última vez que el arte te hizo ver a tus padres —o a quien te crió— con una compasión que antes no tenías?", 3),
        ("¿Hay alguna historia de ficción que te haya ayudado a entender tu familia mejor de lo que lo hubiera hecho cualquier conversación directa?", 3),
        ("¿Cuándo fue la última vez que una obra de arte te ayudó a sanar algo de tu historia familiar?", 3),
        ("¿Hay alguna canción, libro o película que sientas que es el legado más honesto que tu familia te dejó?", 3),
    ],

    "amistades": [
        ("¿Cuándo fue la última vez que descubriste una canción increíble gracias a un amigo?", 1),
        ("¿Cuándo fue la última vez que viste una película con amigos y fue mucho mejor que haberla visto solo?", 1),
        ("¿Cuándo fue la última vez que un amigo te recomendó un libro que te cambió algo?", 1),
        ("¿Cuándo fue la última vez que compartiste música con un grupo de amigos y todos la pegaron?", 1),
        ("¿Cuándo fue la última vez que discutiste sobre una película con amigos y la discusión fue más entretenida que la peli?", 1),
        ("¿Cuándo fue la última vez que fuiste a un recital o show con amigos y fue una de esas noches?", 1),
        ("¿Cuándo fue la última vez que un amigo te llevó a ver algo —teatro, expo, cine— que no hubieras elegido vos solo?", 1),
        ("¿Cuándo fue la última vez que te reíste con amigos de algo de la cultura popular que compartían?", 1),
        ("¿Cuándo fue la última vez que vos y tus amigos tuvieron un inside joke basado en una película o serie?", 1),
        ("¿Cuándo fue la última vez que una canción se convirtió en el himno de un grupo de amigos?", 1),
        ("¿Cuándo fue la última vez que compartir una experiencia cultural con amigos los unió más?", 1),
        ("¿Cuándo fue la última vez que vos fuiste el que le descubrió algo a un amigo?", 1),
        ("¿Cuándo fue la última vez que una canción te hizo acordar de un momento con amigos?", 1),
        ("¿Cuándo fue la última vez que viste algo con un amigo y los dos se quedaron en silencio porque no había nada que decir?", 1),
        ("¿Cuándo fue la última vez que la música fue el fondo de una noche increíble con amigos?", 1),
        ("¿Cuándo fue la última vez que alguien de tu grupo musical te influyó sin que te dieras cuenta?", 1),
        ("¿Cuándo fue la última vez que vos y un amigo vieron algo simultáneamente aunque estuvieran en lugares distintos?", 1),
        ("¿Cuándo fue la última vez que una experiencia cultural compartida con amigos se volvió un recuerdo permanente?", 1),
        ("¿Cuándo fue la última vez que un amigo te hizo ver algo artístico que te cambió la forma de ver el mundo?", 1),
        ("¿Cuándo fue la última vez que le recomendaste algo —música, película, libro— a un amigo y terminó siendo su favorito?", 1),
        ("¿Cuándo fue la última vez que compartís con un amigo un gusto cultural tan específico que saben que nadie más los entendería?", 1),
        ("¿Cuándo fue la última vez que bailaron juntos como si nadie los estuviera mirando?", 1),
        ("¿Cuándo fue la última vez que la música fue el puente que unió a personas que no se conocían y se volvieron amigos?", 1),
        ("¿Cuándo fue la última vez que lo que escuchabas o veías con amigos definió quiénes eran como grupo?", 1),
        ("¿Hay algún libro, canción o película que solo vos y un amigo muy cercano entiendan de la manera que lo entienden?", 2),
        ("¿Cuándo fue la última vez que el arte fue el espacio donde vos y un amigo pudieron hablar de algo que de otro modo no hubieran podido?", 2),
        ("¿Cuándo fue la última vez que compartir algo cultural con un amigo profundizó su amistad de una manera que no esperabas?", 2),
        ("¿Hay alguna experiencia cultural compartida con amigos que sientas que los marcó a todos de alguna manera?", 2),
        ("¿Cuándo fue la última vez que un amigo te mostró algo artístico que te hizo ver la vida un poco diferente?", 2),
        ("¿Cuándo fue la última vez que la música o el arte fue el lenguaje en el que alguien te dijo que te quería?", 2),
        ("¿Cuándo fue la última vez que el arte fue el espacio más honesto dentro de una amistad?", 2),
        ("¿Cuándo fue la última vez que una experiencia cultural compartida te hizo sentir que tenías los amigos correctos?", 2),
        ("¿Cuándo fue la última vez que el arte fue el que salvó una noche difícil con amigos?", 2),
        ("¿Cuándo fue la última vez que sentiste que los gustos culturales que compartís con tus amigos son parte de tu identidad?", 2),
        ("¿Hay algún concierto, obra o película que hayas experimentado con amigos y que sientas que te formó?", 3),
        ("¿Cuándo fue la última vez que el arte fue la razón por la que te acercaste a alguien que se convirtió en un amigo importante?", 3),
        ("¿Hay alguna canción o película que sientas que guarda la esencia de una amistad que fue muy importante para vos?", 3),
        ("¿Cuándo fue la última vez que el arte te ayudó a perdonar o a sanar algo dentro de una amistad?", 3),
        ("¿Cuándo fue la última vez que sentiste que compartir algo que amás culturalmente con alguien fue un acto de confianza profunda?", 3),
        ("¿Hay alguna experiencia artística compartida con un amigo que haya sido uno de los momentos más verdaderos de tu vida?", 3),
    ],

    "exs": [
        ("¿Hay alguna canción que no podés escuchar sin que te haga acordar a alguien del pasado?", 1),
        ("¿Cuándo fue la última vez que una película te hizo acordar a alguien con quien saliste?", 1),
        ("¿Cuándo fue la última vez que alguien te descubrió una canción o artista que todavía escuchás?", 1),
        ("¿Cuándo fue la última vez que escuchaste algo que era 'la canción de alguien' y reaccionaste de una forma que no esperabas?", 1),
        ("¿Cuándo fue la última vez que una película romántica te hizo pensar en alguien del pasado?", 1),
        ("¿Hay algún género musical o artista que asociés claramente con una relación pasada?", 1),
        ("¿Cuándo fue la última vez que fuiste al cine o a ver un espectáculo solo porque antes ibas con alguien?", 1),
        ("¿Cuándo fue la última vez que una canción te ayudó a procesar una ruptura?", 1),
        ("¿Cuándo fue la última vez que descubriste una peli o libro que le hubiera encantado a alguien del pasado y sentiste algo?", 1),
        ("¿Cuándo fue la última vez que te diste cuenta de que un gusto cultural te lo había dejado alguien con quien saliste?", 1),
        ("¿Hay algún lugar al que ibas a ver música o cine con alguien que ahora visitás diferente?", 1),
        ("¿Cuándo fue la última vez que bailaste una canción que compartiste con alguien del pasado?", 1),
        ("¿Cuándo fue la última vez que la música te ayudó a soltar a alguien?", 1),
        ("¿Cuándo fue la última vez que reescuchaste un playlist que alguien te armó y lo hiciste sin culpa?", 1),
        ("¿Cuándo fue la última vez que una escena de una película te pegó porque era demasiado parecida a algo que viviste?", 1),
        ("¿Cuándo fue la última vez que te dio satisfacción escuchar algo nuevo que te rompía el molde de lo que habías escuchado con alguien?", 1),
        ("¿Cuándo fue la última vez que encontraste un libro o película que alguien del pasado te había recomendado y lo dejaste para otro momento?", 1),
        ("¿Cuándo fue la última vez que la música te ayudó a entender lo que sentiste en una relación mejor de lo que podías articularlo con palabras?", 1),
        ("¿Cuándo fue la última vez que te llegó una canción nueva que le hubiera mandado de inmediato a alguien si las cosas fueran distintas?", 1),
        ("¿Cuándo fue la última vez que te reíste de lo que escuchabas o veías con alguien del pasado porque ahora todo parecía un cliché?", 1),
        ("¿Cuándo fue la última vez que una canción o película te hizo procesar algo de una relación pasada que creías tener superado?", 1),
        ("¿Cuándo fue la última vez que el arte fue más honesto sobre lo que sentías en una relación de lo que vos podías serlo?", 1),
        ("¿Cuándo fue la última vez que la música te ayudó a recordar a alguien con cariño en lugar de con dolor?", 1),
        ("¿Cuándo fue la última vez que algo artístico que compartiste con alguien te dio gratitud por haberlo vivido, aunque ya no estuvieran?", 1),
        ("¿Hay alguna canción o película que sientas que captura perfectamente lo que fue una relación pasada —sin juzgar, solo retratando?", 2),
        ("¿Cuándo fue la última vez que el arte te ayudó a perdonar a alguien del pasado amoroso?", 2),
        ("¿Cuándo fue la última vez que una canción o película te hizo ver una relación pasada desde un lugar más compasivo hacia vos mismo?", 2),
        ("¿Hay algún gusto cultural —música, cine, libros— que hayas adquirido en una relación y que sientas que es genuinamente tuyo ahora?", 2),
        ("¿Cuándo fue la última vez que el arte fue el espacio donde pudo existir algo de una relación que en la realidad ya no podía?", 2),
        ("¿Cuándo fue la última vez que una canción te hizo darte cuenta de que ya sanaste de algo que creías que nunca ibas a sanar?", 2),
        ("¿Cuándo fue la última vez que el arte te ayudó a entender mejor por qué una relación funcionó —o por qué no?", 2),
        ("¿Cuándo fue la última vez que te permitiste disfrutar algo artístico que compartías con alguien, sin que eso significara nada más?", 2),
        ("¿Cuándo fue la última vez que una canción te mostró que lo que sentiste fue real, aunque la relación haya terminado?", 2),
        ("¿Cuándo fue la última vez que el arte te dio un cierre que la relación nunca te dio?", 2),
        ("¿Cuándo fue la última vez que una canción te ayudó a honrar algo de una relación pasada sin romantizarla?", 3),
        ("¿Hay alguna obra artística —canción, película, libro— que sientas que guarda lo mejor de lo que viviste con alguien?", 3),
        ("¿Cuándo fue la última vez que el arte te hizo enfrentar algo de vos mismo que una relación pasada había revelado?", 3),
        ("¿Cuándo fue la última vez que la música o el arte te dio el espacio para sentir todo lo que no pudiste sentir mientras estabas en la relación?", 3),
        ("¿Hay alguna canción o historia que sientas que sos capaz de escuchar o ver ahora que antes no podías, y que eso es señal de que sanaste algo?", 3),
        ("¿Cuándo fue la última vez que el arte te hizo agradecer lo que viviste con alguien, aunque haya dolido el final?", 3),
    ],

    "personalidad": [
        ("¿Cuándo fue la última vez que una canción capturó exactamente cómo sos?", 1),
        ("¿Cuándo fue la última vez que alguien te conoció mejor a través de lo que escuchás o leés?", 1),
        ("¿Cuándo fue la última vez que te sentiste más vos mismo escuchando música?", 1),
        ("¿Cuándo fue la última vez que una película te hizo reír de algo de vos mismo?", 1),
        ("¿Cuándo fue la última vez que un personaje de ficción te representó de manera incómoda pero honesta?", 1),
        ("¿Cuándo fue la última vez que encontraste una canción que sentiste que nadie más que vos hubiera podido conectar así?", 1),
        ("¿Cuándo fue la última vez que un libro te hizo sentir que alguien te entendía sin conocerte?", 1),
        ("¿Cuándo fue la última vez que tus gustos culturales dijeron algo de vos que vos no habías podido decir?", 1),
        ("¿Cuándo fue la última vez que una obra de arte te dio el vocabulario para entender algo de vos mismo?", 1),
        ("¿Cuándo fue la última vez que te reíste de un personaje porque era exactamente algo que vos hacés?", 1),
        ("¿Cuándo fue la última vez que tu lista de reproducción o tus libros favoritos te revelaron algo que no sabías de vos mismo?", 1),
        ("¿Cuándo fue la última vez que el arte fue más honesto sobre quién sos que cualquier conversación?", 1),
        ("¿Cuándo fue la última vez que encontraste un artista y sentiste que pensaba como vos?", 1),
        ("¿Cuándo fue la última vez que una película o serie te hizo ver un rasgo tuyo que te costaba admitir?", 1),
        ("¿Cuándo fue la última vez que el arte te dio el permiso de ser cómo sos?", 1),
        ("¿Cuándo fue la última vez que escuchar cierta música te hizo recordar quién sos cuando estás solo?", 1),
        ("¿Cuándo fue la última vez que descubriste algo cultural que se convirtió en una parte central de cómo te definís?", 1),
        ("¿Cuándo fue la última vez que un libro cambió algo en cómo te ves a vos mismo?", 1),
        ("¿Cuándo fue la última vez que te sorprendiste teniendo una reacción emocional muy fuerte ante una obra?", 1),
        ("¿Cuándo fue la última vez que compartiste algo cultural con alguien como un acto de mostrarte tal cual sos?", 1),
        ("¿Cuándo fue la última vez que el arte te hizo sentir que estar solo con tus pensamientos era un regalo?", 1),
        ("¿Cuándo fue la última vez que alguien entendió algo de vos solo por lo que escuchás o ves?", 1),
        ("¿Cuándo fue la última vez que el arte te hizo más curioso sobre quién sos?", 1),
        ("¿Cuándo fue la última vez que una canción te acompañó en uno de tus mejores momentos a solas?", 1),
        ("¿Cuándo fue la última vez que el arte te hizo confrontar algo de tu carácter que preferías ignorar?", 2),
        ("¿Cuándo fue la última vez que encontraste en una obra la descripción más exacta de una emoción que creías que nadie entendía?", 2),
        ("¿Cuándo fue la última vez que el arte te ayudó a aceptar una parte de vos mismo con la que tenías conflicto?", 2),
        ("¿Cuándo fue la última vez que lo que consumís culturalmente te hizo darte cuenta de cómo cambiaste?", 2),
        ("¿Cuándo fue la última vez que el arte te devolvió a una versión de vos mismo que creías haber perdido?", 2),
        ("¿Cuándo fue la última vez que una obra de arte te hizo más compasivo con vos mismo?", 2),
        ("¿Cuándo fue la última vez que el arte te dio el coraje de ser diferente sin pedir perdón?", 2),
        ("¿Cuándo fue la última vez que algo que leíste o escuchaste te ayudó a entender por qué sos como sos?", 2),
        ("¿Cuándo fue la última vez que el arte fue el espejo más honesto que tuviste?", 2),
        ("¿Cuándo fue la última vez que una obra cultural te mostró que lo que considerabas un defecto también podía ser una fortaleza?", 2),
        ("¿Cuándo fue la última vez que el arte te ayudó a integrar algo de vos mismo que veías como fragmentado?", 3),
        ("¿Hay alguna obra —canción, libro, película— que sientas que te conoce mejor de lo que vos mismo te conocés?", 3),
        ("¿Cuándo fue la última vez que el arte te hizo sentir que no tenés que justificar quién sos?", 3),
        ("¿Cuándo fue la última vez que el arte te mostró que la persona que sos hoy tiene sentido, aunque el camino parezca raro desde afuera?", 3),
        ("¿Cuándo fue la última vez que el arte fue el único espacio donde podías ser completamente vos sin ningún filtro?", 3),
        ("¿Hay alguna obra que sientas que guarda la esencia de quién sos en este momento de tu vida, de una manera que no encontrás en ninguna otra parte?", 3),
    ],

    "miedos": [
        ("¿Cuándo fue la última vez que una película de terror te asustó de verdad?", 1),
        ("¿Cuándo fue la última vez que un libro de suspenso te puso nervioso en serio?", 1),
        ("¿Cuándo fue la última vez que una canción te generó una sensación de angustia que no esperabas?", 1),
        ("¿Cuándo fue la última vez que algo en una película de terror te pareció más realista que fantástico?", 1),
        ("¿Cuándo fue la última vez que miraste una película de terror solo y te arrepentiste?", 1),
        ("¿Cuándo fue la última vez que el suspenso de una historia te mantuvo despierto más de lo que querías?", 1),
        ("¿Cuándo fue la última vez que una película de terror te hizo reflexionar sobre algo que te aterra en la vida real?", 1),
        ("¿Cuándo fue la última vez que una obra de ficción amplificó un miedo que ya tenías?", 1),
        ("¿Cuándo fue la última vez que la música te generó una sensación de inquietud que fue placentera?", 1),
        ("¿Cuándo fue la última vez que viste algo —película, serie, documental— que te perturbó sin que pudieras explicar bien por qué?", 1),
        ("¿Cuándo fue la última vez que una película de terror te hizo replantearte algo que creías sin miedo?", 1),
        ("¿Cuándo fue la última vez que encontraste un libro de no ficción más aterrador que cualquier película de terror?", 1),
        ("¿Cuándo fue la última vez que algo que viste o leíste te generó pesadillas?", 1),
        ("¿Cuándo fue la última vez que disfrutaste el miedo controlado de una historia de terror?", 1),
        ("¿Cuándo fue la última vez que una obra de ficción te ayudó a entender un miedo que en la vida real no podías nombrar?", 1),
        ("¿Cuándo fue la última vez que la música te ayudó a calmarte cuando tenías miedo de algo?", 1),
        ("¿Cuándo fue la última vez que viste algo que al principio te dio miedo y después te dio ganas de verlo de nuevo?", 1),
        ("¿Cuándo fue la última vez que una obra artística te hizo enfrentar algo que te aterraba de manera más segura que en la vida real?", 1),
        ("¿Cuándo fue la última vez que el arte fue el espacio donde pudiste explorar un miedo sin consecuencias?", 1),
        ("¿Cuándo fue la última vez que un documental te asustó más que cualquier ficción?", 1),
        ("¿Cuándo fue la última vez que el arte te hizo más valiente frente a un miedo?", 1),
        ("¿Cuándo fue la última vez que la música te sacó de un espiral de miedo?", 1),
        ("¿Cuándo fue la última vez que una historia de terror te ayudó a procesar algo que te daba miedo en la vida real?", 1),
        ("¿Cuándo fue la última vez que la ficción te permitió sentir un miedo de manera segura y saliste mejor de eso?", 1),
        ("¿Hay alguna obra de arte —película, libro, canción— que haya nombrado un miedo tuyo que no habías podido articular antes?", 2),
        ("¿Cuándo fue la última vez que el arte te ayudó a comprender de dónde venía uno de tus miedos?", 2),
        ("¿Cuándo fue la última vez que una historia te enseñó algo sobre cómo enfrentar algo que te asustaba?", 2),
        ("¿Hay alguna película o libro que te haya dado una perspectiva nueva sobre algo que te genera mucho miedo?", 2),
        ("¿Cuándo fue la última vez que una obra artística te hizo ver que un miedo tuyo era compartido y eso te alivió?", 2),
        ("¿Cuándo fue la última vez que la música te ayudó a atravesar un momento de mucho miedo?", 2),
        ("¿Cuándo fue la última vez que el arte te hizo sentir que sos capaz de vivir con tus miedos en lugar de huir de ellos?", 2),
        ("¿Cuándo fue la última vez que una historia te mostró que el miedo podía coexistir con el coraje?", 2),
        ("¿Cuándo fue la última vez que el arte te ofreció un lugar seguro para explorar lo que más te asustaba?", 2),
        ("¿Cuándo fue la última vez que una obra te hizo darte cuenta de que lo que más te asustaba era también lo que más te importaba?", 2),
        ("¿Hay alguna obra de arte que sientas que te mostró la cara de tu miedo más profundo de una manera que te ayudó a entenderlo?", 3),
        ("¿Cuándo fue la última vez que el arte te ayudó a pararte frente a un miedo existencial sin evadirlo?", 3),
        ("¿Cuándo fue la última vez que una canción o historia te hizo ver que el miedo también podía ser una señal de que algo te importaba de verdad?", 3),
        ("¿Cuándo fue la última vez que el arte te hizo sentir que tus miedos más oscuros no te definían?", 3),
        ("¿Hay alguna obra que hayas consumido y que haya cambiado permanentemente cómo te relacionás con algo que te daba miedo?", 3),
        ("¿Cuándo fue la última vez que el arte te dio el coraje de mirar de frente lo que más te asusta de vos mismo?", 3),
    ],

    "logros": [
        ("¿Cuándo fue la última vez que escuchaste una canción que sentiste que era el soundtrack de algo que lograste?", 1),
        ("¿Cuándo fue la última vez que una película te inspiró a ir a buscar algo que querías?", 1),
        ("¿Cuándo fue la última vez que un libro te dio herramientas para lograr algo que no sabías cómo hacer?", 1),
        ("¿Cuándo fue la última vez que el arte te recordó por qué vale la pena esforzarse?", 1),
        ("¿Cuándo fue la última vez que la música te acompañó en el camino hacia algo que querías lograr?", 1),
        ("¿Cuándo fue la última vez que una historia de superación —en película, libro o documental— te motivó genuinamente?", 1),
        ("¿Cuándo fue la última vez que un artista te inspiró a ser más disciplinado o persistente?", 1),
        ("¿Cuándo fue la última vez que una canción te dio energía en un momento en que la necesitabas para seguir?", 1),
        ("¿Cuándo fue la última vez que una película biográfica te hizo creer más en lo que podés hacer?", 1),
        ("¿Cuándo fue la última vez que una obra de arte validó un logro tuyo que no sabías cómo valorar?", 1),
        ("¿Cuándo fue la última vez que el arte te recordó que la creatividad es en sí misma un logro?", 1),
        ("¿Cuándo fue la última vez que escuchaste la historia de alguien en una canción o película y te hizo querer hacer algo más grande?", 1),
        ("¿Cuándo fue la última vez que terminaste algo largo —un libro, una serie— y lo sentiste como un logro?", 1),
        ("¿Cuándo fue la última vez que la música fue parte de la celebración de algo que lograste?", 1),
        ("¿Cuándo fue la última vez que una obra te mostró que el proceso también es parte del logro?", 1),
        ("¿Cuándo fue la última vez que te inspiraste en alguien del mundo del arte o la cultura para hacer algo concreto?", 1),
        ("¿Cuándo fue la última vez que el arte fue parte de algo que lograste crear vos mismo?", 1),
        ("¿Cuándo fue la última vez que escuchar música mientras trabajabas en algo te hizo rendir más?", 1),
        ("¿Cuándo fue la última vez que te propusiste ver, leer o escuchar más sobre algo y lo cumpliste?", 1),
        ("¿Cuándo fue la última vez que una historia de alguien que fracasó y siguió adelante te enseñó más que una historia de éxito?", 1),
        ("¿Cuándo fue la última vez que el arte te hizo querer dejar algo tuyo en el mundo?", 1),
        ("¿Cuándo fue la última vez que una canción te acompañó en un momento en que te sentiste orgulloso de algo?", 1),
        ("¿Cuándo fue la última vez que el arte te hizo sentir que sos capaz de más de lo que creías?", 1),
        ("¿Cuándo fue la última vez que terminaste algo difícil y lo primero que hiciste fue poner música?", 1),
        ("¿Cuándo fue la última vez que el arte te mostró que un logro no tiene que ser reconocido por los demás para ser real?", 2),
        ("¿Cuándo fue la última vez que una historia te enseñó algo sobre cómo llevar un fracaso y seguir construyendo?", 2),
        ("¿Cuándo fue la última vez que el arte te hizo redefinir lo que significa para vos haber logrado algo?", 2),
        ("¿Cuándo fue la última vez que te inspiraste en un artista para intentar algo que te parecía demasiado difícil?", 2),
        ("¿Cuándo fue la última vez que el arte te ayudó a apreciar algo que habías logrado y que estabas minimizando?", 2),
        ("¿Cuándo fue la última vez que una obra te recordó que el legado más importante que podés dejar es el que no se mide con métricas?", 2),
        ("¿Cuándo fue la última vez que el arte te dio perspectiva sobre lo que realmente querés lograr en tu vida?", 2),
        ("¿Cuándo fue la última vez que una historia —libro, película, documental— te ayudó a entender el precio que pagó alguien por algo que logró?", 2),
        ("¿Cuándo fue la última vez que el arte te hizo conectar con lo que verdaderamente querés dejar en el mundo?", 2),
        ("¿Cuándo fue la última vez que una obra te mostró que el logro más importante puede no ser el más visible?", 2),
        ("¿Cuándo fue la última vez que el arte te mostró que lo que creás —aunque sea pequeño— tiene valor en sí mismo?", 3),
        ("¿Hay alguna obra que te haya inspirado a ir a por algo que te daba miedo intentar, y que terminaste logrando?", 3),
        ("¿Cuándo fue la última vez que el arte te recordó que el tipo de éxito que perseguís debería ser tuyo, no el de nadie más?", 3),
        ("¿Cuándo fue la última vez que una historia te hizo ver que lo que lograste tiene más profundidad de la que vos mismo le dabas?", 3),
        ("¿Cuándo fue la última vez que el arte te mostró que lo mejor que podés lograr puede ser algo interno que nadie más verá?", 3),
        ("¿Cuándo fue la última vez que crear o consumir arte fue en sí mismo uno de los logros más importantes de tu semana?", 3),
    ],

    "sinFiltro": [
        ("¿Cuándo fue la última vez que fingiste conocer una canción que nunca escuchaste para no quedar mal?", 1),
        ("¿Cuándo fue la última vez que lloraste con una película que se supone que no era para llorar?", 1),
        ("¿Cuándo fue la última vez que dijiste que habías leído un libro que nunca abriste?", 1),
        ("¿Cuándo fue la última vez que te emocionaste con una canción de mala calidad y no te lo podés explicar?", 1),
        ("¿Cuándo fue la última vez que escuchaste algo en privado que te daría vergüenza que se supiera?", 1),
        ("¿Cuándo fue la última vez que juzgaste el gusto musical de alguien y después escuchaste lo mismo a escondidas?", 1),
        ("¿Cuándo fue la última vez que cantaste a todo pulmón en el auto una canción que te avergüenza?", 1),
        ("¿Cuándo fue la última vez que miraste una serie malísima hasta el final sabiendo que era malísima?", 1),
        ("¿Cuándo fue la última vez que viste una peli de terror solo y quedaste paralizado pero no lo admitiste?", 1),
        ("¿Cuándo fue la última vez que googleaste la letra de una canción porque juraste que era otra y estabas equivocado?", 1),
        ("¿Cuándo fue la última vez que pretendiste que te gustaba algo cultural para gustarle a alguien?", 1),
        ("¿Cuándo fue la última vez que te dormiste en una película que todo el mundo dijo que era buenísima?", 1),
        ("¿Cuándo fue la última vez que escuchaste la misma canción más de 30 veces seguidas?", 1),
        ("¿Cuándo fue la última vez que hiciste spoiler de algo sin querer y te bancaste la mirada de los demás?", 1),
        ("¿Cuándo fue la última vez que te hiciste el interesante recomendando algo que en realidad no habías terminado?", 1),
        ("¿Cuándo fue la última vez que lloraste por el final de una serie como si fuera una pérdida real?", 1),
        ("¿Cuándo fue la última vez que pausaste una película en lo mejor porque no podías con la tensión?", 1),
        ("¿Cuándo fue la última vez que le mentiste a alguien sobre qué tan avanzada estabas en una serie?", 1),
        ("¿Cuándo fue la última vez que escuchaste una playlist del tipo que se supone que no va con tu estética?", 1),
        ("¿Cuándo fue la última vez que compraste un libro solo para que te vean con él?", 1),
        ("¿Cuándo fue la última vez que le diste skip a una canción que antes amabas porque ahora te la asociás con algo?", 1),
        ("¿Cuándo fue la última vez que miraste el perfil de alguien en Spotify para ver qué estaba escuchando?", 1),
        ("¿Cuándo fue la última vez que usaste una canción para crear una imagen de vos que no era del todo exacta?", 1),
        ("¿Cuándo fue la última vez que googleaste a un artista que todos conocían para poder opinar en la conversación?", 1),
        ("¿Cuándo fue la última vez que usaste el gusto cultural de alguien —su música, sus libros, sus pelis— para juzgarlo?", 2),
        ("¿Cuándo fue la última vez que te avergonzó algo que te gustaba culturalmente y lo callaste?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que tu gusto cultural dice algo de vos que preferirías que no dijera?", 2),
        ("¿Cuándo fue la última vez que te identificaste demasiado con un personaje que claramente era el malo de la historia?", 2),
        ("¿Cuándo fue la última vez que usaste una recomendación cultural como forma de flirtear y funcionó?", 2),
        ("¿Cuándo fue la última vez que el arte te hizo sentir algo que en otro contexto te daría vergüenza admitir?", 2),
        ("¿Cuándo fue la última vez que fanateaste en secreto de algo que en público criticabas?", 2),
        ("¿Cuándo fue la última vez que te diste cuenta de que una canción que amabas la habías adoptado sin darte cuenta de lo que decía la letra?", 2),
        ("¿Cuándo fue la última vez que juzgaste a alguien por lo que escucha y después te arrepentiste?", 2),
        ("¿Cuándo fue la última vez que te sorprendiste cantando en privado algo que nunca escucharías en público?", 2),
        ("¿Cuándo fue la última vez que el arte te reveló algo de vos mismo que no querías ver y lo miraste igual?", 3),
        ("¿Cuándo fue la última vez que usaste el arte como escudo para no tener que hablar de lo que realmente sentías?", 3),
        ("¿Cuándo fue la última vez que una canción, película o libro te dio acceso a una parte de vos que normalmente no mostrás?", 3),
        ("¿Cuándo fue la última vez que el arte te confrontó con algo que estabas evitando y no pudiste cerrar el libro o apagar la música?", 3),
        ("¿Cuándo fue la última vez que lo que sentiste con una obra de arte fue tan intenso que te dio miedo que alguien lo viera en tu cara?", 3),
        ("¿Cuándo fue la última vez que usaste el arte para procesar algo que no le podías decir a nadie?", 3),
    ],
}

def get_prefix(cat_id):
    return {
        "infancia": "inf", "futuro": "fut", "amor": "am", "familia": "fam",
        "amistades": "ami", "exs": "ex", "personalidad": "per",
        "miedos": "mie", "logros": "log", "sinFiltro": "sf",
    }[cat_id]

def main():
    with open("data/questions.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    for cat in data["categories"]:
        cat_id = cat["id"]
        if cat_id not in ADDITIONS11:
            continue

        prefix = get_prefix(cat_id)
        max_idx = {1: 0, 2: 0, 3: 0}
        for q in cat["questions"]:
            parts = q["id"].split("_")
            level = int(parts[1])
            idx = int(parts[2])
            if idx > max_idx[level]:
                max_idx[level] = idx

        level_counters = dict(max_idx)
        new_qs = []

        for (text, level) in ADDITIONS11[cat_id]:
            level_counters[level] += 1
            q_id = f"{prefix}_{level}_{level_counters[level]:03d}"
            new_qs.append({"id": q_id, "text": text, "level": level})

        cat["questions"].extend(new_qs)
        print(f"{cat_id}: {len(cat['questions']) - len(new_qs)} → {len(cat['questions'])} (+{len(new_qs)})")

    with open("data/questions.json", "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    total = sum(len(c["questions"]) for c in data["categories"])
    print(f"\nTotal questions: {total}")

if __name__ == "__main__":
    main()
